LibUnwind/build_tarballs.jl
Disable building of libunwind tests, makes libunwind build with musl libc.
=> Disable building of libunwind tests

Hwloc/build_tarballs.jl
Super simple, `./configure ...; make; make install` worked for all architectures on the first try.
=> Add build script for Hwloc

LibUV/build_tarballs.jl
For https://github.com/JuliaLang/julia/pull/32280
=> update libuv to 2+1.29.1-julia proposed

XML2/build_tarballs.jl
This is adapted from https://github.com/bicycle1885/XML2Builder.
=> add XML2 builder

CFITSIO/build_tarballs.jl
This is the builder for [CFITSIO](https://heasarc.gsfc.nasa.gov/fitsio/).
Originally at https://github.com/JuliaAstro/CFITSIOBuilder.
Note that this builds a new version of the library not yet present in the old builder, so a new build would be welcome :slightly_smiling_face:
=> Add builder for CFITSIO

Cuba/build_tarballs.jl
This is the builder for [Cuba](http://www.feynarts.de/cuba/) library.
Originally at https://github.com/giordano/CubaBuilder/
=> Add Cuba builder

WCSLIB/build_tarballs.jl, WCSLIB/patches/configure-mingw.patch
This is the builder for [WCSLIB](https://www.atnf.csiro.au/people/mcalabre/WCS/).  Originally at https://github.com/JuliaAstro/WCSLIBBuilder.
Note that this builds a new version of the library not yet present in the old builder, so a new build would be welcome :slightly_smiling_face:
=> Add builder for WCSLIB

E/Expat/build_tarballs.jl
Originally at https://github.com/JuliaGraphics/ExpatBuilder (upgraded to latest version).
Fix #36.
=> Add builder for Expat

C/Cairo/build_tarballs.jl, C/Cairo/bundled/patches/configure.ac.patch
I'm copying this from https://github.com/JuliaGraphics/CairoBuilder.  Note: building for all platforms works on Travis: https://travis-ci.org/JuliaGraphics/CairoBuilder/builds/576867465.
A release would be welcome :slightly_smiling_face:
=> Add builder for Cairo

X/XML2/build_tarballs.jl
I can't test it right now, but my understanding is this these are the changes necessary for the upgrade.
=> [XML2] Upgrade to new BinaryBuilder.jl

O/OpenBLAS/build_tarballs.jl
=> Use more openblas threads on 64-bit arch

X/X11/build_tarballs.jl
These are dependencies of GTK.  I tested only on `arm-linux-musleabihf`,`x86_64-unknown-freebsd11.1`,`x86_64-linux-gnu`, didn't have the time to test for all platforms.
=> [X11] Add more libraries

A/ATK/build_tarballs.jl
This is a dependency of GTK, see #62.
=> Add builder for ATK

A/adwaita-icon-theme/build_tarballs.jl
=> Add builder for adwaita-icon-theme

I/iso-codes/build_tarballs.jl
=> Add builder for iso-codes

G/Graphene/build_tarballs.jl
This is dependency of GTK, see #62
=> Add builder for Graphene

I/ImageMagick/build_tarballs.jl
Probably won't work right away?!
Swapped libjpeg with JpegTurbo...
=> Add ImageMagick

L/Libglvnd/build_tarballs.jl
Dependency of libepoxy, in turn dependency of Gtk, see #62
=> Add builder for libglvnd

L/Libepoxy/build_tarballs.jl
This is a dependency of GTK, see #62.
=> Add builder for Libepoxy

L/Lz4/build_tarballs.jl
Indirect dependency of GTK, see #62
=> Add builder for lz4

E/Elfutils/build_tarballs.jl
Not tested at all, requires a package for XZ (the builder is already here, though)
=> Add builder for elfutils

A/Arpack/build_tarballs.jl
Once https://github.com/JuliaPackaging/Yggdrasil/pull/70 is merged, we should update Arpack to use the new openblas and then merge this PR
=> Update arpack to 3.7

P/PALISADE/build_tarballs.jl
Is this right or am i not understanding this comment?
=> PALISADE is not Nettle?

P/p7zip/build_tarballs.jl
Is this right or am i not understanding this comment
=> p7zip is nott Pcre ?

Z/ZMQBuilder/build_tarballs.jl
I've verified that this works:
https://github.com/kdheepak/ZMQBuilder/releases
https://travis-ci.com/kdheepak/ZMQBuilder/builds/130858111
=> Add ZMQBuilder

G/Giflib/build_tarballs.jl
Dependency of leptonica, see #118
=> Add builder for giflib

X/XSLT/build_tarballs.jl
This is an indirect dependency of GTK, see #62
=> [XSLT] Update script to new BinaryBuilder and upgrade to latest version

0_RootFS/Glibc/build_tarballs.jl, 0_RootFS/Go/build_tarballs.jl, 0_RootFS/Musl/build_tarballs.jl, 0_RootFS/PlatformSupport/build_tarballs.jl, 0_RootFS/Rootfs/build_tarballs.jl, 0_RootFS/Rust/build_tarballs.jl, A/ATK/build_tarballs.jl, E/Elfutils/build_tarballs.jl, F/Fontconfig/build_tarballs.jl, G/Graphite2/build_tarballs.jl, H/HarfBuzz/build_tarballs.jl, L/LibVPX/build_tarballs.jl, L/Libglvnd/build_tarballs.jl, L/Libgpg_error/build_tarballs.jl, L/Libmount/build_tarballs.jl, L/Libpciaccess/build_tarballs.jl, L/Libuuid/build_tarballs.jl, L/Linux/build_tarballs.jl, L/Lz4/build_tarballs.jl, L/lm_sensors/build_tarballs.jl, N/Ncurses/build_tarballs.jl, N/Nettle/build_tarballs.jl, P/Pixman/build_tarballs.jl, Q/Qemu/build_tarballs.jl, S/SCALE_MAMBA/build_tarballs.jl, T/TVM/build_tarballs.jl, W/Wayland/build_tarballs.jl, W/Wayland_protocols/build_tarballs.jl, X/X11/build_tarballs.jl
=> Remove references to Pkg.BinaryPlatforms

A/Attr/build_tarballs.jl
Indirect dependency of GTK3, see #62
=> Add builder for attr

0_RootFS/Rootfs/build_tarballs.jl, 0_RootFS/Rootfs/bundled/conf/profile.d/bb_utils.sh, 0_RootFS/Rootfs/bundled/utils/install_license.sh
This will be executed at the end of the build script.
Ref: https://github.com/JuliaPackaging/BinaryBuilder.jl/issues/309
=> Define shell function to automatically install license files

A/adwaita_icon_theme/build_tarballs.jl, H/hicolor_icon_theme/build_tarballs.jl
<s>If I remember correctly, this doesn't produce any file, just empty directories, but if this makes Gtk happy...</s>  I stand corrected, there is exactly one file
=> Add builder for hicolor-icon-theme

S/SoftPosit/build_tarballs.jl, S/SoftPosit/bundled/patches/makefile.patch
Moved from https://github.com/giordano/SoftPositBuilder
=> Add builder for SoftPosit

X/Xorg_xkbcomp/build_tarballs.jl
Indirect dependency of GTK, see #62
=> Add builder of xkbcomp

X/Xorg_xkeyboard_config/build_tarballs.jl
Indirect dependency of GTK, see #62
=> Add builder for xkeyboard-config

S/SQLite/build_tarballs.jl
Based on https://github.com/JuliaDatabases/SQLiteBuilder/, updated to the latest SQLite release.
=> add SQLite builder

X/Xorg_libXft/build_tarballs.jl
=> Add builder for libXft

O/Ogg/build_tarballs.jl
=> Revised builder for Ogg

L/liblame/build_tarballs.jl
=> Added builder for LAME

L/libass/build_tarballs.jl
=> Added builder for libass

A/at_spi2_atk/build_tarballs.jl, A/at_spi2_atk/bundled/patches/meson_build.patch
(Hopefully) last direct dependency of GTK, see #62
=> Add builder for at-spi2-atk

L/libvorbis/build_tarballs.jl
=> added libvorbis builder

X/x264/build_tarballs.jl
=> added x264 builder

G/GTK3/build_tarballs.jl, G/GTK3/bundled/patches/gdkwindow-quartz_c.patch, G/GTK3/bundled/patches/meson_build.patch
<s>This is only a stub of the GTK3 builder and it's only for macOS.</s>  Ref #62
=> Add builder for GTK3

0_RootFS/PlatformSupport/bundled/buildsystem_toolchains/build_toolchains.sh, 0_RootFS/PlatformSupport/bundled/buildsystem_toolchains/meson.j2
This helps the linker finding libraries in lib64 directory
=> Improve link args in meson cross file for PowerPC64

F/FLAC/build_tarballs.jl
This build is untested, based on the advice from #107.
=> Add builder for FLAC

L/libsndfile/build_tarballs.jl
=> Added libsndfile builder

T/Tcl/build_tarballs.jl
With this fix I was able to build Tk for macOS
=> [Tcl] Install private headers, rename library product variable

G/Gnome_themes_extra/build_tarballs.jl
With this, I think we can say that the GTK-verse is complete.  Close #62.
=> Build gnome_themes_extra for the rest of the platforms

T/Tk/build_tarballs.jl, T/Tk/bundled/patches/configure.patch
<s>It still needs some work, in particular for macOS</s>
CC: @aviks
=> Add builder for Tk

G/Geant4/build_tarballs.jl
Geant4 is a library that simulates the transport of elementary particles through matter. It is frequently used in high energy physics, medical physics and space science.
This builder unfortunately times out on travis, but it works for me locally.
=> Add Geant4

Z/z3/build_tarballs.jl
* Package name: z3
* Version: v4.8.6
=> Wizard recipe: z3-v4.8.6

M/mpg123/build_tarballs.jl
Dependency of sdl2_mixer (#122)
=> Add builder for mpg123

L/libmodplug/build_tarballs.jl
Dependency of sdl2_mixer (#122)
=> Add builder for libmodplug

L/libwebp/build_tarballs.jl
Dependency of leptonica (see #118)
=> Add builder for libwebp

.ci/Makefile, .ci/azure_agent/start.sh, .ci/docker-compose.yml
=> Multiple agents

O/OptimPack/build_tarballs.jl
This is a new script to build [OptimPack](https://github.com/emmt/OptimPack) C libraries to be used in Julia via the [OptimPack.jl](https://github.com/emmt/OptimPack.jl) package.
=> Add script for OptimPack

azure-pipelines.yml
Let's see if this works
_Edit_: it looks like it does?
=> Move condition of building to the job instead of each step

M/MPFR/build_tarballs.jl
Fix https://github.com/JuliaBinaryWrappers/MPFR_jll.jl/issues/1
=> Retrigger build of MPFR to update JLL package

README.md
Image taken from [Wikimedia Commons](https://commons.wikimedia.org/wiki/File:Yggdrasil.jpg)
=> [skip ci] Add Yggdrasil to the README

azure-pipelines.yml
=> Colourful output in Docker

.ci/register_package.jl, azure-pipelines.yml
This relies upon
https://github.com/JuliaPackaging/BinaryBuilder.jl/pull/502
=> Improve registration

.ci/register_package.jl
Depends on https://github.com/JuliaPackaging/BinaryBuilder.jl/pull/503
=> We need to initialize the JLL packages before we try to write them out

D/Darknet/build_tarballs.jl, D/Darknet/bundled/patches/gemmc_windows_64bit.patch, D/Darknet/bundled/patches/getopt_windows.patch, D/Darknet/bundled/patches/windows_headers_case.patch, D/Darknet/bundled/patches/windows_ldflags.patch
Builder for AlexeyAB's fork of Darknet (for image object detection with YOLO)
https://github.com/AlexeyAB/darknet
Used in [Darknet.jl](https://github.com/ianshmean/Darknet.jl)
=> add darknet

A/ATK/build_tarballs.jl, A/at_spi2_atk/build_tarballs.jl, A/at_spi2_core/build_tarballs.jl, G/GTK3/build_tarballs.jl, G/gdk_pixbuf/build_tarballs.jl
=> Re-run registration for a multi-project group

S/Spglib/build_tarballs.jl, S/spglib/build_tarballs.jl
https://atztogo.github.io/spglib/
Spglib is a library for finding and handling crystal symmetries written in C.
=> wrap of spglib

D/Darknet/build_tarballs.jl
Build was successful but tests in Darknet.jl are failing for the previous jll
I'm just disabling AVX
=> [darknet] disable AVX

N/Ncurses/build_tarballs.jl
I needed this in #228, I guess it's better to have it here
=> [Ncurses] Create symlink for headers directory

azure-pipelines.yml
Reverts JuliaPackaging/Yggdrasil#225
=> Revert "[AZP] Map the token"

R/Readline/build_tarballs.jl
=> [Readline] Add builder

A/ASL/build_tarballs.jl
Ref https://github.com/JuliaPackaging/BinaryBuilder.jl/issues/512.  CC: @dpo
=> [ASL] Use Clang for FreeBSD, some other fixes

M/Mineos/build_tarballs.jl
Mineos (https://geodynamics.org/cig/software/mineos/) computes
normal modes of the Earth and similar planets.
=> [Mineos] Add builder for Mineos

F/FFMPEG/build_tarballs.jl
=> [FFMPEG] Fix name of library file for Windows

A/alsa/build_tarballs.jl
* Package name: alsa
* Version: v1.2.1-1
=> Wizard recipe: alsa-v1.2.1-1

G/GibbsSeaWater/build_tarballs.jl
For the oceanographers using Julia, It would be nice have support for the Gibbs-SeaWater library.
=> add GibbsSeaWater

A/alsa/build_tarballs.jl, F/FFMPEG/build_tarballs.jl, M/Mineos/build_tarballs.jl, X/Xorg_xcb_util_image/build_tarballs.jl, X/Xorg_xcb_util_keysyms/build_tarballs.jl, X/Xorg_xcb_util_renderutil/build_tarballs.jl, X/Xorg_xcb_util_wm/build_tarballs.jl
=> Mass rebuild of bugged JLL's

G/GSL@1/build_tarballs.jl, G/GSL@2/build_tarballs.jl, azure-pipelines.yml
=> New Recipe: GSL v1.16

P/PROJ/build_tarballs.jl
Ref https://github.com/JuliaPackaging/BinaryBuilder.jl/issues/539
=> [PROJ] expand cxx string ABIs

S/SuiteSparse@5/build_tarballs.jl
We need to do the same thing to SS on FreeBSD as on macOS
=> Fix `SuiteSparse` on FreeBSD as well

M/METIS/build_tarballs.jl
Building METIS_jll so that we can have it as a dependency for #289
=> [METIS] PR to build METIS_jll

P/pprof/build_tarballs.jl
manual PR since I couldn't figure out how to add the Go shard in the Wizard.
=> add pprof recipe

S/SymEngine/build_tarballs.jl
=> [SymEngine] Build with GCC7

azure-pipelines.yml
This should hopefully make things like LLVM a little easier to deal with.  ;)
=> [AZP] Limit BB `nproc` to 10

G/GEOS/build_tarballs.jl
Ref https://github.com/JuliaPackaging/Yggdrasil/pull/293#issuecomment-566749598
=> [GEOS] expand_cxxstring_abis

X/Xorg_xkeyboard_config/build_tarballs.jl
=> [Xorg_xkeyboard_config] Retrigger build

H/Htop/build_tarballs.jl
* Package name: Htop
* Version: v2.2.0
=> Wizard recipe: Htop-v2.2.0

P/Python/build_tarballs.jl, P/Python/bundled/patches/cross_compile_configure_ac.patch
Given https://github.com/JuliaLang/Pkg.jl/issues/1439, I think this might be useful.  I played with this a few weeks ago, if I remember well it doesn't currently work on any platform (that's why I didn't even open the PR back then), this is going to be fun.
=> Add builder for Python

I/iperf/build_tarballs.jl
* Package name: iperf
* Version: v3.7.0
=> Wizard recipe: iperf-v3.7.0

P/Python/build_tarballs.jl
We need more snakes in our lives
=> Add products for `python`, also build shared library

G/Gumbo/build_tarballs.jl
* Package name: Gumbo
* Version: v0.10.1
=> Wizard recipe: Gumbo-v0.10.1

O/OpenMPI/build_tarballs.jl
Currently being built without Fortran interface. We are also not building on Windows.
=> [OpenMPI] Build openmpi

M/MPICH/build_tarballs.jl
Provide MPICH binaries based on discussion in https://github.com/JuliaParallel/MPI.jl/issues/328
=> Add MPICH. Switch to https

P/Python/build_tarballs.jl
These snakes need to be able to talk to other snakes sssecurely.
=> Python: Add `OpenSSL_jll`

C/capnproto/build_tarballs.jl, C/capnproto/bundled/patches/aligned-alloc.patch
manual PR since capnproto requires C++14
@staticfloat please review and merge
=> add recipe for capnproto

L/Leptonica/build_tarballs.jl
=> [Leptonica] Add builder

A/ASL/build_tarballs.jl, A/ASL/bundled/asl-extra/aslinterface.cc
properly initialize fint return code
=> ASL v0.1.1

T/tmux/build_tarballs.jl
* Package name: tmux
* Version: v3.0.0-a
=> Wizard recipe: tmux-v3.0.0-a

L/libconfuse/build_tarballs.jl
* Package name: libconfuse
* Version: v3.2.2
=> Wizard recipe: libconfuse-v3.2.2

L/libnl/build_tarballs.jl
* Package name: libnl
* Version: v3.5.0
=> Wizard recipe: libnl-v3.5.0

F/Fontconfig/build_tarballs.jl
This will make it easier to call the various `fc-*` binaries.
=> [Fontconfig] Add more products

L/LCIO/build_tarballs.jl
LCIO.jl is a registered package. It depends on binaries that this script builds.
=> Add LCIO builder

B/bmon/build_tarballs.jl
* Package name: bmon
* Version: v4.0.0
=> Wizard recipe: bmon-v4.0.0

G/GtkSourceView/build_tarballs.jl, G/GtkSourceView/bundled/patches/meson_build_no_tests.patch
Ref https://github.com/JuliaGtk/GtkSourceWidget.jl/issues/8.  CC: @jonathanBieler
=> [GtkSourceView] Add builder

L/libusb/build_tarballs.jl
* Package name: libusb
* Version: v1.0.23
=> Wizard recipe: libusb-v1.0.23

F/Fastjet/build_tarballs.jl
* Package name: Fastjet
* Version: v3.3.3
=> Wizard recipe: Fastjet-v3.3.3

azure-pipelines.yml
To support the tree structure in #296 and to no
longer hardcode the depth of the tree.
=> search for build_tarballs.jl at any level

L/libexif/build_tarballs.jl
* Package name: libexif
* Version: v0.6.21
=> Wizard recipe: libexif-v0.6.21

M/METIS/build_tarballs.jl
Let's see if this fixes FreeBSD craziness.
=> [METIS] Trigger rebuild

0_RootFS/LLVMBootstrap@7/bundled/patches/0004-llvm-use-after-free.patch, 0_RootFS/LLVMBootstrap@8/bundled/patches/0004-llvm-use-after-free.patch, 0_RootFS/LLVMBootstrap@9/bundled/patches/0004-llvm-use-after-free.patch, 0_RootFS/llvm_common.jl
hopefully fixes the issue that has been plaguing building LLVM
in BB 0.2.0, I sofar verified that the patches apply cleanly.
=> add patch for use after free in LLVM

F/FastTransforms/build_tarballs.jl
To close https://github.com/JuliaCI/BaseBenchmarks.jl/issues/253
=> [FastTransforms] v0.2.13: change -Ofast to -O3

M/MPICH/build_tarballs.jl, O/OpenMPI/build_tarballs.jl
=> add mpiexec as ExecutableProducts to OpenMPI and MPICH

C/cxxwrap_julia/build_tarballs.jl
I took the liberty of submitting a PR with changes suggested by @giordano over at https://github.com/JuliaPackaging/Yggdrasil/pull/357#issuecomment-575115263 since I'm depending on a new release of [CxxWrap.jl](https://github.com/JuliaInterop/CxxWrap.jl).
@barche Please feel free to intervene!
=> JlCxx: Expand C++ string ABI + install LICENSE.md

M/MariaDB_Connector_C/build_tarballs.jl, M/MariaDB_Connector_C/bundled/patches/0001-Add-missing-header-file.patch, M/MariaDB_Connector_C/bundled/patches/0002-Add-definition-of-macros-and-structs-missing-in-MinG.patch, M/MariaDB_Connector_C/bundled/patches/0003-Use-_WIN32-macro.patch, M/MariaDB_Connector_C/bundled/patches/0004-Add-ws2_32-to-remoteio-libraries.patch, M/MariaDB_Connector_C/bundled/patches/0005-Fix-capitalisation-of-header-files.patch, M/MariaDB_Connector_C/bundled/patches/0006-pdb-gcc.patch, M/MariaDB_Connector_C/bundled/patches/0007-plugins_auth_bcrypt.patch, M/MariaDB_Connector_C/bundled/patches/0008-stray_char.patch, M/MariaDB_Connector_C/bundled/patches/0009-Fix-inconsistent-type-declaration-for-mysql_load_plu.patch
=> [MariaDB_Connector_C] Add builder

H/HDF5/build_tarballs.jl
=> [HDF5] Build for ARM and add header files for all platforms

H/HDF5/build_tarballs.jl
Fix #329, again.
CC: @Alexander-Barth
=> [HDF5] Install MinGW header files for Windows

C/CGAL/build_tarballs.jl
=> [CGAL]: Expand C++ string abi versions

M/MPICH/build_tarballs.jl, M/MPICH/bundled/patches/0001-romio-Use-tr-for-replacing-to-space-in-list-of-file-.patch
MPI-IO isn't building correctly, see https://github.com/JuliaParallel/MPI.jl/pull/339#issuecomment-575971632
This might fix it.
=> [MPICH] specify file systems

L/LLVM/common.jl, L/LLVM/v9/build_tarballs.jl
Another attempt at getting a successful build.
=> [LLVM] disable ccache for the mingw builds

L/LLVM/v6/build_tarballs.jl
=> [LLVM] build v6

S/SDL2_image/build_tarballs.jl
* Package name: SDL2_image
* Version: v2.0.5
=> Wizard recipe: SDL2_image-v2.0.5

S/SDL2_mixer/build_tarballs.jl
* Package name: SDL2_mixer
* Version: v2.0.4
=> Wizard recipe: SDL2_mixer-v2.0.4

S/SDL2/build_tarballs.jl, S/SDL2/bundled/patches/opengl_es2_conflicting_type.patch
=> [SDL2] Add patch for `i686` and `arm` Linux platforms

F/Fontconfig/build_tarballs.jl
This is a dummy change to trigger rebuilding FontConfig
=> Rebuild Fontconfig on CI

O/opusfile/build_tarballs.jl, O/opusfile/bundled/patches/no-openssl-wincert.patch
* Package name: opusfile
* Version: v0.11.0
=> Wizard recipe: opusfile-v0.11.0

N/NUMA/build_tarballs.jl
* Package name: NUMA
* Version: v2.0.13
=> Wizard recipe: NUMA-v2.0.13

S/SDL2_gfx/build_tarballs.jl, S/SDL2_gfx/bundled/patches/configure_in_add_macro_dir.patch
* Package name: SDL2_gfx
* Version: v1.0.3
=> Wizard recipe: SDL2_gfx-v1.0.3

G/GDAL/build_tarballs.jl, G/GDAL/bundled/patches/geos-m4-extra-libs.patch, G/GDAL/bundled/patches/sqlite3-m4-extra-libs.patch
In #418 it was reported that GDAL in some cases doesn't actually link against GEOS.  For the time being, this PR just checks for which platforms this happens, then we'll figure out what to do.
CC: @visr
=> [GDAL] Make sure we link to GEOS and SQLite3

N/NNPACK/build_tarballs.jl
This updates the `NNPACK` recipe so that we get a JLL out of it.
=> Update `NNPACK` recipe

L/libdivsufsort/build_tarballs.jl
* Package name: libdivsufsort
* Version: v2.0.2-1
=> Wizard recipe: libdivsufsort-v2.0.2-1

L/Libiconv/build_tarballs.jl
We need a new JLL package for this guy so it can be installed on Julia 1.2- via BP
=> Bump libiconv

G/GLFW/build_tarballs.jl
Lets see if this "just works"...
This must also udpate the sha, right?
=> [GLFW] upgrade to newest version

S/sdsl-lite/build_tarballs.jl
Windows missing because it's not supported
=> add sdsl-lite

0_RootFS/PlatformSupport/bundled/buildsystem_toolchains/cmake_macos_gcc.j2, 0_RootFS/PlatformSupport/bundled/buildsystem_toolchains/cmake_simple_gcc.j2, 0_RootFS/common.jl
We need to point to tools like `${target}-ar`, not `${target}-gcc-ar`
=> Fix cmake definitions

L/libcgal_julia/build_tarballs.jl
Properly this time, unlike #405.
**EDIT:** Force pushed to rename the package.
=> Add builder for CGAL julia wrapper

S/sais/build_tarballs.jl
Another suffix arrays library... In fact it's two libraries, sais and (optionally) sais64. I modified the build so that on 64-bit systems, it puts everything from sais64 into sais.
=> add "sais"

F/FastJet/build_tarballs.jl
=> [FastJet] disable deprecated features

azure-pipelines.yml
My `awk`-fu is not great, so please triple check what I did here :slightly_smiling_face:
=> [AZP] Limit the number of projects that can be built in a single go

L/lrslib/build_tarballs.jl
=> Wizard recipe: lrslib-v0.1.0

.ci/jll_init.jl, azure-pipelines.yml
Should fix #485, but this is totally untested (yet)
=> [AZP] Initialise JLL package from the JSON dump

H/HelloWorldGo/build_tarballs.jl, azure-pipelines.yml
This should fix https://github.com/JuliaPackaging/Yggdrasil/issues/497
=> Fix registration by generating `meta.json` again

.ci/azp_agent/install_agents.sh
Need to restart the agents after this.  Needed for #492
=> [AZP] Install `unzip` in the sandbox environment

T/tree_sitter_c/build_tarballs.jl
=> [tree_sitter_c] Install license and rename to remove dashes

L/libcgal_julia/build_tarballs.jl
4 new 3D objects: Point_3, Plane_3, Segment_3, and Vector_3 (see [`kernel.cpp`](https://github.com/rgcv/libcgal-julia/commit/060e23368328c2f4851af22809910713e867f568#diff-fa018f4d28b5116a35b36b72fc9f4e51) diff for more). With them, a few functions came along as well (some new, some specializations, see [`global_kernel_functions.cpp`](https://github.com/rgcv/libcgal-julia/commit/060e23368328c2f4851af22809910713e867f568#diff-391a750cbdae1d171575d89fb7eef2b1) diff for more.)
=> [libcgal_julia] Update to v0.6.0

F/FastJet_Julia_Wrapper/build_tarballs.jl
getting ready for the release of CxxWrap
=> adding builder for FastJet wrapper

C/CUTEst/build_tarballs.jl, L/LCIO_Julia_Wrapper/build_tarballs.jl
OK, trying this again. Not yet ready for merge until CxxWrap makes a release and I can add the release for LCIO_Julia_Wrapper.
Comments on nomenclature welcome.
=> adding LCIO Julia Wrapper

M/MKL/build_tarballs.jl
=> [MKL] Update builder to new BB and upgrade to v2020

O/OpenSpiel/build_tarballs.jl
=> add OpenSpiel

M/MPICH/build_tarballs.jl
See https://github.com/JuliaPackaging/Yggdrasil/pull/313#issuecomment-575337293
=> [MPICH] Fix musl build

M/Minuit2/build_tarballs.jl, M/Minuit2/bundled/patches/cmake-add-project.patch
* Package name: Minuit2
* Version: v6.15.1
=> Wizard recipe: Minuit2-v6.15.1

B/Bison/build_tarballs.jl
* Package name: Bison
* Version: v3.5.2
=> Wizard recipe: Bison-v3.5.2

L/libftd2xx/build_tarballs.jl
We now have a better way to express this
=> [libftd2xx]: Remove prepended hashes

A/aiger/build_tarballs.jl, A/aiger/bundled/patches/configure.patch
* Package name: aiger
* Version: v1.9.9
=> New Recipe: aiger v1.9.9

M/METIS@4/build_tarballs.jl, azure-pipelines.yml
This should hopefully fix registration issues
=> Merge variable generation into a single loop, pass hashes on through properly

G/glmnet/build_tarballs.jl
* Package name: glmnet
* Version: v5.0.0
=> Wizard recipe: glmnet-v5.0.0

N/NOMAD/build_tarballs.jl, N/NOMAD/bundled/patches/include_sys_time_missing_timeval_musl.patch
* Package name: NOMAD
* Version: v4.0.0
=> add builder for NOMAD

H/htslib/build_tarballs.jl
[Htslib](https://github.com/samtools/htslib) is a library for high-throughput sequencing data formats used in biology. I'm planning to create a binding as a Julia package next week and so I've made a build script.
=> Add htslib

P/P4est/build_tarballs.jl
* Package name: P4est
* Version: v2.2.0
=> Wizard recipe: P4est-v2.2.0

T/TerminalImageViewer/build_tarballs.jl, T/tiv/build_tarballs.jl
=> Wizard recipe: tiv-v1.0.0

O/OpenBLAS/OpenBLAS@0.3.7/build_tarballs.jl, O/OpenBLAS/OpenBLAS@0.3.7/bundled/patches/openblas-winexit.patch
This patch isn't suitable for upstream, but I'm hoping it'll help our CI issues. If it does, we can look at getting it done properly.
=> Take a hammer to OpenBLAS's attempts at cleanup

D/dSFMT/build_tarballs.jl
I have no idea why these depended on LibSSH2 and MbedTLS and whatnot.  Probably some kind of copypasta issue.
=> Upgrade `dSFMT`

M/mlpack/build_tarballs.jl
=> Rebuild mlpack

T/Triangle/build_tarballs.jl
Hi, this should replace JuliaGeometry/TriangleBuilder.
=> Add recipe for building Triangle mesh generator

O/OpenBLAS/OpenBLAS@0.3.7/bundled/patches/openblas-winexit.patch
I messed up the OpenBLAS patch. This fixes it.
=> Fix the patch

C/coordgenlibs/build_tarballs.jl
Package name: coordgenlibs
https://github.com/schrodinger/coordgenlibs
=> Add coordgenlibs

X/Xorg_libXt/build_tarballs.jl
=> [Xorg_libXt] Add builder

X/Xorg_libXmu/build_tarballs.jl
Browsing in my branches I found this builder dated October.  Let's see if it works
=> [Xorg_libXmu] Add builder

L/libsharp2/build_tarballs.jl
=> Wizard recipe: libsharp2-v1.0.0

L/LLVM/LLVM@9.0.1/bundled/llvm_patches/9999-llvm-symver-jlprefix.patch
It seems we forgotten to symbol version LLVM9
=> apply symver patch to LLVM9

L/LLVM/common.jl
=> set version suffix for LLVM

L/LLVM/common.jl
Trying to fix a few typos so that we build LLVM with JIT events again.
cc: @vchuravy , @mchristianl
Closes #616.
=> LLVM JIT events

G/gof3r/build_tarballs.jl, S/s3gof3r/build_tarballs.jl
Can't figure out how to build with godeps but running out of time for this -.-
Want to still have it here, so I have a place to pick it up again - or get some help with godeps ;)
=> Add s3gof3r

N/NOMAD/build_tarballs.jl, N/NOMAD/bundled/patches/nomad_openmp.patch, N/NOMAD/bundled/patches/sgtelib_openmp.patch
+ The problems with libgomp should be fixed :crossed_fingers:
=> Compile NOMAD with OpenMP

.devcontainer/Dockerfile
Should fix a permission problem.
=> Use Julia 1.4 in devcontainer

K/KaHyPar/build_tarballs.jl, K/KaHyPar/bundled/patches/disable-tests.patch
=> Wizard recipe: KaHyPar-v1.0.0

L/lrslib/build_tarballs.jl, L/lrslib/bundled/patches/no128bit.patch
small patch for the makefile for 32bit platforms
set several more variables to make it work on all platforms
add products for a few binaries
=> [lrslib] more platforms

P/PPL/build_tarballs.jl, P/PPL/bundled/patches/patch-v1.2.diff
More polyhedral software:
The Parma Polyhedra Library (PPL) provides numerical abstractions especially targeted at applications in the field of analysis and verification of complex systems. These abstractions include convex polyhedra, defined as the intersection of a finite number of (open or closed) halfspaces, each described by a linear inequality (strict or non-strict) with rational coefficients; some special classes of polyhedra shapes that offer interesting complexity/precision tradeoffs; and grids which represent regularly spaced points that satisfy a set of linear congruence relations. 
See: https://www.bugseng.com/parma-polyhedra-library
* The patch is needed because more recent compilers enforce extra typename and template statements.
* The configure needs a small correction …
=> [PPL] new recipe

X/XPA/build_tarballs.jl, X/xpa/build_tarballs.jl
* Package name: xpa
* Version: v2.1.19
=> Wizard recipe: xpa-v2.1.19

C/cddlib/build_tarballs.jl
More polyhedral software:
The C-library cddlib is a C implementation of the Double Description Method of Motzkin et al. for generating all vertices (i.e. extreme points) and extreme rays of a general convex polyhedron in R^d given by a system of linear inequalities.
See https://github.com/cddlib/cddlib
=> [cddlib] new recipe

K/KCP/build_tarballs.jl, K/kcp_jll/build_tarballs.jl
* Package name: kcp_jll
* Version: v1.5.0
=> Wizard recipe: kcp_jll-v1.5.0

F/FastTransforms/build_tarballs.jl
=> [FastTransforms] Rebuild to fix dependency on OpenBLAS on macOS

O/OpenBLAS/OpenBLASHighCoreCount@0.3.5/build_tarballs.jl, O/OpenBLAS/OpenBLASHighCoreCount@0.3.5/bundled/patches/openblas-avx512_sgemm.patch, O/OpenBLAS/OpenBLASHighCoreCount@0.3.5/bundled/patches/openblas-ofast-power.patch, O/OpenBLAS/OpenBLASHighCoreCount@0.3.5/bundled/patches/openblas-skylakexdgemm.patch, O/OpenBLAS/OpenBLASHighCoreCount@0.3.5/bundled/patches/openblas-winexit.patch, O/OpenBLAS/OpenBLASHighCoreCount@0.3.7/build_tarballs.jl, O/OpenBLAS/OpenBLASHighCoreCount@0.3.7/bundled/patches, O/OpenBLAS/OpenBLASHighCoreCount@0.3.7/bundled/patches/openblas-ofast-power.patch, O/OpenBLAS/OpenBLASHighCoreCount@0.3.7/bundled/patches/openblas-winexit.patch, O/OpenBLAS/common.jl
This necessary for working around situations such as https://github.com/JuliaLang/julia/issues/14857
=> Add special OpenBLASHighCoreCount JLL for HPC situations

.ci/Manifest.toml
To get PPC GlibC 2.17 binaries
=> upgrade to BB 0.2.4

S/SCS/build_tarballs.jl
Based on https://github.com/JuliaOpt/SCSBuilder/blob/master/build_tarballs.jl
=> [SCS] new recipe

G/GLPK/build_tarballs.jl
=> [GLPK] new recipe

E/ECOS/build_tarballs.jl
Based on https://github.com/JuliaOpt/ECOSBuilder
=> [ECOS] new recipe

U/utf8proc/build_tarballs.jl
=> update utf8proc to 2.5.0

C/CompilerSupportLibraries/build_tarballs.jl
Now that we've bumped BB, we can get GCC v9 CSL's!
=> [CSL]: Bump for gcc v9, include extraction logs for better debugging

B/bliss/build_tarballs.jl, B/bliss/bundled/patches/notimer.patch
bliss: A Tool for Computing Automorphism Groups and Canonical Labelings of Graphs
http://www.tcs.hut.fi/Software/bliss/
Needed for Polymake.jl.
I needed to remove `sys/timer.h` related stuff for mingw.
Also building the shared library manually as there is only a very basic `Makefile`.
And always build with GMP support and store this in `defs.hh` to avoid problems with other software depending on bliss.
=> [bliss] new recipe

S/Sundials@5/build_tarballs.jl
=> [Sundials] update for sundials 5.2

F/FLINT/build_tarballs.jl
FLINT: Fast Library for Number Theory: http://www.flintlib.org/
Needed for oscar-system and related software (Nemo.jl, Oscar.jl, Polymake.jl).
Script adapted from Flint2Builder by @thofma but with support for all platforms.
cc: @wbhart
=> [FLINT] new recipe

E/ECOS/build_tarballs.jl
-> https://github.com/JuliaOpt/ECOS.jl/pull/100#issuecomment-606641944
The same problem happened with GLPK.
=> [ECOS] add ECOS 2.0.5

O/Osi/build_tarballs.jl
Based on https://github.com/JuliaOpt/OsiBuilder/blob/master/build_tarballs.jl
=> [Osi] New recipe v0.107.9

L/Libtask/build_dylib.sh, L/Libtask/build_tarballs.jl
The binary [Libtask](https://github.com/TuringLang/Libtask.jl) uses.
=> New pkg: Libtask

Q/Qhull/build_tarballs.jl
This is my first pass at building Qhull, so I probably messed up a bit.  I can't use the wizard (no disk space), so I'll be relying on CI for this.
Fixes #685
=> New recipe: Qhull

L/LLVM/libLLVM@10.0.0/build_tarballs.jl
=> rebuild libLLVM

B/Bzip2/build_tarballs.jl, E/Expat/build_tarballs.jl, L/Libffi/build_tarballs.jl, L/Libuuid/build_tarballs.jl, Z/Zlib/build_tarballs.jl
=> bump for PPC -- Stage 1

O/OpenCL_Headers/build_tarballs.jl
=> fix OpenCL_Headers name

C/Clp/build_tarballs.jl
Following https://github.com/JuliaOpt/ClpBuilder
Currently disables mumps. We'll enable it once the library is building.
=> [Clp] New recipe. v1.16.11

B/bmon/build_tarballs.jl, G/Geant4/build_tarballs.jl, T/tree_sitter_c/build_tarballs.jl
with this we should be able to load all jll's on PPC
=> rebuild packages for PPC -- 2

L/LLVM/LLVM_full@9.0.1/build_tarballs.jl, L/LLVM/common.jl
=> [LLVM] fixes generate cmake files

M/MUMPS_seq/build_tarballs.jl
=> [MUMPS_seq] new formula v5.2.1

A/assimp/build_tarballs.jl
failures on 32-bit systems will be fixed by https://github.com/assimp/assimp/issues/2733.
=> Add recipe for assimp

C/Cubature/build_tarballs.jl
From: https://github.com/stevengj/CubatureBuilder/blob/master/build_tarballs.jl
=> [Cubature] New recipe

Q/QD/build_tarballs.jl
Failed on my machine with:
```
lib/libqdmod.so: undefined symbol: _ZN7dd_real8_ndigitsE
```
=> rebuild QD

O/OpenBLAS/OpenBLAS32@0.3.9/build_tarballs.jl, O/OpenBLAS/OpenBLAS@0.3.9/build_tarballs.jl, O/OpenBLAS/OpenBLASHighCoreCount@0.3.7/build_tarballs.jl
The most recent rebuild was just a day before the GlibC downgrade :/
=> rebuild OpenBLAS

A/alsa/build_tarballs.jl, A/armadillo/build_tarballs.jl, C/CGAL/build_tarballs.jl, H/htslib/build_tarballs.jl, L/Leptonica/build_tarballs.jl, L/Luna/build_tarballs.jl, M/MPICH/build_tarballs.jl, N/NUMA/build_tarballs.jl, P/P4est/build_tarballs.jl, S/SymEngine/build_tarballs.jl
=> rebuild packages for PPC -- 3

C/CFITSIO/build_tarballs.jl, E/Elfutils/build_tarballs.jl, G/GLEW/build_tarballs.jl, G/Graphene/build_tarballs.jl, L/Libcroco/build_tarballs.jl, L/libass/build_tarballs.jl, L/libsndfile/build_tarballs.jl, W/Wayland/build_tarballs.jl, X/Xorg_libXft/build_tarballs.jl
=> rebuild packages for PPC -- 4

C/Cgl/build_tarballs.jl
Based on https://github.com/JuliaOpt/CglBuilder/blob/master/build_tarballs.jl
=> [Cgl] New recipe v0.59.10

C/Cbc/build_tarballs.jl, C/Cbc/bundled/patches/no_lp.patch
Based on https://github.com/JuliaOpt/CbcBuilder/blob/master/build_tarballs.jl
=> [Cbc] new recipe v2.10.3

O/OpenBLAS/OpenBLAS32@0.3.9/build_tarballs.jl, O/OpenBLAS/OpenBLAS@0.3.5/build_tarballs.jl, O/OpenBLAS/OpenBLAS@0.3.7/build_tarballs.jl, O/OpenBLAS/OpenBLAS@0.3.9/build_tarballs.jl, O/OpenBLAS/OpenBLASHighCoreCount@0.3.5/build_tarballs.jl, O/OpenBLAS/OpenBLASHighCoreCount@0.3.7/build_tarballs.jl, O/OpenBLAS/common.jl
=> [OpenBLAS] Fix alignment and add dependency on CSL

A/at_spi2_core/build_tarballs.jl, H/HarfBuzz/build_tarballs.jl, T/Tk/build_tarballs.jl
=> bump TK/HarfBuzz/at_spi2 for alignment

L/LLVM/LLVM_full@8.0.1/build_tarballs.jl, L/LLVM/LLVM_full@9.0.1/build_tarballs.jl, L/LLVM/common.jl
fixes #769 and https://github.com/JuliaPackaging/Yggdrasil/issues/652#issuecomment-610460173
=> [LLVM] fix *_INSTALL_DIR references and clang symlinks

C/Coin-OR/Clp/build_tarballs.jl
=> [Clp] Add 1.17.3

Z/ZeroMQ/build_tarballs.jl
Potential space saving
`C:\Users\jr\.julia\artifacts\2fe5dc83269a247546ff56e9babd02af644a410e\bin\libzmq.dll`  19,003 KB
`C:\Users\jr\.julia\conda\3\Library\bin\libzmq.dll` 441 KB
=> [ZeroMQ] without debugging information

C/Coin-OR/Cbc/build_tarballs.jl, C/Coin-OR/Cgl/build_tarballs.jl, C/Coin-OR/Clp/build_tarballs.jl, C/Coin-OR/CoinUtils/build_tarballs.jl, C/Coin-OR/Osi/build_tarballs.jl, C/Coin-OR/coin-or-common.jl
This will make it easier to update and stay consistent
=> [Coin-OR] Refactor the Coin-OR solver build files

E/Elemental/build_tarballs.jl
95% sure this will not work on some platforms but we'll see!
Fix #420
=> Add recipe for Elemental

O/OSQP/build_tarballs.jl
first timer, happy to fix any issues
=> New recipe: OSQP

X/XML2/build_tarballs.jl, X/XSLT/build_tarballs.jl
=> [XML2] [XSLT] Remove static archives and large doc directories

L/LLVM/libLLVM@8.0.1/build_tarballs.jl
=> add libLLVM@8.0.1

F/fakechroot/build_tarballs.jl
* Package name: fakechroot
* Version: v2.20.2
=> Wizard recipe: fakechroot-v2.20.2

E/Elemental/build_tarballs.jl, E/Elemental/bundled/patches/01-fix-suffix.patch, E/Elemental/bundled/patches/02-fix-musl.patch
So it turns out that Elemental is actually unmaintained and has been forked to this other repo where development has continued... It also seems to have been pseudo-renamed, not really sure whether this should have been called Elemental or Hydrogen. Don't merge this yet, I mostly just want to see which platforms build properly. 
e: looks like musl is not cooperating
=> Build LLNL Elemental fork

0_RootFS/Rootfs/build_tarballs.jl, 0_RootFS/Rootfs/bundled/utils/bb.c
Goes with https://github.com/JuliaPackaging/BinaryBuilder.jl/pull/739
=> Add BB service client

Q/Qt/build_tarballs.jl
This should not be merged until PR https://github.com/JuliaPackaging/BinaryBuilder.jl/pull/698 is merged and operational. It also finally closes https://github.com/JuliaPackaging/BinaryBuilder.jl/issues/393
Especially take note of the beautifully short part in the script for macOS 🤮
I did a local test, binaries are here for now: https://github.com/barche/qt5_jll.jl/releases
=> [Qt] Add builder for Qt

C/Coin-OR/Clp/build_tarballs.jl, C/Coin-OR/coin-or-common.jl
Trying to address https://github.com/JuliaOpt/Clp.jl/pull/77#issuecomment-615220528
=> [Clp] Build 1.16.11

X/Xorg_libX11/build_tarballs.jl, X/Xorg_libXScrnSaver/build_tarballs.jl, X/Xorg_libXcomposite/build_tarballs.jl, X/Xorg_libXcursor/build_tarballs.jl, X/Xorg_libXdamage/build_tarballs.jl, X/Xorg_libXext/build_tarballs.jl, X/Xorg_libXfixes/build_tarballs.jl, X/Xorg_libXi/build_tarballs.jl, X/Xorg_libXinerama/build_tarballs.jl, X/Xorg_libXpm/build_tarballs.jl, X/Xorg_libXrandr/build_tarballs.jl, X/Xorg_libXrender/build_tarballs.jl, X/Xorg_libXtst/build_tarballs.jl, X/Xorg_libXxf86vm/build_tarballs.jl, X/Xorg_libpciaccess/build_tarballs.jl, X/Xorg_libxcb/build_tarballs.jl, X/Xorg_libxkbfile/build_tarballs.jl, X/Xorg_libxshmfence/build_tarballs.jl, X/Xorg_xkbcomp/build_tarballs.jl
Ref https://github.com/JuliaPackaging/BinaryBuilder.jl/issues/753
=> [Xorg] Rebuild packages to fix picking up armv7l wrappers in Julia v1.3

L/LibSpatialIndex/build_tarballs.jl, L/LibSpatialIndex/patches/header-check.patch, L/LibSpatialIndex/patches/makefile.patch
Copied from https://github.com/JuliaGeo/LibSpatialIndexBuilder and updated.
=> [LibSpatialIndex] new recipe

C/Coin-OR/CSDP/build_tarballs.jl
=> [Csdp] Do not install executables

O/OpenJpeg/build_tarballs.jl, O/OpenJpeg/bundled/patches/no_ffast-math.patch
* Package name: OpenJpeg
* Version: v2.3.1
=> Wizard recipe: OpenJpeg-v2.3.1

G/gmmlib/common.jl, N/NEO/build_tarballs.jl, S/SPIRV_LLVM_Translator/common.jl
Ref https://github.com/JuliaPackaging/Yggdrasil/pull/882#discussion_r410662622
=> Use explicit nproc with ninja.

generate_buildjl.jl
The first loop is needed for CompilerSupportLibraries and OpenBLAS32. The second loop is needed for GMP.
=> [generate_buildjl] Fix CompilerABI

S/sed/build_tarballs.jl
=> New Recipe: sed v4.8.0

M/MKL/build_tarballs.jl
=> [MKL] Disable autofix

T/Torch/build_tarballs.jl
Had to do a bit of weird linking due to Torch having a weird hardcoded path in their build scripts that deals with some CUDA tools.
cc @maleadt @staticfloat
=> add Torch build_tarballs.jl

0_RootFS/Rootfs/bundled/utils/flagon
Supersedes https://github.com/JuliaPackaging/BinaryBuilder.jl/pull/737
=> Add flagon script to convert platform-specific flags to compiler

C/CovidSim/build_tarballs.jl
=> [CovidSim] Build also for Windows

X/xsum/build_tarballs.jl
For https://github.com/stevengj/Xsum.jl, replacing https://github.com/stevengj/xsumBuilder
=> xsum builder

P/PCRE2/build_tarballs.jl
=> [skip ci] [PCRE2] Remove unrecognized configure options

M/mlpack/build_tarballs.jl
Hello there!  Just a package version update.  Hopefully I can get these automated at some point in the near(ish) future. :)
=> Update mlpack to latest stable version.

L/Leptonica/build_tarballs.jl
* Package name: Leptonica
* Version: v1.79.0
=> [Leptonica] Upgrade to v1.79.0

C/Cairo/build_tarballs.jl
=> [Cairo] Add all products

L/libcgal_julia/build_tarballs.jl
Includes a few things:
- Major overhaul to how geometrical kernel types are wrapped
- Adds 3D Linear Kernel types
- Adds 3D Linear Kernel global functions
=> [libcgal-julia] Update to v0.8.0

.ci/register_package.jl
Reverts JuliaPackaging/Yggdrasil#949 and restores changes in #894
=> [AZP] Restore fixes for multiple `build_tarballs`

O/OpenBLAS/OpenBLAS32@0.3.9/bundled/patches/fix-initialization-to-zero-in-the-NEON-SGEMM_BETA-ke.patch, O/OpenBLAS/OpenBLAS@0.3.9/bundled/patches/fix-initialization-to-zero-in-the-NEON-SGEMM_BETA-ke.patch
Ref https://github.com/JuliaLang/julia/pull/35113 :D
=> Add OpenBLAS patch for aarch64

O/OpenCL_Headers/build_tarballs.jl
Reverts JuliaPackaging/Yggdrasil#990
I fat-fingered the merge button...
=> Revert "[OpenCL] Use AnyPlatform for the headers JLL."

O/OpenCL_Headers/build_tarballs.jl
Revive of https://github.com/JuliaPackaging/Yggdrasil/pull/990, which I accidentally merged before it was ready.
=> [OpenCL] Use AnyPlatform for the headers JLL.

F/FastJet/build_tarballs.jl
Also attempting to build plugins. The plugin "Makefile" is a shell script and not very portable, since it calls a fastjet config binary.
The plugins are independent, though, so I'm attempting something extremely simple.
=> [FastJet] updating version

N/neofetch/build_tarballs.jl
* Package name: neofetch
* Version: v6.1.0
=> Wizard recipe: neofetch-v6.1.0

M/MozillaCACerts/build_tarballs.jl, M/MozillaCACerts/bundled/LICENSE
This packages up the .pem form of the Mozilla CA Certificates, downloaded via the LibCURL website.
=> Mozilla CA Certificates

F/FriBidi/build_tarballs.jl, L/LAME/build_tarballs.jl, L/libass/build_tarballs.jl, L/libfdk_aac/build_tarballs.jl, L/libvorbis/build_tarballs.jl, X/x264/build_tarballs.jl, X/x265/build_tarballs.jl
Try also to remove bloated static archives from the tarballs where necessary.
=> Rebuild other packages to fix selection of armv7l wrappers

D/datamash/build_tarballs.jl
* Package name: datamash
* Version: v1.7.0
=> Wizard recipe: datamash-v1.7.0

U/unixODBC/build_tarballs.jl
* Package name: unixODBC
* Version: v2.3.7
=> Wizard recipe: unixODBC-v2.3.7

G/gperftools/build_tarballs.jl
=> New Recipe: gperftools v2.7.0

S/SPIRV_LLVM_Translator/SPIRV_LLVM_Translator@10/build_tarballs.jl, S/SPIRV_LLVM_Translator/SPIRV_LLVM_Translator@8/build_tarballs.jl, S/SPIRV_LLVM_Translator/SPIRV_LLVM_Translator@9/build_tarballs.jl
Needed to get the fix in https://github.com/JuliaPackaging/BinaryBuilder.jl/pull/775.
CC: @maleadt @PhilipVinc
=> [SPIRV_LLVM_Translator] Rebuild to fix wrappers on macOS

M/MPICH/build_tarballs.jl
The fix is in https://github.com/JuliaPackaging/BinaryBuilder.jl/pull/775.
=> [MPICH] Rebuild to get a fix for macOS wrappers

M/MPFI/build_tarballs.jl
This adds a builder for the MPFI v1.5.4 library.
=> Add MPFI builder

P/Popt/build_tarballs.jl, P/Popt/bundled/patches/0001-nl_langinfo.mingw32.patch, P/Popt/bundled/patches/197416.all.patch, P/Popt/bundled/patches/217602.all.patch, P/Popt/bundled/patches/278402-manpage.all.patch, P/Popt/bundled/patches/318833.all.patch, P/Popt/bundled/patches/356669.all.patch, P/Popt/bundled/patches/367153-manpage.all.patch, P/Popt/bundled/patches/README, P/Popt/bundled/patches/fix-old-configure-macros.patch, P/Popt/bundled/patches/get-w32-console-maxcols.mingw32.patch, P/Popt/bundled/patches/no-uid-stuff-on.mingw32.patch
=> [WIP] Recipe for Popt

N/nauty/build_tarballs.jl, N/nauty/bundled/patches/autotoolization.patch
<s>This is not quite ready, but I figured it would be helpful to let it run through the tests here.</s>
This should be ready now.
=> New recipe: nauty 2.6.12

F/FastTransforms/build_tarballs.jl
This fixes a C -- Julia BigFloat interoperability issue.
=> [FastTransforms] v0.3.2

C/CImPlot/build_tarballs.jl, C/CImPlot/bundled/cmake/CMakeLists.txt
Build of the CImGui extension, CImPlot.
=> [CImPlot] initial commit

.ci/register_package.jl
=> [AZP] Define `repo` variable in `.ci/register_package.jl` once for all

C/CeresSolver/build_tarballs.jl
No success using OpenMP on macOS so far. Setting the compiler to `gcc` results in `"/opt/bin/gcc" is not able to compile a simple test program`.
=> CeresSolver: new recipe

C/Coin-OR/Osi/build_tarballs.jl
=> [Coin-OR/OSI] hotfix configure script for ppc

L/LetsBeRational/build_tarballs.jl
This is formerly #1073 
I changed the name and added a license file.
=> add LetsBeRational v1

L/libcint/build_tarballs.jl
* Package name: libcint
* Version: v3.0.20
=> Wizard recipe: libcint-v3.0.20

L/LASzip/build_tarballs.jl, L/LASzipBuilder/build_tarballs.jl
Previously this was https://github.com/evetion/LASzipBuilder
=> LASzip builder v3.4.3

L/libcxxwrap_julia/build_tarballs.jl
Not sure if this is sufficient or something more needs to be done.
Should it be a BuildDependency?
=> [libcxxwrap_julia] Add Julia_jll to libcxxwrap_julia

G/GnuTLS/build_tarballs.jl
=> [GnuTLS]: Bump to v3.6.13

C/Chafa/build_tarballs.jl
=> Add Chafa, a library for images in the terminal

O/OpenSSH/build_tarballs.jl, O/OpenSSH/bundled/patches/makefile-rm-duplicate-object.patch
* Package name: OpenSSH
* Version: v8.1.0
=> Wizard recipe: OpenSSH-v8.1.0

L/libsvm/build_tarballs.jl, L/libsvm/bundled/patches/makefile.patch, L/libsvm/bundled/patches/openmp.patch
And simplify the makefile changes, since we are building in a controlled environment.
=> [libsvm] Actually use OpenMP

D/Darknet/build_tarballs.jl
=> Include darknet headers

H/HELICS/build_tarballs.jl
Updates the HELICS package to v2.5.1
=> [HELICS] update to v2.5.1

D/Darknet_CUDA/build_tarballs.jl, D/Darknet_CUDA/bundled/patches/makefile-fix-cuda-paths.patch, S/snappy/build_tarballs.jl
Continuation of #1122 but with CUDA support
=> Darknet_CUDA - Darknet with CUDA support

G/Gdbm/build_tarballs.jl, G/Gdbm/bundled/patches/gdbm-1.15-win32.patch
Windows and Mac don't work yet.
=> New Recipe: Gdbm v1.18.1

C/CUDA/CUDA_full@11.0/build_tarballs.jl
I swear they purposefully reorganize the entire SDK every other release.
Now with PPC support (cc @vchuravy).
=> Add CUDA 11 RC.

C/CUTENSOR/CUTENSOR_CUDA10.1/build_tarballs.jl, C/CUTENSOR/CUTENSOR_CUDA10.2/build_tarballs.jl, C/CUTENSOR/common.jl
Same comments as in https://github.com/JuliaPackaging/Yggdrasil/pull/1144.
=> Add CUTENSOR v1.0.1.

P/pandoc/build_tarballs.jl, azure-pipelines.yml
=> [pandoc] Use permanet URL for the copyright files

H/HELICS/build_tarballs.jl
Updates the HELICS package to v2.5.2
=> [HELICS] update to v2.5.2

T/tblis/build_tarballs.jl
* Package name: tblis
* Version: v1.2.0
=> Wizard recipe: tblis-v1.2.0

S/SentencePiece/build_tarballs.jl
=> Add SentencePiece tokenizer

L/Libtask/build_dylib.sh, L/Libtask/build_tarballs.jl
=> Libtask update: support arch ppc64le

G/Git/build_tarballs.jl
Fixes #1063, fixes https://github.com/JuliaBinaryWrappers/Git_jll.jl/issues/2
=> Bump `Git` version

Z/zfp/build_tarballs.jl
Only FreeBSD does not work yet. If I can't find a fix soon, we'll disable FreeBSD and merge.
=> Wizard recipe zfp v0.5.5

O/OCaml/build_tarballs.jl
Add a recipe to install the ocaml compiler (my main motivation is that I'm working on some interoperability layer between julia and ocaml and this would make the package setup easier).
=> New Recipe: OCaml v4.10.0

L/LibArchive/build_tarballs.jl
* Package name: LibArchive
* Version: v3.4.3
=> Wizard recipe: LibArchive-v3.4.3

G/GDAL/build_tarballs.jl
Fixes https://github.com/JuliaGeo/GDAL.jl/issues/64
=> GDAL add OpenJPEG support

Z/Zlib/build_tarballs.jl
When I extract the object files in `lib/libz.a` I currently get an empty out with
```sh
readelf --relocs *.o | egrep '(GOT|PLT|JU?MP_SLOT)'
```
With this PR I get instead
```sh
0000000004b3  000800000004 R_X86_64_PLT32    0000000000000000 adler32_z - 4
00000000005a  000c00000004 R_X86_64_PLT32    0000000000000000 deflateInit_ - 4
0000000000db  000d00000004 R_X86_64_PLT32    0000000000000000 deflate - 4
0000000000f3  000e00000004 R_X86_64_PLT32    0000000000000000 deflateEnd - 4
000000000127  000a00000004 R_X86_64_PLT32    0000000000000000 compress2 - 4
0000000004a3  000c00000004 R_X86_64_PLT32    00000000000001c0 crc32_z - 4
0000000003d3  001100000004 R_X86_64_PLT32    0000000000000000 memcpy - 4
000000000423  001100000004 R_X86_64_PLT32    0000000000000000 memcpy - 4
000000000528 …
```
=> [Zlib] Ensure all libraries have position-independent code

A/Antic/build_tarballs.jl
=> [Antic] Fix bug (wrong library name)

Q/Qt/build_tarballs.jl
This supersedes PR  #1162 
Changes:
* Upgrade to 5.15
* Add LGPLv3 license
* Turn all dependencies into `BuildDependency`s
The last point might seem bad, but I compared with the official Qt Linux binaries, and they use a similar mechanism, where all the OpenGL and Xorg stuff comes from the system. This makes sense, since otherwise subtle errors appear. For example, using our own fontconfig at runtime will try to look for a config file in the buildbot root. I also experienced crashes that didn't happen anymore after this change.
=> [Qt] Version 5.15, license and dependency fixes

M/mlpack/build_tarballs.jl
Just a simple version bump, not much more to add. :)  (Hopefully it builds right!)
=> Bump mlpack version to 3.3.2

L/libinchi/build_tarballs.jl
* Package name: libinchi
* Version: v1.5.0
=> Wizard recipe: libinchi-v1.5.0

.ci/Manifest.toml
Not sure if this is the right way to go about it...
=> Update to latest BinaryBuilder with 'init_block' support

A/acl/build_tarballs.jl
* Package name: acl
* Version: v2.2.53
=> Wizard recipe: acl-v2.2.53

U/UCX/build_tarballs.jl
* Package name: UCX
* Version: v1.7.0
=> Wizard recipe: UCX-v1.7.0

C/CImGui/build_tarballs.jl
=> Bump CImGui to 1.77

C/CImPlot/build_tarballs.jl
See title. Version set to now track tags of https://github.com/epezent/implot
=> Updates for implot v0.3 + imgui 1.77

T/TurboPFor/build_tarballs.jl, T/TurboPFor/bundled/license.txt, T/TurboPFor/bundled/patches/makefile.patch
=> Add TurboPFor

L/libcgal_julia/build_tarballs.jl
Adds the 2D Convex Hulls and Extreme Points package
=> [libcgal-julia] Update to v0.11

O/OpenBLAS/OpenBLAS@0.3.9/build_tarballs.jl, O/OpenBLAS/common.jl
Following success here https://github.com/xianyi/OpenBLAS/issues/2696#issuecomment-653252750 in fixing BLAS on aarch64
Worth doing on `powerpc64le` ?
cc. @giordano
=> OpenBLAS: Enable DYNAMIC_ARCH for aarch64

J/JpegTurbo/build_tarballs.jl
Fixes https://github.com/JuliaBinaryWrappers/JpegTurbo_jll.jl/issues/1
=> [JpegTurbo] Rebuild package to install license file

F/fzf/build_tarballs.jl
* Package name: fzf
* Version: v0.21.1
=> Wizard recipe: fzf-v0.21.1

S/SEAL/build_tarballs.jl
=> Update SEAL v3.5.5 file hash after it was re-released

S/SEAL/build_tarballs.jl
=> Update SEAL v3.5.5 file hash after it was re-released *again*

0_RootFS/Rootfs/bundled/utils/config.guess, 0_RootFS/Rootfs/bundled/utils/config.sub
Ref https://github.com/JuliaLang/julia/pull/36615
=> [0_RootFS] Update configure helper scripts

A/acl/build_tarballs.jl, L/Lz4/build_tarballs.jl
=> -fPIC for acl and Lz4

M/mdbtools/build_tarballs.jl
* Package name: mdbtools
* Version: v0.8.2
=> Wizard recipe: mdbtools-v0.8.2

J/jlqml/build_tarballs.jl
=> [jlqml] Update to version 0.1.1

C/CUDA/CUDA@10.2/build_tarballs.jl
This library shipped with CUDA 10.2
=> Update 10.2 CUDA tarballs to include cusolverMg

C/CUDA/CUDA@10.1/build_tarballs.jl
Also shipped with this version
=> Include cusolverMg for CUDA 10.1

L/libcsv/build_tarballs.jl
* Package name: libcsv
* Version: v0.0.1
=> Wizard recipe: libcsv-v0.0.1

C/CMake/build_tarballs.jl
Try to do native builds of CMake.  It's useful to see how it works for https://github.com/JuliaPackaging/BinaryBuilder.jl/issues/741.  If compilation is successful, we can add compilation of CMake to `0_RootFS/Rootfs/build_tarballs.jl`.
=> [CMake] Upgrade CMake to v3.17.1

J/jlqml/build_tarballs.jl
QML.jl CI passes on Windows using this!
=> [jlqml] Update to version 0.1.3

H/HiGHS/build_tarballs.jl
Following the workshop, I up-ed the HiGHS version. Since it requires a higher CMake, I added the temporary fix
=> HiGHS 0.1.4

C/CGAL/build_tarballs.jl
Includes some simplifications in the build script
=> [CGAL] Trigger new build using gcc7

S/SpeexDSP/build_tarballs.jl
* Package name: SpeexDSP
* Version: v1.2.0
=> Wizard recipe: SpeexDSP-v1.2.0

J/JSON_C/build_tarballs.jl
* Package name: JSON_C
* Version: v0.15.0
=> Wizard recipe: JSON_C-v0.15.0

S/SBC/build_tarballs.jl
* Package name: SBC
* Version: v1.4.0
=> Wizard recipe: SBC-v1.4.0

C/Check/build_tarballs.jl
* Package name: Check
* Version: v0.15.1
=> Wizard recipe: Check-v0.15.1

L/libasyncns/build_tarballs.jl
* Package name: libasyncns
* Version: v0.8.0
=> Wizard recipe: libasyncns-v0.8.0

C/coreutils/build_tarballs.jl
* Package name: coreutils
* Version: v8.32.0
=> Wizard recipe: coreutils-v8.32.0

M/MPFR/build_tarballs.jl
It seems to generate more sensible code than v4.8.5 (ref: https://github.com/JuliaLang/julia/pull/36776#issuecomment-667198482).  CC: @vtjnash
=> [MPFR] Build with GCC v5

L/LMDB/build_tarballs.jl
The LMDB surces are maintained here:
https://git.openldap.org/openldap/openldap
=> Added support for building LMDB v0.9.25

F/finufft/build_tarballs.jl
* Package name: finufft
* Version: v1.1.2
=> Wizard recipe: finufft-v1.1.2

O/ORC/build_tarballs.jl
* Package name: ORC
* Version: v4.31.0
=> Wizard recipe: ORC-v4.31.0

F/figtree/build_tarballs.jl, F/figtree/bundled/patches/.gitattributes, F/figtree/bundled/patches/fix-dlext.patch
=> Wizard recipe: figtree-v1.0.0

N/nv_codec_headers/build_tarballs.jl
=> add nv_codec_headers

X/x264/build_tarballs.jl
=> X264: Update version

F/FFMPEG/build_tarballs.jl
Ref: https://github.com/JuliaPackaging/Yggdrasil/pull/1384#issuecomment-668005571
=> [FFMPEG] Fix compat with x264

F/FFMPEG/build_tarballs.jl
=> [FFMPEG] Make LibVPX a build-time dependency

L/LoopTools/build_tarballs.jl, L/LoopTools/bundled/patches/simplify-configure.patch
=> LoopTools build_tarballs

D/difmap/build_tarballs.jl
difmap is a CLI tool for astronomers
its version is 2.5e, that I represented as 2.5.5
=> add recipe for difmap

clean_builds.sh, reproducibility_scanning_tools.jl
Not that we're really pushing on this, but I was curious how reproducible we are.
=> Reproducibility scanning tools

L/LLVM/LLVM_full@9.0.1/bundled/llvm_patches/0050-llvm-julia-tsan-custom-as.patch, L/LLVM/LLVM_full@9.0.1/bundled/patches/0060-llvm-9.0-D85499.patch
Adds the TSAN patch that's on master
Adds the LLVM patch from https://github.com/JuliaLang/julia/pull/36956
=> Add more LLVM patches

L/libcgal_julia/build_tarballs.jl
Fair amount of changes:
+ Map 2D Straight Skeletons package (excluding a few low-level and
composed functions).
* Revise global kernel functions.  In the process, some
intersection-related functions were bound to have been added.
=> [libcgal-julia] Update to v0.15.0

I/isoband/build_tarballs.jl
This is my first attempt at using BinaryBuilder, so if someone experienced could take a look to see if what I did makes sense I'd appreciate it.
The code being built is very simple, it's just two or three C++ files without make script or anything like that. I create a shared object from that which I confirmed to work locally. Tests would live in the package that imports the jll, because originally tests were written in R, not C++
=> New Recipe: isoband v0.2.2

O/OpenLDAPClient/build_tarballs.jl
=> fix bad ssl refererence in mac build

P/Pixman/build_tarballs.jl
=> Eliminate useless syntax

X/Xorg_glproto/build_tarballs.jl
=> Update Xorg_glproto syntax

W/WORLD/build_tarballs.jl
=> Wizard recipe: WORLD-v0.1.0

S/SuiteSparse/SuiteSparse32/build_tarballs.jl
This is (at least one of the things) causing https://github.com/JuliaPackaging/Yggdrasil/pull/995#issuecomment-674395539
=> [SuiteSparse32] Copy SuiteSparse_config.h

S/SDPA/build_tarballs.jl, S/SDPA/bundled/patches/lt_init.diff, S/SDPA/bundled/patches/shared.diff, S/SDPA/bundled/sdpawrap/CMakeLists.txt, S/SDPA/bundled/sdpawrap/sdpawrap.cpp
Continuation of #804 in a new PR.
This is the original SDPABuilder: https://github.com/JuliaOpt/SDPABuilder
=> [SDPA] New recipe (again) 

Q/Qt/build_tarballs.jl
=> [Qt] Use dynamic opengl on Windows

J/jlqml/build_tarballs.jl
New release with environment variable manipulation functions, required for setting the PATH on Windows.
=> [jlqml] Bump version to 0.1.4

0_RootFS/PlatformSupport/build_tarballs.jl, 0_RootFS/Rootfs/build_tarballs.jl, 0_RootFS/Rootfs/bundled/libs/libc/download_libcs.sh, 0_RootFS/cull_old_shards.jl
Upgrade the very foundation of the world.
=> Bump RootFS and Platform Support shards

.ci/azp_agent/install_agents.sh
Ref: https://github.com/JuliaPackaging/BinaryBuilder.jl/issues/888
=> [AZP] Install zstd on the host

X/Xerces/build_tarballs.jl, X/Xerces/bundled/ThreadTest.patch
* Package name: Xerces
* Version: v3.2.3
=> Wizard recipe: Xerces-v3.2.3

C/CImPlot/build_tarballs.jl
Updating to implot v0.4 + regenerated cimplot bindings.
=> update to implot v0.4

F/FFMPEG/FFMPEG/build_tarballs.jl, F/FFMPEG/common.jl
This should allow building FFplay with little effort.
=> [FFMPEG] Build correct version and reorganise build recipe

F/FFMPEG/FFplay/build_tarballs.jl
=> [FFplay] Add builder

L/libsingular_julia/build_tarballs.jl
Same as https://github.com/JuliaPackaging/Yggdrasil/pull/1423, but for Singular.
=> [libsingular_julia] new recipe

.ci/Manifest.toml, H/HelloWorldC/build_tarballs.jl
=> [AZP] Update BB [HelloWorldC] Regenerate wrappers

G/GR/build_tarballs.jl
WIP for issue #11 
This builds on the three platforms that I can test myself, but the GR tests don't pass yet because Qhull only exposes the reentrant variant of the library.
=> [GR] Build using BinaryBuilder

O/OpenLDAPClient/build_tarballs.jl
=> [OpenLDAPClient] Rebuild

P/polymake/build_tarballs.jl, P/polymake/bundled/config/config-x86_64-apple-darwin14.ninja, P/polymake/bundled/patches/relocatable.patch
add the previous change also to the macos configuration 
some minor cleanup
remove flint version requirement as in #1528
=> [polymake] remove flint version requirement and minor configuration fixes

F/FastJet/build_tarballs.jl
=> [FastJet] fixing typo

0_RootFS/PlatformSupport/build_tarballs.jl, 0_RootFS/Rootfs/build_tarballs.jl, 0_RootFS/common.jl, 0_RootFS/gcc_common.jl
But still add the new Artifact to the local Artifacts.toml.
=> [RootFS]: Allow setting `--deploy=local` to skip GitHub upload

S/Singular/build_tarballs.jl
=> [Singular] new version

O/OpenBLAS/OpenBLAS32@0.3.9/build_tarballs.jl, O/OpenBLAS/OpenBLAS@0.3.10/build_tarballs.jl, O/OpenBLAS/OpenBLAS@0.3.5/build_tarballs.jl, O/OpenBLAS/OpenBLAS@0.3.7/build_tarballs.jl, O/OpenBLAS/OpenBLAS@0.3.9/build_tarballs.jl, O/OpenBLAS/OpenBLASHighCoreCount@0.3.5/build_tarballs.jl, O/OpenBLAS/OpenBLASHighCoreCount@0.3.7/build_tarballs.jl
@staticfloat says this is now required
=> Don't lock microarchitecture for OpenBLAS

G/glslang/build_tarballs.jl
This is my first pull request on this repo, hopefully this will work! (I tested it locally for Linux/Windows, it builds fine)
=> New recipe for glslang v8.13.3743

N/NEO/build_tarballs.jl
Forgot to actually bump the source...
=> Fix NEO upgrade.

S/SuiteSparse/SuiteSparse/build_tarballs.jl
Since we don't have the shard set up yet: [skip ci]
=> SuiteSparse: Fix build on Darwin aarch64

E/ephemeralpg/build_tarballs.jl, P/pg_tmp/build_tarballs.jl
* Package name: pg_tmp
* Version: v3.0.0
=> Wizard recipe: ephemeralpg-v3.0.0

G/GMP/build_tarballs.jl
Let's see if our automated platform is all up and running
=> Try building GMP for Darwin aarch64

L/libatomic_ops/build_tarballs.jl
@bramtayl Here's a working recipe.
=> New Recipe: libatomic_ops v1.33.7

.ci/Manifest.toml, M/MiniFB/build_tarballs.jl
=> [MiniFB] Build for all platforms

H/HarfBuzz/build_tarballs.jl, H/HarfBuzz/bundled/patches/Remove-HB_ICU_STMT.patch
Reverts JuliaPackaging/Yggdrasil#1669.  ICU on macOS should be working now
=> Revert "Revert "[HarfBuzz] Build with ICU""

T/tectonic/build_tarballs.jl
Seems to be building fine now after @giordano's ICU and harfbuzz fixes. (I built locally on linux, win, and mac but not the others, hopefully there aren't too many problems with those.)
=> Add tectonic build script.

U/util_linux/build_tarballs.jl
* Package name: util_linux
* Version: v2.35.0
=> Wizard recipe: util_linux-v2.35.0

X/xfoil_light/build_tarballs.jl
This is in preparation for the release of [Xfoil.jl](https://github.com/byuflowlab/Xfoil.jl) to the general package registry.
=> Add xfoil_light

H/HDF5/build_tarballs.jl
Coincidentally, this will also cause it to regenerate JLLs
=> Fix HDF5 install script

B/blis/build_tarballs.jl
* Package name: blis
* Version: v0.7.0+0
=> Wizard recipe: blis-v0.7.0+0

L/libjulia/common.jl, L/libjulia/libjulia@1.5/build_tarballs.jl, L/libjulia/libjulia@1.5/bundled/patches/0001-flisp-system.patch, L/libjulia/libjulia@1.5/bundled/patches/0002-libuv-system.patch, L/libjulia/libjulia@1.5/bundled/patches/0003-flisp.boot.patch, L/libjulia/libjulia@1.5/bundled/patches/0004-musl.patch, L/libjulia/libjulia@1.5/bundled/patches/0005-BUILD_EXE-for-flisp.patch
Issues:
- Need to host compile flisp first
- We don't have `llvm-config-host` so we are fighting the build-system
- Fix diverse bugs in the build-system that bit-rotted
Thanks to the heroic work in https://github.com/JuliaPackaging/Yggdrasil/pull/1664
=> Successfully cross-compile libjulia

L/LLVM/LLVM_full@10.0.1/build_tarballs.jl, L/LLVM/common.jl
=> Add BPF target to LLVM

C/CompilerSupportLibraries/build_tarballs.jl
Should fix https://github.com/JuliaPackaging/Yggdrasil/pull/1691#issuecomment-699501318
=> [CompilerSupportLibraries] Add `libatomic` to products

C/CompilerSupportLibraries/build_tarballs.jl
=> [CompilerSupportLibraries] Fix definition of the products

C/CyrusSASL/build_tarballs.jl, C/CyrusSASL/bundled/patches/02-exeext.patch, C/CyrusSASL/bundled/patches/03-fix-plugins.patch, C/CyrusSASL/bundled/patches/04-manpage-paths.patch, C/CyrusSASL/bundled/patches/14-MinGW-w64-add-LIBSASL_API-to-function-definitions.patch, C/CyrusSASL/bundled/patches/15-MinGW-w64-define-LIBSASL_EXPORTS_eq_1-for-sasldb.patch, C/CyrusSASL/bundled/patches/16-MinGW-w64-define-WIN32_LEAN_AND_MEAN-avoiding-handle_t-redef.patch, C/CyrusSASL/bundled/patches/17-MinGW-w64-define-S_IRUSR-and-S_IWUSR.patch, C/CyrusSASL/bundled/patches/19-paths-relocation.patch, C/CyrusSASL/bundled/patches/20-mingw-tchar.patch, C/CyrusSASL/bundled/patches/21-fix-getopt-guard.patch, C/CyrusSASL/bundled/patches/30-remove-extra-incompatible-typedef.patch, C/CyrusSASL/bundled/patches/31-do-not-make-mdf5global_h.patch, C/CyrusSASL/bundled/patches/macos-shared-lib-extension.patch
This does not work on anything other than Linux at this time. Putting it out there to see if someone wants to take this on.
=> Cyrus SASL

T/TtH/build_tarballs.jl
=> Wizard recipe: TtH-v0.1.0

S/SARSOP/build_tarballs.jl
Moving from https://github.com/JuliaPOMDP/SARSOP_jll.jl to Yggdrasil 
JuliaPOMDP/POMDPs.jl#318
=> add SARSOP v0.96.0

.ci/Manifest.toml, H/HelloWorldC/build_tarballs.jl
Get this fix: https://github.com/JuliaPackaging/BinaryBuilder.jl/pull/926
=> [AZP] Update BinaryBuilder

.ci/Manifest.toml, H/HelloWorldC/build_tarballs.jl
Get [this fix](https://github.com/JuliaPackaging/BinaryBuilder.jl/pull/927).
=> [AZP] Bump BinaryBuilder again

G/GLFW/build_tarballs.jl
To check whether #1733 happens or not with the latest macOS SDK.
=> [GLFW] Update build script

G/GLU/build_tarballs.jl
* Package name: GLU
* Version: v9.0.1
=> Wizard recipe: GLU-v9.0.1

C/Capstone/build_tarballs.jl
* Package name: Capstone
* Version: v4.0.2
=> Wizard recipe: Capstone-v4.0.2

N/ngspice/build_tarballs.jl, N/ngspice/bundled/patches/drop_ac_malloc.patch, N/ngspice/bundled/patches/libtoolize.patch, N/ngspice/bundled/patches/ngicon.patch, N/ngspice/bundled/patches/shlwapi.patch, N/ngspice/bundled/patches/static_inline.patch, N/ngspice/bundled/patches/wincross.patch
Requires four minor patches, but otherwise builds nicely.
I've submitted the first of these four patches upstream at
https://sourceforge.net/p/ngspice/patches/98/. We'll see
if there's any movement there - if so, I'll submit the other
ones.
=> New Recipe: ngspice v32.2.0

P/P4est/build_tarballs.jl
Closes trixi-framework/P4est.jl#3.
=> P4est: Enable BLAS and disable (unused) static libraries

T/ThriftJuliaCompiler/build_tarballs.jl
Use Julia 1.2+ get/set properties for threadsafety
=> ThriftJuliaCompiler v0.12.0

Q/qwt/build_tarballs.jl
+ qwt library for Windows and Linux x64
=> [qwt] adding qwt library

W/WaveFD/build_tarballs.jl
Hi,
This is for version v0.1.1 of [WaveFD.jl](https://github.com/ChevronETC/WaveFD.jl).
Thanks!
Sam
=> WaveFD, new version, 0.1.1

F/fzf/build_tarballs.jl
ref https://github.com/junegunn/fzf/releases/tag/0.23.1
=> [fzf] update to 0.23.1

H/HELICS/build_tarballs.jl
Updates the HELICS package to v2.6.1
=> [HELICS] update to v2.6.1

C/CLIME/build_tarballs.jl
* Package name: CLIME
* Version: v1.3.1
=> Wizard recipe: CLIME-v1.3.1

W/Word2Vec/build_tarballs.jl, W/Word2Vec/bundled/patches/mac_and_cross.patch
Based on sources from https://github.com/tmikolov/word2vec
=> [Word2Vec] new build

B/battery_cli/build_tarballs.jl
For monitoring system battery status
https://github.com/distatus/battery#cli
=> [battery_cli] add cli variant of battery go package

T/TetGen/build_tarballs.jl, T/TetGen/cwrapper/cwrapper.cxx, T/TetGen/cwrapper/generate_cwrapper.jl
Replaces JuliaGeometry/TetGenBuilder.
Coordinated with @SimonDanisch
=> Artifact for TetGen mesh generator

L/libjulia/libjulia@1.3/build_tarballs.jl
first attempt was merged but then due to a CI issue the JLL was not actually
regenerated
=> libjulia 1.3.1, second try

M/Mesa/build_tarballs.jl
=> Mesa: switch to https download, regenerate JLL wrapper

D/dSFMT/build_tarballs.jl
=> dSFMT: add the shlib build options

H/HelFEM/build_tarballs.jl
Adds a recipe for the [HelFEM](https://github.com/susilehtola/HelFEM) library which I intend to wrap in a Julia package. It's very preliminary (e.g. the source of the wrapper sits on a [branch of my fork](https://github.com/mortenpi/HelFEM/tree/mp/julia) at the moment), but functional. But I would love to have a version of it in the registry, as that will make working on the wrapper easier.
If something looks weird, then it's probably because I didn't really know what I was doing, and tried to hack together something seems to compile :laughing: 
cc @susilehtola (just FYI)
=> Add recipe for HelFEM

L/libigc/build_tarballs.jl, L/libigc/bundled/patches/cmake.patch
Fixing-up what I accidentally pushed to master.
=> [libigc] Upgrade to v1.0.5186.

H/HelFEM/build_tarballs.jl
Dummy change to actually run the HelFEM build, ref: https://github.com/JuliaPackaging/Yggdrasil/pull/1949#issuecomment-715796128
=> Dummy change to run HelFEM build

A/Antic/build_tarballs.jl
=> Regenerate Antic_jll

L/lib4ti2/build_tarballs.jl
=> Regenerate lib4ti2_jll

F/fzf/build_tarballs.jl
See https://github.com/junegunn/fzf/releases/tag/0.24.0.
=> [fzf] update to version 0.24.1.

S/SharedMimeInfo/build_tarballs.jl
=> Bump SharedMimeInfo JLL wrapper

M/mlpack/build_tarballs.jl
Woohoo!  Version bump day!  Let's see if this works.  I hope so. :smile:
=> Update to latest stable version of mlpack

O/Openresty/build_tarballs.jl
=> [Openresty] Rebuild to trigger registration

M/MongoC/build_tarballs.jl
=> Regenerate MongoC JLL wrapper

M/MbedTLS/build_tarballs.jl
=> Regenerate MbedTLS JLL wrapper

L/libsass/build_tarballs.jl
For use in https://github.com/piever/Sass.jl
=> New recipe: libsass

B/breakpad/build_tarballs.jl, C/CMake/build_tarballs.jl, D/Darknet/Darknet_CUDA/build_tarballs.jl, F/FastJet_Julia_Wrapper/build_tarballs.jl, G/Glibc/build_tarballs.jl, H/HelloWorldRust/build_tarballs.jl, J/jlqml/build_tarballs.jl, L/LCIO_Julia_Wrapper/build_tarballs.jl, L/LibOSXUnwind/build_tarballs.jl, L/libcgal_julia/build_tarballs.jl, L/libcxxwrap_julia/build_tarballs.jl, L/librealsense/build_tarballs.jl, L/libsingular_julia/build_tarballs.jl, N/NNPACK/build_tarballs.jl, O/OpenAL/build_tarballs.jl, O/OpenSpiel/build_tarballs.jl, T/Torch/build_tarballs.jl, T/tblis/build_tarballs.jl
=> Update more platform specifications

S/SharedMimeInfo/build_tarballs.jl
There is also a version 2.0 but it has a new build system and looks like an overall much bigger change, so I don't want to worry about that.
=> Update SharedMimeInfo to 1.15

A/AlgRemez/build_tarballs.jl
=> Wizard recipe: AlgRemez-v0.1.0

A/ASL/build_tarballs.jl, C/Coin-OR/CSDP/build_tarballs.jl, C/Coin-OR/Cbc/build_tarballs.jl, C/Coin-OR/Cgl/build_tarballs.jl, C/Coin-OR/Clp/build_tarballs.jl, C/Coin-OR/CoinUtils/build_tarballs.jl, C/Coin-OR/Osi/build_tarballs.jl, E/ECOS/build_tarballs.jl, I/Ipopt/build_tarballs.jl, M/METIS/METIS@5/build_tarballs.jl, M/MUMPS/MUMPS@5/build_tarballs.jl, M/MUMPS/MUMPS_seq@4/build_tarballs.jl, M/MUMPS/MUMPS_seq@5/build_tarballs.jl, S/SCS/build_tarballs.jl
=> Bumping various coin-or libraries for JLLWrappers

Z/Zlib/build_tarballs.jl
This time, with feeling, and a blatant disregard for upstream version numbers!
=> [Zlib] Rebuild with fake version number for v1.6+ with experimental platforms

L/LibOSXUnwind/build_tarballs.jl
This will likely fail on aarch64
=> [OSXUnwind] Build experimental platforms for v1.6+

S/SuiteSparse/SuiteSparse/build_tarballs.jl
Fixes a regression introduced in 278171537414285ce46427c78310d3da877ce89c
=> Fix SuiteSparse for macOS & FreeBSD

E/Enzyme/Enzyme@9/build_tarballs.jl
=> [Enzyme@9] Actually build new version

.ci/register_package.jl
Could we actually fix the incorrect tagged values this time?!
=> Push JLL package _before_ uploading binaries

F/fzf/build_tarballs.jl
https://github.com/junegunn/fzf/releases/tag/0.24.2
=> [fzf] upgrade to 0.24.2

X/XZ/build_tarballs.jl
XZ_jll is a build dependency of some other Julia dependencies
=> [XZ] Enable experimental platforms

E/EarCut/build_tarballs.jl
=> Regenerate EarCut_jll wrapper

O/OpenMPI/build_tarballs.jl
=> Bump JLL wrapper: OpenMPI_jll

azure-pipelines.yml
Let's see if this works nicely.
=> [AZP] Pay attention to BBB hash as well

O/OpenSlide/build_tarballs.jl
Build recipe for [OpenSlide](https://openslide.org/).
=> Add OpenSlide.

N/Nettle/build_tarballs.jl, N/Nettle/bundled/patches/alloca.patch
Also get the latest JLL wrapper code.
=> Rebuild nettle with FreeBSD support

G/GAP/build_tarballs.jl
Some minor tweak to the GAP_jll that make it slightly more convenient to actually use in GAP.jl.
=> Tweak GAP_jll

W/WaveFD/build_tarballs.jl
New version of WaveFD (with breaking changes).
=> WaveFD 0.2.0

G/GAP_lib/build_tarballs.jl
for use in https://github.com/oscar-system/GAP.jl
=> Add GAP_lib

N/NEO/build_tarballs.jl
=> [NEO] Enable DG1 support.

S/SPIRV_LLVM_Translator/SPIRV_LLVM_Translator@10/build_tarballs.jl, S/SPIRV_LLVM_Translator/SPIRV_LLVM_Translator@11/build_tarballs.jl, S/SPIRV_LLVM_Translator/SPIRV_LLVM_Translator@8/build_tarballs.jl, S/SPIRV_LLVM_Translator/SPIRV_LLVM_Translator@9/build_tarballs.jl, azure-pipelines.yml
@giordano like this?
If so, I'll attach a bump to the recently-failed JLL build here.
=> Run init_jll serially.

W/Wine/build_tarballs.jl
This does not actually build for me, but perhaps it'll help anybody
interested in reviving it
[skip ci]
[skip build]
=> Wine_jll: update outdated commands

T/TDLib/build_tarballs.jl
=> add recipe for TDLib

N/NetCDF/build_tarballs.jl
=> [NetCDF] rebuild against new HDF5 1.12.0 build

S/SPIRV_LLVM_Translator/SPIRV_LLVM_Translator@9/build_tarballs.jl
~Only merge when https://github.com/JuliaPackaging/Yggdrasil/commit/e85764c7f595eaf809269ff41b717131f98b7e2c#commitcomment-44214400 is resolved.~
Probably needs to wait on https://github.com/JuliaRegistries/General/pull/24728 too to avoid merge conflicts.
=> [LLVM SPIRV translator] Add Julia 1.5 compat.

Q/Qt/build_tarballs.jl
Draft PR to try and add more platforms (notably aarch64).
A local check indicated that at least armv7 doesn't compile anymore, either.
=> [Qt] Bump version to v5.15.1

G/GDAL/build_tarballs.jl
Fix #2140, ref https://github.com/JuliaGeo/GDAL.jl/pull/103#issuecomment-730626039
=> [GDAL] build with fixed nghttp2 version to fix OSX

O/OpenBLAS/OpenBLAS32@0.3.12/bundled/patches/neoverse-generic-kernels.patch, O/OpenBLAS/OpenBLAS@0.3.12/bundled/patches/neoverse-generic-kernels.patch, O/OpenBLAS/OpenBLASHighCoreCount@0.3.12/bundled/patches/neoverse-generic-kernels.patch
See https://github.com/xianyi/OpenBLAS/issues/2998
=> [OpenBLAS] Disable specialized Neoverse-N1 kernels for nrm2

L/libjulia/common.jl, L/libjulia/libjulia@1.3/build_tarballs.jl, L/libjulia/libjulia@1.3/bundled/patches/0006-src-Makefile.patch
=> libjulia: fix 1.3.1 build

W/wannier90/build_tarballs.jl
Adds Wannier90 as library and executable.
=> Add Wannier90

N/NetCDF/build_tarballs.jl
Since this library gave it a failure on loading the JLL package.
As suggested by @giordano in https://github.com/JuliaPackaging/Yggdrasil/pull/2125#issuecomment-729904159.
=> [NetCDF] fix MbedTLS version

H/HelFEM/build_tarballs.jl
Exposes a few more methods and functions from the HelFEM library ([changes](https://github.com/mortenpi/HelFEM/compare/d3b9ce4d34fcce3296a80aef0ed9b60ce45319c9...f2a1dcd456ab1c6c530ff9ae3b916bde2ebf9ae6?expand=1)).
=> Update HelFEM_jll to 0.0.2

U/utf8proc/build_tarballs.jl
For https://github.com/JuliaLang/julia/pull/38551
=> [utf8proc] v2.6.0

M/MPSolve/build_tarballs.jl
Build script for the [MPSolve library](https://github.com/robol/MPSolve) for finding the roots of polynomials and secular equations.
=> Build script for MPSolve library by Leonardo Robol

C/CRlibm/build_tarballs.jl, C/CRlibm/bundled/patches/fpu_setcw.patch, C/CRlibm/bundled/patches/random-rand.patch
* Package name: CRLibm
CC: @dpsanders
=> Wizard recipe: CRLibm-v1.0.0

C/Cubature/build_tarballs.jl
For https://github.com/stevengj/cubature/pull/14 and https://github.com/JuliaMath/Cubature.jl/issues/25
=> [cubature] bump to v1.0.4

O/OpenBLAS/OpenBLAS32@0.3.10/build_tarballs.jl, O/OpenBLAS/OpenBLAS32@0.3.12/build_tarballs.jl, O/OpenBLAS/OpenBLASHighCoreCount@0.3.10/build_tarballs.jl, O/OpenBLAS/OpenBLASHighCoreCount@0.3.12/build_tarballs.jl
The compat has been already fixed in the registry, but it should also be
reflected in the recipe, to avoid future rebuilds have the same problem again.
=> [OpenBLAS] Fix julia compat of some OpenBLAS builders

P/Pixman/build_tarballs.jl
=> Bump Pixman to 0.40.0

L/LLVM/Clang@11.0.0/build_tarballs.jl, L/LLVM/LLVM@11.0.0/build_tarballs.jl
=> bump Clang and LLVM

S/SPIRV_Tools/build_tarballs.jl
Should my accidental push-to-master.
=> [SPIRV-Tools] Fix build.

Q/Qt/build_tarballs.jl
=> [Qt] Try to fix libatomic issue on armv7

P/protoc/build_tarballs.jl, P/protoc/bundled/patches/winmutex.patch
* Package name: protoc
* Version: v3.14.0
=> Wizard recipe: protoc-v3.14.0

Q/Qt/build_tarballs.jl
Qt update. @barche 
The build script is looking solid!
=> [Qt] - update to 5.15.2

Q/qwtw/build_tarballs.jl
another 2D plotting library, for Linux X64 only yet..
=> + qwtw library

F/FLINT/build_tarballs.jl
This should be checked by at least @thofma and @benlorenz before being merged.
=> Revise FLINT_jll versioning scheme

.ci/Manifest.toml
Needed in particular for
https://github.com/JuliaPackaging/BinaryBuilderBase.jl/pull/88.
=> [AZP] Update BinaryBuilderBase

generate_buildjl.jl
=> Revise generate_buildjl.jl

Q/qwtw/build_tarballs.jl
=> [qwtw] push to latest qwtw version with improvements and bug fixes

F/FastHadamardStructuredTransforms/build_tarballs.jl
This pull request contains a build_tarballs file for a new library, called "FastHadamardStructuredTransforms".
It's the first time I use BinaryBuilder so let me know if I did anything wrong!
=> New library: FastHadamardStructuredTransforms v0.0.1

F/finufft/build_tarballs.jl
Let's hope the build for x86_64-linux-musl does not fail as on my system.
=> Update to latest stable release v2.0.2

S/Singular/build_tarballs.jl
also use a slightly newer git snapshot yet again
CC @thofma @fieker
=> Update Singular_jll to use Flint 2.7

F/fzf/build_tarballs.jl
https://github.com/junegunn/fzf/releases/tag/0.24.4
=>  [fzf] upgrade to 0.24.4

L/libsingular_julia/common.jl, L/libsingular_julia/libsingular_julia@1.3/build_tarballs.jl
Requires #2298 (and then must wait for resulting JLL update to arrive in the registry).
Also kinda leapfrogs #2263 (which I will update to match once this PR here is merged)
=> libsingular_julia: rebuild with latest Singular_jll

L/libsingular_julia/libsingular_julia@1.5/build_tarballs.jl
Should wait for PR #2263 to be merged (but I wanted to already have it prepared)
=> libsingular_julia for Julia 1.5

A/Antic/build_tarballs.jl, A/Arb/build_tarballs.jl, F/FLINT/build_tarballs.jl, N/normaliz/build_tarballs.jl, S/Singular/build_tarballs.jl
This is is mostly fixing a few typos and aligning these files to
be as similar as possible, to make future edits a bit easier.
[skip ci]
[skip build]
=> Cleanup some build files

M/Minuit2/build_tarballs.jl
libMinuit2Math was built as .a. Needs to be a .so.
=> [Minuit2] adding target

L/libcxxwrap_julia/build_tarballs.jl, L/libsingular_julia/common.jl, L/libsingular_julia/libsingular_julia@1.3/build_tarballs.jl, L/libsingular_julia/libsingular_julia@1.4/build_tarballs.jl, L/libsingular_julia/libsingular_julia@1.5/build_tarballs.jl
They are not useful but make it harder to compose the .jl files.
[skip build]
[skip ci]
=> Remove various uses of const

L/Libcerf/build_tarballs.jl
Another dependency for gnuplot
I also hope that someone can use this jll to make libcerf julia bindings in the future
=> Add Libcerf builder

K/kubectl/build_tarball.jl
Gave up on trying to compile kubernetes, this just downloads pre-compiled binaries.
=> kubectl v1.20.0 pre-packaged binaries x86_64-* only

C/CMake/build_tarballs.jl
Updating Cmake to the latest version
=> [CMake] Update to v3.19.2

L/libcgal_julia/common.jl, L/libcgal_julia/libcgal_julia@1.3/build_tarballs.jl
Supersedes @fingolfin's draft #2326, betting on supporting julia versions increasingly since the latest LTS.
=> [libcgal-julia] Update to v0.16.0 w/ libjulia v1.3.1

M/MathGL/build_tarballs.jl, M/MathGL/bundled/patches/cmake_patch.patch
+ MathGL 2D and 3D plotting library from sourceforge
=> [MathGL] library

C/CImPlot/build_tarballs.jl, C/CImPlot/bundled/cmake/CMakeLists.txt
bumping implot binaries to version release 0.8
=> update to implot v0.8

C/CUDA/CUDA_full@10.0/build_tarballs.jl, C/CUDA/CUDA_full@10.1/build_tarballs.jl, C/CUDA/CUDA_full@10.2/build_tarballs.jl, C/CUDA/CUDA_full@11.0/build_tarballs.jl, C/CUDA/CUDA_full@11.1/build_tarballs.jl, C/CUDA/CUDA_full@11.2/build_tarballs.jl, C/CUDA/CUDA_full@9.0/build_tarballs.jl, C/CUDA/CUDA_full@9.2/build_tarballs.jl
Ref https://github.com/JuliaLang/julia/issues/38993; let's hope this doesn't massively conflict when it hits General.
=> [CUDA] Fix permissions of DLLs.

.ci/Manifest.toml
... and all their deps, while at it.
I need this for https://github.com/JuliaPackaging/BinaryBuilderBase.jl/pull/93
@giordano so I just did a `Pkg.update()` in there -- but perhaps that's too much? Not sure what else would be the recommended way, though?
=> Update to latest BB and BBB

L/LLVM/libLLVM@11.0.0/build_tarballs.jl
=> [libLLVM] Retrigger registration

C/Chemfiles/build_tarballs.jl
Do not merge this yet, it contains a pre-release version to check everything is working fine with Yggdrasil infrastructure.
=> Update chemfiles to 0.10.0

G/gmsh/build_tarballs.jl
add a fileproduct to `gmsh_jll.jl` that contains the julia gmsh api
Path should be fine, but need to verify it with CI, so WIP
=> gmsh api as fileproduct

generate_buildjl.jl
Both CXX and libgfortran tags should be supported.
This is a follow up to #2243, @thofma you might be interested! Instead of hardcoding known platform triple => julia Platform types conversions, this code tries to parse the platform triple. I tested it with a few packages, including ones with both cxx and fortran ABI requirements.
=> Make sure generate_buildjl works with compiler_abi

L/libsingular_julia/libsingular_julia@1.4/build_tarballs.jl
Needs to wait for PR #2379 having landed in the registry.
=> Update libsingular to 0.5 for Julia 1.4

0_RootFS/Rootfs/build_tarballs.jl, 0_RootFS/Rootfs/bundled/testsuite/rust/cargo_build/Cargo.toml, 0_RootFS/Rootfs/bundled/testsuite/rust/cargo_build/Makefile, 0_RootFS/Rootfs/bundled/testsuite/rust/cargo_build/src/main.rs, 0_RootFS/Rootfs/bundled/utils/apk_wrapper.sh, 0_RootFS/Rootfs/bundled/utils/config.guess, 0_RootFS/Rootfs/bundled/utils/config.sub, 0_RootFS/Rootfs/bundled/utils/tar_wrapper.sh
TODO:
Companion PR to BinaryBuilder: https://github.com/JuliaPackaging/BinaryBuilderBase.jl/pull/100
=> [RootFS] Install `samurai` instead of `ninja`

L/libsingular_julia/libsingular_julia@1.5/build_tarballs.jl
Needs to wait for PR #2380 having landed in the registry.
=> Update libsingular to 0.5 for Julia 1.5

C/CUDA/CUDA_full@10.0/build_tarballs.jl, C/CUDA/CUDA_full@10.1/build_tarballs.jl, C/CUDA/CUDA_full@10.2/build_tarballs.jl, C/CUDA/CUDA_full@11.0/build_tarballs.jl, C/CUDA/CUDA_full@11.1/build_tarballs.jl, C/CUDA/CUDA_full@11.2/build_tarballs.jl, C/CUDA/CUDA_full@9.0/build_tarballs.jl, C/CUDA/CUDA_full@9.2/build_tarballs.jl, G/GTK3/build_tarballs.jl, L/libjulia/common.jl, M/MathGL/build_tarballs.jl, M/marble/build_tarballs.jl, Q/Qt/build_tarballs.jl, Q/qwtw/build_tarballs.jl
This should in the final version skip ci & skip build, I think, but it seems prudent to first test if it works?
=> Remove workarounds for ninja/samurai bug

L/libsingular_julia/common.jl, L/libsingular_julia/libsingular_julia@1.3/build_tarballs.jl
@fingolfin: Is this the correct way? Do I need to wait with the 1.4 + 1.5 versions until this here is merged?
=> Update libsingular to 0.6 for Julia 1.3

L/libsingular_julia/libsingular_julia@1.4/build_tarballs.jl
=> Update libsingular to 0.6 for Julia 1.4

M/MKL/build_tarballs.jl
Ref https://github.com/JuliaLang/julia/issues/38993
=> [MKL] Rebuild to fix permissions of libraries on Windows

I/IntelOpenMP/build_tarballs.jl
Ref https://github.com/JuliaLang/julia/issues/38993
=> [IntelOpenMP] Simplify script and rebuild to make libraries executable

I/IntelOpenMP/build_tarballs.jl
Ref https://github.com/JuliaMath/FFTW.jl/pull/178#issuecomment-761904389
=> [IntelOpenMP] Do not run autofix for macOS

P/PCRE2/build_tarballs.jl, P/PCRE2/bundled/patches/sljit-apple-silicon-support.patch
Also including the sljit fix which provides support for Apple Silicon (https://bugs.exim.org/show_bug.cgi?id=2618#c20). Part of the work in https://github.com/JuliaLang/julia/issues/36617
=> [PCRE2] Bump to PCRE2 10.36

Q/qwtw/build_tarballs.jl
=> [qwtw] 3D lines/surfaces added (for linux only)

A/AMGX/build_tarballs.jl, A/AMGX/bundled/patches/fix-regex-syntax-cmake.patch
https://github.com/NVIDIA/AMGX
The latest released version seems to only support CUDA 10 and earlier.
cc @maleadt
=> AMGX - Initial recipe for v2.1.0. 

G/GnuTLS/build_tarballs.jl
<s>Draft because if PR #2078 eventually works out, this can be extended to cover FreeBSD as well.</s>
Once PR #2078 is merged, we can see if building on FreeBSD works or not.
=> Rebuild GnuTLS

G/GAP/build_tarballs.jl
<s>This only needs changes to the wrappers, so I think we can use [skip build]</s>
OK had to change the sources, too, as the initial version of this revealed a bug
=> GAP: update, add init_block

N/NetCDF/NetCDF@julia-1.6/build_tarballs.jl
=> [NetCDF] Add recipe for Julia v1.6

D/DGGRID7/build_tarballs.jl
The tool DGGRIDv7 by Kevin Sahr for use multi-platform in Julia
[https://github.com/sahrk/DGGRID](https://github.com/sahrk/DGGRID)
with some patches to make the build also work on mingw/Windows
Other popular DGGIRD bundles are in R and Python
- https://github.com/r-barnes/dggridR
- https://github.com/allixender/dggrid4py/
=> DGGRID tool for Dicrete Global Grid Systems

P/pigz/build_tarballs.jl
I know there are some platforms that don't work. The downloads kept stalling so I'm checking them here.
=> [pigz] Create initial build for pigz

R/rdma_core/build_tarballs.jl
=> [RDMA-CORE] Build v33.1

L/libnl/build_tarballs.jl
Otherwise rdma-core is unhappy https://github.com/JuliaRegistries/General/runs/1799362054
=> [libnl] add libnl-route-3 as a product

F/fzf/build_tarballs.jl
https://github.com/junegunn/fzf/releases/tag/0.25.0
=> [fzf] update to version 0.25.0

L/librealsense/build_tarballs.jl
Updating librealsense to 2.41
only changed the version and commit id
=> Update librealsense to 2.41

L/LibUnwind/build_tarballs.jl, L/LibUnwind/bundled/patches/libunwind-cfa-rsp.patch
See https://github.com/JuliaLang/julia/pull/39553.
=> Carry Libuwnind CFA RSP patch

Z/ZeroMQ/build_tarballs.jl
=> [ZeroMQ] add libsodium as a dependency

T/tippecanoe/build_tarballs.jl
Fixed up and should be good to merge. Thanks for the help, @giordano : )
~~I've no idea if this will work. I'm hoping that the CI will tell me : )~~
~~Mostly copied from the `tmux` build script.~~
=> Add tippecanoe builder

.ci/register_package.jl, F/flux_core/build_tarballs.jl
Registration of #2512 failed due to HBD not being filtered out.
=> filter out HostBuildDependencies

L/licensecheck/build_tarballs.jl, L/licensecheck/buildtarballs.jl, L/licensecheck/bundled/main.go
I didn't test locally, but the other go packages look super easy so hopefully it works :)
=> add licensecheck

F/FastTransforms/build_tarballs.jl
Adjoint and transposed transforms for reverse-mode automatic differentiation
=> [FastTransforms] v0.5.0

I/ICU/build_tarballs.jl
Libical seems to require at least this version
=> Bump [ICU] version

.ci/Manifest.toml, L/LibCURL/build_tarballs.jl
Should fix https://github.com/JuliaPackaging/Yggdrasil/issues/2438. I haven't had luck validating this locally so we'll see how the CI does.
=> [LibCURL] Request macOS 11.0+ on Apple Silicon

T/Tokei/build_tarballs.jl
I mimicked tectonic and made sure to add the feature flag to get JSON output
=> [tokei] use prebuilt executables

P/PROJ/PROJ@julia-1.6/build_tarballs.jl
=> [PROJ] add julia 1.6 build

T/Tokei/build_tarballs.jl
try to fix https://github.com/JuliaPackaging/Yggdrasil/pull/2540#issuecomment-778864910
=> [tokei] unpack archives

C/CUDA/CUDA@10.0/build_tarballs.jl, C/CUDA/CUDA@10.1/build_tarballs.jl, C/CUDA/CUDA@10.2/build_tarballs.jl, C/CUDA/CUDA@11.0/build_tarballs.jl, C/CUDA/CUDA@11.1/build_tarballs.jl, C/CUDA/CUDA@11.2/build_tarballs.jl, C/CUDA/CUDA@9.0/build_tarballs.jl, C/CUDA/CUDA@9.2/build_tarballs.jl, L/LLVM/common.jl
This was changed in https://github.com/JuliaPackaging/BinaryBuilderBase.jl/commit/c91148e1bbcae698793b8e3b5ca8feed0644d332#diff-48f90c9f7d86cf3e80c85fa66b31702f51d91cb8f6ce531575d7cc1f85f200f9R356
=> Fix clearing-out the prefix.

C/CompilerSupportLibraries/build_tarballs.jl
Also get new codesigned versions on Darwin!
=> [CSL] Bump to get new versions from new GCCs

G/GDAL/GDAL@julia-1.6/build_tarballs.jl
Julia 1.6 companion PR of #2566
=> [GDAL] specify patch version of proj_jll_version

F/FastJet_Julia_Wrapper/build_tarballs.jl, L/libjulia/common.jl, L/libjulia/libjulia@1.3/build_tarballs.jl, L/libjulia/libjulia@1.4/build_tarballs.jl, L/libjulia/libjulia@1.5/build_tarballs.jl
@fingolfin I believe this is the culprit of
https://github.com/JuliaPackaging/Yggdrasil/pull/2543#discussion_r575727249.
=> [libjulia] Do not use global `ARGS`

P/PCRE2/build_tarballs.jl, P/PCRE2/bundled/patches/sljit-nomprotect.patch
X-ref: https://github.com/zherczeg/sljit/pull/105
=> Backport SLJIT fix for Apple Silicon restrictions on mapping WX pages

W/wget/build_tarballs.jl
Draft while PRs #2078 and #2079 are not merged.
=> Update wget recipe

L/libblastrampoline/build_tarballs.jl
This should fix our MKL issues
=> [libblastrampoline] Update to v3.0.1

E/Elfutils/build_tarballs.jl, E/Elfutils/bundled/error.h, E/Elfutils/bundled/patches/fix-aarch64_fregs.patch, E/Elfutils/bundled/patches/musl-asm-ptrace-h.patch, E/Elfutils/bundled/patches/musl-cdefs.patch, E/Elfutils/bundled/patches/musl-fts-obstack.patch, E/Elfutils/bundled/patches/musl-macros.patch, E/Elfutils/bundled/patches/musl-qsort_r.patch, E/Elfutils/bundled/patches/musl-strerror_r.patch, E/Elfutils/bundled/patches/musl-strndupa.patch
Depends on #2626 , #2627 , #2628 
Conditionally pulls in patches from Alpine Linux to fix build issues
=> [Elfutils] Build on musl

L/LLVM/LLVM_full@11.0.1/bundled/patches/0704-D97435-AArch64-movaddrreg.patch, L/LLVM/LLVM_full@11.0.1/bundled/patches/0705-D97571-AArch64-loh.patch, L/LLVM/LLVM_full@11.0.1/bundled/patches/0706-aarch64-addrspace.patch, L/LLVM/LLVM_full@11.0.1/bundled/patches/0707-PR49357-AArch64-FastIsel-bug.patch
Includes patches for
https://github.com/JuliaLang/julia/issues/39823
https://github.com/JuliaLang/julia/issues/39820
https://github.com/JuliaLang/julia/issues/39818
as well as an issue causing an assertion in
debug mode due to address spaces.
=> Add LLVM AArch64 patches

.ci/Manifest.toml
Among other things, it includes
https://github.com/JuliaPackaging/BinaryBuilderBase.jl/pull/120.  CC: @vchuravy
=> [AZP] Update BinaryBuilder and BinaryBuilderBase

H/Help2man/build_tarballs.jl
This adds `help2man` as a `FileProduct`
=> Adds Help2man

S/S2Geometry/build_tarballs.jl, S/S2Geometry/bundled/patches/disable-s2testing.patch
An attempt to build [S2Geometry](https://github.com/google/s2geometry) for use with Julia.
=> add S2Geometry builder

L/libsingular_julia/common.jl, L/libsingular_julia/libsingular_julia@1.3/build_tarballs.jl
=> Update libsingular to 0.9 for Julia 1.3

L/libsingular_julia/libsingular_julia@1.4/build_tarballs.jl
=> Update libsingular to 0.9 for Julia 1.4

L/libsingular_julia/libsingular_julia@1.5/build_tarballs.jl
=> Update libsingular to 0.9 for Julia 1.5

G/Ghostscript/build_tarballs.jl
~This is a test to make sure the Libtiff is needed, I feel like it isn't.~ It does look like it isn't needed
=> [Ghostscript] Remove useless dependency

S/startin/build_tarballs.jl
(https://github.com/hugoledoux/startin) written in Rust by Hugo Ledoux (https://3d.bk.tudelft.nl/hledoux).
=> Add startin library for Delaunay triangulation

C/Coin-OR/Cbc/build_tarballs.jl, C/Coin-OR/coin-or-common.jl
Let's see if anything breaks...
=> [Cbc] bump to 2.10.5

G/GLPK/build_tarballs.jl
See the following for the release notes:
https://lists.gnu.org/archive/html/info-gnu/2020-12/msg00007.html
=> [GLPK] bump to version 5.0

C/catch22/build_tarballs.jl
* Package name: catch22
* Version: v0.2.1
=> Wizard recipe: catch22-v0.2.1

A/Antic/build_tarballs.jl, N/normaliz/build_tarballs.jl, S/Singular/build_tarballs.jl
=> Use compat for dependency on FLINT_jll

generate_buildjl.jl
=> Fix generate_buildjl.jl

L/libsingular_julia/common.jl, L/libsingular_julia/libsingular_julia@1.3/build_tarballs.jl
CC @thofma @tthsqe12
I want to have this ASAP so we can use the new Singular_jll in Singular.jl; of course we can then soon after make a new release with Dan's improvements
=> libsingular_julia: use new compat feature (for Julia 1.3)

L/libsingular_julia/libsingular_julia@1.4/build_tarballs.jl
To be merged after #2675 has hit the registry
=> libsingular_julia: use new compat feature (for Julia 1.4)

L/libsingular_julia/libsingular_julia@1.5/build_tarballs.jl
To be merged after #2676 has hit the registry
=> libsingular_julia: use new compat feature (for Julia 1.5)

P/pandoc_crossref/build_tarballs.jl
Related to https://github.com/JuliaPackaging/Yggdrasil/pull/2697.
=> [pandoc-crossref] Version 0.3.9.1

F/FastTransforms/build_tarballs.jl
Fix spin-weighted spherical harmonics with |m| = 1
https://github.com/JuliaApproximation/FastTransforms.jl/issues/139
It's marked draft because I want to try fixing OpenMP on macOS
https://github.com/JuliaApproximation/FastTransforms.jl/issues/136
=> [FastTransforms] v0.5.1

F/FlowCutterPACE17/build_tarballs.jl
Adds Flow Cutter PACE17: https://github.com/kit-algo/flow-cutter-pace17
=> Add FlowCutterPACE17

.devcontainer/Dockerfile
=> [Codespaces] Install stable version of BinaryBuilder

R/Rmath/build_tarballs.jl
Fix #2717 
I am also trying to update the Rmath-julia sources, so if that looks good, we might as well bump to a new version.
=> [Do not merge] [Rmath] Build for experimental platforms

L/libsingular_julia/libsingular_julia@1.5/build_tarballs.jl
Should probably wait till #2736 hits the registry
=> Update libsingular_julia to latest (for Julia 1.5)

Q/qr_mumps/build_tarballs.jl
=> [QR_MUMPS] Fix routines with complex numbers

Q/Qt5Svg/build_tarballs.jl
Qt Svg library. This is a dependency for Gnuplot and QML.jl.
=> [QT] Add Qt5Svg

Q/Qt5Tools/build_tarballs.jl
Tools like `qdoc` and `lrelease`. The latter is needed for Gnuplot.
=> [QT] Add Qt5Tools

L/Libbpf/build_tarballs.jl, L/Libbpf/bundled/patches/musl-add-stddef.patch
=> Add libbpf builder

D/DASKR/build_tarballs.jl
Builds the double-precision solvers of [DASKR](https://www.netlib.org/ode/daskr.tgz)
=> Adds DASKR tarball build script

Q/Qt5Declarative/build_tarballs.jl
Qt5 QML base package and a dependency for QML.jl.
=> [Qt] Add Qt5Declarative package

O/OpenBLAS/OpenBLAS32@0.3.13/bundled/patches/openblas-exshift.patch, O/OpenBLAS/OpenBLAS@0.3.13/bundled/patches/openblas-exshift.patch, O/OpenBLAS/OpenBLASHighCoreCount@0.3.13/bundled/patches/openblas-exshift.patch
Fix https://github.com/JuliaLang/julia/issues/40279
=> [OpenBLAS] Add openblas-exshift.patch for 0.3.13

L/libblastrampoline/build_tarballs.jl
More armv7l fixes, this time for interface autodetection code
=> [libblastrampoline] bump to v3.0.4

P/primecount/build_tarballs.jl
* Package name: primecount
* Version: v6.4.0
=> Wizard recipe: primecount-v6.4.0

P/primecount/build_tarballs.jl, P/primecount/bundled/patches/0001-Allow-disabling-building-static-library-for-Windows.patch
=> [primecount] Upgrade to v6.5, build shared library, add missing dep

0_RootFS/Go/build_tarballs.jl
Was attempting to compile Kubernetes from source and encountered the following:
```
Detected go version: go version go1.13 linux/amd64.
Kubernetes requires go1.15.0 or greater.
Please install go1.15.0 or later.
```
Seems like a good time for an upgrade :)
=> [RootFS] Update Go compiler shard to 1.16.3

N/NetCDFF/build_tarballs.jl
* Package name: NetCDFF
* Version: v4.5.3
=> Wizard recipe: NetCDFF-v4.5.3

.ci/Manifest.toml
Changelogs:
* BinaryBuilder: https://github.com/JuliaPackaging/BinaryBuilder.jl/compare/v0.3.0...v0.3.1
* BinaryBuilderBase: https://github.com/JuliaPackaging/BinaryBuilderBase.jl/compare/v0.5.0...v0.5.2
=> [AZP] Update BinaryBuilder to v0.3.1 and BinaryBuilderBase to v0.5.2

C/Coin-OR/Bonmin/build_tarballs.jl
x-ref https://github.com/JuliaRegistries/General/pull/33796#issuecomment-815384152
=> [Bonmin] expose libbonminampl

I/Ipopt/build_tarballs.jl
x-ref https://github.com/JuliaRegistries/General/pull/33796#issuecomment-815384152
=> [Ipopt] expose libipoptamplinterface

L/libcgal_julia/libcgal_julia@1.4/build_tarballs.jl
Waiting on JuliaRegistries/General#33856
=> [libcgal-julia] Update v0.16.1 (Julia 1.4)

L/libcgal_julia/libcgal_julia@1.6/build_tarballs.jl
Waiting on JuliaRegistries/General#33860
=> [libcgal-julia] Update v0.16.1 (Julia 1.6)

C/Coin-OR/Couenne/build_tarballs.jl
With this build I get
```console
% nm libCouenne.so|c++filt|grep OsiClpSolverInterface::getRowName
U OsiClpSolverInterface::getRowName[abi:cxx11](int, unsigned int) const
U virtual thunk to OsiClpSolverInterface::getRowName[abi:cxx11](int, unsigned int) const
```
consistent with `libOsiClp.so` for `x86_64-linux-gnu-libgfortran5-cxx11` loaded
at runtime.  More details about the rabbit hole in the comments added to the builder.
CC: @odow
=> [Couenne] Build with GCC 7

C/Coin-OR/Bonmin/build_tarballs.jl
As suggested https://github.com/JuliaPackaging/Yggdrasil/pull/2730#discussion_r610213305.
=> [Bonmin] stop including IpoptConfig.h in tarball

C/CImPlot/build_tarballs.jl
Updated build of binaries for ImPlot.jl
=> Upgrade to implot v0.9 and imgui v1.82

I/IOAPI/build_tarballs.jl
* Package name: IOAPI
* Version: v3.2.0
=> Wizard recipe: IOAPI-v3.2.0

N/nPth/build_tarballs.jl, N/npth/build_tarballs.jl
=> [npth] Add builder

L/Libassuan/build_tarballs.jl, L/libassuan/build_tarballs.jl
Seems to build right on everything (including i686 windows) except x86_64 windows... Same issue as previously, although a straightforward copy paste solution didn't work. Will try to fix shortly.
=> [libassuan] Add builder

Q/Qt5QuickControls2/build_tarballs.jl
Needed for QML.jl based on the split Qt5 packages.
=> [Qt] Add Qt5QuickControls2 package

Q/Qt5QuickControls/build_tarballs.jl
Needed for QML.jl based on the split Qt5 packages.
=> [Qt] Add Qt5QuickControls builder

J/jlqml/build_tarballs.jl
Needed for a Julia1.6-compatible QML.jl
=> [jlqml] Version 0.2

G/GnuPG/build_tarballs.jl, G/GnuPG/bundled/patches/intel-linux-gnu-add-rt-lib.patch
=> [GnuPG] Add builder

G/GDB/build_tarballs.jl
* Package name: GDB
* Version: v10.1.0
=> Wizard recipe: GDB-v10.1.0

R/racket/build_tarballs.jl
* Package name: racket
* Version: v8.0.0
=> Wizard recipe: racket-v8.0.0

C/Coin-OR/Osi/build_tarballs.jl, C/Coin-OR/coin-or-common.jl
Same motivation and reasoning as https://github.com/JuliaPackaging/Yggdrasil/pull/2844.
=> [Osi] rebuild 0.108.6

S/SuiteSparse/SuiteSparse/bundled/SuiteSparse_wrapper/SuiteSparse_wrapper.c
Update Yggdrasil to reflect the changes in https://github.com/JuliaLang/julia/pull/38919.
=> Copy SuiteSparse_wrapper.c from Julia repo

U/UserNSSandbox/build_tarballs.jl, U/UserNSSandbox/bundled/sandbox.c
I also realized I had forgotten to bump the version; we just use dates here?
=> Fix sandbox shm mount.

Q/Qt6Base/build_tarballs.jl
Second stage for adding the Qt6Base package, now for all platforms. 🤞
=> [Qt] Qt6Base builder for all platforms

K/kubectl/build_tarballs.jl
Hopefully this can be replaced with https://github.com/JuliaPackaging/Yggdrasil/pull/2797 in the future.
=> [kubectl] Support aarch-linux-gnu

R/raptor/build_tarballs.jl
* Package name: raptor
* Version: v0.0.1
=> Wizard recipe: raptor-v0.0.1

L/libsingular_julia/common.jl, L/libsingular_julia/libsingular_julia@1.3/build_tarballs.jl
=> Update libsingular to 0.10 for Julia 1.3

O/OpenEXR/build_tarballs.jl
~Currently waiting on #2878. Once it is merged this can refer to `Imath_jll` as a dependency.~ Done.
=> [OpenEXR] new package

O/OpenEXR/build_tarballs.jl
=> [OpenEXR] Target gcc5

L/libudfread/build_tarballs.jl
* Package name: libudfread
* Version: v1.1.2
=> Wizard recipe: libudfread-v1.1.2

Z/zimg/build_tarballs.jl
* Package name: zimg
* Version: v3.0.1
=> Wizard recipe: zimg-v3.0.1

.ci/Manifest.toml, C/CompilerSupportLibraries/build_tarballs.jl
Third (fourth?) time's the charm.
=> [CSL] bump to fix macOS (again)

V/Vulkan_Headers/build_tarballs.jl
=> Vulkan_Headers v1.2.177

Q/Qt5Charts/build_tarballs.jl
Needed to use chart QML components in the new split package system.
See https://github.com/barche/QML.jl/issues/118
=> [Qt] Add Qt5Charts

Y/YASM/build_tarballs.jl
* Package name: YASM
* Version: v1.3.0
=> Wizard recipe: YASM-v1.3.0

L/libbluray/build_tarballs.jl
* Package name: libbluray
* Version: v1.3.0
=> Wizard recipe: libbluray-v1.3.0

L/libsixel/build_tarballs.jl
* Package name: libsixel
* Version: v1.8.6
=> Wizard recipe: libsixel-v1.8.6

C/Clingcon/build_tarballs.jl
A little cart before the horse here given I haven't even finished the Clingo wrapper. Feel free to close since this won't be wrapped for at least 2 months.
=> [Clingcon] Add builder

H/HELICS/build_tarballs.jl
Updates the HELICS package to v2.7.0
=> [HELICS] update to v2.7.0

A/ABC/build_tarballs.jl
new recipe for the ABC logic synthesis system
=> ABC: System for Sequential Logic Synthesis and Formal Verification

C/CUDA/CUDA_loader/build_10.0.jl, C/CUDA/CUDA_loader/build_10.1.jl, C/CUDA/CUDA_loader/build_10.2.jl, C/CUDA/CUDA_loader/build_11.0.jl, C/CUDA/CUDA_loader/build_11.1.jl, C/CUDA/CUDA_loader/build_11.2.jl, C/CUDA/CUDA_loader/build_11.3.jl, C/CUDA/CUDA_loader/build_9.0.jl, C/CUDA/CUDA_loader/build_9.2.jl
Removing some unused libraries, adding others and additional compiler executables.
=> [CUDA] Re-organize loader recipe

A/ATK/build_tarballs.jl
Required by more recent versions of Gtk (#2943)
=> [ATK] Upgrade to v2.36.0

S/SFML/build_tarballs.jl
=> SFML: Build with BB instead of using prebuilt tarballs on Linux

B/Bzip2/build_tarballs.jl
Before merging I want to do some tests to make sure I'm not going to break anything.
=> [Bzip2] Upgrade to v1.0.8 and build for experimental platforms

C/CSFML/build_tarballs.jl
=> CSFML: Enable all x86 Linux platforms

X/xsum/build_tarballs.jl
Includes new routines to add one accumulator to another, among other things.
=> update xsum to latest version

L/libjulia/common.jl
This is probably going to fail for aarch64-apple-darwin
=> [libjulia] Build for experimental platforms with Julia v1.7

L/libsingular_julia/common.jl, L/libsingular_julia/libsingular_julia@1.3/build_tarballs.jl
=> Update libsingular to 0.11 for Julia 1.3

O/OpenMPI/build_tarballs.jl
=> update Open MPI to 4.1.1

L/libsingular_julia/libsingular_julia@1.5/build_tarballs.jl
=> Update libsingular to 0.11 for Julia 1.5

R/RDKit/build_tarballs.jl
fixes 2 of the bugs in https://github.com/eloyfelix/RDKitMinimalLib.jl
=> [RDKit ] update commit

L/LLVM/libLLVM_assert@12.0.0/build_tarballs.jl
=> [libLLVM_assert@12] Require Julia v1.7

S/SuiteSparse/SSGraphBLAS/build_tarballs.jl
New version, force compat to 1.6?
=> [SSGraphBLAS] v5.0 - Don't Merge

O/Openresty/build_tarballs.jl
Update Openresty build to v1.19.3
=> Update Openresty to 1.19.3

F/FLINT/build_tarballs.jl
This is a prerelease of 2.8.0, so I think according to our versioning scheme this should be v"200.790.000".
@fingolfin
=> [FLINT]: New version

.ci/Manifest.toml
Changes:
* BinaryBuilderBase: https://github.com/JuliaPackaging/BinaryBuilderBase.jl/compare/v0.6.3...v0.6.4
* BinaryBuilder: https://github.com/JuliaPackaging/BinaryBuilder.jl/compare/v0.3.3...v0.3.4
=> [AZP] Update BinaryBuilderBase and BinaryBuilder

D/Dbus/build_tarballs.jl, F/Fontconfig/build_tarballs.jl, G/GDAL/common.jl, G/Geant4/build_tarballs.jl, G/Git/build_tarballs.jl, G/Graphviz/build_tarballs.jl, L/LibArchive/build_tarballs.jl, P/Python/build_tarballs.jl, W/Wayland/build_tarballs.jl
Companion pull request in the General registry: https://github.com/JuliaRegistries/General/pull/36825
=> Fix compat of packages depending on Expat_jll

G/Glib/build_tarballs.jl, H/HarfBuzz/build_tarballs.jl, P/Python/build_tarballs.jl, W/Wayland/build_tarballs.jl
Companion pull request in the General registry: https://github.com/JuliaRegistries/General/pull/36866
=> Fix compat of packages depending on `Libffi_jll`

A/ADIOS2/build_tarballs.jl
[ADIOS2](https://github.com/ornladios/ADIOS2) is a high-performance I/O library, comparable to HDF5.
=> New package ADIOS2

L/libsingular_julia/common.jl, L/libsingular_julia/libsingular_julia@1.6/build_tarballs.jl
Is this what we had in mind @benlorenz @fingolfin? I tested it locally with 1.3, 1.4, 1.5 and 1.6. (CC @tthsqe12)
=> [libsingular_julia] Bump to 0.12 and fix dependency bugs

B/Bzip2/build_tarballs.jl, F/Fontconfig/build_tarballs.jl, F/FreeType2/build_tarballs.jl
This reverts commit 11e04b100a08a7debc1f1a991dc5a32728f7d8f0.
=> Revert "[Bzip2] Build old version v1.0.7 ABI-compatible with v1.0.8 (#3025)"

B/BlueZ/build_tarballs.jl
This seems to get pretty far just using the host version of Libical, but I think a target version is needed? Ref #2564
=> [BlueZ] Add builder

C/Ccluster/build_tarballs.jl
* Package name: Ccluster
* Version: v1.1.6
=> Wizard recipe: Ccluster-v1.1.6

G/Git/build_tarballs.jl, H/HarfBuzz/build_tarballs.jl, N/Ncurses/build_tarballs.jl, P/PulseAudio/build_tarballs.jl, Q/Qemu/build_tarballs.jl, U/util_linux/build_tarballs.jl, X/Xorg_libXpm/build_tarballs.jl
Companion pull request in the General registry: https://github.com/JuliaRegistries/General/pull/37160
=> Fix compat of packages depending on `Gettext_jll`

C/CImGuiPack/build_tarballs.jl
prepare for https://github.com/Gnimuc/CImGui.jl/discussions/43
=> New recipe: CImGuiPack

L/libgraphicsmagic/build_tarballs.jl
* Package name: libgraphicsmagic
* Version: v1.3.0
=> Wizard recipe: libgraphicsmagic-v1.3.0

G/GnuPG/build_tarballs.jl, L/Libassuan/build_tarballs.jl, L/Libgcrypt/build_tarballs.jl, L/Libksba/build_tarballs.jl
Companion pull request to the General registry: https://github.com/JuliaRegistries/General/pull/37287
=> Fix compat of packages depending on `Libgpg_error_jll`

L/libgraphicsmagic/build_tarballs.jl
adding more optional deps to expand functionality
=> [libgraphicsmagic] Add more optional deps to expand functionality

L/libpolymake_julia/common.jl, L/libpolymake_julia/libpolymake_julia@1.3/build_tarballs.jl
Gonna check the logs this time before marking this as ready.
=> [libpolymake_julia] bump for 4.4 (see #3057) for julia 1.3

X/XSLT/build_tarballs.jl
Wait, I need to build libgcrypt for the new platforms
=> [XSLT] Upgrade to v1.1.34 and build for experimental platforms

P/polymake/build_tarballs.jl, P/polymake/bundled/patches/minkowski_sum.patch
was just merged upstream, needed until polymake 4.5 is released to fix tests in Oscar.jl.
=> [polymake] add patch to fix bug in minkowski_sum
