JuliaPackaging/Yggdrasil

Zstd/build_tarballs.jl

Based on https://github.com/bicycle1885/ZstdBuilder, cc @bicycle1885. Updated to the newest version of zstd.

Add builder for Zstd

---

GSL/build_tarballs.jl

This is the builder for the [GNU Scientific Library](https://www.gnu.org/software/gsl/).  Originally at https://github.com/giordano/GSLBuilder.jl.

Add builder for GSL

---

H/HDF5/build_tarballs.jl

- Use binaries provided from msys2 (they finally updated hdf5 after pushing the patches I sent).
- Reverted the changes made before upgrading to use my binaries.

Upgrade to msys2 binaries

---

F/FriBidi/build_tarballs.jl

This is a dependency for Pango.
I'm building this with autotools, but it supports also meson.  When we get a basic support for meson in BinaryBuilder (https://github.com/JuliaPackaging/BinaryBuilder.jl/issues/437) this should be a good test case, as it's way simpler than glib or pango.

Add builder for FriBidi

---

L/LZO/build_tarballs.jl

This is an optional dependency of Cairo, but I see that most Linux distros build Cairo with this

Add builder for LZO

---

X/X11/build_tarballs.jl

It's working for all platforms, excluding x86_64 Windows.  We get the following error:
```
imDefIc.c: In function '_XimGetInputStyle':
imDefIc.c:1342:21: error: cast from pointer to integer of different size [-Werror=pointer-to-int-cast]
*input_style = (XIMStyle)p->value;
^
cc1: some warnings being treated as errors
```
We can either ignore the error or fix it, now I'm exhausted and can't look into this.
**Edit**: even with `make CFLAGS="-WNO-error=pointer-to-int-cast"` I'm getting a ton of other errors (real errors, not something triggered by `-Werror`) :confused:

Add builder for libX11

---

L/Libuuid/build_tarballs.jl

This is required by fontconfig, which is needed by Pango and Cairo on Linux and FreeBSD.
It's incredibly hard to find a single portable implementation of libuuid that can be cross-compiled for all platforms.  Apart this one in util-linux, I found:
* this: https://sourceforge.net/projects/libuuid/, despite being advertised as "portable", it doesn't work at all on Windows, includes Unix-only header files and tries to open files like `/dev/random`
* this could be a good cross-platform choice: http://www.ossp.org/pkg/lib/uuid/ (source code can be found, e.g., at http://deb.debian.org/debian/pool/main/o/ossp-uuid/ossp-uuid_1.6.2.orig.tar.gz), however it can't be cross-compiled as it performs some checks at configure time by running code that it compiles :man_facepalming:

Add builder for libuuid

---

L/Libffi/build_tarballs.jl

`BinaryProvider.jl` doesn't seem to be able to find libraries in `./lib64`.  This is a _dirty_ hack to work around this.

[Libffi] Link libraries in $prefix/lib64 to $prefix/lib

---

G/Graphite2/build_tarballs.jl

I'm sorry this is is still for current BinaryBuilder.  Of course it fails to build for Windows, but this is needed by HarfBuzz, which is needed by Pango only on Linux and FreeBSD (see issue #48), so it should be fine.

Add builder for Graphite2

---

H/HarfBuzz/build_tarballs.jl
H/HarfBuzz/bundled/patches/config_ac-freetype2_version.patch

It doesn't work on Windows as it requires Graphite2 (PR #49).  This is required by Pango on Linux and FreeBSD, see #48.

Add builder for HarfBuzz

---

P/Pango/build_tarballs.jl

Currently this works only for macOS and Windows, as it needs native backend in Cairo for Linux and FreeBSD (see #39)

Add builder for Pango

---

F/FFTW/build_tarballs.jl

Fix #5 
I copied the [build_tarballs.jl](https://github.com/JuliaMath/FFTWBuilder/blob/master/build_tarballs.jl) from the FFTW Builder repo.

Add FFTW builder

---

F/FFTW/build_tarballs.jl

Altivec was deprecated years ago in favor of VSX, and I think we only support Power8 or later architectures that have VSX (which provides both double and single precision SIMD instructions).

FFTW: use VSX, not Altivec

---

S/SharedMimeInfo/build_tarballs.jl

Started from builder at https://github.com/ianshmean/SharedMimeInfoBuilder by @ianshmean, upgraded to latest version of the package (v1.12) and compatible with future BinaryBuilder.jl

Add builder for shared-mime-info

---

L/Libcroco/build_tarballs.jl

I can't test this now, my main concern are the dependencies, but I'm fairly confident that I got the direct ones right.  The full list of dependencies is Glib, XML2, libiconv, PCRE, zlib, Gettext.  Also, I'm not sure that after the latest changes in BinaryBuilder changing `RANLIB` for macOS will still be necessary.

Add builder for libcroco

---

F/FFTW/build_tarballs.jl

Use new upstream tarball to fix missing mingw export (JuliaMath/FFTW.jl#110).   Also disable avx-512 for now since it is still marked "experimental" upstream.

new FFTW upstream tarball

---

L/Libmount/build_tarballs.jl

This is required by glib 2.62, in case we want to upgrade it.  Glib requires libmount only on Linux, so it's fine excluding all other operating systems.
Note that I'm getting errors when compiling for `powerpc64le-linux-gnu`:
```
In file included from libmount/src/context.c:42:0:
./include/namespace.h:34:19: error: static declaration of ‘unshare’ follows non-static declaration
static inline int unshare(int flags)
^
In file included from /opt/powerpc64le-linux-gnu/powerpc64le-linux-gnu/sys-root/usr/include/sched.h:44:0,
from ./include/namespace.h:5,
from libmount/src/context.c:42:
/opt/powerpc64le-linux-gnu/powerpc64le-linux-gnu/sys-root/usr/include/bits/sched.h:86:12: note: previous declaration of ‘unshare’ was here
extern int unshare (int __flags) __THROW;
^
In file included from …
```

Add builder for libmount

---

G/gdk-pixbuf/build_tarballs.jl

This is a dependency of GTK, see #62.
Note: version number is a lie, as I checked out latest master.  The latest stable version, v2.38.2, can't be cross-compiled because of this issue: https://gitlab.gnome.org/GNOME/gdk-pixbuf/issues/64

Add builder for gdk-pixbuf

---

W/Wayland/build_tarballs.jl
W/Wayland/bundled/patches/Makefile_in.patch

Optional dependency of GTK on Linux and FreeBSD, see #62.  This builder is only for Linux, I'm excluding FreeBSD because it requires a lot of work
<s>Note: this doesn't currently work on FreeBSD!  Wayland needs to be heavily patched in order to be compiled for FreeBSD, see https://svnweb.freebsd.org/ports/head/graphics/wayland/files/ :disappointed:  Those patches have to be manually adapted, as they are for Wayland 1.16, while this builder is for 1.17, and I think not all of those changes are needed in our case.
I started to adapt very few changes, before I gave up, it's going to be a lot of work.</s>

Add builder for Wayland

---

O/OpenBLAS/build_tarballs.jl

Latest version claims some nice HASWELL DGEMM speedups:
https://github.com/xianyi/OpenBLAS/issues/2225
We should also start experimenting with `USE_TLS=1`.

Update openblas to 0.3.7

---

L/Libpciaccess/build_tarballs.jl

<s>Not tested at all, it requires a new version of the X11 mega package (see #75), in particular it needs xorg-utils-macros.</s>  Ready to go, tested on all platforms we care about

Add builder for libpciaccess

---

S/SDL2/build_tarballs.jl

This is the builder for [SDL2](https://www.libsdl.org/).  Originally at https://github.com/giordano/SDL2Builder.
<s>Note: this is ***not*** working.  My understanding is that it compiles for the wrong target system.  E.g., the compiler used for macOS is `/opt/x86_64-linux-gnu/tools/clang --sysroot=/opt/x86_64-apple-darwin14/x86_64-apple-darwin14/sys-root` instead of `/opt/x86_64-linux-gnu/tools/clang -target x86_64-apple-darwin14 --sysroot /opt/x86_64-apple-darwin14/x86_64-apple-darwin14/sys-root` (note the missing `-target` option).</s> Everything works now.
CC: @aviks.

Add builder for SDL2

---

W/Wayland_protocols/build_tarballs.jl

Optional dependency of GTK on Linux, see #62.  However, I'm not sure how Wayland is going to find these files.... :confused:

Add builder for wayland-protocols

---

C/Cairo/build_tarballs.jl

Gtk3 on Windows requires at least Cairo 1.15.2 (see #62), let's give it the very latest version.
<s>I tested only on three platforms, it's very late here and it was going to take too long.</s>  Tested on all platforms, build is flawless

[Cairo] Upgrade to latest version

---

L/Libgpg_error/build_tarballs.jl

I have disabled the platforms (all with musl libc) that are not supported at all by this library.  Note: compilation is successful for FreeBSD, but it generates a static library instead of a shared one, despite the default is to generate the shared.  Explicitly asking for the shared library doesn't help.
This is an indirect dependency of GTK, see #62

Add builder for libgpg-error

---

N/Ncurses/build_tarballs.jl

This is one of the dozens of indirect dependencies of GTK on Linux and FreeBSD, see #62.
I had to disable macOS only because installation of executables fails and we can actually skip it by editing the Makefile (the error is: `error: /opt/x86_64-apple-darwin14/bin/x86_64-apple-darwin14-strip: unrecognized option: -p` :woman_shrugging:), for Windows compilation fails pretty early.  Anyway support of the package for these platforms is not important for GTK.

Add builder for ncurses

---

L/Libgcrypt/build_tarballs.jl

Indirect dependency of GTK, see #62.
The two extra configure options are not strictly needed for a successful compilation, but I've seen they're used e.g. by Debian and Arch Linux, I thought it was good to follow their example.  What do you think?

Add builder for libgcrypt

---

K/Keyutils/build_tarballs.jl

Indirect dependency of GTK, see #62.
Auditor spits out a few warnings, but the tarball is generated

Add builder for keyutils

---

G/Git/build_tarballs.jl

It doesn't work on macOS, as it needs curl (which is usually an optional dependency, but would be useful to have everywhere anyway), and on Windows, where it fails to configure because of missing `socklen_t` or equivalent.
A possibility for Windows could be to simply use the pre-built `.exe`s in https://github.com/git-for-windows/git/releases/tag/v2.23.0.windows.1 if we're sure that they're self-contained and don't need other dynamic libraries.  As an alternative, we can take the full `.tar.bz2` tarballs and install the `/usr` and `bin` directories in `${prefix}`
CC: @DilumAluthge

Add builder for Git

---

N/Ncurses/build_tarballs.jl

The changes are inspired by https://github.com/msys2/MINGW-packages/blob/44e66c3a332dc457f00b9a12d3efbb7be5dba66e/mingw-w64-ncurses/PKGBUILD and https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-ncurses/001-use-libsystre.patch.  Tested on all platforms.

Make Ncurses work for Windows, too

---

L/Libcap_ng/build_tarballs.jl

This is an indirect dependency of GTK3, see #62.

Add builder for libcap-ng

---

G/Gnome_themes_extra/build_tarballs.jl

Last library necessary for `Gtk.jl`, this one depends on gtk3, see #62.
Note: this works only on macOS, on Windows it's failing at `make` with the following error:
```
libtool:   error: cannot find the library '/workspace/destdir/x86_64-w64-mingw32/lib/../lib/libstdc++.la' or unhandled argument '/workspace/destdir/x86_64-w64-mingw32/lib/../lib/libstdc++.la'
```
I'm sure that you know how to deal with this :slightly_smiling_face:

Add builder for gnome-themes-extra

---

I/ICU/build_tarballs.jl

<s>This is only a stub, it doesn't work at all.</s>  Cross-compilation is quite complicated, it requires first a native build, e.g. see https://wiki.openttd.org/Cross-compiling_for_Windows#ICU.
PS: I started this because I thought ICU is an indirect dependency of GTK3, but actually I can't find anymore which package would depend on ICU :sweat_smile:

Add builder for ICU

---

0_RootFS/Rootfs/bundled/conf/profile.d/bb_utils.sh

I often need to use `find`, all those "Permission denied" messages bug me so much that I always need to silence them.
The second function is part of https://github.com/JuliaPackaging/BinaryBuilder.jl/issues/309.

Define quiet find and function to install license files

---

G/GLEW/build_tarballs.jl

CC: @colinxs.
PS: we could add a couple more of dependencies, currently not available: glu and libxmu, see https://www.archlinux.org/packages/extra/x86_64/glew/

[GLEW] Build for all platforms

---

D/Dbus/build_tarballs.jl

Indirect dependency of GTK, see #62 
Compared to https://git.alpinelinux.org/aports/tree/main/dbus/APKBUILD I disabled tests and doc.
There are a couple of hardcoded system directories that I'm not much sure what to do with... :confused:

Add builder for Dbus

---

A/at_spi2_core/build_tarballs.jl
D/Dbus/build_tarballs.jl

Indirect dependency of GTK, see #62.
I couldn't actually build for `powerpc64le-linux-gnu`, `ld` was complaining that couldn't find `libffi.so`.  I don't know if we need to do add `-L${prefix}/lib64` to linker options in the meson cross file (didn't try at all this option, but I didn't have any problem with all the other 64-bit platforms) or GCC v8 must be used (I couldn't install GCC 8 on my computer).

Add builder for at-spi2-core

---

G/GEOS/build_tarballs.jl

Based on existing build script at https://github.com/JuliaGeo/GEOSBuilder, but upgraded to the latest GEOS release.
Left out these lines for now, not sure if they are still needed:
https://github.com/JuliaGeo/GEOSBuilder/blob/56e53d1eed1cea8659826652a54aeda5350c6e01/build_tarballs.jl#L13-L17

add GEOS builder

---

X/xkbcommon/build_tarballs.jl
X/xkbcommon/bundled/patches/meson_build.patch
X/xkbcommon/bundled/patches/meson_options.patch

Direct dependency of GTK, when Wayland is enabled (i.e., only on Linux), see #62

Add builder for xkbcommon

---

C/Cairo/build_tarballs.jl
G/GLEW/build_tarballs.jl
G/GLFW/build_tarballs.jl
G/gdk_pixbuf/build_tarballs.jl
L/Libepoxy/build_tarballs.jl
L/Libglvnd/build_tarballs.jl
L/Libpciaccess/build_tarballs.jl
S/SDL2/build_tarballs.jl

Before building GTK for Linux and FreeBSD I think it'd be good to completely get rid of the old `X11_jll` package.  I'd recommend prioritising `Cairo`, `gdk_pixbuf`, `Libepoxy` and `Libglvnd`, I don't think the other libraries are part of the GTK world.

Remove all references to old X11_jll package

---

L/libvorbis/build_tarballs.jl

`libvorbisenc` and `libvorbisfile` were missing from this file, as listed [here](http://www.linuxfromscratch.org/blfs/view/svn/multimedia/libvorbis.html) and as required when loading `libsndfile`.

Added missing products to libvorbis builder

---

azure-pipelines.yml

See an example of manual rebuild that tried to deploy the JLL package: https://dev.azure.com/JuliaPackaging/Yggdrasil/_build/results?buildId=75.  Luckily, it failed, but I'm not sure why :thinking:
Maybe only the new condition is sufficient?  Testing both shouldn't hurt though

Deploy JLL package only if source branch is master

---

azure-pipelines.yml

This should fix CI failure in #183 and some of the failures in #159.

Tag Docker image using System.JobId instead of Build.SourceVersion

---

Z/Zlib/build_tarballs.jl

Quite unusually, zlib embeds the license inside the `README`.  Thus, what I'm doing here is to install the `README` file as license.  I couldn't think of a way to extract the license text from the `README`  that won't break in case the format of the file will change.

[Zlib] Install license file

---

O/Opus/build_tarballs.jl

Dependency of sdl2_mixer (#122).
This doesn't work only on aarch64, during `make` I get:
```
libtool: compile:  cc -std=gnu99 -DHAVE_CONFIG_H -I. -I./include -I./celt -I./silk -I./silk/float -I./silk/fixed -g -O2 -fvisibility=hidden -D_FORTIFY_SOURCE=2 -W -Wall -Wextra -Wcast-align -Wnested-externs -Wshadow -Wstrict-prototypes -MT celt/arm/celt_neon_intr.lo -MD -MP -MF celt/arm/.deps/celt_neon_intr.Tpo -c celt/arm/celt_neon_intr.c  -fPIC -DPIC -o celt/arm/.libs/celt_neon_intr.o
In file included from celt/arm/celt_neon_intr.c:37:0:
celt/arm/celt_neon_intr.c: In function ‘xcorr_kernel_neon_float’:
celt/arm/celt_neon_intr.c:137:14: error: incompatible types when initializing type ‘float32x4_t’ using type ‘float32x2_t’
SUMM = vmlaq_lane_f32(SUMM, YY[0], vget_low_f32(XX[0]), 0);
^ …
```

Add builder for Opus

---

generate_buildjl.jl

With this change, only the first argument is mandatory, e.g.
```
% julia --color=yes generate_buildjl.jl Z/Zlib/build_tarballs.jl
[ Info: Build tarballs script: Z/Zlib/build_tarballs.jl
[ Info: Repo name: JuliaBinaryWrappers/Zlib_jll.jl
Updating registry at `~/.julia/registries/General`
Updating git-repo `https://github.com/JuliaRegistries/General.git`
[ Info: Tag name: Zlib-v1.2.11+7
[ Info: Calculated c5064dade1ced139e5feb055d53d7487fd421a037d46bb800eaa49e55149fbff for Zlib.v1.2.11.aarch64-linux-gnu.tar.gz
[ Info: Calculated 8462f173e8dabd6e8e391841b9ed13028599dee99f210780220bad9e58a59f57 for Zlib.v1.2.11.aarch64-linux-musl.tar.gz
[ Info: Calculated 3f274eaeb22e512ee2345807b6937dcd71a6fecd0ec67b0d73f3f855c7c25c70 for Zlib.v1.2.11.arm-linux-gnueabihf.tar.gz
[ Info: Calculated …
```

[generate_buildjl] Automatically guess repo name and latest version

---

.ci/download_sources.jl
.ci/register_package.jl
H/HelloWorldC/build_tarballs.jl
H/HelloWorldCxx/build_tarballs.jl
H/HelloWorldFortran/build_tarballs.jl
H/HelloWorldGo/build_tarballs.jl
H/HelloWorldRust/build_tarballs.jl
azure-pipelines.yml

This enables us to level up our CI game, namely:
* Download sources once, to avoid clobbering when multiple jobs start at once
* Run a separate job PER TARGET PLATFORM; not only does this increase parallelism, it also makes debugging easier.

Declarative `build_tarballs.jl` parsing!

---

azure-pipelines.yml

This is just a safeguard against an unlikely race condition where two Registrator instances would be running at the same time.

Don't allow parallel registration

---

A/ATK/build_tarballs.jl
A/at_spi2_atk/build_tarballs.jl
A/at_spi2_core/build_tarballs.jl
G/GTK3/build_tarballs.jl
G/gdk_pixbuf/build_tarballs.jl
X/xkbcommon/build_tarballs.jl

We used to use GCC8 to build for PowerPC64, but we do not need it anymore as
this has been fixed in the meson cross file by adding the options for the linker
to look for libraries in ${prefix}/lib64 (see #157).

Use default GCC version for builders using meson

---

F/FFMPEG/build_tarballs.jl

* Update configure options to match those in [JuliaIO/FFMPEGBuilder](https://github.com/JuliaIO/FFMPEGBuilder/blob/99bb3a1c82dd4b8ca15487b9f1be749153662ad8/build_tarballs.jl)
* Remove products coming from other libraries
* Fix capitalisation of dependencies, add `OpenSSL_jll`
Depends on #183.

[FFMPEG] Update builder

---

X/Xorg_xcb_util/build_tarballs.jl

In my slow and on-going effort to keep/make QML.jl alive, this is one of the dependencies for Qt5. I will need to add some more xcb-util-* packages that depend on this one.
Very nice that so many X11 libs are here already, I wished I had checked for their existence before building all of them myself [here](https://github.com/barche/libx11builder/blob/master/build_tarballs.jl) 🙃

Add builder for xcb-util

---

0_RootFS/CompilerSupportLibraries/build_tarballs.jl

Skipping the audit appears to prevent rpath from doing anything (https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/issues/1). But rpath needs some write permissions. There is still
```
Warning: Unable to set SONAME on lib/libgcc_s.1.dylib
```

attempt to fix CSL

---

F/FastTransforms/build_tarballs.jl

I will split this PR into (at least) 2 commits: the first one passes builds locally; the second one fails on the extra platforms `MacOS` and `Windows(:x86_64)` for the following reasons:
- `libopenblas64_` appears not to be found by the linker for `MacOS(:x86_64)` and `Windows(:x86_64)`. Sample error from `Windows(:x86_64)`:
```
[ Info: Building for x86_64-w64-mingw32
Updating registry at `~/.julia/registries/General`
Updating git-repo `https://github.com/JuliaRegistries/General.git`
Updating registry at `~/.julia/registries/General`
Updating git-repo `https://github.com/JuliaRegistries/General.git`
Resolving package versions...
Resolving package versions...
Updating `~/Codes/build/x86_64-w64-mingw32/rAty1i0Z/.project/Project.toml`
[e66e0078] + CompilerSupportLibraries_jll v0.2.0+0 …
```

add FastTransforms builder

---

G/GEOS/build_tarballs.jl

Static libraries for GEOS take space unnecessarily 79 MB, as discussed in JuliaGeo/LibGEOS.jl#65 . Disable static libraries.
Judging from https://github.com/search?p=1&q=org%3AJuliaPackaging+--disable-static&type=Code `--disable-static` should be the correct option.

Disable static libraries for GEOS

---

azure-pipelines.yml

I think we should map the token to an environment variable, so that it can be treated in the script as a plain variable, instead of command-like, which would fail when the token is not available.  This is also the recommended way to deal with this, according to https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#secret-variables.
Tested in #224.

[AZP] Map the token

---

F/FastTransforms/build_tarballs.jl

It turns out that having `-march=native` is not good for cross-compilation. Sorry for the double take!
Instead, I turned on the `-mavx` flag because: Travis uses Ivybridge to test on macOS and Haswell to test on Linux and Windows; Appveyor also uses Haswell on Windows; and, Cirrus uses Haswell on FreeBSD.

[FastTransforms] Remove -march=native on cross-compile

---

L/libportaudio/build_tarballs.jl

Thanks @jpsamaroo for the help realizing that we don't actually need to build JACK and ALSA.
I've tested that this runs locally and builds all the targets, but not that it actually works. I figure once the `libportaudio_jll` package is available I'll be able to test from PortAudio.jl and make sure everything's working.

adds libportaudio builder

---

L/Lua/build_tarballs.jl
L/Lua/bundled/LICENSE
L/Lua/bundled/patches/src_Makefile.patch

Work in progress. I think it will take some patches in order to produce a shared library. Both FreeBSD Ports and Homebrew have a number of patches which make it build a shared library in addition to or instead of (respectively) an archive.
Note that this is for regular ol' Lua, not LuaJIT.

Add a builder for Lua 5.3

---

G/GEOS/build_tarballs.jl

`configure` is generating a `Makefile` with
```
CFLAGS = -g -O2
CXXFLAGS = -g -O2
```
Here we just set
```
CFLAGS=-O2
CXXFLAGS=-O2
```
These are the sizes of the resulting libraries for `x86_64-w64-mingw32`:
```
% ls -lh GEOS.v3.8.0.x86_64-w64-mingw32/bin 
total 3.8M
-r-xr-xr-x 1 mose mose 1.3K Nov 26 02:21 geos-config
-r-xr-xr-x 1 mose mose 3.0M Nov 26 02:21 libgeos-3-8-0.dll
-r-xr-xr-x 1 mose mose 815K Nov 26 02:21 libgeos_c-1.dll
```
I think this is a good improvement compared to the current situation, without doing any magic.  Ref #234.  CC: @jaakkor2 @visr

[GEOS] Remove -g options to compilers to reduce size

---

X/Xorg_xcb_util_image/build_tarballs.jl
X/Xorg_xcb_util_keysyms/build_tarballs.jl
X/Xorg_xcb_util_renderutil/build_tarballs.jl
X/Xorg_xcb_util_wm/build_tarballs.jl

These are the final dependencies for Qt5 on Linux ( ref: https://github.com/JuliaPackaging/BinaryBuilder.jl/issues/393 )

Add some xcb-util based libraries

---

L/Lua/build_tarballs.jl
L/Lua/bundled/patches/src_lauxlib.c.patch

These simply return the values of configuration parameters that do not seem to be accessible after build time. They're useful for [LuaCall.jl](https://github.com/ararslan/LuaCall.jl) to ensure the correct types are passed back and forth between Julia and Lua.

[Lua] Add Julia-specific functions to liblua

---

R/ReadStat/build_tarballs.jl

I need some help with this, so far I just copied the old build script we had in ReadStatBuilder over, but that doesn't seem to work anymore.

Add ReadStat builder

---

A/Arpack/build_tarballs.jl

We apparently can't deal with `v3.7` in `Arpack.jl` yet.

Roll `Arpack` back to `v3.5`

---

L/Libxls/build_tarballs.jl

I'm currently running into some problem that BinaryBuilder complains that it can't `rm` something that is read-only. I think that error is probably unrelated to this particular build receipt.
Could someone else maybe test whether this branch works? I mostly copied the script from the previous builder repository.

Add builder for libxls

---

A/Arpack/build_tarballs.jl

By default, Arpack links against the most specific OpenBLAS dylib name;
we fix that manually.

Fix Arpack OpenBLAS linkage on MacOS

---

A/Arpack/build_tarballs.jl

This should at least buffer ourselves against OpenBLAS upgrading its version and breaking this step.  It should also actually, like, work and stuff.

Imrpove Arpack `install_name_tool` trickery

---

G/Git/build_tarballs.jl
fancy_toys.jl

This is to see if now we'll get the wrapper for `x86_64-w64-ming32`, ref #233.
Let's see also if our Azure pipeline really works with this kind of builder :crossed_fingers:

[Git] Improve builder so that it runs only for requested platforms

---

azure-pipelines.yml

Should fix JLL binary upload issues.
This depends on https://github.com/JuliaPackaging/BinaryBuilder.jl/pull/551

[AZP] Deploy only binaries during split build steps

---

G/GMP/build_tarballs.jl
M/MPFR/build_tarballs.jl

We need to rebuild these then point to the new binaries for GMP and MPFR to work on ppc64le

Bump MPFR and GMP for ppc64le patchelf fixes

---

V/VerizonEctoken/build_tarballs.jl
V/VerizonEdgecastTokenBuilder/build_tarballs.jl

* Package name: VerizonEdgecastTokenBuilder

Wizard recipe: VerizonEdgecastTokenBuilder-v0.1.0

---

L/LibOSXUnwind/build_tarballs.jl

* Package name: LibOSXUnwind
* Version: v1.33.7

Wizard recipe: LibOSXUnwind-v1.33.7

---

S/SuiteSparse@5/build_tarballs.jl
S/SuiteSparse@5/bundled/patches/0001-mingw-w64-does-not-have-sys-resource-h.patch
S/SuiteSparse@5/bundled/patches/0002-mingw-w64-do-not-use-reserved-double-underscored-names.patch
S/SuiteSparse@5/bundled/patches/0003-WIN32-Install-RUNTIME-to-bin.patch
S/SuiteSparse@5/bundled/patches/0004-Fix-GKLIB_PATH-default-for-out-of-tree-builds.patch

Now that metis-5.1.0 is included in SuiteSparse, let's try build CHOLMOD with the PARTITION module. This should give us the capability to do nested dissection orderings. For cholesky factorizations on certain graphs, this may give better fill.
Cc @ranjanan

Attempt to build suitesparse with PARTITION module (with metis)

---

S/SuiteSparse@5/build_tarballs.jl

Use official SuiteSparse repo on github to pull sources
Simplify SuiteSparse_wrapper build by not linking extra libs
Ensure Metis linkage by removing -DNPARTITION (introduced in the recent reverting)
License file is auto-detected

[SuiteSparse] Various SuiteSparse build cleanups

---

G/git_crypt/build_tarballs.jl

* Package name: git_crypt
* Version: v0.6.0

Wizard recipe: git_crypt-v0.6.0

---

M/MPICH/build_tarballs.jl

This is to try avoid the case sensitivity issues that seem to affect macOS, by avoiding the docs install.

[MPICH] Address case sensitivity on mac

---

V/Vmtouch/build_tarballs.jl
V/vmtouch/build_tarballs.jl

* Package name: Vmtouch
* Version: v1.3.1

Wizard recipe: vmtouch-v1.3.1

---

L/libportaudio_ringbuffer/build_tarballs.jl

This splits out a particularly useful piece of code from libportaudio for usage in `RingBuffers.jl`

Add `libportaudio_ringbuffer`

---

L/libportaudio/build_tarballs.jl

This should make `libportaudio` actually useful on most Linux systems.

Enable `ALSA` backend for `libportaudio`

---

S/SDL2_ttf/build_tarballs.jl
S/SDL2_ttf/bundled/patches/Makefile_in_dont_build_programs.patch
S/SDL2_ttf/bundled/patches/configure_in-v2.0.15.patch

Ref #122.  I consumed all my energy to make this build for FreeBSD, then I gave up when I arrived on Windows.  It doesn't build the shared library, only the static archive.
I had the same problem with FreeBSD and I had to patch `configure.in` and (repeatedly) rebuild `configure`, but apparently this isn't sufficient for Windows.  The patch is inspired by https://git.archlinux.org/svntogit/packages.git/tree/trunk/freetype-pkgconfig.patch?h=packages/sdl2_ttf.

Add builder for SDL2_ttf

---

X/Xorg_libXpm/build_tarballs.jl

* Package name: Xorg_libXpm
* Version: v3.5.13

Wizard recipe: Xorg_libXpm-v3.5.13

---

X/XML2/build_tarballs.jl

With this, on macOS I get:
```
sandbox:${WORKSPACE}/srcdir/libxml2-2.9.9 # otool -L ${libdir}/libxml2.2.dylib 
/workspace/destdir/lib/libxml2.2.dylib:
/workspace/destdir/lib/libxml2.2.dylib (compatibility version 12.0.0, current version 12.9.0)
/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1213.0.0)
@rpath/libz.1.dylib (compatibility version 1.0.0, current version 1.2.11)
@rpath/libiconv.2.dylib (compatibility version 9.0.0, current version 9.1.0)
```
See https://github.com/JuliaGtk/GtkSourceWidget.jl/pull/9 for reference

[XML2] Make sure libxml2 is linked to our own libiconv on macOS

---

G/Gettext/build_tarballs.jl

This is to make sure that the libraries are linked against our own libxml2 on macOS:
```
sandbox:${WORKSPACE}/srcdir/gettext-0.20.1 # otool -L ${libdir}/libgettextlib.dylib 
/workspace/destdir/lib/libgettextlib.dylib:
/workspace/destdir/lib/libgettextlib-0.20.1.dylib (compatibility version 0.0.0, current version 0.0.0)
/workspace/destdir/lib/libintl.8.dylib (compatibility version 10.0.0, current version 10.6.0)
@rpath/libxml2.2.dylib (compatibility version 12.0.0, current version 12.9.0)
/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1213.0.0)
@rpath/libz.1.dylib (compatibility version 1.0.0, current version 1.2.11)
@rpath/libiconv.2.dylib (compatibility version 9.0.0, current version 9.1.0)
/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFounda …
```

[Gettext] Add XML2 to the dependencies

---

0_RootFS/Rootfs/bundled/conf/profile.d/license_utils.sh

I want a way to check if `auto_install_license` installed anything, so that in the wizard we can warn the user if no license is found.

Add flag to `auto_install_license` to check success

---

O/OpenBLAS/build_tarballs.jl
O/OpenBLAS/bundled/patches/openblas-winexit.patch

This is the patch from https://github.com/JuliaLang/julia/pull/34225, but
against 0.3.7 not 0.3.5.

[OpenBLAS] Add hang-on-exit patch

---

0_RootFS/PlatformSupport/bundled/buildsystem_toolchains/cmake_macos_clang.j2
0_RootFS/PlatformSupport/bundled/buildsystem_toolchains/cmake_macos_gcc.j2
0_RootFS/PlatformSupport/bundled/buildsystem_toolchains/cmake_simple_clang.j2
0_RootFS/PlatformSupport/bundled/buildsystem_toolchains/cmake_simple_gcc.j2

In order to  bootstrap LLVM properly I need to provide my own toolchain file currently
since the one we use doesn't note which `nm` etc to use
https://github.com/JuliaPackaging/Yggdrasil/pull/296/files#diff-08724ed72679c754126058e3bfd19c92R76
@staticfloat please review and merge

add other build tools to cmake toolchains

---

F/Fontconfig/build_tarballs.jl

This should make the `fonts.conf` file identical to "standard" one on Linux and FreeBSD systems -- this is at least identical to my own `/etc/fonts/fonts.conf`.  I don't think there is really a "standard" fontconfig on the other systems, so we can keep this as it is now.

[Fontconfig] Set cachedir for Linux and FreeBSD

---

C/Chemfiles/build_tarballs.jl
C/Chemfiles/bundled/patches/fileno_posix.patch

* Package name: Chemfiles
* Version: v0.9.2

Wizard recipe: Chemfiles-v0.9.2

---

B/boost/build_tarballs.jl
B/boost/bundled/patches/boost_math_tools_config_hpp.patch

This makes it possible to provide boost for FreeBSD: for some reasons not very clear from the log, `libboost_math_c99l` and `libboost_math_tr1l` are not built.  I also alphabetically sorted the products, to make it easier to go through them.

[boost] Build libraries missing on FreeBSD

---

C/CGAL/build_tarballs.jl

Simple builder for CGAL 5.0.
**NOTICE**: This builder only requests the `CORE` number library component. `ImageIO` and `Qt5` are **NOT** included/built. Feel free to convince me to add them in :slightly_smiling_face:

Add a builder for CGAL

---

T/Tesseract/build_tarballs.jl
T/Tesseract/bundled/patches/sys_time_musl_freebsd.patch

[Tesseract] Add builder

---

P/peco/build_tarballs.jl

* Package name: peco
* Version: v0.5.7
Created with https://github.com/JuliaPackaging/BinaryBuilder.jl/pull/553.  Fix #374.  CC: @rapus95

Wizard recipe: peco-v0.5.7

---

C/cxxwrap_julia/build_tarballs.jl

This adds a builder for [libcxxwrap-julia](https://github.com/JuliaInterop/libcxxwrap-julia). Some notes:
* I set the gfortran version just to force a C++ compiler new enough for C++17, I'm not sure if there is a more direct way
* Julia binaries are downloaded directly inside the script, awaiting build-time-only deps as discussed in #321 
* i686 Linux doesn't build, but it never did before either (can't find the issue on this) and is of very low priority to me

Add builder for libcxxwrap-julia

---

G/GEOS/build_tarballs.jl

This commit is mainly to trigger a new build after https://github.com/JuliaPackaging/BinaryBuilder.jl/pull/616 has been merged, since I'm hoping that will resolve #316, towards #293.

GEOS - rebuild after cxxstring_abi fixes in BB

---

C/Chemfiles/build_tarballs.jl

<s>It has been reported in https://github.com/JuliaBinaryWrappers/Chemfiles_jll.jl/issues/1 that the 64-bit Windows library makes Julia crash upon `dlopen`ing it.  I did some tests in my fork of `Chemfiles_jll` (see for example the [AppVeyor jobs](https://ci.appveyor.com/project/giordano/chemfiles-jll-jl/history)) and I'm pretty convinced that we need to expand the C++ string ABI.</s> The [renewed audit pass](https://github.com/JuliaPackaging/BinaryBuilder.jl/pull/616) about C++ string ABI confirms that this library needs to expand the ABIs.
CC: @Luthaf

[Chemfiles] Expand C++ string ABIs

---

A/armadillo/build_tarballs.jl

This is a dependency of mlpack (#368).  @giordano suggested that I pull it out as a separate package.  I decided to package `libarmadillo.so`, but it's still possible to use Armadillo as a header-only library.  `libarmadillo.so` is basically just a wrapper around OpenBLAS.
Armadillo's quite easy to package, so I think that this should be good to go.  For downstream packages that link against Armadillo, there may be problems until https://github.com/JuliaPackaging/BinaryBuilder.jl/pull/604 is fixed (I think that caused issues with mlpack, which depends on Armadillo).  In any case, this appeared to build fine locally for me.

Add Armadillo build script

---

S/SQLite/build_tarballs.jl

Purely cosmetic change to trigger a build to fix the most likely culprit in #394; an outdated SQLite build.

SQLite - bring build script closer to the wizard

---

G/GDAL/build_tarballs.jl
G/GDAL/bundled/patches/configure_ac_proj_libs.patch

An attempt to build GDAL with a rather minimal set of dependencies. We'd [like to add more](https://github.com/JuliaGeo/GDAL.jl/issues/65), but only after this builds well, taking it one step at a time.
Going over it with @giordano on Slack we already managed to bypass `configure` errors (PROJ dependency checks) by adding `CompilerSupportLibraries_jll`, see the second commit. Unfortunately it does not seem possible to bypass these checks with `configure` arguments.
Right now, on `x86_64-linux-gnu`, this hits:
```
[14:59:35] sed: /workspace/destdir/x86_64-linux-gnu/lib/../lib64/libstdc++.la: No such file or directory
[14:59:35] libtool:   error: '/workspace/destdir/x86_64-linux-gnu/lib/../lib64/libstdc++.la' is not a valid libtool archive
[14:59:35] make[1]: *** [GNUmakefile:66: …
```

add GDAL builder

---

L/LLVM/common.jl
L/LLVM/v9/build_tarballs.jl
L/LLVM/v9/bundled/patches/0700-clang-shlib-mingw.patch

fix the cmake file for clang to build the shlib on mingw

[LLVM9] allow clang shlib on mingw

---

T/Tar/build_tarballs.jl

@StefanKarpinski I thought this could be useful for testing in `Tar.jl`, but it doesn't seem to be easy to build for Windows.  I could not find any patch in https://github.com/msys2/MINGW-packages/
```
MINGW-packages-master% find . -iname "*tar*" -type d
./mingw-w64-xmlstarlet-git
./mingw-w64-cantarell-fonts
```
I found http://gnuwin32.sourceforge.net/packages/gtar.htm but it's super-old.  It's also quite hard to google something like "build tar for windows"

[Tar] Add builder

---

L/Libglvnd/build_tarballs.jl

For some mysterious reasons, `Libglvnd_jll.jl` [depends](https://github.com/JuliaRegistries/General/blob/ca3fd0f77200a9cd4823170dd90a007d84e56e16/L/Libglvnd_jll/Deps.toml) on both `X11_jll` and `Xorg_libX11_jll`.  This doesn't make any sense, in [this commit](https://github.com/JuliaPackaging/Yggdrasil/commit/45c59bc13354f1301850f1ed85414a78e5798bd1#diff-b1b205d69c72c8422f64d9eb38d15640) `X11_jll` was removed from the dependencies, and `Xorg_libX11_jll` was added, they've never been together in the list of dependencies :confused:

[Libglvnd] Retrigger build to fix dependencies of JLL package

---

C/CGAL/build_tarballs.jl

Some noteworthy changes:
- The (hopefully obvious) addition of the `ImageIO` library
- Requires Zlib [[1](https://www.zlib.net), [2](https://github.com/JuliaBinaryWrappers/Zlib_jll.jl)], hence added as a dependency
- Install `LICENSE`s
- Remove apparently unused cross-compilation `try_run` variable (scarcely tested, will add back if builds start failing)
Minor changes:
- Couple `name` and `version` assignments
- Inline `majorminor` function which produced the `"<MAJOR>.<MINOR>"` semver string
- **EDIT:** Benefit from some parallelism with the `-j$nproc` make flag

[CGAL]: Add ImageIO + tweak build recipe

---

S/SDL2_image/build_tarballs.jl
S/SDL2_mixer/build_tarballs.jl

This should magically remove the dependency on libiconv for the macOS library.

[SDL2_image] [SDL2_mixer] Trigger build

---

O/OpenBLAS/OpenBLAS@0.3.5/build_tarballs.jl
O/OpenBLAS/OpenBLAS@0.3.5/bundled/patches/openblas-ofast-power.patch
O/OpenBLAS/OpenBLAS@0.3.7/build_tarballs.jl
O/OpenBLAS/OpenBLAS@0.3.7/bundled/patches/openblas-ofast-power.patch
O/OpenBLAS/common.jl

Export `LDFLAGS` within `OpenBLAS` builder

---

C/cxxwrap_julia/build_tarballs.jl

This fixes some errors for CxxWrap.jl that were revealed when running CI on the previous version.

Update libcxxwrap-julia to v0.6.6

---

0_RootFS/Rootfs/bundled/testsuite/Makefile
0_RootFS/Rootfs/bundled/testsuite/c/openmp/Makefile
0_RootFS/Rootfs/bundled/testsuite/c/openmp/openmp.c
0_RootFS/Rootfs/bundled/testsuite/cxx/dyn_link/dyn_link.cc
0_RootFS/Rootfs/bundled/testsuite/fortran/hello_world/Makefile

This adds a few small improvements to our testsuite:
* It tests linking with both `$CC` and `$FC` when running the fortran test suite, to catch things like https://github.com/JuliaPackaging/BinaryBuilder.jl/pull/630
* It adds an OpenMP test to the `c` test suites, so that I can try out linking against different versions of `libgomp`.

RootFS: Upgrade testsuite

---

G/GDAL/build_tarballs.jl
G/GDAL/bundled/patches/configure_ac_curl_libs.patch

By adding -lstdc++ as was done for GEOS.
Hopefully this will fix the last part of #418:
```
found libcurl version 7.66.0
checking for curl_global_init in -lcurl... no
cURL support (wms/wcs/...):no
```

GDAL try to fix libcurl dependency on Linux

---

L/LibCURL/build_tarballs.jl

I want to double-check that this new version will get the Julia 1.0 compatibility automatically, instead of just patching the registry.

Update LibCURL to v7.68

---

0_RootFS/PlatformSupport/build_tarballs.jl

This fixes the incorrectly-named CMake files.

PlatformSupport: Use `aatriplet()` when dealing with `COMPILER_TARGET`

---

H/HelloWorldC/build_tarballs.jl
azure-pipelines.yml

We don't need to cleanup anymore, since that's old `docker` stuff.  Also, actually map through the `GITHUB_TOKEN` to the scripts.

[AZP] fix token mapping, eliminate stale stage

---

B/bsdiff/build_tarballs.jl

* Package name: bsdiff
* Version: v4.3.0

Wizard recipe: bsdiff-v4.3.0

---

C/CGAL/build_tarballs.jl

Small patch, see [release notes](https://github.com/CGAL/cgal/releases/tag/releases%2FCGAL-5.0.1)

[CGAL]: Bump to 5.0.1

---

L/libcgal_julia/build_tarballs.jl

Includes a few new things:
+ WIP crude mapping of 2D Voronoi Diagram and Delaunay Triangulation
+ Another Circular kernel intersection (includes CK -> LK construct
conversion to avoid exposing CK types)
+ Deliver two separate artifacts: one compiled with an inexact
constructions (i.e. doubles), and another with exact constructions (i.e.
CORE bignums). This is a breaking change since artifact names change!!

[libcgal_julia]: Update to version v0.5.1

---

S/Sundials/build_tarballs.jl

This should make it possible to build with support for OpenBLAS, but it's not clear to me if it's still desired.  CC: @ViralBShah.
Note: it's a draft because this requires https://github.com/JuliaPackaging/BinaryBuilder.jl/pull/604.

[Sundials 3.1] Build with OpenBLAS support

---

H/hidapi/build_tarballs.jl

Adds the library hidapi, which allows easy access to hid devices. On linux only the libusb backend is supported. (The other backend: hidraw requires libudev, for which there isn't an easy way to build)

Add hidapi recipe

---

S/Sundials@5/build_tarballs.jl

Trying the suggestion from https://github.com/LLNL/sundials/issues/29 for fixing windows build.
Remove gcc preferred version.

[Sundials@5] Resubmit Sundials build

---

T/tree-sitter-c/build_tarballs.jl

* Package name: tree-sitter-c
* Version: v0.16.0

Wizard recipe: tree-sitter-c-v0.16.0

---

L/libcgal_julia/build_tarballs.jl

Previous version defined two new `min` and `max` methods instead of specializing the functions in `Base`. This patch fixes that.

[libcgal_julia] Hotfix v0.6.1

---

L/libsodium/build_tarballs.jl

* Package name: libsodium
* Version: v1.0.18

Wizard recipe: libsodium-v1.0.18

---

L/libcgal_julia/build_tarballs.jl

`abs` and `sqrt` were being defined for `Union{Float64,Ref{Float64}}`
using the inexact constructions kernel variant library, causing method
ambiguity issues regarding the aforementioned methods. New version fixes
said issue.

[libcgal_julia] Fix method ambiguity with v0.6.2 bump

---

L/libftd2xx/build_tarballs.jl

NB: requires fix of https://github.com/JuliaPackaging/BinaryBuilder.jl/issues/672 before usable on Linux

libftd2xx disable windows x86

---

H/hub/build_tarballs.jl

* Package name: hub
* Version: v2.14.1
Fix #522, CC: @rapus95

Wizard recipe: hub-v2.14.1

---

L/libcgal_julia/build_tarballs.jl

Since I'm using (and abusing) macros, I forget which implicitly create
lambdas with parameters that are either `const T&` or just plain `T`
(const ref vs. values).
Turns out it leads to issues when using mapped types in method
signatures, since it couldn't convert a plain julia type to a
corresponding C type when hitting `ccall`. Changing the parameter type
`T` to a `const T&` does the work. Don't think it had to be `const`,
just not a value-type.
In short: `Point23/Origin` interop (`==` testing, `Vector23` creation
from subtraction)

[libcgal_julia] Method sig fixes in v0.6.3

---

.ci/Manifest.toml
.ci/register_package.jl
H/HelloWorldCxx/build_tarballs.jl
azure-pipelines.yml

This uploads tarballs to S3, keyed by binary builder version, a combined
source input hash, then target platform.  All builds, no matter their
provenance, will first check to see if the desired tarball exists within
the build cache, skipping building for that platform if it does exist.
Registration now downloads the binaries from the cache, then uploads
them to GitHub in one fell swoop.  JLL source code is pushed first, so
we no longer have the awkward situation where the GH release is pointing
ot the commit _before_ the code is pushed.

Add S3-based build cache

---

M/METIS@4/build_tarballs.jl
M/METIS@4/bundled/patches/metis.patch

Version 4 of METIS is still required by a number of linear algebra and HPC libraries.
Should I also rename METIS -> METIS@5 in this pull request?

builder for METIS@4

---

A/armadillo/build_tarballs.jl

I was very excited to finally use `armadillo_jll` and its dependency `mlpack_jll` to get the mlpack Julia bindings working.  But, when I tried to use them, I was presented with:
```
julia> mlpack.pca(x; verbose=true)
[INFO ] Performing PCA on dataset...
error: svd(): use of LAPACK must be enabled
terminate called after throwing an instance of 'std::logic_error'
what():  svd(): use of LAPACK must be enabled
```
This meant that Armadillo had not been properly configured during the build to use the LAPACK functions that are available in OpenBLAS.  I dug into the CMake configuration of Armadillo, and the comments seem to indicate that there do exist some distributions of OpenBLAS that have the LAPACK symbols stripped out, so Armadillo disables LAPACK unless it's separately found.
This PR …

Enable LAPACK in Armadillo

---

F/FFTW/build_tarballs.jl

Just a testing PR to see what happens when we remove the win64 AVX assembler workaround; without this we usually get an assembler error, but perhaps with the right GCC version, we can avoid such issues.

[FFTW]: Try removing win64 AVX workaround

---

X/XZ/build_tarballs.jl

I'm now trying to build a new binary library that depends on XZ. However, the current XZ binaries of Windows do not offer header files and therefore it cannot complete. Also, DLL files seem to be a strange place (why in the bin directory?) on Windows, which also makes building libraries harder. I've stripped several options and flags from configuration but I'm not sure whether they are actually effective or not. So, I still need to check the products.

make XZ builder simpler and more standardized

---

L/librealsense/build_tarballs.jl

It's been retagged to 2.32.1 according to the upstream.

Correct the version number of librealsense

---

A/armadillo/build_tarballs.jl

This is part of an attempt to debug #539, which is failing due to linking errors of the following form:
```
[23:36:31] /opt/powerpc64le-linux-gnu/powerpc64le-linux-gnu/sys-root/usr/local/lib/libarmadillo.so: undefined reference to `spocon_'
[23:36:31] /opt/powerpc64le-linux-gnu/powerpc64le-linux-gnu/sys-root/usr/local/lib/libarmadillo.so: undefined reference to `dgbsvx_'
[23:36:31] /opt/powerpc64le-linux-gnu/powerpc64le-linux-gnu/sys-root/usr/local/lib/libarmadillo.so: undefined reference to `zgesvd_'
[23:36:31] /opt/powerpc64le-linux-gnu/powerpc64le-linux-gnu/sys-root/usr/local/lib/libarmadillo.so: undefined reference to `dgesdd_'
[23:36:31] /opt/powerpc64le-linux-gnu/powerpc64le-linux-gnu/sys-root/usr/local/lib/libarmadillo.so: undefined reference to `spotrs_'
[23:36:31] …
```

Add _64 to OpenBLAS symbols on Linuxes and FreeBSD also for Armadillo.

---

M/MPICH/build_tarballs.jl

Attempt to enable the MPI Fortran compiler.

MPICH: enable Fortran support

---

H/HelloWorldGo/build_tarballs.jl
azure-pipelines.yml

We were signing metadata which included a timestamp; cache that timestamp so that there's no chance that it can change between us signing it, then transmitting it.  Also, explicitly check that the upload succeeded, so that we don't try to register something that doesn't exist.

Fix artifact uploading

---

O/OpenSpecFun/build_tarballs.jl

This ensures that the corresponding `libgfortran` version is always available.
In particular, this should alleviate (or maybe effectively fix) https://github.com/JuliaMath/SpecialFunctions.jl/issues/192.

[OpenSpecFun] Add `CompilerSupportLibraries_jll` to the dependencies

---

0_RootFS/Rootfs/bundled/conf/profile.d/license_utils.sh

Add some more common file names for the licenses.  `NOTICE` is often used for Apache licenses.
I've also seen sometimes files name like `LICENSE.MIT` that include the name of the license as extensions.  Not sure these extra extensions are a good idea, open to comments.

[RootFS] Add more license file names for `auto_install_license`

---

H/HelloWorldC/bundled/CMakeLists.txt
azure-pipelines.yml

As shown in https://dev.azure.com/JuliaPackaging/Yggdrasil/_build/results?buildId=1866&view=logs&j=96c13d9d-dfd2-51e5-2f76-4a0b3ce09abc&t=09532434-8b0a-5f0e-118d-a3181cde5ec8, there are cases where we edit only patches or similar, and these commits get dropped from CI because we don't find the `build_tarballs.jl` file sitting in a parent directory.

[AZP] Search in parent directories for `build_tarballs.jl` files

---

X/XZ/build_tarballs.jl

The `configure` option was wrong, see #574 for reference.
Now I get
```
sandbox:${WORKSPACE}/destdir/lib # ar x liblzma.a 
sandbox:${WORKSPACE}/destdir/lib # readelf --relocs liblzma_la-index.o | grep lzma_free
000000000058  001800000009 R_X86_64_GOTPCREL 0000000000000000 lzma_free - 4
000000000547  001800000004 R_X86_64_PLT32    0000000000000000 lzma_free - 4
000000000c65  001800000004 R_X86_64_PLT32    0000000000000000 lzma_free - 4
000000000d18  001800000004 R_X86_64_PLT32    0000000000000000 lzma_free - 4
00000000006e  001800000004 R_X86_64_PLT32    0000000000000000 lzma_free - 4
000000000582  001800000004 R_X86_64_PLT32    0000000000000000 lzma_free - 4
```
As far as I understand, this means that the symbol has now position-independent code.

[XZ] Fix generation of PIC code

---

A/armadillo/build_tarballs.jl

After excitedly finally getting mlpack.jl merged into the Julia general registry, I opened up a Julia REPL in order to see the algorithms work nicely from Julia:
```
_
_       _ _(_)_     |  Documentation: https://docs.julialang.org
(_)     | (_) (_)    |
_ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
| | | | | | |/ _` |  |
| | |_| | | | (_| |  |  Version 1.3.1 (2019-12-30)
_/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |
julia> import mlpack
julia> x = rand(5, 5);
julia> mlpack.pca(x, verbose=true)
[INFO ] Performing PCA on dataset...
** On entry to DGESDDM parameter number 12 had an illegal value
signal (11): Segmentation fault
in expression starting at REPL[3]:1
_ZN6mlpack3pca3PCAINS0_14ExactSVDPolicyEE5ApplyERN4arma3MatIdEEm at …
```

Armadillo: use 64-bit integers for 64-bit OpenBLAS

---

U/utf8proc/build_tarballs.jl

The `Makefile` doesn't have a rule for the Windows shared library, thus we have
to build it manually.

[utf8proc] Manually build the shared library for Windows

---

X/xxHash/build_tarballs.jl

* Package name: xxHash
* Version: v0.7.3

Wizard recipe: xxHash-v0.7.3

---

L/LLVM/LLVM@9.0.1/bundled/llvm_patches/0032-llvm-D75072-SCEV-add-type.patch

Adds the patch from https://github.com/JuliaLang/julia/pull/34860.

Add LLVM patch

---

H/HELICS/build_tarballs.jl

Bumps the HELICS version to v2.4.1

Bump `HELICS` version to `v2.4.1`

---

S/SuiteSparseGraphBLAS/build_tarballs.jl

We are bumping SuiteSparse to 5.6 here for GraphBLAS so that we get GraphBLAS 3, and can skip older versions. The libgraphblas is completely independent from anything else in SuiteSparse and thus this should be ok.

[SuiteSparseGraphBLAS] Add SuiteSparseGraphBLAS

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json
.gitattributes

With this, and if the VS Code `Remote - Container` extension is installed, VS Code will auto-provision an environment when this repo is opened in VS Code.

Add devcontainer config

---

E/EDFlib/build_tarballs.jl

EDFlib is a C library for reading and writing EDF and BDF files.

Add EDFlib

---

E/EDFlib/build_tarballs.jl

A comment in edflib.h says that the library needs to be compiled with `-D_LARGEFILE64_SOURCE` and `-D_LARGEFILE_SOURCE`. I missed that when initially adding the builder. 🙄

[EDFlib] Add required build options

---

N/normaliz/build_tarballs.jl

Normaliz is an open source tool for computations in affine monoids, vector configurations, lattice polytopes, and rational cones. https://www.normaliz.uni-osnabrueck.de/
* First build failed because of libstdc++ issue between CompilerSupportLibraries and Rootfs for gcc6, see #624 for details. Second build is with workaround in place.
A few comments on the extra options:
* `preferred_gcc_version` is needed because `GMP_jll` uses the same option and normaliz uses `libgmpxx`.
* `expand_cxxstring_abis` is needed because `libgmpxx` uses `std::string` symbols and was recommended when running the build without.
* `CompilerSupportLibraries_jll` is needed for OpenMP (`libgomp`) and was recommended when running the build without.

[normaliz] Add builder for normaliz 3.8.4

---

.devcontainer/Dockerfile
O/OpenBLAS/OpenBLAS@0.3.5/build_tarballs.jl
O/OpenBLAS/OpenBLAS@0.3.7/build_tarballs.jl
O/OpenBLAS/common.jl

We need to set the SONAME of `libopenblas` to be `libopenblas.so`, not
`libopenblas.so.0.3.7`, in order for our builds of SuiteSparse to work
across versions.  We actually were trying to do this, but the logic
seems to have bitrotten somewhere.

[openblas]: Set SONAME to unversioned filename

---

R/rr/build_tarballs.jl
R/rr/bundled/patches/rr_old_glibc.patch

Not functional yet, because `rr` is not supporting musl.
I think the best immediate goal is to try and only build `rrpreload`
and then inject that into an rr built for glibc so that we can record
binaries built for musl.

add recipe for rr

---

G/GMP/build_tarballs.jl

Without the product declaration it is not dlopened automatically and then not found by other libraries that depend on it, see: https://github.com/JuliaBinaryWrappers/normaliz_jll.jl/issues/1
I also added libgmpxx.dll for windows, similar to libgmp.dll.
The same happens on linux when there is no system-libgmpxx.so available:
```
julia> using normaliz_jll
ERROR: InitError: could not load library "~/.julia/artifacts/3673e354da051c278f4d8a839105527345ec219a/lib/libnormaliz.so"
libgmpxx.so.4: cannot open shared object file: No such file or directory
Stacktrace:
[1] dlopen at /var/tmp/portage/dev-lang/julia-1.4.0_rc2/work/julia-1.4.0-rc2/usr/share/julia/stdlib/v1.4/Libdl/src/Libdl.jl:109 [inlined] (repeats 2 times)
[2] __init__() at ~/.julia/dev/normaliz_jll/src/wrappers/x86_64-linux-gnu-cxx11.j …
```

[GMP] add libgmpxx to products

---

0_RootFS/CompilerSupportLibraries/build_tarballs.jl

An example of why we need this is for `llvm-config.exe` when running out of a JLL during bootstrap.

[CSL]: Include `libwinpthread`

---

L/LLVM/common.jl
L/LLVM/libLLVM@9.0.1/build_tarballs.jl

`llvm-config` spits out lots of warnings if the static libraries aren't available, so just ship 'em.

[LLVM]: ship static libraries in `libLLVM` and `Clang`

---

K/KAShim/build_tarballs.jl

Wizard recipe: KAShim-v0.1.0

---

O/OpenBLAS/OpenBLAS@0.3.9/build_tarballs.jl
O/OpenBLAS/OpenBLAS@0.3.9/bundled/patches/openblas-ofast-power.patch
O/OpenBLAS/OpenBLAS@0.3.9/bundled/patches/openblas-winexit.patch
O/OpenBLAS/common.jl

I've rebased the patches to 0.3.9, let's see if they are still working properly.

Bump OpenBLAS 0.3.9

---

.ci/register_package.jl

For some reason, I was iterating over the `objs` object instead of the nice merged object?  I don't know why.  @giordano do you have any idea why I would have been doing that?  This is definitely a case of me looking at this and thinking to myself "now why on earth would I have ever done that?"

[AZP] Fix registration doing extra work

---

C/CompilerSupportLibraries/build_tarballs.jl

Some GCC versions replace `.so` files with linker scripts

[CompilerSupportLibraries] Remove linker script `.so` files

---

G/GLPK/build_tarballs.jl

Use gcc 6 as the preferred GCC, to be consistent with GMP.

[GLPK] add GLPK 4.64

---

H/HELICS/build_tarballs.jl

Release notes: https://github.com/GMLC-TDC/HELICS/releases/tag/v2.4.2

[HELICS] update to 2.4.2

---

O/OpenSSL/build_tarballs.jl

* Compared to 1.1.1c. 1.1.1e fixes 5 low priority vulnerabilities https://www.openssl.org/news/vulnerabilities.html
* `install_sw` should only install the OpenSSL software components, helping in https://github.com/JuliaPackaging/Yggdrasil/issues/668 by not including the docs that make most of the uncompressed artifact size

Update OpenSSL to 1.1.1e, do not install docs

---

C/CALCEPH/build_tarballs.jl

* Package name: CALCEPH
* Version: v3.4.2

Wizard recipe: CALCEPH-v3.4.2

---

I/ImageMagick/build_tarballs.jl

Output of `print_package_disk_usage()` says ImageMagick version = "6.9.10-12+0" takes 83.75 MiB on disk on Windows. Disabling docs and static libraries should bring this to about 42 MiB.
* `--disable-static` https://github.com/ImageMagick/ImageMagick/blob/7.0.10-3/Install-unix.txt#L204-L211
* `--disable-docs` https://github.com/ImageMagick/ImageMagick/blob/7.0.10-3/configure.ac#L3039-L3045
Note: the links are to ImageMagick v7 since I did not find v6.9 on github.

ImageMagick disable docs, disable static

---

N/Ninja/build_tarballs.jl
N/ninja/build_tarballs.jl

ninja build tool: https://ninja-build.org/
I know that this exists already in the build environment but we need this at runtime for the target platform as well, for Polymake.jl . (To compile C++ template instantiations on demand for our C++ / perl interface.)

[ninja] new recipe

---

O/OpenBLAS/OpenBLAS32@0.3.9/build_tarballs.jl
O/OpenBLAS/OpenBLAS32@0.3.9/bundled/patches/openblas-ofast-power.patch
O/OpenBLAS/OpenBLAS32@0.3.9/bundled/patches/openblas-winexit.patch
O/OpenBLAS/common.jl

@staticfloat @giordano 
Many libraries hardcode the assumption of a 32-bit BLAS even on 64-bit platforms. @staticfloat suggested two options - OpenBLAS32_jll for such packages which provides a 32-bit BLAS on all platforms (includeing 64-bit) which would be nice for interoperability, or building 32-bit stubs that dispatch to 64-bit. I like OpenBLAS32_jll since I don’t have to write new code, and packages that need this can simply just pull it in.
I am not sure if this is the best way to build the 32-bit variant of OpenBLAS on 64-bit platforms. Requesting a review on how best to organize this.

OpenBLAS32: An LP64 openblas with 32-bit BlasInt on 64-bit platforms

---

A/ASL/bundled/asl-extra/aslinterface.cc
A/ASL/bundled/asl-extra/aslinterface.h

Recover _n_cc_ (integer) and _cvar_ (array of integer) from ASL to handle complementarity constraints.

[ASL] add `n_cc` and `cvar`

---

G/gmmlib/build_tarballs.jl

This one was significantly easier. Adds a recipe for https://github.com/intel/gmmlib, another dependency for the NEO compute stack.

Add recipe for the Intel Graphics Memory Management Library.

---

L/libigc/build_tarballs.jl
L/libigc/bundled/patches/cbc78036d1a5bd0a889acdc87c2fb902d5ace159.patch

This PR adds a recipe for the Intel Graphics Compiler (Linux only) from https://github.com/intel/intel-graphics-compiler. Requires some hacks, most notably to avoid using target binaries as the library relies on LLVM and generates precompiled headers using Clang at compile time (let's hope their format is portable...).

Add a new recipe for the Intel Graphics Compiler.

---

O/OpenCL-Headers/build_tarballs.jl

Bit of a silly package, but we need it as a build dependency for e.g. the Level Zero loader. Could be platform agnostic, but I don't think we support that?

Add recipe for the OpenCL headers.

---

C/CImGui/build_tarballs.jl
C/CImGui/bundled/wrapper/CMakeLists.txt

This file contains full compilation info and can be used in Clang.jl.

cimgui: Export `compile_commands.json`

---

M/MicrosoftMPI/build_tarballs.jl

It wasn't clear how to get this to build directly, since it requires Visual Studio, so instead we download and extract the Micrsoft-provided binaries.

add Microsoft MPI

---

M/MUMPS_seq/build_tarballs.jl

MUMPS_seq provides fake mpi.h and mpif.h that could conflict with
the actual header files from an MPI implementation.

MUMPS_seq: install headers in include/mumps_seq

---

.ci/Manifest.toml

New version of RegistryTools includes https://github.com/JuliaRegistries/RegistryTools.jl/pull/29, which should address https://github.com/JuliaPackaging/BinaryBuilder.jl/issues/722

[AZP] Bump RegistryTools version

---

L/Libxc/build_tarballs.jl

Fixes as discussed in #782. I also added a "--disable-static" to hopefully avoid the production of the `.a` files.

Fixes for Libxc 5.0.0

---

M/mlpack/build_tarballs.jl

Version 3.3.0 was released, so, I've updated the package here and added two new `LibraryProduct`s (which correspond to functions that are made available in Julia's mlpack package).
Previously, we used a placeholder version that we versioned as 3.3.0, since the 3.3.0 release of mlpack was actually waiting for Julia availability. :)  So, do I need to bump the version or anything?  Maybe `3.3.0-1`?  I don't know if that will be needed.

Update mlpack to latest stable version.

---

M/MUMPS_seq/build_tarballs.jl

This library is currently only used by Ipopt, which uses 32-bit Ints and segfaults if MUMPS_seq is linked against `libopenblas64_`.

MUMPS_seq: use OpenBLAS32

---

L/LLVM/Clang@9.0.1/build_tarballs.jl
L/LLVM/LLVM@9.0.1/build_tarballs.jl
L/LLVM/common.jl

We were missing these internal headers that get tucked away in `${prefix}/lib/clang/${version}`.

[Clang_jll]: ship internal headers

---

I/Ipopt/build_tarballs.jl

We incorrectly rewrote `/usr/lib/libc++.1.dylib` -> `@rpath/libc++.1.dylib`.  This [has been fixed](https://github.com/JuliaPackaging/BinaryBuilder.jl/commit/64f26e73c6c751eaf1032e2754cd29b6f47d2bf3), but we need to rebuild this JLL, unfortunately.

[Ipopt] Rebuild incorrect `libc++.1.dylib` rewrite

---

L/Libtiff/build_tarballs.jl

It seems a bit sad to depend on Zlib and JPEG but not configure libtiff to enable them, so this PR does just that. Possibly some paths to those libraries will need to be configured as well, CI will tell.

Configure libtiff with ZIP and JPEG.

---

C/CUDA/CUDA@10.0/build_tarballs.jl
C/CUDA/CUDA@10.1/build_tarballs.jl
C/CUDA/CUDA@10.2/build_tarballs.jl
C/CUDA/CUDA@9.0/build_tarballs.jl
C/CUDA/CUDA@9.2/build_tarballs.jl

This JLL is for use in packages that need CUDA libraries, and is basically a reorganized and stripped (removing stuff we don't need or can't redistribute) version of CUDA_full_jll. Modeled after the LLVM JLLs. Still requires a NVIDIA driver to provide `libcuda.so`.

[CUDA] Rework CUDA_jll on top of CUDA_full_jll.

---

Y/YAJL/build_tarballs.jl
Y/YAJL/bundled/patches/01-fix-windows-compiler.patch

Add YAJL recipe

---

M/MicrosoftMPI/build_tarballs.jl

This keeps the library name the same for both builds, which should simplify matters. It also keeps it consistent with the installer, which renames them when it installs.

MicrosoftMPI: remove 32-bit files from 64-bit

---

L/libigc/build_tarballs.jl
L/libigc/bundled/patches/gcc-constexpr_assert_bug.patch

Listening to @giordano's stream taught me that we don't actually need to cross-compile when targeting 32/64-bit glibc, so let's not do that! :smile:  Now, I know that wasn't the point he was trying to get across, but libigc is a pain to cross-compile. In fact, I think it even causes my binaries to segfault when used by another package (https://github.com/intel/intel-graphics-compiler/issues/128), so let's disable cross-compilation for now. The compiler is only supported on Intel anyhow, and I'm happy to revisit once upstream has dealt with some of the issues.

[libigc] Disable cross compilation.

---

L/libcgal_julia/build_tarballs.jl

In light of the most recent update to CxxWrap, a new version was issued alongside an update to the lib's buildscript, the latter being intensely inspired by `libcxxwrap_julia`'s recipe.
The buildscript update includes the addition of julia binaries as sources, much like `libcxxwrap_julia`.

[libcgal-julia] Update to 0.7.0 + update build script

---

M/METIS/METIS@4/build_tarballs.jl
M/MUMPS/MUMPS_seq@4/build_tarballs.jl
M/MUMPS/MUMPS_seq@4/bundled/patches/quiet.diff

[METIS@4] Build only static libraries to avoid conflict with METIS@5
[MUMPS_seq@4] Build only static libraries to avoid conflict with MUMPS_seq@5
@giordano If I am only building `.a` files, is there a build product I should specify?
cc @dpo We should update any packages that depend on METIS 4 to link against it statically. I think that is a safe way to do it to avoid conflict with METIS 5 being available as a shared library.

[METIS@4 and MUMPS_seq@4] Build only static libraries

---

0_RootFS/Rootfs/bundled/utils/sandbox.c

Abort tries to send SIGABRT to the current process, but init can't receive signals.
Use _exit instead.
Incidentally, this also causes attached debugging tools to go crazy, which I belive
is a kernel bug (https://lkml.org/lkml/2020/4/11/38).

Don't use abort in _check

---

S/SPIRV_LLVM_Translator/SPIRV_LLVM_Translator@10/build_tarballs.jl
S/SPIRV_LLVM_Translator/SPIRV_LLVM_Translator@8/build_tarballs.jl
S/SPIRV_LLVM_Translator/SPIRV_LLVM_Translator@9/build_tarballs.jl
S/SPIRV_LLVM_Translator/common.jl

This tool uses LLVM, so I guess this will be a bit tricky :-) Some thoughts:
- `get_addable_spec` errored, so constructing the PackageSpec manually here
- I need LLVM_full for building (for the CMake files), and Julia's libLLVM at run time; depending on both seems to result in ugly warnings during artifact set-up (symlink already exists)
- This currently only works with 1.5/LLVM9, https://github.com/JuliaRegistries/General/blob/3c3a2496d5a6f62ea0e08542b37d9558fdd28a40/L/libLLVM_jll/Compat.toml, but I assume we will have a version of libLLVM_jll compatible with other Julia versions?

Add the SPIRV to LLVM translator.

---

H/HiGHS/build_tarballs.jl
H/HiGHS/bundled/patches/mm_malloc.patch

Following the fix in https://github.com/JuliaPackaging/Yggdrasil/blob/48ac662cd53e02aff0189c81008874a04f7172c7/Z/ZeroMQ/build_tarballs.jl#L24
we can expand the platorms HiGHS is currently building on (I hope)

HiGHS: expanding platforms with patch

---

C/Coin-OR/Clp/build_tarballs.jl
C/Coin-OR/coin-or-common.jl

Contains a bug-fix for https://github.com/coin-or/Clp/issues/142
cc @ViralBShah is this all I need to do for a release?

[Clp] Add v1.17.6

---

X/XML2/build_tarballs.jl

Still quite a lot of docs here:

remove more docs from XML2

---

C/CUDA/CUDA_full@10.0/build_tarballs.jl
C/CUDA/CUDA_full@10.1/build_tarballs.jl
C/CUDA/CUDA_full@10.2/build_tarballs.jl
C/CUDA/CUDA_full@9.0/build_tarballs.jl
C/CUDA/CUDA_full@9.2/build_tarballs.jl

Fixes https://github.com/JuliaPackaging/Yggdrasil/issues/844
I guess there isn't a mechanism for it right now (ship `${prefic}/etc/profile.d/cuda`?), but the package could set CUDA_HOME to `${prefix}/cuda` to help discoverability.

[CUDA] Put the toolkit in a cuda subdirectory of the prefix.

---

O/oneAPI_Level_Zero/build_tarballs.jl

```julia
Dependency("NEO_jll"), # FIXME: OptionalDependency
```
We could create an `OptionalDependency`, which the JLL code could look for (`isdefined(Main, :OptDep_jll)`) and put on the search path. Thoughts? Or is there a mechanism already to do so?

[oneL0] Depened on an implementation of the API, for now.

---

R/Readline/build_tarballs.jl

Actually my main motivation to make this was that the Readline_jll repository is 5 months old and the generated code there is outdated; e.g. Readline_jll is lacking the `artifact_dir` variable. But I figured it doesn't hurt to also get some fixes in there ;-).

[Readline] update to 8.0.4

---

C/Coin-OR/Clp/build_tarballs.jl

Use `-DNDEBUG` to try to be on par with the performance of the original builders: https://github.com/JuliaOpt/Clp.jl/pull/77#issuecomment-615006008

[Clp] Add -DNDEBUG

---

C/Coin-OR/Cbc/build_tarballs.jl

To be honest, I'm not entirely sure why, but it does look like we need to expand the libgfortran version also in Cbc, as suggested by @ViralBShah at https://github.com/JuliaPackaging/Yggdrasil/pull/869#issuecomment-614993593.  I've built it locally for `x86_64-linux-gnu-libgfortran4-cxx11` and now the library `libCbc.so` correctly looks for the symbol
```
% nm libCbcSolver.so|grep _ZTv0_n720_NK21OsiClpSolverInterface10getRowNameB5cxx11Eij|c++filt 
U virtual thunk to OsiClpSolverInterface::getRowName[abi:cxx11](int, unsigned int) const
```

[Cbc] Expand libgfortran version

---

C/Coin-OR/Clp/build_tarballs.jl

This ensures that `-O3` etc. get passed to the compiler.

[Clp] Avoid setting CXXFLAGS

---

E/Eigen/build_tarballs.jl

Eigen already installs a Eigen3Config.cmake file in share/eigen3/cmake, 
so there is no need to additionally install the FindEigen3.cmake file.
Furthermore, ${prefix}/share/eigen3/cmake is not on the CMAKE_MODULE_PATH, 
so in any case the FindEigen3.cmake file installed there would be ignored by CMake.
@dpo @giordano

[Eigen] Do not install FindEigen3.cmake file

---

E/Eigen/build_tarballs.jl

The Bitbucket repository of Eigen has been deprecated some time ago  (see https://bitbucket.org/eigen/eigen/src/default/README.md ), so it  probably make more sense to use the Gitlab archives, that are the one  linked in the official  Eigen website as well: http://eigen.tuxfamily.org/index.php?title=Main_Page .
Note that the hash is different probably due to the differences between Bitbucket and GitLab automatically generated archives.

[Eigen] Switch to download Gitlab archive instead of deprecated Bitbucket archive

---

generate_buildjl.jl

Before this PR:
```
$ julia --color=yes generate_buildjl.jl C/CompilerSupportLibraries/build_tarballs.jl JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl CompilerSupportLibraries-v0.3.3+0
[ Info: Build tarballs script: C/CompilerSupportLibraries/build_tarballs.jl
[ Info: Repo name: JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl
[ Info: Tag name: CompilerSupportLibraries-v0.3.3+0
[ Info: Building for 
ERROR: LoadError: UndefVarError: _products not defined
Stacktrace:
[1] top-level scope at /home/blegat/git/Yggdrasil/generate_buildjl.jl:212
in expression starting at /home/blegat/git/Yggdrasil/generate_buildjl.jl:211
```
After this PR:
```
$ julia --color=yes generate_buildjl.jl C/CompilerSupportLibraries/build_tarballs.jl JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl …
```

Typo fix: _producs -> _products

---

S/SPIRV_Tools/build_tarballs.jl

Recipe has some vendored deps, of which at least SPIRV-Headers could be moved out. But lacking an Any platform, and with no other packages using the SPIRV Headers, I left it in for now.

[SPIRV] Add recipe for SPIRV Tools.

---

I/LittleCMS/build_tarballs.jl

I generated this with the wizard locally without the `autoreconf` and `update_configure_scripts` and it failed on powerpc, so I added these here to try it on the CI to see if that would help.
This is a dependency of openjpeg and of poppler; openjpeg is also a dependency of poppler. I'm interested in building poppler for [pdfsandwich](http://www.tobias-elze.de/pdfsandwich/) to setup a convenient binary story for OCRing PDFs; I know @asinghvi17 is interested in building poppler too, I think for MakieTex stuff.

Build LittleCMS

---

O/oneAPI_Level_Zero/build_tarballs.jl

I think the current tarballs are missing two symlinks, that are instead correctly generated by `symlink_soname_lib` when building a dependency, but not removed by `cleanup_dependencies` because they're missing in current `oneAPI_Level_Zero_jll` tarballs.
This is for example causing spurious warnings in https://github.com/JuliaPackaging/Yggdrasil/pull/901.
I'm triggering this build mostly to make sure that my understanding is correct.  I'm not sure why the two symlinks are missing from the current tarballs

[oneAPI_Level_Zero] Rebuild to generate missing symlinks

---

generate_buildjl.jl

Without this, the generated `build.jl` throws a `MethodError` when trying to create the `LibraryProduct` object.

Add prefix first argument to LibraryProduct

---

M/MicrosoftMPI/build_tarballs.jl

In #845 I found that the header file `mpifptr.h` was expected, but currently we're installing `mpifptr32.h` and `mpifptr64.h`, which are actually identical.  With this PR I'm installing only one.  CC: @simonbyrne
BTW, I just noticed that msys2/MingW has a recipe to build MicrosoftMPI from source: https://github.com/msys2/MINGW-packages/tree/master/mingw-w64-msmpi

[MicrosoftMPI] Install only one mpifptr.h header file

---

N/NEO/build_tarballs.jl

The circular dependency between oneAPI_Level_Zero and NEO turned out problematic, e.g., when upgrading NEO (which pulled in oneAPI_Level_Zero, depending on an older NEO, depending on conflicting deps):
```
ERROR: LoadError: Unsatisfiable requirements detected for package NEO_jll [700fe977]:
NEO_jll [700fe977] log:
├─possible versions are: 20.12.16259 or uninstalled
├─restricted by compatibility requirements with libigc_jll [94295238] to versions: uninstalled
│ └─libigc_jll [94295238] log:
│   ├─possible versions are: [1.0.3586, 1.0.3771] or uninstalled
│   └─restricted to versions 1.0.3771 by an explicit requirement, leaving only versions 1.0.3771
└─restricted by compatibility requirements with oneAPI_Level_Zero_jll [0038a6a5] to versions: 20.12.16259 — no versions left …
```

[NEO] Remove the circular dependency on oneAPI, and update deps.

---

generate_buildjl.jl

This third loop is needed for `C/Coin-OR/Clp`.

[generate_buildjl] Fix CompilerABI with gfortran and cxx

---

P/Poppler/build_tarballs.jl

This doesn't work yet, giving the following error:
```julia
CMake Error at /opt/i686-linux-gnu/i686-linux-gnu/sys-root/usr/local/lib/openjpeg-2.3/OpenJPEGTargets.cmake:78 (message):
The imported target "opj_decompress" references the file
"/opt/i686-linux-gnu/i686-linux-gnu/sys-root/usr/local/bin/opj_decompress"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
"/opt/i686-linux-gnu/i686-linux-gnu/sys-root/usr/local/lib/openjpeg-2.3/OpenJPEGTargets.cmake"
but not all the files it references.
Call Stack (most recent call first):
/opt/i686-linux-gnu/i686-linux-gnu/sys-root/usr/local/lib/openjpeg-2.3/OpenJPE …
```

Add Poppler

---

0_RootFS/PlatformSupport/build_tarballs.jl

We're currently linking only `lib/` and `lib64/` to the prefix, however CMake
find modules often find libraries in `${sysroot}/usr/local/lib` and then use
relative paths to executables or header files, that therefore can't be found.
With this change we link `${sysroot}/usr/local` to the entire prefix, which
should alleviate these issues, until the time we don't need to add this link at
all.

[PlatformSupport] Link `${sysroot}/usr/local` to entire `${prefix}`

---

U/unpaper/build_tarballs.jl

This errors out with:
```
/opt/i686-linux-gnu/bin/../lib/gcc/i686-linux-gnu/8.1.0/../../../../i686-linux-gnu/bin/ld: warning: libstdc++.so.6, needed by /workspace/destdir/lib/libx265.so.169, not found (try using -rpath or -rpath-link)
/opt/i686-linux-gnu/bin/../lib/gcc/i686-linux-gnu/8.1.0/../../../../i686-linux-gnu/bin/ld: /workspace/destdir/lib/libx265.so.169: undefined reference to `__cxa_guard_acquire@CXXABI_1.3'
/opt/i686-linux-gnu/bin/../lib/gcc/i686-linux-gnu/8.1.0/../../../../i686-linux-gnu/bin/ld: /workspace/destdir/lib/libx265.so.169: undefined reference to `operator delete(void*)@GLIBCXX_3.4'
/opt/i686-linux-gnu/bin/../lib/gcc/i686-linux-gnu/8.1.0/../../../../i686-linux-gnu/bin/ld: /workspace/destdir/lib/libx265.so.169: undefined reference to `vtable for …
```

Add `unpaper`

---

I/ImageMagick/build_tarballs.jl

It would be helpful to be able to do stuff like `ImageMagick_jll.convert_path`; these two are the ones needed for pdfsandwich.

[ImageMagick] Add `convert` and `identify` to products

---

C/CovidSim/build_tarballs.jl
C/CovidSim/bundled/patches/0001-fix-lib-cases.patch

* Package name: CovidSim
* Version: v0.8.0

Wizard recipe: CovidSim-v0.8.0

---

.ci/register_package.jl

Fixes error with PR #586
This requires PR https://github.com/JuliaPackaging/BinaryBuilder.jl/pull/754 to be merged and operational on Yggdrasil.
I generated a test-repo using these changes here: https://github.com/barche/Qt_jll.jl
This worked on both Mac and Linux (tested by calling qVersion in libqt5core). Note that the version is still 5.14.1 on my testrepo because I still had those binaries and didn't want to rebuild.
Disclaimer: I have no idea if this causes any side effects with other builds, or how to test this rigorously 🙃

Fix JLL with multiple build_tarballs

---

.ci/register_package.jl

This reverts changes in #894.
This is to be reverted once we upgrade BinaryBuilder here, hopefully in the next few days!

[AZP] Temporarily revert changes to `.ci/register_package.jl`

---

C/Coin-OR/CSDP/build_tarballs.jl

@blegat Trying this out to see if it helps.

[CSDP] Build without openmp on windows

---

L/LibCURL/build_tarballs.jl

The curl project extracts the mozilla CA certificate bundle, and and provides it for download in a format amenable to curl. We can use this to bypass the vagaries of the OS installed cert bundles.
Close #957.

[LibCURL] Upgrade curl to 7.70.0 and add cacert

---

Z/Zstd/build_tarballs.jl

We already build it, it just doesn't have an export in the jll.

Add zstdmt target for Zstd

---

P/PROJ/build_tarballs.jl

In #962 we just built the latest PROJ 6 release, but PROJ 7 is already out.
[Proj4.jl](https://github.com/JuliaGeo/Proj4.jl) was written for the PROJ 4 API, which is deprecated now. This is probably a good moment to both switch to the new API and rename (i.e. start a new) package named PROJ as well.

[PROJ] build new major version 7

---

I/ImageMagick/build_tarballs.jl

Companion PR to https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/pull/1 so the changes there don't get overwritten if the `build_tarballs` gets updated.
Another, just in case:
[ci skip]
[skip ci]

[ImageMagick] rename `convert` to not conflict with Base

---

L/Libtiff/build_tarballs.jl

Directly bumps to the latest 4.1.0 release from November 2019.
It seems the current libtiff build is broken on Windows, possibly since #961.
```
julia> using Libtiff_jll
ERROR: InitError: could not load library "C:\Users\visser_mn\.julia\artifacts\f98adb5b4de5c29a8d77def412b792beaec6180b\bin\libtiff-5.dll"
The specified module could not be found.
Stacktrace:
[1] dlopen(::String, ::UInt32; throw_error::Bool) at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.4\Libdl\src\Libdl.jl:109
[2] dlopen at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.4\Libdl\src\Libdl.jl:109 [inlined] (repeats 2 times)
[3] __init__() at C:\Users\visser_mn\.julia\packages\Libtiff_jll\0kDRi\src\wrappers\x86_64-w64-mingw32.jl:45
[4] _include_from_serialized(::String, ::Array{Any,1}) …
```

try unbreaking libtiff on windows with new build

---

B/Blosc/build_tarballs.jl

Explanation at #970. I just tried
```
(Proj4) pkg> add Blosc_jll
Resolving package versions...
Installed Lz4_jll ─── v1.9.2+0
Installed Blosc_jll ─ v1.14.3+0
Updating `C:\Users\visser_mn\.julia\dev\Proj4\Project.toml`
[0b7ba130] + Blosc_jll v1.14.3+0
Updating `C:\Users\visser_mn\.julia\dev\Proj4\Manifest.toml`
[0b7ba130] + Blosc_jll v1.14.3+0
[5ced341a] + Lz4_jll v1.9.2+0
julia> using Blosc_jll
[ Info: Precompiling Blosc_jll [0b7ba130-8d10-5ba8-a3d6-c5182647fed9]
ERROR: InitError: could not load library "C:\Users\visser_mn\.julia\artifacts\579a09774380e99d70add2ba8682e426c8d2d76e\bin\libblosc.dll"
The specified module could not be found.
Stacktrace:
[1] dlopen(::String, ::UInt32; throw_error::Bool) at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.4\Libdl\src\Libdl.jl:109 …
```

blosc rebuild after renamed libzstd dll

---

L/Leptonica/build_tarballs.jl

Even though Giflib_jll was added as a dependency the configure script did not find gif_lib.h so GIF support was disabled.  You can see this in the Leptonica.log lines 325 to 327:
```
checking gif_lib.h usability... no
checking gif_lib.h presence... no
checking for gif_lib.h... no
```
Additionally you can test it with the julia code:
```
julia> using Leptonica_jll
julia> buffer = Vector{UInt8}()
0-element Array{UInt8,1}
julia> ccall((:pixReadMemGif, Leptonica_jll.liblept), Cvoid, (Ptr{UInt8}, Csize_t), buffer, 0)
Error in pixReadMemGif: function not present
```
Which is the stub that is compiled in when libgif wasn't linked.
This change defines CPPFLAGS to include the $prefix/include directory which allows `configure` to determine that gif_lib.h is available and thus GIF support is …

Adds GIF and OpenJpeg support to the Leptonica library.

---

0_RootFS/PlatformSupport/bundled/buildsystem_toolchains/build_toolchains.sh

We often need to manually tell meson to not try to run executables for this platform, and modifying the toolchain file is incredibly annoying.  We had to this for example in #961 and #91
@staticfloat I hope it isn't too late to get this into BB :grimacing:

[PlatformSupport] Tell meson we need a wrapper for `i686-linux-musl`

---

F/FLAC/build_tarballs.jl
F/FLAC/bundled/patches/flac_linux_headers.patch

We need this if only to get the `arm`/`armv7l` renaming stuff baked in.

[FLAC]: upgrade buildscript and expand cxx

---

O/Ogg/build_tarballs.jl

This also has the nice side-effect of upgrading our JLL to work on `armv7l` with the renaming.

[Ogg] Bump to v1.3.4

---

F/FastTransforms/build_tarballs.jl

This adds AVX and FMA support (dispatched by cpu id) for spin-weighted spherical harmonics, and fixes a bug (that I introduced in v0.3.0) regarding orthogonal polynomial transforms on a tetrahedron.

[FastTransforms] v0.3.1

---

D/Dex/build_tarballs.jl
D/Dex/bundled/patches/01-allow-optional-github-gitlab-scopes.patch

This provides federated OpenID Connect provider [Dex](https://github.com/dexidp/dex).
This includes a patch to allow optional additional scopes to be specified in configuration for github and gitlab connectors.

Add builder for Dex (dexidp/dex)

---

D/Dex/build_tarballs.jl

Since Dex web templates are version specific, it makes sense to include them as artifacts here.
Updating the builder to add a `FileProduct` with tar gzipped web templates.

Update Dex builder to include additional artifact

---

.ci/download_sources.jl
azure-pipelines.yml

Ideally we should have a fix in BinaryBuilder, but I'd like to see first here what are all the changes needed to make the pipeline involving `AnyPlatform` work.  See for reference #990

[AZP] Fix list of platforms when we have `AnyPlatform`

---

S/SPIRV_Cross/build_tarballs.jl

cc @maleadt @vchuravy 
I'm playing around with Metal on OSx, and this is needed for the compiler toolchain.
On osX I get an error 
```
ld: unknown option: -soname
```
so I used sed to patch it up, but I'm sure we can do better.

New Recipe: SPIRV_Cross v2020-04-03

---

T/Tesseract/build_tarballs.jl
T/Tesseract/bundled/patches/disable_fast_math.patch

I disabled -ffast-math to conform with current requirements.  Unfortunately it doesn't appear you can disable it with a compile flag so I put together a patch to apply to the make file.

Updated Tesseract to 4.1.1.

---

N/NOMAD/build_tarballs.jl

We need to fix some bugs associated to parralel evaluations of a black-box in C interface between NOMAD and Julia. I temporarily disable parallelism.

Build NOMAD without OpenMP

---

O/Openresty/build_tarballs.jl

This adds a new builder for [Openresty](https://openresty.org/en/) - a web server based on NGINX and LuaJIT.

New builder for Openresty

---

T/ThriftJuliaCompiler/build_tarballs.jl

This adds a builder for the Thrift IDL compiler for Julia. Includes additional patches to Thrift maintained [here](https://github.com/tanmaykm/thrift).

Add builder for Julia Thrift IDL Compiler

---

L/lib4ti2/build_tarballs.jl
L/lib4ti2/bundled/patches/ftrapv.patch
L/lib4ti2/bundled/patches/gmp.patch
L/lib4ti2/bundled/patches/time.patch

This contains some nasty workarounds for issues with `libstdc++.la` -- I wonder if these hint at an issue with the build environment? Or perhaps I am doing something stupid?  (perhaps @benlorenz has an idea -- but don't feel compelled to look, or waste time on this).
There are a few issues building everything for all platforms, so I may have to disable some. But I thought I should submit this now, even though it is not 100% ready, in the hopes that somebody has feedback on the `libstdc++.la` problems, and also so that I can show this more easily to people who might be interested in using this (e.g. @mohamed-barakat). And finally perhaps there are other things I should be doing differently here, then it'd be good to hear about it sooner rather than later :-).

New Recipe: lib4ti2 1.6.9

---

L/librsync/build_tarballs.jl

This adds a build recipe for `librsync`. 
The library has an optional command line binary called `rdiff` but that is not included since it depends on `libpopt` which we don't yet seem to have. So only the shared lib `librsync` is included for now. 
cc: @StefanKarpinski

librsync build recipe

---

L/lib4ti2/build_tarballs.jl

People are using these scripts, so let's make a best effort to have
the available; of course on Windows, one has to find a POSIX shell
to run them, but that shouldn't be a reason to cripple this package
on Unix variants.

4ti2: add some shell scripts as FileProduct

---

L/librsync/build_tarballs.jl

We now build the `rdiff` executable in addition to the shared lib. 
cc: @StefanKarpinski

[librsync] build rdiff executable

---

I/iODBC/build_tarballs.jl

* Package name: iODBC
* Version: v3.52.13

Wizard recipe: iODBC-v3.52.13

---

generate_buildjl.jl

`Module(:x)` doesn't define `include` and `eval` so `include_string`,
with an include statement will fail.

Fix definition of anonymous module and 1.5 compat

---

Z/ZeroMQ/build_tarballs.jl

Rebuilding the package also fixes the wrapper for old macOS versions (ref:
https://github.com/JuliaPackaging/BinaryBuilder.jl/pull/775).

[ZeroMQ] Remove static archive from the tarball

---

J/Julia/build_tarballs.jl

It's in `sources` but not `platforms`. See https://github.com/JuliaPackaging/Yggdrasil/pull/1048#discussion_r428150041

[julia] Add FreeBSD to `platforms`

---

C/CImGui/build_tarballs.jl
C/CImGui/bundled/wrapper/CMakeLists.txt

With this PR, CImGui_jll ships a stand-alone libimgui-cpp.so that can be reused in cimplot.

CImGui: Split imgui and cimgui libs

---

P/pandoc/build_tarballs.jl

Supports linux64, mac64, windows32 and windows64
I'll need help to fix some of the warning, probably needs some patchelf wrangling.

repackage pandoc binaries into jll

---

I/IpoptMKL/build_tarballs.jl

Is this of interest? There have been a few requests for Ipopt/MKL recently over at Ipopt.jl.

IpoptMKL: new recipe

---

L/libcgal_julia/build_tarballs.jl

The library exposes a few more 2D Triangulation types and methods, as
well as some missing 2D Voronoi Diagram methods.
Furthermore, the buildscript itself has been updated to use `Julia_jll`
as a build dependency instead of unpacking platform specific tarballs,
hacked within the buildscript.

[libcgal-julia] Update to v0.9.0 + purge julia dependency hack

---

L/libcgal_julia/build_tarballs.jl

Instead of working about a method to map circulators/iterators directly
to julia (even though they're mostly pointers and dereferncing them
should be enough, the underlying types are unnecessarily complex), the
elements are collected in the C++-side into arrays.
As such, this patch includes a tiny change which involves copying the
beginning of the circulator instead of modifying it directly.
Sorry for the extra PR... I just feel this could have caused some
damage in the short term.

[libcgal-julia]: Minor update to v0.9.1

---

C/Coin-OR/CSDP/build_tarballs.jl

Fix #1081.  @blegat could you please check when the tarballs are ready?  I think this was caused by my mistake in BB documentation (fixed by https://github.com/JuliaPackaging/BinaryBuilder.jl/pull/800)

[CSDP] Revert use of `flagon`

---

L/libcxxwrap_julia/build_tarballs.jl

This hopefully fixes CxxWrap.jl on systems which have e.g. gfortran 5.
See https://github.com/JuliaInterop/CxxWrap.jl/issues/246
Ping @barche @mohamed-barakat @benlorenz

libcxxwrap_julia: drop libgfortran_version from platform specifiers

---

.ci/register_package.jl
H/HelloWorldRust/build_tarballs.jl
azure-pipelines.yml

The magic word is `[skip build]`, this tells to the pipeline to not build new
tarballs and reuse those from the latest build.  Fix #938.
Note: this is a proof-of-concept, not tested yet!

[AZP] Allow skipping building of binaries with keyword in commit message

---

H/HelloWorldRust/build_tarballs.jl
azure-pipelines.yml

Even though the macro syntax for environment variables in Azure Pipelines _looks
like_ command substitution, that is processed before runtime, see
https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#macro-syntax-variables.
Thus we have to protect `$(Build.SourceVersionMessage)` with single quotes to
avoid evaluating its value.
This makes it possible to safely type `[skip build]` in the commit message.

[AZP] Fix check on the environment variable with the commit message

---

.ci/register_package.jl
H/HelloWorldGo/build_tarballs.jl

In the previous commit I tried to test `[skip build]` with `HelloWorldRust_jll`,
but it failed because `HelloWorldRust_jll` had never been registered.  At least
we know that the check is working correctly :slightly_smiling_face: Trying again
with `HelloWorlGo_jll` which does have a registered version to update.

[HelloWorldGo] Update wrappers

---

L/libserialport/build_tarballs.jl

sigroks libseriallib hasn't been updated in four years, although many bug fixes and improvements have been implemented. This PR creates a new version 0.2.0 (0.1.1 is the latest release), which builds from master.
It was mentioned that sigrok wants to release a new version of libserialport in the near future, but its unclear when this is going to happen. I think it would be good to release this interims build.
I've tested it on Windows 64 and Linux 64 (glibc).

Update libserialport to build from master

---

N/NetCDF/build_tarballs.jl

I first tried to commit directly to
https://github.com/JuliaPackaging/Yggdrasil/pull/513
but I got a permission denied error.
armv7l-linux-gnueabihf build is still failing.
The build script could be simplified for in HDF5, if one would also provide libhdf5.so/libhdf5.dynlib in addition to libhdf5.so.x.y/libhdf5.x.y.dynlib (the same for libhdf5_hl).

NetCDF builds for Linux x86, Windows and Mac OS

---

H/Hwloc/build_tarballs.jl

The Hwloc recipe is so old that a jll doesnt seem to have been built. Also update the package to the latest version.

[Hwloc] Update to 2.2 and jll

---

E/eccodes/build_tarballs.jl
E/eccodes/bundled/patches/unix.patch
E/eccodes/bundled/patches/windows.patch

I think this works? I had to go in and change the version to 2.17 because I didn't understand that entry in the wizard. It should build on MacOS since conda-forge supports it, but I don't have an Apple computer so the wizard didn't generate that. The sed patch in the script is to knock out where cmake was calling try_run because the ECMWF developers didn't trust the `test_big_endian` function.

New Recipe: ecCodes v2.17.0

---

M/MongoC/build_tarballs.jl

Mongo C Driver for all platforms: Windows/Linux/Mac
Built *with* OpenSSL, Zlib and Zstd, *without* kerberos or ldap authentication, or snappy compression, or ICU
*[edit]* now includes Snappy
cc: @felipenoris

Mongo C Driver

---

F/FLINT/build_tarballs.jl

Update to new release, remove some workarounds, switch to proper version number now that there is a proper release.

[FLINT] update to version 2.6.0

---

Z/ZeroMQ/build_tarballs.jl

Draft ZMQ socket types are allowed to break compatibility, but for those that want to use them, let's give them the option.

[ZeroMQ]: Enable draft ZMQ socket types

---

N/normaliz/build_tarballs.jl

- remove workaround for #624 
- add `FLINT_jll` as dependency
- add `nauty_jll` as dependency

[normaliz] update to version 3.8.5

---

A/Arb/build_tarballs.jl

This will be failing for a few platforms (I have included the list of platforms for which it worked).
I don't care too much about musl (nor do I know what this is :)). But I do care about Windows!
I think there are two problems for Windows. When linking, he is trying to find libflint.dll in `$prefix/lib/` instead of `$prefix/bin/`. Secondly, it produces `libarb.so` instead of `libarb.dll`.
In my old builder repository, I worked around this "succesfully", see https://github.com/thofma/ArbBuilder/blob/master/build_tarballs.jl
But there is surely a better way. Any hint appreciated @benlorenz

 New Recipe: Arb v2.18.0

---

C/CUDNN/CUDNN_CUDA10.0/build_tarballs.jl
C/CUDNN/CUDNN_CUDA10.1/build_tarballs.jl
C/CUDNN/CUDNN_CUDA10.2/build_tarballs.jl
C/CUDNN/CUDNN_CUDA9.0/build_tarballs.jl
C/CUDNN/CUDNN_CUDA9.2/build_tarballs.jl
C/CUDNN/common.jl

Couple of comments/questions:
- since we can't download the CUDNN tarballs without authenticating, I downloaded and hashed the manually and `scp`d them to @staticfloat's home folder on `arctic3` :trollface:
- lacking a proper mechanism, I created several packages for each combination of CUDA/CUDNN
- the PackageSpec linking CUDNN to CUDA is too strict, e.g. it would suffice to depend on e.g. CUDA v10.1 instead of v10.1.243, but I don't think we have a way of expressing that?

Add CUDNN v7.6.5.

---

M/mpv/build_tarballs.jl

This probably only works for `x86_64-linux-gnu`, but it's a start in that this uses the [waf](https://waf.io/) build tool.

[mpv] Add builder

---

P/pandoc/build_tarballs.jl

Since we are not building the binaries from source, it is better not to use our
own Zlib and Libiconv libraries and just trust that the system ones will work.
Fixes https://github.com/JuliaBinaryWrappers/pandoc_jll.jl/issues/1

[pandoc] Do not use JLL dependencies

---

L/libcxxwrap_julia/build_tarballs.jl

Update to the latest version. Julia dependency is locked at v1.4.1 for now because of the missing binaries for some platforms on Julia 1.4.2.

[libcxxwrap-julia] Update version to 0.8.0

---

L/libcgal_julia/build_tarballs.jl

Fixing libcxxwrap_julia@v0.7.1 for now as I ran into a few issues with a newer
version of CxxWrap. For now, releasing a new version with new things, namely:
+ Most of the 2D Polygon package
+ 3/5 of the Principal Component Analysis package
* Few tweaks to a few methods, namely some return types in
`triangulation_2` and `voronoi_delaunay`

[libcgal_julia]: Update to v0.10.0, fix libcxxwrap_julia@v0.7.1

---

N/ntl/build_tarballs.jl

<s>Also enable more platforms.</s> I am giving up on trying to enable more platforms, the build system tries to compile and execute a *lot* of code making it rather difficult to cross compile. 
Lots of these tests could be changed to not require execution, just compilation; actually, autoconf would provide a lot of that "for free". I started converting some of the tests but this quickly spiraled out of control; fixing this proprietary build system is just not worth the effort for me (I'd rather use FLINT than NTL anyway).

NTL 11.4.3

---

L/LibSSH2/build_tarballs.jl

This pull request bumps the JLL version of LibSSH2_jll.

JLL bump: LibSSH2_jll

---

N/nghttp2/build_tarballs.jl

This pull request bumps the JLL version of nghttp2_jll.

JLL bump: nghttp2_jll

---

Z/Zlib/build_tarballs.jl

This pull request bumps the JLL version of Zlib_jll.

JLL bump: Zlib_jll

---

X/XML2/build_tarballs.jl

This pull request bumps the JLL version of XML2_jll.

JLL bump: XML2_jll

---

M/MbedTLS/build_tarballs.jl

This pull request bumps the JLL version of MbedTLS_jll.

JLL bump: MbedTLS_jll

---

L/LibCURL/build_tarballs.jl

This pull request bumps the JLL version of LibCURL_jll.

JLL bump: LibCURL_jll

---

O/OpenSSL/build_tarballs.jl

This pull request bumps the JLL version of OpenSSL_jll.

JLL bump: OpenSSL_jll

---

G/Gettext/build_tarballs.jl

This pull request bumps the JLL version of Gettext_jll.

JLL bump: Gettext_jll

---

P/PCRE2/build_tarballs.jl

This pull request bumps the JLL version of PCRE2_jll.

JLL bump: PCRE2_jll

---

E/Expat/build_tarballs.jl

This pull request bumps the JLL version of Expat_jll.

JLL bump: Expat_jll

---

L/Libiconv/build_tarballs.jl

This pull request bumps the JLL version of Libiconv_jll.

JLL bump: Libiconv_jll

---

0_RootFS/gcc_common.jl

When building a package, some of the libtool archives in
`/opt/${target}/${target}/lib*` contain wrong paths.  For example, for
`x86_64-linux-gnu`,
`/opt/x86_64-linux-gnu/x86_64-linux-gnu/lib64/libquadmath.la` has the following
`libdir`:
```sh
libdir='/workspace/destdir/x86_64-linux-gnu/lib/../lib64'
```
This happens because the file is generated and installed in `${prefix}` in
GCCBoostrap, but then in the RootFS this is placed in `/opt/${target}` instead
of `/workspace/destdir`.  Since these files often cause troubles during build
and aren't of any utility, we can just get rid of them.
I _think_ this is what we need for https://github.com/JuliaPackaging/BinaryBuilder.jl/issues/689, but I didn't actually try if this does what I expect :grin:

[0_RootFS] Remove libtool archives from GCCBoostrap tarballs

---

S/Singular/build_tarballs.jl

This is work in progress; right now a [required patch](https://github.com/Singular/Sources/pull/1003) is not yet merged, so I am building against my fork of the repo, not upstream, just to be able to see which platforms work and which don't. 
I hope for the missing patch to be merged tomorrow (assuming it passes all tests etc.; it may be a bit longer if I have to iterate on it)
CC @hannes14 @thofma

New Recipe: Singular 4.1.3

---

.ci/register_package.jl
L/Libiconv/build_tarballs.jl

Also, use download information in latest `Artifacts.toml` when only updating the
wrappers without rebuilding the package.

[skip build] [Libiconv] Add `libcharset` to products

---

X/XML2/build_tarballs.jl

Seems like the easiest way to fix https://github.com/JuliaPackaging/Yggdrasil/issues/1203 is to release the conveniently-existing next patch version of the library

Bump XML2 library version to 2.9.10

---

G/Git/build_tarballs.jl

This pull request bumps the JLL version of Git_jll.

JLL bump: Git_jll

---

M/MbedTLS/build_tarballs.jl

We needed to change the `ranlib` symlink to include `${target}-ranlib` as well, since we now set the `RANLIB` environment variable to point to that filename.

Bump MbedTLS to v2.16.6

---

G/GMP/build_tarballs.jl
G/GMP/bundled/patches/gmp-exception.patch

This PR adds back a new version of the GMP exception patch, in order to match https://github.com/JuliaLang/julia/pull/36343.
Before this PR here is merged, we should make sure that the compat requirement of GMP_jll 6.2, namely `julia >= 1.6`, is preserved; I think if we just merge this, the fix in https://github.com/JuliaRegistries/General/pull/16517 is effectively reverted.
I see two options:
- this PR is merged and then once the JLL is in the registry, immediately a PR similar to https://github.com/JuliaRegistries/General/pull/16517 is merged there
- better of course would be to add a feature to BinaryBuilder that allows specifying a Julia version range / minimal version (see also discussion in https://github.com/JuliaPackaging/BinaryBuilder.jl/issues/511)

GMP: add back exception patch

---

A/AmazonCACerts/build_tarballs.jl

This will allow us to use the AWS certificates directly in Julia, in order to verify the identity of RDS servers over SSL.
For example, using `LibPQ` to connect to an RDS PostgreSQL database, we'll be able to do:
```Julia
using LibPQ, AmazonCACerts_jll
sslrootcert = AmazonCACerts_jll.rds_ca_root_certificate
LibPQ.Connection("port=5432 dbname=test host=ec2-00-000-000-0.compute-1.amazonaws.com sslmode=verify sslrootcert=$sslrootcert")
```
Note: this is inspired by https://github.com/JuliaPackaging/Yggdrasil/tree/master/M/MozillaCACerts

Add recipe for AWS certificates

---

Q/Qt/build_tarballs.jl

This backtracks some of my previous changes, as needed to build jlqml and run on some Linux installations.

[skip build] [Qt] Convert more build dependencies to dependencies

---

J/jlqml/build_tarballs.jl

This adds [jlqml](https://github.com/barche/jlqml), the C++ component of QML.jl
Note that I can't use the Julia_jll as build-dependency here, because that JLL is incompatible with GCC 8 given the fortran abi specification in Julia_jll, and with GCC 7 jlqml doesn't compile because of a constexpr in a header in Qt.

[jlqml] Add builder for jlqml

---

M/MbedTLS/build_tarballs.jl

It is needed for NTLM support in LibGit2.

MbedTLS: enable MD4

---

F/Fontconfig/build_tarballs.jl

Ref: https://github.com/barche/QML.jl/issues/73#issuecomment-653897866 (thanks to @barche for finding the right combination of variables).  Should fix also https://github.com/JuliaGraphics/Cairo.jl/issues/312
CC: @lobingera.

[Fontconfig] Set relevant environment variables in `__init__`

---

L/libcgal_julia/build_tarballs.jl

Embrace a few peculiarities regarding method registration for types
deriving from Integer that might collide with existing methods causing
issues with precompilation (see JuliaInterop/CxxWrap.jl#244).
Consequently, on the up side, it is now possible to leverage the new
method registering mechanism in CxxWrap v0.10.2+.

[libcgal-julia] Update to v0.12, free libcxxwrap-julia

---

L/libcgal_julia/build_tarballs.jl

Bit more significant of an update:
* Revise the way kernels are defined, experiment with conversions to
have different functionality from different kernels to "work
together".  It's a shoddy approach, but this allows the usage of other
types and functionality outside the linear kernel.
+ Consequently, add `Circular_arc_2` and `Circular_arc_3` from the
circular and spherical kernels respectively.
+ Add circular and spherical intersection functions.
* Break global functions sources in terms of the kernel they're from.
* Revise function to collect iterators/circulators into arrays by
obtaining the respective input's `value_type`.
* Rename and hide a few functions based on chosen constructions type.

[libcgal-julia] Update to v0.13

---

T/tree_sitter/build_tarballs.jl
T/tree_sitter/bundled/CMakeLists.txt

Closes #1302. This just builds the runtime library `libtreesitter`. Does not include individual language parsers, I'll add those in a separate PR once this one is done so that parsers can include this in their `dependencies`.

Add tree-sitter runtime lib.

---

T/tree_sitter_bash/build_tarballs.jl
T/tree_sitter_bash/bundled/CMakeLists.txt
T/tree_sitter_c/build_tarballs.jl
T/tree_sitter_c/bundled/CMakeLists.txt
T/tree_sitter_cpp/build_tarballs.jl
T/tree_sitter_cpp/bundled/CMakeLists.txt
T/tree_sitter_go/build_tarballs.jl
T/tree_sitter_go/bundled/CMakeLists.txt
T/tree_sitter_html/build_tarballs.jl
T/tree_sitter_html/bundled/CMakeLists.txt
T/tree_sitter_java/build_tarballs.jl
T/tree_sitter_java/bundled/CMakeLists.txt
T/tree_sitter_javascript/build_tarballs.jl
T/tree_sitter_javascript/bundled/CMakeLists.txt
T/tree_sitter_json/build_tarballs.jl
T/tree_sitter_json/bundled/CMakeLists.txt
T/tree_sitter_julia/build_tarballs.jl
T/tree_sitter_julia/bundled/CMakeLists.txt
T/tree_sitter_php/build_tarballs.jl
T/tree_sitter_php/bundled/CMakeLists.txt
T/tree_sitter_python/build_tarballs.jl
T/tree_sitter_python/bundled/CMakeLists.txt
T/tree_sitter_ruby/build_tarballs.jl
T/tree_sitter_ruby/bundled/CMakeLists.txt
T/tree_sitter_rust/build_tarballs.jl
T/tree_sitter_rust/bundled/CMakeLists.txt
T/tree_sitter_typescript/build_tarballs.jl
T/tree_sitter_typescript/bundled/CMakeLists.txt
azure-pipelines.yml

Builds the following parsers:
- bash
- c (modifies the current build script, only builds the parser, not the runtime since that's provided by `tree_sitter_jll` now)
- cpp
- go
- html
- java
- javascript
- json
- julia ~~(takes quite a while to build, hopefully this won't time out. If it does then will probably need fixes to the underlying `grammar.js` that generates the c code)~~
- php
- python
- ruby
- rust
- typescript

tree-sitter parsers

---

S/SCS/build_tarballs.jl

the patch changing the definition of `scs_int` was dropped since it's already included in scs. It defines
```c
typedef int64_t scs_int;
```
instead of (old script):
```c
typedef __int64 scs_int;
```
but I don't know what is the difference; @ViralBShah @juan-pablo-vielma @migarstka

update SCS to 2.1.2

---

M/mdbtools/build_tarballs.jl
M/mdbtools/bundled/patches/build_shared_libraries_mingw.patch
M/mdbtools/bundled/patches/locale_header.patch

- Add patch for Windows
- Remove LibraryProducts 
- Windows only has static .a files
- Most users are probably interested in the binaries
Reference: https://github.com/cyberemissary/mdbtools/issues/18

Support windows for mdbtools

---

M/MPFR/build_tarballs.jl

These are usually auto-detected, but we want to make them explicit to ensure the builds are consistent.
I'm expecting this may fail on some platforms, as we've noticed regressions in this area (https://github.com/JuliaLang/julia/issues/35796) currently.

update MPFR and make build options explicit

---

L/libcgal_julia/build_tarballs.jl

Bit of an overhaul to `VoronoiDiagram2`. Namely, making it parametric
enables the creation of different kinds of diagrams. Currently, only
Delaunay and Power diagrams can be creating, i.e. `VoronoiDiagram2` can
be parameterized using `DelaunayTriangulation2` and
`RegularTriangulation2`.

[libcgal-julia] Bump to v0.14

---

M/mlpack/build_tarballs.jl

It was observed that the `mlpack_jll` package ships with a bunch of libraries related to mlpack's Go language bindings; these don't have anything to do with Julia.  Observe from inside `.julia/artifacts/<mlpack_jll>/lib/`:
```
$ ls
cmake                                    libmlpack_julia_decision_stump.so
libgo_util.so                            libmlpack_julia_decision_tree.so
libmlpack_go_adaboost.so                 libmlpack_julia_det.so
libmlpack_go_approx_kfn.so               libmlpack_julia_emst.so
libmlpack_go_cf.so                       libmlpack_julia_fastmks.so
libmlpack_go_dbscan.so                   libmlpack_julia_gmm_generate.so
libmlpack_go_decision_stump.so           libmlpack_julia_gmm_probability.so
libmlpack_go_decision_tree.so            libmlpack_julia_gmm_train.so …
```

mlpack: don't build Go bindings

---

L/libcgal_julia/build_tarballs.jl

As is, the script can be used locally as well (given the sources are in
the path specified within the script).  armv7l is not being targetted
due to a series of warnings regarding changes in parameter passing ABI
in GCC 7.1.  I'm guessing a dependency is at fault here. Sadly, it isn't
CGAL since I just updated it.  I suspect it's boost, but it's no big
deal.  Better target one less platform than reduce compatibility scope,
I suppose.
I'm not terribly adept when it comes to these lower level c++ compiler
nuances.  I've seen `-Wno-psabi` silences said messages, and if
silencing them is enough, I could go further and add back armv7l.  But
it seems unwise to do so.  Better safe than sorry.

[libcgal-julia] Modularize + target more platforms

---

L/Libtool/build_tarballs.jl

* Package name: Libtool
* Version: v2.4.6

Wizard recipe: Libtool-v2.4.6

---

L/libsamplerate/build_tarballs.jl

* Package name: libsamplerate
* Version: v0.1.9

Wizard recipe: libsamplerate-v0.1.9

---

G/gperf/build_tarballs.jl

* Package name: gperf
* Version: v3.1.0

Wizard recipe: gperf-v3.1.0

---

F/FastTransforms/build_tarballs.jl

Support all supported platforms.
Drops `expand_gfortran_versions`.

[FastTransforms] v0.3.3

---

S/SDL2_ttf/build_tarballs.jl

This library is apparently dinamically linked to a bunch of libraries even if
they aren't present during the build:
```
% ldd libSDL2_ttf.so
linux-vdso.so.1 (0x00007fff724ee000)
libfreetype.so.6 => /usr/lib/libfreetype.so.6 (0x00007f7d7f567000)
libz.so.1 => /usr/lib/libz.so.1 (0x00007f7d7f54d000)
libbz2.so.1.0 => /usr/lib/libbz2.so.1.0 (0x00007f7d7f53a000)
libSDL2-2.0.so.0 => /usr/lib/libSDL2-2.0.so.0 (0x00007f7d7f3be000)
libm.so.6 => /usr/lib/libm.so.6 (0x00007f7d7f279000)
libiconv.so.2 => /usr/lib/libiconv.so.2 (0x00007f7d7f193000)
libdl.so.2 => /usr/lib/libdl.so.2 (0x00007f7d7f18b000)
libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007f7d7f169000)
librt.so.1 => /usr/lib/librt.so.1 (0x00007f7d7f15e000)
libc.so.6 => /usr/lib/libc.so.6 (0x00007f7d7ef97000)
libpng16.so.16 => …
```

[SDL2_ttf] Do not build with X, add missing runtime dependencies

---

F/FFMPEG/build_tarballs.jl
X/x264/build_tarballs.jl

Attempting to enable nvidia hardware acceleration optional functionality, as per https://trac.ffmpeg.org/wiki/HWAccelIntro
```
NVENC can be used for H.264 and HEVC encoding. FFmpeg supports NVENC through the h264_nvenc and hevc_nvenc encoders. In order to enable it in FFmpeg you need:
- A ​supported GPU
- Supported drivers for your operating system
​- The NVIDIA Codec SDK or compiling FFmpeg with --enable-cuda-llvm
- ffmpeg configured with --enable-nvenc (default if the drivers are detected while configuring)
Note: FFmpeg uses its own slightly modified runtime-loader for NVIDIA's CUDA/NVENC/NVDEC-related libraries. 
If you get an error from configure complaining about missing ffnvcodec, ​this project is what you need. It has a 
working Makefile with an install target: make install …
```

FFMPEG: Enable nvidia hardware acceleration 

---

F/FFMPEG/build_tarballs.jl

This pull request bumps the JLL version of FFMPEG.

JLL bump: FFMPEG

---

B/Bzip2/build_tarballs.jl

This pull request bumps the JLL version of Bzip2_jll.

JLL bump: Bzip2_jll

---

X/x265/build_tarballs.jl

This pull request bumps the JLL version of x265_jll.

JLL bump: x265_jll

---

L/libvorbis/build_tarballs.jl

This pull request bumps the JLL version of libvorbis_jll.

JLL bump: libvorbis_jll

---

X/x264/build_tarballs.jl

This pull request bumps the JLL version of x264_jll.

JLL bump: x264_jll

---

L/LAME/build_tarballs.jl

This pull request bumps the JLL version of LAME_jll.

JLL bump: LAME_jll

---

F/FriBidi/build_tarballs.jl

This pull request bumps the JLL version of FriBidi_jll.

JLL bump: FriBidi_jll

---

O/Opus/build_tarballs.jl

This pull request bumps the JLL version of Opus_jll.

JLL bump: Opus_jll

---

L/libass/build_tarballs.jl

This pull request bumps the JLL version of libass_jll.

JLL bump: libass_jll

---

L/libfdk_aac/build_tarballs.jl

This pull request bumps the JLL version of libfdk_aac_jll.

JLL bump: libfdk_aac_jll

---

F/FreeType2/build_tarballs.jl

This pull request bumps the JLL version of FreeType2_jll.

JLL bump: FreeType2_jll

---

L/LibVPX/build_tarballs.jl

This pull request bumps the JLL version of LibVPX_jll.

JLL bump: LibVPX_jll

---

C/CGAL/build_tarballs.jl

[Bug fix release](https://github.com/CGAL/cgal/releases/tag/releases%2FCGAL-5.0.3)
Preferred minimal GCC version ~~is now~~ already was 7. Misread
a diff. Figures, I should be sleeping.
Includes some touches to the buildscript itself, but very minimal.

[CGAL] Update to v5.0.3

---

P/polymake/build_tarballs.jl
P/polymake/bundled/config/build-Opt-x86_64-apple-darwin14.ninja
P/polymake/bundled/config/config-x86_64-apple-darwin14.ninja
P/polymake/bundled/config/perlx-config-x86_64-apple-darwin14.ninja
P/polymake/bundled/config/targets.ninja
P/polymake/bundled/patches/JSON/Tiny.pm
P/polymake/bundled/patches/polymake-cross-build.patch
P/polymake/bundled/patches/polymake-cross.patch
P/polymake/bundled/patches/relocatable.patch

This is rather involved build recipe for polymake (https://polymake.org) which is needed for Polymake.jl.
The main obstacles are:
- polymake doesn't really support cross-compilation (it needs to run the correct perl during configuration and build)
- polymake needs headers and libraries of all dependencies at _runtime_ to compile C++ snippets for template-instantiations for the perl-C++ interface.
Changes for cross compilation:
- prepared config files for MacOS
- patches (some are needed only during build)
- custom JSON module
- use miniperl during build
Changes for relocatability:
- extra build configuration file `config-reloc.ninja`
using prefix as ninja variable (supplied via environment variable variable)
- remove target + sysroot flags from configuration
- need directory tree similiar …

[polymake] builder for x86_64 linux and mac os

---

M/MozillaCACerts/build_tarballs.jl

Without this, the version number is an unholy union of versioning schemes, things like `2020.0.0-07-22+0`
@aviks can you verify that this fix is good?

Fix MozillaCACerts version number

---

L/libpolymake_julia/build_tarballs.jl

C++ library for `Polymake.jl`, using `libcxxwrap-julia`.
This comes from the `deps/src` folder and was run via `Pkg.build` previously but is in a separate repository now.

[libpolymake_julia] new recipe

---

S/Singular/build_tarballs.jl

... and also force it to be built against FLINT 2.6.2 or newer, as Singular disables some code for FLINT 2.6.1 or older, due to bugs in FLINT it wants to avoid.
Finally, also enabled gfanlib, which requires cddlib as a dependency.

Update Singular to newer version

---

F/finufft/build_tarballs.jl

Note that we can disable linking to fftw_threads or fftw_omp without losing the FFTW threading since the libraries in FFTW_jll already provide the threading capabilities!

Enable OMP in finufft

---

O/OpenLDAPClient/build_tarballs.jl

Doesn't yet work on 
- FreeBSD(:x86_64)
- Windows(:x86_64)
- Windows(:i686)
- Linux(:powerpc64le, libc=:glibc)
Something about needing a Posix Regex. Should I just add a dependency on PCRE? Surprisingly, I cannot see any additional dependencies in https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-openldap/PKGBUILD so I'm a bit confused how that works.

OpenLDAP Client

---

A/AmazonCACerts/build_tarballs.jl

Adding the AmazonRootCA1.pem root certificate (taken from https://www.amazontrust.com/repository/), which can be used e.g. to connect to a serverless RDS database.
Also combining this certificate with the RDS root certificate that was already there, so as to make it easier to use SSL/TLS with either serverless or non-serverless RDS.

Add Amazon root certificate to AmazonCACerts

---

H/hsakmt_roct/build_tarballs.jl
R/ROCT-Thunk-Interface/build_tarballs.jl

Working on getting all the ROC* stuff for AMDGPU.
Questions remain
1. Should I pick GitSource or ArchiveSource?
2. What the heck to be call this library? I've seen it be referred to:
ROCT, ROCT-Thunk-Interface, hsakmt, rocm, roc, hsakmt-roc, hsakmt-rocm, hsakmt-roct, ROCT-Thunk-Interface-roc, ROCT-Thunk-Interface-rocm, HSARuntime

Add hsamkt_roct (ROCT-Thunk-Interface)

---

H/hsakmt_roct/build_tarballs.jl

Only when i tried to work on ROC runtime i realized that the headers were missing in the 3.5.0 build i submitted yesterday. 
Fortunately, the newest release (which also just arrived yesterday) just fixed their flawed cmake files, so, now everything is included as it should be.

Update to ROCT 3.7.0 which fixes missing headers

---

G/GDAL/build_tarballs.jl

Hopefully will help with https://github.com/yeesian/ArchGDAL.jl/issues/138, which has libcurl init issues.

rebuild GDAL

---

P/polymake/build_tarballs.jl
P/polymake/bundled/patches/relocatable.patch

These changes are only needed when building `libpolymake_julia` outside of BinaryBuilder using `polymake_jll` as an artifact, e.g. for our development workflow and tests.

[polymake] minor improvements for relocatability

---

M/Mesa/build_tarballs.jl

This builds opengl32sw.dll as required by #1330. Note that it can't be a `LibraryProduct` since the loading of the DLL is determined by Qt's internal OpenGL version checking. We need the path in the `FileProduct` so it can be added to the `PATH` before launching a Qt OpenGL application, which will then dlopen `opengl32sw.dll` if no compatible OpenGL driver is installed (requires Qt built with `-opengl dynamic`). Unfortunately the relative path `"opengl32sw.dll"` is hard-coded into the Qt source code, so there is no way to supply this path to Qt other than updating `PATH`.
This build takes the easy route, omitting the faster LLVM driver, which I couldn't get to build. This is a minor issue, since even though the LLVM variant is a lot faster than the standard software driver, it is still a …

[Mesa] Add builder for Mesa

---

Q/Qhull/build_tarballs.jl

This also adds the non-rentrant version of the library as a product, as needed by GR.
Edit: I don't know what loading both the reentrant and normal libs at the same time will do to the other clients of this JLL, so some caution is advised.

[Qhull] Add libqhull LibraryProduct

---

S/SDL2/build_tarballs.jl

SDL2 needs to link against some kind of backing sound library to output on Linux; let's use `alsa` for that.
X-ref: https://github.com/JuliaPackaging/Yggdrasil/issues/1432

Add `alsa` as a dependency for `SDL2`

---

X/Xorg_libXi/build_tarballs.jl

This pull request bumps the JLL version of Xorg_libXi_jll.

JLL bump: Xorg_libXi_jll

---

A/ATK/build_tarballs.jl

This pull request bumps the JLL version of ATK_jll.

JLL bump: ATK_jll

---

D/Dbus/build_tarballs.jl

This pull request bumps the JLL version of Dbus_jll.

JLL bump: Dbus_jll

---

X/Xorg_libXinerama/build_tarballs.jl

This pull request bumps the JLL version of Xorg_libXinerama_jll.

JLL bump: Xorg_libXinerama_jll

---

X/Xorg_libXtst/build_tarballs.jl

This pull request bumps the JLL version of Xorg_libXtst_jll.

JLL bump: Xorg_libXtst_jll

---

X/Xorg_libXdamage/build_tarballs.jl

This pull request bumps the JLL version of Xorg_libXdamage_jll.

JLL bump: Xorg_libXdamage_jll

---

I/iso_codes/build_tarballs.jl

This pull request bumps the JLL version of iso_codes_jll.

JLL bump: iso_codes_jll

---

A/at_spi2_atk/build_tarballs.jl

This pull request bumps the JLL version of at_spi2_atk_jll.

JLL bump: at_spi2_atk_jll

---

W/Wayland_protocols/build_tarballs.jl

This pull request bumps the JLL version of Wayland_protocols_jll.

JLL bump: Wayland_protocols_jll

---

X/Xorg_libXrandr/build_tarballs.jl

This pull request bumps the JLL version of Xorg_libXrandr_jll.

JLL bump: Xorg_libXrandr_jll

---

A/at_spi2_core/build_tarballs.jl

This pull request bumps the JLL version of at_spi2_core_jll.

JLL bump: at_spi2_core_jll

---

X/Xorg_libXfixes/build_tarballs.jl

This pull request bumps the JLL version of Xorg_libXfixes_jll.

JLL bump: Xorg_libXfixes_jll

---

X/Xorg_libXcursor/build_tarballs.jl

This pull request bumps the JLL version of Xorg_libXcursor_jll.

JLL bump: Xorg_libXcursor_jll

---

X/Xorg_glproto/build_tarballs.jl

This pull request bumps the JLL version of Xorg_glproto_jll.

JLL bump: Xorg_glproto_jll

---

L/Libepoxy/build_tarballs.jl

This pull request bumps the JLL version of Libepoxy_jll.

JLL bump: Libepoxy_jll

---

L/Libglvnd/build_tarballs.jl

This pull request bumps the JLL version of Libglvnd_jll.

JLL bump: Libglvnd_jll

---

H/HarfBuzz/build_tarballs.jl

This pull request bumps the JLL version of HarfBuzz_jll.

JLL bump: HarfBuzz_jll

---

X/Xorg_libXcomposite/build_tarballs.jl

This pull request bumps the JLL version of Xorg_libXcomposite_jll.

JLL bump: Xorg_libXcomposite_jll

---

G/Graphite2/build_tarballs.jl

This pull request bumps the JLL version of Graphite2_jll.

JLL bump: Graphite2_jll

---

W/Wayland/build_tarballs.jl

This pull request bumps the JLL version of Wayland_jll.

JLL bump: Wayland_jll

---

P/Pango/build_tarballs.jl

This pull request bumps the JLL version of Pango_jll.

JLL bump: Pango_jll

---

X/xkbcommon/build_tarballs.jl

This pull request bumps the JLL version of xkbcommon_jll.

JLL bump: xkbcommon_jll

---

G/GTK3/build_tarballs.jl

This pull request bumps the JLL version of GTK3_jll.

JLL bump: GTK3_jll

---

T/Tk/build_tarballs.jl

This pull request bumps the JLL version of Tk_jll.

JLL bump: Tk_jll

---

X/Xorg_libXft/build_tarballs.jl

This pull request bumps the JLL version of Xorg_libXft_jll.

JLL bump: Xorg_libXft_jll

---

Z/Zstd/build_tarballs.jl

This pull request bumps the JLL version of Zstd_jll.

JLL bump: Zstd_jll

---

L/LZO/build_tarballs.jl

This pull request bumps the JLL version of LZO_jll.

JLL bump: LZO_jll

---

L/libpng/build_tarballs.jl

This pull request bumps the JLL version of libpng_jll.

JLL bump: libpng_jll

---

G/gdk_pixbuf/build_tarballs.jl

This pull request bumps the JLL version of gdk_pixbuf_jll.

JLL bump: gdk_pixbuf_jll

---

X/Xorg_libXext/build_tarballs.jl

This pull request bumps the JLL version of Xorg_libXext_jll.

JLL bump: Xorg_libXext_jll

---

L/Libuuid/build_tarballs.jl

This pull request bumps the JLL version of Libuuid_jll.

JLL bump: Libuuid_jll

---

L/Libtiff/build_tarballs.jl

This pull request bumps the JLL version of Libtiff_jll.

JLL bump: Libtiff_jll

---

J/JpegTurbo/build_tarballs.jl

This pull request bumps the JLL version of JpegTurbo_jll.

JLL bump: JpegTurbo_jll

---

C/Cairo/build_tarballs.jl

This pull request bumps the JLL version of Cairo_jll.

JLL bump: Cairo_jll

---

X/Xorg_libXrender/build_tarballs.jl

This pull request bumps the JLL version of Xorg_libXrender_jll.

JLL bump: Xorg_libXrender_jll

---

P/Pixman/build_tarballs.jl

This pull request bumps the JLL version of Pixman_jll.

JLL bump: Pixman_jll

---

F/Fontconfig/build_tarballs.jl

This pull request bumps the JLL version of Fontconfig_jll.

JLL bump: Fontconfig_jll

---

X/Xorg_libXdmcp/build_tarballs.jl

This pull request bumps the JLL version of Xorg_libXdmcp_jll.

JLL bump: Xorg_libXdmcp_jll

---

X/Xorg_libpthread_stubs/build_tarballs.jl

This pull request bumps the JLL version of Xorg_libpthread_stubs_jll.

JLL bump: Xorg_libpthread_stubs_jll

---

X/Xorg_util_macros/build_tarballs.jl

This pull request bumps the JLL version of Xorg_util_macros_jll.

JLL bump: Xorg_util_macros_jll

---

X/XSLT/build_tarballs.jl

This pull request bumps the JLL version of XSLT_jll.

JLL bump: XSLT_jll

---

X/Xorg_xcb_proto/build_tarballs.jl

This pull request bumps the JLL version of Xorg_xcb_proto_jll.

JLL bump: Xorg_xcb_proto_jll

---

L/Libgcrypt/build_tarballs.jl

This pull request bumps the JLL version of Libgcrypt_jll.

JLL bump: Libgcrypt_jll

---

X/Xorg_libX11/build_tarballs.jl

This pull request bumps the JLL version of Xorg_libX11_jll.

JLL bump: Xorg_libX11_jll

---

X/Xorg_xproto/build_tarballs.jl

This pull request bumps the JLL version of Xorg_xproto_jll.

JLL bump: Xorg_xproto_jll

---

X/Xorg_libxkbfile/build_tarballs.jl

This pull request bumps the JLL version of Xorg_libxkbfile_jll.

JLL bump: Xorg_libxkbfile_jll

---

X/Xorg_xkbcomp/build_tarballs.jl

This pull request bumps the JLL version of Xorg_xkbcomp_jll.

JLL bump: Xorg_xkbcomp_jll

---

X/Xorg_xtrans/build_tarballs.jl

This pull request bumps the JLL version of Xorg_xtrans_jll.

JLL bump: Xorg_xtrans_jll

---

X/Xorg_xkeyboard_config/build_tarballs.jl

This pull request bumps the JLL version of Xorg_xkeyboard_config_jll.

JLL bump: Xorg_xkeyboard_config_jll

---

X/Xorg_xorgproto/build_tarballs.jl

This pull request bumps the JLL version of Xorg_xorgproto_jll.

JLL bump: Xorg_xorgproto_jll

---

X/Xorg_libXau/build_tarballs.jl

This pull request bumps the JLL version of Xorg_libXau_jll.

JLL bump: Xorg_libXau_jll

---

L/Libgpg_error/build_tarballs.jl

This pull request bumps the JLL version of Libgpg_error_jll.

JLL bump: Libgpg_error_jll

---

X/Xorg_libxcb/build_tarballs.jl

This pull request bumps the JLL version of Xorg_libxcb_jll.

JLL bump: Xorg_libxcb_jll

---

M/Mesa/build_tarballs.jl

This pull request bumps the JLL version of Mesa_jll.

JLL bump: Mesa_jll

---

A/adwaita_icon_theme/build_tarballs.jl

This pull request bumps the JLL version of adwaita_icon_theme_jll.

JLL bump: adwaita_icon_theme_jll

---

T/Tcl/build_tarballs.jl

This pull request bumps the JLL version of Tcl_jll.

JLL bump: Tcl_jll

---

P/PCRE/build_tarballs.jl

This pull request bumps the JLL version of PCRE_jll.

JLL bump: PCRE_jll

---

X/Xorg_kbproto/build_tarballs.jl

This pull request bumps the JLL version of Xorg_kbproto_jll.

JLL bump: Xorg_kbproto_jll

---

L/Libmount/build_tarballs.jl

This pull request bumps the JLL version of Libmount_jll.

JLL bump: Libmount_jll

---

G/Glib/build_tarballs.jl

This pull request bumps the JLL version of Glib_jll.

JLL bump: Glib_jll

---

L/Libffi/build_tarballs.jl

This pull request bumps the JLL version of Libffi_jll.

JLL bump: Libffi_jll

---

H/hicolor_icon_theme/build_tarballs.jl

This pull request bumps the JLL version of hicolor_icon_theme_jll.

JLL bump: hicolor_icon_theme_jll

---

S/Singular/build_tarballs.jl

Also adjust the flint dependency, so that we don't have to manipulate the compat entries in the registry.

[Singular] new version

---

recursively_regenerate_jlls.jl

This allows us to easily generate a bunch of JLLs locally, to experiment
with alternate JLL generation techniques

Add local-regeneration to `recursively_regenerate_jlls.jl`

---

M/MiniFB/build_tarballs.jl

MacOS does not work since our builders do not include MetalKit. 
musl and freebsd have problems finding the X11 headers, which I am not bothered to investigate.

Add MiniFB build

---

L/libpolymake_julia/build_tarballs.jl

I forget to bump the version number within the library and that caused the checks in Polymake.jl to refuse the new version, sorry about that.

[libpolymake-julia] further bump version to 0.1.2

---

C/CoolProp/build_tarballs.jl

This is for https://github.com/CoolProp/CoolProp.jl, which is currently broken because the binaries went away at the location referenced in the build.jl script.

[CoolProp] Add builder for CoolProp

---

D/Deldir/build_tarballs.jl

I'm doing this manually because the wizard failed:
```
[ Info: Checking temporary Yggdrasil out to /tmp/jl_DC91wV
[ Info: Generating D/Deldir/build_tarballs.jl
[ Info: Committing and pushing to robertdj/Yggdrasil#wizard/Deldir-v0.1.15_e46bfc15...
UndefVarError: gh_username not defined
```
The token was obtained successfully.

Builder for Deldir 0.1.15

---

0_RootFS/gcc_common.jl

Upgrades libtapi to the latest version in
https://github.com/tpoechtrager/apple-libtapi, which in particular
picks up support for the v4 format for TAPI, which is used in
the macOS 11 SDK.

GCCBootstrap: Bump libtapi version

---

S/SCS_GPU/build_tarballs.jl

Builds only `libscsgpuindir` against `CUDA_full_jll`;
this simplified the build script (only the GPU part is built) and I bit the bullet and tested the build locally ;)
this moves #1289 into a separate package following advice of @giordano;
I limited the platforms only to the supported by CUDA; here is the output of `ldd` on BB compiled library:
```
$ ldd ./products/lib/libscsgpuindir.so
linux-vdso.so.1 (0x00007ffe2eeb9000)
libm.so.6 => /usr/lib/libm.so.6 (0x00007f985dc8f000)
librt.so.1 => /usr/lib/librt.so.1 (0x00007f985dc84000)
libopenblas64_.so => not found
libcudart.so.11.0 => not found
libcublas.so.11 => not found
libcusparse.so.11 => not found
libc.so.6 => /usr/lib/libc.so.6 (0x00007f985dabb000)
/usr/lib64/ld-linux-x86-64.so.2 (0x00007f985e03a000)
libpthread.so.0 => …
```

SCS_GPU: build libscsgpuindir against CUDA_full_jll

---

J/Julia/Julia@1.4/build_tarballs.jl
J/Julia/Julia@1.5/build_tarballs.jl

This is an alternative to PR #1439 by @barche which adds Julia 1.5.0 but also keep Julia 1.4 around. I hope that in the future we can then add Julia 1.6, etc. (and perhaps also Julia 1.3).

Add Julia_jll 1.5, but keep version for 1.4

---

G/GMP/build_tarballs.jl
G/GMP/bundled/patches/gmp-apple-arm64.patch

This is the same patch as https://github.com/JuliaLang/julia/commit/cdddcb7792d2e4d473ac22160610d338a2b9f28c, but this time for the BB'ed version. 
[skip ci]

GMP: Carry Darwin ARM64 patch

---

A/AzStorage/build_tarballs.jl

Hello,
This is in support of the AzStorage.jl package (https://github.com/ChevronETC/AzStorage.jl).  AzStorage.jl uses C code for IO to Azure cloud storage.  The motivation for the C code is to use a combination of OpenMP and libcurl to make the IO efficient.
In the future, we would like to switch from OpenMP+libcurl to PARTR+HTTP.jl, but for the time being we have not being able to get the same performance with the pure Julia solution.
Thanks!

build recipe for AzStorage

---

M/mlpack/build_tarballs.jl

It's the rules: it can never go right the first time. I was tricked by #1649's first-time green build into believing I had everything right, but this is clearly too good to be true. Upon trying to update the mlpack.jl package that depends on mlpack_jll, I discovered the gotcha, which is just that I forgot a LibraryProduct. Oops... :)
(round two: rebase on master, not the #1649 branch)

Add libmlpack_julia_kde LibraryProduct.

---

I/ICU/build_tarballs.jl

This seems to fix the issue with ICU reported in #1668.  See also https://github.com/JuliaPackaging/Yggdrasil/issues/1650#issuecomment-691369425 for more information about the error.
With this PR, locally during audit I get
```
[ Info: Checking lib/libicutu.67.1.dylib with RPath list String[]
[ Info: Linked library libicui18n.67.dylib has been auto-mapped to @rpath/libicui18n.67.dylib
[ Info: Linked library libicudata.67.dylib has been auto-mapped to @rpath/libicudata.67.dylib
[ Info: Linked library libicuuc.67.dylib has been auto-mapped to @rpath/libicuuc.67.dylib
[ Info: Ignored system libraries /usr/lib/libSystem.B.dylib, /usr/lib/libc++.1.dylib
[ Info: Modifying dylib id from "libicutu.67.dylib" to "@rpath/libicutu.67.dylib"
```
and then
```
sandbox:${WORKSPACE} # otool -L …
```

[ICU] Pass `-headerpad_max_install_names` to macOS linker

---

C/CvxCompress/build_tarballs.jl
C/CvxCompress/bundled/patches/cross-compile-cvxcompress-gencode.patch

Hello,
This is in support of the CxvCompress.jl package (https://github.com/ChevronETC/CvxCompress.jl). CxvCompress.jl uses C code for an efficient compression algorithm used in seismic analysis.
Thanks!

add build recipe for CvxCompress

---

recursively_regenerate_jlls.jl

I'm always nervous that I will accidentally send out hundreds of PRs. Seems reasonable that that is opt-in maybe.

don't make JLL bump PRs by default

---

M/mpv/build_tarballs.jl

The Mac builder shards have changed since this package was last build. Force a rebuild before we investigate #1520

[mpv] force a rebuild

---

T/tblis/build_tarballs.jl
T/tblis/bundled/patches/aligned_allocator.hpp.mingw.patch

Previous script seems not compiling on containers provided by current master.
Container build does not allow specifying -march options.
This update:
- Patches scripts before compiling to remove incompatible options;
- Adds support for macOS and FreeBSD;
Limitations:

Update recipe: tblis-v1.2.0 more Tier-1 platforms

---

0_RootFS/common.jl
0_RootFS/gcc_common.jl

* Upgrade `GCCBootstrap` to Julia 1.6+ syntax
* Change GCC bootstrapping process to use armv6l as the default
microarchitecture.  This builds an armv6l-compatible version of the
initial compiler support units, and allows us to build armv6 or armv7
targeting binaries.  It may cause a slight slowdown on armv7l, (due to
some of those compiler support libraries using only older, slower, armv6
instructions).  If it turns out to be too much of a problem, we may need
to build independent copies of the arm shards.

[GCCBootstrap]: Change ARM shard to support armv6l and armv7l

---

L/Libglvnd/build_tarballs.jl

Alpine's musl libc won't load `libGLdispatch.so` without this flag.

Libglvnd: Disable initial-exec TLS model for musl

---

W/WaveFD/build_tarballs.jl

This is in support of the WaveFD.jl package: https://github.com/ChevronETC/WaveFD.jl.  WaveFD is a collection of finite difference solutions to variations on the wave equation (PDE).  The finite difference codes in WaveFD are implemented in C++ (for performance reasons) and wrapped in a Julia API.

buid_tarballs.jl for WaveFD

---

S/Singular/build_tarballs.jl

Force GMP_jll to build with version 6.1.2, to ensure the resulting
binaries work in both Julia <= 1.5 and >= 1.6
CC @staticfloat @thofma 
If this works, we can next update PR #1695 similarly (CC @benlorenz).
Finally, I'd be tempted to apply this dependency patch to "all" JLLs using GMP_jll (with `[skip ci]`) just to make sure we don't run into this issue again by accident, down the line. Or is that a bad idea for some reason?

Update Singular, fix GMP dependency

---

M/MagicVLSI/build_tarballs.jl

This is the Magic VLSI tool (http://www.opencircuitdesign.com/magic/).
It is mostly written in tcl/tk with some native extensions.
The source is 8.3.61 from upstream, plus three patches to make
it more redistributable. I've submitted those patches upstream
here: https://github.com/RTimothyEdwards/magic/pull/41
Windows and MacOS builds are currently disabled. Enabling MacOS
looks quite doable, but requires some further build system tweaks
that I don't have time for at the moment. Windows looks harder
and does not appear to be supported upstream (other than using Cygwin).
Maybe for somebody who wants a challenge someday.

New Recipe: MagicVLSI v8.3.61

---

S/Singular/build_tarballs.jl

Similar to the issues with GMP_jll (see PR #1718), this prevents issues on macOS when trying to load Singular_jll in Julia <= 1.4 which ships with MPFR 4.0.2, and binaries linked against MPFR 4.1.0 won't load there on macOS.
This will likely be affected by the same bug https://github.com/JuliaPackaging/BinaryBuilderBase.jl/issues/45 but I hope that won't matter?
This is also something that should be applied to other patches, similar to PR #1739.

Singular: build against MPFR 4.0.2

---

E/Enzyme/Enzyme@9/build_tarballs.jl
E/Enzyme/common.jl

cc: @wsmoses
@giordano @staticfloat Enzyme is a compiler plugin for LLVM, so it has to be build against the right LLVM version, but it does support LLVM 7-9 (and higher). So the question is which version number to choose. Right now I used `0.0.1` instead of `9.0.1`, since we need Julia 1.4+ anyway for the project, but this yet again opens the question of how do I build something for LLVM 9 and LLVM 10 as variants :P

add build recipe for Enzyme

---

A/Antic/build_tarballs.jl
A/Arb/build_tarballs.jl
B/bliss/build_tarballs.jl
C/CGAL/build_tarballs.jl
C/cddlib/build_tarballs.jl
F/FLINT/build_tarballs.jl
F/FastTransforms/build_tarballs.jl
G/GLPK/build_tarballs.jl
G/GnuTLS/build_tarballs.jl
I/ISL/build_tarballs.jl
L/LEAN_Community/build_tarballs.jl
L/lib4ti2/build_tarballs.jl
L/lrslib/build_tarballs.jl
M/MPC/build_tarballs.jl
M/MPFI/build_tarballs.jl
M/MPFR/build_tarballs.jl
N/Nettle/build_tarballs.jl
N/nauty/build_tarballs.jl
N/normaliz/build_tarballs.jl
N/ntl/build_tarballs.jl
P/PPL/build_tarballs.jl
P/polymake/build_tarballs.jl
S/SymEngine/build_tarballs.jl

... to ensure that future updates for these will keep working with Julia <= 1.5.
[skip ci]
It seems best to do this now in one batch, instead of having updates which forget to changes this trickle in over time.

Tweak a bunch of packages to build against GMP 6.1.2 resp. MPFR 4.0.2

---

A/Arb/build_tarballs.jl

This was using a bad Dependency on FLINT_jll (my fault) which later was
fixed in the package registry. Let's fix it here, too, to ensure it is
not forgotten during the next real update. The existing binaries can
be reused, but let's regenerate the JLL to get a correct Project.toml.
[skip build]

Fix build_tarballs.jl for Arb_jll

---

P/polymake/build_tarballs.jl
P/polymake/bundled/config/config-x86_64-apple-darwin14.ninja
P/polymake/bundled/patches/sigint.patch

The sigint patch make sure that the Ctrl+C handler of julia is kept, otherwise julia will terminate immediately when ctrl+c is pressed after polymake_jll was loaded (and initialized).
Switched to archive source.

[polymake] bump to 4.2 and add patch for sigint

---

L/LibYAML/build_tarballs.jl

This PR adds a build script for LibYAML. This is the first time I work with Yggdrasil and BinaryBuilder, so make sure to check it carefully :slightly_smiling_face: 
BTW actually I would like to build a library that requires LibYAML, and hence I tried to package LibYAML first. I managed to install the LibYAML_jll package locally, but I didn't know how to use this local JLL package in local builds of other packages - I always got a an error message since it couldn't be resolved (even though it is added to my global environment). Is it possible to use local JLL packages as dependencies in build_tarballs.jl files?

Add LibYAML

---

H/HelloWorldFortran/build_tarballs.jl
azure-pipelines.yml

The undocumented environment variable `BUILD_SOURCEVERSIONMESSAGE` in Azure
Pipelines doesn't return anymore the full commit message but only the summary in
the first line.  Let's just stop hoping AZP will make things easier for us and
use git to get the full commit message.

[AZP] Fix detection of `[skip build]` and update wrappers for HWF

---

N/nv_codec_headers/build_tarballs.jl

This pull request bumps the JLL version of nv_codec_headers_jll.

JLL bump: nv_codec_headers_jll

---

O/Ogg/build_tarballs.jl

This pull request bumps the JLL version of Ogg_jll.

JLL bump: Ogg_jll

---

F/FFMPEG/FFMPEG/build_tarballs.jl

This pull request bumps the JLL version of FFMPEG/FFMPEG.

JLL bump: FFMPEG/FFMPEG

---

L/libpolymake_julia/build_tarballs.jl

- update for polymake_jll 4.2
- dependency to make sure libpolymake with the correct soname is available
- update syntax

[libpolymake_julia] bump to 0.2 and restrict polymake_jll version

---

L/libpolymake_julia/build_tarballs.jl

they are already indirect dependencies from `polymake_jll` but that
doesn't restrict the versions at build-time, so we need them explicit to make it work with
julia < 1.6 on macos:
```
ERROR: LoadError: InitError: could not load library "/Users/runner/.julia/artifacts/953c9e0347aff95c09f1c94ce54315063283f315/lib/libpolymake_julia.dylib"
dlopen(/Users/runner/.julia/artifacts/953c9e0347aff95c09f1c94ce54315063283f315/lib/libpolymake_julia.dylib, 1): Library not loaded: @rpath/libmpfr.6.dylib
Referenced from: /Users/runner/.julia/artifacts/953c9e0347aff95c09f1c94ce54315063283f315/lib/libpolymake_julia.dylib
Reason: Incompatible library version: libpolymake_julia.dylib requires version 8.0.0 or later, but libmpfr.dylib provides version 7.0.0
```

[libpolymake_julia] make gmp and mpfr dependencies explicit to fix versions

---

L/libpolymake_julia/build_tarballs.jl

@giordano The registration issue seems to come from some change in Pkg.jl that was in included in the latest nightly.
From two days ago:
```
$ /tmp/julia/julia-1e7fb1d844/bin/julia -e 'using InteractiveUtils; versioninfo(); using Pkg; @show PackageSpec(name="Julia_jll", version="v1.4.1");'
Julia Version 1.6.0-DEV.1186
Commit 1e7fb1d844 (2020-10-12 07:50 UTC)
...
PackageSpec(name = "Julia_jll", version = "v1.4.1") = PackageSpec(
name = Julia_jll
version = VersionSpec("1.4.1")
)
```
Fresh download:
```
$ /tmp/julia/julia-a1da84c3b0/bin/julia -e 'using InteractiveUtils; versioninfo(); using Pkg; @show PackageSpec(name="Julia_jll", version="v1.4.1");'
Julia Version 1.6.0-DEV.1210
Commit a1da84c3b0 (2020-10-13 13:46 UTC)
...
ERROR: ArgumentError: invalid base 10 digit 'v' in "v1"
Stacktrace: …
```

[libpolymake_julia] adjust Julia_jll dependency to fix registration issue in #1786

---

X/xkbcommon/build_tarballs.jl

This pull request bumps the JLL version of xkbcommon_jll.

Bump JLL wrapper: xkbcommon_jll

---

L/Librsvg/build_tarballs.jl

This pull request bumps the JLL version of Librsvg_jll.

JLL bump: Librsvg_jll

---

I/ICU/build_tarballs.jl

This pull request bumps the JLL version of ICU_jll.

JLL bump: ICU_jll

---

G/Gnome_themes_extra/build_tarballs.jl

This pull request bumps the JLL version of Gnome_themes_extra.

JLL bump: Gnome_themes_extra

---

L/Libcroco/build_tarballs.jl

This pull request bumps the JLL version of Libcroco_jll.

JLL bump: Libcroco_jll

---

L/libjulia/common.jl
L/libjulia/libjulia@1.4/build_tarballs.jl

This fix is required so that libjulia_jll 1.4.2 can be added in Julia 1.6.
See <https://github.com/JuliaRegistries/General/pull/23018>.
It relies on that fact that we set `julia_version` for all platforms, which
should ensure that GMP_jll and MPFR_jll are resolved to the correct versions.

Fix libjulia 1.4.2 dependency issue on Julia 1.6

---

X/Xorg_libXScrnSaver/build_tarballs.jl

This pull request bumps the JLL version of Xorg_libXScrnSaver_jll.

JLL bump: Xorg_libXScrnSaver_jll

---

S/SDL2/build_tarballs.jl

This pull request bumps the JLL version of SDL2.

JLL bump: SDL2

---

B/bliss/build_tarballs.jl

tldr: please rebuild `bliss_jll` to fix the rpath for `libc++.1.dylib` in `libbliss.dylib`.
Details:
I am getting some weird errors with a missing `libc++.1.dylib` when using `libbliss.dylib` via a binary in the `libpolymake_julia_jll` artifact:
```
dlopen(/Users/runner/.julia/artifacts/f36589b6aa598ba4c9ec9a6b51c4d552660e7f97/lib/polymake/lib/graph.dylib, 9): Library not loaded: @rpath/libc++.1.dylib
Referenced from: /Users/runner/.julia/artifacts/545975cc9147363cb3dfde0e97ac9717894f8d19/lib/libbliss.dylib
Reason: image not found
```
The code looks like this, where `polymake_run_script` is from the `libpolymake_julia_jll` artifact:
```
polymake_run_script() do runner
run(`$runner $json_script $json_folder`)
end
```
(Full log is here: …

[bliss] rebuild to fix libc++ rpath in dylib (on macos)

---

F/FFTW/build_tarballs.jl

This pull request bumps the JLL version of FFTW.

JLL bump: FFTW

---

G/GMP/build_tarballs.jl
G/GMP/bundled/patches/configure.patch
G/GMP/bundled/patches/gmp-exception.patch

This is temporary and shall be reverted once the update is complete.
Uses expand_cxxstring_abis so a full rebuild is needed.

Switch GMP back to 6.1.2 to rebuild its JLL wrapper

---

M/MPFR/build_tarballs.jl

This is temporary and shall be reverted once the update is complete.
We don't revert to the precise version of the code in the original
4.0.2, to benefit from some improvements made to 4.1.0 over time.

Switch MPFR back to 4.0.2 to rebuild its JLL wrapper

---

G/GDAL/build_tarballs.jl

Works on Linux, let's see what all other platforms do.
Should support many webbased xml formats in GDAL. See also https://github.com/JuliaGeo/GDAL.jl/issues/65 and ping @visr.

[GDAL] Add expat support

---

R/Readline/build_tarballs.jl

This pull request bumps the JLL version of Readline_jll.

JLL bump: Readline_jll

---

C/cddlib/build_tarballs.jl

This pull request bumps the JLL version of cddlib_jll.

JLL bump: cddlib_jll

---

N/nauty/build_tarballs.jl

This pull request bumps the JLL version of nauty_jll.

JLL bump: nauty_jll

---

P/Perl/build_tarballs.jl

This pull request bumps the JLL version of Perl_jll.

JLL bump: Perl_jll

---

N/Ncurses/build_tarballs.jl

This pull request bumps the JLL version of Ncurses_jll.

JLL bump: Ncurses_jll

---

L/lrslib/build_tarballs.jl

This pull request bumps the JLL version of lrslib_jll.

JLL bump: lrslib_jll

---

F/FLINT/build_tarballs.jl

This pull request bumps the JLL version of FLINT_jll.

JLL bump: FLINT_jll

---

L/LCIO/build_tarballs.jl

This is an experiment to see which platforms really pass/fail right now and how, and whether it really is necessary to only build with the C++11 string ABI (which is independent of whether or not the C++ code uses C++03 or something newer).
CC @jstrube whose JLL this really is (I don't mean to intrude but this came up while working on PR #1921)

Experiment: Add more platforms to LCIO

---

N/normaliz/build_tarballs.jl

This pull request bumps the JLL version of normaliz_jll.

JLL bump: normaliz_jll

---

P/PPL/build_tarballs.jl

This pull request bumps the JLL version of PPL_jll.

JLL bump: PPL_jll

---

G/GDAL/build_tarballs.jl

Instead of upgrading, let's broaden some drivers. Had to enable -lstdc++, not sure if it's needed on other platforms than linux.

[GDAL] Add zstd and webp drivers

---

A/alsa/build_tarballs.jl

This pull request bumps the JLL version of alsa_jll.

JLL bump: alsa_jll

---

0_RootFS/GCCBootstrap@4/bundled/patches/musl_disable_tls.patch
0_RootFS/GCCBootstrap@5/bundled/patches/musl_disable_tls.patch
0_RootFS/GCCBootstrap@6/bundled/patches/musl_disable_tls.patch
0_RootFS/GCCBootstrap@7/bundled/patches/musl_disable_tls.patch
0_RootFS/GCCBootstrap@8/bundled/patches/musl_disable_tls.patch
0_RootFS/GCCBootstrap@9/bundled/patches/musl_disable_tls.patch
0_RootFS/gcc_common.jl

Similar idea to #1716. Should allow `libgomp.so` to load on musl without any errors.

Disable non-POSIX TLS usage in libgomp

---

N/normaliz/build_tarballs.jl

Since MPFR is only an indirect dependency the wrong version was pulled in during the latest rebuild.
So rebuild it to make those poor macos users happy again:
```
ERROR: LoadError: LoadError: InitError: could not load library /Users/runner/.julia/artifacts/34750e7597595ecce93a0a04cd79cbb7514e475f/lib/libnormaliz.3.dylib
dlopen(/Users/runner/.julia/artifacts/34750e7597595ecce93a0a04cd79cbb7514e475f/lib/libnormaliz.3.dylib, 1): Library not loaded: @rpath/libmpfr.6.dylib
Referenced from: /Users/runner/.julia/artifacts/34750e7597595ecce93a0a04cd79cbb7514e475f/lib/libnormaliz.3.dylib
Reason: Incompatible library version: libnormaliz.3.dylib requires version 8.0.0 or later, but libmpfr.dylib provides version 7.0.0
```

[normaliz] rebuild to fix MPFR version, because FLINT needs MPFR

---

B/boost/build_tarballs.jl

This pull request bumps the JLL version of boost_jll.

JLL bump: boost_jll

---

N/Ninja/build_tarballs.jl

also makes sure we have new jll wrappers without any LIBPATH issues

[Ninja] bump to 1.10.1

---

G/GMP@6.1.2/build_tarballs.jl

[skip build]
This should deal with https://github.com/JuliaRegistries/General/pull/23421. The version specifier is not just "1.0-1.5" because I am trying to have this work in older Julia versions -- but perhaps that's misguided (I admit I don't fully understand how all the underlying tooling works), in that case it could of course be simplified 🤷 
Using "skip build" ought to be safe since the most recent GMP_jll is a 6.1.2 one, so the correct binaries will be reused.

GMP 6.1.2: correct Julia compat

---

L/lib4ti2/build_tarballs.jl

This uses expand_cxxstring_abis and so it must be rebuilt
to deal with the fact that macOS builds now only have a single version
regardless of the cxxstrings ABI choice.

Rebuild lib4ti2_jll

---

L/libjulia/common.jl
L/libjulia/libjulia@1.3/build_tarballs.jl

It is not clear to me right now why libjulia is not built for FreeBSD, so this PR is trying to figure it out, and then either solve it, or document it for future generations.

Improve libjulia, rebuild libjulia 1.3.1 with the improvements

---

P/Poppler/build_tarballs.jl

Changing a couple of lines and updating the order of the dependencies. I leave everything else as-is in case someone is interested in enabling the rest of the disabled features.

[Poppler] Enable the Glib wrapper

---

Q/Qhull/build_tarballs.jl

The non-reentrant library :libqhull is not provided any more.

Qhull: Update to 2020.2

---

P/Poppler/build_tarballs.jl

This pull request should resolve the "wonderfuk" with a recursive `bin` directory in MinGW tarballs.

[Poppler] Remove the line with the ${bindir} link

---

azure-pipelines.yml

This allows us to get both the HTTP status code (which we want to be
`200`) and write out the full set of HEAD request/repsonse values

Better `curl` invocation

---

H/HelFEM/build_tarballs.jl

So, basically switch from `libgfortran_version=v"4"` to `preferred_gcc_version=v"7"`, to make sure all the dependencies are happy. First, let's see if it builds on all platforms.

Try fixing HelFEM_jll constraints

---

G/GAP/build_tarballs.jl
G/GAP/bundled/patches/Makefile.patch
G/GAP/bundled/patches/configure.patch

TODO:
UPDATE: this is now ready for merging

New recipe: GAP

---

O/Openresty/build_tarballs.jl

Removed `FileProduct("site", :site_dir)` folder from list of products as it seems to cause problems during build. It just contains a few empty folders so not important to have in the JLL.
ref: #2006, #2007

fix Openresty builds

---

S/snappy/build_tarballs.jl

Uses `expand_cxxstring_abis` so we cannot reuse the macOS binaries

Regenerate snappy JLL wrapper

---

G/glmnet/build_tarballs.jl

Ref https://github.com/JuliaStats/GLMNet.jl/issues/46
The current glmnet build uses an [older version of glmnet](https://github.com/JuliaStats/GLMNet.jl/blob/8d8d22d573f7f608515fcf5f5192cf28cced8f1b/deps/glmnet5.f90) from 2014 that was copied into the GLMNet repo a long time ago, and this changes to build from the current [R package source](https://github.com/cran/glmnet) instead.
There are a couple of issues where I need some help:
- the original glmnet build was given version 5, because the file was named `glmnet5.f90` with no version info in the the file other than a datestamp. I figured it would make sense to sync the version to the tagged version of the R package, but the problem is that the most recent tag is currently v4.0.2, so there is the chance for a v5 conflict in future. I'd …

Update glmnet to use latest source from R package

---

A/AlgRemez/build_tarballs.jl

Version info of GMP_jll is added.
Fix #2027

[AlgRemez] Build against GMP v6.1.2

---

L/LibCURL/build_tarballs.jl

We have had struggles in integration with special certificates for restrictive installs; let's move towards using the native TLS libraries on Mac and Windows, but still using MbedTLS on Linux where we don't want to depend on OpenSSL for licensing reasons.

[LibCURL] Bump to `v7.73.0`, use native TLS libraries on MacOS and Windows

---

L/libunicorn/build_tarballs.jl
U/Unicorn/build_tarballs.jl

I've been having some trouble with the BinaryBuilder wizard, which keeps failing with a 404 error when it tries to communicate with the github API, so I wrote the build_tarballs.jl script to a local file, and put together this PR manually. 
This is a wrapper for the Unicorn emulation library.

BinaryBuilder jlls for unicorn emulator library

---

O/OpenBLAS/OpenBLAS@0.3.10/build_tarballs.jl
O/OpenLibm/build_tarballs.jl
P/p7zip/build_tarballs.jl

This PR contains a bundle (hopefully not too large) of dependencies that need to be rebuilt/restricted to v1.6+ so that we can expand into experimental platforms.

Rebuild many Julia deps for v1.6+

---

M/MbedTLS/build_tarballs.jl
M/MbedTLS/bundled/patches/fix_incorrect_EOF_check.patch

https://github.com/ARMmbed/mbedtls/releases/tag/v2.24.0

Bump mbedtls  to v2.24.0

---

M/MPFR/build_tarballs.jl

This is actually MPFR v4.1.0, but we're calling it v4.1.1 so that we
cans add compat entries on Julia and GMP that weren't there for v4.1.0

[MPFR] Rebuild for Julia 1.6+ as v4.1.1, requiring GMP 6.2.0+

---

A/AzStorage/build_tarballs.jl

The new version of AzStorage removes the list of retryable error codes to the Julia package.  This means that we can now update these error codes as needed without requiring any changes to the jll.

new version of AzStorage

---

A/AzStorage/build_tarballs.jl

@giordano per our [conversation](https://github.com/JuliaPackaging/Yggdrasil/pull/2040#issuecomment-721629333), here is the change to make the mbedtls version explicit.  I was not sure if I need to change the AzStorage "version" or not.  For now, I left it the same as before (v"0.2.0").  But, let me know if that needs changing, and I will update the PR. 
This is an attempt to fix the following problem: https://github.com/ChevronETC/AzStorage.jl/runs/1350739865

AzStorage: fix mbedtls to 2.16.0 for compatability with more Julia versions

---

L/LibUnwind/build_tarballs.jl

This has a build dependency on `XZ_jll`, so we'll see if this goes through with the new `XZ_jll` we just built that contains the experimental platforms.

[LibUnwind] Bump to v1.3.2 and build on experimental platforms for v1.6+

---

P/pprof/build_tarballs.jl

Bump from 20191205061153 => 20201109224723
My personal interest is to pull in https://github.com/google/pprof/pull/564, which adds support for displaying names with `"` in them, which julia functions sometimes have (e.g. `var"#foo#23"`)
Includes:
- https://github.com/google/pprof/pull/564
- https://github.com/google/pprof/pull/575
- https://github.com/google/pprof/pull/574
- https://github.com/google/pprof/pull/571
- https://github.com/google/pprof/pull/572
- https://github.com/google/pprof/pull/570
- https://github.com/google/pprof/pull/562
- https://github.com/google/pprof/pull/561
- https://github.com/google/pprof/pull/565
- https://github.com/google/pprof/pull/560
- https://github.com/google/pprof/pull/563
- https://github.com/google/pprof/pull/557
- …

Update pprof to latest revision

---

L/LibCURL/build_tarballs.jl

This fixes a `___isOSVersionAtLeast` symbol reference error.

[LibCURL] Explicitly request macOS 10.11+

---

M/MbedTLS/build_tarballs.jl

I don't know why, but the MbedTLS build system seems to be lacking the executable permission on its installed DLLs.

[MbedTLS]: Fix lack of `+x` permissions on DLLs

---

P/polymake/build_tarballs.jl
P/polymake/bundled/patches/generate_deps_tree.jl

For compatibility with julia 1.6+ which doesn't allow `create_artifact` from the `init_block`.
Putting it here allows us to use it in Polymake.jl but also in the CI for libpolymake_julia.
We can (ab)use the patch level bump for this as polymake only uses major.minor.
After this is merged I will need to bump libpolymake_julia_jll (which luckily has polymake_jll=4.2.0 currently) and Polymake.jl to adjust for this change (and to make sure that the new artifact is not loaded where the `init_block` is still needed).

[polymake] move dependency tree artifact generator from init_block to jl script

---

L/libcxxwrap_julia/build_tarballs.jl

Also drop the restriction to the cxx11 ABI and add more platforms.
Motivation: while this is not the perfect next step for libcxxwrap_julia, I think it makes sense to do this now: switching to libjulia and adding more platforms will allow other packages using libcxxwrap_julia to do the same. Once (if?) we get "full" support for "julia_version" as part of the platform, adjusting `libcxxwrap_julia` and other JLLs depending on it to benefit from those shouldn't be hard; but it is unclear when this will be available; so why not implement those benefits we can already get now?
As a side effect, this will produce a fresh JLLWrapper based JLL :-)
However, this PR shouldn't be merged without @barche approving.
UPDATE: ... and of course it should pass the CI tests before all else ;-)
Close #1647

libcxxwrap_julia: switch to libjulia

---

H/HDF5/build_tarballs.jl

Updates the library to v1.12.   HDF5 passes on Windows and Linux locally using this.
The bad news is that PyPy stopped distributing i686 linux tarballs. I also had to drop armv7 since that was user contributed and thus not scalable in terms up being able to upgrade (the user reported they no longer had access to a raspberry pi).

Update HDF5 to v1.12

---

L/libpolymake_julia/build_tarballs.jl

The julia code to generate the dependency tree is now available as a fileproduct and will be run from Polymake.jl.

[libpolymake_julia] version bump for removed init_block in polymake_jll

---

S/SPIRV_LLVM_Translator/SPIRV_LLVM_Translator@11/build_tarballs.jl

~Only merge when https://github.com/JuliaPackaging/Yggdrasil/commit/e85764c7f595eaf809269ff41b717131f98b7e2c#commitcomment-44214400 is resolved.~
Probably needs to wait on https://github.com/JuliaRegistries/General/pull/24728 too to avoid merge conflicts.

[LLVM SPIRV translator] Add Julia 1.6 compat for LLVM 11.

---

G/GDAL/build_tarballs.jl

`webp` is removed since it brings in `libxml2` which broke the GDAL build, see https://github.com/JuliaGeo/GDAL.jl/pull/99
PROJ_jll is fixed to 7.2 since the minor version is part of the DLL filename, causing
https://github.com/JuliaGeo/GDAL.jl/pull/102

[GDAL] remove webp and fix PROJ minor version

---

C/CompilerSupportLibraries/build_tarballs.jl

Previously, we were accidentally including `libstdc++` twice due to
getting the "latest" version as well as the version corresponding to the
current libgfortran-locked version.  This gets only the latest version.

[CSL] Don't copy libstdc++ twice

---

G/GDAL/build_tarballs.jl

Just like done in https://github.com/visr/Yggdrasil/blob/8f23bd062f9efd77cc87e2aa5e664006b72d32d1/N/NetCDF/build_tarballs.jl#L72-L74
Will hopefully further fix #2140.

[GDAL] fix versions of libcurl and dependencies

---

0_RootFS/Rust/build_tarballs.jl

Previously, we were mistakenly just getting the latest `stable` version
of the `rustc` toolchain.  Instead, we now explicitly ask for a
particular `rustup` version, then a particular `rustc` toolchain.

[Rust] Update build process, get explicit rust toolchain version

---

L/libcxxwrap_julia/build_tarballs.jl

Do not merge this just yet, I want to test the macOS binary to see if it actually solves the issues there.
I've incremented the version as otherwise I am not sure we can rely on everybody receiving the fix? But perhaps this is not actually necessary?
CC @barche

Rebuild libcxxwrap_julia against latest libjulia_jll

---

S/SPIRV_LLVM_Translator/SPIRV_LLVM_Translator@10/build_tarballs.jl

~Only merge when https://github.com/JuliaPackaging/Yggdrasil/commit/e85764c7f595eaf809269ff41b717131f98b7e2c#commitcomment-44214400 is resolved.~
Probably needs to wait on https://github.com/JuliaRegistries/General/pull/24728 too to avoid merge conflicts.

[LLVM SPIRV translator] Add Julia 1.6 compat for LLVM 10.

---

L/libcxxwrap_julia/build_tarballs.jl

As discussed in PR #1948 this is the next update for libcxxwrap -- should only be merged after https://github.com/JuliaRegistries/General/pull/24616 (which needs manual intervention due to julia_compat).
Moreover, I strongly suggest we first test the 0.8.2 build with Julia 1.3, to make sure it really works there; if there is a systematic issue that needs to be fixed, then it'll be annoying to redo all Julia versions.
CC @barche @giordano

libcxxwrap 0.8.4 for Julia 1.4

---

H/HDF5/build_tarballs.jl

This will hopefully help #2133. On `x86_64-apple-darwin` and `x86_64-linux-gnu` it failed to find the HDF5 library.
cc @musm @giordano

[HDF5] add symlinks on more platforms

---

L/LibBirch/build_tarballs.jl

This PR adds the [LibBirch library](https://github.com/lawmurray/Birch/tree/master/libbirch). It was part of https://github.com/JuliaPackaging/Yggdrasil/pull/1924 but I think it might be better to split the previous PR into separate packages for the driver, the libbirch library, the Birch standard library, and the Birch libraries for SQLite and Cairo. This modular setup allows users/developers to only install the desired packages. In particular, Cairo_jll pulls in quite many dependencies, so it might be nice to keep it separate.

Add LibBirch

---

L/Libtask/build_tarballs.jl

This is a follow-up PR to https://github.com/JuliaPackaging/Yggdrasil/pull/2087 that builds Libtask for Julia 1.4 and bumps the version.

Build Libtask for Julia 1.4

---

L/Libtask/build_tarballs.jl

This is a follow-up PR to https://github.com/JuliaPackaging/Yggdrasil/pull/2087 that builds Libtask for Julia 1.5 and bumps the version.

Build Libtask for Julia 1.5

---

I/Ipopt/build_tarballs.jl

Ipopt fails tests with MUMPS_seq 5.3.5. As temporary hack, fix to 5.2.1.
x-ref: https://github.com/jump-dev/Ipopt.jl/pull/243
cc @dpo

[Ipopt] pin MUMPS_seq version

---

O/OpenBLAS/OpenBLAS32@0.3.10/build_tarballs.jl
O/OpenBLAS/OpenBLAS32@0.3.10/bundled/patches/neoverse-generic-kernels.patch
O/OpenBLAS/OpenBLAS32@0.3.10/bundled/patches/openblas-ofast-power.patch
O/OpenBLAS/OpenBLAS32@0.3.10/bundled/patches/openblas-winexit.patch
O/OpenBLAS/OpenBLAS@0.3.10/build_tarballs.jl
O/OpenBLAS/OpenBLAS@0.3.10/bundled/patches/neoverse-generic-kernels.patch
O/OpenBLAS/OpenBLAS@0.3.10/bundled/patches/openblas-ofast-power.patch
O/OpenBLAS/OpenBLAS@0.3.10/bundled/patches/openblas-winexit.patch
O/OpenBLAS/OpenBLASHighCoreCount@0.3.10/build_tarballs.jl
O/OpenBLAS/OpenBLASHighCoreCount@0.3.10/bundled/patches/neoverse-generic-kernels.patch
O/OpenBLAS/OpenBLASHighCoreCount@0.3.10/bundled/patches/openblas-ofast-power.patch
O/OpenBLAS/OpenBLASHighCoreCount@0.3.10/bundled/patches/openblas-winexit.patch

OpenBLAS 0.3.12 was causing a suspicious number of CI timeouts. Since we're using 0.3.10 successfully so far, go back to it, but add the Neoverse patch, which should hopefully be stable for the 1.6 release. We can try again afterwards.

Go back to OpenBLAS 0.3.10

---

0_RootFS/Rust/build_tarballs.jl

[Rust] Use `aatriplet` to write the name of the linker

---

L/libjulia/common.jl
L/libjulia/libjulia@1.5/build_tarballs.jl

The ultimate goal of this PR is to resolve the linker issue [reported here](https://github.com/JuliaPackaging/Yggdrasil/pull/2158#issuecomment-731643842) based on the [pointers by @benlorenz](https://github.com/JuliaPackaging/Yggdrasil/pull/2158#issuecomment-732033167).
For now I just enabled `LibUnwind_jll` as a dependency to see what goes wrong, if anything. This can't be the final version, though, as we must also make sure not to break Julia 1.3 and 1.4.

Rebuild libjulia+jll 1.5 with fixed libunwind linkage

---

L/libcxxwrap_julia/build_tarballs.jl

This is marked as a draft, as it shouldn't be merged immediately; instead, first...
1. https://github.com/JuliaRegistries/General/pull/25105 should be merged...
2. ... and tested, i.e. libcxxwrap 0.8.4 for Julia 1.4 should be verified before we advance further
3. and I'd also like to test at least the macOS build artifact produced by this PR before merging.
CC @barche

libcxxwrap 0.8.5 for Julia 1.5

---

B/BLST/build_tarballs.jl

If you are into Pairing Based Cryptography (PBC) -
in perticular BLS-381 - then this will make you very happy.
It is the fastest implementation out there:
https://github.com/supranational/blst
Use the 'Clang' package to generate wrappers.

Added support for Supernational's BLST library

---

L/LibOSXUnwind/build_tarballs.jl

... without experimental platforms and with correct julia_compat bound
See https://github.com/JuliaPackaging/Yggdrasil/pull/2190#issuecomment-735318854
and also https://github.com/JuliaRegistries/General/pull/25468
Ping @giordano @staticfloat
A follow up PR could re-enable the experimental platforms, as long as it increases the version to at least 0.0.7

LibOSXUnwind: rebuild 0.0.6

---

L/libgeotiff/build_tarballs.jl
L/libgeotiff/bundled/patches/more-reasonable-default-bin-subdir.patch

This PR adds a `build_tarballs.jl` script to build [libgeotiff](https://github.com/OSGeo/libgeotiff).
I created the file using `BinaryBuilder.run_wizard()`. The only modification I had to make outside of the repo notes is the addition of a `export LDFLAGS="$LDFLAGS -lstdc++"` step. Otherwise I kept running into linking issue with the wrong libstdc++ being used in the sandbox
```
[ 92%] Linking C executable makegeo
cd /workspace/srcdir/libgeotiff-1.6.0/bin && /usr/bin/cmake -E cmake_link_script CMakeFiles/makegeo.dir/link.txt --verbose=false
/opt/x86_64-linux-gnu/bin/../lib/gcc/x86_64-linux-gnu/7.1.0/../../../../x86_64-linux-gnu/bin/ld: warning: libstdc++.so.6, needed by /opt/x86_64-linux-gnu/x86_64-linux-gnu/sys-root/usr/local/lib/libproj.so.21.0.2, not found (try using -rpath or …
```

add libgeotiff

---

L/libgeotiff/build_tarballs.jl

I forgot to output the actual shared library in the first commit.
I tested it locally with `julia --color=yes build_tarballs.jl --verbose --debug` and no fatal errors?

[libgeotiff] update build_tarballs to output shared libs

---

C/CeresSolver/build_tarballs.jl
L/LLVM/common.jl
N/NNPACK/build_tarballs.jl
S/Snowball/build_tarballs.jl

[skip ci] [skip build]
This is part of an effort to reduce hardcoded uses of /opt

Use CMAKE_TARGET_TOOLCHAIN env var where possible

---

B/Birch_Standard/build_tarballs.jl
B/Birch_Standard/bundled/stdio.patch

This PR adds the [Birch standard library](https://github.com/lawmurray/Birch/tree/master/libraries/Standard), hence I thought the name `Birch_Standard` would be appropriate. It was part of https://github.com/JuliaPackaging/Yggdrasil/pull/1924 but as mentioned in https://github.com/JuliaPackaging/Yggdrasil/pull/2155 I think I prefer a modular setup.
The patches for FreeBSD and musl included in https://github.com/JuliaPackaging/Yggdrasil/pull/1924 are not needed anymore, I moved them upstream.

Add Birch Standard library

---

H/HelFEM/build_tarballs.jl

Wraps `lobatto` (https://github.com/mortenpi/HelFEM/compare/HelFEM_jll/v0.0.2...mortenpi:HelFEM_jll/v0.0.3).

Update HelFEM to 0.0.3

---

S/SPIRV_Headers/build_tarballs.jl

Yes, upstream has multiple tags without bumping the version... https://github.com/KhronosGroup/SPIRV-Headers/releases

[SPIRV-Headers] Include new raytracing defs in 1.5.4.

---

L/libjulia/common.jl
L/libjulia/libjulia@1.5/build_tarballs.jl

WIP trying to fix the issue on macOS reported [here](https://github.com/JuliaPackaging/Yggdrasil/issues/2160#issuecomment-735287449) by @barche: on macOS, we get this error:
```
dyld: lazy symbol binding failed: Symbol not found: __Unwind_Resume
Referenced from: /Users/user/tmp/clean_julia_depot_cxx/artifacts/1417b691b9d1117225089c656ede8940fbf2eba8/lib/libtypes.dylib
Expected in: /Applications/Julia-1.5.app/Contents/Resources/julia/bin/../lib/libjulia.dylib
dyld: Symbol not found: __Unwind_Resume
Referenced from: /Users/user/tmp/clean_julia_depot_cxx/artifacts/1417b691b9d1117225089c656ede8940fbf2eba8/lib/libtypes.dylib
Expected in: /Applications/Julia-1.5.app/Contents/Resources/julia/bin/../lib/libjulia.dylib
```
This is because libosxunwind is linked statically but it really needs to be …

libjulia 1.5: link LibOSXUnwind dynamically

---

L/LibOSXUnwind/build_tarballs.jl

This is identical to 0.0.6 except that it adds aarch64 support and sets julia_compat to 1.6
See [discuss here](https://github.com/JuliaPackaging/Yggdrasil/pull/2190#issuecomment-736309195).
CC @staticfloat.
Should only be merged after PR #2199 is closed (merged or rejected).

LibOSXUnwind 0.0.7

---

S/Singular/build_tarballs.jl

CC @thofma @benlorenz one more step towards https://github.com/oscar-system/Oscar.jl/issues/193
Note that for Singular, versioning is a bit awkward; we have versions like 4.1.3p5 -- so there are two patch levels (!?!); the 4 is basically constant, and even the 1 changes rarely. And in the past, I think there were ABI breaks even in patch level releases... Anyway, I am going to ask Hans tomorrow to please call the next release 4.2 ;-).

Singular_jll v400.101.390

---

I/ICU/build_tarballs.jl
I/ICU/bundled/patches/yes_stdlibs.patch

armv7l has a slightly more persnickety linker than on other platforms,
and the weirdness that ICU does here, trying to create a "data-only"
shared library causes the linker to freak out.  It turns out most
distros patch away some of the weirdness, so we carry a patch as well.
Since it is highly unlikely any Julia package will ever want to load
this data directly, we'll also mark it as `dont_dlopen` for good
measure.

[ICU] Fix `libicudata` issues on armv7l

---

L/libcxxwrap_julia/build_tarballs.jl

This may fix the crash reported here: <https://github.com/JuliaInterop/libcxxwrap-julia/issues/75>.
Once the binaries are built, I'll verify this locally with an artifact override.
CC @barche @benlorenz

libcxxwrap_julia for Julia 1.5: rebuild with GCC 8

---

L/libplist/build_tarballs.jl

libplist is a cross-platform library for dealing with `.plist` files,
common on Apple platforms, and necessary for `ldid`.

[libplist] Add libplist `v2.2.0`

---

L/ldid/build_tarballs.jl

This utility makes it easy to perform ad-hoc code signing of mach-o
executables.

[ldid] Add `ldid` `v2.1.2`

---

F/finufft/build_tarballs.jl

~~GOMP linking does not work on GCC8 for whatever reason. Accordingly, FINUFFT is broken using multiple threads. However, it did work fine with the BinaryBuilder version 0.26 available on julia 1.5.2. GCCv9 should help with the performance anyway.~~
Please see my comment below.

FINUFFT: Fix GOMP linking

---

U/UBPF/build_tarballs.jl

[ubpf](https://github.com/iovisor/ubpf) is a simple eBPF (Extended Berkeley Packet Filter) VM implementation in C, which strives to provide a simple and accessible alternative to the Linux Kernel's internal eBPF VM. I'm interested in using it for my [BPFnative.jl](https://github.com/jpsamaroo/BPFnative.jl) package for testing and also for tracing/profiling use cases.
While eBPF is platform-agnostic, the file loader built into ubpf is ELF-only (as is pretty much the entire BPF ecosystem), so I'm skipping Windows and Mac support for now. If in the future ubpf gains support for COFF and Mach-O binaries, I'll add them to this builder.
I'm using my personal fork of ubpf because upstream is pretty quiet (the maintainers are busy right now), but if and when it becomes active then I'll switch the …

Add ubpf library

---

R/rr/build_tarballs.jl

We ran into a Linux kernel bug on CI trying to get rr to properly find the .sos it depends on.
Rather than trying to make that whole dance work, just link rr statically, so we don't have
to worry about setting it up to be able to find the capnproto.so. Note that this isn't a true
static link since we're still linking the libc and CSL dynamically, but hopefully it's good enough
to avoid the errors we were seeing.

[rr] Link libcapnproto statically

---

F/FLINT/build_tarballs.jl

@fingolfin `200.690` is too old to push https://github.com/Nemocas/Nemo.jl/pull/919 over the finish line.
Did I bump the version correctly? Or should I bump the patch version?

[FLINT] new version

---

L/LMDB/build_tarballs.jl

Skipping LMDB 0.9.26 as it [only impacts for FreeBSD](https://bugs.openldap.org/show_bug.cgi?id=9278).
Please let me know if you disagree and I'll do that PR first.

LMDB 0.9.27

---

A/Antic/build_tarballs.jl

I have also introduced the version scheme that we are using for flint.
@fingolfin Is this OK with the version? We still have the problem with https://github.com/JuliaPackaging/BinaryBuilderBase.jl/issues/89.

[Antic] Version 0.2.3

---

A/Arb/build_tarballs.jl

Also introduce the new version number scheme.
@fingolfin We need these binaries, because the current ones don't work with FLINT_jll 200.700.0 (see https://github.com/kalmarek/Arblib.jl/pull/105).

[Arb] New version

---

F/FFTW/build_tarballs.jl

I have changed the download source for FFTW to be fftw's official download link,
instead of the link that was being used here (an unofficial one). FFTW recently
released version 3.3.9, which includes at least one function that is not present
in the current FFTW_jll artifact. This is likely due to the current download
link pointing to an old release candidate for fftw 3.3.9, instead of the
released version.
More details about this change, and why I think it is necessary, can be found in
JuliaMath/FFTW.jl#170.

[FFTW] Update FFTW source and use version 3.3.9

---

N/normaliz/build_tarballs.jl

Also our the new decoupled versioning scheme for the JLL, as well as a hardcoded FLINT_jll dependency
CC @benlorenz @thofma

Update to Normaliz 3.8.9

---

T/TetGen/build_tarballs.jl
T/TetGen/cwrapper/cwrapper.cxx

* Update of upstream patch version to "August 18, 2018". Formally this still appears to be 1.5.1
* Catch errors thrown by TetGen in a rc variable
* Handle unsuitable callback to allow local refinement.

Update of upstream TetGen patch version and wrapper API improvemnts

---

L/libsingular_julia/libsingular_julia@1.4/build_tarballs.jl

This is a draft for now: On the one hand, I am waiting for https://github.com/Nemocas/Nemo.jl/pull/919 to be merged and a new release of Nemo.jl, so that I can then in turn update https://github.com/oscar-system/Singular.jl/ to use libsingular_julia_jll 0.3 and the new Nemo.jl.
On the other hand, there is this bug in https://github.com/JuliaPackaging/BinaryBuilderBase.jl/issues/89 which affects this JLL, too (although we are not immediately affected, as it just our "second layer of defense", so we can ultimately proceed even if that bug is not yet fixed in BBB)

libsingular_julia for Julia 1.4

---

P/polymake/build_tarballs.jl

Also update its version to follow our new scheme.
Should only be merged with @benlorenz approval. CC @thofma 
I've debated with myself whether to also hardcode the `normaliz_jll` version (it also depends on FLINT_jll), but right now I think this is not necessary as the usual package dependency mechanism will take care of it. Alas, Benjamin or Tommy might disagree.

Update polymake_jll to use FLINT 2.7.0

---

L/libpolymake_julia/common.jl
L/libpolymake_julia/libpolymake_julia@1.3/build_tarballs.jl

This won't compile succesfully until https://github.com/JuliaPackaging/Yggdrasil/pull/2304 is merged and in the registry.
But I wanted to get it out here right away to (a) have it of my plat and (b) to maximize the time @benlorenz has to look at it.

Update libpolymake_julia (for Julia 1.3)

---

L/libjulia/common.jl

Without this, we are now seeing the following:
---> apk add coreutils libuv-dev utf8proc
ERROR: unsatisfiable constraints:
ninja (virtual):
provided by: samurai
required by: world[ninja]
---> apk add coreutils libuv-dev utf8proc
Previous command exited with 1
Child Process exited, exit code 1

Fix libjulia_jll building regression

---

0_RootFS/Rootfs/bundled/utils/flagon

No idea why I used `/usr/bin/bash` instead of `/bin/bash`.  It goes without
saying that the former doesn't even exist in the build environment.

[0_RootFS] Fix interpreter of `flagon` utility

---

F/FastJet_Julia_Wrapper/build_tarballs.jl
L/LCIO_Julia_Wrapper/build_tarballs.jl
L/Libtask/build_tarballs.jl
L/libcxxwrap_julia/build_tarballs.jl
L/libjulia/common.jl
L/libsingular_julia/common.jl

... so that packages using libjulia_jll have an easier time to select
the right base set of platforms. Now they can just start with the result
of `libjulia_platforms()` instead of `supported_platforms()` and then
selectively remove those which are not supported.
Also adapt a few JLL recipes to use the new helper.
This PR should ultimately be marked as "skip ci, skip build", I think, but first I'd like to make sure everything still builds.

Add libjulia_platforms() helper

---

C/CGAL/build_tarballs.jl

Removes specific version coupling to its dependencies since it doesn't
appear to be much of an issue which version gets to be picked, be it the
latest or the minimum supported version.

[CGAL] Update to v5.2

---

Q/Qt/build_tarballs.jl

OpenSSL support for QT.  Looks like it was disabled by default, at least for Linux x64.

[QT] enable OpenSSL support

---

S/SDPA/build_tarballs.jl

Make some progress towards issue #2160 
Should not be merged before @ViralBShah had a chance to review and comment. Also, there are some questions to discuss: 
1. Which version to use for this JLL? It really shouldn't be the same as right now, as the list of dependencies changes, and that requires a new version.
2. Which Julia versions should this JLL be made compatible with? Right now, this is built for Julia 1.5.3 or later, and thus only usable in Julia >=1.5. But we could make versions supporting 1.4 or even 1.3 if desired. But that's extra work and complexity, so I first would like to get this version working, and also hear explicitly that Julia 1.3/1.4 support is wanted, before spending time on it.
3. The two first points are actually somewhat related: in order to support multiple …

Update SDPA to new libcxxwrap / libjulia

---

J/jlqml/build_tarballs.jl

Make some progress towards issue #2160 
Should not be merged before @barche had a chance to review and comment. Also, there are some questions to discuss: 
1. Which version to use for this JLL? It really shouldn't be the same as right now, as the list of dependencies changes, and that requires a new version.
2. Which Julia versions should this JLL be made compatible with? Right now, this is built for Julia 1.5.3 or later, and thus only usable in Julia >=1.5. But we could make versions supporting 1.4 or even 1.3 if desired. But that's extra work and complexity, so I first would like to get this version working, and also hear explicitly that Julia 1.3/1.4 support is wanted, before spending time on it.
3. The two first points are actually somewhat related: in order to support multiple Julia …

Update jlqml to new libcxxwrap / libjulia

---

G/GDAL/build_tarballs.jl

This PR modifies the `GDAL` build script to add `Libtiff` and `libgeotiff` as dependencies and build using them as external versions rather than the internal versions shipped with the code. See discussion [here](https://github.com/JuliaGeo/GDAL.jl/issues/110) for background.
Tested locally on a small subset of OS/compiler combos with no issues.
cc @visr

[GDAL] use external libtiff and libgeotiff libraries to build

---

L/libcgal_julia/libcgal_julia@1.5/build_tarballs.jl

Apologies if I'm submitting this too fast after the 1.4 update, but I'd assume concurrent updates aren't necessarily an issue since they're effectively different versions.  Unless registering "future" versions (if it ends up happening) is an issue, here's another PR.
**EDIT**: Maybe next time I'll just wait for previous versions to hit the registry, avoid complications ^^ For quick reference, here's the previous version's Registry PR: JuliaRegistries/General#27271

[libcgal-julia] Update libcgal_julia for Julia 1.5

---

P/polymake/bundled/patches/generate_deps_tree.jl

Work around stdlibs in nightly that ship `GMP_jll` and `MPFR_jll` without headers by downloading the corresponding artifacts manually as suggested in https://github.com/JuliaLang/julia/pull/38797.
I tested the script with 1.3, 1.4, 1.5, and various nightly versions.

[polymake] fix dependency-tree for stdlibs in nightly

---

.devcontainer/Dockerfile

`BinaryBuilder#master` isn't in a good shape at the moment and requires some random versions of Julia in the `release-1.6` branch.  I think that for the time being the best thing to do is to use last stable BinaryBuilder with Julia v1.5

[Codespaces] Update to Julia v1.5, use stable BinaryBuilder

---

.ci/Manifest.toml
.ci/register_package.jl

This includes https://github.com/JuliaPackaging/BinaryBuilder.jl/pull/986.
Also, correctly register JLLs with lazy artifacts.

[AZP] Update to latest BinaryBuilder

---

H/HelFEM/build_tarballs.jl

Make some progress towards issue #2160 
Should not be merged before @mortenpi had a chance to review and comment. Also, there are some questions to discuss: 
1. Which version to use for this JLL? It really shouldn't be 0.0.3, as the list of dependencies changes, and that requires a new version.
2. Which Julia versions should this JLL be made compatible with? Right now, this is built for Julia 1.5.3 or later, and also only usable in Julia 1.5. But we could make versions supporting 1.4 or even 1.3 if that is desirable. But it's a bit extra work, so I first want to get this version working, and also hear from @mortenpi what his preferences are.
3. The two first points are actually somewhat related: in order to support multiple Julia versions, the trick we used in other JLLs is to use the …

Convert HelFEM to use new libcxxwrap / libjulia

---

S/Singular/build_tarballs.jl
S/Singular/bundled/patches/0001-fix-add-n_InitMPZ-and-n_MPZ-for-Zn.patch

Ideally this would be built with https://github.com/JuliaPackaging/BinaryBuilderBase.jl/pull/93 in effect (e.g. via https://github.com/JuliaPackaging/Yggdrasil/pull/2369). Then we could see if the VersionSpec change works as intended.

Singular: backport upstream fix

---

.ci/Manifest.toml

We had to revert https://github.com/JuliaPackaging/BinaryBuilderBase.jl/pull/93
because it breaks registration of the LLVM package.

[AZP] Update BinaryBuilderBase

---

C/CompilerSupportLibraries/build_tarballs.jl

Using `ls` output in scripts is generally considered a [bad idea](https://mywiki.wooledge.org/ParsingLs),
in the previous versions of this recipe it caused to copy a file which isn't
even in the wanted directory.  Quoting from the log:
```
---> for d in /opt/${target}/${target}/lib*
---> NON_LATEST_LIBS=$(ls ${d}/*.${dlext}* | grep -v libstdc++ | grep -v libgomp)
---> cp -uav ${NON_LATEST_LIBS} ${libdir}/
'LatestLibraries.v0.3.6.x86_64-linux-gnu.tar.gz' -> '/workspace/destdir/lib/LatestLibraries.v0.3.6.x86_64-linux-gnu.tar.gz'
```
Additionaly, this use libs from the newly built GCC 10.2.

[CompilerSupportLibraries] Do not use `ls` to find the files to copy

---

L/libsingular_julia/libsingular_julia@1.5/build_tarballs.jl

CC @thofma 
I would suggest to wait with merging this PR until #2391 is merged and the result got accepted in the general registry, to avoid trouble -- but perhaps I am overly careful here and the infrastructure can handle it? What I am concerned about is this: what if the registry ends up getting PRs for 0.6.4 and 0.6.5 very close to each other, will it really automerge both and in the right order?

Update libsingular to 0.6 for Julia 1.5

---

U/UserNSSandbox/build_tarballs.jl
U/UserNSSandbox/bundled/sandbox.c

As part of the effort to split BB up into smaller, more manageable
pieces, create a standalone JLL that contains the `sandbox` user
namespacing utility, and strip out all parts of its life as an `init`
replacement for running inside of `QEMU`.  If we ever resurrect that
part of its life, we'll do so with a dedicated tool.

Add `UserNSSandbox`

---

L/LibGit2/build_tarballs.jl

Julia v1.6 uses MbedTLS v2.24.0, so use that instead of the latest.
As a side note; this should not be necessary once we manage to get BBB working on julia v1.6+, since it should respect the julia compat better.

LibGit2: build for Julia v1.6 against MbedTLS_jll v2.24.0

---

M/MbedTLS/build_tarballs.jl

libmbedcrypto changed its SOVERSION in 2.25, making this unlinkable on Julia v1.6.

MbedTLS 2.25 is incompatible with Julia 1.6

---

0_RootFS/GCCBootstrap@7/bundled/patches/gcc710_i386_avx512fintrin.patch
0_RootFS/GCCBootstrap@8/bundled/patches/gcc710_i386_avx512fintrin.patch

Closes https://github.com/JuliaPackaging/Yggdrasil/issues/2389. This is my first time patching the root bundle so let be know if I missed anything. I believe I named the patch appropriately using the first GCC version affected.
Here's the original patch: https://github.com/gcc-mirror/gcc/commit/23bce99cbe7016a04e14c2163ed3fe6a5a64f4e2#diff-c3bbd1dcd7c953ef6d719969fb187e31209ef3d7851a84448aad949aea2e8106. I'll note I'm currently only patching the header file (as was mentioned here: https://github.com/JuliaPackaging/Yggdrasil/pull/2385#discussion_r556600642) but we may want to apply the entire patch.
Edit: I see now that the other code change only applies to the tests so just patching the header should be fine.

[GCCBootstrap] Patch avx512fintrin

---

G/GAP/build_tarballs.jl

Fix typo in GAP_jll init_block

---

B/blis/build_tarballs.jl

Hi.
[BLIS](https://github.com/flame/blis) has made quite a lot of changes since last binary.
This 0.8.0 compiles BLIS tag 0.8.0 and provides additional routines such as `bli_gemmt`.

[BLIS]Update to Version 0.8.0

---

0_RootFS/Rootfs/build_tarballs.jl

This gives us the ability to easily ad-hoc sign mach-o
libraries/executables, which is important for Big Sur, especially M1
machines.

Bundle `ldid` into the rootfs

---

0_RootFS/GCCBootstrap@4/bundled/patches/gcc485_texi.patch
0_RootFS/gcc_common.jl

Our libtapi build is naming `dsymutil` differently, so fix that.  Also,
fix a GCC docs issue that we weren't hitting before

Fix GCC build on MacOS

---

0_RootFS/gcc_common.jl

Reduces the GCCBootstrap shard size by removing unneeded man pages.
```
281M	./aarch64-apple-darwin20/sys-root/usr/share/man
```

Remove man pages from GCCBootstrap sysroot

---

S/SBML/build_tarballs.jl

SBML is Systems Biology Markup Language, a de-facto standard for creation, annotation, conversion and processing of models for computational systems biology, see https://en.wikipedia.org/wiki/LibSBML. This builds the package as-is with minimal required explicit modifications in the build script.
I'm a bit new to JLL packaging, any feedback welcome.

new recipe: SBML

---

H/HiGHS/build_tarballs.jl

Changes to the cmake script supplied by @galabovaa. (I haven't actually run this locally, so we will see what happens.)
Minor version is incremented because we drop support for 'libipx'. (Was this intended @galabovaa?)
cc @matbesancon since he has more experience with this.
Closes https://github.com/JuliaPackaging/Yggdrasil/pull/2358

[HiGHS] Update build to a recent commit.

---

X/XML2/build_tarballs.jl

I believe I need this to build LLVMBootstrap for `aarch64-apple-darwin20`:
```
[03:48:01]  ---> cp -a $(realpath ${libdir}/libxml2.so) ${prefix}/${target}/lib64
[03:48:01] cp: can't stat '/workspace/aarch64-apple-darwin20-libgfortran5-cxx11/destdir/lib/libxml2.so': No such file or directory
```

[XML2] Build on experimental platforms

---

0_RootFS/Rootfs/bundled/utils/apk_wrapper.sh

As far as I can see, only `apk add` accepts this option.  In particular, forcing
`--no-chown` everywhere breaks `apk del`.
Ref: https://github.com/JuliaPackaging/Yggdrasil/pull/2468#issuecomment-770438499.

[Rootfs] Pass `--no-chown` only to `apk add`

---

.ci/Manifest.toml

In particular, get
* New macOS shards
(https://github.com/JuliaPackaging/BinaryBuilderBase.jl/pull/104)
* HostBuildDependency
(https://github.com/JuliaPackaging/BinaryBuilderBase.jl/pull/43,
https://github.com/JuliaPackaging/BinaryBuilder.jl/pull/995)
* New PlatformSupport with new macOS SDK
(https://github.com/JuliaPackaging/BinaryBuilderBase.jl/pull/109)
Will we survive to all these changes?

[AZP] Update BinaryBuilder and BinaryBuilderBase

---

T/tblis/build_tarballs.jl

To ensure at least 1 configuration is usable.
Usually this is not needed, but x86_64 compatible layers like
Windows' ARM64EC and Apple's Rosetta 2 runs these.
Didn't notice this util I tried to run on Apple Silicon...

[TBLIS] Build Reference Kernels for All Situations

---

S/SBML/build_tarballs.jl

libsbml [is known](http://sbml.org/Software/libSBML/5.18.0/docs/cpp-api/libsbml-issues.html#gcc5-python)
to cause `free()` errors when built with [GCC 5.1 or 5.2](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=67557)
Fix #2492.  CC: @exaexa.

[SBML] Rebuild with GCC 6 to work around known issue

---

0_RootFS/common.jl

Uses `pigz` for compressiong the "unpacked" artifact. Uses the changes from: https://github.com/JuliaPackaging/BinaryBuilderBase.jl/pull/113

Use BinaryBuilderBase archive_artifact

---

L/LibUnwind/bundled/patches/libunwind-cfa-rsp.patch

Also drop changes for other architectures (c.f. https://github.com/JuliaLang/julia/pull/39553).

libunwind: Fix CFA-RSP patch for freebsd

---

.devcontainer/Dockerfile

Note: RC1 is not yet available in Docker Hub, we'll probably need to wait a few
days more before merging this.

[Codespaces] Update to Julia v1.6 and BinaryBuilder#master

---

0_RootFS/LLVMBootstrap@11/build_tarballs.jl

Addresses the `error: unknown target CPU 'x86-64'` problem noted in: https://github.com/JuliaPackaging/BinaryBuilderBase.jl/pull/112#issuecomment-772088375. Follow up to: https://github.com/JuliaPackaging/Yggdrasil/pull/2473

[LLVMBootstrap] Use GCC 7 for LLVM 11

---

.ci/register_package.jl

We can use the new function `BinaryBuilderBase.is_runtime_dependency`.

[AZP] Better way to filter runtime dependencies when registering

---

P/polymake/build_tarballs.jl
P/polymake/bundled/patches/latte-config.patch

taken from polymake master
this should avoid some annoying warning during usage

[polymake] add patch to avoid picking up the wrong count binary (at runtime)

---

O/OpenBLAS/OpenBLAS32@0.3.13/build_tarballs.jl
O/OpenBLAS/OpenBLAS@0.3.13/build_tarballs.jl
O/OpenBLAS/OpenBLASHighCoreCount@0.3.12/build_tarballs.jl
O/OpenBLAS/OpenBLASHighCoreCount@0.3.13/build_tarballs.jl
O/OpenBLAS/common.jl

Following https://github.com/JuliaLang/julia/issues/39436, first attempt at building blas with 64 bits even on aarch64 without the special condition

[OpenBLAS] build 64 Aarch without special case

---

.ci/register_package.jl

The CR is interpreted by Azure as a newline, resulting in huge logs.

Remove download progress logging again.

---

L/LLVMLibUnwind/LLVMLibUnwind@11.0.0/build_tarballs.jl
L/LLVMLibUnwind/LLVMLibUnwind@11.0.1/build_tarballs.jl
L/LLVMLibUnwind/common.jl

The [`unw_init_local_dwarf`](https://github.com/JuliaPackaging/Yggdrasil/blob/1c96ea350b383bf157e60fe037cd9452a8416fe3/L/LLVMLibUnwind/LLVMLibUnwind%4011.0.0/bundled/patches/0002-force-dwarf.patch#L17) added by the `0002-force-dwarf.patch` in #2557 isn't accessible due to not installing the LLVM libunwind header files. I've taken the [same approach that LibOSXUnwind did](https://github.com/JuliaPackaging/Yggdrasil/blob/1c96ea350b383bf157e60fe037cd9452a8416fe3/L/LibOSXUnwind/build_tarballs.jl#L33) by manually copying over the header files.
Needed to finish up: https://github.com/JuliaLang/julia/pull/39127

[LLVMLibUnwind] Install header files

---

O/OpenBLAS/OpenBLAS@0.3.10/build_tarballs.jl
O/OpenBLAS/common.jl

We aren't ready to make this switch on `release-1.6`, this will be a `release-1.7` feature alongside libblastrampoline

[OpenBLAS] OpenBLAS v0.3.10 should not include ILP64 aarch64

---

G/GDAL/GDAL@julia-1.3/build_tarballs.jl

See https://github.com/JuliaRegistries/General/pull/30206#issuecomment-780412386.
Since the previous build has not been used anywhere yet, I guess it is fine to leave the version_offset as is? Or should I bump the patch version offset?

[GDAL] specify patch version of proj_jll_version

---

S/SuiteSparse/SuiteSparse/build_tarballs.jl
S/SuiteSparse/common.jl

Link to LBT (instead of OpenBLAS). Also uses ilp64 BLAS on aarch64 by default.

[SuiteSparse] Update to 5.8.1 and link to LBT

---

O/OpenBLAS/OpenBLAS@0.3.10/build_tarballs.jl
O/OpenBLAS/common.jl

Turns out that OpenBLAS 0.3.12 and earlier have some kind of
`clang`-related code generation bug when built like this.
The issue is that the call to `gotoblas->init()` here [0] does not
actually call `init` but instead calls `ztrsm_olnncopy`, presumably
because of some struct layout issue.  I briefly looked into it, but
since it only effects `clang` and doesn't effect `0.3.13`, I'm taking
the coward's way out and just not poking the compiler bear.
[0]
https://github.com/xianyi/OpenBLAS/blob/v0.3.10/driver/others/dynamic.c#L921
X-ref: https://github.com/JuliaLang/julia/pull/39719

[OpenBLAS] Disable `TARGET=GENERIC` on OpenBLAS 0.3.12 and earlier

---

G/GMP/GMP@6.1.2/build_tarballs.jl
G/GMP/GMP@6.2.1/build_tarballs.jl
G/GMP/GMP@6.2.1/bundled/patches/gmp-exception.patch
G/GMP/GMP@6.2.1/bundled/patches/gmp_alloc_overflow_func.patch
G/GMP/common.jl

GMP release notes for 6.2.1 (https://gmplib.org/gmp6.2)
> Initial support for Darwin on arm64, and improved portability.

[GMP] Add GMP 6.2.1

---

L/LibGit2/build_tarballs.jl
L/LibGit2/bundled/patches/libgit2-continue-zlib.patch

libgit2 v1.1.0 has a bug with zlib stream handling, causing clone error on 32-bit systems.
This backports the patch to fix the bug. (xref: https://github.com/libgit2/libgit2/pull/5740)

[LibGit2] Add patch to fix zlib stream handling

---

H/hsa_rocr/build_tarballs.jl

ROCR doesn't need any special patches to run on musl, thankfully

[hsa_rocr] Build for musl

---

L/LLVM/LLVM_full_assert@11.0.1/build_tarballs.jl
L/LLVM/libLLVM@11.0.1/build_tarballs.jl

Triggers the assert version of 11.0.1 which had a patch in the previous
commit, as well as the non-asserts libLLVM.

Trigger LLVM builds

---

T/Trilinos/build_tarballs.jl

- This changes binary dep from `SuiteSparse32` to `SuiteSparse` as required by Xyce.
- Turns `Umfpack` on.

Trilinos 12.12.1 update

---

G/GStreamer/build_tarballs.jl

I'm not sure what's going on 32 bit musl and powerpc. The errors I'm getting are, respectively,
```
ninja: job failed: /opt/bin/i686-linux-musl-cc  -o tests/examples/streams/stream-status 'tests/examples/streams/45a1c43@@stream-status@exe/stream-status.c.o' -Wl,--as-needed -Wl,--no-undefined -Wl,-Bsymbolic-functions -Wl,--start-group gst/libgstreamer-1.0.so.0.1803.0 /workspace/destdir/lib/libglib-2.0.so /workspace/destdir/lib/libgobject-2.0.so -Wl,--export-dynamic /workspace/destdir/lib/libgmodule-2.0.so -pthread -lm -Wl,--end-group '-Wl,-rpath,$ORIGIN/../../../gst:/workspace/destdir/lib' -Wl,-rpath-link,/workspace/srcdir/gstreamer-1.18.3/build/gst -Wl,-rpath-link,/workspace/destdir/lib
/workspace/destdir/lib/libunwind.so.8: undefined reference to `setcontext'
collect2: error: ld returned …
```

[GStreamer] Add builder

---

U/UserNSSandbox/build_tarballs.jl
U/UserNSSandbox/bundled/sandbox.c

With the `--persist` option, it is now possible to persist changes made
to the root fs between runs.  This is showcased in the new release of
`Sandbox.jl`, which allows much easier breakpointing and debugging of
build systems.

[UserNSSandbox] Add `--persist` option

---

L/LAPACK/build_tarballs.jl

Addresses #2657 
The main missing thing here is to make it depend on our own BLAS, ideally through LBT. I'm not quite sure how to make its cmake recipe pick a BLAS - help welcome.

[LAPACK] Add builder

---

P/pandoc_crossref/build_tarballs.jl

I would like to add `pandoc-crossref`. This version supports [Pandoc version 2.9](https://github.com/lierdakil/pandoc-crossref/releases/tag/v0.3.6.4), which is contained in [Yggdrasil](https://github.com/JuliaPackaging/Yggdrasil/blob/master/P/pandoc/build_tarballs.jl) at the moment.
After reading the documentation, I'm still unsure how to test the changes. Instead, I've used the Pandoc Yggdrasil script as a template. Some pointers on how I can improve the changes are welcome.
EDIT: I've got it working via the devcontainer. I am now fixing some issues in the file.

Add pandoc-crossref

---

.ci/Manifest.toml
A/Arb/build_tarballs.jl

With https://github.com/JuliaPackaging/BinaryBuilder.jl/pull/1023 and https://github.com/JuliaPackaging/BinaryBuilderBase.jl/pull/123 merged I'd like to use them (and thus also test them "in the field"). We have a bunch of packages that could use them, but I figure we should start with one and then see if it works (or if not, then the Manifest.toml change here can be reverted until we figure it out).
@giordano @staticfloat is that OK, or do you prefer another approach (which)?
CC @thofma @benlorenz

Update to latest BB, and test new compat field with Arb

---

F/FLINT/build_tarballs.jl

CC @thofma @benlorenz (since we are now using tight versioning, there should be no need to worry about this right now -- once all JLLs depending on this are updated, we can look into adjusting LoadFlint, Nemo, etc.)

FLINT 2.7.1

---

P/polymake/build_tarballs.jl

building and loading works fine without that dont_dlopen
This build will also include the patch from the previous update that we needed to remove from the registry because it failed to load due to the `dont_dlopen`.

[polymake] remove dont_dlopen, swich to compat entries for deps

---

A/AzStorage/build_tarballs.jl

This is for a change in AzStorage.jl that allows for larger OAuth2 tokens.

new azstorage version 0.2.1

---

C/CompilerSupportLibraries/build_tarballs.jl

We want the symlinks such as `libatomic.so -> libatomic.so.1`.  This
symlink was being eliminated in the `rm` pass that was trying to drop
all linker scripts, but because the check (which was attempting to
determine whether a library is a proper `ELF` file or not) did not
dereference symlinks, it was rejecting all symlinks as non-`ELF` files.

[CompilerSupportLibraries] Don't eliminate `.so` symlinks

---

B/blis/build_tarballs.jl
B/blis/bundled/patches/bli_macro_defs.h.f77suffix64.patch

A recent upstream fix (flame/blis@8a3066c) addresses generic-stride problems (flame/blis#484) for configurations with gemmsup enabled.
Including this fix in our binary would address JuliaLinearAlgebra/BLIS.jl#1 and let the package pass all CI tests.

[BLIS]Include a Recent Upstream Fix + Switch BLAS Interface to ILP64

---

K/Kaleido/build_tarballs.jl

@sglyon: I'm creating a JLL package which should make it a bit easier for you to
update Kaleido in the future.  Also, this makes sure the program is executable.

[Kaleido] Add builder

---

E/ECOS/build_tarballs.jl

ECOS_jll doesn't bundle the header files, which makes it difficult to automatically build a wrapper:
```Julia
julia> readdir(ECOS_jll.artifact_dir)
3-element Array{String,1}:
"lib"
"logs"
"share"
```

[ECOS] copy include files

---

Q/Qt/build_tarballs.jl

@barche any issues with removing static libraries from the tarballs?  Is it
possible some libraries want to static link Qt?  It'd save some space on disk.

[Qt] Remove static libraries from tarballs

---

I/ImarisWriter/build_tarballs.jl

ImarisWriter is a high performance file writer for microscopy images
Add ImarisWriter build_tarballs.jl with sources from https://github.com/JaneliaSciComp/ImarisWriter/tree/binarybuilder
The original source is from https://github.com/imaris/ImarisWriter under Apache License Version 2.0 by Imaris (fma Bitplane) of Oxford Instruments
This package depends on HDF5 and is thus limited by cross compilation issues there.
Mac build fails due to lack of features.h. See H5_HAVE_FEATURES_H in
/opt/x86_64-apple-darwin14/x86_64-apple-darwin14/sys-root/usr/local/include/H5pubconf.h
/opt/x86_64-apple-darwin14/x86_64-apple-darwin14/sys-root/usr/local/include/H5public.h
CMake cannot locate libhdf5 on Windows which is located in `$prefix/bin/libhdf5-0.dll`. A custom CMake variable is provided as a …

[ImarisWriter] Add initial ImarisWriter build_tarballs.jl

---

Q/Qt/build_tarballs.jl

We need the Qt static libraries to build GR binaries. Refer to discussions in:
https://github.com/JuliaPackaging/Yggdrasil/pull/2713
https://github.com/JuliaPackaging/Yggdrasil/pull/2704

[Qt] Keep the static libraries

---

C/CGAL/build_tarballs.jl

Minor patch, however it includes a stripped down archive without
docs and examples -- an archive nearly 5x smaller.  Even if not much,
this should still benefit slower or metered connections.

[CGAL] Update to v5.2.1

---

L/libpolymake_julia/libpolymake_julia@1.4/build_tarballs.jl

Tests with julia 1.3 (using #2745) seem fine, so lets continue.

[libpolymake_julia] update to 0.4.1, use compat (for julia 1.4)

---

E/eccodes/build_tarballs.jl

Updating ecCodes to version 2.21.0, which brings the WMO tables to version 26.0.0, among other improvements and bug fixes

Update ecCodes to 2.21.0

---

L/libsodium/build_tarballs.jl

This tries to copy #2732 for another library. 
This one, because running `julia build_tarballs.jl --help` on an ARM mac gives failures in BinaryBuilder > GitHub > SodiumSeal > libsodium. And because its version numbers aren't tied to those of the upstream source. 
See if this works?

[libsodium] Build for experimental platforms

---

A/ASL/build_tarballs.jl

I started to build Couenne, but it needed some `.hd` files like `opcodes.hd`.
@dpo is there a reason not to use https://github.com/ampl/asl? The archive from Netlib is semi-regularly updated, so it isn't reproducible.

[ASL] bump and export .hd files

---

M/METIS/METIS@4/build_tarballs.jl

@giordano @dpo @ViralBShah 
`HSL.jl` is the only Julia package to my knowledge that uses explicitly `METIS_jll` v4.0.3 in its `Project.toml`. Because `MA57` and `MA97` are not open source, we cannot build the libraries with Yggdrasil and use `METIS_jll` v4.0.3 as build dependency like it's done with the CoinOR `jll`. Therefore, `HSL.jl` is incompatible with other packages that require `METIS_jll` v5.1.0. `METIS_jll` v4.0.3 only contains static library whereas `METIS_jll` v5.1.0 contains dynamic one.
Related discussions :
- https://github.com/JuliaPackaging/Yggdrasil/pull/836
- https://github.com/JuliaPackaging/Yggdrasil/pull/530

Add a METIS4_jll

---

C/Coin-OR/Bonmin/bundled/patches/fix_dllexport.patch

When making https://github.com/JuliaPackaging/Yggdrasil/pull/2730, I missed some instances that are required for https://github.com/JuliaPackaging/Yggdrasil/pull/2772.

[bonmin] add missing dllexport in patch
