JuliaPackaging/Yggdrasil

- L/libcxxwrap_julia/build_tarballs.jl
New build based on Julia 1.6 (requires PR #1987 first). This also removes a call to `jlbacktrace`, which is not exported anymore in Julia 1.6 and therefore fails on Windows.
> [libcxxwrap-julia] Update for Julia 1.6

- O/OpenBLAS/OpenBLAS@0.3.13/build_tarballs.jl
- O/OpenBLAS/common.jl
We accidentally stopped setting `TARGET` completely by using `FLAGS`
instead of `flags`.
> Fix OpenBLAS using incorrect instructions

- 0_RootFS/Go/build_tarballs.jl
Minor follow up to https://github.com/JuliaPackaging/Yggdrasil/pull/2781.
After getting farther in compiling Kubernetes from source I discovered that part of the build process expected `gofmt` to be present. It is strange that a build process would require this but it's harmless to add.
> [RootFS] Include gofmt in Go compiler shard

- L/libcgal_julia/common.jl
- L/libcgal_julia/libcgal_julia@1.3/build_tarballs.jl
Includes new versioning system akin to libsingular_jll for the patch
version in order to permit both patches to the lib itself and encode the
julia version it is tied to.  Externalizes `preferred_gcc_version` into
a variable `gcc_version` as well.
> [libcgal-julia] Update v0.16.1 (Julia 1.3)

- J/JasPer/build_tarballs.jl
This PR adds a `build_tarballs.jl` for the [JasPer](https://github.com/jasper-software/jasper) library. 
It built successfully locally with no issues on linux and windows.
> add JasPer

- D/Dex/build_tarballs.jl
- D/Dex/bundled/patches/02-allow-multiple-refresh-tokens.patch
This updates Dex to v2.28.1.
In addition, this adds a patch to allow Dex, based on a configuration switch, to issue multiple refresh tokesn for the same user.
In the current design Dex stores a refresh token per user and connector. When a refresh token is encashed or when a new offline token is requested, Dex scans the offline sessions table for an existing offline session, retrieves the refresh token id from the offline sessions table, issues a new id token based on the data stored against the refresh token id, updates the refresh token, and returns the renewed id token and refresh token. Thus, the old refresh token is no longer valid.
With this change, if the option `enableMultiRefreshTokens` is set to `true` in the config (default is false), Dex would issue a new refresh token when a …
> update Dex to v2.28.1, patch for multiple sessions

- 0_RootFS/Rootfs/build_tarballs.jl
These aren't useful, and can screw up our git hashing algorithms
> [RootFS] Clear out `.git` directories

- Q/qr_mumps/build_tarballs.jl
This is the last time that I change the `shasum` for the release 3.0.2.
> [QR_MUMPS] Official release 3.0.2

- C/Coin-OR/Clp/build_tarballs.jl
- C/Coin-OR/coin-or-common.jl
x-ref: https://github.com/JuliaPackaging/Yggdrasil/pull/2831 and https://github.com/JuliaPackaging/Yggdrasil/pull/2834.
cc @tkralphs.
This PR:
* Rebuilds Clp with MUMPS5.2.1 to match Ipopt
* Adds the `clp` executable
* Modifies the version number to `v"100.1700.600"`.
Modifying the version number gives us some breathing room, because both Clp.jl and Cbc.jl use a version fixed to `v"1.17.6"`:
https://github.com/jump-dev/Clp.jl/blob/12542b098a901de55e44587966c11b563203fcd5/Project.toml#L17
Once this is merged, we should rebuild Cbc_jll to use the new version. I can also refactor #2834 to keep MUMPS5. Then rebuild Bonmin to use Cbc and Ipopt all using the same versions of things.
> [Clp] rebuild with MUMPS5 and modify version numbers

- C/Coin-OR/Cgl/build_tarballs.jl
- C/Coin-OR/coin-or-common.jl
In order to rebuild https://github.com/JuliaPackaging/Yggdrasil/pull/2831 with the new Clp version, I had to bump Cgl.
> [Cgl] rebuild Cgl without fixed Clp version

- 0_RootFS/gcc_common.jl
GCC on Darwin can't properly deal with certain feature detection macros,
so we'll help it out by manually disabling them for it.
> Manually disable `clock_gettime` in GCC builds for Darwin

- C/Coin-OR/Cbc/build_tarballs.jl
- C/Coin-OR/coin-or-common.jl
Talked to @tkralphs, who suggested some things to clean up the COIN-OR builds. 
Maybe a question for @giordano, what are the implications of adding new dependency? Do I have to bump a version? or can it be released as a `+N` version?
Ted: I had to add `--with-coindepend-lib` because it complained about missing Cgl otherwise, even though `--with-cgl-lib` was specified.
I tested this locally, and the AMPL Interface works:
```Julia
julia> model = Model(() -> AmplNLWriter.Optimizer(Cbc_jll.cbc))
A JuMP Model
Feasibility problem with:
Variables: 0
Model mode: AUTOMATIC
CachingOptimizer state: EMPTY_OPTIMIZER
Solver name: AmplNLWriter
julia> @variable(model, x >= 1)
x
julia> @objective(model, Min, 2x)
2 x
julia> optimize!(model)
CBC 2.10.5: 
julia> value(x)
1.0
julia> objective_value(model)
2.0 …
```
> [Cbc] expose cbc executable and add ASL interface

- C/Coin-OR/CoinUtils/build_tarballs.jl
- C/Coin-OR/coin-or-common.jl
With the ExecutableProduct in `Clp_jll` and the existing `CoinUtils_jll@2.11.4`, I get:
```Julia
julia> Clp_jll.clp() do exe
run(`$exe`)
end
dyld: Library not loaded: @rpath/libc++.1.dylib
Referenced from: /Users/oscar/.julia/artifacts/38d2a3c2c3ee4e798cb6bf60940d69f19ff59070/lib/libCoinUtils.3.11.4.dylib
Reason: image not found
```
However with `CoinUtils_jll@2.11.3` it works as expected. The LibraryProducts work with both 2.11.3 and 2.11.4.
Viral added 2.11.4 https://github.com/JuliaPackaging/Yggdrasil/pull/771, but then a few days later changed back to 2.11.3 https://github.com/JuliaPackaging/Yggdrasil/pull/783, I think just to sync things up with the old CoinUtilsBuilder package to get something working.
I would second https://github.com/JuliaPackaging/BinaryBuilder.jl/issues/1012, …
> [CoinUtils] rebuild 2.11.4

- C/Coin-OR/Bonmin/build_tarballs.jl
- C/Coin-OR/coin-or-common.jl
@tkralphs that seems to have done the trick:
```Julia
julia> using JuMP, AmplNLWriter, Bonmin_jll
julia> model = Model(() -> AmplNLWriter.Optimizer(Bonmin_jll.amplexe))
A JuMP Model
Feasibility problem with:
Variables: 0
Model mode: AUTOMATIC
CachingOptimizer state: EMPTY_OPTIMIZER
Solver name: AmplNLWriter
julia> @variable(model, x >= 0)
x
julia> @objective(model, Min, x)
x
julia> optimize!(model)
Bonmin 1.8.8 using Cbc 2.10.5 and Ipopt 3.13.4
bonmin: 
Cbc3007W No integer variables - nothing to do
******************************************************************************
This program contains Ipopt, a library for large-scale nonlinear optimization.
Ipopt is released as open source code under the Eclipse Public License (EPL).
For more information visit https://github.com/coin-or/Ipopt …
```
> [Bonmin] rebuild using latest versions

- .ci/Manifest.toml
- C/CompilerSupportLibraries/build_tarballs.jl
This should fix JuliaLang/julia#40375 which is due to the compiler shards containing `clock_gettime` symbol references which are not allowed for macOS < 10.12.  The fix to the GCC shards was made in #2836 and was integrated into BinaryBuilderBase in JuliaPackaging/BinaryBuilderBase.jl#134
> Bump BBB and CSL

- Q/Qt6Base/build_tarballs.jl
First pass for the the `Qt6Base` package for musl only, to be used as a `HostBuildDependency` for the other platforms. 
This Is The Way for the Qt 6 build system, see https://www.qt.io/blog/qt-6-build-system
> [Qt] Add Qt6Base package

- A/AMReX/build_tarballs.jl
[AMReX](https://github.com/AMReX-Codes/amrex) is a C++ package for block-structured AMR. Building it via BinaryBuilder is more convenient than other choices (Docker, Spack).
It doesn't have anything to do with Julia – I don't have immediate plans to provide a Julia wrapper for AMReX's C++ API, although that would be most useful. Please reject this pull request if non-Julia packages are not ([yet?](https://github.com/JuliaPackaging/BinaryBuilder.jl/issues/917)) welcome.
> AMReX: New package

- L/lrslib/build_tarballs.jl
Adds a `LibraryProduct` for `liblrsnash`, which will allow this JLL to be used by [JuliaPolyhedra/LRSLib.jl](https://github.com/JuliaPolyhedra/LRSLib.jl).
x-ref: https://github.com/JuliaPolyhedra/LRSLib.jl/issues/39
> [lrslib] Add LibraryProduct for `liblrsnash`

- I/Imath/build_tarballs.jl
This is a dependency of OpenEXR, which will be added once this is merged. Following that, the plan is to tweak the build for ImageMagick_jll to depend on OpenEXR. Then add OpenEXR support to FileIO.
> [Imath] new package

- L/lrslib/build_tarballs.jl
https://github.com/JuliaPolyhedra/LRSLib.jl/pull/40 CI is passing on version [0.1.0+3](https://github.com/JuliaPackaging/Yggdrasil/pull/2862) of `lrslib_jll`, and fails on earlier versions due to the lack of an `liblrsnash` LibraryProduct.  AFAIK, Julia package compatibility [specifiers](https://pkgdocs.julialang.org/v1/compatibility/) don't have a way of saying "version 0.1.0+3 or above," so we need a version bump to be able to require at least this version in LRSLib.jl's `Project.toml` (see https://github.com/JuliaPolyhedra/LRSLib.jl/pull/40).  Since this release adds more API (in the form of the new LibraryProduct), I think a bump to the [minor version](https://semver.org/#spec-item-7) makes sense, i.e., to `v"0.2.0"`.
> [lrslib] Bump version

- S/Serd/build_tarballs.jl
- S/serd/build_tarballs.jl
* Package name: serd
* Version: v0.30.10
> Wizard recipe: serd-v0.30.10

- U/UserNSSandbox/build_tarballs.jl
Turns out `musl`'s `realpath()` is not as flexible as `glibc`'s
> [UserNSSandbox] Bump version

- A/alsa/build_tarballs.jl
- A/alsa/bundled/patches/plugin_dir_no_DL.patch
I've getting a segfault when I try running the "runtests_local.jl" file in PortAudio...I'm hoping this might help?
```
julia> stream = PortAudioStream(2, 0)
signal (11): Segmentation fault
in expression starting at REPL[6]:1
snd_pcm_avail_update at /workspace/srcdir/alsa-lib-1.2.1.1/src/pcm/pcm.c:2929
unknown function (ip: 0x7ffc138e52df)
Allocations: 14490140 (Pool: 14484196; Big: 5944); GC: 13
fish: “/home/brandon/julia-1.6.0/bin/j…” terminated by signal SIGSEGV (Address boundary error)
```
> [ALSA] Bump version

- C/CUDA/CUDA_loader/build_10.0.jl
- C/CUDA/CUDA_loader/build_10.2.jl
- C/CUDA/CUDA_loader/build_11.0.jl
- C/CUDA/CUDA_loader/build_11.1.jl
- C/CUDA/CUDA_loader/build_11.2.jl
- C/CUDA/CUDA_loader/build_11.3.jl
- C/CUDA/CUDA_loader/build_9.0.jl
- C/CUDA/CUDA_loader/build_9.2.jl
- C/CUDA/CUDA_loader/build_tarballs.jl
This PR does some API exploration to figure out how a unified CUDA recipe would look; it's not intended to be functional (yet), as it needs additional features in BinaryBuilder.
IIUC, to use the new platform augmentation support, I need a single JLL that contains all the CUDA artifacts for each CUDA version (as opposed to the current CUDA_jll which attaches different artifacts to different versions of CUDA_jll), differentiated by the platform tag. There's a couple of problems with that:
- CUDA_jll pulls in the CUDA toolkit from CUDA_full_jll, which_does_ use package versions to select different versions of CUDA. I'd want to keep that, as it matches how we normally do this in Yggdrasil, but that means I can't have a single `dependencies` array (because it can't contain multiple versions of …
> Add a unified CUDA loader.

- D/Dex/bundled/patches/02-allow-multiple-refresh-tokens.patch
This updates the multiple sessions patch added in https://github.com/JuliaPackaging/Yggdrasil/pull/2820 to make the way it updates database records backwards compatible to older versions of Dex and those that do not have this patch.
> update Dex patch, make backward compatible

- I/Imath/build_tarballs.jl
Build with gcc5. As it is, openexr support can't be built into ImageMagick_jll.
> [Imath] build with gcc5

- 0_RootFS/gcc_common.jl
This is a newer support function that is not available on older macOS
builds
> [GCCBootstrap] Avoid `mkostemp` as well on macOS

- B/BerkeleyDB/build_tarballs.jl
A couple of platforms aren't working for me locally, but I wanted to see what happened here.
The version seems a very old but it's the version alpine uses; I think there might have been some licensing changes in newer versions
> [BerkeleyDB] Add builder

- C/CryptoMiniSat/build_tarballs.jl
- C/CryptoMiniSat/bundled/Yalsatpatch.patch
- C/CryptoMiniSat/bundled/feenablepatch.patch
There's a weird issue I can't really figure. On musl I get `/workspace/srcdir/cryptominisat/src/main_exe.cpp:34:5: error: ‘feenableexcept’ was not declared in this scope`. But if I inspect that section of the code I see it's in an `#if defined(__GNUC__) && defined(__linux__)` block. That seems like it shouldn't be defined on musl then to me?
> [CryptoMiniSat] Add Builder

- Q/Qt6Base/build_tarballs.jl
Before https://github.com/JuliaPackaging/BinaryBuilderBase.jl/pull/135 and
https://github.com/JuliaPackaging/BinaryBuilder.jl/pull/1036, some symlinks were
erroneously deleted from the tarballs.
> [Qt6Base] Rebuild

- M/MagicVLSI/build_tarballs.jl
Bumps MagicVLSI to 8.3.160 and fixes a relocation-related problem
that caused `magic --version` to hang rather than printing the
version, breaking downstream tooling.
> Bump MagicVLSI

- R/RDKit/build_tarballs.jl
updating only the git commit for the new build (memory leak fixed) since this is building dev functionality that won't be stable until Setp/Oct when the 2021.09 version will be released. We'll then replace the GitSource by an ArchiveSource.
So the auto build number the BinaryBuilder adds will work for now.
More info: 
https://greglandrum.github.io/rdkit-blog/technical/2021/05/01/rdkit-cffi-part1.html
https://chembl.blogspot.com/2021/05/julia-meets-rdkit.html
Thanks!
> [RDKit] update git commit

- O/OpenAL/build_tarballs.jl
Looks like OpenAL is eager to use new C++ features. This version needs a compiler that at least has full C++14 support. GCC 5 could be fine, but I bumped the version to 7 in case they use some C++17 features in the future.
> OpenAL: Bump version to 1.21.1 and integrate `PulseAudio_jll`

- N/ngspice/build_tarballs.jl
This is part of an experiment to use the julia package manager to
manage SPICE library files. The patches being included here allow
NgSpice.jl to register a callback to have julia resolve SPICE-side
library and include references using regular code loading.
> ngspice: Add some custom extensions

- O/obstack/build_tarballs.jl
Also changed the source because all of the changes in the fork repo are now merged to the original repo. 
The "musl" in the project name means it supports both glibc and musl, not musl-only.
> obstack: Enable all Linux build and bump version

- L/libsixel/build_tarballs.jl
- L/libsixel/bundled/patches/01-libsixel-win32.patch
`sixel_allocator_new` is expected to be a part of libsixel API
I've manually tested that it fixes the symbol issue in https://github.com/johnnychen94/Sixel.jl/issues/5 with `Libdl.dlsym` so should be a good patch. The upstream patch is in https://github.com/saitoha/libsixel/pull/151
> [patch] libsixel: export required missing symbol for the windows target

- C/CUDA/CUDA_loader/build_10.0.jl
- C/CUDA/CUDA_loader/build_10.1.jl
- C/CUDA/CUDA_loader/build_10.2.jl
- C/CUDA/CUDA_loader/build_11.0.jl
- C/CUDA/CUDA_loader/build_11.1.jl
- C/CUDA/CUDA_loader/build_11.2.jl
- C/CUDA/CUDA_loader/build_11.3.jl
- C/CUDA/CUDA_loader/build_9.0.jl
- C/CUDA/CUDA_loader/build_9.2.jl
- C/CUDA/CUDA_loader/build_tarballs.jl
- C/CUDNN/build_tarballs.jl
- C/CUTENSOR/build_tarballs.jl
Something fishy was going on; either because of changing the Platform objects in-place, or by calling `should_build_platform` on a non-augmented triple.
> [CUDA] Fix handling of augmented platforms.

- 0_RootFS/gcc_common.jl
When I [originally added MacOSX SDK 11.1](https://github.com/JuliaPackaging/Yggdrasil/pull/2436) I used a fork as the usual source did not yet have this version available.
> [RootFS] Use phracker MacOSX SDK 11.1

- D/Deno/build_tarballs.jl
Hi!
This changes the archive sources to [deno 1.10.1](https://github.com/denoland/deno/releases/tag/v1.10.1).
> [Deno_jll.jl] Bump deno to 1.10.1

- C/CompilerSupportLibraries/build_tarballs.jl
For example, for libgfortran5 libraries from GCC 10.2 are used.
Opening as draft to avoid it being merged by mistake, but I want @staticfloat opinion on this.  I was under the impression we wanted to use latest version of GCC libraries with `CompilerSupportLibraries`, `preferred_gcc_version=v"100"` is used in the first iteration of the build but not the second one.
Background: https://github.com/JuliaPackaging/BinaryBuilder.jl/issues/1055.
> [CompilerSupportLibraries] Use latest version of libraries

- F/flex/build_tarballs.jl
Building flux from release doesn't require help2man which is nice. Let's see if this builds for everyone. This should help with OpenFOAM
> [flex] Add builder

- P/P4est/build_tarballs.jl
This `build_tarballs.jl` is quite a mess, mainly due to adding support for Windows. p4est is being restructured these days, and will get a CMake build system. I hope once it is released, it'll reduce the amount of special cases present here.
> Update p4est to v2.3.1 and enable Windows build

- X/xsum/build_tarballs.jl
Note that this is a breaking change.  From the NEWS:
* *Changed default xsum_length type to ptrdiff_t (from int), so array
lengths on 64-bit systems will be accomodated, while still (hopefully)
being 32 bits in size on 32-bit systems.*
> update to xsum 2.0

- A/ADIOS2/build_tarballs.jl
- A/ADIOS2/bundled/patches/shlwapi.patch
- A/ADIOS2/bundled/scripts/as.llvm
I realized that I do need macOS support, and I found a work-around.
With the help of the ADIOS2 developers, Windows is now also working.
I don't intend to work on this any further in the near future (assuming that the created binary works).
> Make ADIOS2 build on macOS and Windows

- B/Bzip2/build_tarballs.jl
This version won't require Julia v1.6, to make it easier targeting a version of
Bzip2 which can be installed with all versions of Julia.
This pull request will be later reverted to have v1.0.8 as latest version.
> [Bzip2] Build old version v1.0.7 ABI-compatible with v1.0.8

- L/LAMMPS/build_tarballs.jl
* Package name: LAMMPS
* Version: v20201029.0.0
> Wizard recipe: LAMMPS-v20201029.0.0

- G/Glib/build_tarballs.jl
- G/Glib/bundled/patches/freebsd-have_xattr.patch
This requires a newer version of objcopy (binutils) in the builder environment to work
> [Glib] Upgrade builder to v2.68.1

- C/CompilerSupportLibraries/build_tarballs.jl
At the moment, some tarballs include extraneous libraries, for example
```console
% tar tzvf CompilerSupportLibraries.v0.4.3.x86_64-linux-musl-libgfortran5.tar.gz|grep 'lib/'
lrwxr-xr-x 0/0               0 1970-01-01 01:00 lib/libatomic.so -> libatomic.so.1.2.0
lrwxr-xr-x 0/0               0 1970-01-01 01:00 lib/libatomic.so.1 -> libatomic.so.1.2.0
-rwxr-xr-x 0/0          121584 1970-01-01 01:00 lib/libatomic.so.1.2.0
-rwxr-xr-x 0/0          580536 1970-01-01 01:00 lib/libgcc_s.so.1
lrwxr-xr-x 0/0               0 1970-01-01 01:00 lib/libgfortran.so -> libgfortran.so.5.0.0
lrwxr-xr-x 0/0               0 1970-01-01 01:00 lib/libgfortran.so.5 -> libgfortran.so.5.0.0
-rwxr-xr-x 0/0        11681536 1970-01-01 01:00 lib/libgfortran.so.5.0.0
lrwxr-xr-x 0/0               0 1970-01-01 01:00 …
```
> [CompilerSupportLibraries] Remove extraneous libraries

- L/libpng/build_tarballs.jl
Switch the build system from CMake to Autoconf because the autodetection of ARM NEON for `aarch64-apple-darwin` (Apple Silicon, M1 CPU) at build time works with the latter but not the former system.
> [libpng] Build for experimental platforms

- C/Ccluster/build_tarballs.jl
- P/PTSCOTCH/build_tarballs.jl
- P/PTSCOTCH/bundled/patches/Makefile.patch
- P/PTSCOTCH/bundled/patches/OSX_FreeBSD.patch
- P/PTSCOTCH/bundled/patches/Windows.patch
- P/PTSCOTCH/bundled/patches/native_build.patch
I'm not sure this is the best way to do this, if we had multi-jll builders that would be best. Right now I just build scotch and ptscotch but only copy ptscotch to the prefix.  The build script is otherwise exactly the same as SCOTCH_jll.
> [PTSCOTCH] Add Builder

- L/libpng/build_tarballs.jl
Pass option `PNG_ARM_NEON=on` to CMake when targeting `aarch64-apple-darwin` to
let it know the platforms has the NEON extension.
Additionally, this should avoid breaking the ABI of the library on Windows by changing its soname, as it happened when [switching to Autoconf](https://github.com/JuliaBinaryWrappers/libpng_jll.jl/commit/b778f2a3aa2c3b32142f3fb519ecf5ad45edca2a#diff-7b45cff429f8c49eb84a6a0cb9f24cf87ab0923b409bb51ba9172d49aa44e1b6)
> [libpng] Go back to building with CMake

- L/libpolymake_julia/libpolymake_julia@1.6/build_tarballs.jl
rebuild to make sure that this is really built with polymake 4.4
#3057 was built with 4.3 because the registry from the pkgserver was not up-to-date
after #3065
> [libpolymake_julia] bump for 4.4 (see #3057) for julia 1.6

- C/Cairo/build_tarballs.jl
- C/Cairo/bundled/patches/mingw-libssp.patch
Note to self: Windows builds were failing with
```
[01:33:47] /opt/x86_64-w64-mingw32/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../../x86_64-w64-mingw32/bin/ld: .libs/cairo-output-stream.o: in function `memcpy':
[01:33:47] /opt/x86_64-w64-mingw32/x86_64-w64-mingw32/sys-root/include/string.h:202: undefined reference to `__memcpy_chk'
[01:33:47] /opt/x86_64-w64-mingw32/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../../x86_64-w64-mingw32/bin/ld: .libs/cairo-win32-font.o: in function `memcpy':
[01:33:47] /opt/x86_64-w64-mingw32/x86_64-w64-mingw32/sys-root/include/string.h:202: undefined reference to `__memcpy_chk'
[01:33:47] /opt/x86_64-w64-mingw32/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../../x86_64-w64-mingw32/bin/ld: .libs/cairo-pdf-interchange.o: in function `strcat': …
```
> [Cairo] Build for aarch64-apple-darwin

- N/NOMAD/build_tarballs.jl
NOMAD_jll is not working with FreeBSD (https://github.com/bbopt/NOMAD.jl/issues/40)
> [NOMAD] Use Clang for OSX and FreeBSD platforms

- L/LibMPDec/build_tarballs.jl
- L/LibMPDec/bundled/patches/01-libname-windows.patch
- L/LibMPDec/bundled/patches/02-linker-cc.patch
* Package name: LibMPDec
* Version: v2.5.1
> Wizard recipe: LibMPDec-v2.5.1

- P/P4est/build_tarballs.jl
- P/P4est/bundled/patches/fix-bad-ftell-return-value-windows.patch
This adds a hotfix for the different behavior of `fopen`/`ftell` under Windows, resolving the issue reported in https://github.com/cburstedde/p4est/issues/113.
I realize that it's frowned upon to create new builds for an already released version, but it's a blocking issue for us at the moment (preventing us to use `P4est_jll` on Windows) and from what I can tell, no actual harm is done (it's not breaking any existing use of `P4est_jll` since the current version is unusable on Windows when trying to use the p4est output routines). Also, considering the past release frequency of the upstream project (approximately once every 2 years), I'd rather not wait for a proper patch release (at least in this particular case).
> Hotfix for p4est output routines on Windows

- P/P4est/build_tarballs.jl
- P/P4est/bundled/patches/fix-end-of-file-detection-windows.patch
This fixes https://github.com/cburstedde/p4est/pull/115 until a new release of the upstream library with the fix is available.
It's a bug that can only appear on Windows due to `toupper(EOF)` being undefined behavior, whereas on Linux/macOS/BSD, `toupper(EOF) == EOF`.
By moving the check for `EOF` before the conversion `toupper`, the relevant code section works as intended and independent of the platform.
> Fix EOF detection for p4est on Windows

- U/unpaper/build_tarballs.jl
and get the threadsafe method. 6.1 is still the latest release, or I'd just upgrade it for real.
> [unpaper] build for experimental platforms

- G/GRAMPC/build_tarballs.jl
This adds a builder for the GRAMPC optimal control solver library. It actually will build the wrapper library https://github.com/JuDO-dev/grampc_julia_wrapper becase the upstream library was written in a way that made using it as a shared library very difficult (hard-coded error handling by calling `exit` and requiring the callbacks to be statically compiled into the library itself are the two biggest issues).
This does technically have a dependency on `libjulia` because I use the `jl_error` and `jl_errorf` functions to throw Julia errors when they occur in the library (as the replacement of calling `exit`). These functions should ideally be version-agnostic since their API hasn't changed much - so this isn't too much of a maintenance burden for that.
> Add builder for GRAMPC optimal control solver

- F/FGlT/build_tarballs.jl
Hello! This pull-request contains the recipe needed for building the [Fast Graphlet Transform](https://github.com/fcdimitr/fglt) implementation. The binaries are required for [FGLT.jl](https://github.com/nsailor/FGLT.jl).
The source code takes advantage of `cilk` or `openMP` for parallelism. These are "optional" dependencies in the FGlT package, the code can be compiled for sequential execution if none is available.
What is the best way to check on which framework is used on each platform?
Many thanks in advance!
> FGlT v1.0.0 

- S/SCIP/build_tarballs.jl
There shouldn't be much surprise, preparing the SCIP_jll for 7.0.3
> bumping scip to 7.0.3 beta

- M/mlpack/build_tarballs.jl
- M/mlpack/bundled/patches/count-categories.patch
It was recently discovered in mlpack/mlpack#2973 that mlpack's Julia bindings segfault when a user is trying to learn a model on categorical data.  This was traced to a fairly simple patch, but, a new mlpack release is not coming soon since the library is currently in a heavy state of refactoring to reduce its dependencies.
Therefore, I took the relevant patch from that PR and backported it into the `mlpack_jll` package here.
One thing I am not sure of is whether I need to bump the package version from 3.4.2 so that Julia will automatically update the package.  If so, I'd bump it to something like 3.4.2-1, but I think that is not a valid Julia version number... someone please correct me with whatever the right thing is here. :)
> Patch categorical support for mlpack

- X/XyceWrapper/build_tarballs.jl
- X/XyceWrapper/src/CMakeLists.txt
- X/XyceWrapper/src/xycelib.cpp
We are working on a high-level Julia wrapper over Xyce, to complement Xyce_jll that is part of Yggdrasil already. However, the Xyce API is C++ so using CxxWrap requires building a native extension that can be used from Julia.
This extension currently requires manual building inside https://github.com/JuliaComputing/Xyce.jl/ which is not user friendly at all. So we'd like to get this wrapper in Yggdrasil as well so people can just `] add Xyce.jl` and start simulating.
> Xyce wrapper

- X/XyceWrapper/src/xycelib.cpp
The `set_report_handler` function I added in the last minute in the previous PR is not actually usable from Julia. Very sorry about the noise.
The purpose of this function is simply to avoid Xyce aborting the Julia runtime on an error, so I just hardcoded it. I have now properly tested this in Xyce.jl: https://github.com/JuliaComputing/Xyce.jl/blob/7a2bff1f037dff2f4173e49bcdb60787a2daac61/src/Xyce.jl#L9
> XyceWrapper: hardcode non-aborting report handler

- L/Libiconv/build_tarballs.jl
It'll enable more encodings with libiconv. Not sure if I need to bump version by adding metadata like `+20210614` to trigger a new package build on Yggdrasil.
> Enable extra encodings for libiconv

- H/HOHQMesh/build_tarballs.jl
Add a build recipe to distribute [HOHQMesh](https://github.com/trixi-framework/HOHQMesh), the High Order Hex-Quad Mesh (HOHQMesh) package to automatically generate all-quadrilateral meshes with high order boundary information, via the Julia package system.
While this is the initial version of a registered HOHQMesh_jll package in Yggdrasil, we have had an unregistered version for testing purposes at https://github.com/trixi-framework/HOHQMESH_jll.jl, from which also this `build_tarballs.jl` script is derived.
> Add build recipe for creating HOHQMesh_jll (v1.0.0)

- C/Coin-OR/MibS/build_tarballs.jl
- C/Coin-OR/coin-or-common.jl
Probably still a WIP, but let's see what the damage is on some other platforms.
This targets 
- MibS 1.1.3 https://github.com/coin-or/MibS/commit/4b7ec93c4bd1d6a978deff9987cf1df74f6598d3
- SYMPHONY https://github.com/coin-or/SYMPHONY/commit/c0a755011ea2430f3465927ef29820933ddf3f2f
- CHiPPS-ALPS https://github.com/coin-or/CHiPPS-ALPS/commit/5b1a0b524979764d6ca929446762762712c035bb
- CHiPPS-BiCePS https://github.com/coin-or/CHiPPS-BiCePS/commit/bb7c56ef1bc91624a1dbee8c2f7da7246a0933ed
- CHiPPS-BLIS https://github.com/SaTahernejad/CHiPPS-BLIS/commit/b714e6af651704d0b019ad4495cbbe7529fbdb17
<s>It's probably easiest to keep them bundled together like this for now. We can split of SYMPHONY as a separate solver at some point if there is interest, or if we start building other COIN software with …
> [MibS] add a build script for coin-or/Mibs

- L/libmicrohttpd/build_tarballs.jl
* Package name: libmicrohttpd
* Version: v0.9.73
> Wizard recipe: libmicrohttpd-v0.9.73

- C/Coin-OR/Cbc/build_tarballs.jl
MibS failed to install because it was missing this library: https://github.com/JuliaRegistries/General/pull/39121
> [Cbc] Export libOsiCbc library

- H/Hwloc/build_tarballs.jl
Copies changes made for example here https://github.com/JuliaPackaging/Yggdrasil/pull/2892, by copying numbers from https://www.open-mpi.org/software/hwloc/v2.5/ . I have not tried to build or test anything locally. 
Tracking issue https://github.com/JuliaPackaging/Yggdrasil/issues/2763, also https://github.com/JuliaParallel/Hwloc.jl/issues/44
> [Hwloc] Build for experimental platforms

- L/Libiconv/build_tarballs.jl
After JuliaPackaging/Yggdrasil#3195, let's go back to the up-to-date version
> Revert "[Libiconv] Backport extra encodings to old Julia versions"

- Q/QPALM/build_tarballs.jl
It's a bit silly that there's a source file in the jl package that's necessary for the Julia interface. I didn't notice the first time around. Hopefully, that will be restructured in the near future.
> QPALM v0.1.1

- F/faust/build_tarballs.jl
- F/faust/bundled/patches/disable_interp.patch
- F/faust/bundled/patches/execinfo.patch
- F/faust/bundled/patches/rt.patch
- F/faust/bundled/patches/set_llvm_libs.patch
- F/faust/bundled/patches/set_llvm_libs_musl_cxx03.patch
- F/faust/bundled/patches/windows-microhttpd.patch
- F/faust/bundled/patches/ws2.patch
This adds the [Faust](https://faust.grame.fr/) DSP compiler. I endeavored to get all platforms building successfully; am currently in the process of developing a wrapper [Faust.jl](https://github.com/corajr/Faust.jl) around Faust's LLVM IR generation.
> [faust] add Faust compiler v2.32.16

- F/flux_core/build_tarballs.jl
- M/mpv/build_tarballs.jl
On Windows, Lua uses its major and minor version as part of the DLL name, so updating Lua_jll to use a newer version of Lua can break packages that depend on it.
[skip ci] [skip build]
> Set compat for packages using Lua_jll

- X/XyceWrapper/build_tarballs.jl
- X/XyceWrapper/src/xycelib.cpp
Since Xyce 7.3 it is no longer possible to add output handlers after calling `initialize` but this needs to be done with these methods that were added.
The corresponding CxxWrap change: https://github.com/JuliaComputing/Xyce.jl/commit/f0940ce24c6eaeda8b516e2d99d34e11dd1bff23
> Add methods needed for Xyce 7.3 initialisation

- B/Blosc2/build_tarballs.jl
c-Blosc2 was released today at v2.0.0. This updates c-Blosc2 to https://github.com/Blosc/c-blosc2/commit/bd0b1105c1e81071f8d04720514a510e8ec403c5 corresponding to the v2.0.0 release tag.
https://github.com/Blosc/c-blosc2/releases/tag/v2.0.0
> Update c-Blosc2 to v2.0.0 release

- .ci/Manifest.toml
- L/LLVM/LLVM_full@12.0.0/build_tarballs.jl
- L/LLVM/LLVM_full@12.0.0/bundled/patches/0708-Do-not-patch-FDE-symbols-on-AArch64.patch
- L/LLVM/LLVM_full@12.0.0/bundled/patches/0709-Force-.eh_frame-emission-on-AArch64.patch
Splitting out the LLVM 12 patches from #3063
> [LLVM_full@12] Add LLVM AArch64 unwind patches

- L/Libxc/build_tarballs.jl
Needed for Libxc support in Quantum Espresso (see https://github.com/JuliaPackaging/Yggdrasil/pull/3229).
> Enable fortran interface for Libxc

- L/Libxc/build_tarballs.jl
Required to solve build issues in #3247.
> Change minimal GCC version for Libxc to 5

- Q/QuantumEspresso/build_tarballs.jl
- Q/QuantumEspresso/bundled/patches/0001-libxc-prefix.patch
Build currently fails due to mismatching FORTRAN versions, error message:
```
Fatal Error: Cannot read module file 'xc_f90_lib_m.mod' opened at (1), because it was created by a different version of GNU Fortran
```
I suppose the solution is to also bump the GCC version when building Libxc ... or is there something more clever that can be done @giordano ?
> Add Libxc and Scalpack support to QuantumEspresso

- D/DirectQhullHelper/build_tarballs.jl
* Package name: DirectQhullHelper
> Wizard recipe: DirectQhullHelper-v0.1.0

- O/OpenMPI/build_tarballs.jl
- O/OpenMPI/bundled/aarch64-linux-gnu
- O/OpenMPI/bundled/aarch64-linux-musl
- O/OpenMPI/bundled/arm-linux-gnueabihf
- O/OpenMPI/bundled/arm-linux-musleabihf
- O/OpenMPI/bundled/i686-linux-gnu
- O/OpenMPI/bundled/i686-linux-musl
- O/OpenMPI/bundled/powerpc64le-linux-gnu
- O/OpenMPI/bundled/x86_64-apple-darwin14
- O/OpenMPI/bundled/x86_64-linux-gnu
- O/OpenMPI/bundled/x86_64-linux-musl
- O/OpenMPI/bundled/x86_64-unknown-freebsd11.1
On FreeBSD we're hitting https://github.com/JuliaPackaging/BinaryBuilderBase.jl/issues/158, so registration of this package actually failed on `master`
> [OpenMPI] Expand gfortran versions and use LLVM 11

- L/libjulia/common.jl
- L/libjulia/libjulia@1.7/build_tarballs.jl
- L/libjulia/libjulia@1.7/bundled/patches/0001-skip-dsymutil-segfaults.patch
This is work in progress; I figure there'll be problems, but we
will need this to rebuild CxxWrap for 1.7 (otherwise everything
using CxxWrap will segfault there)﻿
> libjulia_jll 1.7

- L/libjulia/libjulia@1.7/build_tarballs.jl
- L/libjulia/libjulia@1.7/bundled/patches/0002-support-julia-h.patch
Taken from https://github.com/JuliaLang/julia/pull/41308, this is necessary in order to actually build C code against libjulia.
> Backport fix for Julia 1.7.0-beta2 headers

- Z/ZITSOL_1/build_tarballs.jl
Github ZITSOL code includes some cleanup and bug fixes to the ZITSOL tar package. CMake build added to Github repository.
> [ZITSOL_1] Changed source code to use GitHub repository instead ITSOL tar package.

- L/libjulia/common.jl
- L/libjulia/libjulia@1.7/build_tarballs.jl
... not just a build dependency, so that `uv.h` is present when including
`julia.h`, which is necessary.
<s>Also add an option third argument to build_julia to allow us to decouple
the Julia version (such as 1.7.0-beta2) from the version of the
JLL (which must not contain a prerelease part).
We then use this to assign the version 1.7.1 to this latest libjulia_kll build.
</s>
> libjulia 1.7: turn libuv into a dependency

- L/libjulia/libjulia@1.7/build_tarballs.jl
- L/libjulia/libjulia@1.7/bundled/patches/0003-exports.patch
These symbols will be back in beta3. For now, adding them here should
allow us to build libcxxwrap for julia 1.7, and then proceed to adapt
dependent JLLs. Even though the resulting binaries won't work with
Julia 1.7-beta2, this still seems useful, as (a) it allows us to prepare
for -beta3 *now*, and (b) the resulting binaries probably will work
with Julia nightly builds.
> libjulia 1.7: export two "missing" symbols

- C/Coin-OR/SHOT/build_tarballs.jl
- C/Coin-OR/SHOT/bundled/patches/0001-Fix-whole-archive-linker-options-for-macOS.patch
- C/Coin-OR/SHOT/bundled/patches/0002-cmake.patch
```
[05:31:30] /workspace/srcdir/SHOT/src/Model/../Model/Simplifications.h:1370:26: error: 'value' is unavailable: introduced in macOS 10.14
[05:31:30]                 optional.value()->coefficient *= -1.0;
[05:31:30]                          ^
[05:31:30] /opt/x86_64-apple-darwin14/x86_64-apple-darwin14/sys-root/usr/include/c++/v1/optional:947:27: note: 'value' has been explicitly marked unavailable here
[05:31:30]     constexpr value_type& value() &
[05:31:30]                           ^
```
```
[05:43:58] CMake Error at misc/FindFilesystem.cmake:61 (message):
[05:43:58]   No C++ support for std::filesystem
[05:43:58] Call Stack (most recent call first):
[05:43:58]   CMakeLists.txt:23 (find_package)
```
> [SHOT] first pass at a builder

- P/pandoc/build_tarballs.jl
Since the newer versions use `2.14.0.1` instead of `2.14.1`, I decided to just go for a slightly older version, that is, `2.14`.
> [Pandoc] Version 2.14

- C/CGAL/build_tarballs.jl
CGAL is now purely header-only, producing no shared libraries anymore.
Additionally, it now only supports GCC/G++ >=8.3, leading to a change in
the preferred gcc version.  Furthermore, I also opted for adding
`compat` entries to GMP and MPFR in accordance to CGAL's manual despite
it not mattering much since the specified versions are well within
acceptable bounds.
Furthermore, I was looking into pulling more optional dependencies such
as Eigen.  However, if they're optional and CGAL is now header-only, I'm
assuming these will mostly matter when building whatever depends on
CGAL, having that specific dependent pull in the optional dependencies.
This, alas, leads to every dependent pulling optional dependencies over
and over again, but it also means one isn't pulling a tree of
unnecessary …
> [CGAL] Update to v5.3

- O/openPMD_api/build_tarballs.jl
This corrects a subtle error in the upstream repository, which uses template specializations to determine whether a given type `T` is a `std::array<T,N>`. Before, this matching would give different results on different operating systems; now it always returns the same result.
> openPMD_api: Update upstream

- C/CGAL/build_tarballs.jl
Zlib is not required by CGAL unless one is interested in image I/O
functionality.  As such, it should be required by dependants who need it
instead of further blowing up CGAL_jll's dependency graph.
> [CGAL] Remove unnecessary dependency

- L/libserialport/build_tarballs.jl
Use lastest master to fix https://github.com/JuliaIO/LibSerialPort.jl/issues/84
I'm not sure why/when the `--with-include-path=` was added, but the build complains that this isn't used, so I removed it.
> Update libserialport to latest master

- G/Giflib/build_tarballs.jl
- G/Giflib/bundled/patches/makefile.patch
At the moment this only works on Linux and FreeBSD because upstream replaced the
previous autoconf-based build system with a hand-written Makefile which works
only on those platforms...
See https://sourceforge.net/p/giflib/bugs/133/ for inspiration about how to
patch the Makefile to build the library on the other platforms.
> [Giflib] Upgrade to v5.2.1 and build for experimental platforms

- B/bitwarden_cli/build_tarballs.jl
I'm using the Bitwarden CLI in a GitHub job to run backups for my passwords. Specifically, via a scheduled GitHub Actions cronjob it:
1. Exports passwords as JSON
2. Encrypts the json via OpenSSL
3. Runs a "website publishing" Action to put the backup in a separate branch (`backup` instead of `gh-pages`)
I figured that I can just as well build a Julia wrapper around the Bitwarden CLI since it has 1.2k stars (https://github.com/bitwarden/cli).
> [bitwarden_cli] Add version 1.17.1

- R/ROCmCompilerSupport/build_tarballs.jl
- R/ROCmCompilerSupport/bundled/patches/disable-1031.patch
- R/ROCmCompilerSupport/bundled/patches/disable-bc2h.patch
- R/ROCmCompilerSupport/bundled/patches/disable-tests.patch
In theory I don't need LLVM_full, but the other LLVM packages don't have LLD, which is needed for this package.
> [New package] Add ROCmCompilerSupport 4.0.0

- .ci/Manifest.toml
Changes:
* BinaryBuilderBase: https://github.com/JuliaPackaging/BinaryBuilderBase.jl/compare/v0.6.11...v0.6.12
> [AZP] Update  BinaryBuilderBase

- L/libpolymake_julia/common.jl
- L/libpolymake_julia/libpolymake_julia@1.7/build_tarballs.jl
Changed to gitsource to include one small change for julia 1.7, but we can keep that `0.4.(1*100+10+julia.minor)` version number.
> [libpolymake_julia] build for julia 1.7

- L/libcgal_julia/common.jl
- L/libcgal_julia/libcgal_julia@1.3/build_tarballs.jl
This includes an update to CGAL v5.3 (which just dawned on me that, CGAL now being header-only, a build of libcgal-julia for every CGAL patch is now required... not terribly fun).  Also discards the externalized `gcc_version` for preferred gcc version, fixing it to v9.  Finally, it pins libcxxwrap-julia's build version.
> [libcgal-julia] Update to v0.17 (julia 1.3)

- R/ROCmOpenCLRuntime/build_tarballs.jl
- R/ROCmOpenCLRuntime/bundled/patches/musl-opencl.patch
- R/ROCmOpenCLRuntime/bundled/patches/musl-rocclr.patch
- R/ROCmOpenCLRuntime/bundled/patches/rocclr-install-prefix.patch
These packages are the last dependencies of ROCm's HIP. I'm building both in the same build script because they are pretty tightly intertwined, and were too annoying to split up. I'd be happy to split them in the future if for some reason people want one and not the other.
> [New package] Add ROCm-OpenCL-Runtime and ROCclr 4.0.0

- L/libcgal_julia/libcgal_julia@1.4/build_tarballs.jl
Should be merged after jll for 1.3 is registered, i.e., JuliaRegistries/General#40868 is merged.
> [libcgal-julia] Update to v0.17 (julia 1.4)

- L/libcgal_julia/libcgal_julia@1.5/build_tarballs.jl
Should be merged after #3334 and consecutive jll (JuliaRegistries/General#40879) is registered.
> [libcgal-julia] Update to v0.17 (julia 1.5)

- R/rocminfo/build_tarballs.jl
ROCm tool used when building with hipcc (ref #3338 ), and just generally useful for system monitoring.
> [New package] Add rocminfo_jll 4.0.0

- R/rocm_cmake/build_tarballs.jl
Needed to locate ROCm components when building HIP-derived libraries
> [New package] Add rocm_cmake_jll 4.0.0

- L/libcgal_julia/libcgal_julia@1.6/build_tarballs.jl
Should be merged after #3335 and consecutive jll (JuliaRegistries/General#40883) is registered.
> [libcgal-julia] Update to v0.17 (julia 1.6)

- L/libcgal_julia/common.jl
- L/libcgal_julia/libcgal_julia@1.7/build_tarballs.jl
Should be merged after #3336 and consecutive jll (JuliaRegistries/General#40888) is registered.
> [libcgal-julia] Update to v0.17 (julia 1.7)

- P/PETSc/build_tarballs.jl
- P/PETSc/bundled/patches/petsc_name_mangle.patch
- Upgrades PETSc to 3.15.2
- Allows for 8 different build options:
- Scalar Types: `complex` and `real`
- Real Types: `Float64` and `Float32`
- Int Types: `Int32` and `Int64`
The libraries named:
- `libpetsc_Float64_Real_Int64`
- `libpetsc_Float32_Real_Int64`
- `libpetsc_Float64_Complex_Int64`
- `libpetsc_Float32_Complex_Int64`
- `libpetsc_Float64_Real_Int32`
- `libpetsc_Float32_Real_Int32`
- `libpetsc_Float64_Complex_Int32`
- `libpetsc_Float32_Complex_Int32`
Additionally, there is a library `libpetsc` which is the same as `libpetsc_double_real_Int32` (the current default version of `PETSc_jll`).
> [PETSc] Upgrades petsc to 3.15.2 and enables multiple precision, scalar, and int types

- L/libclangex/build_tarballs.jl
@vchuravy, using `LLVM_full_jll` instead of `Clang_jll` seems to work fine. I'd like to do some tests on Windows, and it's OK to use `LLVM_full_jll` at the moment.
> libclangex: Fix RPATH

- L/libcgal_julia/libcgal_julia@1.5/build_tarballs.jl
Should not be merged before #3344 and subsequent jll registry.
> [libcgal-julia] Fix gcc version (julia 1.5)

- R/ROCmCompilerSupport/build_tarballs.jl
- R/ROCmCompilerSupport/bundled/patches/fix-objdump-clopt.patch
Fixes an LLVM CommandLine conflict due to Julia's usage of LLVM.
Thanks to @staticfloat for helping solve this!
> [ROCmCompilerSupport_jll] Disable -h flag in comgr-objdump

- R/ROCmOpenCLRuntime/build_tarballs.jl
- R/ROCmOpenCLRuntime/bundled/patches/rocclr-disable-initial-exec.patch
Since musl doesn't support it.
> [ROCmOpenCLRuntime_jll] Disable initial-exec TLS model

- 0_RootFS/Rootfs/bundled/libs/csl/download_csls.sh
These are the changes in the script to build the RootFS included in https://github.com/JuliaPackaging/BinaryBuilderBase.jl/pull/157
> [Rootfs] Fix script to download `CompilerSupportLibraries_jll`

- S/Sundials/Sundials@5/build_tarballs.jl
- S/Sundials/bundled@5/patches/Sundials_findklu_suffixes.patch
- S/Sundials/bundled@5/patches/Sundials_lapackband.patch
~@staticfloat since this is for Julia v1.7 only, we might actually target
libblastrampoline instead of OpenBLAS.  Do we only need to use that as
dependency instead of OpenBLAS and point the build system to
`libblastrampoline.${dlext}` and that's it?~  nevermind, I think this needs lapack more than blas
CC: @ChrisRackauckas
> [Sundials] Build for Julia v1.7

- L/libnode/build_tarballs.jl
NodeJS does not have an official distribution of shared libraries, so we have to compile it manually.
I mainly intend to use `libnode` in my attempt to embed NodeJS in Julia. There are two packages related:
- [`jlnode`](https://github.com/sunoru/jlnode) wraps some functions to let NodeJS and Julia communicate more easily.  I will submit another package `libjlnode_jll` after this PR is merged.
- [`NodeCall.jl`](https://github.com/sunoru/NodeCall.jl) makes use of `libjlnode_jll` to run an embedded NodeJS instance in the Julia's process, and we can then simply use javascript in julia. It will be very handy to use npm packages in Julia.
v14.17.3 is the latest one of LTS versions, which imo could be a good choice to be used here. I successfully build it on my own computer (x86_64-linux-glibc) …
> Build NodeJS v14.17.3 as a shared library.

- L/libcleri/build_tarballs.jl
Hello, this PR adds a new recipe for the libcleri C library, currently directed to v0.12.1 from https://github.com/transceptor-technology/libcleri/tree/0.12.1. I am adding it as a build dependency of my repo at https://github.com/libAtoms/extxyz, for which a build recipe will be coming shortly, since I understood that it was preferable to have a single library in each recipe.
This recipe builds correctly on all but two platforms:
- Linux armv7l {call_abi=eabihf, libc=musl}
- Linux armv7l {call_abi=eabihf, libc=glibc}
The error on armv71 is an internal compiler error, details pasted below. For now I simply skipped these platforms, but I'm happy to revisit, for example with newer compiler versions, if that would be preferable.
```
[22:19:03] make: Entering directory …
```
> New Recipe: libcleri v0.12.1

- G/GAP/GAP@1.7/build_tarballs.jl
[skip build]
[skip ci]
I'm trying to fix this in the registry in https://github.com/JuliaRegistries/General/pull/41585 so this PR is just meant to ensure the next time I update this JLL, it is done right.
> Fix julia_compat for GAP_jll for Julia 1.7

- P/pugixml/build_tarballs.jl
Pugixml is a non-validating XML parser that it is several times faster than libxml2. So it would be a good addition to the julia ecosystem.
It seems that it was correctly built for linux x86_64 glibc, not sure about the other platforms.
> New Recipe: pugixml v1.11.0

- L/libcleri/build_tarballs.jl
My initial build, merged in #3382, did not include `@rpath` in its `install_name`, so was not easy to link to in dependent libraries.
I've also removed the change to GCC v5 since this proved to be unnecessary, so better to stick with the older and more compatible default GCC v4.8.5.
> Fix install_name of libcleri.dylib on MacOS builds

- E/extxyz/build_tarballs.jl
This recipe is for v0.1.0 of my extxyz C library, available from https://github.com/libAtoms/extxyz. I've tested it locally on x86_64-linux-gcc and x86_64-apple-darwin, but will use CI to test on all other supported platforms.
> New recipe for extxyz library

- C/cif_api/build_tarballs.jl
- C/cif_api/bundled/patches/mingw-remove-install-hook.patch
This PR adds a `build_tarball.jl` for [cif_api](https://github.com/COMCIFS/cif_api).
This is what comes out of the wizard for me on a `x86_64-mingw-*` platform, `*-linux-*` still needs some tinkering but I wanted to see how the other platforms do as well.
Closes #2680
> add cif_api

- G/Graphene/build_tarballs.jl
Need to build a new version of Glib because we need https://gitlab.gnome.org/GNOME/glib/-/commit/2c97526c006b22110f013dfc13ddf55e032e4ec8.  Sigh
> [Graphene] Upgrade to v1.10.6 and build for experimental platforms

- O/OpenMPI/build_tarballs.jl
We need a more capable compiler in order to build the Fortran F08 module also
for libgfortran3.
> [OpenMPI] Require at least GCC 5

- O/openPMD_api/build_tarballs.jl
We're still using a git checkout from a feature branch for the Julia bindings, but this branch is now based on the 0.14 release.
> [openpmd_api]: Update to new version 0.14

- O/OpenEXR/build_tarballs.jl
Provides a new, vastly richer C API on which https://github.com/twadleigh/OpenEXR.jl will be updated to depend.
> Bump OpenEXR: v3.0.1 -> v3.1.1.

- E/Eigen/build_tarballs.jl
Let's see what happens. I got `LoadError: Unable to automatically install 'GCCBootstrap-x86_64-linux-musl.v10.2.0.x86_64-linux-musl.unpacked` so let's see what this does. 
Also is empty products intentional?
> [Eigen] Build for Experimental Platforms

- S/SPIRV_Tools/build_tarballs.jl
Upstream doesn't bother tagging a release of SPIRV-Headers (https://github.com/KhronosGroup/SPIRV-Headers/issues/199), so vendor own own copy (https://github.com/KhronosGroup/SPIRV-Tools/pull/4444) so that we can finally upgrade SPIRV-Tools (it doesn't compile with the tagged headers).
> Bump SPIRV-Tools to v2021.2, vendor SPIRV-Headers.

- Y/Yosys/build_tarballs.jl
This adds support for building Yosys, the open source synthesis suite for FPGAs and ASICs.
> [Yosys] init

- H/HiGHS/build_tarballs.jl
Closes #3431
cc @galabovaa 
The error was because of this use of `target_link_libraries`:
https://github.com/ERGO-Code/HiGHS/pull/369/commits/086b075aa8854f41b0c65c3283bee8bdd3b9b2dd
but even when I fixed that, I ran into another error
```
[ 99%] Linking CXX shared library ../lib/libhighs.so
cd /workspace/srcdir/HiGHS/build/src && /usr/bin/cmake -E cmake_link_script CMakeFiles/libhighs.dir/link.txt --verbose=true
/opt/bin/x86_64-unknown-freebsd11.1-libgfortran3-cxx03/x86_64-unknown-freebsd11.1-clang++ --sysroot=/opt/x86_64-unknown-freebsd11.1/x86_64-unknown-freebsd11.1/sys-root/ -fPIC -O3 -DNDEBUG  -shared -Wl,-soname,libhighs.so -o ../lib/libhighs.so CMakeFiles/libhighs.dir/__/extern/filereaderlp/reader.cpp.o CMakeFiles/libhighs.dir/io/Filereader.cpp.o …
```
> [HiGHS] add exectuable build

- P/Prjtrellis/build_tarballs.jl
This adds support for Prjtrellis, the open source bitstream documentation for ECP5 FPGAs.
> [prjtrellis] init

- C/Chuffed/build_tarballs.jl
cc @dourouc05
I haven't build all platforms locally, only Mac:
```
(base) oscar@Oscars-MBP ~ % /Users/oscar/Documents/Code/Yggdrasil/C/Chuffed/products/Chuffed.v0.10.4.x86_64-apple-darwin/bin/fzn-chuffed -h
Usage: /Users/oscar/Documents/Code/Yggdrasil/C/Chuffed/products/Chuffed.v0.10.4.x86_64-apple-darwin/bin/fzn-chuffed [options] <file>.fzn
Options:
-h, --help
Print help for common options.
--help-all
Print help for all options.
-a
Satisfaction problems: Find and print all solutions.
Optimisation problems: Print all (sub-optimal) intermediate solutions.
-n <n>, --n-of-solutions <n>
An upper bound on the number of solutions (default 1).
-v, --verbose
Verbose mode (default off).
-t, --time-out <n>
Time out in milliseconds (default 0, 0 = run indefinitely).
--rnd-seed <n>
Set random seed …
```
> [Chuffed] add new build recipe for Chuffed solver

- O/OpenBLAS/OpenBLAS32@0.3.13/bundled/patches/openblas-armv8-volatile-detecion.patch
- O/OpenBLAS/OpenBLAS@0.3.13/bundled/patches/openblas-armv8-volatile-detecion.patch
- O/OpenBLAS/OpenBLASHighCoreCount@0.3.13/bundled/patches/openblas-armv8-volatile-detecion.patch
Backports https://github.com/xianyi/OpenBLAS/pull/3060 towards fixing https://github.com/JuliaLang/julia/issues/39877. Verified to work using https://github.com/maleadt/OpenBLAS_jll.jl.
> Backport an additional OpenBLAS patch.

- P/polymake/build_tarballs.jl
- P/polymake/bundled/patches/sigchld.patch
This fixes `No child processes` errors with some subprocesses when both Polymake.jl and GAP.jl are active.
> [polymake] add patch for SIGCHLD conflicts with other packages

- P/polymake/build_tarballs.jl
Unfortunately my last patch fixed errors on Linux but triggered similar errors on MacOS so until I understand what is really going on with the signal handlers we need to apply this just for Linux.
> [polymake] only apply sigchld patch for linux

- .ci/Manifest.toml
This updates `.ci/Manifest.toml` to use BB 0.4.1 and BBB 1.0.0.
> [AZP] Update CI to use newer BinaryBuilder and BinaryBuilderBase

- L/LibUV/build_tarballs.jl
Hopefully this will address https://github.com/JuliaLang/julia/issues/34627! Though hopefully it won't just change the issue to "BB libuv built on FreeBSD 12 doesn't work on FreeBSD 13" :grimacing:
> [LibUV] Touch build_tarballs.jl to trigger a rebuild

- L/LibUnwind/build_tarballs.jl
We'll see if it picks up the right XZ_jll, since that was just merged to General
> [LibUnwind] Touch build_tarballs.jl to trigger a rebuild

- G/GMP/GMP@6.2.0/build_tarballs.jl
- G/GMP/GMP@6.2.1/build_tarballs.jl
This touches GMP 6.2.0 (for Julia 1.6 + MPFR) and 6.2.1 (newer Julia). It leaves 6.1.2 alone, as it's incompatble with Julia < 1.6.
> [GMP] Touch build_tarballs.jl to trigger a rebuild

- Y/Yosys/build_tarballs.jl
- enable libyosys
- correct version to match upstream
- whitespace fixes
- fix Product array
> [yosys] enable libyoys, and several cleanups

- T/TinyXML/build_tarballs.jl
This PR adds a `build tarballs.jl` for [TinyXML](https://sourceforge.net/projects/tinyxml/). I would like to have this available as a dependency for another project. 
The project does come with a small `Makefile`, but it seemed simple enough to just skip it and write it in the bash commands.
I picked `supported_platforms()` somewhat arbitrarily, I didn't see anything weird so I thought it would be safe for everything.
> add TinyXML

- Y/Yosys/build_tarballs.jl
It seems to be making the latest Yosys version impossible to install through Pkg.
> [yosys] loosen zlib compat

- L/libcleri/build_tarballs.jl
This was reported in https://github.com/libAtoms/ExtXYZ.jl/issues/6, and now shows up directly in the CI for ExtXYZ.jl, which tries and fails to import `libcleri.dll`  on Windows with an access error.
https://github.com/libAtoms/ExtXYZ.jl/runs/3351081827?check_suite_focus=true#step:6:58. 
The manual fix to add execute permissions to the built libraries should not be necessary since JuliaPackaging/BinaryBuilder.jl#992 has been merged, but somehow does seem to be.
> Update libcleri recipe: manually make library executable on Windows

- M/muparser/build_tarballs.jl
This PR adds a `build_tarballs.jl` for the [muparser](https://beltoforion.de/en/muparser/) library. Tested locally on `x86_64-linux-gnu`, `x86_64-linux-musl`, `x86_64-mingw` with no issues.
> add muparser

- Y/Yosys/build_tarballs.jl
To support this in YosysWrapper, some CMake trickery is required. It is easier to keep this in `lib` like everything else so it can be automatically found.
> [yosys] remove special 'yosys' subdirectory for libyosys install path

- 0_RootFS/LLVMBootstrap@12/bundled/patches/0101-clang-freebsd-triplet.patch
> [LLVMBootstrap@12] Add a Clang patch for FreeBSD targets

- P/poly2tri/build_tarballs.jl
- P/poly2tri/bundled/patches/cmake-edits.patch
This PR adds a `build_tarballs.jl` for the [poly2tri](https://github.com/jhasse/poly2tri) library.
They don't have any tagged releases on the GitHub page, so this builds from the most recent commit on master.
Tested locally on the usual platforms with no issues
> add poly2tri

- L/librtlsdr/build_tarballs.jl
This adds support for librtlsdr, an interface to the low-cost SDR dongle.
> [librtlsdr] init

- S/SoapyLMS7/build_tarballs.jl
Without this, we can't actually communicate over USB  :)
> [SoapyLMS7] Add `libusb` as a dependency

- X/Xyce/build_tarballs.jl
- X/Xyce/bundled/patches/no-undefined.patch
The AC_F77_LIBRARY_LDFLAGS flag is required when linking C++ and
Fortran *source files* into the same (shared) object. However,
here we're merely linking a Fortran library, so it is not required.
Unfortunately, while it in theory should do no harm, in practice
the AC_F77_LIBRARY_LDFLAGS macro is broken when targeting Windows
(which I will attempt to fix separately in upstream autoconf),
so remove it here.
> Xyce: Expand supported platforms

- U/USRPHardwareDriver/build_tarballs.jl
This adds library support for the USRP series of SDRs by NI. 
https://github.com/EttusResearch/uhd
> [usrp] init

- S/SoapyUHD/build_tarballs.jl
This adds the [SoapyUHD](https://github.com/pothosware/SoapyUHD) library, building upon #3565, for consumption through SoapySDR.jl.
> [soapyuhd] init

- L/LibCURL/build_tarballs.jl
Bump version due to security issues in older versions of curl
> Bumping to curl 7.78.0

- L/LibRaw/build_tarballs.jl
Adds the LibRaw library with all optional dependencies specified.
~For some reason the build fails on some platforms (including my native platform) when the `JasPer` dependence is enabled. The failures are of the form:~
```
/opt/i686-linux-gnu/bin/../i686-linux-gnu/sys-root/usr/local/include/jasper/jas_math.h:360:18: error: ‘INT_FAST32_MIN’ was not declared in this scope
(y < 0 && x < INT_FAST32_MIN - y)) {
```
~which seems really weird to me, since those macros are defined in `stdint.h`, which is included in `jas_math.h`.~
~Any guidance on how to get this recipe to work on all platforms would be much appreciated.~
Bumping the compiler version to `gcc6` was enough to fix this. (Thanks, @Crghilardi .)
> Add LibRaw-v0.20.2.

- Q/QuantumEspresso/build_tarballs.jl
Can the restriction be removed for `QuantumEspresso` now since https://github.com/JuliaPackaging/BinaryBuilderBase.jl/pull/156 was merged? I am no expert in building this, but I really need to install it on macOS. If so, please merge this.
> Remove constraint on macOS of `QuantumEspresso_jll`

- G/GeographicLib/build_tarballs.jl
* Package name: GeographicLib
* Version: v1.52.0
> Wizard recipe: GeographicLib-v1.52.0

- L/LLVM/LLVM_full@12.0.1/bundled/patches/0300-D109203-stackprobe-x86.patch
On i686-linux-gnu, enabling stackprobes caused register clobbering,
which manifested in segfaults in certain rare cases [0].  This ended up
being because a register was incorrectly specified; this patch rectifies
the issue and is confirmed to eliminate the segfaults.
[0] https://github.com/JuliaLang/julia/issues/41528
> [LLVM] Add stackprobe patch to fix i686-linux-gnu segfaults

- L/libpolymake_julia/common.jl
- L/libpolymake_julia/libpolymake_julia@1.3/build_tarballs.jl
This version fixes the backwards compatibility issue that was introduced in the 0.4.2 version, which I have asked to be yanked: https://github.com/JuliaRegistries/General/pull/44719
I will update the PRs for the other julia versions when this is merged.
> [libpolymake_julia] bump to 0.4.3 (julia 1.3)

- F/FFTW/build_tarballs.jl
FFTW.jl now [requires](https://github.com/JuliaMath/FFTW.jl/blob/9a9239f4eabb2656cf6c90dcdbbdcd345d4fdc09/Project.toml#L19) Julia 1.6. In order to support experimental platforms like Apple Silicon, a new FFTW_jll needs to be built with an updated version number and then FFTW.jl can be updated. This PR seeks to resolve the open point for FFTW in https://github.com/JuliaPackaging/Yggdrasil/issues/2763.
> [FFTW] Build for experimental platforms

- L/libaio/build_tarballs.jl
This adds `libaio`:
>The Linux-native asynchronous I/O facility ("async I/O", or "aio") has a richer API and capability set than the simple POSIX async I/O facility. This library, libaio, provides the Linux-native API for async I/O. The POSIX async I/O facility requires this library in order to provide kernel-accelerated async I/O capabilities, as do applications which require the Linux-native async I/O API.
https://pagure.io/libaio
> [libaio] init

- L/libjulia/common.jl
... as older Julia versions get confused by the `julia_version` in the artifact names.
For example, compare 
1. <https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/tag/libsingular_julia-v0.17.5%2B0>
2. <https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/tag/libsingular_julia-v0.18.5%2B0>
The first one was made before we started adding in `julia_version` (which happened in PR #3411). The second was made a few days ago.
I also wonder if we really should be setting `julia_version` to the *full* version, such as  "1.5.3" -- or instead to e.g. `1.5` or `1.5.0`, considering that Julia does this anyway (from `base/binaryplatforms.jl` in Julia 1.6):
>  `By default, we compare julia_version only against major and minor versions:`
On the other hand, …
> Only set julia_version in libjulia_platforms if it is >= 1.6

- G/GDB/build_tarballs.jl
Without this, GDB is incompatible with rr:
```
warning: Can not parse XML target description; XML support was disabled at compile time
Remote 'g' packet reply is too long (expected 560 bytes, got 816 bytes): [snip]
```
cc @ianatol
> GDB: Enable XML support

- L/librttopo/build_tarballs.jl
This PR adds a `build_tarballs.jl` for the [librttopo](https://git.osgeo.org/gitea/rttopo/librttopo) library. They don't seem to have releases, so I am building from current `master` here.
Tested locally on `linux-gnu`, `linux-musl`, `mingw`, `powerpc`, `freebsd`, and `apple-darwin` with no issues.
> add librttopo

- G/GeographicLibWrapper/build_tarballs.jl
- G/GeographicLibWrapper/src/CMakeLists.txt
- G/GeographicLibWrapper/src/GeographicLibWrapper.cpp
Adds a `CxxWrap.jl`-based wrapper to `GeographicLib`.
I followed the patterns used in `X/XyceWrapper`, sometimes blindly, to produce `build_tarballs.jl` and tweak `src/CMakeLists.txt`.
~_N.B._: the script currently refers to my personal deployment of `GeographicLib` pending the merge of #3587.~ Reference updated.
The wrapper is used in [GeographicModels.jl](https://github.com/twadleigh/GeographicModels.jl).
> Add GeographicLibWrapper-0.1.0

- W/wolfSSL/build_tarballs.jl
This PR adds a `build_tarballs.jl` for [wolfSSL](https://github.com/wolfSSL/wolfssl).
Tested locally on `linux-gnu`, `linux-musl`, `mingw`, `powerpc`, `apple-darwin`
> add wolfSSL

- L/libpsl/build_tarballs.jl
This PR adds a `build_tarballs.jl` for the [libpsl](https://github.com/rockdaboot/libpsl) library.
This library doesn't have any dependencies, so I felt it was safe to add the `experimental=true` flag without breaking anything.
Tested locally on `linux-gnu`, `mingw`, `linux-musl` with no issues.
> add libpsl

- O/OpenBLAS/OpenBLAS32@0.3.10/bundled/patches/openblas-julia40963-zdot.patch
- O/OpenBLAS/OpenBLAS@0.3.10/bundled/patches/openblas-julia40963-zdot.patch
- O/OpenBLAS/OpenBLASHighCoreCount@0.3.10/bundled/patches/openblas-julia40963-zdot.patch
xref:  https://github.com/JuliaLang/julia/pull/42397
Things to discuss: Whether the patch needs to be ported to an older version.
> [OpenBLAS] add new patch to fix `zdot` crash

- Q/Qhull/build_tarballs.jl
As [explained in #3657](https://github.com/JuliaPackaging/Yggdrasil/pull/3657#issuecomment-930666102), we should really rename this to the [semver version](http://www.qhull.org/news/qhull-news.html).  (Or semver-like, at least; I don't know if they are strictly following semantic versioning.)
Then [dependents of `qhull_jll`](https://juliahub.com/ui/Packages/Qhull_jll/nBD85/2020.2.0+0?t=2) can update their compatibility section to list `qhull_jll = "8"` and it should do the right thing, since Pkg assumes that differing major versions are incompatible.
Once 8.0.2 is released, we can then merge #3657 to release 8.1-alpha1.
> qhull semver for v2020.2 is actually v8.0.2

- L/libunistring/build_tarballs.jl
This PR adds a `build_tarballs.jl` for the [libunistring](https://www.gnu.org/software/libunistring/) library.
Tested locally on:
`x86_64-linux-gnu`,
`x86_64-linux-musl`,
`x86_64-w64-mingw32`,
`powerpc64le-linux-gnu`,
`x86_64-unknown-freebsd`,
`x86_64-apple-darwin`
> add libunistring

- R/RadeonProRender/build_tarballs.jl
This repackages the prebuild binaries from RadeonProRender...
I guess it would be nice to build them here, but since they don't seem to make cross-platform builds particularly easy and it depends on the entire GPU OpenCL/Vulkan/AMD stack, I didn't even try to build this.
If anyone expects this to be easy, let me know though ;) 
Also, they ship binaries for centos7, but I didn't see any BinaryBuilder Platform that matches that?
> add RadeonProRender

- D/DuckDB/build_tarballs.jl
The latest version of Duckdb.
[Release notes](https://github.com/duckdb/duckdb/releases/tag/v0.2.9)
> Updated DuckDB to version 0.2.9

- O/Openresty/build_tarballs.jl
Update Openresty to v1.19.9 and use openssl v1.1.1l instead of v1.0.
Dropping 32bit build, it does not compile and is also not used.
> Update Openresty to v1.19.9

- G/GEOS/build_tarballs.jl
* Update GEOS from 3.9.0 to 3.10.0
* Switch to CMake
* Add experimental platforms 
See https://github.com/libgeos/geos/blob/main/NEWS
> Autoconf build system is dropped in favour of CMake
> Update GEOS to 3.10.0, switch to CMake, add experimental platforms

- M/msolve/build_tarballs.jl
Trying to help @ederc expand this JLL: the main goal is to enable OpenMP on Linux and add Apple M1 support. However, to get started, I also enabled *all* platforms, just to see what all breaks, and how ;-). As such, this is of course just a draft for now.
> msolve: more platforms, enable OpenMP (WIP)

- G/GDAL/common.jl
- L/librttopo/build_tarballs.jl
- L/libspatialite/build_tarballs.jl
This brings the build scripts back in line with the already merged registry edit of https://github.com/JuliaRegistries/General/pull/47879
The GEOS 3.10 build works as well, but its dependencies will need a new build, since the SONAME of the GEOS build changed.
[skip ci] [skip build]
> add compat bounds for GEOS_jll

- H/HiGHS/build_tarballs.jl
This builds HiGHS off the latest commit: https://github.com/ERGO-Code/HiGHS/commit/bd9703cc1a896c68473144064011cc9d64246e07
Internally, they're calling it v1.1,  but there isn't a tagged release yet: https://github.com/ERGO-Code/HiGHS/issues/595.
cc @jajhall, @galabovaa
> [HiGHS] add version 1.1.0

- L/LibUnwind/LibUnwind@1.3.2/build_tarballs.jl
- L/LibUnwind/LibUnwind@1.3.2/bundled/patches/libunwind-cfa-rsp.patch
- L/LibUnwind/LibUnwind@1.3.2/bundled/patches/libunwind-configure-ppc64le.patch
- L/LibUnwind/LibUnwind@1.3.2/bundled/patches/libunwind-configure-static-lzma.patch
- L/LibUnwind/LibUnwind@1.3.2/bundled/patches/libunwind-dwarf-table.patch
- L/LibUnwind/LibUnwind@1.3.2/bundled/patches/libunwind-prefer-extbl.patch
- L/LibUnwind/LibUnwind@1.3.2/bundled/patches/libunwind-static-arm.patch
PR #3856 refactored the previous master into a builder specifically for libunwind v1.5.0. To avoid issues with automated JLL registration, it only did that version. This PR now adds a separate builder for v1.3.2, the version of libunwind currently in use by Julia, based on the state of the builder as of commit e9a0bfdaf1947867eafde7c8472389fdf60ccdc6 but with https://github.com/libunwind/libunwind/pull/308 as an added patch.
Note that to avoid said issues with registration, this commit does not refactor the other builder to use a common setup; that can be done separately to reduce duplication.
> [libunwind] Add a separate builder for v1.3.2

- M/MMseqs2/build_tarballs.jl
- M/MMseqs2/bundled/patches/arm-simd-march-cmakefile.patch
This is a build script for mmseqs2, a many-to-many sequence searching tool for bioinformatics:
https://github.com/soedinglab/MMseqs2
Notes:
- not sure if the way i switched `CMAKE_TARGET_TOOLCHAIN` on macos and freebsd is the right way to do it
- I added the dependencies Zlib and Bzip2 by hand, so i don't have any uuids there. Is this a problem?
- ARM doesn't have vectorization acceleration due to the -march issues noted in the build script
- I chose g++-8, because g++-7 didn't compile on powerpc. A build with g++-11 resulted in binaries that didn't work on Ubuntu 20.04 due to newer GLIBCXX symbols used
- freebsd has a warning from the BinaryBuilder auditor: `Warning: Linked library libomp.so could not be resolved and could not be auto-mapped`. I don't have a freebsd system so i can't …
> Add MMseqs2 build script

- M/MAFFT/build_tarballs.jl
MAFFT is a multiple-sequence alignment program for amino acid or nucleotide sequences used in bioinformatics.
https://mafft.cbrc.jp/alignment/software/
> Add MAFFT-7.490 build script

- P/pciutils/build_tarballs.jl
This adds [pciutils](https://github.com/pciutils/pciutils).
>1. What's that?
>The PCI Utilities package contains a library for portable access to PCI bus
>configuration registers and several utilities based on this library.
>
>In runs on the following systems:
>
>	Linux		(via /sys/bus/pci, /proc/bus/pci or i386 ports)
>	FreeBSD		(via /dev/pci)
>	NetBSD		(via libpci)
>	OpenBSD		(via /dev/pci)
>	GNU/kFreeBSD	(via /dev/pci)
>	Solaris/i386	(direct port access)
>	Aix		(via /dev/pci and odmget)
>	GNU Hurd	(direct port access)
>	Windows		(direct port access, see README.Windows for caveats)
>	CYGWIN		(direct port access)
>	BeOS		(via syscalls)
>	Haiku		(via /dev/misc/poke)
>	Darwin		(via IOKit)
>	DOS/DJGPP	(via i386 ports)
>	SylixOS		(via /proc/pci)
> [pciutils] init

- L/libcint/build_tarballs.jl
1. Updated source library version.
2. Added installation of long-range part of range-separated Coulomb operator.
3. Added Windows as a supported platform.
4. Change binary dependency from `OpenBLAS32_jll` to `OpenBLAS_jll`.
> Update build_tarballs.jl for libcint v4.4.6

- L/libcint/build_tarballs.jl
Remove Windows from building platforms because `libcint` itself does not support Windows for now.
> [libcint] Do not build for Windows

- V/ViennaRNA/build_tarballs.jl
- V/ViennaRNA/bundled/patches/windows-forester-remove-time-measurement.patch
- RNAforester build now enabled. The build used to fail on windows due
to unportable timing calls, we patch these out on windows.
See: `bundled/patches/windows-forester-remove-time-measurement.patch`
- New program RNAmultifold for structure prediction of multistrand
complexes. This uses dlib in the calculation of strand
concentrations. Unfortunately, dlib doesn't compile at the moment on
powerpc64le, so this platform is disabled for now until this is
fixed.
> Update ViennaRNA to 2.5.0

- A/Aria2/build_tarballs.jl
Add aria2 https://github.com/aria2/aria2
I had a strange linking error when adding `Dependency(PackageSpec(name="LibSSH2_jll"))` to the dependencies, due to LibSSH in turn using mbedtls. So for now i removed libssh2 functionality. When adding libssh2 to the build deps, the build works fine but the executable and library are linked to `libmbedcrypto.so.7` which can't be found.
I think it's due to `LibSSH2_jll v1.10.1+0` pulling in `MbedTLS_jll v2.27.0+0` for the build, even though according to the [build script](https://github.com/JuliaPackaging/Yggdrasil/blob/7a834c853005098bf8a8f0817e7fa93be2525e40/L/LibSSH2/build_tarballs.jl#L45) it should use 2.24.0.
> Add Aria2-1.36.0

- X/Xyce/build_tarballs.jl
- The master of Xyce has a lot improvements over v7.4
- This is for power users who want to use them already
----
- For people interested in v7.4 of Xyce this [Xyce_jll-v7.4.0+0](https://github.com/JuliaBinaryWrappers/Xyce_jll.jl/releases/tag/Xyce-v7.4.0%2B0) release can be used
> Create a Xyce_jll with the latest commit on master

- L/Libffi/build_tarballs.jl
- L/Libffi/bundled/patches/0001-libdir-no-touchy.patch
The libffi configure script tries to be "smart" and detect whether
the target platform uses the lib/lib64 split for its libraries even
though nobody asked it too. This causes libffi to not be linkable
because it doesn't get installed in the lib directory. Now, in theory
pkg-config would take care of that, because it does have the correct
directory, but in practice pkg-config does not work, so we really do
need everything in one directory. The last question may be why didn't
this cause trouble before? Well, the answer to that one is that on
many platforms, we have a copy of libffi in the sysroot, which
builds picked up instead of the correct dependency. We don't on
powerpc64 though, causing issues in #3903.
Fix all that by just patching the problematic code out of the
configure script. …
> libffi: Stop messing with the install directory

- G/Graphviz/build_tarballs.jl
@Keno Thanks for the work in #3903! The generated config didn't actually end up in the final artifact for windows due to this small omission, hopefully this should do the trick.
> [Graphviz] Fix to copy generated config on windows

- F/FLINT/build_tarballs.jl
As last time, ideally the PR to the General registry could be prevented from auto-merging, so that we can update `LoadFlint.jl` first.
> Update FLINT to 2.8.4, for Julia 1.0-1.5

- F/FLINT/build_tarballs.jl
Should be only merged after #3911 was merged and we had a chance to update LoadFlint.jl
> Update FLINT to 2.8.4, for Julia >= 1.6

- L/LLVM/LLVM_full@11.0.1/bundled/patches/0708-Do-not-patch-FDE-symbols-on-AArch64.patch
- L/LLVM/LLVM_full@11.0.1/bundled/patches/0709-Force-.eh_frame-emission-on-AArch64.patch
Move out patches for LLVM 11 in #3063, without rebuilding the package
> [LLVM_full@11.0.1] Add LLVM AArch64 unwind patches

- R/Readline/build_tarballs.jl
Add linker flag to point to correct `$libdir` for FreeBSD (this is often needed for FreeBSD and can lead to failures as mentioned in the [Build Troubleshooting](https://docs.binarybuilder.org/dev/troubleshooting/#Libraries-of-the-dependencies-can't-be-found), but in this case the failure was hidden because of a similar library existing in the Rootfs). With this change running the build with `--debug=end` produces:
```console
sandbox:${WORKSPACE}/srcdir/readline-8.1 # patchelf --print-needed $libdir/libhistory.so
libncursesw.so.6
libc.so.7
```
Without that change we get this on FreeBSD:
```julia
root@freebsd:~ # /root/julia-1.6.4/bin/julia
_
_       _ _(_)_     |  Documentation: https://docs.julialang.org
(_)     | (_) (_)    |
_ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
| …
```
> [Readline] fix linkage on freebsd

- C/cilantro/build_tarballs.jl
This PR adds a `build_tarballs.jl` for the [cilantro](https://github.com/kzampog/cilantro) point cloud library.
There are currently no releases or tags, so I am just building from current `master` here. There is an open issue about use of releases on the repo though.
Tested locally on `x86_64-linux-gnu`, `x86_64-linux-musl`, `powerpc`, and `mingw`
I did run into a small issue where `make install` would grab the `libcilantro.dll.a` and leave the actual `libcilantro.dll` behind. I just `mv` it here.
> add cilantro

- C/Cares/build_tarballs.jl
This adds a build script for c-ares-1.18.1, a C library for asynchronous DNS requests.
I have chosen the package name to be `Cares`, i thought it looked a bit better than `C_ares`, but not sure on the conventions in Yggdrasil.
https://c-ares.org/
https://github.com/c-ares/c-ares
> Add c-ares-1.18.1

- L/LAMMPS/build_tarballs.jl
Modified to build LAMMPS with "most" packages cmake preset.
LAMMPS packages requiring extra libraries were disabled to simplify the process.
The LAMMPS packages containing DPD style potentials caused issues while cross compiling and have been disabled.
> Update LAMMPS to include most packages

- L/libLAS/build_tarballs.jl
- L/libLAS/bundled/patches/add-arch-macros.patch
- L/libLAS/bundled/patches/comment-out-FixupOrdering.patch
- L/libLAS/bundled/patches/mingw-rename-libs.patch
This PR adds a `build_tarballs.jl` for the [libLAS](https://github.com/libLAS/libLAS) library (not to be confused with the [LASlib](https://github.com/LAStools/LAStools/tree/master/LASlib) library....). This project is semi-deprecated (?) but I still see it as a dependency for a number of projects floating around. The last release was in 2016, they mention in an issue that there are no plans to cut a new release and it's basically managed as a rolling release now. I am building from latest master here.
Many of the dependencies are newer than what the project is written for so I had to fix some things. Otherwise tested on the usual subset of platforms with no issues. :crossed_fingers: 
FYI: @visr @evetion
> add libLAS

- L/LibUV/build_tarballs.jl
Minor, but includes several (6) fixes:
https://github.com/JuliaLang/libuv/compare/c6869fba163a1e04af64ede438a8fd0191e75e9e...3a63bf71de62c64097989254e4f03212e3bf5fc8
> bump libuv

- L/libnabo/build_tarballs.jl
This PR adds a `build_tarballs.jl` for the [libnabo](https://github.com/ethz-asl/libnabo) library.
Tested on `x86_64-linux-gnu`,  `x86_64-linux-musl`,  `x86_64-w64-mingw64`
> add libnabo

- P/polymake/bundled/patches/sigchld.patch
This should fix https://github.com/oscar-system/Oscar.jl/issues/831 (`No child processes`), even though I do not fully understand why this happens now and why only with 1.6.4 macos but I have spent way too much time trying to debug this.
Note: This is just a bugfix, an update to the latest Perl_jll will come later.
> [polymake] update patch to (temporarily) set sigchld before spawning subprocess

- L/LLVMExtra/build_tarballs.jl
For LLVM 13 compatibility (although it doesn't build compatible artifacts; we currently just follow the version used by Julia).
> Bump LLVMExtra.

- N/nanoflann/build_tarballs.jl
This PR adds a `build_tarballs.jl` for [nanoflann](https://github.com/jlblancoc/nanoflann), which is a header-only library.
I largely followed the structure of the `Eigen` script for this one and learned about `AnyPlatform()`
> add nanoflann

- G/Gingko/build_tarballs.jl
This PR adds a `build_tarballs.jl` for the [Gingko](https://github.com/ginkgo-project/ginkgo) library. I left it pretty close to default build settings.
Tested on `x86_64-linux-gnu`, `x86_64-linux-musl` and `x86_64-w64-mingw64`
> add Ginkgo

- M/MPICH/build_tarballs.jl
- M/MPItrampoline/build_tarballs.jl
- M/MicrosoftMPI/build_tarballs.jl
- O/OpenMPI/build_tarballs.jl
Also improve the way in which the fall-back MPICH library is built. It is now a static library which simplifies `dlopen`ing the MPIwrapper library.
> [MPItrampoline] Update to version 2.7.0

- Y/yaml_cpp/build_tarballs.jl
Closes #3668 and small edits including
-add flag to disable building tests
-consolidate the `platforms` variable slightly
> [yaml_cpp] change to use standard platform toolchains

- B/boostpython/build_tarballs.jl
Apparently boostpython now needs to encode the python version in the file name, so that you can install multiple parallel versions of boostpython for your different python versions.
> boostpython: Encode python version in file name

- O/OpenMPI/build_tarballs.jl
As this is not used by MPI.jl by default, it doesn't make sense to download it. See https://github.com/JuliaParallel/MPI.jl/issues/483
> [Open MPI] bump version and make lazy

- G/Glib/build_tarballs.jl
Following https://github.com/JuliaPackaging/Yggdrasil/pull/3989, hopefully Glib goes down from 32.7 MB.
cc @giordano
> [Glib] Use release build type

- O/OpenBLAS/OpenBLAS@0.3.17/build_tarballs.jl
- O/OpenBLAS/common.jl
After this we should rebuild the OpenBLAS libraries used on 1.6.4 and 1.7.0 with this.
Ref https://github.com/JuliaPackaging/Yggdrasil/issues/3996
> put back the default threads for OpenBLAS to 32

- U/Usrsctp/build_tarballs.jl
* Package name: Usrsctp
* Version: v0.9.5
> Wizard recipe: Usrsctp-v0.9.5

- .ci/Manifest.toml
Changes:
* BinaryBuilderBase: https://github.com/JuliaPackaging/BinaryBuilderBase.jl/compare/v1.0.4...v1.1.0
* BinaryBuilder: https://github.com/JuliaPackaging/BinaryBuilder.jl/compare/v0.4.2...v0.4.4
Most notably, this includes a slightly less broken Rust toolchain, supporting
also experimental platforms, however 32-bit Windows (`i686-w64-mingw32`) is
completely unusable.
> [AZP] Update BinaryBuilderBase and BinaryBuilder

- W/WhiteboxTools/build_tarballs.jl
This PR adds a `build_tarballs.jl` for the [WhiteboxTools](https://github.com/jblindsay/whitebox-tools) library.
I just grabbed the platforms and some of the params from the `ripgrep` file.  I just wanted to try something `rust`-y and cool
> add WhiteboxTools

- S/Singular/build_tarballs.jl
should fix 'NTL/FLINT missing' errors when running the Singular testsuite on aarch64-apple-darwin
(see also https://github.com/oscar-system/Oscar.jl/issues/546#issuecomment-969164739)
cc: @fingolfin @tthsqe12 
Patchlevel bump due to compat change, we could also just build with a newer version and keep the compat but I am slightly scared of downwards compatibility.
> [Singular] rebuild with newer (M1-enabled) FLINT

- 0_RootFS/GCCBootstrap@4/bundled/patches/gcc494_musl.patch
The patch for using old GCC on musl defined INCLUDE_DEFAULTS_MUSL_LOCAL but
never used it in the definition of INCLUDE_DEFAULTS. Comparing the patch with
what is in mainline GCC these days suggest this patch. For reference, see:
<https://github.com/gcc-mirror/gcc/blob/master/gcc/config/linux.h#L190>
This is a first step towards addressing (parts of) issue #3949. Alas, since I only modify a .patch, nothing will actually be built -- which is good, as I am not sure how the correct way is to proceed with updating the RootFS / compiler shard. And in fact before doing that, it should be tested whether the patch even works as intended. So, baby steps:
1. Perform a test build and check if it has the correct default include paths
- I tried this via `julia --color=yes  --proj=../../.ci …
> GCC 4.8.5 for musl: tweak patch to match upstream

- B/Blosc/build_tarballs.jl
This updates c-blosc 1 to 1.21.1: https://github.com/Blosc/c-blosc/releases/tag/v1.21.1
Builds for experimental platforms to address macOS on M1.
Fix https://github.com/JuliaPackaging/Yggdrasil/issues/4051
Fix https://github.com/JuliaIO/Blosc.jl/issues/85
Fix https://github.com/JuliaIO/HDF5.jl/issues/870
> Update Blosc1 to version 1.21.1; support experimental platforms

- M/MPICH/build_tarballs.jl
Also, build with more optimisations and less debug symbols, like Homebrew does:
https://github.com/Homebrew/homebrew-core/blob/894e4247adf3115acef43daaf71f2704890a61ad/Formula/mpich.rb#L66.
See list of enabled optimisations (nothing too bad) at
https://github.com/pmodels/mpich/blob/5faab845dc3277e25bd2b2302f6acf04cc6f5b36/configure.ac#L419-L431.
Should fix #4039 (or at least work around it by not building assertions).  CC: @simonbyrne
> [MPICH] Update to v3.4.3

- L/libjulia/build_tarballs.jl
- L/libjulia/bundled/patches/1.8.0-DEV/0001-Don-t-set-HAVE_SSP-unconditionally-on-aarch64.patch
- L/libjulia/common.jl
Note that this *hopefully* doesn't matter, namely if 1.7.0-rc3 and 1.7.0 are 100% ABI compatible, which they should be, but better safe than sorry? Same goes for the master branch, which is far more likely to have breaking ABI changes. I figure it's a good idea to at least rebuild this once with the final releases, anyhow. Thoughts?
> libjulia: update to 1.7.0 final and also a newer master snapshot

- P/ParseGen/build_tarballs.jl
This PR adds a `build_tarballs.jl` for the [ParseGen](https://github.com/sandialabs/parsegen-cpp) library. This needs `C++17` and `std::filesystem`, so I am using `GCC 8` here.
> add ParseGen

- G/GAP/build_tarballs.jl
- G/GAP_pkg/GAP_pkg_juliainterface/build_tarballs.jl
- L/libcxxwrap_julia/build_tarballs.jl
... to adjust for ABI changes in Julia 1.8.0-DEV
Strictly speaking only the binaries for 1.8 need to be updated, but I don't think that's possible, so all get updated.
I suspect more JLLs need this treatment, but most of the remaining ones use `libcxxwrap_julia`, and so I'd like to first update that (whether this is *really* necessary or not is another question, but I'd rather not risk it).
CC @benlorenz @thofma
> Rebuild GAP, GAP_pkg_juliainterface, libcxxwrap_julia

- O/ONNX/build_tarballs.jl
As of now, this build recipe excludes building for the windows platform. The upstream code includes many instances of conditional compilation guarded by `#ifdef _WIN32` that selects between targeting a Win32 API vs. POSIX. The cross compilers don't seem to like building against the Win32 interface. I don't know if the mingw compilers provide the full POSIX interface. And, if they actually do, I haven't yet been able to convince the build system to treat this case as POSIX. (All I've tried on that front to this point is to pass `-U_WIN32` to cmake.)
> Add ONNX v1.10.2.

- L/libpolymake_julia/build_tarballs.jl
and rebuild for updated julia nightly (1.8)
(this obsoletes one half of #4118)
> [libpolymake_julia] bump to 0.6.1

- C/Conduit/build_tarballs.jl
Adds a new build recipe for LLNL's conduit mesh data exhange library
https://github.com/LLNL/conduit
This does not include MPI support for the time being, but that should be
a strict addition in the future (when the default Julia MPI ABI issues get
resolved).
> Add Conduit

- O/openbabel/build_tarballs.jl
Adds [openbabel](https://github.com/openbabel/openbabel), a library to work with atomic structure files.
Haven't included GUI support for now.
While building for Windows, I got warnings like: `Minimum instruction set detected for lib/openbabel/3.1.0/zindoformat.obf is avx2, not x86_64 as desired.`. Hope that's fine.
> Add openbabel

- N/Notcurses/build_tarballs.jl
I noticed we are currently building the cxx library for notcurses which isn't really useful. Disable it.
> notcurses: stop building the cxx libraries

- M/MUMPS/MUMPS@5/build_tarballs.jl
- M/MUMPS/MUMPS@5/bundled/patches/mumps_int32.patch
Without Artifacts, MUMPS.jl works with MUMPS 5.4.1 but I have some errors with the Artifact `MUMPS_jll` and the only difference is `MUMPS_INT` (Int64 instead of Int32) .
> Recompile MUMPS 5.4.1 with a patch update

- C/Catalyst/build_tarballs.jl
Adds a new build recipe for the Catalyst in-situ mesh visualization library.  https://catalyst-in-situ.readthedocs.io/en/latest/introduction.html.
> add paraview catalyst library recipe

- B/Bison/build_tarballs.jl
As an experiment, I've also turned Windows back on, just to say if / how that fails.
> Bison: update to 3.8.2, enable more platforms

- L/libtirpc/build_tarballs.jl
- L/libtirpc/bundled/queue.h
This PR adds a `build_tarballs.jl` for the [libtirpc](https://sourceforge.net/projects/libtirpc/) library. I did find a closed PR (#1488) about this, not sure what happened there.
This works for me locally on `linux-gnu` and `linux-musl`. I can't quite tell if `*-mingw*` platforms are actually patch-able or not, it's currently erroring out with `err.h` issues and many type issues. I may have to just filter out windows platforms
> add libtirpc

- H/HiGHS/build_tarballs.jl
We now have an official release: https://github.com/ERGO-Code/HiGHS/releases/tag/v1.1.1
cc @jajhall
> [HiGHS] bump to v1.1.1

- T/TracyProfiler/build_tarballs.jl
- T/TracyProfiler/bundled/patches/library_extension.patch
- T/TracyProfiler/bundled/patches/unix_common_make.patch
- T/TracyProfiler/bundled/patches/unix_library_release.patch
More info here: https://github.com/wolfpld/tracy
This builds the profiler gui, instrumentation library and utilities.  The only issue on OSX is with the instrumentation library with libbacktrace, I don't think the MACHO defines are correct with cross compilation and needs someone better versed to debug but everything on linux x64 should work to get started.
> add build recipe for the tracy profiler

- H/hsa_rocr/build_tarballs.jl
- H/hsa_rocr/bundled/patches/no-symlinks.patch
The symlinks are created for legacy reasons we don't care about, for us they
only cause confusions with RUNPATHs:
https://github.com/JuliaPackaging/Yggdrasil/pull/4077#issuecomment-1000500072
CC: @jpsamaroo
> [hsa_rocr] Do not install legacy symlinks

- T/TempestRemap/build_tarballs.jl
TempestRemap is a conservative, consistent and monotone remapping package for arbitrary grid geometry.
https://github.com/ClimateGlobalChange/tempestremap
> add build recipe for tempestremap library

- M/MbedTLS/MbedTLS@2.28.0/build_tarballs.jl
- M/MbedTLS/MbedTLS@2.28.0/bundled/patches/0001-Remove-flags-not-sopported-by-ranlib.patch
- M/MbedTLS/common.jl
Add MbedTLS 2.28.0 due to [CVE-2021-44732](https://nvd.nist.gov/vuln/detail/CVE-2021-44732)
https://tls.mbed.org/tech-updates/security-advisories/mbedtls-security-advisory-2021-12
> Add MbedTLS 2.28.0

- R/ROCmOpenCLRuntime/build_tarballs.jl
This was necessary because `hsa_rocr_jll` used to have legacy symlinks with
weird RUNPATHs set for the libraries.  Now that we removed those symlinks, this
hack isn't needed anymore.
> [ROCmOpenCLRuntime] Remove unneeded hack

- L/libgeotiff/build_tarballs.jl
Needed to progress with #4193, since both have a PROJ dependency.
Had to add LibCURL_jll as a direct dependency (rather than through PROJ), to avoid this issue:
```
/opt/x86_64-linux-gnu/x86_64-linux-gnu/sys-root//usr/local/lib/libcurl.so.4: undefined reference to `mbedtls_net_recv'
/opt/x86_64-linux-gnu/x86_64-linux-gnu/sys-root/usr/local/lib/libproj.so.22.2.0: undefined reference to `curl_easy_perform@CURL_4'
```
> [libgeotiff] build 1.7.0

- L/LLVM/Clang@13.0.0/build_tarballs.jl
We missed this one in the last round of LLVM builds
> Build Clang `v13.0.0+3`

- G/gperftools/build_tarballs.jl
This PR bumps `gperftools` from 2.7 up to 2.9.1. I also tried to update it a bit with wider platforms and `julia_compat` statement.
> [gperftools] bump version from 2.7 to 2.9.1

- M/MPICH/build_tarballs.jl
https://github.com/conda-forge/mpich-feedstock/issues/56
It should solve the issue with #4199 :crossed_fingers:
> Add --disable-opencl to configure script of MPICH

- U/UDUNITS/build_tarballs.jl
- U/UDUNITS/bundled/patches/freebsd.patch
* Package name: UDUNITS
* Version: v2.2.28
> Wizard recipe: UDUNITS-v2.2.28

- T/TempestModel/build_tarballs.jl
- T/TempestModel/bundled/patches/mk_defs.patch
- T/TempestModel/bundled/patches/mk_system_agri.patch
- T/TempestModel/bundled/patches/mk_system_macosx.patch
- T/TempestModel/bundled/patches/netcdf_cpp.patch
tempestmodel is an atomospheric dycore implementation.  this build will help in making it easier for the CliMA team to run comparative simulations on well defined test cases.
> add tempest model build for x86 unix platforms

- F/finufft/build_tarballs.jl
The FINUFFT library doesn't have CPU instruction set dispatch, but benefits a lot from optimization with SIMD instructions, so compiling it for different microarchitectures seems like a good idea.
> [FINUFFT] Microarchitecture expansion

- E/ensmallen/build_tarballs.jl
This PR adds a `build_tarballs.jl` for the [ensmallen](https://github.com/mlpack/ensmallen) library. It's a header only library so pretty straightforward.
> add ensmallen

- S/spectra/build_tarballs.jl
This PR adds a `build_tarballs.jl` for the [spectra](https://github.com/yixuan/spectra) library. This is another header only library. I believe I remembered to use the correct dependency type this time around.
> add spectra

- .ci/Manifest.toml
- .ci/azp_agent/install_agents.sh
- H/HelloWorldC/build_tarballs.jl
Changes:
* https://github.com/JuliaPackaging/BinaryBuilder.jl/compare/v0.4.8...v0.5.0
* https://github.com/JuliaPackaging/BinaryBuilderBase.jl/compare/v1.3.0...v1.4.0
Note: with this change we switch to Julia v1.7
> [AZP] Upgrade BinaryBuilder to v0.5.0 and require Julia v1.7

- T/Taskflow/build_tarballs.jl
This PR adds a `build_tarballs.jl` for the [Taskflow](https://github.com/taskflow/taskflow) library. Once again, header only library. The only thing maybe worth mentioning was they specify a minimum `gcc` version in the `CMakeLists.txt`, so I had to increase the `preferred_gcc_version` to make everything happy.
> add Taskflow

- S/SLICOT/build_tarballs.jl
SLICOT - Subroutine Library In COntrol Theory - is a general purpose
basic mathematical library for control theoretical computations.
This commit adds the relicensed (BSD) version of SLICOT, linking
against libblastrampoline.
> [SLICOT] Add builder

- A/Antlr4CppRuntime/build_tarballs.jl
g++-6 on linux was causing issues downstream when linking with ANTLR driver code compiled with later versions. Verified locally that the issue goes away with g++-7.
> [Antlr4CppRuntime] Update gcc version.

- L/libblastrampoline/build_tarballs.jl
Chewing through version numbers like it's going out of style, let's add LBT v4.0.0 which allows for loading dual-interface libraries such as MKL v2022+.
> [libblastrampoline] Build v4.0.0

- L/libblastrampoline/build_tarballs.jl
Version 4 of libblastrampoline breaks the ABI compared to v3, and it's used only in julia v1.8: https://github.com/JuliaLang/julia/pull/43877.  We should reflect these constraints in the registry.
CC @staticfloat
> [libblastrampoline] Fix julia compat to v1.8

- azure-pipelines.yml
There is currently an outage of the PkgServer used by Yggdrasil, redirecting to
a working PkgServer should avoid issues.
> [AZP] Temporarily force use of `us-east` PkgServer

- O/oneTBB/build_tarballs.jl
- O/oneTBB/bundled/patches/NOMINMAX-defines.patch
- O/oneTBB/bundled/patches/clang-no-lto.patch
- O/oneTBB/bundled/patches/lowercase-windows-include.patch
This PR bumps the commit hash to current master and bumps the version number up to the most recent release for `oneTBB`.
I am also removing the windows platform filter. The commit referenced about the export attributes has been merged. In addition, I am using the most current master instead of the release archive to include a [commit with mingw specific fixes](https://github.com/oneapi-src/oneTBB/commit/ce476173772f289c66ba98089618c1ff767ecea4) that didn't make it in to the release.
> [oneTBB] bump version and try adding mingw platforms back in

- T/TempestRemap/build_tarballs.jl
Until the build / runtime issues with libblastrampoline are resolved, this is a workaround.
> [TempestRemap] linking against libblastrampoline causes segfaults in some utilities so switch to OpenBLAS32

- Q/QDLDL/build_tarballs.jl
- Q/qdldl/build_tarballs.jl
This is for the qdldl library for solving quasidefinite symmetric systems. 
Provides support for both `Float32` and `Float64` types, available as separate shared libraries.
> New Recipe: qdldl v0.1.5

- P/P4est/build_tarballs.jl
* Use p4est v2.8 which is the current stable release
* Compile p4est with MPI support (against MicrosoftMPI_jll on Windows and MPICH_jll on all other platforms)
* Compilation with MPI enabled fails for 32 bit Windows, hence that platform is no longer supported
cc @sloede
> Update P4est to v2.8 and enable MPI support

- T/Tar/build_tarballs.jl
The use of `acl_jll` caused a lot of troubles in https://github.com/staticfloat/Sandbox.jl/pull/51, revert it.
> [Tar] Build without `acl_jll`

- J/jlqml/build_tarballs.jl
Needed to make QML.jl work on Julia 1.7
> [jlqml] Bump version to v0.3

- B/blaspp/build_tarballs.jl
Build system isn't really built to handle LBT. Next release of SLATE I will try again on LBT. Just want it running in the meantime.
> [blaspp] Revert to openblas32 instead of LBT

- I/IOAPI/build_tarballs.jl
- M/MDAL/build_tarballs.jl
- N/NetCDFF/build_tarballs.jl
- T/TempestModel/build_tarballs.jl
NetCDF broke the ABI in the 4.7 -> 4.8 transition (the major soversion changed
from 18 to 19), so we always must specify the compat of packages depending on
it.
PR companion to https://github.com/JuliaRegistries/General/pull/53508.
> Fix compat bounds of packages depending on NetCDF_jll

- T/TempestRemap/build_tarballs.jl
We want to use NetCDF 4.7, the build of 4.8 has many problems.
> [TempestRemap] Fix compat of NetCDF

- R/rocm_smi_lib/build_tarballs.jl
Different ROCm versions promise support for different AMD hardware,
so bumping to a newer version immediately after submitting 4.0.0.
> Bump rocm_smi_lib to 4.2.0

- A/Arpack/build_tarballs.jl
This requires Julia v1.7 but makes it possible to use it correctly on aarch64
platforms, where OpenBLAS now uses ILP64.
CC: @ViralBShah
> [Arpack] Build v3.5 also for experimental platforms

- L/libsass/build_tarballs.jl
Note: Gtk4 uses https://github.com/lazka/libsass/tree/meson, which is a fork built on top of 3.6.4 that only adds Meson as build system, without further changes, so it should hopefully work.
Ref: #3898
> [libsass] Update to v3.6.4 and build for all platforms

- D/Dbus/build_tarballs.jl
- F/Fontconfig/build_tarballs.jl
- G/GDAL/build_tarballs.jl
- G/Graphviz/build_tarballs.jl
- P/Python/build_tarballs.jl
- W/Wayland/build_tarballs.jl
PR #2996 was too restrictive, there are actually no incompatibilities which
require to restrict compats to ~2.2. I tested some dependent packgages with new
Expat_jll 2.4.4, they work fine.
Companion PR to https://github.com/JuliaRegistries/General/pull/53921
> Relax compat bounds with Expat_jll

- B/bottom/build_tarballs.jl
I tested locally only for `x86_64-linux-gnu`, we'll need to see if there are
problems for other platforms (it will likely fail for 32-bit Windows).
> [bottom] Add builder

- D/DuckDB/build_tarballs.jl
[0.3.2 Preview Release "Gibberifrons"](https://github.com/duckdb/duckdb/releases)
> DuckDB version 0.3.2

- M/MUMPS/MUMPS@5/build_tarballs.jl
We can compile MUMPS for PowerPC now, SCALAPACK 2.2.0 works for this platform.
Update: We also have the issue with PowerPC platform here in MUMPS....
I will keep the PR to add the flag `-fno-stack-check` for `Apple` platforms.
> Recompile MUMPS with -fno-stack-check flag for OSX

- L/LibCURL/build_tarballs.jl
URL has changed permanently from curl.haxx.se to curl.se. Also note to depends on MbedTLS 2.28 in this script.
I would consider holding this for a bit as some potential issues between LibCURL 7.81 and Julia are investigated:
https://github.com/JuliaLang/julia/issues/43682
However, I have built Julia master with curl 7.81.0 and MbedTLS 2.28 just fine locally on Linux.
> Bump (Lib)CURL to 7.81.0

- Q/QPALM/build_tarballs.jl
https://github.com/kul-optec/QPALM/releases/tag/1.0.0
QPALM was originally maintained by Ben Hermans at https://github.com/Benny44/QPALM_vLADEL, but will now be maintained in the kul-optec organization by myself and other members of the research group.
> [QPALM] Version 1.0.0

- H/HiGHS/build_tarballs.jl
Bumping HiGHS to a newer commit but leaving as v1.2.0 because the original v1.2.0 has some bugs which prevent usage with JuMP.
> [HiGHS] update v1.2.0

- C/CUDA/CUDA_full@10.2/build_tarballs.jl
Added CUDA 10.2 for aarch64-linux-gnu from the APT archives for Jetson.
> [CUDA_full] Added CUDA 10.2 for aarch64-linux-gnu

- M/ModularForms/build_tarballs.jl
Same as #4433, but GitHub closed the merge request after I force pushed the rebased commits.
ModularForms.jl is a new package (at https://gitlab.com/mraum/modularforms.jl) to compute with modular forms based on the Oscar CAS. These are the C dependencies that we use. The build script follows the pattern of, for example, FLINT, but the preferred GCC version was needed to complete local tests successfully.
As for the comment about Windows libs in the review, I only later realized that this would require ModularForms_jll_src to be adjusted, where we do not accept special casing for proprietary platforms. I narrowed down the target platforms accordingly.
> [ModularForms] new recipe

- C/ColPack/build_tarballs.jl
This is the binary for ColPack forked from https://github.com/CSCsw/ColPack . It should enable advanced coloring algorithms that can be used in SparseDiffTools.jl . A C interface was added and a ColPack.jl package will be published soon.
> New Recipe: ColPack v0.1.0

- H/HiGHS/HiGHS/build_tarballs.jl
This PR restores the build_tarballs.jl script for the dynamic build
of HiGHS. It was removed in #4456 to avoid rebuilding the binary.
[ci skip]
> [HiGHS] restore build_tarballs.jl

- B/blis/build_tarballs.jl
To resolve JuliaLinearAlgebra/BLIS.jl#8 .
This upgrade from `v0.8.0` to `v0.8.1` should be trivial. In fact, the upstream seems to be in a course of changing its versioning system.
Let me note here some non-trivial functionalities on current `master`:
- Compilation on macOS Aarch64. Now the aarch64 kernels should support both GCC and `clang`. (& Would it be OK to introduce xrq-phys/blis_apple@8912315 kernels)
- SVE kernels for Neoverse V1, etc. SVE kernels require GCC>=8 for basic support and GCC>=10 to fully compile.
> BLIS Support Aarch64-mac Platform, Version Push to HEAD v0.8.1+α

- X/XyceWrapper/build_tarballs.jl
I am not 100% of the mechanics here. Let's give this a shot :)
> XyceWrapper: support more julia versions

- B/blis/bundled/patches/bli_macro_defs.h.f77suffix64.patch
Resolves JuliaLinearAlgebra/libblastrampoline#36
Currently only level-1/2/3 S/D/C/Z routines are exported w/ `64_` suffix, while libblastrampoline identifies BLAS suffix against `isamax`. This causes the issue above. The patch here should resolve the issue and kickoff lbt+libblis.
> BLIS Append 64_ Suffix to All F77 Exported

- B/blis/build_tarballs.jl
- B/blis/bundled/patches/a64fx_config_screen_sector_cache.patch
- B/blis/bundled/patches/armsve_config_screen_non_sve.patch
- B/blis/bundled/patches/armsve_kernels_unscreen_arm_sve_h.patch
- B/blis/bundled/patches/config_registry.metaconfig+armsve.patch
Both SVE configs are added:
- `armsve` the generic one.
- `a64fx` the A64FX one.
Runtime detection supported by upstream.
Select to bypass `-march` limitation since we're building a fat-lib.
Sorry for having opened yet another issue :D
> Include Arm SVE in Config arm64

- L/libjulia/build_tarballs.jl
- L/libjulia/bundled/libunwind-julia-1.6.patch
- L/libjulia/common.jl
This is experimental. I still need to verify that the result can
be used to build other JLLs using `libjulia_jll`. But I thought
it'd be good to already collect feedback here.
[skip ci] [skip build]﻿
> libjulia_jll: turn LibOSXUnwind_jll into a build dep for Julia 1.6

- C/CMake/build_tarballs.jl
As noticed in https://github.com/maleadt/LLVM.jl/pull/294, it's currently a Linux-only recipe.
> [CMake] Update to v3.22.2 and build for more platforms

- L/libsharp2/build_tarballs.jl
Testing on a relatively recent Cascade Lake machine suggests that Libsharp is really an anomaly, and O3 has a factor of three (!) performance difference.
@ziotom78 
I think this will close https://github.com/ziotom78/Libsharp.jl/issues/2
> [libsharp] add -O3 CFLAGS

- L/LLVMExtra/build_tarballs.jl
- platforms/llvm.jl
Same as https://github.com/JuliaPackaging/Yggdrasil/pull/4291, but for LLVMExtra.
> Rework LLVMExtra using augmented platforms.

- L/Libtiff/build_tarballs.jl
@Crghilardi added LERC to Yggdrasil 👍🏻. Ping to @visr because of #4537 which can be closed if this works.
> Add LERC compression to libtiff

- L/LAMMPS/build_tarballs.jl
- platforms/mpi.jl
Based off https://github.com/JuliaParallel/MPI.jl/pull/541 (but also independent enough that we can use it before that lands)
Replaces https://github.com/JuliaPackaging/Yggdrasil/pull/4073
> Add MPI platform tag and have LAMMPS use it

- M/Musl/build_tarballs.jl
- M/Musl/bundled/patches/qsort_r.patch
Currently in our environment we have
```console
% julia --compile=min -e 'using BinaryBuilderBase; BinaryBuilderBase.runshell(Platform("x86_64", "linux"; libc="musl"))'
sandbox:${WORKSPACE} # apk add binutils
fetch https://dl-cdn.alpinelinux.org/alpine/v3.15/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.15/community/x86_64/APKINDEX.tar.gz
(1/1) Installing binutils (2.37-r3)
Executing busybox-1.34.1-r3.trigger
OK: 294 MiB in 118 packages
sandbox:${WORKSPACE} # /usr/bin/readelf
Error relocating /usr/lib/libctf-nobfd.so.0: qsort_r: symbol not found
```
because Alpine Linux basically forked Musl in an ABI-incompatible way and some
binaries provided by Alpine Linux reference the Alpine-specific `qsort_r`
symbol, so we have to apply their patch in order to be able …
> [Musl] Add patch from Alpine Linux to use `qsort_r`

- C/CPUInfo/build_tarballs.jl
- C/CPUInfo/bundled/patches/lowercase-windows-include.patch
Packaging similar to [libcpuinfo0](https://packages.ubuntu.com/impish/libcpuinfo0) in Ubuntu.
Starting with an old version - used by PyTorch v1.5.
> New Recipe: CPUInfo v0.0.20200122

- E/eccodes/build_tarballs.jl
- E/eccodes/bundled/patches/kinds.patch
This updates the version of ecCodes and adds the fortran module and library, which we need for the subsequent JLL for the FLEXPART particle dispersion code.
> [ecCodes] Enable fortran and bump version

- P/PETSc/build_tarballs.jl
This is just a first attempt at building PETSc a little differently. It may be totally the wrong way to do it, but it achieves two things: keeps generated include files for each scalar type version, and avoids renaming.
I'm not sure the latter is necessary, but it helps me avoid symlinking/digging into build systems for packages that depend on `-lpetsc`.
> [PETSc] Attempt to rebuild with good include files (and don't rename libpetsc)

- P/PETSc/build_tarballs.jl
Silly typo in patchelf conditional meant we weren't getting new soname. Sorry for spam!
> [PETSc] Correct Typo

- C/CPUInfo/build_tarballs.jl
- C/CPUInfo/bundled/patches/lowercase-windows-include.patch
Referenced by Torch v1.6.0 - v1.7.1: https://github.com/pytorch/pytorch/tree/v1.7.1/third_party
via XNNPACK: https://github.com/google/XNNPACK/blob/1b354636b5942826547055252f3b359b54acff95/cmake/DownloadCpuinfo.cmake
> Changed CPUInfo recipe to build v0.0.20200228

- M/Metal_LLVM_Tools/build_tarballs.jl
For the upcoming Metal.jl package, we have a custom LLVM back-end capable of writing MetalLib archives (essentially LLVM bitcode, but packaged up differently). Instead of adding this back-end to the LLVM build of Julia (which we want to avoid, since it locks us to the Julia release cycle, while also adding questionable code to the Julia distribution everybody uses) I'm exploring a different approach here, instead building essentially a specialized `llc` that is only capable of generating MetalLib output: https://github.com/JuliaGPU/llvm-metal/tree/main/llvm/tools/metallib-as. We then generate and optimize LLVM IR using Julia's LLVM library as usual, but hand it of to `metallib-as` to generate machine code.
Apart from the many obvious advantages, this approach also has a couple of …
> Add initial recipe for Metal LLVM tools.

- L/LLVMCompilerRT/build_tarballs.jl
- L/LLVMCompilerRT/bundled/patches/do-not-codesign.patch
To build some packages for macOS we need libclang_rt.  In the long term
finishing up #1681 is a better option, but compiling a standalone compiler-rt
may be a good stop-gap solution.
> [LLVMCompilerRT] Add builder

- L/libsvm/build_tarballs.jl
Use `LLVMOpenMP_jll` to provide OpenMP on BSD systems, instead of using GCC.
CC: @aviks
> [libsvm] Update to v3.25

- L/LLVMOpenMP/build_tarballs.jl
New attempt at building OpenMP from LLVM 13.0.1, after #3271.  Main issue on
Linux was that we had to point to the right target `clang`, which is used to
build some files.  This currently fails on FreeBSD.
> [LLVMOpenMP] Upgrade to v13.0.1

- F/FastTransforms/build_tarballs.jl
@MikaelSlevinsky you may be interested in this.  It took us some time since
#2701, but LLVM OpenMP is finally available.  Let me know if you're OK with this
change.
> [FastTransforms] Use LLVM OpenMP on BSD systems

- L/LibYAML/build_tarballs.jl
Rebuild LibYAML to add support for macOS aarch64. It seems a `julia_compat` entry is required.
> Build LibYAML also for macOS aarch64

- F/finufft/build_tarballs.jl
- platforms/microarchitectures.jl
Fix #4252.  Need more testing, and also fixing https://github.com/JuliaPackaging/BinaryBuilder.jl/issues/1179.
> [finufft] Augment platforms by setting the microarchitecture

- C/cuQuantum/build_tarballs.jl
@maleadt does it look good?  These libraries require `libcublas.so.11` and `libcutensor.so.1`, how do we deal with the dependencies?  Also, this should correspond to CUDA 11.4, do we need to use tags?
CC: @kshyatt
> [cuQuantum] Add recipe

- C/CUDA/CUDA_Runtime/build_10.0.jl
- C/CUDA/CUDA_Runtime/build_10.2.jl
- C/CUDA/CUDA_Runtime/build_11.0.jl
- C/CUDA/CUDA_Runtime/build_11.1.jl
- C/CUDA/CUDA_Runtime/build_11.2.jl
- C/CUDA/CUDA_Runtime/build_11.3.jl
- C/CUDA/CUDA_Runtime/build_11.4.jl
- C/CUDA/CUDA_Runtime/build_11.5.jl
- C/CUDA/CUDA_Runtime/build_11.6.jl
- C/CUDA/CUDA_Runtime/build_tarballs.jl
- platforms/cuda.jl
This is an experimental JLL, working my way towards actually using JLLs to load the CUDA runtime libraries instead of doing everything ourselves in CUDA.jl. It uses the `cuda` platform tag to determine which CUDA toolkit to load (based on driver compatibility and toolkit availability). That tag can then used by dependent JLLs, like CUDNN, to determine which library to load.
Note that I didn't use a comparison strategy for determining which toolkit artifact to load. Instead, I'm using plain equality, but providing the list of available toolkits to `augment_platform!` instead (essentially embedding that in the generated JLL). This results in the platform tag containing the actual toolkit loaded, instead of the host's compatibility, which should make it easier for dependent JLLs to determine …
> Add a CUDA JLL for actually loading the runtime libraries.

- H/hyper/build_tarballs.jl
According to https://docs.rs/hyper/latest/hyper/ffi/index.html, the C API of hyper is not compiled by default. Extra options and environment variables need to be set to make the C API work.
> [hyper] Actually compile the C API

- L/libmseed/build_tarballs.jl
libmseed (https://github.com/iris-edu/libmseed) is a library for
reading and writing data in the miniSEED format, usually obtained
from seismic recordings.
> [libmseed] Add recipe for libmseed v3.0.9

- T/tree_sitter_highlight/build_tarballs.jl
The crate type is coded to be staticlib or lib but using rustc --crate-type we can create a shared library.
> add libtree_sitter_highlight

- P/pprof/build_tarballs.jl
Bump pprof upstream commit to [`b5a4dc8f4f2afdee77047b6aae3834140efc83ed`](https://github.com/google/pprof/commit/b5a4dc8f4f2afdee77047b6aae3834140efc83ed).
While I'm here, I've gone ahead and upgraded this to be v1.0 instead of v0.2 or v0.1.2, since i think it's been pretty stable. I definitely feel comfortable calling this "v1.0 ready"!
This PR picks up @vilterp's https://github.com/google/pprof/pull/684, which fixes a bug we encounter from julia's PProf, where large flamegraphs don't render (julia hits this more than other languages, since we print full method signatures with arbitrarily large type names): https://github.com/google/pprof/issues/663.
Upstream changes in this release:
https://github.com/google/pprof/compare/20978b51388db0648809a2c5cc88b494c7945ec1...b5a4dc8f4f2afdee77047b …
> Bump pprof to latest release b5a4dc8f4f2afdee77047b6aae3834140efc83ed & release v1.0

- R/RadeonProRender/build_tarballs.jl
This updates the version of RadeonProRender to [v2.02.12](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderSDK/commit/e284dfac04ee3a142603ba955a2bf8d11a78d945), released in March 2022.  Additionally, it adds Mac M1 as a build target, given that the website claims it can run on M1 chips as well.
> Update RadeonProRender version, build on macos aarch64

- P/PETSc/build_tarballs.jl
- P/PETSc/bundled/patches/mingw-version.patch
- P/PETSc/bundled/patches/sosuffix.patch
@giordano is it possible to relax the requirement that the file must end in `dll`? If not I will need to fix the petsc build system to not produce files like that.
cc: @boriskaus
> Patch PETSc build instead of moving files

- K/Kerberos_MIT_krb5/build_tarballs.jl
- K/Kerberos_krb5/build_tarballs.jl
This adds MIT Kerberos v5 (aka krb5) for Linux.
I'm not able to make builds for mac or windows work.
On the [download page](https://web.mit.edu/kerberos/dist/) there are binaries for windows but I'm not sure how to install those though BinaryBuilder.
> krb5 for linux

- platforms/mpi.jl
The library that provides the MPI implementation (i.e. the ABI against which the packages link) is provided by MPItrampoline, not MPIwrapper.
> Change MPItrampoline's ABI name to `MPItrampoline`

- P/Pfapack/build_tarballs.jl
[PFAPACK](https://michaelwimmer.org/downloads.html) / [ACM Trans. Math. Software 38 30 (2012)](https://dl.acm.org/doi/10.1145/2331130.2331138) is a Fortran package for computing LTL' factorization of antisymmetric matrices.
This package's in Fortran but makes no reference to `libgfortran`. I'm currently keep the Fortran build but later it can be replaced by F2C.
> New Recipe: Pfapack v0.1.0

- M/Musl/build_tarballs.jl
Without this, our default `musl` in the BB rootfs has the SONAME `libc.musl-.so.1`:
```
Dynamic section at offset 0x94928 contains 18 entries:
Tag        Type                         Name/Value
0x000000000000000e (SONAME)             Library soname: [libc.musl-.so.1]
```
Note that this doesn't really affect things built with BB, it only affects things built by an `apk`-supplied GCC.
> Fix musl SONAME

- A/AcousticsToolbox/build_tarballs.jl
Executables for "AcousticsToolbox" FORTRAN code for Ocean Acoustic Modeling.
Original homepage:
http://oalib.hlsresearch.com/AcousticsToolbox/
For use in https://github.com/org-arl/UnderwaterAcoustics.jl to support models from this toolbox.
> New recipe: AcousticsToolbox v2002_11_4

- L/libjulia/common.jl
There have been changes in 1.9 that affect binary compatibility, see https://github.com/JuliaInterop/CxxWrap.jl/pull/318
> [libjulia] Update dev versions for 1.8 and 1.9

- H/HPTT/build_tarballs.jl
- H/HPTT/bundled/patches/clang_compatibility.patch
This adds the HPTT library (High Performance Tensor Transposition), original version here:
https://github.com/springer13/hptt
I plan to use this library in forthcoming versions of [TensorOperations.jl](https://github.com/Jutho/TensorOperations.jl), and it can also be useful to other tensor libraries.
The patch fixes compatibility with clang, and corresponds to the changes of PR https://github.com/springer13/hptt/pull/16 .
While the library promises dedicated optimisations for the ARM platform, these lead to compiler issues ( believe the original source file does contain bugs or is broken), so I decided to fall back to the general build flags on this platform and to disable specific optimisations.
On Intel platforms, I enable avx optimisations, which yields a warning that I cannot assume …
> New recipe: High Performance Tensor Transposition library (v1.0.5)

- 0_RootFS/Rootfs/bundled/libs/libc/download_libcs.sh
- G/GCCBootstrap/build_tarballs.jl
- G/GCCBootstrap/bundled/gen_config.sh
- G/GCCBootstrap/bundled/patches/glibc/2.19/0100-sunrpc_on_musl.patch
- G/GCCBootstrap/bundled/patches/glibc/2.19/0101-ppc64le_mtfsf.patch
TODO before merging:
on all platforms right now; this is fine, because this glibc is not
what will be used in production, and it mostly affects what version of
glibc must be available on the _host_ system when compiling, not on the
_target_ system when running things built with this compiler.  So by
using 2.19 here, we simply make it impossible to use BinaryBuilder on
ancient CentOS systems, which I'm okay with.
```
/tmp/bin # ./x86_64-linux-gnu-readelf -d ./x86_64-linux-gnu-gcc
Dynamic section at offset 0x1f7a18 contains 21 entries:
Tag        Type                         Name/Value
0x0000000000000001 (NEEDED)             Shared library: [libc.musl-.so.1]
```
UPDATE: This will be fixed by a new RootFS containing: https://github.com/JuliaPackaging/Yggdrasil/pull/4762, which is currently …
> Try building a `GCCBootstrap_jll` using `crosstool-ng`

- P/Pfapack/build_tarballs.jl
CC: @xrq-phys.  I hope this will work :slightly_smiling_face:
> [Pfapack] Deal with different versions of libblastrampoline

- B/blis/build_tarballs.jl
- B/blis/bundled/patches/armsve_config_screen_non_sve.patch
- B/blis/bundled/patches/armsve_kernels_unscreen_arm_sve_h.patch
- B/blis/bundled/patches/config_registry.metaconfig+a64fx.patch
- B/blis/bundled/patches/config_registry.metaconfig+armsve.patch
Not that big update.
The build script for v0.8.1 was already building pre-0.9 instead of tag 0.8.1
> [BLIS] Upgrade to v0.9

- F/FastME/build_tarballs.jl
I am having an error compiling when glibc is not available on linux-musl and apple platforms
```
[13:38:50] Undefined symbols for architecture arm64:
[13:38:50]   "_rpl_realloc", referenced from:
[13:38:50]       _Read_Branch_Label in p_bootstrap.o
[13:38:50]       _Make_New_Edge_Label in p_bootstrap.o
[13:38:50] ld: symbol(s) not found for architecture arm64
```
Not sure if there is anything I can do to easily fix it, so I limited the available platforms.
> New recipe: FastME-v2.1.6

- G/GTK4/build_tarballs.jl
The absence of `gschemas.compiled` in `${prefix}/share/glib-2.0/schemas` breaks some dialogs (https://github.com/JuliaGtk/Gtk4.jl/issues/2). This PR just adds a call to `glib-compile-schemas` after installation to create that file. A post-install script that does this in the build of GTK3 is not run for GTK4 when cross compiling.
The post-install script does other stuff:
• calling `gtk_update_icon_cache` is not necessary, I think, since we're not compiling `gtk4-demo`
• updating module cache for print backends -- I tried adding this but the output file `giomodule.cache` didn't end up in the tarball -- printing isn't a high priority IMHO anyway
• updating module cache for media backends isn't relevant since none are built
Since these other items don't seem necessary/important, I opted to …
> [GTK4] add call to glib-compile-schemas

- L/LibCURL/LibCURL/build_tarballs.jl
- L/LibCURL/common.jl
This adds Kerberos support to LibCURL on Linux.
The Kerberos_krb5 package also support FreeBSD, but compiling LibCURL for FreeBSD with kerberos enabled fails with this error:
```
[17:01:46] checking for sys/socket.h... (cached) yes
[17:01:46] checking for recv... no
[17:01:46] configure: error: Unable to link function recv
[17:01:46]  ---> ./configure --prefix=$prefix --host=$target --build=${MACHTYPE} "${FLAGS[@]}"
[17:01:46]  ---> ./configure --prefix=$prefix --host=$target --build=${MACHTYPE} "${FLAGS[@]}"
[17:01:46] Previous command exited with 1
[17:01:46] Child Process exited, exit code 1
┌ Warning: Build failed, the following log files were generated:
│   - ${WORKSPACE}/srcdir/curl-7.81.0/config.log
│ 
│ Launching debug shell:
└ @ BinaryBuilder …
```
> Add kerberos support to LibCURL on linux

- J/jlqml/build_tarballs.jl
This should make QML.jl work on M1 and with the new libcxxwrap also on Julia nightly.
> [jlqml] Add Apple M1 support

- F/FlexExtract/build_tarballs.jl
- F/FlexExtract/bundled/patches/flexextract-makefile.patch
This comes from the split of #4627 into two separated packages.
[flex_extract](https://www.flexpart.eu/flex_extract/index.html) is a software to retrieve meteorological fields from ECMWF and prepare them to be input of [FLEXPART](https://www.flexpart.eu/). This recipe provides the `calc_etadot` binary needed to post-process the meteorological fields.
> New recipe: FlexExtract v7.1.2

- O/OptimPack/build_tarballs.jl
- Status returned by `BOBYQA`, `COBYLA`, and `NEWUOA` algorithms are now enumerations.
- Names of functions, types, and macros no longer start with an underscore (reserved to future development of the C language).  Names of types, structures, and enumerations no longer have a `_t` suffix.  Names of opaque structures have a trailing underscore.  File [`tools/update_3p1_to_3p2`](tools/update_3p1_to_3p2) provides a simple Perl script to make the necessary changes in your code.
> Update for OptimPack version 3.2.0

- B/blis/build_tarballs.jl
- B/blis/bundled/nthreads64_.c
Cf. JuliaLinearAlgebra/BLIS.jl#3
- 32-bit machines can call `bli_thread_set_num_threads` with 32-bit integers. `dim_t` in this case is also 32-bit.
- 64-bit machines can call `bli_thread_set_num_threads64_` with 32-bit integers (as is done in `libblastrampoline`). The additional `nthreads64_.c` converts it to 64-bit `dim_t` types.
F77-style `bli_thread_set_num_threads_` and `bli_thread_set_num_threads_64_` are left alone.
> Import libblastrampoline-Style Num. Threads Setter / Getter

- S/SDPA/build_tarballs.jl
Needed to fix SDPA.jl on Julia v1.7, see https://github.com/jump-dev/SDPA.jl/issues/34
Largely inspired from https://github.com/JuliaPackaging/Yggdrasil/pull/4264
cc @barche
> Fix SDPA_jll for Julia v1.7

- A/AWSCRT/build_tarballs.jl
- A/AWSCRT/bundled/awscrt/CMakeLists.txt
This PR includes all cross-platform CRT libraries in the archive (so all except for aws-lc and s2n-tls). This is done to include some missing symbols I found in my testing.
> [AWSCRT] Include all cross-platform libraries in the archive

- G/GAP/build_tarballs.jl
- G/GAP/bundled/patches/kernel-tweak-Julia-integration.patch
This way we don't have to recompile against new libjulia builds as often
> [GAP] Avoid access to members of Julia kernel structs

- G/GAP/build_tarballs.jl
- G/GAP/bundled/patches/kernel-tweak-Julia-integration.patch
<s>A build problem was previously hidden as a compiler warning, so turn those
into errors.</s>
Also remove some unused code, and add missing prototype for
`jl_get_current_task` in Julia 1.7 (this was causing crashes).
> GAP: fix crash with Julia 1.7

- G/GAP/build_tarballs.jl
- G/GAP/bundled/patches/kernel-fix-FreeBSD-compiler-warning.patch
A build problem was previously hidden as a compiler warning, so turn those into errors.
> GAP: rebuild with -Werror to catch problems sooner

- T/Telescope/build_tarballs.jl
Some platforms fail saying that Bullet needs to be recompiled with -fPIC. Fair enough, I overlooked that in my original PR, it's an easy fix.
Others fail saying that they can't find the header files for SDL Mixer, which...I'm going to need some help figuring out.
> New Telescope version

- Q/Qt6ShaderTools/build_tarballs.jl
Similarly to Qt6Base, this package needs to be built for the host first and then becomes a build dependency for the other platforms. It is a dependency of Qt6Declarative, which is the main library needed for QML.jl.
> [Qt6ShaderTools] New package, host build

- O/OpenSSH/build_tarballs.jl
Ref: https://github.com/JuliaDocs/DocumenterTools.jl/pull/56
> [OpenSSH] Avoid linking to `libcrypt.so.1` on glibc systems

- J/jlqml/build_tarballs.jl
New version that depends on Qt6. The Qt5 support remains in 0.3, but no further updates there are planned.
> [jlqml] Version 0.4 (Qt 6)

- D/dlfcn_win32/build_tarballs.jl
This adds [dlfcn-win32](https://github.com/dlfcn-win32/dlfcn-win32)
> dlfcn-win32 is an implementation of dlfcn for Windows.
>dlfcn is a set of functions that allows runtime dynamic library loading. It is standardized in the POSIX. Windows also provide similar routines, but not in a POSIX-compatible way. This library attempts to implement a wrapper around the Windows functions to make programs written for POSIX that use dlfcn work in Windows without any modifications.
> [dlfcn-win32] init

- M/MPICH/build_tarballs.jl
The current value of `CROSS_F90_ADDRESS_KIND` is wrong for 32-bit architectures. This value is used only in Fortran.
I am also adding some other specifications that most likely have no effect, but I added them for completeness.
> MPICH: Correct CROSS_F90_ADDRESS_KIND for 32-bit architectures

- N/NodeJS/NodeJS_16/build_tarballs.jl
This was just done in the web editor based off the checksums in https://nodejs.org/dist/v16.15.0/SHASUMS256.txt, so fingers crossed I did the copy pasting correctly.
> Update `NodeJS_16` to latest LTS 16.15.0

- O/OCCT/build_tarballs.jl
Fix undefined reference linker errors for `backtrace` and `backtrace_symbols`, similar to existing fix for `musl` Linux builds.
> Fix OCCT build for FreeBSD

- O/OCCT/build_tarballs.jl
No need to restrict platforms for C++03 ABI.
> OpenCASCADE C++03 ABI build for Windows

- G/gmsh/build_tarballs.jl
Updates Gmsh to v4.10.2 and configures to use OpenCASCADE, FLTK, and MMG dependencies.
Depends on #4888 and #4891.
> [gmsh] Update to v4.10.2 and use MMG, FLTK, and OpenCASCADE

- C/cmark/build_tarballs.jl
- C/cmark_gfm/build_tarballs.jl
Adds recipes for the [cmark CommonMark parser](https://github.com/commonmark/cmark) and its GitHub-flavored cousin [cmark-gfm](https://github.com/github/cmark-gfm).
cmark-gfm is basically cmark with a couple of small additions (although it appears to be slightly behind with versions), so I was initially thinking of putting under the same directory. But in the end it was easier to organize it this way for now, but happy to change that if need be.
> [cmark] Add recipes for cmark and cmark-gfm

- G/GPI2/build_tarballs.jl
GPI-2 is an API for the development of scalable, asynchronous and fault tolerant parallel applications.
Source: http://gpi-site.com/ (yes, `http` 😦)
Source: https://github.com/cc-hpc-itwm/GPI-2
This adds a `build_tarballs.jl` for GPI-2 that only uses Ethernet for convenience. If you want to do actual production runs, you want to use a system-local installation of GPI-2 that exploits the local Infiniband drivers.
> Add GPI-2 library for the development of scalable, parallel applications

- C/cmark_gfm/build_tarballs.jl
Following up on #4917: I had forgotten that the GFM library provides two separate shared libraries.
> [cmark-gfm] Declare second .so as a LibraryProduct

- C/cmark_gfm/build_tarballs.jl
- C/cmark_gfm/bundled/patches/extension_type_exports.patch
There are a few global variables that I need to access, but they're not available on Windows with `dlsym` right now. This patch should fix that by exporting them properly on Windows too.
X-ref: https://github.com/github/cmark-gfm/issues/263
> [cmark_gfm] Apply patch to export node types on Windows

- L/LibGit2/build_tarballs.jl
In the [previous build](https://dev.azure.com/JuliaPackaging/Yggdrasil/_build/results?buildId=19752&view=logs&j=012419e0-1f0d-5c7f-8376-cde93101c5d2&t=67007929-a8f9-5c00-96b4-44d560c75917&l=323) we had
```
[17:31:54] -- LIBSSH2 not found. Set CMAKE_PREFIX_PATH if it is installed outside of the default search path.
```
It looks like simply setting `USE_SSH=ON` ([default is `OFF`](https://github.com/libgit2/libgit2/blob/bdab22384cc61d315005a65456a9f9563bb27c8f/CMakeLists.txt#L30)) is sufficient to convince CMake to find libssh (if the search would fail, CMake configuration should [error out](https://github.com/libgit2/libgit2/blob/23c5c315d5f6a3e93cdb1bf1f51016fbacb86881/cmake/SelectSSH.cmake#L13) when `USE_SSH=ON`).  This should hopefully help with …
> [LibGit2] Explicitly request SSH support

- N/NetCDF/NetCDF@julia-1.8/build_tarballs.jl
- N/NetCDF/bundled/patches/0004-save-rc-in-globalstate-rcinfo.triples.patch
This is a (partial) back-port of upstream patch  https://github.com/Unidata/netcdf-c/pull/2352 to address (or work-around) the issue described in:
* https://github.com/Alexander-Barth/NCDatasets.jl/issues/173
* https://github.com/JuliaPackaging/Yggdrasil/issues/4843
My original PR https://github.com/Unidata/netcdf-c/pull/2347  was merged into the PR https://github.com/Unidata/netcdf-c/pull/2352.
> [NetCDF] add patch related to https://github.com/Unidata/netcdf-c/pull/2352

- G/Glibc/DebianGlibc@2.33/build_tarballs.jl
- G/Glibc/DebianGlibc@2.33/bundled/patches/glibc-003-sunrpc_on_musl.patch
- G/Glibc/common.jl
This builds a replacement glibc for use in debian testing images
that need to be compatible with rr (such as our JuliaCI images).
Due an interaction between libgcc and glibc, current versions of
these dependencies currently, intermittently, result in
rr-incompatible binaries due to an accidental use of legacy atomics
instructions. Building with `-march=armv8.3-a -mno-outline-atomics`
works around this issue at the cost of losing compatibility with pre-8.3
ARMv8. The product of this builder can be applied with `tar -C / xf`
over an existing debian rootfs to work around this issue while we
work with upstream to correct it.
cc @DilumAluthge
> Add DebianGlibc@2.33 for aarch64-linux-gnu

- G/Glibc/DebianGlibc@2.33/build_tarballs.jl
- G/Glibc/common.jl
Plus an issue with bash expansion when the path is actually taken.
> DebianGlibc: Fix typo

- K/Kaleido/build_tarballs.jl
Kaleido updated to 0.2.1 from new [releases](https://github.com/plotly/Kaleido/releases). This added support for macOS aarch64. `julia_compat` is now set to "1.6" for build_tarballs. With these changes, Plotly figures can be saved to image files under aarch64-julia in macOS.
> Kaleido updated to 0.2.1 + macOS aarch64 support

- L/LibCURL/LibCURL/build_tarballs.jl
- L/LibCURL/common.jl
We'll consider bringing it back later, but for the time being we need to remove
support for Kerberos.
> [LibCURL] Remove Kerberos

- G/GDAL/build_tarballs.jl
Soon we will have to transition the build script to CMake, see the first point of the [changelog](https://github.com/OSGeo/gdal/blob/v3.5.0/NEWS.md):
> [RFC 84](https://gdal.org/development/rfc/rfc84_cmake.html):
Addition of a CMake build system, which deprecates the existing
autoconf/automake and nmake build systems, that will be removed
in GDAL 3.6.0. Users are encouraged to adopt the new CMake build system.
Documentation of the CMake build system is at
https://gdal.org/build_hints.html.
But let's first just get a GDAL 3.5 build using what works now.
> [GDAL] build version 3.5.0

- L/LinearSampling/build_tarballs.jl
Here is a new recipe for the program LinearSampling, which implements linear-time RNA structural sampling.
https://github.com/LinearFold/LinearSampling
I took the last git commit as there isn't any released version yet on github.  There have been some recent commits but no changes to the code since last year.
I have already added support for calling LinearSampling_jll in the linearsampling-and-turbofold branch of my repo LinearFold.jl:
https://github.com/marcom/LinearFold.jl/tree/sampling-and-turbofold
> new recipe: LinearSampling, version is a git snapshot

- L/LinearTurboFold/build_tarballs.jl
Here is a new recipe for the program LinearTurboFold, which implements linear-time RNA multiple sequence alignment and simultaneous structure prediction.
https://github.com/LinearFold/LinearTurboFold
I took the last git commit as there isn't any released version yet on github.
The paper appeared 9 Dec, 2021:
https://www.pnas.org/doi/10.1073/pnas.2116269118
I have already added support for calling LinearTurboFold_jll in the linearsampling-and-turbofold branch of my repo LinearFold.jl:
https://github.com/marcom/LinearFold.jl/tree/sampling-and-turbofold
> new recipe: LinearTurboFold, version is from git commit

- S/SoapyRTLSDR/build_tarballs.jl
```
Release 0.3.3 (2022-06-04)
==========================
- Add setting for test mode (#60)
- Add getSampleRateRange (closes #54)
```
via: https://github.com/pothosware/SoapyRTLSDR/blob/80c93fbe189def3ab68d47a6ad3f813f96d3cb99/Changelog.txt#L1-L5
> [SoapyRTLSDR] Bump to 3.3

- S/SoapyLoopback/build_tarballs.jl
This adds [SoapyLoopback](https://github.com/JuliaTelecom/SoapyLoopback), a simple package used for testing [SoapySDR.jl](https://github.com/JuliaTelecom/SoapySDR.jl).
> [SoapyLoopback] init

- G/GibbsSeaWater/build_tarballs.jl
> GibbsSeaWater_jll update

- G/GSL/GSL@2/build_tarballs.jl
Do we need to increase the "official" version number to 2.7.2, or should we keep it at 2.7.1?
> GSL: New version 2.7.1

- C/casacorewrapper/build_tarballs.jl
I'm cleaning up, updating, and packaging Michael Eastwood's wrapper for casacore from [here](https://github.com/mweastwood/CasaCore.jl), this should be good to go. Only sticky bit is that we need at least GCC 6, not sure why.
Here is the repo https://github.com/kiranshila/casascorewrapper/
This is part of the greater effort of updating [CasaCore.jl](https://github.com/mweastwood/CasaCore.jl) to modern julia.
> [casacorewrapper] Release v0.1.0

- B/boost/build_tarballs.jl
This adds several compression options (gzip, deflate, etc.) to boost::iostreams.
> Add Zlib support to Boost Iostreams

- L/LibGit2/build_tarballs.jl
- L/LibGit2/bundled/patches/libgit2-win32-ownership.patch
This patch from upstream (https://github.com/libgit2/libgit2/pull/6321) will fix the bug that prevents updating the dependency in julia currently: https://github.com/JuliaLang/julia/pull/45411#issuecomment-1159490130
> [LibGit2] Add patch to fix ownership check on Windows

- H/HELICS/build_tarballs.jl
Updates HELICS package to v2.8.1, the final bug fix release of the 2.x series. After this will be sorting out the issues with the 3.x Yggdrasil builds.
> [HELICS] update to v2.8.1

- 0_RootFS/Rust/build_tarballs.jl
Companion PR to https://github.com/JuliaPackaging/BinaryBuilderBase.jl/pull/251.
> [0_RootFS] Update Rust to v1.61.0

- G/gobject_introspection/build_tarballs.jl
Builds libgirepository, which reads XML and .typelib files containing info about GObject based libraries. It also includes XML, etc. for Glib and some other libraries that will be useful for testing the corresponding Julia package.
This only builds for x86_64-linux-gnu, which is all I need at the moment. The library builds fine for all platforms, but the XML output (and gi-scanner) don't for anything but x86_64-linux-*. Long term it would be nice to get that working -- I'm sure it's possible.
> New recipe: gobject-introspection

- S/SoapyMultiSDR/build_tarballs.jl
This adds https://github.com/pothosware/SoapyMultiSDR :
> Use multiple SoapySDR supported devices under a single device wrapper.
More documentation: https://github.com/pothosware/SoapyMultiSDR/wiki
> [soapyMultiSDR] init

- H/HDF5/build_tarballs.jl
To avoid other users to accidentally make a big mistake.  Ref: https://github.com/JuliaPackaging/Yggdrasil/pull/5065#issuecomment-1166247471.
> [HDF5] Expand comment about why we can't use C++ and Fortran libraries

- S/snappy/build_tarballs.jl
- S/snappy/bundled/patches/0001-Fix-compilation-for-older-GCC-and-Clang-versions.patch
We need to apply https://github.com/google/snappy/commit/8dd58a519f79f0742d4c68fbccb2aed2ddb651e8 to properly compile the library with GCC.  Ref: https://github.com/JuliaIO/Snappy.jl/issues/32 and https://github.com/JuliaIO/Snappy.jl/pull/35.
> [snappy] Add upstream patch to fix compilation of asm statements

- Q/qwtw/build_tarballs.jl
I realized that previous version hangs (in Linux only) on Julia's exit(). now this is fixed.
> [qwtw] update to version 2.12.1 (linux bug fixed)

- M/MAGEMin/build_tarballs.jl
We are happy to announce version 1.2.0. This brings a number of changes & improvements:
1. Updated the PGE solver to further improve stability and convergence
2. Added a Linear-Programming "legacy solver" to deal with failing PGE points and provide a slower back-up solution (mainly for water undersaturated cases) when cases do not converge.
3. Extended pseudocompound checks during PGE iterations to further improve convergence to global minimum
4. Added an option to provide bulk-rock composition in "wt fraction"
5. Added outputting of the system composition in "wt fraction" 
6. Corrected a minor biotite memory allocation mistake
7. Updated the documentation which now fully describes the content of the output structure. Added a "Tips and Issues" section to the documentation to report known …
> MAGEMin v1.2.0

- L/log4cplus/build_tarballs.jl
This PR adds a `build_tarballs.jl` for the [log4cplus](https://github.com/log4cplus/log4cplus) library. I originally wrote this using `2.0.7` probably close to a year ago but ran into issues with unit tests. A fix was merged upstream and  a new version was just released yesterday finally.
> add log4cplus

- M/MParT/build_tarballs.jl
- M/build_tarballs.jl
Adds a `build_tarballs.jl` for the [MParT repository](https://github.com/MeasureTransport/MParT).
> Create MParT build tarballs

- N/normaliz/build_tarballs.jl
Also remove an old workaround for libtool.
cc: @fingolfin
> [normaliz] bump to 3.9.3, build with flint 2.9

- L/LibSSH2/build_tarballs.jl
- L/LibSSH2/bundled/patches/0002-libssh2-fix-import-lib-name.patch
`liblibssh2.dll.a` ==> `libssh2.dll.a`
xref: JuliaLang/julia#45914
Do we need to inc version number to v"1.10.3"?
> [LibSSH2] Fix import lib name on windows

- L/libpolymake_julia/build_tarballs.jl
update flint to 2.9
drop support for 32bit platforms
> [libpolymake-julia] update to 0.8.1 for polymake 4.7

- L/libopenjpegextra/build_tarballs.jl
This one adds extra apis from openjpeg
The repository is at: https://github.com/ashwani-rathee/libopenjpegextra
> LibOpenJpegExtra basic library

- O/OpenMPI/build_tarballs.jl
Use `--enable-script-wrapper-compilers` to turn the compiler wrappers (`mpicc` etc.) into scripts instead of binaries. As scripts, they can be run in a cross-compiling environment, and I expect that cmake can then infer the MPI options. Currently, MPI options need to be specified manually for OpenMPI to work.
> OpenMPI: Use --enable-script-wrapper-compilers

- P/Python/build_tarballs.jl
Normally this should already be detected properly:
```
julia> using Python_jll
julia> run(Python_jll.python())
Python 3.8.1 (default, Aug  8 2021, 21:34:14)
[GCC 4.8.5] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.base_exec_prefix
'/home/tim/Julia/depot/artifacts/4dcd8a52e092c1e82cef8e0c0ed138b30c4cd17b'
```
However, when using Python via `libpython`, that doesn't seem to be the case:
```
julia> using GDB_jll # (WIP, with Python integration)
julia> run(GDB_jll.gdb())
Could not find platform independent libraries <prefix>
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
```
Explicitly setting `PYTHONHOME` (to the same value it should have been autodetected) fixes …
> Specify PYTHONHOME during loading of Python_jll.

- P/Python/build_tarballs.jl
I accidentally filtered them all out, leading to a spectacular failure.
Let's also try enabling the previously-disabled `armv6l` platform; the recipe didn't explain why it was disabled.
> Fix the Python platform specification.

- G/GDB/build_tarballs.jl
- G/GDB/bundled/python-cross-configure.sh
Our current GDB build doesn't ship python scripting support:
```
julia> using GDB_jll
julia> run(GDB_jll.gdb())
GNU gdb (GDB) 10.1
(gdb) python
>Scripting in the "Python" language is not supported in this copy of GDB.
```
Since I'm working on making BugReporting.jl use GDB_jll for its use of rr, which depends on [quite a bit](https://github.com/rr-debugger/rr/blob/329cbf86a763497fd085f38d59309bddcf031230/src/GdbCommandHandler.cc#L34-L177=) Python functionality to augment GDB, I'd like to add Python support and a Python_jll dep to our GDB_jll build.
Depends on https://github.com/JuliaPackaging/Yggdrasil/pull/5187.
> Add Python support to GDB_jll.

- N/normaliz/build_tarballs.jl
by adding the correct dependencies
and adding configure flag to enable openmp
I am not sure if the version bump is necessary for this change of dependencies.
> [normaliz] enable openmp for all platforms

- P/polymake/build_tarballs.jl
The last update enabling OpenMP for more polymake platforms did unfortunately break some specific Oscar.jl tests because Apple disabled openmp support in their compilers (why?) and the `-fopenmp` flag from the config is not accepted at runtime (polymake does need to compile some C++ template instantiations at runtime).
So we remove this flag from the installed config file at the end.
@giordano a quick merge would be appreciated, thanks!
> [polymake] fixup: remove openmp flag from config for compiling at runtime on macos

- platforms/mpi.jl
This avoids the wrong SOVERSIONs in earlier versions of MPItrampoline.
> mpi.jl: Require version 5 of MPItrampoline

- P/Python/build_tarballs.jl
Starting with Bzip2_jll 1.0.8, macOS has a stable SONAME.
Ref https://github.com/JuliaPackaging/Yggdrasil/pull/2981
> Bump Python_jll's Bzip2 dependency.

- S/SBML/build_tarballs.jl
- S/SBML/bundled/patches/0001-FbcModelPlugin-C-API-for-createObjective-and-createG.patch
This adds code from https://github.com/sbmlteam/libsbml/pull/252 to allow
development and deployment before upstream merges and releases the patched
version.
> [SBML] FbcModelPlugin missing functions patch

- L/LAMMPS/build_tarballs.jl
- Don't expand gfortran versions
- Build with libgfortran3 as well
- Avoid platforms where the MPI implementation doesn't exist
> LAMMPS: Require MPItrampoline 5

- P/PTSCOTCH/build_tarballs.jl
It's easy if cmake auto-detects OpenMPI.
> PTSCOTCH: Require MPItrampoline 5, and build with OpenMPI as well

- I/iso_codes/build_tarballs.jl
Updating the build for `iso_codes` version 4.10. This required:
- Accounting for the change in format of the git tag used on released versions.
- Adding `apk update` because it could not find `libxml2` otherwise.
Here is the full output if you miss out `apk update`:
```
[ Info: Building for any
[ Info: Downloading https://salsa.debian.org/iso-codes-team/iso-codes/-/archive/iso-codes-4.3/iso-codes-iso-codes-4.3.tar.bz2 to /home/cjdoris/.julia/packages/BinaryBuilderBase/TwlYI/deps/downloads/6b539f915d02c957c45fce8133670811f1c36a1f1535d5af3dd95dc519d3c386-iso-codes-iso-codes-4.3.tar.bz2...
Downloaded artifact: Rootfs.v2022.4.15.x86_64-linux-musl.unpacked
Downloading artifact: Rootfs.v2022.4.15.x86_64-linux-musl.unpacked
[ Info: No hash cache found
[ Info: Calculated hash …
```
> iso_codes v4.10.0

- H/HDF5/build_tarballs.jl
NetCDF_jll is broken when building against the current HDF5_jll 1.12.1. This should resolve that issue, see @Alexander-Barth's comment in https://github.com/JuliaPackaging/Yggdrasil/issues/4511#issuecomment-1155003075.
This also bumps the MinGW dependencies, assuming it's fine to bundle `gcc-libs-12` instead of `gcc-libs-11` for 32 bit Windows, though I'd be happy to keep that as is as well.
> [HDF5] redistribute 1.12.2

- H/HDF5/build_tarballs.jl
While keeping the MinGW binaries at 1.12.2, for libnetcdf compatibility.
See discussion at https://github.com/JuliaPackaging/Yggdrasil/issues/4511#issuecomment-1198615732.
> [HDF5] revert conda-forge binaries to 1.12.1

- U/UserNSSandbox/build_tarballs.jl
It turns out that we don't have a valid `/etc/mtab` inside of our workers.
> [UserNSSandbox] Bump to read from /proc/self/mounts

- S/SoapyPlutoSDR/build_tarballs.jl
This is the latest git build, using libiio 0.24. 
This line breaks the Musl builds, but that should be fine for now: https://github.com/pothosware/SoapyPlutoSDR/blob/a07c37230369653818b3a5c448c00cee1ac9f8e5/CMakeLists.txt#L77
We drop libad9361_iio for now, since it is only used for filters and unsupported on latest libiio.
> [SoapyPlutoSDR] bump build

- M/mvndst/build_tarballs.jl
Add support for the Fortran library `mvndst`, required to remove Fortran code from https://github.com/computationalprivacy/CorrectMatch.jl.
> Add support for mvndst

- P/Python/build_tarballs.jl
Equivalent of https://github.com/JuliaPackaging/Yggdrasil/pull/4879.
Fixes:
```
ERROR: LoadError: InitError: could not load library "/home/pkgeval/.julia/artifacts/e1a397270be4e889bccc3bed5512d1e0fbac5979/lib/libpython3.8.so"
libcrypt.so.1: cannot open shared object file: No such file or directory
Stacktrace:
[1] dlopen(s::String, flags::UInt32; throw_error::Bool)
@ Base.Libc.Libdl ./libdl.jl:117
[2] dlopen(s::String, flags::UInt32)
@ Base.Libc.Libdl ./libdl.jl:116
[3] macro expansion
@ ~/.julia/packages/JLLWrappers/QpMQW/src/products/library_generators.jl:54 [inlined]
[4] __init__()
@ Python_jll ~/.julia/packages/Python_jll/myk8c/src/wrappers/x86_64-linux-gnu.jl:15
[5] _include_from_serialized(pkg::Base.PkgId, path::String, depmods::Vector{Any})
@ Base ./loading.jl:831
[6] …
```
> Python_jll: Avoid linking to `libcrypt.so.1` on glibc systems.

- W/WhiteboxTools/build_tarballs.jl
WhiteboxTools stopped doing GitHub releases, but there was a versioning issue in the latest release v2.0.0 that kept everything at v1.5. I want to fix this for my new [package](https://github.com/acgold/Whitebox.jl) that uses WhiteboxTools_jll.jl.
This PR:
- Bumps WhiteboxTools to v2.1.0
- Gets the latest version of the repo with `GitSource()` instead of `ArchiveSource()`
- Changes the working directory within the bash recipe (original code errored when I briefly tested locally)
> Update to WhiteboxTools 2.1.0

- F/FlangClassic/build_tarballs.jl
- F/FlangClassic/bundled/patches/0010-add-musl-triples.patch
- F/FlangClassic/bundled/patches/flang2-install-dir.patch
- F/FlangClassic/bundled/patches/musl-patches.patch
- F/FlangClassic/bundled/patches/no-fastmath.patch
- F/FlangClassic/bundled/patches/nosincos.patch
This adds a new recipe for "flang classic" (not to be confused
with LLVM's new flang which cannot yet generate code) from
https://github.com/flang-compiler/flang. Currently only
x86_64-linux-musl is supported because the build does complicated
bootstrap things to build its runtime library. The intent here
is to try to this in sanitizer builds of fortran-containing jlls,
so the musl version is sufficient (though we'll need to figure out
how to build the rtlib for each target).
> New Recipe: FlangClassic

- M/micromamba/build_tarballs.jl
This "builds" micromamba by grabbing the tarballs of the conda package for all supported platforms and extracting the executable.
> add micromamba

- V/VDT/build_tarballs.jl
VDT is a collection of fast and inline implementations of mathematical functions.
This package together with #5192 are needed for compilation of [ROOT](https://github.com/root-project/root).
> [VDT] new package

- K/kdb_c_api/build_tarballs.jl
* Package name: kdb_c_api
* Version: v2022.7.19
> Wizard recipe: kdb_c_api-v2022.7.19

- M/MParT/build_tarballs.jl
Bumps MParT version to 0.3.3. Moves `libmpartjl` into `lib`, hopefully fixes MacOS detection problem.
> Bump MParT version to 0.3.3

- M/MKL/build_tarballs.jl
Only the 64-bit binaries have 2022.1.0 updates at https://anaconda.org/intel/mkl/
> [MKL] Update to 2022.1.0

- N/NetCDF/build_tarballs.jl
* drop the c-flag `-std=c99`: the flag was necessary in the past, but this is longer the case. But more importantly, this flag triggers some memory issue and segmentation fault (https://github.com/Unidata/netcdf-c/issues/2486#issuecomment-1224285775, https://github.com/Alexander-Barth/NCDatasets.jl/issues/187)
* disable plugins: previously plugins are compiled on non-Windows platforms, but not installed. We can re-enable plugins once the upstream issues are solved (see https://github.com/JuliaPackaging/Yggdrasil/pull/5319#issuecomment-1217512599).
I tested my package NCDatasets with this NetCDF_jll, and I don't see any failure on Linux, Mac OS and Windows (all x86_64):
https://github.com/Alexander-Barth/NCDatasets.jl/actions/runs/2902145491
> [NetCDF] drop the c-flag -std=c99 and explicitly disable plugins

- G/GMP/GMP@6.2.1/build_tarballs.jl
- G/GMP/common.jl
> Add Msan build to GMP

- L/LibSSH2/build_tarballs.jl
> Build LibSSH2 with Msan

- G/glmnet/build_tarballs.jl
This is the most recent version of the glmnet library (tagged as [`2.0-13`](https://github.com/cran/glmnet/tree/2.0-13/src)) that works with the current (0.7) release of the GLMNet.jl package.
Trying to use the following [`2.0-16`](https://github.com/cran/glmnet/tree/2.0-16/src) release or any later version with the current GLMNet.jl results in a segfault. I am trying to figure this out, but have not yet been successful (see [here](https://discourse.julialang.org/t/help-with-updating-fortran-wrapper/86221) for more info). This problem occurs with v4.0.2 build that was added in #2028, this version has never been used by the GLMNet.jl package.
This version of the source is more recent than the JLL that is currently used by GLMNet.jl (which was added in #540 as v5.0.0, because confusingly …
> [glmnet] New version 2.0.13

- M/MariaDB_Connector_ODBC/build_tarballs.jl
The PR in the General registry https://github.com/JuliaRegistries/General/pull/67306 initially failed to load the package with
```
ERROR: InitError: could not load library "/tmp/jl_37WPXe/artifacts/5da83d1208b15cd03019a90afe1b30e61a28bbf3/lib/mariadb/libmaodbc.so"
libmariadb.so.3: cannot open shared object file: No such file or directory
```
This is explained by the fact
```
julia> using MariaDB_Connector_ODBC_jll
julia> run(addenv(`libtree -p $(libmaodbc)`, "LD_LIBRARY_PATH"=>MariaDB_Connector_ODBC_jll.LIBPATH[]));
/home/mose/.julia/artifacts/5da83d1208b15cd03019a90afe1b30e61a28bbf3/lib/mariadb/libmaodbc.so 
├── /home/mose/.julia/artifacts/84637f9dbc8f313838011977325eec613e7ca1bc/lib/libodbcinst.so.2 [LD_LIBRARY_PATH]
│   └── /lib/libpthread.so.0 [default path]
├── …
```
> [MariaDB_Connector_ODBC] Make `MariaDB_Connector_C` a runtime dependency

- G/gdk_pixbuf/build_tarballs.jl
Bump gdkpixbuf to 2.42.8 and include gobject-introspection data for x86_64-linux-gnu.
On Apple (both ARM and x86_64) I ran into a linker bug and copied a workaround from GTK4's build_tarballs.jl. (#3915)
My real motive here is to get more introspection data to use in Gtk4.jl. If this looks OK, I'd like to repeat this for libgtk's other GLib-based dependencies.
> [gdk_pixbuf] Update to 2.42.8, enable introspection for x86_64-linux-gnu

- L/libgeotiff/build_tarballs.jl
The current `Dependency("PROJ_jll"; compat="~900.0")`, which is also used in GDAL_jll, blocks PROJ_jll 900.100 that was just released.
The SOVERSION of PROJ 9.0 and 9.1 are the same, so I went for `Dependency("PROJ_jll"; compat="900")` to allow both. Or is it better to just allow compat of 9.1 and not higher?
Version and instructions around PROJ_SOVERSION:
https://github.com/OSGeo/PROJ/blob/9.1.0/CMakeLists.txt#L119
https://github.com/OSGeo/PROJ/blob/9.1.0/HOWTO-RELEASE#L36-L39
> [libgeotiff] allow PROJ 9.1 compat

- O/oneAPI_Support/build_tarball.jl
This is a recipe for the oneAPI support library, a set of extensions/wrappers to the oneAPI APIs that makes it possible for oneAPI.jl to invoke more functionality (similar to LLVMExtra). It's pretty hacky though:
- pulls binaries from Conda, both build- and run-time dependencies (removing the former from the prefix after build)
- uses Clang instead of GCC: it seems we are shipping Clang already, but without a mechanism to switch compilers?
But it's a good first step.
> Add recipe for oneAPI.jl's support library.

- M/MDAL/build_tarballs.jl
Windows builds have less drivers (due to NetCDF missing) than other platforms: https://github.com/evetion/MDAL.jl/actions/runs/2934632776
> [MDAL] Add tools, drivers

- R/ROCmLLVM/ROCmLLVM@5.2.3/build_tarballs.jl
- R/ROCmLLVM/ROCmLLVM@5.2.3/bundled/crt_patches/define-fp-magic.patch
- R/ROCmLLVM/ROCmLLVM@5.2.3/bundled/libcxx_patches/7005_libcxx_musl.patch
- R/ROCmLLVM/ROCmLLVM@5.2.3/bundled/patches/0050-unique_function_clang-sa.patch
- R/ROCmLLVM/ROCmLLVM@5.2.3/bundled/patches/0100-llvm-12-musl-bb.patch
- R/ROCmLLVM/ROCmLLVM@5.2.3/bundled/patches/0100-revert-sdk-requirement-tsan.patch
- R/ROCmLLVM/ROCmLLVM@5.2.3/bundled/patches/0101-fix-darwin-tsan-on-old-sdks.patch
- R/ROCmLLVM/ROCmLLVM@5.2.3/bundled/patches/0101-llvm-12-musl-bb-32.patch
- R/ROCmLLVM/ROCmLLVM@5.2.3/bundled/patches/0702-apple-codesign.patch
- R/ROCmLLVM/ROCmLLVM@5.2.3/bundled/patches/0703-apple-10..12.patch
- R/ROCmLLVM/common.jl
Patches are taken from respective LLVM_full recipe.
Added `define-fp-magic.patch` which is already fixed on master, but not in 5.2.3.
> Add ROCmLLVM 5.2.3

- G/GDAL/build_tarballs.jl
@visr 
Fixes #4950 (at least partially).
Uses the same approach as #5383, by only using NetCDF and HDF5 on the platforms where they are available. While this introduces a disparity between platforms, it helps the most common platforms (Windows, macOS, Linux gnu).
Platforms without HDF5 and NetCDF
- FreeBSD
- Linux
- musl
- i686
- arm
- powerpc
> [GDAL] Use NetCDF and HDF5 when available.

- O/oneAPI_Support/build_tarballs.jl
Biggest change is the change in version numbering; I realized that following the upstream version isn't great here, because we want to be able to independently version the API changes in our wrapper library (again, just like LLVMExtra_jll). Hopefully I can get this right with some changes to General in the registrator PR.
> Improvements to oneAPI support library

- T/Torch/build_tarballs.jl
- T/Torch/bundled/patches/pytorch-aten-qnnpack-cmake-windows.patch
- T/Torch/bundled/patches/pytorch-cmake-find-cuda.patch
- T/Torch/deps.md
Alternative to #4477, as that bumped into https://github.com/FluxML/Torch.jl/issues/17
Building Torch from source (for Linux and Linux with CUDA) would likely remedy (at least):
* https://github.com/FluxML/Torch.jl/issues/17
* https://github.com/FluxML/Torch.jl/issues/20
* https://github.com/FluxML/Torch.jl/issues/42
Related aims (but not the aim of this PR):
* Updating Torch version.
* Windows support.
* Windows + CUDA support.
* macOS support.
> Build Torch from source

- L/libRadtran/build_tarballs.jl
* Package name: libRadtran
* Version: v2.0.4
> Wizard recipe: libRadtran-v2.0.4

- P/Python/build_tarballs.jl
- P/Python/bundled/patches/libcrypt.patch
Alternative to https://github.com/JuliaPackaging/Yggdrasil/pull/5277 that actually works. Backports https://github.com/python/cpython/pull/28881 to our build of Python 3.8.
> Backport Python 3.11 patch to avoid linking against libcrypt.

- M/Metal_LLVM_Tools/build_tarballs.jl
```
❯ otool -L /Users/tim/Julia/depot/artifacts/0ec307395e9dd683100b6ecbb14963c6ddd232e6/bin/metallib-as
/Users/tim/Julia/depot/artifacts/0ec307395e9dd683100b6ecbb14963c6ddd232e6/bin/metallib-as:
/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1292.60.1)
@rpath/libz.1.dylib (compatibility version 1.0.0, current version 1.2.12)
/usr/lib/libncurses.5.4.dylib (compatibility version 5.4.0, current version 5.4.0)
/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 904.4.0)
```
I'm not sure where the ncurses use comes from... It doesn't happen with `llvm-as` (or any other tool) from LLVM_full_jll:
```
$ otool -L llvm-as
llvm-as:
@rpath/libLLVM.dylib (compatibility version 1.0.0, current version 14.0.6)
/usr/lib/libc++.1.dylib (compatibility version …
```
> Add Zlib and Ncurses dep to Metal LLVM tools

- L/libxcrypt/common.jl
- L/libxcrypt/libxcrypt/build_tarballs.jl
- L/libxcrypt/libxcrypt_legacy/build_tarballs.jl
`libxcrypt_legacy_jll` can be used as `RuntimeDependency` for packages that link to `libcrypt.so.1` from the old glibc that is used for building in BinaryBuilder (this is only built for glibc based platforms).
I tested this once by deploying this locally (x86_64-linux-gnu without libcrypt.so.1), loaded the `libxcrypt_legacy_jll` and then successfully loaded the (now obsolete) `Python_jll-3.8.8+2` with the libcrypt problem.
`libxcrypt_jll` which contains `libcrypt.so.2` can be used as a normal dependency for programs that need the crypt api, but this is untested. I am not sure how to make sure that this library will be used instead of the code from the old glibc, but maybe it just works.
This wont compile for mingw platforms, apart from a few minor errors that I was able to work around, …
> [libxcrypt] add new recipes

- Q/quarto/build_tarballs.jl
Repackages the entire upstream distribution from https://quarto.org/docs/download/. That distribution bundles `pandoc` and `deno`, among other things. 
Supports limited platforms, only those for which upstream binaries exist:
*  Platform("x86_64", "linux")
*  Platform("x86_64", "macos")
* Platform("x86_64", "windows")
Only lightly tested. Can successfully generate plain html and docx. PDF requires installing xelatex. Quarto attempts to install it. Code execution requires a jupyter installation plus a kernel. 
```
using quarto_jll
quarto() do quarto
run(`$quarto render test.qmd --to html`)
end
quarto() do quarto
run(`$quarto render test.qmd --to docx`)
end
```
Replaces #5269
Might be good to integrate with https://github.com/quarto-dev/quarto-julia at some point.
> New recipe: quarto

- S/SPEX/build_tarballs.jl
- S/SPEX/bundled/werror.patch
Not sure if the copying is done correctly. The makefile relies on being part of SuiteSparse, but it isn't currently set up that way.
> [SPEX] Add builder

- L/LFortran/build_tarballs.jl
* Package name: LFortran
* Version: v0.16.0
> Wizard recipe: LFortran-v0.16.0

- S/SCIP_PaPILO/build_tarballs.jl
As far as I understand, this is what was used before through IPOPT.  At least,
this library was linking to `libopenblas.so`, not `libopenblas64_.so`.  Also,
relax compat bound to be actually compatible with Julia v1.6.
> [SCIP_PaPILO] Use OpenBLAS32 instead of OpenBLAS

- S/SLICOT/build_tarballs.jl
> Someone should do something like #4770 (for lack of better options at the moment)
_Originally posted by @giordano in https://github.com/JuliaPackaging/Yggdrasil/issues/4969#issuecomment-1146836975_
I'm "someone".
https://discourse.julialang.org/t/too-many-julia-versions/84538/15?u=mkitti
1. Do we need a version bump to SLICOT 5.8.1 to do this?
2. @andreasvarga can we coordinate a SLICOT 5.8.1 release?
cc: @RalphAS
> SLICOT 5.8.0, Julia 1.8 compat

- L/LibTeXPrintf/build_tarballs.jl
- L/LibTeXPrintf/bundled/patches/texfree.diff
This adds a `texfree` function, so that it can be called from Julia to free memory.
@giordano
> add `texfree` function for freeing memory

- H/HIP/HIP@4.5.2/bundled/patches/improve-compilation-disable-tests.patch
- H/HIP/HIP@5.2.3/bundled/patches/improve-compilation-disable-tests.patch
- H/HIP/common.jl
Disable legacy folder structure using `-DFILE_REORG_BACKWARD_COMPATIBILITY=OFF`.
Otherwise it creates a duplicate library directory which confuses rocBLAS and other libraries.
This is only in 5.2.3.
> [HIP 5.2.3] Disable legacy folder structure

- R/rsync/build_tarballs.jl
Created with the wizard, so leaving out platforms it didn't build for out-of-the-box.
> Add recipe for rsync.

- O/OpenBLAS/OpenBLAS@0.3.21/bundled/patches/openblas-default-num-threads.patch
This allows Julia to set a default number of threads (usually `1`) to be used when no other thread counts are specified, to short-circuit the default OpenBLAS thread intialization routine that spins up a different number of threads than Julia would otherwise choose.
> Add `OPENBLAS_DEFAULT_NUM_THREADS` environment variable

- S/s5cmd/build_tarballs.jl
https://github.com/peak/s5cmd
A Go utility for interfacing with S3 servers (like s3cmd and aws-cli, but native).
> Add recipe for s5cmd.

- M/minio/build_tarballs.jl
Includes a fix for https://github.com/minio/minio/issues/15733, which should make MinIO/CloudBase work on CI that uses tmpfs (e.g. PkgEval).
cc @quinnj
> Bump MinIO.

- L/LibTeXPrintf/build_tarballs.jl
- L/LibTeXPrintf/bundled/patches/texfree.diff
I noticed that `texfree` needed to be in the list of exported symbols to appear in the shared library for `libtexprintf`.
@giordano (is it annoying to you if I ping you? To know, and avoid doing it. 😅)
> add `texfree` to the list of exported symbols

- T/Torch/build_tarballs.jl
Attempt to fix https://github.com/JuliaRegistries/General/pull/68204 
Might also need to be a `BuildDependency` in addition to `Dependency`
> [Torch] Fix deps issue for Torch

- T/Torch/build_tarballs.jl
Ref: https://github.com/JuliaPackaging/Yggdrasil/pull/5551/files#r979472676.  I'll fix this directly in the registry, to avoid rebuilding this yet another time.
> [Torch] Limit compat of protoc_jll to minor version

- H/Hwloc/build_tarballs.jl
See https://github.com/JuliaParallel/Hwloc.jl/pull/62#issuecomment-1257248490
In this PR I add `lstopo-no-graphics` as an `ExecutableProduct`. I tested it locally and it looked fine.
> [Hwloc] Add `lstopo-no-graphics` as an `ExecutableProduct`

- F/FFMPEG/FFMPEG/build_tarballs.jl
It appears FFMPEG explicitly requires PCRE, dependency that we were previously
getting indirectly from Glib, but now Glib 2.74 dropped PCRE for PCRE2, so now
the dependency is gone and we have to restore it directly.
***Edit***: actually, FFMPEG seems to prefer PCRE2 over PCRE, use that one instead.
> [FFMPEG] Add explicit dependency on `PCRE2_jll`

- L/licensecheck/build_tarballs.jl
There isn't a new version since 0.3.1, so I moved to the "expanded" version scheme. Bumped version and added julia compat per-https://github.com/JuliaPackaging/Yggdrasil/issues/2763.
> [LicenseCheck] Rebuild for aarch64

- R/rocSPARSE/common.jl
- R/rocSPARSE/rocSPARSE@5.2.3/build_tarballs.jl
In the previous PR #5619 I forgot to replace version in `build_tarballs.jl` to `5.2.3` so it just rebuilt `4.5.2`. This one actually adds rocSPARSE 5.2.3
> Add rocSPARSE 5.2.3

- C/Coin-OR/Ipopt/build_tarballs.jl
- C/Coin-OR/coin-or-common.jl
@odow 
I recompiled `MUMPS_seq` with `OpenBLAS32` for windows platforms.
It should fix the issue within https://github.com/jump-dev/Ipopt.jl/pull/327.
> Recompile Ipopt with OpenBLAS32 for windows platforms

- T/tectonic/build_tarballs.jl
There's also a 0.11.0 that was released shortly after the 0.10.0. Do we care about having all the intermediate versions available, or should I just switch this PR to updating directly to 0.11.0?
> Update tectonic to 0.11.0

- C/CLFFT/build_tarballs.jl
This is the last PR in a series of PRs to revive OpenCL + CLFFT binaries for OpenCL.jl and CLFFT.jl respectively.
Appreciate if you can review @giordano. In particular, could you please double check which dependency is a BuildDependency and which is an actual Dependency? That is not 100% clear for me.
> Add recipe for CLFFT

- S/SCIP/build_tarballs.jl
This is a bit too constraining to have Ipopt requiring julia 1.8
> [SCIP] fix Ipopt version to last 1.6 compatible

- T/Triangle/build_tarballs.jl
* Fix issue https://github.com/JuliaGeometry/Triangulate.jl/issues/15 by replacing `unsigned long` with `unsigned long long` on x86_64_w64_mingw32
* Upstream source with all patches is now https://github.com/JuliaGeometry/Triangle
* Synchronized version number with upstream source
> [Triangle] fix crash on windows + new clean upstream source

- C/CUDA/CUDA_compat/build_tarballs.jl
Not great how `build_tarballs` ignores extraneous keyword arguments.
> [CUDA] Fix dont_dlopen for CUDA_compat_jll.

- C/CUDA/CUDA_Driver/build_tarballs.jl
- C/CUDA/CUDA_compat/build_tarballs.jl
The rename is for consistency with CUDA_Runtime_jll, and the (WIP) CUDA_Driver.jl that will use this JLL.
The other change is embedding the version of the build library in the JLL, as we need it to determine whether we want to use this alternative driver. I was wondering if there isn't a better way to do this though, as putting it in `init_block` results in a non-precompiled global variable.
> [CUDA] Rename CUDA_compat to CUDA_Driver; add version to JLL.

- C/CUDA/CUDA_Runtime/build_11.0.jl
- C/CUDA/CUDA_Runtime/build_11.1.jl
- C/CUDA/CUDA_Runtime/build_11.2.jl
- C/CUDA/CUDA_Runtime/build_11.3.jl
- C/CUDA/CUDA_Runtime/build_11.4.jl
- C/CUDA/CUDA_Runtime/build_11.5.jl
- C/CUDA/CUDA_Runtime/build_11.6.jl
- C/CUDA/CUDA_Runtime/build_11.7.jl
- C/CUDA/CUDA_Runtime/build_11.8.jl
- C/CUDA/CUDA_Runtime/build_tarballs.jl
- C/CUDA/CUDA_Runtime/platform_augmentation.jl
- platforms/cuda.jl
- remove support for 10.x
- add 11.7 and 11.8
- add libcudart and libcusolverMg
- put the non-reusable platform augmentation parts in the directory of this jll
- depend on CUDA_Driver for driver discovery
> [CUDA] Rework CUDA_Runtime_jll.

- C/CUDA/CUDA_Runtime/build_tarballs.jl
Otherwise registration fails with:
```
┌ Error: Dependency "CUDA_Driver" does not have a compat entry that has an upper bound
└ @ RegistryCI.AutoMerge ~/.julia/packages/RegistryCI/78Rh8/src/AutoMerge/guidelines.jl:134
```
> [CUDA] Add compat entry for CUDA_Driver.

- F/flashrom/build_tarballs.jl
This is technically not `v1.2`, but instead some random `master` version, because the board I actually need to flash is too new to appear in `v1.2` proper.  So we denote this by calling it `v1.2.900`, in hopes that there will not be a large number of upstream releases on the `v1.2` branch.
> Add `flashrom`

- L/LibUnwind/LibUnwind@1.5.0/build_tarballs.jl
Unfortunately, while this code has been often getting copied to other platforms lately, the option here (CONSERVATIVE_CHECKS) is typically lost when the libunwind authors do the code copying. Unfortunately also, the help continues implies that disabled should be the default value, although this was changed many years ago to be enabled. This should a give very substantial performance improvement on x86_64, by disabling unnecessary checks. It is not supposed to be enabled, since it is known to hurt performance very badly:
https://github.com/libunwind/libunwind/commit/649f1fb3449a65dd0626a709432d8b02a7c56bbc but then later got enabled because some people were using buggy compilers: https://github.com/libunwind/libunwind/commit/045c55b2a296988c16a4c1b90f3d8b7e8b78752b
Note: in v1.6, it looks …
> make libunwind substantially faster

- K/KaHyPar/build_tarballs.jl
- K/KaHyPar/bundled/patches/no_native.patch
KaHyPar v1.3.0 supports building for the M1 architecture. This should be a simple update but please review if other changes are needed.
> [KaHyPar] update build script for M1

- C/CUDA/CUDA_Driver/build_tarballs.jl
Turns out we have a policy that JLLs cannot depend on non-JLL packages, so having CUDA_Runtime_jll depend on CUDA_Driver doesn't work. Instead, this PR moves the functionality from that package into the JLL by (ab)using the init mechanism. This functionality is required to determine whether the driver provided by CUDA_Driver_jll can be used, or whether we should use the system driver instead.
This change will also make it easier to further inline all of CUDA_Driver(_jll) into CUDA_Runtime_jll, which we sadly have to do because CUDA_Runtime_jll's package hooks cannot depend on _any_ non-stdlib package.
> [CUDA] Inline CUDA_Driver.jl into CUDA_Driver_jll._

- C/CUDA/CUDA_Runtime/build_tarballs.jl
- C/CUDA/CUDA_Runtime/platform_augmentation.jl
Works around:
```
┌ Info: If this is a JLL package, only deps are Pkg, Libdl, and other JLL packages
│   meets_this_guideline = false
└   message = "JLL packages are only allowed to depend on Pkg, Libdl, Artifacts, JLLWrappers, LazyArtifacts, TOML, MPIPreferences and other JLL packages"
```
> [CUDA] Update CUDA_Runtime_jll to depend on CUDA_Driver_jll.

- L/LibPQ/build_tarballs.jl
Hi @giordano! This PR exposes the postgres header files to client applications, that can build on top of them. This is for example needed in gdal. Maybe the contents of `$prefix/include/postgresql/server` are unused and can be deleted to save space?
> LibPQ: expose headers to client applications

- C/CUDNN/build_tarballs.jl
Only spotted by Yggdrasil CI during registration:
```
ERROR: LoadError: Augmentation blocks cannot be used with Julia v1.5-.
Change `julia_compat` to require at least Julia v1.6
Stacktrace:
[1] error(s::String)
@ Base ./error.jl:33
[2] register_jll(name::String, build_version::VersionNumber, dependencies::Vector{Dependency}, julia_compat::String; deploy_repo::String, code_dir::String, gh_auth::GitHub.OAuth2, gh_username::String, augment_platform_block::String, lazy_artifacts::Bool, kwargs::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
@ BinaryBuilder /depot/packages/BinaryBuilder/dyIhw/src/AutoBuild.jl:556
[3] top-level scope
@ /agent/_work/1/s/.ci/register_package.jl:137
in expression starting at /agent/_work/1/s/.ci/register_package.jl:137
```
> [CUDNN] Fix Julia compat.

- platforms/cuda.jl
We're currently using 'none' as a special case to indicate no CUDA toolkit, so need to handle this appropriately.
> [CUDA] Fix comparison strategy in case of missing CUDA.

- G/GDAL/build_tarballs.jl
@visr This is the follow-up to #5700 and adds PostgreSQL support to gdal. Should the version offset be changed? If yes, how?
> [GDAL] add PostgreSQL support

- P/Python/build_tarballs.jl
- bump python to `3.10.8`;
- add `--enable-optimizations` configure flag;
- ~~add `version.major` & `version.minor` to `LibraryProduct`.~~
> bump `Python` to `3.10.8` - enable-optimizations

- P/pprof/build_tarballs.jl
In the latest 1.0.0+1 release, a large # of JLL dependencies were added. I have a project where JLLs have to be added carefully, and the `+1` build number doesn't allow pinning the version to a pre-lots-of-JLLs version. As recommended in [this slack thread](https://julialang.slack.com/archives/C674ELDNX/p1666244847300719), we can bump the version and then yank the 1.0.0+1 version from the General registry to allow pinning.
> Bump pprof to 1.0.1

- C/CUDA/CUDA_Runtime/build_tarballs.jl
- C/CUDA/CUDA_Runtime/platform_augmentation.jl
- platforms/cuda.jl
By encoding this as a platform tag incompatible with other CUDA platform tags, this makes it possible to opt-out of the JLL system and not download any artifacts at all.
> [CUDA] Introduce cuda=local platform tag for local discovery.

- C/CUDA/CUDA_Runtime/platform_augmentation.jl
Otherwise the compilecache doesn't ever invalidate after having set the version to `local`.
> [CUDA] Fix runtime JLL recompilation on preference change.

- C/casacorecxx/build_tarballs.jl
This is a CxxWrapper around Casacore, which is already packaged as part of Yggdrasil.
It is intended to be used primarily by https://github.com/torrance/Casacore.jl
> Add casacorecxx build script

- A/Arpack/build_tarballs.jl
@giordano Updating Arpack 3.7 in here with a modern build. I think this is ok, since it has been yanked for a long time, and nobody is using it.
> ARPACK 3.7

- C/cereal/build_tarballs.jl
Just earlier today, mlpack 4.0.0 was released, so I have begun the process of updating the `mlpack_jll` package.  However, mlpack 4 has a new dependency on cereal, a header-only serialization library (this then let mlpack remove its Boost dependency).  So, we just need to add a `cereal_jll` package to make those headers available for mlpack.
I ran and tested this locally---seems to be fine.  We'll see if CI agrees. :)
> Add cereal_jll package (dependency of mlpack).

- S/SuiteSparse/SuiteSparse_GPU/build_tarballs.jl
@ViralBShah I removed several components that failed to build (e.g. Slip_LU), making it consistent with the main SuiteSparse build. I'm also not sure why this version included METIS? I couldn't find anything about SuiteSparse+CUDA and any METIS requirements.
> Update SuiteSparse GPU build.

- O/oneAPI_Support/build_tarballs.jl
I _think_ this is why I'm running into:
```
ERROR: could not load library "/home/tim/Julia/depot/artifacts/89bcb2617e71169efe39a4770f3a92ac6b37c210/lib/liboneapi_support.so"
libmkl_sycl.so.2: cannot open shared object file: No such file or directory
```
... as `libmkl_sycl.so.2` is just provided in the same directory as `liboneapi_support.so`, and there's no proper dependency on a JLL loading that library.
> [oneAPI] Do dlopen the support library during init.

- O/oneAPI_Support/build_tarballs.jl
It's needed to patch the RPATH so that the library is loadable.
Thanks to @vchuravy for the suggestion.
> [oneAPI] Enable the auditor for the support library.

- C/CUDA/CUDA_Runtime/platform_augmentation.jl
This happens when we don't have a driver artifact, in which case the init function that sets libcuda doesn't run (https://github.com/JuliaPackaging/JLLWrappers.jl/issues/50). For now, duplicate the system discovery logic.
> [CUDA] Fix platform augmentation when CUDA_Driver_jll isn't available.

- G/GNUMake/build_tarballs.jl
- G/GNUMake/bundled/patches/findprog-in-ignore-directories.patch
Make bundles gnulib, and gnulib has a bug where it tries to execute
directories in the PATH instead of files, see
https://savannah.gnu.org/bugs/?57962
> GNUMake: patch bug that makes it execute dirs

- L/libcleri/build_tarballs.jl
- L/libcleri/bundled/patches/cc-compiler.patch
Fix #5771, at least for the specific case of libcleri, although other libraries are going to have troubles on Intel macOS Ventura because the dynamic loader change behaviour in a breaking way.
> [libcleri] Do not build with GCC on all platforms

- G/GAP/build_tarballs.jl
- G/GAP/bundled/patches/sysinfo.patch
... to deal with Julia 1.9-DEV ABI changes.
Also patch sysinfo.gap so we can later simplify GAP_pkg_* recipes
> Rebuild GAP

- S/SCS/build_tarballs.jl
- S/SCS_GPU/build_tarballs.jl
- S/SCS_MKL/build_tarballs.jl
There are some failures/segfaults on i686 which I can't reproduce/track locally
https://github.com/jump-dev/SCS.jl/pull/255#issuecomment-1107815005
So to move this forward it's best to disable the build until somebody asks for it ;)
Questions:
1. Is it possible to add compat as `=3.2.1+1` (the version of binary built here?)
2. does this merit/require changing to `3.2.2`? 
the point is that I want just to remove i686 binaries from the registry ;)
> [SCS_MKL] don't build binaries for i686

- O/OpenSSH/build_tarballs.jl
This uses an archive from a git tag to download the tarball; I hope this is okay.
> openssh: New version 9.1p1

- G/GR/build_tarballs.jl
GR uses a Preferences.jl mechanism to `dlopen` the libraries so the GR_jll does not need to dlopen the binaries directly:
https://github.com/jheinen/GR.jl/blob/f224e831abbade86ad1932a8b4b7fa2c85cec86d/src/funcptrs.jl#L33-L35
On Linux in certain configurations, a LD_PRELOAD is needed to get around this since the GR_jll binaries may be loaded before the system binaries. This pull request resolves this, but having GR_jll not load the binaries.
I'm also looking into using Overrides.toml or local preferences for overrides. Even with JLL overrides, this is still needed in case someone wants to use a Plots.jl backend that is not GR. In that case, using dlopen on GR_jll would just add time to loading. Additionally, GR_jll may interfere with other binaries making it difficult to load another …
> Use dont_dlopen=true with GR libraries

- A/Arpack/build_tarballs.jl
- M/MAGMA/build_tarballs.jl
Both of these packages are safe to fix the Julia version bounds on without bumping their version numbers.
> Fix Julia version compatibility due to LBT SONAME change

- C/CompilerSupportLibraries/CompilerSupportLibraries@v1.0/build_tarballs.jl
- C/CompilerSupportLibraries/common.jl
We have to manually fix a dependency of `libgcc.1.dylib` in order to
make the library properly loadable.
> [CompilerSupportLibraries] Fix dependency of `libgcc_s.1.dylib`

- S/Singular/build_tarballs.jl
Now with a version_offset bump due to an unexpected ABI change.
> [Singular] update to 4.3.1-4

- L/LLVMOpenMP/build_tarballs.jl
We [were getting crashes](https://github.com/oscar-system/Oscar.jl/issues/1674) from llvm-openmp on aarch64-apple-darwin:
```
OMP: Error #13: Assertion failure at kmp_dispatch.cpp(1298).
OMP: Hint Please submit a bug report with this message, compile and run commands used, and machine configuration info including native compiler and operating system versions. Faster response will be obtained by including all program sources. For information on submitting this issue, please see https://bugs.llvm.org/.
signal (6): Abort trap: 6
in expression starting at /Users/horn/Projekte/OSCAR/Oscar.jl/test/PolyhedralGeometry/timing.jl:1
__pthread_kill at /usr/lib/system/libsystem_kernel.dylib (unknown line)
Allocations: 137297125 (Pool: 137203552; Big: 93573); GC: 50
```
This seems to be a bug in llvm …
> [LLVMOpenMP] update to 15.0.4

- Z/ZlibNG/build_tarballs.jl
I don't have much experience building C libraries and this is my first direct interaction with BinaryBuilder.jl.
I'm trying to build one of the more performant zlib forks, the `ZLIB_COMPAT` flag builds a version with an API compatible with the original zlib. Since the only purpose of this recipe is to unlock more performance, I tried setting some of the optimizations on but I am not sure if it is safe to do so. Any guidance would be greatly appreciated!
On my two laptops (M1 mac and intel linux), when trying to compress and decompress 1MB of lorem ipsum text, I see ~2x performance increase when I plug the resulting binary into CodecZlib.jl.
cc: @quinnj 
EDIT: No longer using the `ZLIB_COMPAT` due to soname clash with zlib.
> Add zlib-ng

- R/ROCmCompilerSupport/ROCmCompilerSupport@5.2.3/build_tarballs.jl
- R/ROCmCompilerSupport/common.jl
- Add `julia_compat=1.9` to 5.2.3
- Specify `compat` version instead of regular version.
Leaving out `julia_compat=1.9` introduces more problems than it solves:
https://github.com/JuliaGPU/AMDGPU.jl/issues/313#issuecomment-1289107341
If we had `julia_compat=1.9` for all ROCm 5.2.3 packages we could've safely deleted `Manifest.toml` from AMDGPU.jl and let it automatically resolve correct versions of artifacts.
Also I don't think we need to account for the fact that you can rebuild Julia with different LLVM, as LLVM itself [specifies](https://github.com/JuliaPackaging/Yggdrasil/blob/d2cbdb2501f0e25c29e34575b302a8c4b1498737/L/LLVM/LLVM%4014/build_tarballs.jl#L37) `julia_compat` bounds.
And ROCm 5.2.3 requires LLVM 14, which is what Julia 1.9 uses, so it makes sense to have `julia_compat` …
> [ROCmCompilerSupport] Add Julia 1.9 compat for 5.2.3

- M/METIS/METIS@5/build_tarballs.jl
- M/METIS/METIS@5/bundled/patches/005-add-ifndefs.patch
SuperLU_DIST is currently built incorrectly, we need 64 bit versions of METIS where required.
I left `libmetis` as is, I didn't want to mess with it and break anyone else. Rebuilding the 64 bit versions of PARMETIS and SuperLU is going to be a pain...
> [METIS] Add 64 bit builds

- D/ducc0/build_tarballs.jl
This adds a rudimentary JLL interface for the ducc0 package (https://gitlab.mpcdf.mpg.de/mtr/ducc). This is most likely not generally useful yet, but I don't know how to test the binary building without opening a PR and letting the CI build and test the package.
> Add ducc0 package

- G/gobject_introspection/build_tarballs.jl
This will make the introspection data packaged here match the current version of Glib_jll (2.74).
> [gobject_introspection] update to 1.74.0

- S/SDL2/build_tarballs.jl
When switching to CMake the soname of macOS binaries went from `@rpath/libSDL2-2.0.0.dylib` to `@rpath/libSDL2-2.0.dylib`, breaking the ABI.
CC: @Gnimuc
> [SDL2] Go back to autoconf

- B/BladeRFHardwareDriver/build_tarballs.jl
- B/BladeRFHardwareDriver/bundled/patches/readline-freebsd.patch
* Package name: BladeRFHardwareDriver
* Version: v2.4.1
It does not cross compile for freebsd and windows:
https://github.com/Nuand/bladeRF/issues/890
https://github.com/Nuand/bladeRF/issues/891
https://github.com/Nuand/bladeRF/issues/892
> Wizard recipe: BladeRFHardwareDriver-v2.4.1

- C/Clipper/build_tarballs.jl
Requested at https://discourse.julialang.org/t/how-to-update-a-jll-wrapper-to-support-mac-m1/89936.  CC: @Wikunia
> [Clipper] Build for new platforms

- F/fts/build_tarballs.jl
As noted by @giordano; Pkg doesn't handle the Julia compat changing without an actual version change.
> fts: bump the package version.

- L/libcgroup/build_tarballs.jl
- L/libcgroup/bundled/patches/0001-replace_ac_malloc_realloc.patch
This provides useful cgroup management utilities that I may use in PkgEval (instead of requiring systemd for `systemd-run`).
> Add recipe for libcgroup 3.0.

- G/GR/build_tarballs.jl
Use the correct hash for the tagged release : v0.69.1-46-g25cf3368 => v0.70.0. Does not involve any change to the code and is purely cosmetic.
> [GR] use correct hash

- G/GDAL/build_tarballs.jl
The [release notes](https://github.com/OSGeo/gdal/releases/tag/v3.6.0) mention a bump of the shared lib major version, so I'm bumping the major version here as well.
Adding these deps was discussed before at https://github.com/JuliaGeo/GDAL.jl/issues/65#issuecomment-1220678410 and was the main motivation to finish the Arrow_jll build in #5425 by @evetion. This PR should enable us to make use of GDAL's [RFC 86: Column-oriented read API for vector layers](https://gdal.org/development/rfc/rfc86_column_oriented_api.html).
> [GDAL] build 3.6.0 and add Arrow & Parquet

- A/Arrow/build_tarballs.jl
I'm not sure if this makes sense, but I noticed #5848 got [tagged](https://github.com/JuliaBinaryWrappers/GDAL_jll.jl/releases/tag/GDAL-v301.600.0%2B0) but not [registered](https://github.com/JuliaRegistries/General/pull/72100) since `import GDAL_jll` failed.
Trying to dev GDAL_jll locally I get this on `import GDAL_jll`:
```
ERROR: InitError: could not load library "d:\visser_mn\.julia\artifacts\a2b72ddc9b6d6e60c1f41aa1351392f97af055d1\bin\libgdal-32.dll"
The specified module could not be found.
```
Loading it with DependencyWalker I see 3 libraries are not found:
```
✗ libarrow_dataset.dll (NOT FOUND)
✗ ODBCCP32.dll (NOT FOUND)
✗ ODBC32.dll (NOT FOUND)
```
The last two have been like that for a while and don't really cause issues, but since Arrow is a new dependency I suspect the …
> [Arrow] add libarrow_dataset LibraryProduct

- P/protoc/build_tarballs.jl
Added another Library product in `protoc/build_tarballs.jl` for `libprotobuf`
Currently, the only product is `libprotoc` but I need a safe way to get the path for the `libprotobuf` library file generated as well. I need this to be able to compile and link my C++ files against the protobuf library.
The hack I currently have and this PR fixes is the following
```
using protoc_jll
protobuf_lib = replace(protoc_jll.get_libprotoc_path(), "libprotoc." => "libprotobuf.")
```
> Update protoc library products to include `libprotobuf`

- L/libjulia/build_tarballs.jl
- L/libjulia/bundled/patches/1.10.0-DEV/cycleclock.patch
- L/libjulia/bundled/patches/1.10.0-DEV/msys_build.patch
- L/libjulia/common.jl
Also update Julia 1.9-DEV to latest git version, just in case.
First step towards #5787. It does *not* add `debug` to the platform as Julia happily allows `libjulia` and `libjulia-debug` to co-exist...
... though perhaps we *should* augment the platform like that, and only build either `libjulia` or `libjulia-debug`? One argument for doing that is that it should make it impossible to accidentally link against `libjulia` when one should be linking against `libjulia-debug`, and vice-versa.
As an additional data point, I looked into adding a `platforms/julia-debug.jl`, and realized that all packages that would include it already including `L/libjulia/common.jl`. So now I am wondering if either the `augment_platform` helpers should just go in there -- or dually, that it should all go into a …
> libjulia: add 1.10, update 1.9, add debug shared libs

- C/Coin-OR/Clp/build_tarballs.jl
- C/Coin-OR/Ipopt/build_tarballs.jl
- C/Coin-OR/coin-or-common.jl
@giordano We use gcc v6. Is that good for M1? Or should we be on something newer?
`MUMPS_seq` has a `julia_compat` of 1.8. I wonder if that will create a problem.
> [Coin-OR] OpenBLAS version bump

- L/libcxxwrap_julia/build_tarballs.jl
Adds a bugfix for a crash that appears in QML.jl
> [libcxxwrap_julia] Bump version to 0.9.3

- S/SymEngine/build_tarballs.jl
- S/SymEngine/bundled/patches/gmp-fix.patch
Found by experimenting with mimalloc, upstream PR is https://github.com/symengine/symengine/pull/1940
> Add patch to SymEngine so that it frees GMP strings correctly

- M/METIS/METIS@4/build_tarballs.jl
Mosè, do we need to modify the soname with `patchelf` when we generate a shared library from a static library with a different name?
I don't want to create conflicts with `metis.$dlext` from METIS_jll.
I'm also not sure that we can have two shared libraries that coexist with the same symbols even if they have different name and soname.
> Add a shared library for METIS4

- S/SoapyBladeRF/build_tarballs.jl
This builds the SoapySDR bindings for BladeRF SDR.
Windows is excluded because it depends on `BladeRFHardwareDriver_jll`.
> Soapy bindings for BladeRF

- M/MPFR/build_tarballs.jl
This is an actual 4.1.1 release
> [MPFR] 4.1.1

- Q/Qhull/build_tarballs.jl
This updates Qhull_jll to include some recent merges from the main repo (mainly https://github.com/qhull/qhull/pull/105, which should help with Windows).
@stevengj: I'm a little bit unsure of the versioning convention here: is it acceptable to just increment the patch version by 1?
> [Qhull] update to master

- C/CMake/build_tarballs.jl
`cmake` v3.23.1+ is required to build cuDF (https://github.com/rapidsai/cudf/blob/branch-22.10/CONTRIBUTING.md#setting-up-your-build-environment).
There are newer versions of CMake (v3.24, v3.25), but I just bumped the version to the minimum required version.
> [CMake] Update to v3.23.3

- M/Minuit2_Julia_Wrapper/build_tarballs.jl
I'm trying to remove the version spec from the libcxxwrap dependency and hope that fixes the failing tests at https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_date/2022-11/24/Minuit2.primary.log
> [Minuit2_Julia_Wrapper] remove CxxWrap version restriction

- S/SQLite/build_tarballs.jl
Add SQLITE_ENABLE_FTS3_PARENTHESIS and SQLITE_USE_URI compiler definitions.
The former follows https://github.com/archlinux/svntogit-packages/commit/117e0d7678370c13afaaaf1a4347a3d5055cd3f2
The latter enables https://www.sqlite.org/uri.html in SQLite, so users can use more powerful URI to control the behavior when opening database
> [SQLite] Add compiler flags

- C/Cling/build_tarballs.jl
- C/Cling/bundled/patches/avoid_builtin_available.patch
Cling is an interactive C++ interpreter built on the top of LLVM and Clang libraries
Building Cling requires CERN's patched versions of llvm and clang.
https://root.cern/cling
https://root.cern/cling/cling_build_instructions/
https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/cling.rb
> New: Cling interactive C++ REPL

- C/casacorecxx/build_tarballs.jl
We want to require only glibc build, as Casacore itself uses glibc specific calls. However, for some reason MacOS platforms have no libc information at all and by requiring `libc(p) == "glibc"` we exclude all MacOS builds.
In this patch, we will require `libc(p) != "musl"` (which is consistent with `casacore_jll`).
> Enable builds for MacOS by not explicitly requiring glibc

- R/rr/build_tarballs.jl
This should make it possible to use our x64 rr build with x32 binaries while on a x64 system. This can actually be useful: to be able to execute `julia32 --bug-report=rr` on a x64 system. The platform augmentation hooks make this possible, overloading the platform depending on the system, but currently the build fails because when building for x64 we don't have an x32 compiler.
cc @Keno
> rr: add 32-bit build

- L/libcap/build_tarballs.jl
I'm not sure why it was using `lib64` before; `libdir` is always `$prefix/lib`, and in some cases (https://github.com/JuliaPackaging/Yggdrasil/pull/5963) putting stuff in `lib64` breaks the compiler finding `libcap`.
> Install libcap into lib,  not lib64.

- S/systemd/build_tarballs.jl
This only deals with `libsystemd`. Building the binaries is possible, but for a full-featured set-up that requires a metric ton of dependencies, and we currently don't have the ability to split the generated artifacts in two (libsystemd doesn't have many dependencies). Also, I'm not sure that the binaries are useful to us.
Requires glibc 2.19 (2.16 should be sufficient, but we don't package it, and 2.17 seems incompatible with current Linux kernel headers).
> Add recipe for systemd.

- C/crun/build_tarballs.jl
> crun:  A fast and lightweight fully featured OCI runtime and C library for running containers 
I'm running into some weird compiler errors though:
```
[17:48:59] cc -DHAVE_CONFIG_H -I.    -I /workspace/srcdir/crun-1.7.1/libocispec/src -I /workspace/srcdir/crun-1.7.1/libocispec/src -D CRUN_LIBDIR="\"/workspace/destdir/lib/crun\"" -g -O2 -fPIC -MT src/crun-kill.o -MD -MP -MF src/.deps/crun-kill.Tpo -c -o src/crun-kill.o `test -f 'src/kill.c' || echo './'`src/kill.c
[17:48:59] src/libcrun/cloned_binary.c: In function ‘is_self_cloned’:
[17:48:59] src/libcrun/cloned_binary.c:147:36: error: ‘struct statfs’ has no member named ‘f_flags’
[17:48:59]   147 |                 is_cloned |= (fsbuf.f_flags & MS_RDONLY);
[17:48:59]       |                                    ^
[17:48:59] …
```
> Add recipe for crun.

- C/crun/build_tarballs.jl
`libcrun` is an interesting library, in that it completely breaks Julia when `dlopen`ed:
```
julia> using Libdl
julia> Libdl.dlopen("/home/tim/Julia/depot/artifacts/682a441bd76a9926b58816127b0085eed6e26604/lib/libcrun.so")
/home/tim/Julia/depot/juliaup/julia-1.8.3+0.x64.linux.gnu/bin/julia: error while loading shared libraries: libjulia.so.1: cannot open shared object file: No such file or directory
❯
```
For some reason, loading the library triggers a search for `libjulia` in system directories:
```
2985658:	calling init: /home/tim/Julia/depot/artifacts/682a441bd76a9926b58816127b0085eed6e26604/lib/libcrun.so
2985658:
2985658:	find library=libdl.so.2 [0]; searching
2985658:	 search path=/memfd:crun_cloned:/proc/self/../lib/glibc-hwcaps/x86-64-v3:/memfd:crun_cloned:/proc/self/../lib/glibc-h …
```
> Don't build the crun library.

- C/Ccluster/build_tarballs.jl
Also update dependencies, locking the versions of FLINT and Arb, to avoid accidentally using this JLL with incompatible versions of those JLLs.
I think this will cause issue in the registry, though, due to the changed compat values. I am not sure how to best deal with that, though -- override the errors in the registry? Nicer would be to bump the version here, but then we get out-of-sync with upstream....
CC @fieker @rimbach
> [Ccluster] rebuild for macOS M1 support

- H/HELICS/build_tarballs.jl
This PR supercedes #3644, #3645, and #4205.
Changes:
- Get HELICS package working again for the latest HELICS 3.x release (3.3.2)
- Use gcc v9 to address bug with mingw std::filesystem library on older versions of gcc
- Use MacOSX 10.15 SDK on Intel mac builds to address issues with std::filesystem library on older versions of macOS
- Enable FreeBSD builds (CI system for HELICS has tested FreeBSD for some time now)
- Remove build support for HELICS 2.x, which is no longer supported/receiving updates
Squash/merge commit message should include the line (at the end of the commit message):
`Co-authored-by: Dheepak Krishnamurthy <me@kdheepak.com>`
> [HELICS] update to v3.3.2

- C/crun/build_tarballs.jl
This gives us CLONE_NEWCGROUP and makes crun capable of controlling cgroups, without bumping glibc to 2.36.
> crun: replace sched.h with kernel version.

- L/libjlnode/build_tarballs.jl
An approach similar to #5859 is used here since they can't be cross-compiled
> [libjlnode] Update to v18.0.0. Add support for Windows/macOS

- G/Glib/build_tarballs.jl
I need the `.a`'s to compile qemu statically. It's not ideal to ship these to users, but lacking separate dev JLLs this is the only solution for now, and it's only a couple of MBs.
> glib: also generate static libraries.

- P/PCRE2/build_tarballs.jl
x86_64-linux-glibc artifact size increases from 1.5 to 2.3MB, which seems acceptable:
```
-rw-r--r-- 1 tim tim 794K Jan  1  1970 libpcre2-16.a
-rw-r--r-- 1 tim tim 768K Jan  1  1970 libpcre2-32.a
-rw-r--r-- 1 tim tim 846K Jan  1  1970 libpcre2-8.a
-rw-r--r-- 1 tim tim 6.9K Jan  1  1970 libpcre2-posix.a
```
> PCRE2: Build static libraries.

- L/Libiconv/build_tarballs.jl
Inflates the x86_64-linux-glibc artifact size from 1 to 1.9MB. Not great, not terrible.
Note that we'll eventually want to move these out, e.g. using https://github.com/JuliaPackaging/BinaryBuilder.jl/issues/778, but in the meantime let's just put these in main JLL.
> libiconv: Build static libraries.

- Q/Qemu_static/build_tarballs.jl
- Q/Qemu_static/bundled/patches/qemu_disable_tests.patch
- Q/Qemu_static/bundled/patches/qemu_execve.patch
- Q/Qemu_static/bundled/patches/qemu_falloc.patch
- Q/Qemu_static/bundled/patches/qemu_syscall.patch
These binaries are convenient for use _within_ a container, where the dynamic libraries that Qemu_jll depends on aren't available.
I intend to (try to) use this in PkgEval, for testing e.g. aarch64 binaries on x86. That's why I've only included targets that Julia supports, or otherwise the artifact size balloons to over 500MB.
I've also included an additional patch to inject qemu on execve so that you can launch other foreign processes. Normally you'd do this by installing qemu on the host and registering it with the kernel using binfmt, but I'd like to avoid any required set-up.
> qemu: add recipe for statically-built user-mode emulation binaries.

- G/Gnuplot/build_tarballs.jl
- G/Gnuplot/bundled/patches/01-gnuplot.patch
This again is incomplete! 
@giordano Your kind help is yet again needed my friend!
> Add Gnuplot builder

- C/Ccluster/build_tarballs.jl
Somehow the previous update didn't trigger CI and thus never reached the registry
> Rebuild Ccluster

- B/Binutils/build_tarballs.jl
Current Binutils recipe not only does not longer work but also generated artifacts are wrong (it provides *.exe binaries in Linux...).
This PR updates to the syntax, exports `libbfd`, `libctf`, `libopcodes` shared libraries and refactors the recipe.
> Update binutils to new syntax and version 2.39

- B/Binutils/build_tarballs.jl
Ref JuliaRegistries/General#73995
> Fix `c++filt` symbol of executable product in Binutils

- R/rr/build_tarballs.jl
Bumping to 5.6 to include https://github.com/rr-debugger/rr/pull/3334 for testing InterProcessCommunication.jl on PkgEval. Also moves to JuliaLang/rr, as I didn't have permissions to push to @Keno's personal fork.
> Bump rr to v5.6 (including Julia-specific patches).

- X/XGBoost/build_tarballs.jl
This PR is a WIP. I am trying to build XGBoost with GPU support (https://github.com/dmlc/XGBoost.jl/issues/134). 
Currently, the `x86_64-linux-gnu` cuda build is working. I am struggling to get it to also build with NCCL, but that is not a necessity. 
The `x86_64-w64-mingw` cuda build is not working. Cmake throws the following error:
```
CMake Error at /usr/share/cmake/Modules/CMakeTestCUDACompiler.cmake:56 (message):
[19:10:08]   The CUDA compiler
[19:10:08] 
[19:10:08]     "/workspace/destdir/cuda/bin/nvcc.exe"
[19:10:08] 
[19:10:08]   is not able to compile a simple test program.
[19:10:08] 
[19:10:08]   It fails with the following output:
[19:10:08] 
[19:10:08]     Change Dir: /workspace/srcdir/xgboost/build/CMakeFiles/CMakeTmp
[19:10:08]     
[19:10:08]     Run Build …
```
> [XGBoost] Add GPU support 

- X/XGBoost/build_tarballs.jl
This fixes the GPU build that was merged earlier today (https://github.com/JuliaPackaging/Yggdrasil/pull/5892). The logic for determining the build always built the CPU version of the library. I have updated it to use `$bb_full_target` instead of `$target`, so we can correctly build the CUDA version. 
The only thing this should change is that the x64_linux + CUDA build should now have GPU support. 
I have also removed NCCL (for the time being) because it will require extra work. The no issues that I experienced were due to the incorrect target logic, not the CUDA+NCCL build working.
@ExpandingMan
> [Xgboost] fix gpu build target logic

- F/finufft/build_tarballs.jl
Currently, FINUFFT.jl does not work on the new Zen 4 Ryzen series since there is no binary for AVX512 platforms available in finufft_jll. Hence, disable AVX512 via CFLAGS on x86 to provide binaries for AVX512 platforms such as Zen 4 without introducing the performance issues mentioned in the comment of line 38.
> [finufft] Support for AVX512 platforms

- T/tblis/build_tarballs.jl
libtci needs libatomic also on macOS.  Ref https://github.com/JuliaPackaging/Yggdrasil/pull/4653#issuecomment-1358816331.  CC: @xrq-phys.
> [tblis] Make `CompilerSupportLibraries_jll` available on all platforms

- G/GDAL/build_tarballs.jl
3.6.0 is retracted, details in https://github.com/OSGeo/gdal/blob/v3.6.1/NEWS.md
> [GDAL] build version 3.6.1

- C/CompilerSupportLibraries/CompilerSupportLibraries@v1.0/build_tarballs.jl
- C/CompilerSupportLibraries/common.jl
This is mainly to test on which platforms `libssp` is available, I believe it should be available everywhere apart from Linux Musl.
> [CompilerSupportLibraries] Add `libssp` as product

- W/Wayland/build_tarballs.jl
Alpine 3.15 RootFS has version 1.19, so use package from Alpine 3.17 for `wayland-scanner` (thanks @giordano).
> [Wayland] update to 1.21

- F/FLAC/build_tarballs.jl
- F/FLAC/bundled/patches/flac_linux_headers.patch
Rebuild v1.3.4, but now with CompilerSupportLibraries as dependency.
> [FLAC] Downgrade to v1.3.4

- L/libsndfile/build_tarballs.jl
- S/SFML/build_tarballs.jl
FLAC broke the ABI in the 1.3 -> 1.4 update, so we must specify the compat
> Specify compat for FLAC dependants

- L/libjulia/build_tarballs.jl
- L/libjulia/common.jl
Since several packages include L/libjulia/common.jl, move the
monkey patch for Pkg.jl into build_tarballs.jl, so that it does
not accidentally affect other packages.
[skip build]
[skip ci]
> [libjulia] move Pkg.jl hack

- G/GAP_pkg/GAP_pkg_browse/build_tarballs.jl
- G/GAP_pkg/GAP_pkg_cvec/build_tarballs.jl
- G/GAP_pkg/GAP_pkg_datastructures/build_tarballs.jl
- G/GAP_pkg/GAP_pkg_digraphs/build_tarballs.jl
- G/GAP_pkg/GAP_pkg_edim/build_tarballs.jl
- G/GAP_pkg/GAP_pkg_ferret/build_tarballs.jl
- G/GAP_pkg/GAP_pkg_float/build_tarballs.jl
- G/GAP_pkg/GAP_pkg_io/build_tarballs.jl
- G/GAP_pkg/GAP_pkg_json/build_tarballs.jl
- G/GAP_pkg/GAP_pkg_juliainterface/build_tarballs.jl
- G/GAP_pkg/GAP_pkg_normalizinterface/build_tarballs.jl
- G/GAP_pkg/GAP_pkg_nq/build_tarballs.jl
- G/GAP_pkg/GAP_pkg_orb/build_tarballs.jl
- G/GAP_pkg/common.jl
- G/GAP_pkg/update.jl
Deal with upstream_version not being of the form X.Y.Z, but rather say X.Y and
X.Y-Z. For both it is important to keep upstream_version as a plain string, so
that the download URL derived from it stays valid. For the latter, we want to
replace the - by . (these GAP package versions do *not* follow semvar)
[skip build]
[skip ci]
> [GAP_pkg] avoid issue with irregular upstream_version

- S/SCIP/build_tarballs.jl
- S/SCIP/bundled/patches/findbliss.patch
- S/SCIP_PaPILO/build_tarballs.jl
- S/SCIP_PaPILO/bundled/patches/findbliss.patch
I bumped the patch-level from 300 to 301 to be able to add a compat entry for this version in polymake_jll.
This uses `FindBLISS.cmake` from the scip repo which does not do any version checks but this should not be necessary here.
I ran the testsuite for SCIP.jl on linux with locally built binaries and checked that I can now compile polymake_jll with the scip and soplex interfaces active.
cc: @matbesancon 
fixes: #5651
> [SCIP, SCIP_PaPILO] use bliss_jll and enable boost

- C/CUDA/CUDA_full@12.0/build_tarballs.jl
I guess I misunderstood what `[skip build]` does -- apparently it uses the existing artifacts from the JLL, not the ones that were previously built here -- so after CUDA_full_jll@12 failing to register yesterday it does still need a full rebuild.
Fixes the fact that the JLL now contains the wrong artifacts, https://github.com/JuliaBinaryWrappers/CUDA_full_jll.jl/commit/bca271c8e2c194c80727057a71e728c6e5f2caab
> Bump CUDA_full_jll@12 again

- D/ducc0/build_tarballs.jl
Update ducc0 to version 0.28
(I'm exprimenting with "-fvisibility=hidden" to reduce library size and improve load times; let's hope this works on Windows platforms.)
> update ducc0 to version 0.28.0

- M/msolve/build_tarballs.jl
... to restore compatibility with Julia 1.6 on macOS. Before this, we got this error on an Intel Mac:
ERROR: LoadError: LoadError: InitError: could not load library "JULIADEPOT/artifacts/0ee20e199c8939d53a5262356e455ebed54860a1/lib/libmsolve.dylib"
dlopen(JULIADEPOT/artifacts/0ee20e199c8939d53a5262356e455ebed54860a1/lib/libmsolve.dylib, 1): Library not loaded: @rpath/libmpfr.6.dylib
Referenced from: JULIADEPOT/artifacts/0ee20e199c8939d53a5262356e455ebed54860a1/lib/libmsolve-0.4.8.dylib
Reason: Incompatible library version: libmsolve.dylib requires version 9.0.0 or later, but libmpfr.dylib provides version 8.0.0
CC @ederc @wdecker
> [msolve] rebuild with old MPFR

- Q/Qt6Base/build_tarballs.jl
The wrong case logic here caused the host tools to be removed from the build, causing errors in the other Qt packages. Sorry build agents, and 🤞 that all this gets done before 6.4.3 is released ;)
> [Qt6Base] Build tools (host build)

- L/Libxc/Libxc_GPU/build_tarballs.jl
Not sure I understand this, but it seems #6118 had me pull in CUDA 12 on some machines. I'm now pinning the runtime to 0.2 to avoid this.
> Avoid pulling in CUDA 12 in Libxc

- V/ViennaRNA/build_tarballs.jl
This caused warnings on loading the ViennaRNA_jll package.
> [ViennaRNA] Fix wrong ExecutableProduct statement

- X/Xyce/build_tarballs.jl
This was removed, but `libxyce` still links against `libgfortran.so.5`, so we still need this.
> [Xyce] Expand gfortran versions again

- I/ImageMagick/build_tarballs.jl
We bumped Julia compat, so this needs to be a new patch release.
ref https://github.com/JuliaRegistries/General/pull/76930#issuecomment-1416084767
> [ImageMagick] tag 6.9.10 as 6.9.11 instead

- G/Ghostscript/build_tarballs.jl
- G/Ghostscript/bundled/patches/001-mingw-build.patch
Turns out #6199 didn't actually link against Ghostscript since we didn't
have a shared library for it
> [Ghostscript] also build `libgs`

- G/Ghostscript/build_tarballs.jl
I verified locally that imageMagick now actually links against `libgs`
properly.
> [Ghostscript] add headers required for ImageMagick

- I/ImageMagick/ImageMagick@6/build_tarballs.jl
Because libgs was previously broken on mingw builds, ImageMagick wasn't
linking to it on these platforms. (See
https://buildkite.com/julialang/yggdrasil/builds/647#018622f9-1e83-47d2-925f-8c5ea5c0934b/6-1732)
> [ImageMagick] rebuild

- C/CUDA/CUDA_Runtime/build_11.0.jl
- C/CUDA/CUDA_Runtime/build_11.1.jl
- C/CUDA/CUDA_Runtime/build_11.2.jl
- C/CUDA/CUDA_Runtime/build_11.3.jl
- C/CUDA/CUDA_Runtime/build_11.4.jl
- C/CUDA/CUDA_Runtime/build_11.5.jl
- C/CUDA/CUDA_Runtime/build_11.6.jl
- C/CUDA/CUDA_Runtime/build_11.7.jl
- C/CUDA/CUDA_Runtime/build_11.8.jl
- C/CUDA/CUDA_Runtime/build_12.0.jl
- C/CUDA/CUDA_Runtime/build_tarballs.jl
Sadly compiling the dynamic library doesn't work on Windows, as the static library we're linking here has been generated by MSVC, and there's no guarantee static libraries work across toolchains...
> CUDA: Create and include compiler library, export cublasLt.

- P/pandoc/build_tarballs.jl
Per discussion on slack, this is a CLI tool and we can use the same binaries for `x86_64-apple-darwin-14`.
> [Pandoc] Add `ArchiveSource` for pandoc to support MacOS `aarch64-apple-darwin-20`

- P/Python/build_tarballs.jl
Fixes #6189. The presence of sqlite3 lib causes the Python build to include it, no extra configure flags needed. I also needed the update otherwise was getting package not found errors. 
I personally also need this for Python 3.8 (since I depend on boostpython_jll which is capped at 3.8). Is there a way to also add this as a "backport" to 3.8? (this is my first time doing anything Yggdrasil)
> build Python with sqlite

- N/NRLMSIS/build_tarballs.jl
This is the NRLMSIS 2.1, a relatively widely used atmospheric model described at 
https://ccmc.gsfc.nasa.gov/models/NRLMSIS~v2.0/ (not yet updated for version 2.1)
FORTRAN code, I had success with local deployment for
platforms = [Linux(:x86_64, libc=:glibc, libgfortran_version=5.0.0)]
A NRLMSIS.jl package to follow soon. See also https://github.com/SWxTREC/pymsis
> Added NRLMSIS2.1 (empirical atmospheric model)

- L/LLVM/LLD@14/build_tarballs.jl
- L/LLVM/common.jl
Macos needs dSYM files to get correct debug info, so we should ship dsymutil with it.
> Ship dsymutil together with LLD 

- S/SPIRV_Headers/build_tarballs.jl
The patch version is not indicated officially, so it can be used to indicate subsequent releases of the same minor version.
> Update SPIRV_Headers to version 1.6.0

- P/pandoc_crossref/build_tarballs.jl
After this is done, I'll do a follow-up for pandoc_crossref for pandoc 3.0, but it would be nice to have pandoc_crossref work with the last release of the pandoc 2.x series.
> update pandoc_crossref for pandoc 2.9

- G/Git/build_tarballs.jl
CC: @mortenpi 
Ref https://github.com/JuliaVersionControl/Git.jl/issues/40.
> [Git] Upgrade to v2.36.1 and add hack for macOS

- L/libexif/build_tarballs.jl
- To add support for libexif in arm based macos
> [libexif] Upgrade to 0.6.24 and build for new platforms

- E/Exodus/build_tarballs.jl
- E/Exodus/bundled/patches/0001-Patch-for-changes-to-some-library-names-and-NetCDF-c.patch
Adding a patch to the seacas git repository that fixes 4 minors issues on Windows builds. Three of them are the name of header files are capitalized vs. not and the fourth is related to the seacas cmake build automatically killing windows builds, that was simply commented out in the git patch.
Differences to the build_tarballs.jl include
1. Changed version number to actually match the exodusII library version number in seacas.
2. Added atomic_patch of git patch described above.
3. Added exodiff as executable product. This is used to test diffs between exodusII databases.
4. nem_slice and nem_spread libraries as products. These are used to perform mesh decomposition for parallel calculations.
5. epu as executable product. This is used to 'stitch' decomposed meshes back together after …
> Exodus_jll updates

- L/libaec/build_tarballs.jl
Previously libaec was only built for Linux. Here we expand to all platforms.
> Build libaec for all platforms

- G/Git/build_tarballs.jl
`readlink -f` isn't available on macOS.
We don't expect these to be symlinks anyway.
Fixes https://github.com/JuliaVersionControl/Git.jl/issues/48.
> Git: Don't use `readlink` in script wrappers.

- L/LibTracyClient/LibTracyClient@0.9.0/build_tarballs.jl
- L/LibTracyClient/LibTracyClient@0.9.0/bundled/patches/libTracyClient-no-crash-handler.patch
This is a relatively opinionated set of (non-)features that we'd like to support initially for profiling base Julia.
Eventually, we'll probably want to provide other variants with:
- `TRACY_ON_DEMAND` disabled
- `TRACY_DELAYED_INIT` enabled (and possibly `TRACY_MANUAL_LIFETIME` enabled, too)
> [LibTracyClient] Revise selected feature set.

- D/ducc0/build_tarballs.jl
Tests done on Windows have shown that the library crashes whenever `alm2leg` is called. Thanks to @mreineck, this was traced back to a wrong alignment (not on 32-bit boundaries). This is caused by AVX/AVX2 flags, which should not be used to compile Ducc0 under Windows.
This PR fixes the problem by filtering Windows+AVX/AVX2 out of the list of binaries to build.
> [ducc0] Avoid AVX/AVX2 on Windows

- L/LibGit2/build_tarballs.jl
Follow-up to https://github.com/JuliaPackaging/Yggdrasil/pull/6297
[v1.6.0](https://github.com/libgit2/libgit2/releases/tag/v1.6.0) was retracted because it had the wrong soversion
> [LibGit2] Update to v1.6.1

- L/LaMEM/build_tarballs.jl
version 1.2.2, which fixes bugs that prevented the BB version to work on Apple Silicon machines & updates the VTK output routines to a more recent version.
> [LaMEM] update version

- D/ducc0/build_tarballs.jl
We want to keep the generic architecture anyway, so don't expand it at all and avoid troubles with Pkg.
CC: @ziotom78.
> [ducc0] Simplify expansion of microarchitectures for Windows

- N/nghttp2/build_tarballs.jl
[nghttp2 v1.52.0 released 2023-02-13](https://github.com/nghttp2/nghttp2/releases/tag/v1.52.0)
> [nghttp2] Upgrade to v1.52.0

- M/MPItrampoline/build_tarballs.jl
I did not update the `MPItrampoline_jll` version number since this change is not visible from the outside.
> MPItrampoline: Update enclosed MPICH to 4.1

- C/Cares/build_tarballs.jl
From the changelog:
```
Security:
Low. Stack overflow in ares_set_sortlist() which is used during
c-ares initialization and typically provided by an administrator and
not an end user.
```
See https://c-ares.org/changelog.html
> [Cares] Update to version 1.19.0

- S/SuiteSparse/SuiteSparse@7/SuiteSparse/build_tarballs.jl
- S/SuiteSparse/SuiteSparse@7/common.jl
Previous version is almost 2 years old.
> [SuiteSparse@7] New version for v7.0.1

- C/CUDNN/build_tarballs.jl
x-ref https://github.com/JuliaGPU/CUDA.jl/issues/1777
> CUDNN: Explicitly list (and thus dlopen) sublibraries to work around discoverability issues.

- C/CUDA/CUDA_Runtime/build_11.0.jl
- C/CUDA/CUDA_Runtime/build_11.1.jl
- C/CUDA/CUDA_Runtime/build_11.2.jl
- C/CUDA/CUDA_Runtime/build_11.3.jl
- C/CUDA/CUDA_Runtime/build_11.4.jl
- C/CUDA/CUDA_Runtime/build_11.5.jl
- C/CUDA/CUDA_Runtime/build_11.6.jl
- C/CUDA/CUDA_Runtime/build_11.7.jl
- C/CUDA/CUDA_Runtime/build_11.8.jl
- C/CUDA/CUDA_Runtime/build_12.0.jl
@vchuravy This caused an override warning; I assume you were using the CUDA 12 PR?
> CUDA: Add/correct cublasLt entry in runtime JLL.

- M/MPICH/build_tarballs.jl
This is to fix https://github.com/JuliaRegistries/General/pull/79224#issuecomment-1463017796 (see https://github.com/JuliaPackaging/BinaryBuilderBase.jl/pull/298).
> [MPICH] Retriggere build of v4.1.1

- O/OpenEXR/build_tarballs.jl
Updates OpenEXR to version 3.1.6 and switches to GitSource method: https://github.com/AcademySoftwareFoundation/openexr/releases/tag/v3.1.6
> [OpenEXR] version 3.1.4

- S/SHTns/build_tarballs.jl
also hack around fftw_omp requirement of shtns to allow SHTns_jll to use FFTW_jll threads.
> [SHTns] bump v3.5.2, allow omp threads

- M/MPItrampoline/build_tarballs.jl
They cause clashes on case insensitive file systems. Same as #6345. CC @eschnett
> [MPITrampoline] Do not install MPICH man files

- C/CeresSolver/build_tarballs.jl
The purpose of this PR is to generate the latest version of CeresSolver for all platforms, including the Apple Silicon.
Updates:
@giordano Thank you for your comment! There are at least three issues remaining here:
> [CeresSolver] Bump version to 2.1.0

- E/Extrae/build_tarballs.jl
- E/Extrae/bundled/patches/0004-cuda-cupti-undefined-structs-since-v12.patch
Extrae v4.0.3 was released last week and contains some of the patches we needed in order to build it for Yggdrasil. This PR updates the version and disables the patches.
It also refactors the recipe so it is more maintainable ~~and adds support for CUDA 12.1~~.
> [Extrae] Update to version 4.0.3

- C/CUDA/CUDA_Driver/init.jl
Reverts JuliaPackaging/Yggdrasil#6398
I'm not sure how, but this code _did_ apparently got into user environments:
```
Failed to precompile package  
ERROR: LoadError: MethodError: no method matching dlopen(::Nothing; throw_error=false)                                                         
Closest candidates are:                                                                                                                        
dlopen(::AbstractString) at /opt/julia-1.7.3/share/julia/base/libdl.jl:116 got unsupported keyword argument "throw_error"                    
dlopen(::AbstractString, ::Integer; throw_error) at /opt/julia-1.7.3/share/julia/base/libdl.jl:116                                           
dlopen(::Function, ::Any...; kwargs...) at …
```
> Revert "[CUDA_Driver] Initialize globals to nothing"

- C/CUDA/CUDA_Runtime/build_11.0.jl
- C/CUDA/CUDA_Runtime/build_11.1.jl
- C/CUDA/CUDA_Runtime/build_11.2.jl
- C/CUDA/CUDA_Runtime/build_11.3.jl
- C/CUDA/CUDA_Runtime/build_11.4.jl
- C/CUDA/CUDA_Runtime/build_11.5.jl
- C/CUDA/CUDA_Runtime/build_11.6.jl
- C/CUDA/CUDA_Runtime/build_11.7.jl
- C/CUDA/CUDA_Runtime/build_11.8.jl
- C/CUDA/CUDA_Runtime/build_12.0.jl
- C/CUDA/CUDA_Runtime/build_12.1.jl
Only adding the host lib to the products, unsure if target is actually needed.
In the headers there is a ccall to set the search paths... so I assume that the libs do some dlopen'ing
at least according to `ldd` they don't have a dependency on each.
> CUDARuntime_jll add perfworks libs

- S/SuiteSparse/SuiteSparse@7/SuiteSparse/build_tarballs.jl
It didn't work the last time. So removing the option altogether, putting the build on a default path that should include the internal included Metis.
> [SuiteSparse] build with PARTITION (Metis)

- W/WolframAppDiscovery/build_tarballs.jl
See https://github.com/JuliaInterop/MathLink.jl/issues/18
> [WolframAppDisovery] Initial commit, to be used for MathLink.jl

- U/UserNSSandbox/build_tarballs.jl
This adds a small extra test for when `userxattr` is actually harmful, due to `redirect_dir` defaults being different on different kernels.
> [UserNSSandbox] Build v2023.03.28

- L/LLVMExtra/build_tarballs.jl
There are some difficulties with finding ghostscript when it is called directly from the GMT binary, which expects to find it via path. A new change in the C lib adds a code path, that is active only for GMT_jll, to seek the full gs path saved in a file stored in ~/.gmt
> Rebuild using a GMT source that can find ghostscript

- L/librdkafka/build_tarballs.jl
This change enables SASL-based authentication when connecting to Kafka. Currently RDKafka.jl can segfaul with certain connection configurations, and this should provide the necessary functionality to support e.g. SASL-SCRAM authentication.
I have verified locally that the configure script finds libsasl2 and that it is linked.
> Add CyrusSASL dependency to librdkafka

- L/llama_cpp/build_tarballs.jl
- L/llama_cpp/bundled/patches/fix-mingw32-windows-include.patch
This version enables a new mmap-friendly model weights file
format. Unfortunately w64-mingw32 fails to build after these changes,
so disable it for now (no Windows.h or sys/mman.h).
> [llama_cpp] Bump version 

- B/BerkeleyDB/build_tarballs.jl
- L/libevent/build_tarballs.jl
- M/MariaDB_Connector_ODBC/build_tarballs.jl
- M/MongoC/build_tarballs.jl
- O/oxigraph_server/build_tarballs.jl
- Q/Qt/build_tarballs.jl
- Q/Qt6Base/build_tarballs.jl
- Q/qwtw/build_tarballs.jl
- R/ruby/build_tarballs.jl
- S/S2Geometry/build_tarballs.jl
- S/SQLCipher/build_tarballs.jl
- S/systemd/build_tarballs.jl
- V/VerizonEctoken/build_tarballs.jl
[skip build]
Working part of #6312 
Sets compat="1.1.10" for OpenSSL
* BerkeleyDB
* libevent
* MariaDB_Connector_ODBC
* MongoC
* Oxigraph_server
* QT
* Qt6Base
* qwtw
* ruby
* S2Geometry
* SQLCipher
* systemd
* VerizonEctoken
> [OpenSSL] Select working part of mkitti/openssl_compat

- L/LAMMPS/build_tarballs.jl
Actually sets version number correctly
This reverts commit 218bbd6a0baeb7aa63da6994feac7c7d9a5c8a79.
> Reland "Build the most recent LAMMPS patch (#6522)"

- M/MicrosoftMPI/build_tarballs.jl
When we compile Fortran packages with Microsost-MPI, we need the `mpi.mod` file and it was not generated.
> Recompile MicrosoftMPI_jll to generate Fortran mod files

- M/MicrosoftMPI/build_tarballs.jl
I recompiled Microsoft-MPI to generate Fortran module files in #6525 but I forgot to update the `platforms`.
When I tried to use the `mpi.mod` with another package, I had the following error:
```shell
[15:36:56]    15 |   use mpi
[15:36:56]       |      1
[15:36:56] Fatal Error: Cannot read module file ‘mpi.mod’ opened at (1), because it was created by a different version of GNU Fortran
[15:36:56] compilation terminated.
> expand_gfortran_versions(platforms) for Microsoft-MPI

- A/AcousticsToolbox/build_tarballs.jl
Version update for OALIB to support `AcousticsToolbox`
OALIB:
http://oalib.hlsresearch.com/AcousticsToolbox/at_2022_4_20.zip
Upstream issue:
https://github.com/org-arl/AcousticsToolbox.jl/issues/7
> Update AcousticsToolbox to v2022_4_20

- S/SCS_GPU/build_tarballs.jl
I don't have a GPU, so I haven't tested this. 
But monkey see, monkey do: https://github.com/jump-dev/SCS.jl/pull/267. The tests are failing and this warning is printed:
cc @kalmarek 
@bodono: is this correct?
> [SCS_GPU] update to latest commit

- G/GMT/build_tarballs.jl
New -S grdpaste option gives back info necessary to implement the grdpaste functionality in pure Julia
> [GMT] Rebuild artifact to allow access to the new grdpaste option

- F/file/build_tarballs.jl
It's incredibly difficult to search for this tool online.
> [file] Add GNU file `v5.44`

- P/PTSCOTCH/build_tarballs.jl
I don't understand why `libgfortran5` can't be found for `x86_64-linux-gnu-mpi+mpitrampoline` :thinking: .
> Regenerate PTSCOTCH_jll with a compat entry for SCOTCH_jll

- K/Kira/build_tarballs.jl
Kira needs the external program `Fermat` from [page](https://home.bway.net/lewis/).
Though the source code of the old version of `Fermat` was open-sourced under the GNU GPL as [page](https://home.bway.net/lewis/) says, I have no copy for it.
Therefore I cannot build `Fermat` for most platforms.
However, the building of `Kira` is irrelevant to the Fermat binary, so I try this recipe here for the platforms supported by `Fermat`.
This is just a try.
It would be great if `Yggdrasil` accepts it or not.
> New Recipe: Kira v2.3.0

- C/CUDA/CUDA_Runtime/platform_augmentation.jl
We can't trust compatibility bounds during package upgrades (i.e., when package augmentation hooks run).
> CUDA: Make sure platform augmentation is compatible with older JLLs.

- L/libigc/build_tarballs.jl
I had removed OpenCL support because oneAPI.jl doesn't use it, but now it turns out the NEO_jll build process uses IGC's OpenCL compiler to compile builtins... Hopefully we can split the package at some point using https://github.com/JuliaPackaging/BinaryBuilder.jl/issues/778, but I don't feel like doing it manually right now, so just restore the OpenCL bits (but always strip debug info to reduce the JLL size).
> oneAPI: Restore IGC OpenCL support.

- R/rustfft/build_tarballs.jl
Many variations of this warning appear during the audit phase when building for Windows locally:
BFD: librustfft.dll: Unrecognized storage class 106 for *UND* symbol `jl_unionall_type'
The DLL works correctly, though.
> Add recipe for RustFFT

- L/louvain/build_tarballs.jl
Looks like louvain_jll long time ago was not built for M-Series Macs and it's causing an issue now.
> [louvain_jll] Adding macOS aarch64

- M/mlpack/build_tarballs.jl
With #6656 merged, now I can update mlpack.
(Although: should this wait for a day until the updated `armadillo_jll` package properly hits the repositories?  I'm not sure how long that takes.  I'll check the build logs when they're done to make sure Armadillo 12.2.0 was used...)
> Update mlpack to version 4.1.0.

- B/Bison/build_tarballs.jl
This is an attempt to avoid errors such as the following:
```
julia> using Bison_jll
run(`$(Bison_jll.bison()) --version`)
Inconsistency detected by ld.so: dl-version.c: 204: _dl_check_map_versions: Assertion `needed != NULL' failed!
```
> [Bison] avoid adding `Libiconv` as a dependency on Linux, and build with GCC 5+

- R/robin-hood-hashing/build_tarballs.jl
- R/robin_hood_hashing/build_tarballs.jl
Adding this header-only library: https://github.com/martinus/robin-hood-hashing
Added in context of an effort to build https://github.com/KhronosGroup/Vulkan-ValidationLayers
> Add recipe for robin-hood-hashing

- S/SBML/build_tarballs.jl
- Bumps SBML to v5.20.0[^1].
~- GCC version need not be fixed to v6 anymore, as the linked issue is resolved.~
- Switches to `GitSource` - as `ArchiveSource` may not have a stable checksum in the future[^2]
[^1]:https://github.com/sbmlteam/libsbml/releases/tag/v5.20.0
[^2]:https://github.blog/2023-02-21-update-on-the-future-stability-of-source-code-archives-and-hashes/
> chore: bump SBML to v5.20.0

- L/libsigcpp/libsigcpp@2.12.0/build_tarballs.jl
- L/libsigcpp/libsigcpp@3.4.0/build_tarballs.jl
libsigc++-2.0 and libsigc++-3.0 are "parallel-installable" ABI's used with GTK3 and GTK4, respectively.
Rather unintuitively, the entire `*mm` stack is split on this ABI even for libraries (e.g. Pango) whose C bindings have no such breaking ABI change. This means that the minor version of every GTK-upstream library must be constrained to respect the `libsigc++` ABI bifurcation.
> [libsigc++] Bump to v3.4.0 and add v2.12.0

- L/libsigcpp/libsigcpp@3.4.0/build_tarballs.jl
Several of the libraries in the GTK4mm dependency chain do not build with clang++ so we have to switch to GCC and fully-expand the string ABI for `libsigc++-3.0` just like we do for `libsigc++-2.0`
> [libsigc++] Use `gcc` to compile `libsigc++-3.0`

- L/libsigcpp/libsigcpp@2.12.0/build_tarballs.jl
See https://github.com/JuliaPackaging/Yggdrasil/pull/6688#discussion_r1183640855
Unfortunately, it looks like several of the libraries in the GTK4mm dependency chain also do not build with `clang++` so we'll probably have to switch to GCC and fully-expand string ABI's for `libsigc++-3.0` too
> [libsigc++] Expand C++ string ABI for all systems

- G/Glibmm/Glibmm@2.66.6/build_tarballs.jl
This is the latest version with the libsigc++-2.0 ABI, for use with GTK3.
> [Glibmm] Add v2.66.6

- A/ATK/build_tarballs.jl
It's been a minute since ATK was updated, so this should get us some new targets as well (including aarch64-apple-darwin).
> [ATK] Bump version to 2.38.0

- A/ATKmm/ATKmm@2.28.3/build_tarballs.jl
This is the latest version with the libsigc++-2.0 ABI, for use with GTK3.
> [ATKmm] Add v2.28.3

- C/Cairomm/Cairomm@1.16.2/build_tarballs.jl
- C/Cairomm/Cairomm@1.16.2/bundled/patches/disable-quartz-aarch64-apple-darwin.patch
This is the latest version with libsigc++-3.0, for use with GTK4.
> [Cairomm] Bump to v1.16.2

- L/libblastrampoline/build_tarballs.jl
Includes https://github.com/JuliaLinearAlgebra/libblastrampoline/commit/81316155d4838392e8462a92bcac3eebe9acd0c7
> [libblastrampoline] Bump to v5.8.0

- L/LAPACK/LAPACK/build_tarballs.jl
- L/LAPACK/LAPACK32/build_tarballs.jl
- L/LAPACK/common.jl
Libblastrampoline v5.4.0 is compatible only with Julia v1.9+, but it has a stable ABI on all platforms, including Windows.
CC: @fredrikekre.
> [LAPACK] Upgrade to v3.10.1 and require newer libblastrampoline

- L/LAPACK/LAPACK/build_tarballs.jl
- L/LAPACK/LAPACK32/build_tarballs.jl
- L/LAPACK/common.jl
> LAPACK 3.11.0

- Q/Qhull/build_tarballs.jl
- Q/QhullMiniWrapper/build_tarballs.jl
Update the version of Qhull and MiniQhullWrapper and also (hopefully) trigger the build for aarm64 architecture in the process.
> [Qhull] version update

- D/DGGRID7/build_tarballs.jl
This PR aims to fix a version mismatch of DGGRID7_jll and GDAL_jll by updating DGGRID7_jll to the latest official release 7.7 of [DGGRID](https://github.com/sahrk/DGGRID/) that works with BinaryBuilder. @allixender what do you think?
Executing in docker image julia:1.8.5-bullseye :
```{julia}
using Pkg
Pkg.add("DGGRID7_jll")
using DGGRID7_jll
download("https://raw.githubusercontent.com/sahrk/DGGRID/4f24e9de46f9e669af4cba94d9d148b557a1de11/examples/icosahedron/icosahedron.meta", "meta.txt")
mkdir("outputfiles")
DGGRID7_jll.dggrid() do dggrid_path
run(`$dggrid_path meta.txt`)
end
```
results in error
```
/root/.julia/artifacts/3381b9f883af7e984906191545c4fa939e07e91b/bin/dggrid: error while loading shared libraries: libgdal.so.28: cannot open shared object file: No such file or directory …
```
> Fix GDAL and bump version of DGGRID7
