JuliaPackaging/Yggdrasil

- A/ADIOS2/build_tarballs.jl
- A/ADIOS2/bundled/patches/ndims.patch
This function has a bug that is corrected with that patch. There is a PR for this patch; I expect it to be included in the next version of ADIOS2.
> ADIOS2: Apply patch to adios2_variable_ndims

- B/Birch/build_tarballs.jl
- B/Birch_Standard/build_tarballs.jl
- C/CGAL/build_tarballs.jl
- C/CryptoMiniSat/build_tarballs.jl
- M/mlpack/build_tarballs.jl
- P/PCL/build_tarballs.jl
- Q/qwtw/build_tarballs.jl
- R/RDKit/build_tarballs.jl
See also https://github.com/JuliaRegistries/General/pull/37834
> Fix compat of packages depending on boost_jll

- Q/Qt5Base/build_tarballs.jl
@barche I don't really know what I'm doing, so it'd be great if you could have a look :slightly_smiling_face:
> [Qt5Base] Build for `aarch64-apple-darwin`

- O/oneTBB/build_tarballs.jl
- O/oneTBB/bundled/patches/musl.patch
> Wizard recipe: oneTBB-v1.0.0

- L/lrslib/build_tarballs.jl
Close JuliaPolyhedra/LRSLib.jl#45
> [lrslib] Set `-DLRS_QUIET`

- H/HELICS/build_tarballs.jl
Updates the HELICS package to v2.7.1
> [HELICS] update to v2.7.1

- C/cilkrts/build_tarballs.jl
* Package name: cilkrts
* Version: v0.1.2
> Wizard recipe: cilkrts-v0.1.2

- S/sgtsnepi/build_tarballs.jl
Package name: sgtsnepi
Version: v1.0.2
> Wizard recipe: sgtsnepi-v1.0.2

- W/WCS/build_tarballs.jl
- W/WCS/bundled/patches/soname-macos.patch
This patch has been already upstreamed and it'll be in the next release of
WCSLIB, together with our other patch for MinGW
> [WCS] Properly set soname for macOS library

- J/jq/build_tarballs.jl
* Package name: jq
* Version: v1.6.0
> Wizard recipe: jq-v1.6.0

- C/Coin-OR/SYMPHONY/build_tarballs.jl
- C/Coin-OR/coin-or-common.jl
Extracted from https://github.com/JuliaPackaging/Yggdrasil/pull/3139
> [SYMPHONY] add initial builder

- G/gocloc/build_tarballs.jl
* Package name: gocloc
* Version: v0.4.1
> Wizard recipe: gocloc-v0.4.1

- L/LibTorchCAPI/build_dylib.sh
- L/LibTorchCAPI/build_tarballs.jl
The wrapper of libtorch for https://github.com/data-efficient-ml/ThArrays.jl.
> [LibTorchCAPI] Add libtorch capi

- L/libsingular_julia/common.jl
- L/libsingular_julia/libsingular_julia@1.3/build_tarballs.jl
> Update libsingular to 0.13 for Julia 1.3

- C/Coin-OR/BiCePS/build_tarballs.jl
- C/Coin-OR/coin-or-common.jl
Extracted from https://github.com/JuliaPackaging/Yggdrasil/pull/3139
> [BiCePS] add initial builder

- L/Libiconv/build_tarballs.jl
Ref https://github.com/JuliaPackaging/Yggdrasil/pull/3165#issuecomment-864589023.  CC: @nalimilan.
> [Libiconv] Backport extra encodings to old Julia versions

- L/libinput/build_tarballs.jl
Still depends on #3201.
[ci skip]
> add recipe for libinput

- L/Libtask/build_tarballs.jl
- L/Libtask/bundled/task.c
> Make task context copying mem-layout irrelative

- L/LHAPDF/build_tarballs.jl
- L/LHAPDF/bundled/patches/ldflags-no-undefined.patch
- L/LHAPDF/bundled/patches/undefined-setenv-mingw.patch
* Package name: LHAPDF
* Version: v6.3.0
> Wizard recipe: LHAPDF-v6.3.0

- L/Lua/build_tarballs.jl
- L/Lua/bundled/patches/src_Makefile.patch
Lua is notorious for not following semver. We'll see whether they've changed the build system...
> Bump Lua to v5.4.3

- 0_RootFS/LLVMBootstrap@12/build_tarballs.jl
- 0_RootFS/LLVMBootstrap@12/bundled/patches/0002-llvm8_libcxx_musl.patch
- 0_RootFS/LLVMBootstrap@12/bundled/patches/0010-add-musl-triples.patch
- 0_RootFS/LLVMBootstrap@12/bundled/patches/0100-llvm-12-musl-bb.patch
- 0_RootFS/llvm_common.jl
Companion pull request in BinaryBuilderBase: https://github.com/JuliaPackaging/BinaryBuilderBase.jl/pull/155
> [LLVMBootstrap] Add version 12.0.0

- L/LLVMExtra/build_tarballs.jl
cc: @wsmoses @maleadt
For now this is hostest at https://github.com/vchuravy/LLVMExtra and only contains the extras from Julia,
I will add my recent PRs for extended OrcV2 later.
> add LLVMExtra protoype

- F/fzf/build_tarballs.jl
https://github.com/junegunn/fzf/releases/tag/0.27.2
> [fzf] update to 0.27.2

- B/Blosc2/build_tarballs.jl
https://github.com/Blosc/c-blosc2/releases/tag/v2.0.1
> Update c-blosc2 to 2.0.1

- F/FFTW/build_tarballs.jl
Needed for building QuantumEspresso
> [FFTW] enable legacy fortran infterface

- .ci/Manifest.toml
This reverts commit d659a5274cd1d32d184fd695e25a5c760c693915.
> Revert "Revert "[AZP] Update BinaryBuilder and BinaryBuilderBase (#3197)""

- .ci/Manifest.toml
- L/LLVM/LLVM_full_assert@12.0.0/build_tarballs.jl
- Revert "[AZP] Update BinaryBuilder and BinaryBuilderBase (#3197)"
- [LLVM_full] Trigger assert build
> [LLVM_full] Trigger assert build

- L/libsingular_julia/common.jl
- L/libsingular_julia/libsingular_julia@1.3/build_tarballs.jl
> [libsingular_julia] New version for julia 1.3

- S/SuiteSparse/SSGraphBLAS/build_tarballs.jl
I messed up the last one I think. Bugfix needed for new release.
> [SuiteSparseGraphBLAS] Bugfix

- L/LLVMExtra/build_tarballs.jl
@maleadt this also contains your changes from maleadt/LLVM.jl#246
> [LLVMExtra] Build from LLVM.jl

- I/ITSOL_2/build_tarballs.jl
GitHut repository has some interface updates and bug fixes.
> [ITSOL_2] Changed source code reposity to GitHub from ITSOL tar package, Github repo includes some minor updates. 

- L/libsharp2/build_tarballs.jl
> [libsharp2] Enable multiarch and build for experimental platforms

- S/SLATEC/build_tarballs.jl
- S/SLATEC/bundled/LICENSE
Builder for SLATEC from www.netlib.org/slatec/
> [SLATEC] Initial builder for public domain Fortran math library SLATEC.

- S/soapysdr/build_tarballs.jl
- S/soapysdr/bundled/patches/win32notmsvc.patch
- S/soapysdr/bundled/win32notmsvc.patch
* Package name: soapysdr
* Version: v0.8.0
> Wizard recipe: soapysdr-v0.8.0

- F/fpzip/build_tarballs.jl
* Package name: fpzip
* Version: v1.3.0
> Wizard recipe: fpzip-v1.3.0

- P/pandoc_crossref/build_tarballs.jl
Related to Pandoc 2.14 (#3291).
> [pandoc_crossref] Version 0.3.11.0

- L/libclangex/build_tarballs.jl
Thin Clang wrappers for https://github.com/Gnimuc/ClangComplier.jl
> Add recipe for libclangex

- 0_RootFS/Rootfs/build_tarballs.jl
- 0_RootFS/Rootfs/bundled/libs/csl/download_csls.sh
Companion pull request in BinaryBuilderBase: https://github.com/JuliaPackaging/BinaryBuilderBase.jl/pull/165
> [Rootfs] Update base image, Meson and CompilerSupportLibraries

- L/LLVM/common.jl
> [LLVM] Don't break CMAKE files of Clang_jll

- H/HIP/build_tarballs.jl
- H/HIP/bundled/patches/disable-pch.patch
- H/HIP/bundled/patches/hipcc-bb-paths.patch
- H/HIP/bundled/patches/rocclr-not-hcc-platform.patch
WIP until I can get rocBLAS, rocFFT, and rocRAND built and working.
TODO:
> [New package] Add HIP_jll 4.0.0

- L/LLVM/Clang@12.0.1/build_tarballs.jl
- L/LLVM/Clang_assert@12.0.1/build_tarballs.jl
- L/LLVM/LLVM@12.0.1/build_tarballs.jl
- L/LLVM/LLVM_assert@12.0.1/build_tarballs.jl
- L/LLVM/MLIR@12.0.1/build_tarballs.jl
- L/LLVM/common.jl
- [LLVM] add LLVM and Clang 12.0.1
- [LLVM] add MLIR 12.0.1
> [LLVM] Add dependent packages for LLVM@12.0.1

- L/libjlnode/build_tarballs.jl
It's the binary dependency of [`NodeCall.jl`](https://github.com/sunoru/NodeCall.jl).
> [jlnode] Add initial recipe.

- F/FLINT/build_tarballs.jl
EDIT: OK I get it. This should be fine.
CC: @fingolfin
> [FLINT] New version 2.8.0

- U/URCU/build_tarballs.jl
* Package name: URCU
* Version: v0.13.0
> Wizard recipe: URCU-v0.13.0

- G/GAP/GAP@1.3-1.6/build_tarballs.jl
- G/GAP/common.jl
- G/GAP_lib/build_tarballs.jl
This supersedes PR #3316 partially.
> Update GAP, prepare for multiple Julia variants

- G/GAP/GAP@1.3-1.6/build_tarballs.jl
- G/GAP/GAP@1.7/build_tarballs.jl
- G/GAP/common.jl
- G/GAP_lib/build_tarballs.jl
> GAP_jll for Julia >= 1.7

- L/lttng_ust/build_tarballs.jl
* Package name: lttng_ust
* Version: v2.12.2
> Wizard recipe: lttng_ust-v2.12.2

- L/lttng_tools/build_tarballs.jl
* Package name: lttng_tools
* Version: v2.12.4
> Wizard recipe: lttng_tools-v2.12.4

- N/normaliz/build_tarballs.jl
> [normaliz] bump to 3.9.0, update flint dependency, compat for nauty

- L/libsingular_julia/common.jl
- L/libsingular_julia/libsingular_julia@1.3/build_tarballs.jl
> update libsingular to 0.16 for Julia 1.3

- Y/yq/build_tarballs.jl
It's [yq](https://mikefarah.gitbook.io/yq/)!
> New recipe: yq

- G/GR/build_tarballs.jl
> [GR] Update to v0.58.1

- F/FLINT/build_tarballs.jl
- F/FLINT/bundled/patches/remove_endianness_check.patch
This broke everything and we need a rather quick fix.
@fingolfin @tthsqe12 Please double check.
> Remove wrong endianness check

- I/Imath/build_tarballs.jl
Anticipating a similar bump for OpenEXR.
> Bump Imath: v3.0.1 -> v3.1.2

- L/LLVMExtra/build_tarballs.jl
For https://github.com/maleadt/LLVM.jl/pull/255.
> Bump LLVMExtra.

- H/HiGHS/build_tarballs.jl
> [highs] Bump version of HiGHS

- I/Icestorm/build_tarballs.jl
This add support for Icestorm, the open source bitstream documentation for Lattice Ice40 FPGAs.
> [icestorm] init

- L/libjulia/common.jl
- L/libjulia/libjulia@1.5/build_tarballs.jl
- L/libjulia/libjulia@1.5/bundled/patches/0006-skip-dsymutil-segfaults.patch
> Libjulia 1.5.4

- Z/Zlib/build_tarballs.jl
> [Zlib] Touch build_tarballs.jl to trigger rebuild

- X/XZ/build_tarballs.jl
> [XZ] Touch build_tarballs.jl to trigger a rebuild

- N/Netgen/build_tarballs.jl
This adds Netgen, a Layout-versus-schematic (LVS) checking tool which supports many netlist formats.
> [netgen] init

- O/OpenBLAS/OpenBLAS32@0.3.10/build_tarballs.jl
- O/OpenBLAS/OpenBLAS32@0.3.13/build_tarballs.jl
> [OpenBLAS32] Touch build_tarballs.jl to trigger a rebuild

- O/OpenBLAS/OpenBLASHighCoreCount@0.3.10/build_tarballs.jl
- O/OpenBLAS/OpenBLASHighCoreCount@0.3.13/build_tarballs.jl
> [OpenBLASHighCoreCount] Touch build_tarballs.jl to trigger a rebuild

- O/OpenBLAS/OpenBLAS@0.3.10/build_tarballs.jl
- O/OpenBLAS/OpenBLAS@0.3.13/build_tarballs.jl
> [OpenBLAS] Touch build_tarballs.jl to trigger a rebuild

- Y/yaml_cpp/build_tarballs.jl
* Package name: yaml_cpp
* Version: v0.7.0
> Wizard recipe: yaml_cpp-v0.7.0

- U/UserNSSandbox/build_tarballs.jl
See https://github.com/staticfloat/Sandbox.jl/pull/48 for context
> Update UserNSSandbox to add support for the `--tmpfs-size` option

- L/libsigcpp/build_tarballs.jl
* Package name: libsigcpp
* Version: v3.0.7
> Wizard recipe: libsigcpp-v3.0.7

- F/ffts/build_tarballs.jl
- F/ffts/bundled/patches/c11.patch
- F/ffts/bundled/patches/doubletype.patch
* Package name: ffts
* Version: v0.9.0
> Wizard recipe: ffts-v0.9.0

- C/Cairomm/build_tarballs.jl
* Package name: Cairomm
* Version: v1.16.1
> Wizard recipe: Cairomm-v1.16.1

- G/Glibmm/build_tarballs.jl
* Package name: Glibmm
* Version: v2.68.1
> Wizard recipe: Glibmm-v2.68.1

- A/ATKmm/build_tarballs.jl
* Package name: ATKmm
* Version: v2.36.1
> Wizard recipe: ATKmm-v2.36.1

- P/Pangomm/build_tarballs.jl
* Package name: Pangomm
* Version: v2.49.1
> Wizard recipe: Pangomm-v2.49.1

- Y/yaml_cpp/build_tarballs.jl
https://github.com/JuliaPackaging/Yggdrasil/pull/3522#issuecomment-902735410
> Build yaml_gcc with gcc to avoid link errors

- L/LLVM/LLVM_full@11.0.1/build_tarballs.jl
- L/LLVM/LLVM_full@12.0.1/build_tarballs.jl
- L/LLVM/common.jl
> [LLVM_full] Touch build_tarballs.jl to trigger a rebuild

- L/LLVM/libLLVM@11.0.1/build_tarballs.jl
- L/LLVM/libLLVM@12.0.1/build_tarballs.jl
> [libLLVM] Bump LLVM_full build revision

- O/OpenBLAS/OpenBLAS32@0.3.17/build_tarballs.jl
- O/OpenBLAS/OpenBLAS32@0.3.17/bundled/patches/neoverse-generic-kernels.patch
- O/OpenBLAS/OpenBLAS32@0.3.17/bundled/patches/openblas-ofast-power.patch
- O/OpenBLAS/OpenBLAS32@0.3.17/bundled/patches/openblas-winexit.patch
- O/OpenBLAS/OpenBLAS@0.3.17/build_tarballs.jl
- O/OpenBLAS/OpenBLAS@0.3.17/bundled/patches/neoverse-generic-kernels.patch
- O/OpenBLAS/OpenBLAS@0.3.17/bundled/patches/openblas-ofast-power.patch
- O/OpenBLAS/OpenBLAS@0.3.17/bundled/patches/openblas-winexit.patch
- O/OpenBLAS/OpenBLASHighCoreCount@0.3.17/build_tarballs.jl
- O/OpenBLAS/OpenBLASHighCoreCount@0.3.17/bundled/patches/neoverse-generic-kernels.patch
- O/OpenBLAS/OpenBLASHighCoreCount@0.3.17/bundled/patches/openblas-ofast-power.patch
- O/OpenBLAS/OpenBLASHighCoreCount@0.3.17/bundled/patches/openblas-winexit.patch
- O/OpenBLAS/common.jl
This allows us to drop a number of patches.
> [OpenBLAS] Add v0.3.17

- L/libusb/build_tarballs.jl
> [libusb] update to 1.0.24 and enable experimental platforms

- X/XyceWrapper/build_tarballs.jl
- X/XyceWrapper/src/CMakeLists.txt
- X/XyceWrapper/src/xycelib.cpp
Replace #3574 with fixed for Apple and MinGW (don't have permission to push to that branch).
> XyceWrapper: Expand platforms

- E/EarCut/build_tarballs.jl
- E/EarCut/bundled/cwrapper.cpp
- E/EarCut/bundled/generate.jl
The whole EarCutBuilder setup was pretty ridiculous and from ancient times...
> [EarCut] clean up sources and add m1 support

- J/JonkerVolgenant/build_tarballs.jl
* Package name: JonkerVolgenant
> Wizard recipe: JonkerVolgenant-v1.0.0

- P/polymake/build_tarballs.jl
- P/polymake/bundled/patches/generate_deps_tree.jl
add wrapper needed for some 4ti2 binaries
no compat needed as we just use the binaries from 4ti2
> [polymake] add dependency on 4ti2

- L/LLVM/Clang@12.0.1/build_tarballs.jl
- L/LLVM/Clang_assert@12.0.1/build_tarballs.jl
- L/LLVM/LLVM@12.0.1/build_tarballs.jl
- L/LLVM/LLVM_assert@12.0.1/build_tarballs.jl
- L/LLVM/MLIR@12.0.1/build_tarballs.jl
By the third stage of LLVM rebuilding, you've passed through anger, past
grief, and into blissful acceptance.
> [LLVM] Bump for stackprobe patch

- G/GLPK/build_tarballs.jl
Let's get JuMP working on the M1
> [GLPK] Build for experimental platforms

- L/libpolymake_julia/libpolymake_julia@1.5/build_tarballs.jl
> [libpolymake_julia] bump to 0.4.3 (julia 1.5)

- T/TMatrix/build_tarballs.jl
> Wizard recipe: TMatrix-v0.1.0

- L/libpolymake_julia/libpolymake_julia@1.6/build_tarballs.jl
> [libpolymake_julia] bump to 0.4.3 (julia 1.6)

- L/libpolymake_julia/libpolymake_julia@1.7/build_tarballs.jl
> [libpolymake_julia] bump to 0.4.3 (julia 1.7)

- L/libsingular_julia/libsingular_julia@1.4/build_tarballs.jl
Should only be merged after #3634 is in.
> Regenerate libsingular-julia for Julia 1.4

- L/libsingular_julia/libsingular_julia@1.5/build_tarballs.jl
Should only be merged after #3635 is in.
> Regenerate libsingular-julia for Julia 1.5

- M/MKL/build_tarballs.jl
- M/MKL/script.sh
- M/MKL/script_macos.sh
* Reorganize script to so that selecting individual platforms works
* Deduplicate macOS dylibs
Fixes #3632
Cc: @staticfloat
> Update MKL recipe

- G/GMP/GMP@6.2.1/bundled/patches/gmp-HG-changeset.patch
Same as here (https://github.com/JuliaLang/julia/pull/42293), there’s a compute register issue with gmp 6.2.1, will be fixed in subsequent gmp build.
> Add apple silicon patch

- H/HELICS/build_tarballs.jl
Adds a HELICS package for v2.8.0
> [HELICS] update to v2.8.0

- L/libpcap/build_tarballs.jl
This wizard recipe contains `libpcap` v1.10.1.
https://github.com/the-tcpdump-group/libpcap
> New Recipe: libpcap v1.10.1

- T/TetGen/build_tarballs.jl
See request for aarch64: https://github.com/JuliaGeometry/TetGen.jl/issues/28
> Build TetGen for experimental architectures

- L/LLVM/Clang_assert@12.0.1/build_tarballs.jl
- L/LLVM/LLVM@12.0.1/build_tarballs.jl
- L/LLVM/LLVM_assert@12.0.1/build_tarballs.jl
- L/LLVM/MLIR@12.0.1/build_tarballs.jl
This reverts commit 1602ca0d0d5bd49e7031979161c705ac2cf240c7.
> Revert "[LLVM] retrigger registration (#3682)"

- S/spglib/build_tarballs.jl
See https://github.com/spglib/spglib/releases/tag/v1.16.2
> Bump `spglib` to v1.16.2

- L/LLVM/LLVM_full@12.0.1/build_tarballs.jl
- L/LLVM/LLVM_full_assert@12.0.1/build_tarballs.jl
- L/LLVM/common.jl
> [LLVM] add Zlib as dependency

- A/Arb/build_tarballs.jl
> Update Arb for Apple M1 support

- A/Antic/build_tarballs.jl
> Update Antic for Apple M1 support

- C/Calcium/build_tarballs.jl
Requires #3824 and #3825.
CC @tthsqe12 @wbhart @thofma
> Update Calcium for Apple M1 support

- Q/Qhull/build_tarballs.jl
Incorporates bugfix https://github.com/qhull/qhull/pull/101 noted by @blegat.
Also adds additional accessor functions suggested by @JuhaHeiskala (https://github.com/qhull/qhull/pull/102).
> bump qhull to latest master

- H/HOHQMesh/build_tarballs.jl
> Update HOHQMesh to v1.1.0

- F/FLINT/build_tarballs.jl
> FLINT: rewrite compat

- F/FLINT/build_tarballs.jl
> FLINT 2.8.3 for Julia >= 1.6

- C/Cubature/build_tarballs.jl
It doesn't look like there will be new releases in the near future
> [Cubature] Build for experimental platforms

- D/Dierckx/build_tarballs.jl
Updated the source, even though the source code of this library didn't actually
change.
> [Dierckx] Build for experimental platforms

- S/spglib/build_tarballs.jl
> [spglib] Add CSL to dependencies

- D/Doxygen/build_tarballs.jl
- D/Doxygen/bundled/patches/skip-iconv-in-glibc-test.patch
- Libiconv_jll added for aarch64-apple-darwin, auditor was complaining
- not sure if it should be Doxygen or doxygen
> Add Doxygen-1.9.2

- I/Infernal/build_tarballs.jl
This adds infernal, a bioinformatics program for searching databases for RNA sequence and structure similarity.
https://github.com/EddyRivasLab/infernal
> Add Infernal-1.1.4

- H/HMMER/build_tarballs.jl
A bioinformatics program for searching sequences with profile hidden Markov models.
http://hmmer.org/
> Add HMMER-3.3.2

- S/samtools/build_tarballs.jl
- S/samtools/bundled/patches/samtools.patch
* Package name: samtools
* Version: v1.10.0
> Wizard recipe: samtools-v1.10.0

- Y/Yosys/build_tarballs.jl
- pin deps
- add aarch64-apple-darwin
> [yosys] update to 0.11

- C/cohomCalg/build_tarballs.jl
- C/cohomCalg/bundled/patches/Makefile.patch
> Add cohomCalg builder

- S/Singular/build_tarballs.jl
patch level increase for bug fixes in upstream
We need a new singular_jll to the the ball rolling on a new Singular.jl.
@fingolfin please check the increment, and @hannes14 please confirm this Singular commit is OK from your point of view. Local tests with it check out.
> [Singular] update to 402.101.200

- L/libsingular_julia/build_tarballs.jl
> [libsingular_julia] update to 0.20.0

- G/Gumbo/build_tarballs.jl
> [Gumbo] Rebuild JLL package to use JLLWrappers

- X/XyceWrapper/build_tarballs.jl
This is the second part of: https://github.com/JuliaPackaging/Yggdrasil/pull/3901 
Triggering a rebuild and version bump for use in Xyce.jl.
> [XyceWrapper] rebuild and bump version for 7.4 series

- H/HHsuite/build_tarballs.jl
- H/HHsuite/bundled/patches/arm-simd-march-cmakefile.patch
The HH-suite for protein sequence searching.
https://github.com/soedinglab/hh-suite
> Add HHsuite-3.3.0 build script

- K/Kissat/build_tarballs.jl
Should build on at least x86_64-linux-gnu. Might need to adjust build system in the end, it's not an autoconfig `./configure`.
> [Kissat] New builder

- K/Kissat/build_tarballs.jl
> [Kissat] Correct version number

- P/PMIx/build_tarballs.jl
- add PMIx recipe
- [PMIx] build 4.1.0
> [PMIx] build 4.1.0

- P/prrte/build_tarballs.jl
- [PMIx] fix URL
- Add recipe for PRRTE
> Add PPRTE recipe

- P/PMIx/build_tarballs.jl
- P/prrte/build_tarballs.jl
> [PMIx] fix URL

- P/PMIx/build_tarballs.jl
- P/prrte/build_tarballs.jl
- [PMIx] add zlib
- disable debug
> [PMIx] Disable debug again

- O/OpenMPI/build_tarballs.jl
Fixes #390 and https://github.com/JuliaPackaging/BinaryBuilder.jl/issues/687
> [Open MPI] Use init_block to set env

- L/LibPQ/build_tarballs.jl
Attempting to support https://github.com/invenia/LibPQ.jl/issues/240
No idea if this will build properly on the other two experimental platforms but let's find out
> Update libpq to latest versions of PostgreSQL+tzcode, and build on experimental platforms

- D/Deno/build_tarballs.jl
Also bump the Julia compat to 1.6
> [Deno_jll] update to version 1.16.3 and add aarch64-macos

- P/PMIx/build_tarballs.jl
> [PMIx] Use init_block to set env

- B/BWA/build_tarballs.jl
- B/BWA/bundled/patches/0001-Fix-building-against-GCC-10.patch
- B/BWA/bundled/patches/makefile.patch
Fix #3977.  CC: @jonathanBieler
> [BWA] Add builder for v0.7.17

- B/boostpython/build_tarballs.jl
* Package name: boostpython
* Version: v1.76.0
> Wizard recipe: boostpython-v1.76.0

- X/xdm/build_tarballs.jl
- X/xdm/bundled/patches/musl.patch
- X/xdm/bundled/patches/pyinterp.patch
* Package name: xdm
* Version: v2.4.0
> Wizard recipe: xdm-v2.4.0

- S/SCS/build_tarballs.jl
Replacement for https://github.com/JuliaPackaging/Yggdrasil/pull/3987
x-ref https://github.com/jump-dev/SCS.jl/issues/235
> [SCS] build on experimental platforms

- D/Dex/build_tarballs.jl
- D/Dex/bundled/patches/01-allow-optional-github-gitlab-scopes.patch
- D/Dex/bundled/patches/02-allow-multiple-refresh-tokens.patch
This updates Dex to v2.30.2.
Retains the patches made earlier to:
- support additional scopes for github adn gitlab logins
- enable multiple sessions
> update Dex to v2.30.2

- M/METIS/METIS@5/build_tarballs.jl
> [METIS] build on experimental platforms

- 0_RootFS/Rust/build_tarballs.jl
Companion to https://github.com/JuliaPackaging/BinaryBuilderBase.jl/pull/184
> [Rust] Update to v1.57.0

- L/libpolymake_julia/build_tarballs.jl
add many more platforms
pregenerate application metadata with host-dependencies
> [libpolymake_julia] bump to 0.6

- T/Tokei/build_tarballs.jl
> [Tokei] Build from source

- L/LLVM/LLVM_full@13.0.0/build_tarballs.jl
- L/LLVM/LLVM_full_assert@13.0.0/build_tarballs.jl
- L/LLVM/common.jl
- azure-pipelines.yml
> [LLVM] Build 13.0.0+1

- R/rtlsdr/build_tarballs.jl
* Package name: rtlsdr
* Version: v0.6.0
> Wizard recipe: rtlsdr-v0.6.0

- L/LLVM/MLIR@12.0.1/build_tarballs.jl
- L/LLVM/MLIR@13.0.0/build_tarballs.jl
- L/LLVM/common.jl
> add libMLIRPublicAPI

- L/LLVM/MLIR@12.0.1/build_tarballs.jl
- L/LLVM/common.jl
> [MLIR] Correct version check

- C/CRlibm/build_tarballs.jl
Fix https://github.com/JuliaIntervals/CRlibm.jl/issues/48
> [CRlibm] Build for experimental platforms

- W/Wine/build_tarballs.jl
- W/Wine/bundled/patches/darwin.patch
- W/Wine/bundled/patches/hwcap2.patch
We never built a JLL for this and the build script is a bit weird, so not sure this'll go through, but let's see what happens.
> [wine] Fix and modernize build_tarballs

- J/jemalloc/build_tarballs.jl
* Package name: jemalloc
* Version: v5.2.1
(Motivation: dependency required to build https://github.com/ad-freiburg/qlever)
> [jemalloc] Wizard recipe: jemalloc-v5.2.1

- C/COSMA/build_tarballs.jl
- F/faust/build_tarballs.jl
- U/UBPF/build_tarballs.jl
- U/Unicorn/build_tarballs.jl
- X/XPA/build_tarballs.jl
> Fix nproc syntax

- 0_RootFS/gcc_common.jl
Ref: https://github.com/JuliaPackaging/BinaryBuilderBase.jl/issues/188 and https://github.com/JuliaPackaging/BinaryBuilderBase.jl/pull/192
> [GCCBootstrap] Create symlink `libc.musl-$(arch).so.1` -> `libc.so`

- N/NativeFileDialog/build_tarballs.jl
Let's see how it goes :crossed_fingers:
> [NativeFileDialog] Use Gtk only on Linux and FreeBSD

- S/SBML/build_tarballs.jl
Fix https://github.com/LCSB-BioCore/SBML.jl/issues/152.
CC: @anandijain @exaexa
> [SBML] Upgrade to v5.19.2 and build for experimental platforms

- C/CUDNN/build_tarballs.jl
x-ref: https://github.com/JuliaGPU/CUDA.jl/issues/1291
> Add a custom zlib to CUDNN on Windows.

- S/startin/build_tarballs.jl
StarTIN has extended its C API in https://github.com/hugoledoux/startin/pull/11/files
> Update StarTIN to 0.5.3

- W/Wine/build_tarballs.jl
This should be sufficient to bootstrap Julia. cc @DilumAluthge
> Build Wine with my patchset

- L/libpolymake_julia/build_tarballs.jl
- L/libsingular_julia/build_tarballs.jl
... for compatibility with latest libjulia 1.8
> Rebuild libsingular_julia

- S/sed/build_tarballs.jl
Also, this is the first rebuild in 2 years, so it also gets us JLLWrapper for this JLL
> sed: enable more platforms

- P/psurface/build_tarballs.jl
- P/psurface/bundled/patches/make-without-hdf5-work.patch
- P/psurface/bundled/patches/use-std-array-not-tr1-array.patch
- P/psurface/bundled/patches/use-std-shared-ptr.patch
This PR adds a `build_tarballs.jl` for the [psurface](https://github.com/psurface/psurface) library.
> add psurface

- G/GTK3/build_tarballs.jl
- G/GTK3/bundled/patches/0001-Use-lowercase-name-for-windows.h.patch
- G/GTK3/bundled/patches/macos-3.24.31.patch
Should fix https://github.com/JuliaGraphics/Gtk.jl/issues/590.  CC: @gbaraldi
> [GTK3] Update to v3.24.31

- L/libjulia/common.jl
Ref: https://github.com/JuliaPackaging/Yggdrasil/pull/4165#issuecomment-1005599824
> [libjulia] Explicitly filter out unsupported platforms for v1.6-

- U/USRPHardwareDriver/build_tarballs.jl
re: https://github.com/EttusResearch/uhd/releases
> [usrp] bump to 4.1.0.5

- L/libcint/build_tarballs.jl
Title says it all I guess. Successfully tested it locally.
> [libcint] Update to version 5.1.0

- P/PROJ/build_tarballs.jl
Getting the latest PROJ before updating the GDAL build.
> [PROJ] build 8.2.1

- C/Calcium/build_tarballs.jl
Build against the newest Arb with compat crudges removed.
> [Calcium]: New version

- B/bliss/build_tarballs.jl
Ref: https://github.com/JuliaPackaging/Yggdrasil/pull/4170#issuecomment-1007561638
> [bliss] Fix installation of `bliss` executable

- S/SCIP/build_tarballs.jl
Same as https://github.com/JuliaPackaging/Yggdrasil/pull/4169 for SCIP alone
> [SCIP] change SHA for new version

- S/SCOTCH/build_tarballs.jl
Last release 6.x.x before the version 7.0.0 (#4192).
> [SCOTCH] Version 6.1.3

- S/SuiteSparse/SSGraphBLAS/build_tarballs.jl
- S/SuiteSparse/SSGraphBLAS/bundled/cpu_features.patch
> [SSGrB] Bump version

- B/Blosc2/build_tarballs.jl
Update blosc to versions 2.0.4 / 38da659cd5862dccbb0457266fe752cfd6541d4f
> Update blosc to versions 2.0.4

- H/HDF5/build_tarballs.jl
> [HDF5] Update to v1.12.1

- F/fzf/build_tarballs.jl
See https://github.com/junegunn/fzf/releases/tag/0.29.0.
> [fzf] Update to version 0.29

- M/MUMPS/MUMPS@5/build_tarballs.jl
> Recompile MUMPS with SCALAPACK32 and OpenBLAS32

- G/GR/build_tarballs.jl
> [GR] Bump GR version

- T/TempestRemap/build_tarballs.jl
remove unneeded deps for NetCDF build
> [TempestRemap] Remove uneeded dependencies

- P/polymake/build_tarballs.jl
- P/polymake/bundled/patches/bliss.patch
- P/polymake/bundled/patches/generate_deps_tree.jl
- P/polymake/bundled/patches/polymake-cross.patch
- P/polymake/bundled/patches/sigchld.patch
small improvements for cross-compilation and wrapper tree
bump bliss dependency
> [polymake] bump to 4.6

- azure-pipelines.yml
Gives
```
[ Info: PkgServer: https://us-east.pkg.julialang.org/registries.conservative -- last updated: Thu, 06 Jan 2022 18:48:06 GMT (18 minutes, 2 seconds, 721 milliseconds ago)
```
> [AZP] add age to registry last updated info

- A/Antlr4CppRuntime/build_tarballs.jl
- A/Antlr4CppRuntime/bundled/patches/forward-cmake-toolchain.patch
* Package name: Antlr4CppRuntime
* Version: v4.9.3
> Wizard recipe: Antlr4CppRuntime-v4.9.3

- S/Singular/build_tarballs.jl
> [Singular] update to v4.3.0

- I/ImageMagick/build_tarballs.jl
> add gs to ImageMagick

- P/PCRE2/build_tarballs.jl
The old FTP website is gone, together with the old release tarballs.  Sigh.
> [PCRE2] Update source URL and hash

- U/UserNSSandbox/build_tarballs.jl
This updates UserNSSandbox to include the `/dev/zero` fix from https://github.com/staticfloat/Sandbox.jl/pull/70
> Update UserNSSandbox to include the `/dev/zero` fix

- U/UserNSSandbox/build_tarballs.jl
See https://github.com/JuliaPackaging/Yggdrasil/pull/4294#issuecomment-1018273769 and https://github.com/JuliaPackaging/Yggdrasil/pull/4289#discussion_r788552413
> Fix the Git URL for UserNSSandbox

- S/SDL2_mixer/build_tarballs.jl
> Update build script for SDL2_mixer

- O/oneTBB/build_tarballs.jl
note to self, don't try to do boolean things after dinner time
> [oneTBB] correct logic for i686-mingw platform filter

- H/hidapi/build_tarballs.jl
This updates hidapi to version 0.11.2
> update hidapi to 0.11.2

- L/libserialport/build_tarballs.jl
> Tag a new build for libserialport to add experimental platforms

- N/NetCDF/NetCDF@julia-1.6/build_tarballs.jl
- N/NetCDF/common.jl
This build script is a bit weird so I'm not sure if this will work, but all the deps should be fine
> Add aarch64-apple to NetCDF

- L/libcint/build_tarballs.jl
Also removed the dependency on OpenBLAS since the library doesn't depend on BLAS anymore since v5.0.0.
> [libcint] Update to version 5.1.1

- B/blaspp/build_tarballs.jl
Requirement for LAPACK++, which together are dependencies of SLATE.
> [blaspp] New builder

- L/lapackpp/build_tarballs.jl
> [lapackpp]

- G/GLFW/build_tarballs.jl
> [GLFW] Update to 3.3.6

- X/XPA/build_tarballs.jl
> [XPA] Build for new platforms

- L/libblastrampoline/build_tarballs.jl
> [libblastrampoline] Build v5.0.0

- F/FastTransforms/build_tarballs.jl
Solves https://github.com/JuliaApproximation/FastTransforms.jl/issues/162
> [FastTransforms] v0.5.3

- F/FastTransforms/build_tarballs.jl
Solves JuliaApproximation/FastTransforms.jl#163
> [FastTransforms] v0.5.4

- 0_RootFS/PlatformSupport/build_tarballs.jl
> [RootFS] Back to phrack for Mac

- E/Expat/build_tarballs.jl
This version fixes some security vulnerabilities.
> [Expat] Update to v2.4.4

- M/Musl/build_tarballs.jl
Needed for #4364 (upgrading to newer version of Alpine Linux requires a newer libc)
> [Musl] Upgrade to v1.2.2

- 0_RootFS/Rootfs/build_tarballs.jl
- 0_RootFS/Rootfs/bundled/libs/libc/download_libcs.sh
- 0_RootFS/Rootfs/bundled/utils/flagon
Companion PR to https://github.com/JuliaPackaging/BinaryBuilderBase.jl/pull/215
> [RootFS] Update base Alpine Linux image to v3.15 and various utils to more recent versions

- P/pigz/build_tarballs.jl
This is one dependency blocking https://github.com/JuliaPackaging/BinaryBuilder.jl/issues/1166, BinaryBuilder.jl on M1
> [pigz] Build for Apple Silicon, etc.

- J/jemalloc/build_tarballs.jl
Fix https://github.com/JuliaPackaging/Yggdrasil/issues/4379
See this repo for an example product: https://github.com/jeremiahpslewis/jemalloc_jll.jl
> [jemalloc] Fix M1!

- L/L_BFGS_B/build_tarballs.jl
Fixes https://github.com/JuliaBinaryWrappers/L_BFGS_B_jll.jl/issues/1.
@angeris in the future please open issues in this repository, not in
repositories under `JuliaBinaryWrappers`, they shouldn't even have the issues
open.
> [L_BFGS_B] Build for new platforms

- Z/Zenith/build_tarballs.jl
Also this one tested only on `x86_64-linux-gnu`
> [Zenith] Add builder

- M/MPIR/build_tarballs.jl
https://github.com/JuliaPackaging/Yggdrasil/pull/4399/files is blocked by this.
> [MPIR] Build for 1.6 compat 

- H/HiGHS/build_tarballs.jl
Follow-up to https://github.com/JuliaPackaging/Yggdrasil/pull/4318 that I can edit.
There are few things that probably need to be fixed upstream before they make an official 1.2 release.
Closes #4318
> [HiGHS] update to v1.2.0

- L/LAMMPS/build_tarballs.jl
- Update to include ML-PACE package
- filter out aarch64-*-gfortran4
> [LAMMPS] Update to include ML-PACE package

- T/TempestRemap/build_tarballs.jl
> [TempestRemap] v2.1.3

- U/Unishox/build_tarballs.jl
Update to new version to see if it solves a bug
> Update to 1.0.2 version of the lib

- .ci/Manifest.toml
- .ci/Project.toml
- .ci/update_manifest.jl
- .github/workflows/update_manifest.yml
This PR also partially reverts #4431 to let us test out the new workflow.
> [CI] Add GitHub Actions workflow to automatically update manifest

- R/rocPRIM/build_tarballs.jl
Needed for upcoming rocSPARSE builder
> [New Package] Add rocPRIM 4.2.0

- H/HiGHS/build_tarballs.jl
Updating v1.2.0 in place, which contains yet more bug fixes.
> [HiGHS] update with more bug fixes

- G/GAP/build_tarballs.jl
- G/GAP_lib/build_tarballs.jl
> Update GAP and GAP_lib to latest

- L/libcxxwrap_julia/build_tarballs.jl
Ping @barche: I hope this is OK for you?
> libcxxwrap_julia: add Julia 1.9 support

- X/xrootdgo/build_tarballs.jl
- X/xrootdgo/bundled/main.go
still need to add more functions and test the internal API a bit.
But I want to put here to see how the compilation goes and also how to source `google/uuid`...
> add xrootdgo

- X/xrootdgo/build_tarballs.jl
- X/xrootdgo/bundled/main.go
> [xrootdgo] add export comment

- 0_RootFS/Go/build_tarballs.jl
Companion PR to https://github.com/JuliaPackaging/BinaryBuilderBase.jl/pull/223
> [0_RootFS] Update Go toolchain to v1.17.7

- C/CUDA/CUDA@10.2/build_tarballs.jl
- C/CUDA/CUDA_loader/build_10.2.jl
> Adapted CUDA_loader and CUDA@10.2 for CUDA_full for aarch64-linux-gnu 

- S/SQLite/build_tarballs.jl
Some outdated configure flags are removed.
> Update SQLite to 3.38

- W/Wayland_protocols/build_tarballs.jl
Needed for https://github.com/JuliaPackaging/Yggdrasil/pull/3192
> [Wayland_protocols] Update to 1.24

- T/TempestRemap/build_tarballs.jl
cc @jakebolewski @mkitti @giordano
> [TempestRemap] try without HDF5

- X/XyceWrapper/build_tarballs.jl
> XyceWrapper: support 1.6.3 and 1.7

- L/libpolymake_julia/build_tarballs.jl
x-ref: https://github.com/oscar-system/Polymake.jl/issues/394
> [libpolymake_julia] rebuild for julia 1.9

- H/HiGHS/HiGHS/build_tarballs.jl
- H/HiGHS/highs_common.jl
> [HiGHS] update to v1.2.1

- L/LibCURL/LibCURL/build_tarballs.jl
Follow-up to #4472
[ci skip]
[skip ci]
> Add the L/LibCURL/LibCURL/build_tarballs.jl file

- I/isoband/build_tarballs.jl
Resolve https://github.com/JuliaPackaging/Yggdrasil/issues/4507
> [isoband] Bump to experimental platforms

- S/SCS/build_tarballs.jl
- S/SCS_GPU/build_tarballs.jl
Before we merge this let me check that the binaries actually work with SCS.jl
> [SCS] update to v3.2.0

- G/GAP/build_tarballs.jl
Not sure if this will work? I.e. perhaps the registry
> GAP: rebuild previous version to add Julia 1.9 support

- H/helpme/build_tarballs.jl
> Wizard recipe: helpme-v0.1.0

- L/LLVMExtra/build_tarballs.jl
https://github.com/maleadt/LLVM.jl/pull/296#issuecomment-1055105781
> [LLVMExtra] Make artifacts lazy due to platform hooks

- R/ranger/build_tarballs.jl
- R/ranger/bundled/patches/cmake-pthreads.patch
- R/ranger/bundled/patches/make_lib_and_install.patch
* Package name: ranger
* Version: v0.13.1
> Wizard recipe: ranger-v0.13.1

- L/LAMMPS/build_tarballs.jl
> [LAMMPS] Rebuild wrapper

- M/MiniFB/build_tarballs.jl
~Draft. Lets see what breaks. Currently only tested on `x86_64-linux-gnu`~
> update minifb to latest

- D/Deldir/build_tarballs.jl
- G/GAP_pkg/GAP_pkg_browse/build_tarballs.jl
- H/HiGHS/highs_common.jl
- I/IGLWrap/build_tarballs.jl
- O/Objconv/build_tarballs.jl
After https://github.com/JuliaPackaging/Yggdrasil/pull/4551 some license files
were renamed to have a more descriptive name, the license text didn't change.
> Rename `/usr/share/licenses/GPL3` to `GPL-3.0+`

- P/PThreadPool/build_tarballs.jl
Matches version used by PyTorch v1.5.0
> Added PThreadPool v0.0.20191029

- P/protoc/build_tarballs.jl
> Changed protoc to build v3.13.0

- M/msolve/build_tarballs.jl
Enable elimination block orderings and different kinds of saturation algorithms
> bump msolve v0.2.3

- E/Emoslib/build_tarballs.jl
- L/libemos/build_tarballs.jl
Adding the binaries for [emoslib](https://confluence.ecmwf.int/display/EMOS/Emoslib).
> New Recipe: Emoslib v4.5.9

- H/HOHQMesh/build_tarballs.jl
> Updated HOHQMesh to v1.2.1

- 0_RootFS/Rust/build_tarballs.jl
> [Rust] Bump RootFS Rust to 1.59.0

- V/VegaFusion/build_tarballs.jl
> [VegaFusion] Bump to version 0.1.0

- S/SDL2_net/build_tarballs.jl
- S/SDL2_net/bundled/patches/configure-add-macro-dir.patch
* Package name: SDL2_net
* Version: v2.0.1
> Wizard recipe: SDL2_net-v2.0.1

- G/glm/build_tarballs.jl
- O/OpenGLMathematics/build_tarballs.jl
I am attempting to create a jll package to wrap GLM for use in C/C++ dependencies of Julia projects.
> New recipe: OpenGLMathematics-v0.9.9

- C/CPUInfo/build_tarballs.jl
Referenced by Torch v1.8.2 - v1.11.0: https://github.com/pytorch/pytorch/tree/v1.11.0/third_party
> Changed CPUInfo recipe to build v0.0.20201217

- G/gitoxide/build_tarballs.jl
> [gitoxide] Add builder

- T/Telescope/build_tarballs.jl
I'm working on a C++ game/rendering/multimedia library.
> New recipe: Telescope-v0.1.2

- P/PThreadPool/build_tarballs.jl
Referenced by Torch v1.6.0-v1.7.1: https://github.com/pytorch/pytorch/tree/v1.7.1/third_party
Awaiting #4617
> Updated PThreadPool to v0.0.20200616

- M/MAGEMin/build_tarballs.jl
> [MAGEMin]: update version to 1.0.2

- T/TensorRT/build_tarballs.jl
Might resolve blocked https://github.com/JuliaRegistries/General/pull/56696
> TensorRT: Disabled dlopen for library products

- M/MAGEMin/build_tarballs.jl
> [MAGEMin]: update to version 1.0.3

- S/SLEEF/build_tarballs.jl
- S/SLEEF/bundled/patches/cross-compile-mingw-on-unix.patch
- S/SLEEF/bundled/patches/lowercase-windows-include.patch
- S/SLEEF/bundled/patches/version.patch
Roughly the version (commit 7f523de651585fe25cade462efccca647dcc8d02) referenced by Torch v1.6.0 - v1.7.1: https://github.com/pytorch/pytorch/tree/v1.7.1/third_party
> Updated SLEEF to v3.4.1

- T/TensorRT/build_10.2.jl
- T/TensorRT/build_11.jl
- T/TensorRT/build_tarballs.jl
> Updated TensorRT to v8.0.3

- M/MAGEMin/build_tarballs.jl
> [MAGEMin]: update version

- G/Gloo/build_tarballs.jl
- G/Gloo/bundled/patches/mingw32.patch
Referenced by Torch v1.6.0: https://github.com/pytorch/pytorch/tree/v1.6.0/third_party
> Added Gloo v0.0.20200317

- M/MAGEMin/build_tarballs.jl
> [MAGEMin]: update version 

- M/MAGEMin/build_tarballs.jl
previous version created a binary out of the wrong file. This fixes that
> [MAGEMin]: version 1.0.5b

- M/msolve/build_tarballs.jl
> [msolve] Use LLVM OpenMP for BSD systems

- Z/z3/build_tarballs.jl
`]add Z3` fails for me using Julia 1.7, so I thought I would try to update the recipe. This is the first time I have worked on Yggdrasil recipes, comments and scrutiny welcomed. 
There are two patches in here that should be removed at a later date: one to get builds working with Julia 1.6, and another to get builds working for macOS. I'm not quite sure I'm doing the `julia_versions` part right, but I intended to follow the example in the [libcxxwrap_julia](https://github.com/JuliaPackaging/Yggdrasil/blob/82eb18cb6222195b9995b98b136f6f5f995fc721/L/libcxxwrap_julia/build_tarballs.jl#L13) recipe.
> Upgrade z3 to v4.8.14 and build for all supported platforms.

- E/Exodus/build_tarballs.jl
> Wizard recipe: Exodus-v0.1.0

- L/libwatcher/build_tarballs.jl
This is port to Julia from the library [parcel-bundler/watcher](https://github.com/parcel-bundler/watcher) hosted at [JuliaPluto/watcher](https://github.com/JuliaPluto/watcher/tree/julia_port).
> add libwatcher

- platforms/llvm.jl
Ref: https://github.com/JuliaPackaging/Yggdrasil/pull/4292#discussion_r832657700
> [platforms/llvm] Fix llvm augmentation block

- G/GR/build_tarballs.jl
> [GR] update to 0.64.1

- D/DecFP/.gitattributes
- D/DecFP/build_tarballs.jl
- D/DecFP/bundled/patches/string.patch
To fix DecFP.jl issue [134](https://github.com/JuliaMath/DecFP.jl/issues/134)
> [DecFP] Fix rounding when parsing strings

- H/HIP/build_tarballs.jl
- H/HIP/bundled/patches/disable-tests.patch
Aimed at fixing issue reported in #4689
> [HIP] Disable tests

- Z/Zlib/build_tarballs.jl
Supersedes https://github.com/JuliaPackaging/Yggdrasil/pull/4691.
> Zlib: Update to 1.2.12

- G/GR/build_tarballs.jl
> [GR] update to version v0.64.2

- M/mold/build_tarballs.jl
> Wizard recipe: mold-v1.0.0

- I/Infernal/build_tarballs.jl
See https://github.com/cossio/Infernal.jl/issues/1
> [Infernal] install easel executables

- S/SuiteSparse/SuiteSparse/build_tarballs.jl
Reverts JuliaPackaging/Yggdrasil#4709
> Revert "Add CXSPARSE component to SuiteSparse"

- T/tree_sitter/build_tarballs.jl
cc: @MichaelHatherly 
Do the grammars need to be updated simultaneously?
> Update tree-sitter lib to v0.20.6

- S/SuiteSparse/CXSparse/build_tarballs.jl
I'm not 100% sure what happened previously, but this seems cleaner.
> [CXSparse] Build separately

- S/SHTns/build_tarballs.jl
* Package name: SHTns
* Version: v3.5.1
> Wizard recipe: SHTns-v3.5.1

- R/RDKit/build_tarballs.jl
- R/RDKit/bundled/patches/do-not-build-cffi-test.patch
- R/RDKit/bundled/patches/popcnt-target-system.patch
- R/RDKit/bundled/patches/static-libraries-windows.patch
Still doesn't really work, opening the PR to save the attempt so far.  Ref: #4714.  CC: @longemen3000
> [RDKit] Update to v2022.03.1 and build for Windows

- L/LaMEM/build_tarballs.jl
> Rebuild LaMEM

- 0_RootFS/LLVMBootstrap@13/build_tarballs.jl
- 0_RootFS/LLVMBootstrap@13/bundled/patches/0002-llvm8_libcxx_musl.patch
- 0_RootFS/LLVMBootstrap@13/bundled/patches/0010-add-musl-triples.patch
- 0_RootFS/LLVMBootstrap@13/bundled/patches/0100-llvm-12-musl-bb.patch
- 0_RootFS/LLVMBootstrap@13/bundled/patches/0100-llvm-13-musl-bb.patch
- 0_RootFS/llvm_common.jl
Draft, it isn't working at the moment
> [0_RootFS] Add LLVMBootstrap v13

- P/Pathfinder/build_tarballs.jl
- P/Pathfinder/bundled/patches/Compile-to-dynamic-lib.patch
Build recipe for [Pathfinder](https://github.com/servo/pathfinder), a Rust drawing library for text and vector graphics using the GPU.
> New recipe: Pathfinder-v0.5.0

- P/Pfapack/build_tarballs.jl
- `-force-load` only work for LLVM-based linkers. Fallback to `--whole-archive`
- Update upstream to use a CMakeLists.txt with all [sdcz] routines
> [Pfapack] Fix .so Contents

- M/METIS/METIS@4/build_tarballs.jl
Needed for https://github.com/JuliaPackaging/Yggdrasil/pull/4721#issuecomment-1100937950
> Add Julia v1.6 requirement for METIS

- Q/Qt5Svg/build_tarballs.jl
Needed to build jlqml ( as requested in https://discourse.julialang.org/t/problems-installing-qml-on-m1-machine/79742/3 )
> [Qt5Svg] Bump version and add apple M1 support

- U/unixODBC/build_tarballs.jl
Should fix https://github.com/JuliaDatabases/ODBC.jl/issues/335.  CC: @quinnj
> [unixODBC] Update to v2.3.9 and build for new platforms

- Q/Qt5QuickControls/build_tarballs.jl
Not a direct jlqml dependency, but loaded dynamically in virtually all QML applications
> [Qt5QuickControls] Bump version and add Apple M1

- L/libcxxwrap_julia/build_tarballs.jl
Newest version plus this fixes CxxWrap on Julia nightly.
> [libcxxwrap-julia] Version 0.9.1

- L/librdkafka/build_tarballs.jl
> [librdkafka] Version 1.8.2

- I/iODBC/build_tarballs.jl
- I/iODBC/bundled/patches/do-not-strip.patch
> [iODBC] Update to v3.52.15 and build for new platforms

- L/libsingular_julia/build_tarballs.jl
Also update julia_compat as in libsingular_julia
Requires #4816
> [libsingular_julia] update for libjulia 1.9

- M/MUMPS/MUMPS_seq@4/build_tarballs.jl
Following https://github.com/JuliaRegistries/General/pull/58881#issuecomment-1105270509
> [MUMPS_seq@4] Bump METIS dependency

- Q/Qt6Base/build_tarballs.jl
First step in updating Qt6Base, building for the host only (see comment at the top of the build_tarballs.jl).
> [Qt6Base] Update to 6.3.0

- P/PORTA/build_tarballs.jl
Updating the build script for the PORTA_jll
> Update PORTA to v1.4.2

- L/libigc/build_tarballs.jl
Ref https://github.com/intel/compute-runtime/issues/522, https://github.com/JuliaGPU/oneAPI.jl/issues/154.
> IGC: cherry-pick change to fix miscompilation.

- F/FLEXPART/bundled/patches/flexpart-parmod.patch
Fix the error that we get if we use non-global domains.
> [FLEXPART] change nxshift to 0

- L/Luna/build_tarballs.jl
- L/Luna/bundled/patches/fix_it.patch
No idea whether this will work without further changes. Let's find out!
> Update Luna to v0.26.2

- C/CUDA/CUDA_full@10.2/build_tarballs.jl
- C/CUDA/CUDA_full@11.3/build_tarballs.jl
- C/CUDA/CUDA_full@11.4/build_tarballs.jl
- C/CUDA/CUDA_full@11.5/build_tarballs.jl
- C/CUDA/CUDA_full@11.6/build_tarballs.jl
Fix for issue discovered in #4554 : CUDA_full@11.3 is missing thrust library
> CUDA_full: Fix missing thrust library

- L/LLVM/Clang@14.0.2/build_tarballs.jl
- L/LLVM/LLD@14.0.2/build_tarballs.jl
- L/LLVM/LLVM@14.0.2/build_tarballs.jl
- L/LLVM/MLIR@14.0.2/build_tarballs.jl
- L/LLVM/common.jl
- build Clang 14.0.2
- build MLIR
- build LLVM
> vc/LLVM 14.0.2+0

- Q/Qt6Svg/build_tarballs.jl
The final QML dependency apart from jlqml itself.
> [Qt6Svg] New package

- M/MMG/build_tarballs.jl
- M/MMG/bundled/patches/MMG.mingw.patch
- M/MMG/bundled/patches/MMG.patch
- M/MMG/bundled/patches/genheader.patch
Adds MMG package for Gmsh.
Depends on #4888.
> Add MMG for Gmsh builds

- C/CUDA/CUDA_full@11.4/build_tarballs.jl
> Update CUDA 11.4 (full).

- C/CUDA/CUDA_full@11.5/build_tarballs.jl
> Update CUDA 11.5 (full).

- C/CUDA/CUDA_full@11.6/build_tarballs.jl
> Update CUDA 11.6 (full).

- C/CUDA/CUDA@11.5/build_tarballs.jl
> Update CUDA 11.5.

- C/CUDA/CUDA@11.6/build_tarballs.jl
> Update CUDA 11.6.

- C/CUDA/CUDA@11.7/build_tarballs.jl
> Update CUDA 11.7.

- C/CUDA/CUDA_loader/build_11.5.jl
- C/CUDA/CUDA_loader/build_11.6.jl
- C/CUDA/CUDA_loader/build_11.7.jl
- C/CUDA/CUDA_loader/build_tarballs.jl
> Update CUDA loader versions 11.4-11.7.

- G/GR/build_tarballs.jl
> [GR] Bump version

- L/LibGit2/build_tarballs.jl
- L/LibGit2/bundled/patches/libgit2-hostkey.patch
This is intended as a companion PR for https://github.com/JuliaLang/julia/pull/45411
- Updates the version
- Adapts one of the two patches
> Upgrade libgit2 to 1.4.3

- X/XGBoost/build_tarballs.jl
Update xgboost to v1.6.1, the latest release
> [XGBoost] Version bump 1.6.1

- L/LinearFold/build_tarballs.jl
This is a new recipe for LinearFold, an RNA secondary structure prediction program:
https://github.com/LinearFold/LinearFold
> New recipe: LinearFold v1.0.0

- L/LinearPartition/build_tarballs.jl
New recipe for LinearPartition, a partition function calculation program for RNA sequences:
https://github.com/LinearFold/LinearPartition
> new recipe for LinearPartition v1.0.0

- G/GEOS/build_tarballs.jl
And add the `geosop` ExecutableProduct which was new in 3.10.0.
> [GEOS] build 3.10.2

- C/CompilerSupportLibraries/build_tarballs.jl
@staticfloat is this what you were thinking to do?
> [CompilerSupportLibraries] Always package latest `libgcc_s` in x86_64-darwin tarball

- M/MPICH/build_tarballs.jl
See https://github.com/JuliaPackaging/Yggdrasil/issues/4938.
> MPICH: Do not build MPIconstants

- O/OpenMPI/build_tarballs.jl
See https://github.com/JuliaPackaging/Yggdrasil/issues/4938.
> OpenMPI: Do not build MPIconstants

- M/MPItrampoline/build_tarballs.jl
See https://github.com/JuliaPackaging/Yggdrasil/issues/4938.
> MPItrampoline: Do not build MPIconstants

- S/SBML/build_tarballs.jl
- S/SBML/bundled/patches/0002-Add-SBMLNamespaces_addPackageNamespace-s-functions-t.patch
CC: @exaexa (draft while waiting for review upstream)
> [SBML] Add patch to add new functions to C API

- Y/Yosys/build_tarballs.jl
Also adds support for Windows.
> [Yosys] Bump to v0.18

- L/LLVM/LLVM_full@14.0.2/build_tarballs.jl
- L/LLVM/LLVM_full_assert@14.0.2/build_tarballs.jl
- L/LLVM/common.jl
Thanks to @vtjnash for spotting this
> Rebuild LLVM with forward slash off for windows

- H/HOHQMesh/build_tarballs.jl
Adds new features of Gaussian curvature automatic sizing to the HOHQMesh package
> update to HOHQMesh version 1.3.0

- S/SBML/build_tarballs.jl
- S/SBML/bundled/patches/0003-Fix-signature-of-SBase_getNumPlugins-in-prototype.patch
> [SBML] Add patch to fix C API of `SBase_getNumPlugins`

- M/mlpack/build_tarballs.jl
cc: @rcurtin @giordano
I tried (naively) to copy the changes we made to armadillo.
> Update mlpack w/ fake version to add apple m1 support

- README.md
> RFC: update the logo

- O/Openresty/build_tarballs.jl
Update Openresty to v1.21.4
Also update some deps, openssl to 1.1.1p, pcre to 8.45 and zlib to 1.2.12.
> Update Openresty to v1.21.4

- P/Packmol/build_tarballs.jl
Packmol creates an initial point for molecular dynamics simulations by packing molecules in defined regions of space. The packing guarantees that short-range repulsive interactions do not disrupt the simulations.
The great variety of types of spatial constraints that can be attributed to the molecules, or atoms within the molecules, makes it easy to create ordered systems, such as lamellar, spherical, or tubular lipid layers.
> [Packmol] new package

- C/casacorewrapper/build_tarballs.jl
Sorry for the formatting changes
> [casacorewrapper] Pin version due to breaking ABI

- M/msolve/build_tarballs.jl
> msolve v0.3.2

- S/SBML/build_tarballs.jl
- S/SBML/bundled/patches/0004-add-FbcReactionPlugin_createGeneProductAssociation-to-C-API.patch
Upstream PR: https://github.com/sbmlteam/libsbml/pull/247. CC: @exaexa.
> [SBML] Add patch to add missing function to C API

- M/msolve/build_tarballs.jl
New julia interface for more specific data on rational parametrization of solution set.
> msolve v0.4.0

- H/hsa_rocr/build_tarballs.jl
- H/hsa_rocr/bundled/patches/musl-affinity.patch
- H/hsa_rocr/bundled/patches/no-symlinks.patch
> hsa_rocr: Bump to 4.5.2

- M/msolve/build_tarballs.jl
Trying also to update flint version, let's see if powerpc build works
> msolve v0.4.1

- T/TulipIndicators/build_tarballs.jl
The TulipIndicators C library: a library of technical analysis functions written in ANSI C.
https://github.com/TulipCharts/tulipindicators
> add TulipIndicators

- L/LAPACK/build_tarballs.jl
Address https://github.com/JuliaRegistries/General/pull/64542#issuecomment-1189195017
> [lapack] 3.10.0 + LBT 5.1.1 + ILP64

- A/ADIOS2/build_tarballs.jl
Also simplify OpenMPI configuration.
> ADIOS2: Require MPItrampoline 5

- D/DDSCAT/build_tarballs.jl
* Package name: DDSCAT
* Version: v7.3.3
> Wizard recipe: DDSCAT-v7.3.3

- A/AMReX/build_tarballs.jl
> AMReX: Require MPItrampoline 5

- O/openPMD_api/build_tarballs.jl
Also simplify OpenMPI configuration
> openPMD_api: Require MPItrampoline 5

- H/HYPRE/build_tarballs.jl
Also simplify configuring MPItrampoline.
> HYPRE: Require MPItrampoline 5

- M/msolve/build_tarballs.jl
Bug fixes for normal forms and saturations.
Trying also to enable AVX... builds.
> msolve v0.4.3

- M/msolve/build_tarballs.jl
Bug fixes for export functionality to Julia
> msolve v0.4.4

- V/viterbi/build_tarballs.jl
This library includes a viterbi decoder and convolutional encoder.
> Add libviterbi

- L/libiio/build_tarballs.jl
Release notes: https://github.com/analogdevicesinc/libiio/releases/tag/v0.24
> [libiio] update to v0.24

- L/libcxxwrap_julia/build_tarballs.jl
Bump version for https://github.com/JuliaInterop/CxxWrap.jl/issues/320
> [libcxxwrap_julia] Bump version to 0.9.2

- P/PROJ/build_tarballs.jl
Should fix the macOS tests: https://github.com/JuliaGeo/Proj.jl/pull/67
Similar to https://github.com/JuliaPackaging/Yggdrasil/pull/4981
> [PROJ] add LibCURL_jll compat

- .ci/Manifest.toml
- D/dSFMT/build_tarballs.jl
Smoke test for https://github.com/JuliaPackaging/BinaryBuilderBase.jl/pull/255
> Bump BBB and test dSFMT sanitizer build 

- A/ADIOS2/build_tarballs.jl
Also filter out unsupported OpenMPI platforms.
> ADIOS2: Update to version 2.8.3

- M/MParT/build_tarballs.jl
Branch name is misleading. This mostly bumps the version of the release.
> Upgrade MParT to v0.3.1

- S/SuiteSparse/SSGraphBLAS/build_tarballs.jl
Minor version, several important new features.
> [SSGraphBLAS] Version bump

- Q/QRupdate_ng/build_tarballs.jl
- Q/QRupdate_ng/bundled/patches/CMakeListsFix.patch
* Package name: QRupdate_ng
* Version: v1.1.5
> Wizard recipe: QRupdate_ng-v1.1.5

- C/Chemfiles/build_tarballs.jl
- C/Chemfiles/patches/arm-musl-endian-detect.patch
This also requires julia>=1.6 to enable Apple ARM64 CPU (https://github.com/chemfiles/Chemfiles.jl/issues/56)
> Update chemfiles to release 0.10.3

- P/PSRDADA/build_tarballs.jl
> Wizard recipe: PSRDADA-v1.0.0

- P/PThreadPool/build_tarballs.jl
Referenced by Torch v1.8.0-v1.8.2: https://github.com/pytorch/pytorch/tree/v1.8.2/third_party
Awaiting #4619 and #4618
> Updated PThreadPool to v0.0.20201005

- P/PThreadPool/build_tarballs.jl
Referenced by Torch v1.8.0-v1.11.0 via XNNPACK: https://github.com/pytorch/pytorch/tree/v1.11.0/third_party
Awaiting #4620
> Updated PThreadPool to v0.0.20201206

- P/PThreadPool/build_tarballs.jl
> Updated PThreadPool to v0.0.20210414

- L/LibCURL/LibCURL/build_tarballs.jl
- L/LibCURL/common.jl
> Build libCURL with msan

- L/LibUV/build_tarballs.jl
> Build LibUV with Msan

- M/MbedTLS/MbedTLS@2.28.0/build_tarballs.jl
- M/MbedTLS/common.jl
> Build mbedtls with msan

- Z/Zlib/build_tarballs.jl
> Build zlib with msan

- Z/ZipFlow/build_tarballs.jl
- Z/ZipFlow/bundled/patches/pr3.patch
- Z/ZipFlow/bundled/patches/windows.patch
Mark Adler at it again https://github.com/madler/zipflow
> Add zipflow

- O/OpenLibm/build_tarballs.jl
> Build OpenLibm with Msan

- P/PCRE2/build_tarballs.jl
> Build PCRE2 with Msan

- N/nghttp2/build_tarballs.jl
> Build nghttp2 with msan

- P/p7zip/build_tarballs.jl
I also think we don't need this one ;-)
> Build p7zip with Msan

- L/libblastrampoline/build_tarballs.jl
> Build libblastrampoline with Msan

- M/MDAL/build_tarballs.jl
Tried to update NetCDF dep to 4.8+ as well
> [MDAL] Update to 9.4 and hopefully build M1

- R/RNAstructure/build_tarballs.jl
RNAstructure is a program suite for RNA secondary structure prediction and analysis
https://rna.urmc.rochester.edu/RNAstructure.html
> new build RNAstructure 6.4.0

- L/LibUnwind/LibUnwind@1.5.0/build_tarballs.jl
> Build LibUnwind with msan

- X/xfoil_light/build_tarballs.jl
There isn't any changes in the actual code, a new version just needs to be released in order to support newer mac platforms.
> xfoil_light_jll

- S/SuiteSparse/SuiteSparse/build_tarballs.jl
- S/SuiteSparse/common.jl
> Build SuiteSparse with Msan

- M/MUMPS/MUMPS_seq@5/build_tarballs.jl
- M/MUMPS/MUMPS_seq@5/bundled/patches/mumps_int32.patch
> [MUMPS_seq] Version 5.4.1 with LBT

- M/minimap2/build_tarballs.jl
* Package name: minimap2
* Version: v2.24.0
> Wizard recipe: minimap2-v2.24.0

- C/Coin-OR/Ipopt/build_tarballs.jl
- C/Coin-OR/coin-or-common.jl
> Recompile IPOPT with MUMPS 5.4.1 and LBT

- G/GDAL/build_tarballs.jl
> [GDAL] build version 3.5.1 with PROJ 9.1

- T/TempestRemap/build_tarballs.jl
> Update TempestRemap for new NetCDF_jll

- K/kdb_c_api/build_tarballs.jl
* Package name: kdb_c_api
* Version: v2022.9.3
> Wizard recipe: kdb_c_api-v2022.9.3

- V/ViennaRNA/build_tarballs.jl
> [ViennaRNA] Fix compat with GSL

- H/HDF5/build_tarballs.jl
As it might make #5383 build on Windows
> [HDF5] Also include dll.a in the output on Windows

- R/rocBLAS/common.jl
- R/rocBLAS/rocBLAS@4.2.0/build_tarballs.jl
- R/rocBLAS/rocBLAS@4.5.2/build_tarballs.jl
> Add rocBLAS 4.2.0

- R/RE2/build_tarballs.jl
To support the long-shot in #5425.
> [RE2] Add a RE2 build

- M/MParT/build_tarballs.jl
- Bump MParT to version 1.0.0
- Bump Kokkos dependency to 3.6.1+0
- Revert build pathing to previous method
> Bump MParT Version

- C/CoolProp/build_tarballs.jl
Include M1 support (Issue #5468)
> [CoolProp] Add Apple M1 support

- T/TestU01/build_tarballs.jl
- T/TestU01/bundled/src/TestU01extractors/Makefile
- T/TestU01/bundled/src/TestU01extractors/extractors.c
This is an attempt to migrate https://github.com/andreasnoack/TestU01Builder to Yggrasil. It doesn't work yet.
> First version of TestU01 for Yggdrasil

- S/Singular/build_tarballs.jl
> [Singular] update to 4.3.1-2

- M/MParT/build_tarballs.jl
> Bump MParT to 1.1.0

- G/GAP/build_tarballs.jl
Also update some comments
No version change
> GAP: don't install config.h

- P/PROPACK/build_tarballs.jl
`LBT_jll` is not working on Windows platforms.
> Compile PROPACK with OpenBLAS on Windows platforms

- G/GR/build_tarballs.jl
> GR: bump version

- G/GAP_lib/build_tarballs.jl
Apologies for the churn, but I screwed up in the previous PR
*again* by only inspecting the logs, not the artifact. I will
be fully thorough this time, and also inspect a local build.
> Fix GAP_lib *again*

- R/rocSOLVER/common.jl
- R/rocSOLVER/rocSOLVER@4.2.0/build_tarballs.jl
- R/rocSOLVER/rocSOLVER@4.2.0/bundled/patches/include-stdint.patch
> Add rocSOLVER 4.2.0

- S/SDL2_image/build_tarballs.jl
> Update SDL2_image, and build for arm mac

- L/LibTeXPrintf/build_tarballs.jl
- L/LibTeXPrintf/bundled/patches/win-fix.diff
I want to make a wrapper library of [libtexprintf](https://github.com/bartp5/libtexprintf/) for the use of Latexify.jl in the terminal.
> New Recipe: LibTeXPrintf v1.11.0

- .ci/Manifest.toml
- .ci/register_package.jl
- H/HelloWorldC/build_tarballs.jl
- azure-pipelines.yml
Companion to https://github.com/JuliaPackaging/BinaryBuilder.jl/pull/1229
> [CI] Update to new version of BB which move logs into separate tarball

- H/HelloWorldC/build_tarballs.jl
https://dev.azure.com/JuliaPackaging/Yggdrasil/_build/results?buildId=22382&view=logs&j=7e53d7c5-a8fe-5b9b-117b-6e84c08f0fdc&t=2a8f86d4-98f3-5e03-72f2-944701545c00&l=163
```
[ Info: Tree hash of contents of HelloWorldC.v1.2.1.x86_64-linux-gnu.tar.gz: 8c8251b0c21615bce0701995eded26ac7697b5cc
```
Still same hash as https://github.com/JuliaPackaging/Yggdrasil/pull/5526#issuecomment-1250368066 :tada:
> [HelloWorldC] Trigger rebuild to verify it's reproducible

- L/LibUV/build_tarballs.jl
Including https://github.com/JuliaLang/libuv/pull/25
> Bump libuv.

- L/libsingular_julia/build_tarballs.jl
@tthsqe12 Can you please check whether everything is correct? Many thanks!
> [libsingular_julia] update to 0.26

- M/Matio/build_tarballs.jl
This is a C library for opening .mat files from Matlab without the dependencies.
> add Matio build

- D/DynamO/build_tarballs.jl
* Package name: DynamO
* Version: v1.7.6
> Wizard recipe: DynamO-v1.7.6

- P/Pango/build_tarballs.jl
It apparently has a fix I want, but I'm not sure how it interacts with the rest of the ecosystem. Does Cairo in particular need upgrading?
> [Pango] Upgrade Pango to 1.50.9

- X/xapian/build_tarballs.jl
Xapian is a C++ search engine library. 
https://xapian.org/
> New recipe: Xapian

- S/SDL2/build_tarballs.jl
In partial mitigation of https://github.com/JuliaPackaging/Yggdrasil/issues/1432#issuecomment-851065063
> [SDL2] Add a dependency on alsa_plugins

- .ci/Manifest.toml
Reverts JuliaPackaging/Yggdrasil#5575
Ref: https://github.com/JuliaPackaging/Yggdrasil/pull/4896#issuecomment-1257332314
> Revert "[CI] Update manifest"

- F/FMM2D/build_tarballs.jl
Hello,
This is the `build_tarballs.jl` that I could not get working through the wizard (as mentioned on slack).
Cheers,
Mikkel
> [FMM2D] Add new recipe

- C/CUTEst/build_tarballs.jl
[26/09/2022]
Mosè, you can merge the PR.
> [CUTEst] Add M1 platform

- O/OpenBLAS/OpenBLAS@0.3.21/build_tarballs.jl
- O/OpenBLAS/common.jl
Those libs are also needed at runtime
> [OpenBLAS] Make the flang runtime libs actual runtime deps

- O/OpenBLAS/OpenBLAS@0.3.21/bundled/patches/openblas-default-num-threads.patch
The patch didn't quite fix things on windows
> [OpenBLAS] Update patch

- O/OpenBLAS/OpenBLAS@0.3.21/build_tarballs.jl
- O/OpenBLAS/common.jl
This reverts commit 18426841019893d4060d09fe5d9ac23dbc3bd0d0.
@gbaraldi just FYI
> Revert "[OpenBLAS] Make the flang runtime libs actual runtime deps

- O/OpenBLAS/OpenBLAS@0.3.21/bundled/patches/openblas-default-num-threads.patch
I really wish I could just build this locally on windows, but it's such a pain.
> [OpenBLAS] Patch update part 2

- O/OpenCL_Headers/build_tarballs.jl
Appreciate if you can review and merge. After this is merged, I will come back to #5607
> Update OpenCL_Headers recipe

- O/OpenCL/build_tarballs.jl
This recipe supersedes the current OpenCL_Headers recipe by adding the header and the library products into a single JLL.
It would be awesome if someone with more experience on Windows could fix the build errors over there 🙏🏽
> Create recipe for OpenCL library

- M/MUMPS/MUMPS_seq@5/build_tarballs.jl
> Recompile MUMPS_seq with OpenBLAS32 for windows

- T/Tokei/build_tarballs.jl
No new releases since v12.1.2, so I expanded the patch number.
> [Tokei] rebuild for aarch64

- L/LAMMPS/build_tarballs.jl
> [LAMMPS] Bump version

- S/SCIP/build_tarballs.jl
Up bugfix release
Add possible concurrent mode
Versioning to follow Ipopt
> [SCIP] up bugfix release

- L/libopenjpegextra/build_tarballs.jl
- Improved and more flexifble decode and encode methods
> Version 0.0.2 of libopenjpegextra

- P/pprof/build_tarballs.jl
Alternative to https://github.com/JuliaPerf/PProf.jl/pull/71
> add Graphviz as dependency to PProf

- G/GstPluginsBase/build_tarballs.jl
This is an attempt to build plugins for GStreamer so that it can be more useful.
> Wizard recipe: GstPluginsBase-v1.20.3

- P/pciutils/build_tarballs.jl
We need headers for some downstream projects
> [pciutils] Install headers

- L/LibCURL/common.jl
Per https://github.com/JuliaLang/julia/pull/47165#issuecomment-1279459371.
> [LibCURL] disable `brotli` linkage

- G/GnuTLS/build_tarballs.jl
- G/GnuTLS/bundled/patches/03-undo-libtasn1-cisdigit.patch
Based on https://github.com/JuliaPackaging/Yggdrasil/pull/5670
> [GnuTLS] Upgrade to 3.7.8 (modified)

- F/flashrom/build_tarballs.jl
This allows flashing using the internal device
> [flashrom] Build with libpci

- P/P11Kit/build_tarballs.jl
* Package name: P11Kit
* Version: v0.24.1
> Wizard recipe: P11Kit-v0.24.1

- C/CUDA/CUDA_Runtime/build_tarballs.jl
- C/CUDA/CUDA_Runtime/platform_augmentation.jl
Simplifies things based on https://github.com/JuliaPackaging/Yggdrasil/pull/5695
> [CUDA] Use the driver version from CUDA_Driver_jll.

- C/cuQuantum/build_tarballs.jl
Also includes a version revert, until CUDA.jl is compatible.
> [CUDA] Update cuQuantum to use CUDA_Runtime_jll.

- C/cuQuantum/build_tarballs.jl
This should end the recent CUDA PR spree 😅
> [CUDA] Bump cuQuantum to v22.07.1.14.

- S/SQLite/build_tarballs.jl
Also update the url where the license is downloaded.
> SQLite: Update to version 3.39.4

- C/CUDA/CUDA_full@11.8/build_tarballs.jl
This was moved into a separate component as part of 11.8.
> [CUDA] Include profiler API component in 11.8.

- H/HiGHS/HiGHS/build_tarballs.jl
- H/HiGHS/bundled/patches/v1.3.0.patch
- H/HiGHS/highs_common.jl
<s>Please hold off merging just yet. I'm hopeful that HiGHS will make an official v1.3.0 release in the next few days, but I want check that things still compile, and this v101.200.200 is a good fallback if v1.3.0 isn't released.</s> Updated to v1.3.0
cc @ccoffrin
> [HiGHS] update to v1.3.0

- S/stb/build_tarballs.jl
This is another dependency of mlpack (see #5735, [this discussion](https://github.com/JuliaPackaging/Yggdrasil/pull/5735#discussion_r1004863704)).  It is just some header-only files, from https://github.com/nothings/stb/.
> Add stb header-only package

- G/GAP/build_tarballs.jl
- G/GAP/bundled/patches/configure.patch
- G/GAP/bundled/patches/gcc12.patch
- G/GAP/bundled/patches/julia_gc.patch
- G/GAP/bundled/patches/no-strip.patch
- G/GAP_lib/build_tarballs.jl
- Clean up GAP and GAP_lib build recipes
- [GAP] Update to 4.12.1
> [GAP] Update to 4.12.1

- C/Coin-OR/CoinUtils/build_tarballs.jl
- C/Coin-OR/coin-or-common.jl
x-ref: https://github.com/jump-dev/Clp.jl/issues/131#issuecomment-1291080752
> [CoinUtils] update to v2.11.6

- C/Coin-OR/Osi/build_tarballs.jl
- C/Coin-OR/coin-or-common.jl
> [Osi] update to v0.108.7

- C/Coin-OR/Clp/build_tarballs.jl
- C/Coin-OR/coin-or-common.jl
x-ref #5744
x-ref #5745 
x-ref https://github.com/jump-dev/Clp.jl/issues/131
> [Clp] update to v1.17.7

- C/Coin-OR/Cgl/build_tarballs.jl
- C/Coin-OR/coin-or-common.jl
x-ref https://github.com/JuliaPackaging/Yggdrasil/pull/5744
x-ref https://github.com/JuliaPackaging/Yggdrasil/pull/5745
x-ref https://github.com/JuliaPackaging/Yggdrasil/pull/5746
x-ref https://github.com/jump-dev/Clp.jl/issues/131
> [Cgl] update to v0.60.6

- C/Coin-OR/Cbc/build_tarballs.jl
- C/Coin-OR/coin-or-common.jl
x-ref https://github.com/JuliaPackaging/Yggdrasil/pull/5744
x-ref https://github.com/JuliaPackaging/Yggdrasil/pull/5745
x-ref https://github.com/JuliaPackaging/Yggdrasil/pull/5746
x-ref https://github.com/JuliaPackaging/Yggdrasil/pull/5747
> [Cbc] update to v2.10.8

- C/Coin-OR/SYMPHONY/build_tarballs.jl
- C/Coin-OR/coin-or-common.jl
x-ref https://github.com/JuliaPackaging/Yggdrasil/pull/5744
x-ref https://github.com/JuliaPackaging/Yggdrasil/pull/5745
x-ref https://github.com/JuliaPackaging/Yggdrasil/pull/5746
x-ref https://github.com/JuliaPackaging/Yggdrasil/pull/5747
> [SYMPHONY] update to v5.6.19

- 0_RootFS/common.jl
- 0_RootFS/gcc_common.jl
Ref: https://github.com/JuliaLang/julia/pull/45582#issuecomment-1295697412.
This is not yet complete, in particular, I need to upload also the logs files.
> [0_RootFS] Always disable TLS when building GCC for Windows

- L/libpolymake_julia/build_tarballs.jl
... to deal with Julia 1.9-DEV ABI changes
> Rebuild libpolymake_julia

- M/MParT/build_tarballs.jl
Hopefully just have to bump the version
> Bump version of MParT to v1.2.0

- O/oneAPI_Support/build_tarballs.jl
For https://github.com/JuliaGPU/oneAPI.jl/pull/231
> [oneAPI] Bump support library.

- M/msolve/build_tarballs.jl
Bug fixes in F4, F4SAT, rational reconstruction, and on the build system
> msolve-v0.4.5

- M/msgpack/build_tarballs.jl
This PR adds [msgpack](https://msgpack.org/index.html) which is needed to switch rocBLAS internal serialization format from yaml to msgpack.
> Add msgpack

- S/SDL2/build_tarballs.jl
- S/SDL2/bundled/patches/aarch64-darwin-remove-version-check.patch
https://github.com/JuliaPackaging/Yggdrasil/pull/5568
> Update SDL2 to 2.24

- S/SDL2_image/build_tarballs.jl
1. Use Github links
2. Install license
> Rerun SDL2_image

- R/rocBLAS/common.jl
- R/rocBLAS/rocBLAS@5.2.3/build_tarballs.jl
~~Should hopefully work again on musl as well...~~ Still gives LLVM OOM
However, if building for one target, it works.
> [rocBLAS] Add compat and switch from yaml to msgpack serialization

- M/MIOpen/MIOpen@5.2.3/build_tarballs.jl
And rebuild with the updated rocBLAS
> [MIOpen] Add compat

- M/MKL_Headers/build_tarballs.jl
I use the headers to generate the Julia interface in MKLSparse.jl.
> [MKL_Headers] Version 2022.2.1

- C/CBQN/build_tarballs.jl
- C/CBQN/bundled/patches/library-extension.patch
This recipe fails due to make file shenanigans.
cc @giordano
> [CBQN] add CBQN build_tarballs.jl

- M/mimalloc/build_tarballs.jl
Hopefully fixes the musl issues we are having. This probably deserves an upstream issue.
> Update mimalloc and use dynamic tls

- F/fts/build_tarballs.jl
Needed for https://github.com/JuliaPackaging/Yggdrasil/pull/5841
> fts: build for experimental platforms.

- L/LibUV/build_tarballs.jl
Including https://github.com/JuliaLang/libuv/pull/29
> Bump libuv 

- F/FastTransforms/build_tarballs.jl
- Add orthogonal polynomials on an annulus
- add single-precision methods for modified OPs
- Change hard exits in modified OPs to warnings
> [FastTransforms] v0.6.1

- F/FastTransforms/build_tarballs.jl
Store rho in annulus synthesis and analysis
> [FastTransforms] v0.6.2

- C/casacorecxx/build_tarballs.jl
Bump casacorecxx to version 0.2
> casacorecxx: v0.2

- C/casacorecxx/build_tarballs.jl
Bug fix release of casacorecxx.
> casacorecxx v0.2.0 -> v0.2.1

- I/ittapi/build_tarballs.jl
Following https://github.com/mchristianl/IntelITT.jl
> Add ittapi

- J/JuliaNVTXCallbacks/build_tarballs.jl
- J/JuliaNVTXCallbacks/bundled/patches/nvtx-linux-limits.patch
- J/JuliaNVTXCallbacks/bundled/patches/nvtx-windows-case.patch
I have no idea if this is the correct way to do this, but I'm trying to build this: https://github.com/simonbyrne/NVTX.jl/tree/main/deps
> [JuliaNVTXCallbacks] initial attempt

- N/NVTX/build_tarballs.jl
- N/NVTX/bundled/patches/nvtx-pragma-hidden.patch
Thanks again to @giordano: https://github.com/JuliaPackaging/Yggdrasil/pull/5903#issuecomment-1322760932
I also added `-ldl`, since that was noted in the docs: https://github.com/NVIDIA/NVTX/#c-and-c
> [NVTX] remove pragma hide

- H/HiGHS/HiGHSstatic/build_tarballs.jl
I got an email request to update HiGHSStatic_jll.jl to HiGHS v1.3.0.
I didn't update it at the time when I did: https://github.com/JuliaPackaging/Yggdrasil/pull/5713
> [HiGHSStatic] update to v1.3.0

- M/MQLib/build_tarballs.jl
- M/MQLib/bundled/patches/cxx-makefile.patch
- M/MQLib/bundled/patches/include-limits.patch
- M/MQLib/bundled/patches/math-defines.patch
> Wizard recipe: MQLib-v0.1.0

- S/stork/build_tarballs.jl
The wizard crashed ala https://github.com/JuliaPackaging/BinaryBuilder.jl/issues/1248, so I'm trying my luck in CI instead.
> Add stork recipe

- 0_RootFS/Rust/build_tarballs.jl
- 0_RootFS/common.jl
Companion PR to https://github.com/JuliaPackaging/BinaryBuilderBase.jl/pull/287
> [0_RootFS] Upgrade Rust to v1.65 and downgrade Rustup

- L/Libepoxy/build_tarballs.jl
GL+Gtk doesn't work for me on Wayland. I don't think this will fix it but figure it doesn't hurt either.
> [Libepoxy] upgrade to 1.5.10

- T/TMscore/build_tarballs.jl
> Wizard recipe: TMscore-v1.0.0

- P/PARMETIS/build_tarballs.jl
- P/PARMETIS/bundled/patches/0001-allow-overloading-METIS.patch
- P/PARMETIS/bundled/patches/0001-link_directories.patch
- P/PARMETIS/bundled/patches/0002-overload-binaryname.patch
- P/PARMETIS/bundled/patches/0003-mpi-nobuild-metis.patch
Matching PR of METIS_jll. To allow for doing similar to SuperLU_DIST_jll.
> [PARMETIS] Add Int32/Int64 and Real32/Real64 versions of PARMETIS

- S/SuperLU_DIST/build_tarballs.jl
> [SuperLU_DIST] Correct ParMETIS dep

- L/libadwaita/build_tarballs.jl
Most of the recipe is copied from GTK4's.
> Add libadwaita recipe

- K/Kissat/build_tarballs.jl
> [Kissat] Update to v3.0.0

- M/msolve/build_tarballs.jl
> msolve v0.4.6

- H/HiGHS/HiGHS/build_tarballs.jl
- H/HiGHS/HiGHSstatic/build_tarballs.jl
- H/HiGHS/highs_common.jl
> [HiGHS] update to v1.4.1

- L/Liburing/build_tarballs.jl
`liburing` - Linux IO notification interface.
https://kernel.dk/io_uring.pdf
https://github.com/axboe/liburing
Note: not to be merged until after https://github.com/axboe/liburing/pull/743
> liburing: build_tarballs.jl

- C/CompilerSupportLibraries/CompilerSupportLibraries@v1.0/build_tarballs.jl
- C/CompilerSupportLibraries/common.jl
@vchuravy anything else you need?
> [CompilerSupportLibraries] Use import library for `libssp` on Windows

- F/FLINT/build_tarballs.jl
> [FLINT] 2.9.0 + something more

- C/Chipmunk/build_tarballs.jl
- C/Chipmunk/bundled/patches/remove-fast-math.patch
https://github.com/slembcke/Chipmunk2D
> Add Chipmunk 2D physics library

- A/AzStorage/build_tarballs.jl
This corresponds to the changes in https://github.com/ChevronETC/AzStorage.jl/pull/48
> AzStorage_jll 0.5.0

- X/XGBoost/build_tarballs.jl
Patch notes: https://github.com/dmlc/xgboost/releases/tag/v1.7.2
> [XGBoost] Update to v1.7.2

- S/SDL12_compat/build_tarballs.jl
https://github.com/libsdl-org/sdl12-compat/
> New recipe: sdl12-compat

- C/CoolProp/build_tarballs.jl
@barche is this alright? i think we have no option in julia but to skip 6.4.2, but thankfully there is now 6.4.3
> Update to CoolProp 6.4.3

- X/XML2/build_tarballs.jl
> Dummy edit to XML2_jll to retrigger build and registration

- L/libsharp2/build_tarballs.jl
Ref https://github.com/ziotom78/Healpix.jl/issues/101.  CC: @ziotom78
> [libsharp2] Enable OpenMP on macOS

- C/Cairo/build_tarballs.jl
This is not a great solution, but it's a workaround for the versions of Julia which can't find libssp on Windows (as of this writing only Julia v1.8.4).
> [Cairo] Copy `libssp` to libdir on Windows

- C/Cairo/build_tarballs.jl
It seems to have some unspecified problems:
<https://discourse.julialang.org/t/glmakie-and-plots-fail-to-precompile-under-julia-1-8-4/92087/34>.
> [Cairo] Do not install libssp on Windows

- S/SuiteSparse/SuiteSparse/build_tarballs.jl
- S/SuiteSparse/common.jl
Ref https://github.com/JuliaLang/julia/issues/47638#issuecomment-1360396526.  CC @Wimmerer @staticfloat
> [SuiteSparse] Rebuild against libblastrampoline v5.2.0

- P/Perple_X/build_tarballs.jl
> [Perple_X]: update to version 7.0.0

- T/TempestRemap/build_tarballs.jl
- T/TempestRemap/bundled/patches/libadd.patch
- T/TempestRemap/bundled/patches/triangle.patch
NetCDF now works on more platforms, so we can try all of them
> [TempestRemap] Build more platforms

- A/AzStorage/build_tarballs.jl
In addition, this packages the AzStorage header file in the tarballs.
> [AzStorage] update to 0.6.0

- G/GDAL/build_tarballs.jl
GDAL release notes: https://github.com/OSGeo/gdal/blob/v3.6.2/NEWS.md
> [GDAL] build version 3.6.2

- X/XGBoost/build_tarballs.jl
Release notes: https://github.com/dmlc/xgboost/releases/tag/v1.7.3
> [XGBoost] Update to v1.7.3

- .github/workflows/update_manifest.yml
> [CI] Update workflows used in the update manifest action

- .buildkite/generator.jl
- .buildkite/pipeline.yml.signature
- P/p7zip/build_tarballs.jl
Ref: https://github.com/JuliaLang/julia/pull/48176#issuecomment-1374867788.
> [p7zip] Update upstream URL

- M/micromamba/build_tarballs.jl
Release notes: https://github.com/mamba-org/mamba/releases/tag/2023.01.16
In case you're interested @cjdoris
> [micromamba] Update to v1.2.0

- M/msolve/build_tarballs.jl
Bug fixes, optimized parallelization.
> msolve v0.4.8

- P/Perple_X/build_tarballs.jl
> [Perple_X] bump to version 7.0.1

- M/MAGMA/build_tarballs.jl
New version. This builder seems to have been updated in the recent past but there's no jll?
> [MAGMA] Version Bump and Re-init?

- M/MAGMA/build_tarballs.jl
I want this to work on 1.8 as well.
> [MAGMA] fix compat for LBT

- H/hiredis/build_tarballs.jl
- H/hiredis/bundled/patches/link-hiredis-ssl.patch
* Package name: hiredis
* Version: v1.1.0
> Wizard recipe: hiredis-v1.1.0

- R/rr/build_tarballs.jl
Fixes https://github.com/JuliaLang/BugReporting.jl/issues/108
cc @pepijndevos
> rr: backport (unreleased) support for Zen 4

- A/AzStorage/build_tarballs.jl
improvements to how we handle storage service time-outs.
> [AzStorage] new version 0.7.0

- R/Rscape/build_tarballs.jl
- R/Rscape/bundled/patches/allow-env-var-override-of-dirs.patch
Will try to upstream the patch to avoid having to adjust it on each version bump.
> [Rscape] update to version 2.0.0.p

- H/HiGHS/HiGHS/build_tarballs.jl
- H/HiGHS/HiGHSstatic/build_tarballs.jl
- H/HiGHS/highs_common.jl
> [HiGHS] build HiGHS v1.4.2

- P/Perple_X/build_tarballs.jl
> [Perple_X] new version

- I/ImageMagick/build_tarballs.jl
adding JPEG2000 and Ghostscript support
Should address JuliaIO/ImageMagick.jl#158, I tested locally that this doesn't break ImageMagick.jl as in JuliaIO/ImageMagick.jl#206.
cc @jochalek @timholy
> [ImageMagick] rebuild v6.9.10

- X/XyceWrapper/build_tarballs.jl
xref: https://github.com/JuliaPackaging/Yggdrasil/pull/5939
> [xycewrapper] bump for xyce 7.6

- L/libpolymake_julia/build_tarballs.jl
> [libpolymake_julia] bump to version 0.9 (for polymake 4.9)

- C/CUDA/CUDA_Runtime/build_tarballs.jl
- C/CUDA/CUDA_Runtime/platform_augmentation.jl
Fixes https://github.com/JuliaLang/julia/issues/48518
> CUDA: Fix platform augmentation.

- A/AzStorage/build_tarballs.jl
Version of AzStorage that is more aggressive at token refreshing within its retry loops.
> [AzStorage] update to 0.8.0

- G/Ghostscript/build_tarballs.jl
I think this might help with the ImageMagick linking issues on mingw,
that's just a guess though. Shipping these is probably a good idea
anyway.
> [Ghostscript] add gsc and gsx executables

- P/pandoc_crossref/build_tarballs.jl
Similar changes to #6218 and #6220
> [pandoc_crossref] Add macos aarch64 platform support based on x86_64

- P/pandoc_crossref/build_tarballs.jl
> update pandoc_crossref for pandoc 3.0

- A/AzStorage/build_tarballs.jl
see: https://github.com/ChevronETC/AzStorage.jl/pull/57
> [AzStorage] bump 0.8.1

- N/ngspice/build_tarballs.jl
xref: https://github.com/JuliaPackaging/Yggdrasil/pull/6243#discussion_r1103645644
> [ngspice] fix patch application

- M/micromamba/build_tarballs.jl
[v1.3.0 release notes](https://github.com/mamba-org/mamba/releases/tag/2023.02.03)
[v1.3.1 release notes](https://github.com/mamba-org/mamba/releases/tag/2023.02.09)
> [micromamba] Update to v1.3.1

- O/OpenBLAS/OpenBLAS@0.3.21/build_tarballs.jl
- O/OpenBLAS/common.jl
I'm not sure whether to use dynamic arch for powerpc through a config option to `openblas_script`, happy to do it if that's preferrable.
> [OpenBLAS] Build for PowerPC with dynamic arch

- D/ducc0/build_tarballs.jl
> update ducc0 to version 0.29

- X/XGBoost/build_tarballs.jl
Release notes: https://github.com/dmlc/xgboost/releases/tag/v1.7.4
> [XGBoost] Update to v1.7.4

- L/LLVMExtra/build_tarballs.jl
> rebuild libLLVMExtra for LLVM 15

- D/DuckDB/build_tarballs.jl
currently using the cli we can change timezone, it's good if we can also do in julia
> [DuckDB] julia client support set timezone

- F/FORM/build_tarballs.jl
- Package name: FORM
- Version: v4.3.0
Hi, @giordano. Could you review it and give some advice?
> Add FORM-v4.3.0

- G/Git/build_tarballs.jl
Confirmed to work for me on macOS 12.6.
Fix https://github.com/JuliaVersionControl/Git.jl/issues/48.
> [Git] Always canonicalize symlinks

- L/libtasn1/build_tarballs.jl
* Package name: libtasn1
* Version: v4.19.0
> Wizard recipe: libtasn1-v4.19.0

- D/DecompUtil/build_tarballs.jl
Created a small wrapper for `DecompUtil`
Currently I am only exporting one function, but will likely add more later.
> Julia Wrapper for DecompUtil

- W/Woff2/build_tarballs.jl
* Package name: Woff2
* Version: v1.0.2
> Wizard recipe: Woff2-v1.0.2

- X/Xerces/build_tarballs.jl
At the same time build for missing platforms (e.g. aarch64-apple-darwin).
> [Xerces] Upgrade to version 3.2.4

- F/FAMSA/build_tarballs.jl
- F/FAMSA/bundled/patches/fix-makefile-avx2-platform-no-march.patch
FAMSA is a program for large-scale multiple sequence alignments
> [FAMSA] new build FAMSA v2.2.2

- M/MbedTLS/MbedTLS@2.28.2/build_tarballs.jl
- M/MbedTLS/MbedTLS@2.28.2/bundled/patches/conditional/0001-Remove-flags-not-supported-by-ranlib.patch
- M/MbedTLS/common.jl
See https://github.com/JuliaLang/julia/issues/48805
https://github.com/Mbed-TLS/mbedtls/releases/tag/v2.28.2
https://github.com/Mbed-TLS/mbedtls/releases/tag/v2.28.1
> Add MbedTLS 2.28.2, compat Julia 1.9

- B/Baobzi/build_tarballs.jl
Adds build of https://github.com/flatironinstitute/baobzi shared lib.
> [Baobzi] Add Baobzi_jll package (v0.9.6)

- P/protoc/build_tarballs.jl
- Required by https://github.com/JuliaRegistries/General/pull/76452#issuecomment-1445352585
> [protoc] Add protobuf lite

- L/LLVM/libLLVM@15/build_tarballs.jl
> Tag a new libLLVM

- L/LLVM/Clang@15/build_tarballs.jl
- L/LLVM/LLD@15/build_tarballs.jl
- L/LLVM/LLVM@15/build_tarballs.jl
- L/LLVM/MLIR@15/build_tarballs.jl
> Build dependent LLVM libs

- M/MPICH/build_tarballs.jl
> [MPICH] Do not install man files which cause problems on case insensitive filesystems

- Q/Qt65Compat/build_tarballs.jl
Needed for GUIs that want to include legacy Qt5 elements in Qt6.
> [Qt65Compat] New package (version 6.4.2)

- J/jlqml/build_tarballs.jl
> [jlqml] Version v0.5.2

- M/MAGEMin/build_tarballs.jl
- Q/Qt65Compat/build_tarballs.jl
- Added metapelite database with MnO (White et al., 2014), use the flag --db=ig or --db=mp to change database from igneous to metapelite
- Improved GUI (PlotPseudosection.mlapp): added option to change database; added panel to plot isocontour (mode and end-member fractions); added option to save pseudosection with isocontour in vector format (eps)
- Updated python scripts to translate database from TC to MAGEMin (check ./python/SS_Analytical_multi_DB.ipynb)
- Documentation udpate
> MAGEMin v1.3.0

- C/CompilerSupportLibraries/CompilerSupportLibraries@v1.0/build_tarballs.jl
- C/CompilerSupportLibraries/common.jl
Reverts JuliaPackaging/Yggdrasil#6341
> Revert "Add libmsvcr120 to the CSL to remove openlibm from julia"

- M/MPICH/build_tarballs.jl
Also change `MPIPreferences` to `RuntimeDependency`.
> MPICH: New version 4.1.1

- A/Aravis/build_tarballs.jl
Add recipe for [Aravis](https://github.com/AravisProject/aravis) library.
> Add Aravis recipe

- L/LLVM/Clang@15/build_tarballs.jl
- L/LLVM/LLD@15/build_tarballs.jl
- L/LLVM/LLVM@15/build_tarballs.jl
- L/LLVM/MLIR@15/build_tarballs.jl
> Rebuild dependent libs llvm

- N/NVTX/build_tarballs.jl
- N/NVTX/bundled/nvtx.c
I'm not sure if this is the right way to do this. May need to add a build time dependency on CUDA?
cf https://github.com/JuliaGPU/NVTX.jl/issues/27
cc @maleadt
> [NVTX] Build CUDA stream naming functions

- I/Imath/build_tarballs.jl
Updating Imath to https://github.com/AcademySoftwareFoundation/Imath/releases/tag/v3.1.7
> Bump Imath: v3.1.2 -> v3.1.7 

- L/LaMEM/build_tarballs.jl
- platforms/mpi.jl
> [LaMEM] version 1.2.3

- M/MPItrampoline/build_tarballs.jl
See https://github.com/JuliaPackaging/Yggdrasil/pull/5028#issuecomment-1166388492 for a discussion on this idea.
> MPItrampoline: Use CMAKE_INSTALL_RPATH='$ORIGIN'

- C/CUDA/CUDA_Driver/init.jl
Potential fix to https://github.com/JuliaGPU/CUDA.jl/issues/1798
This will require changes to CUDA.jl as well.
cc: @maleadt
> [CUDA_Driver] Initialize globals to nothing

- L/librdkafka/build_tarballs.jl
> [librdkafka] Version 2.0.2

- L/libsingular_julia/build_tarballs.jl
libsingular_julia (0.30.0) for Singular_jll (403.201.000)
> new version of libsingular_julia (0.30.0) for Singular_jll (403.201.000)

- M/MPItrampoline/build_tarballs.jl
> [MPITrampoline] Use RPATH hack only on x86_64 linux

- P/PAPI/build_tarballs.jl
cc: @maleadt
I skipped `libcuda.so` since I am unsure if the SO version will actually match there.
> so version cuda libraries in PAPI

- P/PAPI/build_tarballs.jl
- P/PAPI/bundled/patches/0001-CUDA-Add-environment-overrides.patch
> [PAPI] Use environment variables for override

- L/LLVM/LLVM_full@15/build_tarballs.jl
- L/LLVM/LLVM_full_assert@15/build_tarballs.jl
- L/LLVM/common.jl
Note: Don't merge without checking both the CMAKE variables for Enzyme and also if the clang symlinks are in `tools`
> Another LLVM15 bump

- A/adwaita_icon_theme/build_tarballs.jl
Version number now tracks GNOME, hence the huge jump
> [adwaita_icon_theme] update to version 43

- A/algoimWrapper/build_tarballs.jl
- A/algoimWrapper/bundled/LICENSE.md
This package wraps the algoim library, such that it can be called in Julia through CxxWrap.jl.
> Adds algoimWrapper recipe

- M/micromamba/build_tarballs.jl
[v1.4.0 release notes](https://github.com/mamba-org/mamba/releases/tag/2023.03.22)
> [micromamba] Update to v1.4.0

- O/oneAPI_Support/build_tarballs.jl
> Bump oneAPI Support library.

- C/CUDA/CUDA_Driver/build_tarballs.jl
- C/CUDA/CUDA_Driver/init.jl
Another attempt at #6398.
See https://github.com/JuliaGPU/CUDA.jl/pull/1809#issuecomment-1482504025
Needs to get reviewed by @maleadt
> [CUDA_Driver] define libcuda as nothing

- C/CUDA/CUDA_Runtime/build_tarballs.jl
- C/CUDA/CUDA_Runtime/platform_augmentation.jl
Update CUDA_Runtime platform augmentation for #6449.
cc @maleadt
> [CUDA_Runtime] update platform augmentation

- P/Perple_X/build_tarballs.jl
> [Perple_X] v7.0.9

- M/micromamba/build_tarballs.jl
[Release notes](https://github.com/mamba-org/mamba/releases/tag/2023.03.28)
> [micromamba] Update to v1.4.1

- C/CLN/build_tarballs.jl
Hello, @giordano.
Could you review it?
Thank you~
> New Recipe: CLN v1.3.6

- M/MAGEMin/build_tarballs.jl
- fix issue  that was making MAGEMin super slow on Apple systems
> MAGEMin 1.3.1

- A/avr_binutils/build_tarballs.jl
@staticfloat I more or less copied the recipe from Binutils_jll, so should be fairly simple to merge in the future.
> [avr_binutils] Add recipe

- G/Geant4_julia/build_tarballs.jl
Added new package with CxxWrap wrappers for Geant4
> [Geant4_julia]: Added new package with CxxWrap wrappers for Geant4 

- D/DynarePreprocessor/build_tarballs.jl
update DynarePreprocessor_jll to 6.3.0
> Dynare julia

- Q/Qt5Base/build_tarballs.jl
> [Qt5Base] Set openssl compat to 1.1.10

- 0_RootFS/Rust/build_tarballs.jl
> [Rust] set openssl compat to 1.1.10

- A/Aria2/build_tarballs.jl
> [aria2] Set MbedTLS build dep to 2.28.0, set openssl compat to 1.1.10

- C/CUDA/CUDA_Runtime/platform_augmentation.jl
Fixes https://github.com/JuliaGPU/CUDA.jl/issues/1831
> CUDA: Protect against invalidly-typed preferences.

- L/LAMMPS/build_tarballs.jl
This reverts commit 1cd5e9c605176eadd25bc121525afb7f94742ac0.
> Revert "Build the most recent LAMMPS patch (#6522)"

- C/cfastcdr/build_tarballs.jl
The recipe is ready, but the library it builds is still WIP at this point.
> [WIP] New recipe: cfastcdr v1.0.0

- G/GiNaC/build_tarballs.jl
* Package name: GiNaC
* Version: v1.8.6
> Wizard recipe: GiNaC-v1.8.6

- G/GlibNetworking/build_tarballs.jl
Here's my attempt to get GlibNetworking bundled - at least the OpenSSL based bit. I am able to get libsoup to build based off of this locally, at least, so I could open a PR for that too. Supersedes #5689.
> New recipe: GlibNetworking

- J/JlrsLedger/build_tarballs.jl
Build for all platforms, including 32-bits Windows. Remove RUSTFLAGS.
> [JlrsLedger] Update to v0.0.3

- F/FireFly/build_tarballs.jl
Sorry for missing `argument_platform_block` in `build_tarballs` (#6478 and JuliaRegistries/General#81510).
> [FireFly] fix missing augment

- F/FireFly/build_tarballs.jl
A serious typo due to my carelessness.
I'm sorry for that.
> [FireFly] fix typo

- C/CUTENSOR/build_tarballs.jl
... in order to include https://github.com/JuliaPackaging/Yggdrasil/pull/5722
> CUDA: Bump CUTENSOR JLL.

- S/Singular/build_tarballs.jl
update to 4.3.2-0 + depth patches
> [Singular] update to 4.3.2-0 + depth patches

- G/gawk/build_tarballs.jl
Windows is currently disabled because of an issue in our mingw setup.
> [gawk] Add v5.2.1

- M/MParT/build_tarballs.jl
Bump the version to match with the current version on github.
> Bump MParT_jll to 2.0.2

- G/GTK4/build_tarballs.jl
requires a more recent version of mingw for windows -- method copied from Qt6Base recipe
> update GTK4 to 4.8.3

- S/Soup3/build_tarballs.jl
Here's my attempt to get libsoup3 bundled, assuming I didn't mess anything up locally. I based this off some of the scripts in https://github.com/JuliaPackaging/Yggdrasil/pull/5689.
> New recipe: Soup3

- G/GR/build_tarballs.jl
add 'grplot' executable product
> [GR] add grplot

- 0_RootFS/Rootfs/build_tarballs.jl
> [Rootfs] update meson to v1.0.1

- P/polyhedral/build_tarballs.jl
First version of the compilation of the `polyhedral` code in C++
> Polyhedral

- F/fortune/build_tarballs.jl
- F/fortune/bundled/patches/build.patch
This is mostly me playing with the wizard.
I think I can delete that patch, no?
> New Recipe: fortune v1.0.0

- S/SZ/build_tarballs.jl
The linker creates an unusable library.
> SZ: Disable HDF5 plugin on Windows

- K/KMC/build_tarballs.jl
- K/KMC/bundled/patches/fix-missing-includes.patch
Only works on x86_64 so far.
Supersedes #5582 
Fixes #4813
> [KMC] New build for KMC v3.2.2

- C/CUDA/CUDA_Runtime@0.2/build_tarballs.jl
... to include a newer version of the platform augmentation, which has some bug fixes.
> CUDA: Bump CUDA_Runtime_jll@0.2

- P/polyhedral/build_tarballs.jl
It is fairly massive change in polyhedral code.
But the script should not change significantly.
> Upgrade to the polyhedral after correction

- T/TracyProfiler/build_tarballs.jl
- T/TracyProfiler/bundled/patches/TracyProfiler-filter-user-text.patch
> add patch for filtering user text on tracy

- L/libcxxwrap_julia/build_tarballs.jl
Fixes by @benlorenz for latest Julia master.
> [libcxxwrap-julia] Update to version v0.9.7

- A/ATKmm/ATKmm@2.36.2/build_tarballs.jl
This is the latest version with libsigc++-3.0, for use with GTK4.
> [ATKmm] Bump to v2.36.2

- C/Cairomm/Cairomm@1.14.4/build_tarballs.jl
- C/Cairomm/Cairomm@1.14.4/bundled/patches/disable-quartz-aarch64-apple-darwin.patch
This is the latest version with libsigc++-2.0, for use with GTK3.
> [Cairomm] Add v1.14.4

- P/Pangomm/Pangomm@2.46.3/build_tarballs.jl
This is the latest version with libsigc++-2.0, for use with GTK3.
> [Pangomm] Add v2.46.3

- G/GTKmm3/build_tarballs.jl
This is the latest version supporting GTK3
> [GTKmm3] Add v3.24.7

- P/Pangomm/Pangomm@2.49.1/build_tarballs.jl
This is the latest version with libsigc++-3.0, for use with GTK4.
> [Pangomm] Bump to v2.49.1

- L/LightGBM/build_tarballs.jl
- L/LightGBM/bundled/patches/windows/Ws2_32-iphlpapi.patch
* Package name: LightGBM
* Version: v3.3.5
> Wizard recipe: LightGBM-v3.3.5

- L/libcxxwrap_julia/build_tarballs.jl
updated libjulia_jll for changes on julia master: #6724 
cc: @barche @fingolfin
> [libcxxwrap_julia] rebuild for updated libjulia_jll (for julia 1.9+1.10)

- C/Coin-OR/Ipopt/build_tarballs.jl
- C/Coin-OR/coin-or-common.jl
> [Ipopt] Version 3.14.12

- M/micromamba/build_tarballs.jl
[Release Notes](https://github.com/mamba-org/mamba/releases/tag/2023.05.15)
> [micromamba] Update to v1.4.3

- O/OpenSpiel/build_tarballs.jl
It seems we only need to bump a patch version here to update `libjulia` (which was updated in https://github.com/JuliaPackaging/Yggdrasil/pull/6724)?
cc @jeremiahpslewis , @maleadt , @fingolfin
> [OpenSpiel] Update dependency and Bump version

- A/algoimWrapper/build_tarballs.jl
x-ref ericneiva/Algoim.jl#2
x-ref #6759 
x-ref #6760 
Thanks @maleadt and @giordano
> [algoimWrapper] rebuild with no changes for latest libcxxwrap

- A/ArcadeLearningEnvironment/build_tarballs.jl
'fake' version bump to build package for all platforms
> [Arcade Learning Environment] Build for all platforms

- X/Xorg_compositeproto/build_tarballs.jl
- X/Xorg_damageproto/build_tarballs.jl
- X/Xorg_dri2proto/build_tarballs.jl
- X/Xorg_dri3proto/build_tarballs.jl
- X/Xorg_fixesproto/build_tarballs.jl
- X/Xorg_randrproto/build_tarballs.jl
- X/Xorg_recordproto/build_tarballs.jl
- X/Xorg_scrnsaverproto/build_tarballs.jl
- X/Xorg_xf86vidmodeproto/build_tarballs.jl
- X/Xorg_xineramaproto/build_tarballs.jl
> [Xorg_*proto] Rebuild packages to automatically pick up license files

- K/Keyutils/build_tarballs.jl
- L/libmodplug/build_tarballs.jl
- L/lm_Sensors/build_tarballs.jl
- P/PATHlib/build_tarballs.jl
> Rebuild more packages to automatically pick up license files

- L/libmodplug/build_tarballs.jl
- T/TVM/build_tarballs.jl
> [TVM] [libmodplug] Trigger regeneration of JLLs

- E/Exodus/build_tarballs.jl
- G/GDAL/build_tarballs.jl
- G/gmsh/build_tarballs.jl
- I/ImarisWriter/build_tarballs.jl
- M/Matio/build_tarballs.jl
- M/mdoodz/build_tarballs.jl
- R/RichDEM/build_tarballs.jl
- S/SZ3/build_tarballs.jl
- T/TempestModel/build_tarballs.jl
This sould take care of the easy cases of #6707.
> [HDF5] Compat to ~1.12, Cherry-pick #6707, [skip build]

- M/mosquitto_client/build_tarballs.jl
* Package name: mosquitto_client
* Version: v2.0.15
> Wizard recipe: mosquitto_client-v2.0.15

- R/rustfft/build_tarballs.jl
Sorry about the large number of rebuilds for this library 😅 I hope this one gets rid of the final hurdle that's preventing me from releasing RustFFT.jl
> [rustfft] version 0.1.1

- M/MiniZinc/build_tarballs.jl
- M/MiniZinc/bundled/patches/fixes.patch
This PR is going to be a WIP until I figure out the reasons why I punted on Windows support previously.
> [MiniZinc] add support for Windows

- S/SBML/build_tarballs.jl
> [SBML] Update to v5.20.1

- S/Singular/build_tarballs.jl
Turns out this update was ABI breaking...
> [Singular] re-release update with increased minor version

- L/libsingular_julia/build_tarballs.jl
> [libsingular_julia] rebuild against latest Singular_jll

- H/HOHQMesh/build_tarballs.jl
Adds new feature of conforming meshes with interior boundaries
> update to HOHQMesh version 1.4.0

- G/GRCore/build_tarballs.jl
Draft PR to support proposed changes in GR
> [GR] Add GRCore package

- G/GRQt5/build_tarballs.jl
Draft PR to support proposed changes in GR
> [GR] Add GRQt5 package

- F/Foldseek/build_tarballs.jl
- F/Foldseek/bundled/patches/corrosion-remove-rustup-check.patch
@diegozea 
Messed up the previous PR branch, starting anew here
Had to disable armv6l, armv7l, powerpc64le: 'No SIMD support for this architecture' (maybe due to missing rust simd support on these architectures?)
> [Foldseek] update to v6, take 2

- S/Singular/build_tarballs.jl
... and a few other minor tweaks. There are no ABI breaking changes in this, so we can just update the patch level.
CC @hannes14
> [Singular] overflow check for hilb

- N/nats_c/build_tarballs.jl
- N/nats_c/bundled/patches/freebsd_include.diff
https://nats.io/ and https://github.com/nats-io/nats.c 
~Windows can't find OpenSSL apparently.~ ✅
> New Recipe: NATS C client

- H/hidapi/build_tarballs.jl
No build system change in 0.14.0
> update hidapi to version 0.14.0

- S/Singular/build_tarballs.jl
[Singular] update to 4.3.2-2 + sheafCohBGGregul
> [Singular] update to 4.3.2-2 + sheafCohBGGregul

- M/mlpack/build_tarballs.jl
There was a new release, so, hopefully everything will rebuild cleanly here.  No significant changes.
> Update mlpack to latest stable version (4.2.0)

- P/polyhedral/build_tarballs.jl
Nothing really special. The Julia will need to be upgraded as well.
> 3rd upgrade to the polyhedral C++ exportation

- F/FastTree/build_tarballs.jl
Fix #6895
Caveat: I have no idea what I'm doing.
> Adding double-precision versions to FastTree

- X/XGBoost/build_tarballs.jl
as suggested by @giordano in Slack
> libomp not properly installed with xgboost

- G/GAP/build_tarballs.jl
- G/GAP_pkg/GAP_pkg_juliainterface/build_tarballs.jl
> [GAP] [GAP_pkg_juliainterface] rebuilds for updated libjulia

- D/Diamond/build_tarballs.jl
https://github.com/bbuchfink/diamond/releases/tag/v2.1.8
> [Diamond] Update to v2.1.8

- P/PROJ/build_tarballs.jl
> [PROJ] update to 9.2.1, build with libtiff 4.5

- L/libcxxwrap_julia/build_tarballs.jl
> [libcxxwrap] rebuild for libjulia 1.10 changes

- N/Ncurses/build_tarballs.jl
Once this is through I'll update readline
> [Ncurses] Upgrade to v6.4

- L/libcxxwrap_julia/build_tarballs.jl
CC @barche @benlorenz 
(Note: I am slightly wary about adding a new Julia variant but not updating the JLL version... but in the end this doesn't seem worse than the "rebuilding" we are doing otherwise? Or is it???)
> [libcxxwrap] update for libjulia 1.11

- A/argtable/argtable@2.13/build_tarballs.jl
- A/argtable/argtable@3.2.2/build_tarballs.jl
- A/argtable/common.jl
[libargtable2](https://sourceforge.net/projects/argtable/) v2.13 and [libargtable3](https://github.com/argtable/argtable3) v3.2.2.
> [argtable] add recipe

- F/FreeType2/build_tarballs.jl
The latest HarfBuzz releases requires a more recent version of FreeType2 than 2.10.4, which otherwise seems to result in this issue: https://github.com/JuliaIO/FFMPEG.jl/issues/53
> Update FreeType2 to 2.13.1
