JuliaPackaging/Yggdrasil

G/GLEW/build_tarballs.jl

The existing artifacts have `libglew32.a` in bin and an empty lib directory (except for pkgconfig).
This commit overrides the auto-detection script so that MinGW is correctly configured as the target system, which means that `libglew32.a` and `libglew32.dll.a` are installed into `lib` as expected.

GLEW: Use correct installation convention for MinGW targets

---

S/SDPA/build_tarballs.jl

x-ref https://github.com/jump-dev/SDPA.jl/issues/56
x-ref https://github.com/jump-dev/SDPA.jl/pull/57
OpenSpiel is similar:
x-ref https://github.com/JuliaPackaging/Yggdrasil/pull/6759
If we're going to rebuild libcxxwrap, https://github.com/JuliaPackaging/Yggdrasil/pull/6726, does it make sense to also rebuild all dependent jll at the same time (or after, once version registered)? I can see this being a re-occuring pain point.

[SDPA] rebuild with no changes for latest libcxxwrap

---

C/Cares/build_tarballs.jl

This is a security and bugfix release.
Security fixes:
- CVE-2023-32067. High. 0-byte UDP payload causes Denial of Service
- CVE-2023-31147. Moderate. Insufficient randomness in generation of DNS query IDs
- CVE-2023-31130. Moderate. Buffer Underwrite in ares_inet_net_pton()
- CVE-2023-31124. Low. AutoTools does not set CARES_RANDOM_FILE during cross compilation
https://github.com/c-ares/c-ares/releases/tag/cares-1_19_1

[Cares] Update to v1.19.1 (security update)

---

L/LibTeXPrintf/build_tarballs.jl

Upstream merged two new API functions `texstring` and `texerrors_str` that should make it easier to wrap from Julia.  Also should fix the random build failures we were seeing previously.
cc @Suavesito-Olimpiada

update LibTexPrintf to v1.18

---

N/NetCDF/build_tarballs.jl

Set compat bounds for HDF5_jll
NetCDF_jll probably should be ~1.12.2 unless established otherwise
Otherwise, this hould finish out the diff for #6707 except that I skip build.

[NetCDF] Set compat bounds for HDF5_jll up to patch, ~1.12.2 [skip build]

---

D/Deno/build_tarballs.jl

This is a regular update to 1.33.4, and also I am adding the ARM linux binary.
Deno currently builds from source on ARM, but they don't publish a binary in their [releases](https://github.com/denoland/deno/releases) ([because they only use GH Actions](https://github.com/denoland/deno/issues/1846)). There is however an ARM release from the community: https://github.com/LukeChannings/deno-arm64/releases
So our options for Deno_jll are building from source, or using the community release. It [sounds like](https://github.com/JuliaPackaging/BinaryBuilder.jl/issues/1166#issuecomment-1030819653) building from source on Linux ARM is not supported with BinaryBuilder, so let's go with the community release!

Deno: update to 1.33.4 and add aarch64-linux-gnu

---

N/NetCDF/build_tarballs.jl

- update version_offset
- correct tarball checksum
- correct Windows build instruction
- remove outdated Apple work-around
- build on more platforms
- add new dependencies bzip2 (necessary) and zstd (because we can)

NetCDF: Build against HDF5 1.14

---

T/TempestRemap/build_tarballs.jl

HDF5 is linked to directly, so should be added as a dependency.
Recent HDF5 update broke TempestRemap:
```
julia> using TempestRemap_jll
ERROR: InitError: could not load library "/Users/simon/.julia/artifacts/a3391a5a73004bf491bf9f164cdc8fa1eba7a81e/lib/libTempestRemap.0.dylib"
dlopen(/Users/simon/.julia/artifacts/a3391a5a73004bf491bf9f164cdc8fa1eba7a81e/lib/libTempestRemap.0.dylib, 0x0001): Library not loaded: @rpath/libhdf5.200.dylib
Referenced from: <7A43AE80-1BEC-396B-A80F-45E43008B804> /Users/simon/.julia/artifacts/a3391a5a73004bf491bf9f164cdc8fa1eba7a81e/lib/libTempestRemap.0.dylib
Reason: tried: '/Users/simon/.julia/artifacts/a3391a5a73004bf491bf9f164cdc8fa1eba7a81e/lib/./libhdf5.200.dylib' (no such file), '/Users/simon/.julia/artifacts/a3391a5a73004bf491bf9f164cdc8fa1eba7a81e/lib/. …
```

TempestRemap: add explicit HDF5 dependency

---

M/MiniZinc/build_tarballs.jl

cc @chriscoey
Quite a bit changed since the last build: https://github.com/MiniZinc/libminizinc/compare/2.6.2...2.7.4
So not sure if this will succeed. I didn't try locally.

[MiniZinc] update to 2.7.4

---

S/SLATEC/build_tarballs.jl

BinaryBuilder failed with the current version of build_tarballs.jl.
build_tarballs.jl has been updated to work with current BinaryBuilder.

[SLATEC] Updated build_tarballs.jl due BinaryBuilder updates

---

M/MiniZinc/build_tarballs.jl

https://github.com/JuliaPackaging/Yggdrasil/pull/6801 rebuild v2.7.4, but it didn't actually build with HiGHS because the `vendor` directory isn't downloaded by default. 
We could potentially use `HiGHS_jll` here, but let's see if libminizinc's vendored version works first.
cc @chriscoey

[MiniZinc] build with HiGHS

---

Z/ZITSOL_1/build_tarballs.jl

Version 0.1.1 dit not build under Julia 1.9
Updated to use libblastrampoline v5.4+ instead of BLAS/LAPACK
LLVM left at version 11 as set for v0.1.1

[ZITSOL_1] Updated for Julia 1.9

---

I/ITSOL_2/build_tarballs.jl

Version 0.1.1 dit not build under Julia 1.9
Updated to use libblastrampoline v5.4+ instead of BLAS/LAPACK
LLVM11 requirement left as is from v0.1.1

[ITSOL_2] Updated for Julia 1.9 build

---

M/MiniZinc/build_tarballs.jl

x-ref https://github.com/jump-dev/MiniZinc.jl/pull/35
We're not using the official binaries, so I'm hesitant to file upstream. Reverting to the version of HiGHS that we compiled with works fine.

[MiniZinc] pin the compat version of HiGHS dependency

---

P/PROPACK/build_tarballs.jl

PROPACK v0.2.2+0 was generated two times but the first release was not registered because of some issues related to LBT.
I recompiled PROPACK but now GitHub is not happy because we try to overwrite the old tarballs generated the first time for the version 2.2.0.
Let's just bump the version number and never register the version 2.2.0.
The version number is not relevant for this package.

[PROPACK] Version 0.2.3

---

S/SPRAL/build_tarballs.jl

@giordano 
Is it possible to trigger the registration of  `SPRAL-v2023.3.29+0` again?
Otherwise, we probably just need to remove the release [SPRAL-v2023.3.29+0](https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/tag/SPRAL-v2023.3.29%2B0) and merge this PR.
`SPRAL` is the last package that I compiled with LBT before the release 1.9.
MUMPS and PROPACK are already fixed.

[SPRAL] Recompile SPRAL to trigger the registration

---

M/MUSCLE/build_tarballs.jl

- Replace GCC with Clang (should address gccv11 concerns, see [Building under OSX](https://github.com/rcedgar/muscle/wiki/Building-MUSCLE#building-under-osx))
- `LLVMOpenMP_jll` dependency for non-Windows builds
---------
Co-authored-by: James Foster <James.Foster@csiro.au>

[MUSCLE] add MacOS build

---

L/LibTeXPrintf/build_tarballs.jl

cc @Suavesito-Olimpiada
I'm not sure why the version jumped from v1.18 to v1.21, but that's upstream.
(the previous issues with parallel builds should now be fixed, I hope!)

Update LibTeXPrintf to upstream v1.21

---

B/Blosc/build_tarballs.jl

- Don't expand C++ ABI (not needed)

Blosc: New version 1.21.4

---

C/Coin-OR/Ipopt/build_tarballs.jl
C/Coin-OR/coin-or-common.jl

Please do not merge.
I need to test if we can switch to the SPRAL solver with the Julia interface Ipopt.jl.

Compile Ipopt with LBT for all platforms

---

P/polymake/build_tarballs.jl

`ArchiveSource` complains that the checksum is unreliable. Luckily polymake.org has downloads that we can use instead.

[polymake] Don't use the tarball from GitHub releases

---

L/libsingular_julia/build_tarballs.jl

- switch to new repository
- store tree hash of the source code
- update Singular_jll dependency to latest

[libsingular_julia] various updates

---

A/AzStorage/build_tarballs.jl

Hello,
We recently were made aware of an issue where on a machine with nvc (installed via the NVidia HPC toolkit), AzStorage would crash via a seg-fault.  It turns out the seg-fault was from an [OpenMP loop in AzStorage.c](https://github.com/ChevronETC/AzStorage.jl/blob/feecaf93eb172499d5d32578a2e5d9e4556df3a9/src/AzStorage.c#L968), and that with NVidia HPC toolkit installed, we were linking to the libgomp shipped with the NVidia HPC toolkit.  It looks like the seg-fault goes away if we build AzStorage with gcc 5 rather than gcc 4 (the default).  We think this is due to compatability issues between the openmp shipped with the NVidia HPC toolkit vs that shipped with gcc 4.
I wasn't sure what to do about the version number in this package.  I decided to leave it as since the source code for …

bump AzStorage preferred gcc version to 5

---

S/SCS_MKL/build_tarballs.jl

so that MKL_jll is a truly optional dependency for SCS ;)
@giordano does that require version bump, or is +1 fine?
cc: @odow

make MKL_jll a BuildDependency only for SCS_MKL

---

0_RootFS/GCCBootstrap@12/bundled/patches/gcc1220-libgomp-win.patch

Companion PR to https://github.com/JuliaPackaging/BinaryBuilderBase.jl/pull/313.  See that PR for the explanation.

[0_RootFS] Backport to GCC 12.1 patch to fix libgomp on Windows

---

C/CompilerSupportLibraries/CompilerSupportLibraries@v1.0/build_tarballs.jl

Follow up to https://github.com/JuliaPackaging/BinaryBuilderBase.jl/pull/313 and https://github.com/JuliaPackaging/Yggdrasil/pull/6871

[CompilerSupportLibraries] Get new build of GCC 12 for Windows with libgomp fix

---

L/llama_cpp/build_tarballs.jl

This updates llama_cpp_jll to support ggml file format v3.

update llama to commit 2d5db48 (19 May 2023)

---

L/libjulia/build_tarballs.jl
L/libjulia/common.jl

I tried to remove some blocks for julia < 1.6, lets see if we really do not need them anymore.
Julia 1.10 was changed to LLVM 15.
We need a new libjulia_jll due to the gc.h changes to do a GAP_jll rebuild for nightly.
But there seem to be a few more changes to the GC lined up for a merge to julia master soon (?), so maybe we want to wait a bit more?
We could also bump 1.9.0 to 1.9.1 but I don't think this is needed?
Draft for now to see if this builds and to get some opinions.
cc: @fingolfin

[libjulia] bump 1.10 commit for gc.h changes

---

Q/Qt6Wayland/build_tarballs.jl

This will also allow gksqt (the GR plot window) to run on Wayland natively when using the Qt6 version and when PR https://github.com/jheinen/GR.jl/pull/518 is integrated. Supersedes https://github.com/JuliaPackaging/Yggdrasil/pull/3555 (which I could never get to work). CC @mkitti

[Qt6] Add Qt6Wayland (host build)

---

M/MAGEMin/build_tarballs.jl

- Added Ultramafic database from Evans&Frost (2021)
- Updated GUI to provide better export features
- Added option to the GUI to select grid refinement based on dominant end-member
- Improved transition from PGE to legacy solver and convergence condition for the legacy solver
- Corrected test bug when installing MAGEMin from the binary builder

MAGEMin 1.3.2

---

L/libgeotiff/build_tarballs.jl

Looks like the [upgrade](https://github.com/JuliaPackaging/Yggdrasil/pull/6924) from libtiff 4.4 to 4.5 was [breaking](https://github.com/JuliaBinaryWrappers/Libtiff_jll.jl/commit/fddff204e013fe40cff4fac05fa9289adaaa8034#diff-248757425c80d519c91e1be718766832fdd989ae7837c5c4b6e64f95931a4757) at least on Windows.
Reported in https://github.com/JuliaGeo/GDAL.jl/issues/158
Also addresses one case of #6857 in an effort to get nightly support working again (https://github.com/JuliaGeo/GDAL.jl/issues/152).

[geotiff] build with libtiff 4.5

---

A/ADIOS2/build_tarballs.jl

The recent update to zfp_jll 1.0 broke ADIOS2_jll because it didn't specify a compat bound for zfp.

ADIOS2: Require zfp >= 1

---

G/GTK4/build_tarballs.jl
G/GTK4/bundled/patches/NSPasteboard.patch

Includes patch to fix MacOS build: https://gitlab.gnome.org/GNOME/gtk/-/merge_requests/5813
This version requires Glib 2.72, so I bumped that compat too.

[GTK4] update to v4.10.4

---

V/ViennaRNA/build_tarballs.jl
V/ViennaRNA/bundled/patches/missing-include-for-size_t.patch

To help with https://github.com/marcom/ViennaRNA.jl/pull/15
- update to ViennaRNA-2.6.2
- only link RNAxplorer to BLAS/LAPACK (and PCRE on windows), not the other programs or shared library
- add patch to fix missing include in headers, causes problems when parsing headers with Clang.jl to build bindings

[ViennaRNA] update to ViennaRNA-2.6.2, fix shared lib linking on julia-1.6

---

X/XGBoost/build_tarballs.jl

Ref: https://github.com/JuliaPackaging/Yggdrasil/pull/6746 and https://github.com/JuliaPackaging/Yggdrasil/issues/6911#issuecomment-1599350319
This PR accomplishes 2 things. The first is that it adds the `cxxstring_abi` back into the builds. I forgot to add it to the platform when porting the CUDA build format from AMGX and other libraries with multiple CUDA versions, where the `cxxstring_abi` is not added to the `augmented_platform`. 
The second thing is that I dropped the `cuda=none` tags on all Windows builds.

[XGBoost] Add cxxstring_abi back in, prevent augmenting Windows with a `cuda=none` tag

---

V/ViennaRNA/ViennaRNA@1.8.5/build_tarballs.jl
V/ViennaRNA/ViennaRNA@1.8.5/bundled/patches/fix-ViennaRNA-1.8.5-compile.patch

Supersedes: #6949 
This is a build script for ViennaRNA-1.8.5 (from 2011), the last version of ViennaRNA-1.x.y.
I need it for some old projects of mine to make them easily reproducible.
I have placed the script in an extra directory so as not to mess up the build script for the current ViennaRNA-2.x.y.

[ViennaRNA] Take two for build script for ViennaRNA-1.8.5

---

L/libjulia/build_tarballs.jl
L/libjulia/common.jl

The soname for libjulia was changed to libjulia.so.MAJOR.MINOR in https://github.com/JuliaLang/julia/pull/49012, now libcxxwrap and everything that depends on it now fails on nightly with: 
```
libjulia.so.1: cannot open shared object file: No such file or directory
```
Lets see if it still builds.
cc: @fingolfin @barche

[libjulia] bump nightly version

---

E/eccodes/build_tarballs.jl

ECMWF recently switched to AEC compression in their grib2 files with cycle 48r1. This means the current version provided by eccodes_jll can't read these grib files anymore.
Thankfully we now have [libaec_jll](https://github.com/JuliaBinaryWrappers/libaec_jll.jl) so we can just enable AEC here.
I tried bumping the version as well, but building the tarballs locally the latest version I managed to build on all platforms without further changes was 2.28.0. This might might provide a good stopgap measure for everyone using GRIB.jl etc with ECMWF data before moving further. Version 2.30.2 is available but has dropped 32 bit support requiring dropping some platforms which I didn't want to do without some feedback first.

[ecCodes] Update ecCodes to 2.28.0 and add libaec

---

L/libcifpp/build_tarballs.jl
L/libcifpp/bundled/patches/clang-libc++-fixes.patch
L/libcifpp/bundled/patches/mingw-no-ioctl.patch

https://github.com/PDB-REDO/libcifpp
C++ library for reading and manipulating mmCIF and PDB files
This is a build requirement for DSSP: https://github.com/PDB-REDO/dssp
Note: the build wants to download components.cif, I have disabled this for the time being as the file is quite large (380 MB decompressed). I don't know what functionality is impacted by this, but the test suite passes at least. We should probably have a better way of sharing components.cif between different packages that need it.
cc: @lmiq

[libcifpp] Add build script for libcifpp v5.1.0

---

N/Ncurses/build_tarballs.jl

See https://github.com/JuliaPackaging/BinaryBuilder.jl/issues/687
The recent change by @barche in PR #6980 reminded me about this.
(I should have done it with my recent ncurses 6.4 update *sigh* but since ncurses only seems to use versions of the form MAJOR.MINOR, it should be OK to use this fake version)

[ncurses] set `TERMINFO_DIRS` environment variable

---

G/GAP/build_tarballs.jl

This PR is "too early" as `libjulia_jll` 1.10.4 did not yet complete
its release cycle. But I thought I'd use the opportunity to verify
that the version specification for the build dependency works as
expect (i.e., makes the CI for this PR fail).

[GAP] rebuild for updated libjulia

---

L/libjulia/common.jl

... at least if it wasn't defined before. This way, packages don't need to repeat that definition over and over again.
Not yet used anywhere, but doing that would be the next step after this is merged, I guess...

[libjulia] define `julia_versions` in common.jl

---

L/libsingular_julia/build_tarballs.jl

Also drop old julia_compat hack from pre-1.6 days -- at least I think that's where it came from (older Julia versions used to choke on the `julia_version` key in the platform)...

[libsingular] update to latest version, add Julia 1.11

---

G/GAP/build_tarballs.jl

... to avoid issues loading it in situations were GAP_jll is new but Readline_jll is not.
CC @thofma @wdecker

[gap] ensure GAP is built against old readline

---

P/Perl/build_tarballs.jl

see https://github.com/JuliaRegistries/General/pull/86946
The new compat also matches what GAP and other packages are using.

[Perl] relax readline compat

---

E/Exodus/build_tarballs.jl

…king changes MBedTLS_jll). Also adding a hack to the build process to fix a tree hash mismatch caused on mac with a comment describing the hack in the script.

[Exodus] update to 8.19.1; update compat for hdf5

---

A/argtable/argtable@2.13/build_tarballs.jl

[libargtable](https://sourceforge.net/projects/argtable/) v2.13.
Possible merge conflict was found when pulling both versions to the General registry (see [#86914](https://github.com/JuliaRegistries/General/pull/86914)),
most likely due to trying to register two versions of the same package at once (my bad :c).

[argtable] reattempt libargtable2 build

---

M/micromamba/build_tarballs.jl

[Release notes](https://github.com/mamba-org/mamba/releases/tag/2023.07.06)
`v1.4.3` has some [issues](https://github.com/mamba-org/mamba/issues/2546) with Windows, but this version has a fix (the fix came in [`v1.4.5`](https://github.com/mamba-org/mamba/releases/tag/2023.06.27)).

[micromamba] Update to v1.4.7

---

0_RootFS/PlatformSupport/build_tarballs.jl
0_RootFS/gcc_common.jl
0_RootFS/gcc_sources.jl
RootFS.md
Z/zig/build_tarballs.jl

The FreeBSD toolchain will need to be updated before this is ready, opening now as draft so I don't forget.

Update FreeBSD from 12.2 to 13.2

---

H/HOHQMesh/build_tarballs.jl

Bug fixes and no longer track large mesh files to reduce the repository size.

update to HOHQMesh version 1.4.1

---

C/CompilerSupportLibraries/CompilerSupportLibraries@v1.0/build_tarballs.jl
L/LLVMCompilerRT/build_tarballs.jl
X/XZ/build_tarballs.jl

JLLs used by Julia itself should be updated to use the FreeBSD 13.2 RootFS since Julia now uses FreeBSD 13.2 for binaries and on CI. To accomplish this, I'm poking some build recipes to trigger rebuilds. @staticfloat said I can do a few at a time, so here's three, more to come.

Trigger new builds for CSL, XZ, and LLVM compiler-rt

---

O/oxigraph_server/build_tarballs.jl

NOTE:
I get the `expand_cxxstring_abis` error, but I don't control the build process... is setting `preferred_gcc_version=v"5"` sufficient to deal with this issue?
```
┌ Warning: /workspaces/Yggdrasil/O/oxigraph_server/build/x86_64-linux-gnu/Ai70oVRW/x86_64-linux-gnu-libgfortran3-cxx03/destdir/bin/oxigraph_server contains std::string values!  This causes incompatibilities across the GCC 4/5 version boundary.  To remedy this, you must build a tarball for both GCC 4 and GCC 5.  To do this, immediately after your `platforms` definition in your `build_tarballs.jl` file, add the line:
│ 
│     platforms = expand_cxxstring_abis(platforms)
```

[oxigraph] Bump oxigraph to 3.18, use pre-built binaries

---

G/GR/build_tarballs.jl

Mirror change in https://github.com/JuliaRegistries/General/pull/87537.  Next version should be changed to use libtiff 2.5.1.
CC: @jheinen

[GR] Restrict compat with libtiff

---

L/LLVM/LLVM_full@15/build_tarballs.jl
L/LLVM/LLVM_full_assert@15/build_tarballs.jl
L/LLVM/common.jl

Bump LLVM to 15.0.7+6 in order to include https://github.com/llvm/llvm-project/commit/af39acda8873cc75db116e326588447f018a99d9 / https://github.com/JuliaLang/llvm-project/commit/01d07e22c2a35ec93c3faef6e1d1af405d5e96a1, ref https://github.com/JuliaLang/julia/issues/50448#issuecomment-1636019331.
cc @vchuravy

Bump LLVM to 15.0.7+6.

---

L/LLVM/LLVM_full@15/build_tarballs.jl
L/LLVM/LLVM_full_assert@15/build_tarballs.jl
L/LLVM/common.jl

@gbaraldi wanted another patch for 1.10, so let's re-do the whole thing :-P
This one should be OK to merge & register, but the LLVM/Clang/MLIR packages from the previous build should be fixed first (they failed to register) as otherwise we'd be skipping a version.

Bump LLVM to include yet another patch.

---

T/tectonic/build_tarballs.jl

@tpapp
Removed experimental as it's uneeded (no-op)
Closes #7065.

[tectonic] bump to v0.14.1

---

D/DSSP/build_tarballs.jl

Unfortunately the binaries we build for windows in this build script crash on any non-trivial operation, so use pre-built upstream binaries for now.
Also added are `FileProduct`s for more reliable installation of mmcif dictionaries necessary at runtime.
cc: @lmiq 
Ref: https://github.com/m3g/ProteinSecondaryStructures.jl/issues/8

[DSSP] Use upstream pre-built binaries on windows

---

L/LibTracyClient/LibTracyClient@0.9.1/build_tarballs.jl

Resolves https://github.com/topolarity/Tracy.jl/issues/28
cc @staticfloat

LibTracyClient: Don't use RTLD_LAZY for `dlopen`

---

S/stldecomposition/build_tarballs.jl

A wrapper around the Fortran implementation of the STL (Seasonal and Trend decomposition using Loess) algorithm.
This builds a modified version in the [r-source repo](https://github.com/SurajGupta/r-source/blob/master/src/library/stats/src/stl.f) of the original [Fortran code](https://www.netlib.org/a/stl).
* Cleveland, R. B., Cleveland, W. S., McRae, J. E., & Terpenning, I. J. (1990). STL: A seasonal-trend decomposition procedure based on loess. Journal of Official Statistics, 6(1), 3–33. [http://bit.ly/stl1990](http://bit.ly/stl1990)
* Hyndman, R.J., & Athanasopoulos, G. (2021) Forecasting: principles and practice, 3rd edition, OTexts: Melbourne, Australia. OTexts.com/fpp3. Accessed on 2023/07/24. [https://otexts.com/fpp3/stl.html](https://otexts.com/fpp3/stl.html)

[stldecomposition] Add build recipe v0.1.0

---

G/GDAL/build_tarballs.jl
G/Git/build_tarballs.jl
M/MariaDB_Connector_C/build_tarballs.jl
N/NetCDF/build_tarballs.jl

Fixes #6857.
Already fixed in the registry in https://github.com/JuliaRegistries/General/pull/88557.
[skip build]

relax LibCURL_jll compat to include v8

---

L/LibSSH2/build_tarballs.jl
N/nghttp2/build_tarballs.jl
Z/Zlib/build_tarballs.jl

The saga continues (#7036, #7121, #7125) to build all of Julia's binary dependencies with FreeBSD 13.2

Rebuild zlib, nghttp2, and libssh2

---

L/LibUnwind/LibUnwind@1.5.0/build_tarballs.jl
L/libblastrampoline/build_tarballs.jl
P/PCRE2/build_tarballs.jl

libunwind and pcre2 were getting their tarballs from GitHub releases but now libunwind uses nongnu for tarballs and pcre2 uses git.

Rebuild libblastrampoline, libunwind 1.5.0, and pcre2

---

0_RootFS/GCCBootstrap@12/bundled/patches/glibc_movq_fix.patch
0_RootFS/gcc_common.jl
0_RootFS/gcc_sources.jl

This is necessary to build for LLVM 16 and libuv.

Upgrade x86_64 and i686 linux GCC shares to Glibc v2.17+

---

D/devspace/build_tarballs.jl

[devspace](https://github.com/devspace-sh/devspace.git) v6.3.2
closes #6536

[devspace] add recipe

---

W/WFA2/build_tarballs.jl
W/WFA2/bundled/patches/remove_march_native.patch

- **Name**: WFA2-lib
- **Version**: 2.3.3 (d1116831a3514fff39321a73b8b526f17f7a2c18)
- **Source**: https://github.com/smarco/WFA2-lib.git
- **Language(s)**: C
- **Build System(s)**: CMake, Make (former chosen)
- **Depends**: None
- **Depends (optional)**: CompilerSupportLibraries (non-BSD platforms, JLL available: yes), LLVMOpenMP (BSD, yes) for OpenMP support
- **Platform(s)**: All excluding Windows (see below)
- **Purpose**:  BioJulia community request
- **Description**: "Wavefront alignment algorithm library v2 "
Will look into attempting a future pr to work around missing sys/mman headers for MingW

[WFA2] add recipe

---

M/micromamba/build_tarballs.jl

This is the first time I am trying to update an Yggdrasil binary, I hope I got it right :)
with v1.4.7 I ran into severe issues[1], even on github actions, where PythonCall simply stops working. According to the issue-tracker this issue should be fixed in 1.4.8 - but 1.4.9 is the newest..
[1] https://github.com/mamba-org/mamba/issues/2663
tagging @tylerjthomas9 because you did the earlier releases

[micromamba] update to  to v1.4.9

---

B/bcftools/build_tarballs.jl

- Name: bcftools
- Version: 1.14 (5f1bf7a1b016c24d38657bdde5fd2ca27e6954e9)
- Source: https://github.com/samtools/bcftools.git
- Language(s): C
- Build System(s): Make (configure)
- Depends: htslib (JLL available: yes), Zlib (yes)
- Depends (optional): GSL (yes), Perl (see below)
- Platform(s): All excluding Windows or platforms using musl (see below)
- Purpose: BioJulia community request
- Description: "program for variant calling and manipulating files in the Variant Call Format (VCF) and its binary counterpart BCF"
Optional Perl filtering support, however both it and bcftools are reliant on glibc-specific symbols, therefore not including Perl nor musl builds. Will look into using the gcompat pkg in a future reattempt. htslib (hard dependency) is not available for Windows.

[bcftools] add recipe

---

C/Cairo/build_tarballs.jl
C/Chafa/build_tarballs.jl
F/FLTK/build_tarballs.jl
F/Fontconfig/build_tarballs.jl
G/GRASS/build_tarballs.jl
G/GTK3/build_tarballs.jl
G/GTK4/build_tarballs.jl
G/GraphicsMagick/build_tarballs.jl
G/gmsh/build_tarballs.jl
H/HarfBuzz/common.jl
L/libass/build_tarballs.jl
L/libbluray/build_tarballs.jl
L/libgraphicsmagic/build_tarballs.jl
O/OCCT/build_tarballs.jl
P/Pango/build_tarballs.jl
P/Pathfinder/build_tarballs.jl
Q/qwtw/build_tarballs.jl
R/RDKit/build_tarballs.jl
S/SDL2_ttf/build_tarballs.jl
S/SFML/build_tarballs.jl
T/TracyProfiler/build_tarballs.jl
T/tectonic/build_tarballs.jl

Similar to #7164, but we don't rebuild these packages, not needed at the moment.

Add compat for all FreeType2 dependants

---

L/LLVM/libLLVM@15/build_tarballs.jl
M/MPFR/build_tarballs.jl
S/SuiteSparse/SuiteSparse@7/build_tarballs.jl

The quest continues to make new binaries using the FreeBSD 13.2 sysroot for all of Julia's dependencies

Rebuild libLLVM, MPFR, and SuiteSparse

---

L/LibGit2/build_tarballs.jl

The quest continues to rebuild Julia's dependencies with the FreeBSD 13.2 sysroot. I attemped libgit2 as part of https://github.com/JuliaPackaging/Yggdrasil/pull/7133 but ended up removing it from that PR since there were issues I couldn't figure out. This PR will try to fix them.

Rebuild libgit2

---

L/LLVM/LLD@15/build_tarballs.jl
O/OpenBLAS/OpenBLAS@0.3.23/build_tarballs.jl

I believe that with this, the quest to rebuild all of Julia's dependencies with the FreeBSD 13.2 sysroot will come to a close.

Rebuild OpenBLAS 0.3.23 and LLD 15

---

L/LibTracyClient/LibTracyClient@0.9.1/build_tarballs.jl
O/Objconv/build_tarballs.jl

I missed that Julia uses these as well. Rebuilding to use the 13.2 sysroot on FreeBSD.

Rebuild LibTracyClient and Objconv

---

O/OpenBLAS/OpenBLAS32@0.3.23/build_tarballs.jl
O/OpenBLAS/OpenBLAS@0.3.23/build_tarballs.jl
O/OpenBLAS/common.jl

400 is a much better cutoff than 50 more most modern machines. Note that 100 is way too small even for modern 4 core machines (I think the 50 limit was found pre AVX2 (and possibly pre fma)). 400 is probably a bit larger than optimal on small machines but only gives up ~13% performance single core compared to 8 core (and on laptops it will probably be better because the single core can turbo higher). It also mitigates the horrible performance cliff of using 16 or more threads on medium sized matrices (between roughly 400 and 1600). Of course the better answer would be to make it so BLAS's threading is integrated with julia's (and we use an appropriate number of threads based on the matrix size), but for now this is a pretty noticeable improvement.
```
julia> BLAS.set_num_threads(32) …
```

[OpenBLAS] update multithreading cutoff

---

S/SDPA/build_tarballs.jl
S/SDPA/bundled/sdpawrap/sdpawrap.cpp

I don't really understand what I'm doing, but this looks correct to me.
x-ref https://github.com/jump-dev/SDPA.jl/issues/49
cc @blegat

[SDPA] add methods to sdpawrap.cpp

---

G/GTK4/build_tarballs.jl

Should fix https://discourse.gnome.org/t/menu-button-gives-error-messages-with-latest-gtk4/15689

[GTK4] update to 4.10.5

---

C/CUDA/CUDA_Driver/build_tarballs.jl
C/CUDA/CUDA_Driver/init.jl

Otherwise the wrong version could get picked up at runtime. Let's hope loading these libraries doesn't have side-effects...
Fixes https://github.com/JuliaGPU/CUDA.jl/issues/1859

CUDA: Eagerly dlopen libraries libcuda may require.

---

C/CUDA/CUDA_Driver/build_tarballs.jl

Apparently you shouldn't merge a PR here before the previous build has been registered.

CUDA: Reland driver hotfix.

---

C/CUDA/cuQuantum/build_tarballs.jl

The documentation only mentions that 1.6.1 is required.

CUDA: Loosen cuQuantum compat bounds on cuTensor.

---

T/TracyProfiler/build_tarballs.jl
T/TracyProfiler/bundled/patches/TracyProfiler-rr-nopl-seq.patch

Several users have reported masssive slowdowns to rr record/replay in packages that have the tracy client loaded. The issue turns out to be an unlucky false positive in an rr heuristic that determines the patchability of `rdtsc`. In rr master, it is possible to guarantee patchability by using a specific `nopl; rdtsc` sequence. Add a patch to tracy to do just that.
See also
https://github.com/rr-debugger/rr/pull/3580
https://github.com/JuliaLang/julia/pull/50975

TracyProfiler: Use rr-safe nopl; rdtsc sequence

---

S/sdsl_lite/build_tarballs.jl

Next major release (needed for SeqAn3 which I'm planning to port over), is now header-only which greatly simplifies the build process

[SDSL] update to v3.0.3

---

C/CUDA/CUDA_Runtime/build_tarballs.jl
C/CUDA/CUDA_Runtime/platform_augmentation.jl
platforms/cuda.jl

That way, the 'version' preference is always set to a valid version number, and not to the `"local"` string. This makes it so that CUDA.jl will know the version of the local toolkit. The exception is of course still the `"none"` entry, but that's to work around BinaryBuilder limitations.
To make this feature more powerful, add some libcudart-based detection of the local toolkit's version. This should make setting `local = "true"` behave similar to using artifacts, i.e., if the driver/runtime are available during precompilation, the version will be auto-detected. Only for environments without CUDA (such as containers, log-in nodes, etc) the user will need to set the `version` preference to inform the system what version of CUDA is being used.
This PR also adds / changes artifact comparison …

CUDA: Make use of a local toolkit require a separate preference.

---

L/libcxxwrap_julia/build_tarballs.jl

This introduces a breaking change because of a change in type mapping storage, dependent JLLs will need to be recompiled when moving to the to-be-released CxxWrap 0.14.
@fingolfin Given Friday's fiasco I'm going to hold off merging this until you had a chance to take a look ;)

[libcxxwrap-julia] Version v0.10.0

---

L/LLVMExtra/build_tarballs.jl

This time, using the correct hash. Also gets rid of older LLVM versions.

LLVM: Bump LLVMExtra

---

L/libjulia/build_tarballs.jl
L/libjulia/bundled/patches/1.11.0-DEV/nonative.patch
L/libjulia/common.jl

To prepare for rebuilds to fix small_typeof errors, see https://github.com/JuliaInterop/CxxWrap.jl/pull/368:
```
libcxxwrap_julia.so: undefined symbol: small_typeof, version JL_LIBJULIA_1.11
```
This includes the patch from https://github.com/JuliaLang/julia/pull/51172 to remove the `native` flag.
We might want to wait a bit with this to also rebuild 1.10 in one go once https://github.com/JuliaLang/julia/pull/50892 is backported?
I have updated it to 1.10.0-beta2 for now to see if there are any other errors but he small_typeof change is not included yet.
cc: @fingolfin @barche 
closes #7043

[libjulia] update 1.11-DEV to latest master, update 1.10 to beta2

---

L/libcxxwrap_julia/build_tarballs.jl

We would like to have a working version for julia nightly before we rebuild everything for the new libcxxwrap 0.11.
cc: @fingolfin @barche

[libcxxwrap_julia] rebuild for julia nightly changes

---

H/HDF5/build_tarballs.jl

This should restore libaec as a SZIP filter for HDF5 ON Windows.
Xref:
https://github.com/msys2/MINGW-packages/pull/18328

[hdf5] Update HDF5 for SZIP support

---

B/boostpython/build_tarballs.jl

My newbie attempt to upgrade boostpython to 1.79.0, consistent with the latest boost we have in Yggdrasil (also 1.79.0), and using the latest Python (3.10.8).
(Renders the discussion at the end of https://github.com/JuliaPackaging/Yggdrasil/pull/6228 moot, unless someone _really_ wants a 1.76.0 with newer Python. That person is no longer me though)

[boostpython] upgrade to 1.79.0 (w/ Python 3.10)

---

L/libusb_compat/build_tarballs.jl

This library should be used for JLLs that depend on libusb-0.1.

[libusb_compat] Add libusb_compat

---

C/CUDA/CUDA_Runtime/build_tarballs.jl
C/CUDA/CUDA_Runtime/platform_augmentation.jl

We now accept version=local again, in which case the actual_version preference can optionally be used to configure the actual toolkit version. The new way of doing this is to set local=true and optionally set the version preference, but that is not backwards compatible with older versions of this JLL.
cc @simonbyrne

CUDA: Add backwards-compatible support for old runtime preferences.

---

P/PRIMA/build_tarballs.jl

Note that I didn't modify the version number because the version 0.7.0 was rereleased upstream to include the hotfix for Windows.

Compile PRIMA for Windows platforms

---

P/PROJ/build_tarballs.jl

The PROJ_SOVERSION stays at 25, but since the minor version is in the DLL filename, this also bumps the major version via the offset, to avoid breakage.
https://github.com/search?q=repo%3AJuliaBinaryWrappers%2FPROJ_jll.jl%20dll&type=code
This means that e.g. libgeotiff > GDAL > GMT also need updating to work with this.
PROJ release notes: https://proj.org/en/9.3/news.html

[PROJ] build v9.3.0

---

L/LibPQ/build_tarballs.jl

NOTE: at the moment, super ugly compromise where `./configure` old build system is used for apple, new `meson` build system is used for everything else. As the `meson` build system was just launched, I expect future releases are likely to be easier to build on apple and we can go back to using one consistent build system (`./configure` builds don't work on windows).

[LibPQ] Bump to 16 and align OpenSSL with HDF5

---

L/libgeotiff/build_tarballs.jl

Which has a new major version offset, see #7366.
Marking as draft since this needs #7366.

[libgeotiff] build against PROJ 9.3

---

K/Kokkos/build_tarballs.jl

In prepration of trying to use it directly in the Trilinos jll (See #7386 #7384).
cc (FYI): @dannys4 @eschnett @Crghilardi

Kokkos: Bump to 4.1.00

---

C/CUDA/CUDA_SDK@12.2/build_tarballs.jl
C/CUDA/CUDA_SDK_static@12.2/build_tarballs.jl
C/CUDA/common.jl

Fixes https://github.com/JuliaGPU/CUDA.jl/issues/2066
I'll have to bump the other SDK JLLs as well, but those shouldn't be merged immediately, as that otherwise results in conflicts in General.

CUDA: Bump 12.2 SDKs.

---

G/GR/build_tarballs.jl

[GR] bump version

---

B/blis/common.jl

This enables the CBLAS (and BLAS) compatibility layer, creating currently missing symbols starting with `cblas_`. These are accessed, for example, in the `LinearAlgebra` standard library `./julia/stdlib/LinearAlgebra/src/blas.jl` when using BLIS through `libblastrampoline`.
cf.  https://github.com/flame/blis/blob/c6546c1131b1ddd45ef13f9f2b620ce2e955dbf8/configure#L275-L279

[blis] Add --enable-cblas flag to configuration

---

G/GDAL/build_tarballs.jl

See https://github.com/JuliaPackaging/Yggdrasil/pull/7050#discussion_r1334462064
Registration of the previous version was blocked: https://github.com/JuliaRegistries/General/pull/91991

[GDAL] fix version_offset

---

X/XGBoost/build_tarballs.jl
X/XGBoost/bundled/patches/mac_make_shared.patch

[Release notes](https://github.com/dmlc/xgboost/releases/tag/v2.0.0)
Here are the changes that I have made:
- Bump the XGBoost version to 2.0 and updated the build to the corresponding commit 
- Bump `preferred_gcc_version` from `v8` to `v9` for `std::filesystem` support (from my research, this was the best fix that I found, and the builds worked with this change)
- Add MacOS upgrade to support new C++ features such as `any_cast` in macOS 10.14+ and `std::filesystem` in macOS 10.15+
- Patch to fix MacOS compiling with `std::make_shared`

[XGBoost] Upgrade to v2.0

---

platforms/cuda.jl

In the CUDA platform augmentation, `setindex!` fails on Julia `v1.9` because `local_toolkit` is a `Bool` instead of a `String`. This is causing the latest XGBoost to [fail](https://github.com/JuliaRegistries/General/pull/92047) on Julia `v1.9`+. I have tested this patch in [my fork](https://github.com/tylerjthomas9/XGBoost_jll.jl) of `XGBoost_jll`
This small update was from @maleadt. I just created the PR.

Convert `local_tookit` to `String` in the CUDA platform augmentation

---

X/XGBoost/build_tarballs.jl

[Ref](https://github.com/JuliaPackaging/Yggdrasil/pull/7422)
`CUDA.augment` prevented the build for XGBoost_jll v2.0 from being registered. I just added a commit that changed no code in the build to push through another build of XGBoost_jllwith the patched `CUDA.augment`. 
[Here](https://github.com/JuliaRegistries/General/pull/92047) is the XGBoost_jll v2 registration with the broken import.

[XGBoost] Recompile XGBoost to trigger new registration of v2

---

U/UserNSSandbox/build_tarballs.jl

The current sandbox code has a race condition. If the child exits before the sigwait signal mask is setup, we will hang forever waiting for a signal. This has been observed in practice in Yggdrasil.

[UserNSSandbox] Fix race condition

---

A/abPOA/build_tarballs.jl
A/abPOA/bundled/patches/no_march_native.patch

- **Name**: abPOA
- **Version**: 1.4.1 (16c64e5163cbd0502792ca20f1069fe40c929b0d)
- **Source**: https://github.com/yangao07/abPOA.git
- **Language(s)**: C
- **Build System**: CMake
- **Depends**: SIMDe (JLL available: yes), Zlib (yes)
- **Depends (optional)**: N/A
- **Purpose**:  BioJulia community request
- **Description**: "abPOA: an SIMD-based C library for fast partial order alignment using adaptive band"
Patched out the -march option (disallowed in BinaryBuilder) and enabled shared libraries

[abPOA] add recipe

---

L/LAST/build_tarballs.jl

- Name: LAST
- Version: 1499 (2cc68d3ba8ae5ca46ceeb69302aef18b9db04f46)
- Source: https://gitlab.com/mcfrith/last.git
- Language(s): C++/Python
- Build System: Makefile
- Depends: Zlib (JLL available: yes)
- Depends (optional): N/A
- Purpose: Bioinformatics software port
- Description: "LAST: find & align related regions of sequences"
Python dependency unused (do not build last-dotplot)
Remove Windows support due to missing sys/mman header
LAST is versioned based on tag numbering

[LAST] add recipe

---

L/libwebp/build_tarballs.jl

CVE reference: https://nvd.nist.gov/vuln/detail/CVE-2023-5129
Good news is that the binaries which depend on this one are not version pinned...
Wonder if the previous versions should be yanked from the registry??

[libwebp] Bump to v1.2.4 with CVE fix

---

0_RootFS/GCCBootstrap@10/bundled/patches/gcc520-libgomp-Don-t-hard-code-MS-printf-attributes.patch
0_RootFS/GCCBootstrap@10/bundled/patches/gcc9_vsnprintf-str.patch
0_RootFS/GCCBootstrap@5/bundled/patches/gcc520-libgomp-Don-t-hard-code-MS-printf-attributes.patch
0_RootFS/GCCBootstrap@6/bundled/patches/gcc520-libgomp-Don-t-hard-code-MS-printf-attributes.patch
0_RootFS/GCCBootstrap@7/bundled/patches/gcc520-libgomp-Don-t-hard-code-MS-printf-attributes.patch
0_RootFS/GCCBootstrap@8/bundled/patches/gcc520-libgomp-Don-t-hard-code-MS-printf-attributes.patch
0_RootFS/GCCBootstrap@9/bundled/patches/gcc520-libgomp-Don-t-hard-code-MS-printf-attributes.patch
0_RootFS/GCCBootstrap@9/bundled/patches/gcc9_vsnprintf-str.patch
0_RootFS/gcc_common.jl
0_RootFS/gcc_sources.jl

Sister PR to https://github.com/JuliaPackaging/BinaryBuilderBase.jl/pull/330
Needed these new patches because windows printing is weird apparently.

Update mingw runtime to 11.0.1

---

A/AlphaMolWrapper/build_tarballs.jl
T/Trilinos/build_tarballs.jl

- Name: AlphaMolWrapper
- Version: v0.1 (446c9949291c89596a58cd14f9864101ff0dc9bf)
- Source: https://github.com/IvanSpirandelli/AlphaMolWrapper
- Language: C++
- BuildSystem: CMake
- Depends: GMP
- Depends (optional): None
- Purpose: Calculation of geometric measures of a union of 3d balls.
- Description: "AlphaMol can calculate volume, surface area, mean curvature and Gaussian curvature of a union of 3d balls. Furthermore it can also compute the derivatives of the measures."

[AlphaMolWrapper] add recipe

---

R/ROCmDeviceLibs/ROCmDeviceLibs@5.5.1/build_tarballs.jl
R/ROCmDeviceLibs/common.jl

Build them using ROCmLLVM from 5.4.4 to avoid LLVM 16 vs LLVM 15 incompatibilities.

Add ROCmDeviceLibs@5.5.1

---

0_RootFS/LLVMBootstrap@16/build_tarballs.jl
0_RootFS/LLVMBootstrap@16/bundled/libcxx_patches/0002-llvm8_libcxx_musl.patch
0_RootFS/LLVMBootstrap@16/bundled/patches/0004-enable-emutls-for-mingw.patch
0_RootFS/LLVMBootstrap@16/bundled/patches/0009-compiler-rt-build-crt-in-runtimes-build.patch
0_RootFS/LLVMBootstrap@16/bundled/patches/0010-add-musl-triples.patch
0_RootFS/LLVMBootstrap@16/bundled/patches/0100-llvm-13-musl-bb.patch
0_RootFS/LLVMBootstrap@16/bundled/patches/install-prefix.patch
0_RootFS/LLVMBootstrap@16/bundled/patches/normalize-cmake-triple.patch
0_RootFS/llvm_common.jl

LLVM changed the way runtimes are built, and that big patch is needed because otherwise the build fails. There is also https://reviews.llvm.org/D140925 which will replace [normalize-cmake-triple.patch](https://github.com/JuliaPackaging/Yggdrasil/compare/gb/new-llvm-boot?expand=1#diff-6ecca0277e7bf3d27fe870887a8fb45c4593a8b6614291eaab310b0c9c00cf0d)

Add llvm 16 shard

---

P/P4est/build_tarballs.jl

Currently, OpenMPI is disabled for P4est_jll.

[P4est] Enable OpenMPI

---

L/LLVMCompilerRT/build_tarballs.jl
L/LLVMCompilerRT/bundled/patches/do-not-codesign.patch

This took way longer than I'd like to admit, but I should be able to build `libclang_rt.osx.a` for `aarch64-apple-darwin` (needed for the symbol `__divdc3`)

[LLVMCompilerRT] Update to v16.0.6

---

P/P4est/build_tarballs.jl

Enabling OpenMPI for P4est.jl in #7500 was breaking the JLL, see e.g. https://github.com/trixi-framework/P4est.jl/pull/88. As a hot fix, we first revert the change and disable OpenMPI again.
cc @ranocha, @sloede

[P4est] disable OpenMPI again

---

S/SCOTCH/build_tarballs.jl

The shared library `libptesmumps` and the associated header should be only available in the tarballs generated by PTSCOTCH (#6563).
We also don't want to store the executable in the tarballs.

Recompile SCOTCH for PTSCOTCH

---

platforms/cuda.jl

After #7254, CUDA_full has been replaced by CUDA_SDK.
cc @maleadt

Update CUDA required_dependencies for new CUDA_SDK package name

---

L/LLVM/LLVM_full@16/build_tarballs.jl
L/LLVM/LLVM_full@16/bundled/libcxx_patches/7005_libcxx_musl.patch
L/LLVM/LLVM_full@16/bundled/patches/0001-Disable-tblgen-lsp-server.patch
L/LLVM/LLVM_full@16/bundled/patches/0050-unique_function_clang-sa.patch
L/LLVM/LLVM_full@16/bundled/patches/0100-llvm-12-musl-bb.patch
L/LLVM/LLVM_full@16/bundled/patches/0123-cast-allequal.patch
L/LLVM/LLVM_full@16/bundled/patches/0200-templates.patch
L/LLVM/LLVM_full@16/bundled/patches/0704-no-codesign.patch
L/LLVM/LLVM_full_assert@16/build_tarballs.jl
L/LLVM/LLVM_full_assert@16/bundled
L/LLVM/common.jl

Just to start the ride, it'll likely have problems.  CC: @gbaraldi

[LLVM_full] Build version 16

---

C/CombBLAS/build_tarballs.jl

- Name: CombBLAS
- Version: v2.0.0 (e1c7faad8d5a918d5671b794c04672f30c6bec29)
- Source: https://github.com/PASSIONLab/CombBLAS.git
- Language(s): C++/C
- Build System: CMake
- Depends: OpenMP (jll available: yes - CompilerSupportLibraries), MPI (yes - MPItrampoline)
- Depends (optional): None
- Purpose: Bioinformatics software dependency
- Description: "The Combinatorial BLAS (CombBLAS) is an extensible distributed-memory parallel graph library offering a small but powerful set of linear algebra primitives specifically targeting graph analytics"
gcc recommended for target platforms (see [README](https://github.com/PASSIONLab/CombBLAS/blob/1b1178ef382ed945a3c4e02e3ce98825ab91e4e1/README.md?plain=1#L38))
Need guidance if it is possible to also enable MPI on other platforms like windows

[CombBLAS] add recipe

---

S/SCOTCH/build_tarballs.jl

We will be able to compile PTSCOTCH 7.0.4 after that :crossed_fingers:

[SCOTCH] Delete libptesmumps on all platforms

---

P/picotool/build_tarballs.jl

This is for building the [`picotool`](https://github.com/raspberrypi/picotool) binary, a program used to flash & inspect the Raspberry Pi family of microcontrollers.
The binary is linked statically with libstdc & libstdc++, because _apparently_ their SDK can only be built with GCC13, and pretty much noone is going to already have that around. For my purposes, this will (likely) be good enough.
For future reference, the flags for linking came from [here](https://github.com/arduino/rp2040tools/blob/d6e368bde164286b24a6b647f4a78d49622af457/.github/workflows/release.yml#L77-L91).

[picotool] Add picotool_jll

---

K/Kokkos/build_tarballs.jl

For downstream users that may not want to require OpenMP

Kokkos: Also enable serial execution space

---

T/Trilinos/build_tarballs.jl
T/Trilinos/bundled/patches/teuchoswinexport3.patch

Should hopefully allow the windows build of #7383 to go through.

Trilinos: Add one more patch for missing windows exports

---

C/charon/build_tarballs.jl
C/charon/bundled/patches/charon-all-changes.patch.patch
C/charon/bundled/patches/charon-dup-consts.patch
C/charon/bundled/patches/charon-kokkos-compat.patch
C/charon/bundled/patches/charon-no-rhytmos.patch
C/charon/bundled/patches/m_pi.patch
C/charon/bundled/patches/panzerinclude.patch

* Package name: charon
* Version: v2.2.0

Wizard recipe: charon-v2.2.0

---

C/CompilerSupportLibraries/CompilerSupportLibraries@v1.1/build_tarballs.jl
C/CompilerSupportLibraries/common.jl

[CompilerSupportLibraries] Upgrade to GCC 13 and move Win `*.a` files to subdir

---

platforms/cuda.jl

This will allow easy addition of the static libraries when using the platform dependency generator, since the consuming build_tarballs can just do `CUDA.required_dependencies(platform, static_sdk=true)` instead of having to build the `BuildDependency` themselves.
@maleadt, this look good to you?

[platforms] Add CUDA_SDK_static as an optional dependency in the generator

---

N/NEO/build_tarballs.jl

The new version is broken.
This partially reverts commit 59c0a69f980a670482559924b49ce444c9fdf827.

oneAPI: Revert NEO bump, but enable PVC support.

---

C/CUDA/CUDA_Runtime/platform_augmentation.jl

We were hitting an issue where precompiling on a node with a GPU driver installed would then retrigger precompilation when used on a non-GPU node.
This should avoid the problem when the CUDA runtime version is concretely specified
cc @maleadt @vchuravy

[CUDA_Runtime] only add include_dependency if version not specified

---

U/utf8proc/build_tarballs.jl

Support for Unicode 15.1 (https://github.com/JuliaStrings/utf8proc/pull/253), used in Julia 1.11 (https://github.com/JuliaLang/julia/pull/51799).

update utf8proc to 2.9.0

---

L/libigc/build_tarballs.jl
N/NEO/build_tarballs.jl

Now that the platform augmentations are fixed (we were accidentally selecting debug artifacts with assertions enabled), let's try bumping again.

oneAPI: Bump JLLs again.

---

L/librdkafka/build_tarballs.jl
L/librdkafka/bundled/patches/bsd_posix.patch

So the reason for the build failure seems to be that librdkafka [defines](https://github.com/confluentinc/librdkafka/blob/95a542c87c61d2c45b445f91c73dd5442eb04f3c/src/rd.h#L44) `_POSIX_C_SOURCE` everywhere except windows:
```
#ifndef _POSIX_C_SOURCE
#define _POSIX_C_SOURCE 200809L /* for timespec on solaris */
#endif
```
But this define causes FreeBSD to hide various other defines, including `gettimeofday` and `alloca` (via `__XSI_VISIBLE` and `__BSD_VISIBLE`). We probably need to end up in the default block here to have these available: https://github.com/freebsd/freebsd-src/blob/61b15e6dfc963a0c67dbaeae7f4590674976111f/sys/sys/cdefs.h#L765
PS: The logs from the previous jll version (2.0.3) contain:
```
/workspace/srcdir/librdkafka/src/rdtime.h:118:9: warning: implicit declaration of …
```

[librdkafka] rebuild with freebsd support

---

L/libevent/build_tarballs.jl

These are apparently needed by `PMIx_jll`, see #7605.

[libevent] Add more products

---

A/Aeron/build_tarballs.jl

Update the Aeron client library to 1.42.1
I still hope to build the Aeron media driver in future but have not been successful, so this just bumps the client version.

Update Aeron client to 1.42.1

---

M/MicrosoftMPI/build_tarballs.jl

The header file `mpif.h` provided by `MicrosoftMPI` contains a special character that breaks the compilation of a project with the Meson build system because it is unable to read this character.
I checked the file `mpi.h` and they replaced already this character by a normal space.
I suppose that the number of users of `MicrosoftMPI` for Fortran projects is quite small...

[MicrosoftMPI] Update mpif.h

---

K/KaHyPar/build_tarballs.jl

I need `KaHyPar` in a A64FX machine, so I added the `aarch64-linux-musl` and `aarch64-linux-gnu` platforms.
I'm not sure why, but I was having this error when trying to compile it locally.
```
[18:28:53]  ---> cmake .. -DCMAKE_INSTALL_PREFIX=${prefix} -DCMAKE_TOOLCHAIN_FILE=${CMAKE_TARGET_TOOLCHAIN} -DCMAKE_BUILD_TYPE=Release -DKAHYPAR_PYTHON_INTERFACE=OFF
[18:28:54] Re-run cmake no build system arguments
[18:28:54] CMake Error at /usr/share/cmake/Modules/Compiler/._ADSP-DetermineCompiler.cmake:1:
[18:28:54]   Parse error.  Expected a command name, got bad character with text "".
[18:28:54] Call Stack (most recent call first):
[18:28:54]   /usr/share/cmake/Modules/CMakeCompilerIdDetection.cmake:6 (include)
[18:28:54]   /usr/share/cmake/Modules/CMakeCompilerIdDetection.cmake:33 (_readFile) …
```

Add `aarch64-linux` platforms to KaHyPar, update to v1.3.3 version

---

T/Tasmanian/build_tarballs.jl

New recipes for Tasmanian library (https://github.com/ORNL/TASMANIAN)
"The Toolkit for Adaptive Stochastic Modeling and Non-Intrusive ApproximatioN is a collection of robust libraries for high dimensional integration and interpolation as well as parameter calibration. This documentation focuses on the libraries and the software API, refer to the PDF document on the project web-page for specifics about the mathematics of the implemented methods."

add new recipes for Tasmanian library

---

Q/Qt6Base/build_tarballs.jl
Q/Qt6Base/bundled/patches/mingw.patch

I'm not exactly sure if this is the correct fix?
Fixes #7531.
cc: @barche

[Qt6Base] Upgrade to OpenSSL 3

---

Q/Qt6Base/build_tarballs.jl

[Qt6Base] Targets build for v6.3.5

---

H/Hayagriva/build_tarballs.jl

[Hayagriva v0.4.0 release (8dce242de6366156eee2ea113584236883af6e66)](https://github.com/typst/hayagriva/releases/tag/v0.4.0)

[Hayagriva] Bump to 0.4.0

---

H/htscodecs/build_tarballs.jl

- Name: htscodecs
- Version: v1.5.2 (2aca18b335bc2b580698e487092b794c514ac62c)
- Source: https://github.com/samtools/htscodecs.git
- Language(s): C/JavaScript
- Build System: autoconf
- Depends: Bzip2 (JLL available: yes)
- Depends (optional): JavaScript (unused)
- Description: "Custom compression for CRAM and others."

[htscodecs] add recipe

---

A/ADEPT/build_tarballs.jl

- Name: ADEPT
- Version: v1.0 (166e38b234fd4a6c1e756348eee4253b4ed281ce)
- Source: https://github.com/mgawan/ADEPT.git
- Language(s): C++/Python
- Build System: CMake
- Depends: CUDA, CompilerSupportLibraries
- Depends (optional): Python (unused, only needed for bindings)
- Description: "ADEPT is a GPU accelerated sequence alignment library for short DNA reads and protein sequences."
Not adding multigpu_protein_scoreonly (errors out)

[ADEPT] add recipe

---

L/libjulia/build_tarballs.jl
L/libjulia/common.jl

This is needed to rebuild libcxxwrap (+ maybe more) for the latest julia nightly, see https://github.com/JuliaInterop/libcxxwrap-julia/pull/137.
I bumped the preferred gcc to version 9 for julia 1.11. Older versions (7 and 8) crash in the bfloat instrinsics on `aarch64-linux-{gnu,musl}`:
```
sandbox:${WORKSPACE}/srcdir/julia/src #  aarch64-linux-gnu-gcc -fasynchronous-unwind-tables -fno-tree-tail-merge -DSYSTEM_LIBUNWIND -DSYSTEM_LLVM -DJULIA_NUM_THREADS=1 -DJL_USE_INTEL_JITEVENTS -DJL_USE_PERF_JITEVENTS -std=gnu11 -pipe -fPIC -fno-strict-aliasing -D_FILE_OFFSET_BITS=64 -fno-gnu-unique -DSYSTEM_LIBUNWIND -I/workspace/destdir/include -Wold-style-definition -Wstrict-prototypes -Wc++-compat  -O3 -ggdb2 -falign-functions -D_GNU_SOURCE -I. -I/workspace/srcdir/julia/src …
```

[libjulia] build new nightly for Memory changes, bump 1.10 to rc1

---

S/SDPLR/build_tarballs.jl

It turns out that the library has a nice `sdplrlib` function that would be quite helpful for the Julia wrapper.
This PR compiles a shared library in addition to the executable so that we can call this from the Julia wrapper.

[SDPLR] Add shared library

---

C/Cares/build_tarballs.jl

https://github.com/c-ares/c-ares/releases/tag/cares-1_22_0
- `acountry` executable got removed: https://github.com/c-ares/c-ares/pull/554

[Cares] Update to v1.22.0

---

H/HepMC3/build_tarballs.jl

- Bump version to latest release, 3.2.7
- Add `aarch64-apple-darwin` as target platform
- Increase `julia_compat` to 1.6

[HepMC3] update to v3.2.7, add OS X aarch64 target 

---

C/Coin-OR/Ipopt/build_tarballs.jl
C/Coin-OR/coin-or-common.jl

I also removed the static library `libipopt.a` to reduce the size of the tarballs.

[Ipopt] Upgrade to version 3.14.3

---

I/Infernal/build_tarballs.jl
I/Infernal/bundled/patches/rmark-missing-gsl-link.patch

- use all-in-one tarball from http://eddylab.org/infernal/
- adds support for ARM processors

[Infernal] Update to v1.1.5

---

M/MongoC/build_tarballs.jl

* Switched to `GitSource` as there's no longer any stable archive available and official docs recommend git (https://mongoc.org/libmongoc/current/learn/get/from-source.html#obtaining-the-source)
* Minor fixups

[MongoC] update to v1.25.1

---

X/XML2/build_tarballs.jl

Using CMake breaks ABI compatibility on Windows as the library would have a different soname.
Also, blocked by https://gitlab.gnome.org/GNOME/libxml2/-/issues/625.

[XML2] Switch back to Autotools

---

S/SEAL/build_tarballs.jl

@sloede upon your recommendation I played around with the build and I changed to git cloning instead of downloading the tarball due to the github change (recommended by julia binary builder). Next, I tested this jll with Seal.jl, and the output of the tests there is below. I think its due https://github.com/microsoft/SEAL/releases/tag/v4.0.0 and we could proceed fixing Seal.jl after this is merged probably. This build completes using BinaryBuilder
```
Testing Running tests...
Test Summary: | Pass  Total  Time
1_bfv_basics  |   64     64  1.2s
batch_encoder: Error During Test at /home/zhanibek/Projects/SEAL.jl/test/test_2_encoders.jl:2
Got exception outside of a @test
could not load symbol "CoeffModulus_Create":
/home/zhanibek/.julia/artifacts/084d3d63dee2715e4d178c8e6eba44fcb0c01b00/lib/li …
```

update SEAL to 4.1.1

---

0_RootFS/Rootfs/build_tarballs.jl
0_RootFS/Rootfs/bundled/libs/libc/download_libcs.sh

It should fix some errors when we compile Fortran packages.
Companion PR in BBB: https://github.com/JuliaPackaging/BinaryBuilderBase.jl/pull/353

Upgrade RootFS

---

C/CUDA/CUDA_SDK@12.3/build_tarballs.jl
C/CUDA/CUDA_SDK_static@12.3/build_tarballs.jl

The SDK part of CUDA 12.3.1 was missed in the version bump PR https://github.com/JuliaPackaging/Yggdrasil/pull/7707, so touch the files to rebuild them with the new version.

[CUDA] Build 12.3.1 SDK

---

M/MKL/build_tarballs.jl

MKL should really go hand-in-hand with Intel OpenMP.  See for example https://github.com/JuliaMath/FFTW.jl/issues/281.
Opening as draft because this should be fixed in the registry first, but don't have the time to do that right now.  ***Edit***: done in https://github.com/JuliaRegistries/General/pull/96745.

[MKL] Require same version of IntelOpenMP

---

T/t8code/build_tarballs.jl

This PR fixes a crash on the `x86_64-w64-mingw32` platform when loading `t8code_jll` in Julia. The error message
was something like this:
```
Mingw-w64 runtime failure:
32 bit pseudo relocation at 00007FF6E40F66A1 out of range, targeting 00007FFAB9EEDA10, yielding the value 00000003D5DF736B.
```
Bumping the preferred gcc version to a newer version fixes the problem.

Fix crash in t8code_jll: bump preferred gcc version to 12.0.1.

---

S/SDPLR/build_tarballs.jl

This notably includes the fix https://github.com/sburer/sdplr/pull/2 which is needed for the Julia wrapper SDPLR.jl

[SDPLR] Use github source

---

I/IntelOpenMP/build_tarballs.jl

Using MKL CMake on Windows requires the import library for Intel's OpenMP to be present to work. Unfortunately, this import library isn't distributed in their Conda channel inside the intel-openmp package, and instead is part of the compiler package. The compiler package is also only available on win64 and linux64, so we can only include the import library on w64 targets, not the w32 targets (because I am not sure if they are going to be the same or not, so let's play it safe and just do it on the one that is known to be for it).
It would be nice if we had per-target sources, so not every target has to download the 500MB compiler archive to just ignore it, but c'est la vie.

[IntelOpenMP] Include import library on w64 targets

---

M/MKL_Headers/build_tarballs.jl

Include the CMake/pkgconfig files with the MKL headers so that MKL is usable using the standard CMake/pkgconfig commands.
Also include the Windows import libraries, since the Intel build chain CMake file requires them to be present to link MKL.

[MKL_Headers] Add build system files

---

platforms/cuda.jl

At least on my Julia 1.7 version I use with BB, it errors because it tries to filter the const variable back into itself.

[CUDA] Fix platform script to not overwrite const variable

---

H/Hugo/build_tarballs.jl

- Name: Hugo
- Version: v0.118.2 (da7983ac4b94d97d776d7c2405040de97e95c03d)
- Source: https://github.com/gohugoio/hugo.git
- Language(s): Go
- Build System: go
- Depends: None
- Depends (optional): None
- Description: "The world's fastest framework for building websites."
Requires Go v1.20 to build above v0.118
Windows builds work on my machine though buildkite throws "unable to initialize decompress status for section .zdebug_abbrev" which looks similar to https://github.com/golang/go/issues/28697. It seems to build and work fine so I'm not sure if this is an issue?

[Hugo] add recipe

---

A/ADIOS2/build_tarballs.jl

Case-insensitive file systems become confused because ADIOS2 already depends on the `libsz` library.

ADIOS2: Remove dependency on `libSZ`

---

F/finufft/build_tarballs.jl

- Use latest release of FINUFFT library
- Switch to GCC12. Build was using GCC8 which is explicitly discouraged by FINUFFT team
- Switch from `ArchiveSource` to `GitSource` since GitHub archive hashes no longer are stable

[finufft] Bump Finufft to v2.2.0 and use GCC12

---

M/MKL_Headers/build_tarballs.jl

We have already built 2024.0.0, and that has been fixed to include these CMake/pkgconfig files, but because 2023.2.0 is the last version that is installable on macOS, in order to compile for macOS targets, we should also add these build system files to the 2023.2.0 headers package as well.
I believe this should work with the registry and create a new version for 2023.2.0 and not kill 2024.0.0. I have also restored the old Julia compatibility that 2023.2.0 had, so this should be a transparent change.

[MKL_Headers] Rebuild 2023.2.0 to fix missing CMake files

---

P/POMDPSolve/build_tarballs.jl

New recipe based on a previous receipt (SARSOP). 
I believe all warnings have been taken care of. Changes from the original 5.4 version [link](http://www.pomdp.org/code/index.html) are for cross-platform compatibility and updates for more modern compilers.
This package is intended to be used with https://github.com/JuliaPOMDP/POMDPSolve.jl/tree/jll_integration and addresses https://github.com/JuliaPOMDP/POMDPSolve.jl/issues/11.

[POMDPSolve] Recipe Add

---

L/libpicosat/build_tarballs.jl
L/libpicosat/bundled/Makefile
L/libpicosat/bundled/config.h

I want to use libpicosat in Pkg (see https://github.com/StefanKarpinski/Resolver.jl) and I need it to work on all platforms. The library libpicosat.{so,dll,dylib} is pretty easy to compile for all platforms but the programs rely on a lot of POSIX stuff. This forked JLL provides just the dylib and adds Windows support. We also want what Pkg uses to be as minimal as possible, so this seems worth having as a separate JLL.

libpicosat: fork PicoSAT, only provide libpicosat, support Windows

---

O/OpenFHE/build_tarballs.jl
O/OpenFHE/bundled/patches/macos-include-cmath.patch

Build JLL package for [OpenFHE](https://github.com/openfheorg/openfhe-development).

Add OpenFHE library

---

S/SuiteSparse/SuiteSparse@7/build_tarballs.jl
S/SuiteSparse/common.jl

This release had a large refactor in how the build system was configured, with the introduction of an overarching CMake file in the root directory that now can select the projects to build, and also the renaming of a lot of the SuiteSparse options we need to configure.

[SuiteSparse] Update to v7.4.0

---

A/AMReX/build_tarballs.jl
C/CFITSIO/build_tarballs.jl
G/GraphicsMagick/build_tarballs.jl
L/Libtiff/build_tarballs.jl
M/MPICH/build_tarballs.jl
M/MPItrampoline/build_tarballs.jl
O/OpenMPI/build_tarballs.jl
S/SCIP_PaPILO/build_tarballs.jl
T/t8code/build_tarballs.jl

There are some cases where using `lld` as linker together with Clang is proving to be problematic (for example #7745), this new keyword argument lets you easily switch back to using `ld`.

Use new keyword argument `clang_use_lld` where possible

---

O/OpenFHE/build_tarballs.jl
O/OpenFHE/bundled/patches/windows-fix-cmake-libdir.patch

cc @giordano 
I will also attempt to figure out if this can be fixed upstream, i.e., that OpenFHE directly installs the `.dll` files to the correct location (`bin/`) such that this postfix is not necessary anymore.

OpenFHE: fix library install directory in CMake

---

S/SuiteSparse/SuiteSparse@7/build_tarballs.jl
S/SuiteSparse/SuiteSparse@7/bundled/patches/blas_suffix.patch

This backports the patch from https://github.com/DrTimothyAldenDavis/SuiteSparse/pull/671 to fix the BLAS linkage. After this, the 64-bit build of SuiteSparse is linking against the BLAS/LAPACK functions
```
U dlarf_64_
U dlarfb_64_
U dlarfg_64_
U dlarft_64_
U dnrm2_64_
U dznrm2_64_
```
instead of the non-suffixed variants.

[SuiteSparse] Add patch to fix BLAS linkage on 7.4.0

---

C/crun/build_tarballs.jl

Upstream provides a definition of CLONE_NEWCGROUP now, and includes the kernel's sched.c in addition to libc's, so we don't need any more manual glibc bumps.

crun: Bump to v1.12.

---

A/Aria2/build_tarballs.jl

And hopefully link to libmbedcrypto.so.7, instead of the .5 for the current jll, which fails on current Julia releases.

Update Aria2 to 1.37

---

A/AMGCL_C/build_tarballs.jl

Build script for [AMGCL_C](https://github.com/j-fu/amgcl_c) which is a C wrapper to [AMGCL](https://github.com/ddemidov/amgcl), an algebraic multigrid (AMG) based iterative solver library.
Intended to serve as the backend to [AMGCLWrap.jl](https://github.com/j-fu/AMGCLWrap.jl) intended to be registered once this PR is approved.

[AMGCL_C] new build_tarballs for C Wrapper to AMGCL

---

L/libssh/build_tarballs.jl

Package for https://www.libssh.org.
Some oddities:
- This has an extra `FileProduct` for the Doxygen tag file (useful when generating docs)
- GSSAPI support is only enabled on Linux and freebsd because our Kerberos is only built for those platforms. This causes some warnings on OSX/windows about the dependency not having a product, but I think they can be safely ignored since the library won't try to use it anyway.
- Windows builds show this warning: `Minimum instruction set detected for bin/libssh.dll is avx2, not x86_64 as desired`. I've looked through the code to try to see where those instructions might be coming from but didn't find anything. Not sure how serious it is.

Add recipe for libssh 0.10.6

---

O/object_store_ffi/build_tarballs.jl

- `object_store_ffi` (https://github.com/relationalAI/object_store_ffi) defines a C interface for the Rust crate `object_store` (https://github.com/apache/arrow-rs/tree/master/object_store), which we then use in `ObjectStore.jl` (https://github.com/RelationalAI/ObjectStore.jl/)

Add recipe for object_store_ffi

---

E/elmerfem/build_tarballs.jl

New (unofficial) build recipe for [elmerfem](https://github.com/ElmerCSC/elmerfem/)
Currently this will only build artifacts for certain Linux systems. Hopefully someone can help fix the issues on Windows & MacOS & FreeBSD in due course.

[elmerfem] New package v9.0.20231229

---

L/libmseed/build_tarballs.jl

Also update GitHub organisation in URL to reflect change from
IRIS to EarthScope.

[libmseed] Update libmseed to v3.0.18

---

S/SuiteSparse/SuiteSparse_GPU@7/build_tarballs.jl
S/SuiteSparse/common.jl

This should now be the complete set of changes to make the SuiteSparse GPU recipe build with CUDA in our system.
This is the continuation of https://github.com/JuliaPackaging/Yggdrasil/pull/7803, but it wouldn't let me reopen the PR after force-pushing the branch apparently.

[SuiteSparse_GPU] Update to 7.5.0 and fix CUDA logic

---

I/iso_codes/build_tarballs.jl

This should fix the Windows installation issue.
The tarball is about 6 MB larger. I have tested this version locally with the automated tests in `Gtk.jl` and `Countries.jl` and they both passed, though I don't know what those packages are doing.
The new artifact tree hash is `1719102ef324df43b9fe123a231c2ee630931a03` which matches the tree hash of the old artifact if it is extracted with `copy_symlinks=true`

[iso_codes] Copy symlinks to avoid installation issues.

---

A/adwaita_icon_theme/build_tarballs.jl

The current artifact contains symlinks inside the `share/icons/Adwaita/cursors` directory. These cannot be correctly installed on a typical Windows machine.
`adwaita_icon_theme` has a special process for dealing with installing cursors on Windows that removes the symlinks. (Though that may also be broken in v45 https://gitlab.gnome.org/GNOME/adwaita-icon-theme/-/issues/261).

[adwaita_icon_theme] fix windows installation issues.

---

L/libadwaita/build_tarballs.jl

Also remove symlinks. Should fix #7935
The latest version, 1.4.2, depends on appstream which is not currently in Yggdrasil.

[libadwaita] update to 1.3.6

---

B/Bzip2/build_tarballs.jl

The x86_64-apple-darwin build of `bzip2` was linking to `libgcc_s`, causing errors like
```
dyld[5037]: Library not loaded: '@rpath/libgcc_s.1.dylib'
Referenced from: '/Users/mose/.julia/artifacts/979f68ce65b087a39297a97d21aec04b1d4e9d24/bin/bzip2'
Reason: tried: '/Users/mose/.julia/artifacts/fcce09ea10f6f2d6e185d17a8123a0054d18c1b4/lib/libgcc_s.1.dylib' (no such file), '/Users/mose/.julia/artifacts/979f68ce65b087a39297a97d21aec04b1d4e9d24/lib/libgcc_s.1.dylib' (no such file), '/Users/mose/.julia/artifacts/1e901863cf8fbb1ee50a5d0976114a2371899331/lib/libgcc_s.1.dylib' (no such file)
```
when trying to execute the program if `libgcc_s` isn't available anywhere by default in the system.

[Bzip2] Build with `cc` instead of `gcc`

---

S/Sundials/Sundials@6/build_tarballs.jl

Also, require Julia v1.11+, since Julia v1.11 has a new SuiteSparse version.  This will be the first version that supports Julia v1.11.

[Sundials] Upgrade to v6.7.0

---

O/openfhe_julia/build_tarballs.jl

OpenFHE-julia does not work properly with libcxxwrap-julia v0.12, which has been released 3 days ago (see https://github.com/JuliaInterop/libcxxwrap-julia/issues/143). We therefore build explicitly against the latest version known to work, v0.11.2, until a fix has been released.
@giordano I hope I specified the version correctly and it is not interpreted as a compat setting (with semver upgradeability) but as an exact version.

openfhe_julia: fix version for libcxxwrap_julia to avoid bug

---

P/PETSc/build_tarballs.jl

In `PETSc_jll v3.18.7+1`, merged yesterday, we removed SuiteSparse as a dependency.  Because it was a dependency in version `PETSc_jll 3.18.7+0`, we have problems linking it with other codes [see here](https://github.com/JuliaGeodynamics/LaMEM.jl/actions/runs/7636728953/job/20804282693#step:6:427) as it is looking for SuiteSparse files.
I should really have bumped the version number which is done with this PR.

[PETSc] version 3.18.8

---

L/LaMEM/build_tarballs.jl

This updates LaMEM to use `PETSc_jll` version 3.18.8.
A test with a locally compiled version suggests that it runs fine on [Windows/Mac/linux](https://github.com/JuliaGeodynamics/LaMEM.jl/actions/runs/7644174772/job/20827882495)

[LaMEM] version 2.1.3 

---

M/MAGEMin/build_tarballs.jl

- Largely reworked solver to stabilize and improve general performances
- Added PT paths to the matlab GUI
- Added trace elements calculation to the matlab GUI
- Free H2O for metapelite and metabasite database is now properly considered as a fluid in the output structure
- Corrected wrong cordierite formulation of metapelite database (White et al., 2014)
- Corrected mol fraction sum for phases composition that was not summing to 1.0
- Corrected segfault and memory deallocation when using the Julia wrapper (MAGEMin_C)
- Corrected site fraction issue with liq of igneous database

MAGEMin v1.3.6

---

O/OpenBLAS/OpenBLAS32@0.3.23/bundled/patches/openblas-m1-4003.patch
O/OpenBLAS/OpenBLAS@0.3.23/bundled/patches/openblas-m1-4003.patch

Ref https://github.com/JuliaLang/julia/issues/53054
This should bring the fix from https://github.com/OpenMathLib/OpenBLAS/pull/4003 to Julia 1.10

[OpenBLAS@0.3.23] Add patch to fix CGEMM/CTRMM/DNRM2 on Apple M1/M2

---

G/gdk_pixbuf/build_tarballs.jl

This library has not yet been rebuild against libtiff 4.5.1, since https://github.com/JuliaRegistries/General/pull/86099. That means the GTK stack cannot update to these newer libtiff builds that other deps require.

[gdk_pixbuf] bump patch version and libtiff compat

---

A/adwaita_icon_theme/build_tarballs.jl

Apply the fix in #7930 for the old version of `adwaita_icon_theme_jll.jl` required by `Gtk.jl`
The difference in the tree sha is because the new version is missing the "logs" directory and a few icons are fixed in the "share" directory.
I assume after this PR is merged I should make a PR to undo the changes to go back to the new version?

[adwaita_icon_theme] fix windows installation issues for v3.

---

A/adwaita_icon_theme/build_tarballs.jl

Switches back to the current version of adwaita_icon_theme used by Gtk4 after backporting a fix to v3.

[adwaita_icon_theme] Back to the future [skip build]

---

S/strace/build_tarballs.jl

It appears that old glibc has a bug when reading locale data that makes this particular version of glibc useless for building statically with. Sigh.  Instead, we'll just build normal versions and build for musl as well, but it appears that `aarch64-linux-musl` has a problem that I'm not going to patch right now.

[strace] Don't build static anymore, avoid `aarch64-linux-musl`

---

L/libsingular_julia/build_tarballs.jl

CC @hannes14 @ederc @benlorenz The change to turn Singular_jll into a bdep is as discussed previously:
Decoupling libsingular_julia_jll from Singular_jll is OK because Singular.jl also specifies a version of Singular_jll. The drawback is that one could end up accidentally using the wrong Singular_jll version. But the big advantage is that we are freed to work with newer Singular_jll release in Singular.jl which is safe when using the JLL override mechanism there (when changes in the C++ code is detected while in dev mode, the C++ code just gets compiled and used to replace the code in the JLL).
Dropping the explicit version for Singular_jll also removes the chance for forgetting to update that. Of course all this means that we have to pay close attention in Singular.jl to match what was …

[libsingular_julia] update to latest, drop Singular_jll compat entry

---

M/MUMPS/MUMPS_seq@5/build_tarballs.jl

Related issue: https://github.com/jump-dev/Ipopt.jl/issues/403

Recompile MUMPS_seq 5.6.2 without OpenMP

---

V/VIC5/build_tarballs.jl

This model is under the MIT license.
https://github.com/CUG-hydro/VIC5.c/blob/classic/LICENSE.txt

New Package: Hydrological Model VIC5

---

C/CALCEPH/build_tarballs.jl

Updating CALCEPH to version 3.5.5 (February 2024).

[CALCEPH] Update to v3.5.5

---

H/HiGHS/HiGHS/build_tarballs.jl
H/HiGHS/HiGHSstatic/build_tarballs.jl
H/HiGHS/highs_common.jl

x-ref https://github.com/jump-dev/HiGHS.jl/issues/199
TODO:

[HiGHS] add explicit Zlib_jll dependency

---

L/LibUV/build_tarballs.jl

Smoke build for https://github.com/JuliaLang/julia/pull/49937 to test if this update will go through smoothly

Update libuv to v2-1.48.0

---

L/LLVM/common.jl

This patch sets the default issue tracker URL for LLVM to Julia's issue tracker. LLVM issues coming from Julia should probably go through Julia's issue tracker first and then can be reported upstream if there is an issue with something in upstream LLVM. Having this set to the default is moderately confusing for users as it refers to the LLVM issue tracker, which probably isn't wanted.

Set LLVM issue tracker URL to Julia's issue tracker

---

C/casacore/build_tarballs.jl

Need to trigger a rebuild with the new dependency requirement since CFITSIO_jll seem to have broken semver.

Update casacore dependency cfitsio 4.0.0 -> 4.3.0

---

O/openfhe_julia/build_tarballs.jl

Sorry for the noise 🙈 When working with `libcxxwrap-julia`-based binary wrappers, a "raw" Julia wrapper package, and convenience layer on top of it all, some errors only emerge further down the chain...

[openfhe_julia] update to version v0.2.9

---

O/OpenVAF/build_tarballs.jl

OpenVAF uses Clang to compile a bitcode version of a standard library during the build.
Since the bitcode format is unstable, we need to make sure that the version of LLVM linked against matches the version of `clang` available during the build.

[OpenVAF] Update LLVM to match Clang version

---

C/CUDA/CUDNN/build_tarballs.jl

cuDNN expects to be able to find (dynamically `dlopen`) internal sublibraries, but BinaryBuilder's design makes that impossible, so list the libraries to `dlopen` them explicitly.

CUDNN: Also dlopen internal libraries.

---

O/OpenVAF/bundled/patches/fix-ldflags.patch

This is a small upstream bug, but it turns out being able to provide these flags is essential to get linking working on macOS.

[OpenVAF] Fix condition for `OPENVAF_LDFLAGS` env var

---

M/MicrosoftMPI/build_tarballs.jl

`MicrosoftMPI` provides two shared libraries msmpi.dll and msmpi64.dll and associated import libraries.
We renamed `msmpi64.dll` into `msmpi.dll` but we forgot to also rename the import libraries.

[MicrosoftMPI] Update import libraries

---

F/FFMPEG/FFMPEG/build_tarballs.jl
F/FFMPEG/FFplay/build_tarballs.jl
F/FFMPEG/common.jl

- `libresample` is deprecated and was therefore removed.
- `CUDA_ARGS` was set but `ffnvcodec` (I could not find any jll except for https://github.com/JuliaPackaging/Yggdrasil/blob/master/N/nv_codec_headers/build_tarballs.jl ?) is not provided, resulting in an error when trying to compile it.
There seems to be an error on MacOS, mentioned [here](https://trac.macports.org/ticket/68720l) and indicate that MacOS > 10.13 is needed?

Update FFMPEG to 6.1.1

---

F/finufft/build_tarballs.jl

- Perform library builds using CMake
- Fix broken library and failing Tests on Apple Silicon (observed on M3 Pro)
- Remove obsolete(?) DFFTW_PLAN_SAFE
EDIT: Oops, I messed up and changed the version number... Should probably read 2.2.0+1 instead?

[finufft] Library build using CMake

---

W/WrapIt/build_tarballs.jl

The clang `BuildDependency` was missing the version specification, while the build assumes a specific one.
This has lead to build failure in CI after an update of the default version: https://buildkite.com/julialang/yggdrasil/builds/8260 .
The update script was tested locally.
Philippe.

Fix WapIt_jll build issue.

---

L/LLVMDowngrader/build_tarballs.jl

This adds a new LLVM utility to downgrade IR, currently only to LLVM 5.0. This is useful for GPU back-ends that need to interface with previous LLVM toolchains (Metal, NVIDIA). It's extracted from the Metal_LLVM_Tools repository, and if this approach works, would replace it (with the remaining functionality being moved to GPUCompiler.jl).

LLVM: Add IR downgrader.

---

S/SDPA/build_tarballs.jl
S/SDPA/bundled/patches/shared.diff

Rebase of https://github.com/JuliaPackaging/Yggdrasil/pull/7902 and update SDPA

[SDPA] rebuild for Julia 1.10

---

X/XicTools/build_tarballs.jl
X/XicTools/bundled/patches/Makefile.patch
X/XicTools/bundled/patches/malloc-2.8.6.c.patch

XicTools contains the electronic design editor Xic and the circuit simulator WRspice. This build_tarballs builds the Linux version without a GUI.

add XicTools build script

---

C/Cares/build_tarballs.jl

Security:
Moderate. CVE-2024-25629. Reading malformatted `/etc/resolv.conf`, `/etc/nsswitch.conf` or the `HOSTALIASES` file could result in a crash.
https://github.com/c-ares/c-ares/releases/tag/cares-1_27_0

[Cares] Update to v1.27.0

---

G/Git/build_tarballs.jl

In addition to bumping Git to 2.44.0, this PR changes the Windows bundle to include the git bash parts. See https://github.com/JuliaVersionControl/Git.jl/issues/50 for rationale.

Git: Upgrade to 2.44 and make Windows git more complete

---

I/ImageMagick/ImageMagick@6/build_tarballs.jl

I am relaxing the compat on libtiff (which was set to v4.4), since it looks like [ubuntu and others are using libtiff >=4.5](https://packages.ubuntu.com/noble/libmagickcore-6.q16-7).

[ImageMagick] Update to 6.9.13

---

L/libpolymake_julia/build_tarballs.jl

Use FLINT 2.9 until FLINT 3.1 is released, and the corresponding polymake_jll version.

[libpolymake_julia] rebuild for julia 1.12 (reverting to flint 2.9 for now)

---

O/oneAPI_Support/build_tarballs.jl
O/oneAPI_Support_Headers/build_tarballs.jl

oneAPI: Bump headers and support library to 2024.0.0.

---

O/OpenJpeg/build_tarballs.jl

Make it possible to use newer versions of Libtiff with openjpeg.

[OpenJpeg] Allow libtiff >= 4.5.1 rather than pinning it to that version

---

S/SpFFT/build_tarballs.jl

This is a new build recipe for the SpFFT (Sparse FFT) library: https://github.com/eth-cscs/SpFFT.
Note: we made the active decision to ignore Windows and FreeBSD.

New build recipe for SpFFT

---

S/spla/build_tarballs.jl

PR #8185 introduced the new spla package with a broken `build_tarballs.jl` script (MPI). This is the fixed version of it.

[spla] fix build_tarballs.jl

---

S/SpFFT/build_tarballs.jl

PR #8186 introduced the new SpFFT package with a broken build_tarballs.jl script (MPI). This is the fixed version of it.

[SpFFT] fix build_tarballs.jl

---

C/COSTA/build_tarballs.jl

This is a build recipe for the COSTA (Distributed Communication-Optimal Shuffle and Transpose Algortihm) library: https://github.com/eth-cscs/COSTA.
Note the following line in the script: https://github.com/abussy/Yggdrasil/blob/12c14cbdc661d70f9de2d7365a142cf087336ffe/C/COSTA/build_tarballs.jl#L19. This is a hack in order to be able to build with the native CMake 3.21.7 version despite the project requiring 3.22. It has proven impossible to update CMake in the usual way (see Issue: https://github.com/JuliaPackaging/BinaryBuilder.jl/issues/1317).

[COSTA] New build recipe

---

S/SPIRV_LLVM_Translator_unified/build_tarballs.jl

Bumps the commits, and includes builds for LLVM 16 and 17.

Bump SPIRV to LLVM translator.

---

0_RootFS/GCCBootstrap@13/bundled/patches/gcc-libgomp-environ.patch

See https://gcc.gnu.org/bugzilla/show_bug.cgi?id=111413, this is a fix for https://github.com/JuliaLang/julia/issues/53363 
It's actually a workaround for a deeper issue (https://github.com/python/cpython/issues/116015) that Python is built without `-fPIC` by many maintainers, causing libraries like `libgomp` when loaded with `RTLD_DEEPBIND` not to see the correct `environ` that should have been initialized by glibc. However, the bugfix is also required for `clearenv()` so it's worth carrying anyway.

[GCC] Add `libgomp` patch for NULL `environ` (v13.2.0)

---

O/OpenFOAM_com/build_tarballs.jl

Moving etc folder to `artifact_dir` and pointing `WM_PROJECT_DIR` to `artifact_dir`.  With this, the package could be used directly without setting any ENV on target machine.

[OpenFOAM_com] Add package environment variables to `init_block`

---

S/SDPA/build_tarballs.jl

x-ref https://github.com/JuliaPackaging/Yggdrasil/issues/7904#issuecomment-1982683296
Code take from https://github.com/JuliaPackaging/Yggdrasil/pull/2339/

[SDPA] fix Windows build

---

C/cppcheck/build_tarballs.jl

This adds a build for cppcheck: https://github.com/danmar/cppcheck
cppcheck is useful for static analysis of C/C++ code. From the manual:
> Cppcheck is an analysis tool for C/C++ code. It provides unique code analysis
> to detect bugs and focuses on detecting undefined behaviour and dangerous
> coding constructs. The goal is to detect only real errors in the code, and generate
> as few false positives (wrongly reported warnings) as possible. Cppcheck is
> designed to analyze your C/C++ code even if it has non-standard syntax, as is
> common in for example embedded projects.

[cppcheck] init at v2.13.0 

---

C/Cairo/build_tarballs.jl

Based on the discussion in #7508 I thought the issue with Cairo 1.18 was Pango's fault, but it turns out this fixes it without upgrading Pango.
Fixes #7508 (tested locally)

[Cairo] enable fontconfig for all platforms

---

L/llama_cpp/build_tarballs.jl

This PR is meant to supersede https://github.com/JuliaPackaging/Yggdrasil/pull/8165.
We're still unable to build for ARMv{6,7}, so they have been temporarily removed from the build.
The rationale for moving ahead without ARM:
- our JLL is ~600 versions behind Llama.cpp master
- we're missing key functionality (eg, Gemma models, BERT embeddings, Mamba, ...)
- we're missing critical fixes to the server (used heavily by Llama.jl)
- ARMv{6,7} are not common platforms for GenerativeAI workloads
If some ARMv67 users want to include the builds again, with their help we could, hopefully, upstream the fixes to llama.cpp. Unfortunately, at the moment we're lacking the resources to do so.

[llama_cpp] Update to v0.0.16 (b2382, 2024-03-10)

---

F/FLINT/build_tarballs.jl

This bumps the GMP version to 6.2.1 since this is now the minimum supported version by FLINT. It also bumps the MPFR version to 4.2.0 since the previous one was not compatible with GMP 6.2.1.
It also uses the new repository at https://github.com/flintlib/flint.git rather than the old one at https://github.com/flintlib/flint2.git.
@thofma, @benlorenz and @fingolfin I know you have been involved in updating this package before. Do you have any comments on this update?

[FLINT] Update to 3.1

---

M/MAGEMin/build_tarballs.jl

- removed O2 pure phase
- added metastable phases to the output structure
- added LP initial guess to the output structure´
- saves fO2 as log10(fO2)
- corrected computation of driving force threshold for pseudocompounds
- added calculation of volume fraction

MAGEMin v1.3.9

---

G/GAP/build_tarballs.jl
G/GAP/bundled/patches/macos.patch

This is needed for some GAP_pkg_*_jll recipes

[GAP] rebuild with fixed macos linker rules

---

M/MAGEMin/build_tarballs.jl

- Added computation of dQFM
- Corrected computation of oxides fugacity (FeO, Al2O3, H2O, SiO2, TiO2, MgO)
- Added routines to compute specific heat capacity by Gibbs_system differentiation (using MAGEMinApp)
- Improved performances when using legacy solver at suprasolidus conditions

MAGEMin v1.4.0

---

M/MaximumIndependentSet/build_tarballs.jl

Tarballs for MaximumIndependentSet (originally in C++)

Add Maximum Independent Set library

---

M/MaximumIndependentSet/build_tarballs.jl

This PR reflects a minor update in the upstream branch. Two `cout`s have been commented to suppress printing to the standard output

[MaximumIndependentSet] Minor update to upstream branch

---

L/LibGit2/build_tarballs.jl

LibGit2: New version 1.8.0

---

P/p7zip/build_tarballs.jl

[p7zip] Update to 17.05

---

S/svg2pdf/build_tarballs.jl

* Package name: svg2pdf
* Version: v0.10.0

Wizard recipe: svg2pdf-v0.10.0

---

O/oneAPI_Level_Zero/oneAPI_Level_Zero_Loader/build_tarballs.jl

Addresses part of https://github.com/JuliaGPU/oneAPI.jl/issues/399.
These libraries don't have an explicit dependency, and get loaded dynamically. If we haven't `dlopen`ed the library first, we may pick up a system copy, which is bad.
This isn't great; let's hope loading any of these libraries doesn't actually trigger a change in behavior, but AFAIU it's the best we can do given how JLLs/the dynamic loader works.

oneAPI: Make sure the loader uses the correct tracing library.

---

A/Aria2/build_tarballs.jl
A/AzStorage/build_tarballs.jl
I/IOAPI/build_tarballs.jl
N/NetCDFF/build_tarballs.jl
S/samtools/build_tarballs.jl
T/TempestModel/build_tarballs.jl
V/VMEC/build_tarballs.jl

@fxcoudert I'm taking out of #8377 the commits which are only removing the unneeded dependency of MbedTLS from some packages, so that we can keep there only switching to OpenSSL for julia's stdlibs.  The two changesets are independent, what we have here doesn't require changing the SSL backend for the other packages.
This also reduces CI time, when I push new commits.

Remove indirect MbedTLS_jll dependency from a few packages

---

O/OpenSSL/OpenSSL@3.0/build_tarballs.jl
O/OpenSSL/common.jl

To be consistent with other libraries, libcrypto and libssl should be installed in `lib/` (not `lib64/`) on x86_64-linux. I found out about this because of https://github.com/JuliaLang/julia/pull/53891

OpenSSL: install libraries in lib not lib64

---

L/LibGit2/build_tarballs.jl

I made a mistake in #8377: I moved Windows and macOS builds to OpenSSL, but they shouldn't. Moving back to previous situation.

LibGit2: avoid OpenSSL on Windows and macOS

---

L/LibSSH2/build_tarballs.jl

In Julia builds from source, the native Windows crypto backend is used instead of OpenSSL. This brings the binary builds in line (and I think it is good, one less dependency).

LibSSH2: move to native crypto on Windows

---

L/libpostal/build_tarballs.jl

This adds a build script for [libpostal](https://github.com/openvenues/libpostal), an address-parsing library. I intend to write a Julia wrapper for it (WIP at [mattwigway/Postal.jl](https://github.com/mattwigway/Postal.jl])).
I do have two questions about how to package this:
1. libpostal doesn't really follow a versioning scheme; the last release was seven years ago and everyone seems to just use master. I'm not sure how to version the JLL.
2. I'm getting a warning about the binaries using avx2 instructions on the w64 builds. I tried adding -mno-avx2 to CFLAGS but that didn't solve the problem, I'm not sure what else to try.

[libpostal] add build script for libpostal

---

L/LibGit2/build_tarballs.jl

Follow up from #8399.  This should basically be no-op in terms of building, only the generated wrappers should change (by not loading OpenSSL on macOS and Windows).  CC: @fxcoudert.

[LibGit2] Do not load OpenSSL on Windows and macOS

---

L/LibCURL/LibCURL@7/build_tarballs.jl

We will not use this version in Julia (it's too old), but we use it as baseline for building packages depending on libcurl: by having this build without versioned symbols, it can be used to build packages that will link to libcurl with both with and without OpenSSL.

[LibCURL@7] Disable versioned symbols

---

A/AzStorage/build_tarballs.jl

This should be compatible with multiple versions of libcurl.  Ref #8407.

[AzStorage] Rebuild with libcurl with unversioned symbols

---

H/HiGHS/HiGHSstatic/build_tarballs.jl
H/HiGHS/highs_common.jl

Closes https://github.com/JuliaPackaging/Yggdrasil/issues/8408
Let's just remove this for now. It was added in https://github.com/JuliaPackaging/Yggdrasil/pull/8071, and it's only needed for cases where the user wants to read compressed MPS files.

[HiGHSstatic] remove Zlib dependency

---

M/MAGEMin/build_tarballs.jl

- Corrects issue when maximum of PC is reached
- Switch from PGE to LP solver is more aggressive now (catches when norm(gamma) goes crazy)
- Uses the right julia wrapper method to copy bulk_rock and avoid (rare) related segfaults
- Improved initialization of the different solvers
- Extended clean up of allocated but unused arrays

MAGEMin v1.4.2

---

C/CoverM/build_tarballs.jl

This update has bumped dependencies, which should allow it to compile on aarch64 Linux.

Update CoverM to 0.7.0

---

M/MAGEMin/build_tarballs.jl

- largely improved general performances (~40% faster)
- for mac, matrix inversion now uses dgetrs from the accelerate framework
- fixes cases of ill-conditionned matrix due to duplicated pseudocompounds
- fixes minimization status output

MAGEMin v1.4.3

---

H/HDF5/build_tarballs.jl
platforms/mpi.jl

This PR makes the MPI platform augmentation respect the `platform` argument.
The change fixes a rather niche bug, which is that e.g. `Pkg.instantiate(platform=Windows(:x86_64))` from a non-windows machine doesn't install any artifacts that use this augmentation (I don't know if this claim is fully true, but it is true for HDF5).  I discovered this through https://github.com/JuliaComputing/DepotDelivery.jl, a package for bundling a depot as a software deliverable.
Looks like this would [affect quite a few JLLs](https://github.com/search?q=org%3AJuliaBinaryWrappers+augment_mpi%21&type=code).
Is it possible to trigger all these builds without the dummy e.g. `# Trigger build` changes to the `build_tarballs.jl` files?

Update mpi.jl to respect platform argument

---

S/SCS/build_tarballs.jl
S/SCS_GPU/build_tarballs.jl
S/SCS_MKL/build_tarballs.jl

Since SCS_GPU_jll and SCS_MKL_jll are available only on x86_64 platforms the LLVMOpenMP dep is disabled for them.
MKL can be also updated to v2024, but let's do it in another pull request.
@odow

[SCS] enable openmp

---

L/libblastrampoline/build_tarballs.jl
L/libblastrampoline/bundled/cmake/yggdrasilenv.cmake

This PR adds a new CMake file that setups the environment for libblastrampoline to be used with the CMake FindBLAS and FindLAPACK by setting up the various CMake variables those find modules provide to point to the appropriate library in the buildroot.
This replaces the need for setting all the `-DBLAS*` and `-DLAPACK*` variables on the CMake command line each time. Instead, each CMake invocation that will use libblastrampoline should add
```
-DCMAKE_PROJECT_TOP_LEVEL_INCLUDES="${libdir}/cmake/blastrampoline/yggdrasilenv.cmake" \
```
to the command line, and ensure that they declare a dependency on at least version 3.24 of the CMake JLL.
This does expose two extra variables that aren't actually defined by the find scripts normally, `BLAS_INCLUDE_DIRS` and `LAPACK_INCLUDE_DIRS`, which …

[libblastrampoline] Make using libblastrampoline easier from CMake

---

P/Pango/build_tarballs.jl

Also, update dependency on Cairo_jll.  #7454 changed the build system to the newer meson, but this changed the compatibility version in the macOS binaries, which means that libraries built against Cairo 1.16 require a compatibility version way larger than what's recorded in our builds of Cairo 1.18: https://github.com/JuliaGraphics/Cairo.jl/issues/362.  This is non-sense, but this is a reminder that changing build systems has a cost: most of the time they don't produce 100% compatible binaries.
For the record, the problem with the macOS compatibility arises only on macOS < 12 and `-mmacosx-version-min` is set to a value < 10.14 (we use 10.12 for x86_64-darwin builds, and 11.0 for aarch64-darwin builds): https://github.com/giordano/macos-compatibility-version

[Pango] Update to v1.52.2

---

G/gmsh/build_tarballs.jl

This is an attempt to make `gmsh_jll` work on Julia 1.12. The only HDF5 version that works on Julia 1.12 is 1.14, but `gmsh_jll` is locked to 1.12.
IIRC this PR would only result in a new build number for `gmsh_jll` so it might interfere with the existing compat bounds in the registry, right?

[gmsh]: Update to 4.13.0 and build with updated HDF5 version

---

L/LightGBM/build_tarballs.jl
L/LightGBM/bundled/patches/windows/Ws2_32-iphlpapi.patch

The commit for this version is lost in the original repo, so I'm using a fork of the project I made.
I'm rebuilding this since we found a crash in Windows for Julia 1.8, this is related to https://github.com/JuliaLang/julia/issues/48187 and https://discourse.julialang.org/t/issue-with-xgboost-jl-and-libsvm-jl-when-julia-1-8-4/92396.
This build now should work since it was fixed in https://github.com/JuliaLang/julia/pull/50135.
Also, is it okey to just overwrite build_tarballs.jl?
I saw other projects using Package@version folders inside the main package folder but I'm assuming this works too.

[LightGBM]: Rebuild v3.3.5

---

M/MPItrampoline/build_tarballs.jl

- Do not use Hwloc_jll dependency
- Upgrade internal MPICH to 4.2.1

MPItrampoline: Do not build with external hwloc

---

C/CUDA/libNVVM/build_tarballs.jl

I mistakenly bumped the version number, assuming it was decoupled from the upstream version.
Should I revert of yank the v5 JLL? Nobody is depending on it yet, so reverting should be safe, but it's not a common thing with General.

CUDA: Revert lilbNVVM version number bump.

---

C/CUDA/libNVVM/build_tarballs.jl

Although libNVVM's upstream version number did not change between the CUDA 12.2 version we used to distribute, and the current CUDA 12.4 one, there _are_ differences in what the library supports and how it behaves. Upstream should probably have changed a minor version, but lacking that let's just bump the patch number on our side.

CUDA: Bump libNVVM (again).

---

L/libcxxwrap_julia/build_tarballs.jl

GCC version bump because of `std::ranges` support, but I think this is harmless.

[libcxxwrap-julia] Version 0.12.3

---

L/LLVMDowngrader/build_tarballs.jl

We were previously only using this for Metal/AIR, but it may be useful for NVIDIA/NVVM too.

LLVM: Build IR downgrader for all platforms.

---

R/Reactant/build_tarballs.jl

See https://buildkite.com/julialang/yggdrasil/builds/10149#018f3f9b-9218-438c-8bdd-79880854b42e
```
--> Uploading: Reactant-logs.v0.0.4.aarch64-apple-darwin.tar.gz
--
  | --> Uploading: Reactant-logs.v0.0.4.x86_64-linux-gnu-cxx03.tar.gz
  | ERROR: LoadError: TypeError: in keyword argument augment_platform_block, expected String, got a value of type Vector{String}
  | Stacktrace:
  | [1] top-level scope
  | @ /cache/build/yggy-amdci7-9/julialang/yggdrasil/.ci/register_package.jl:139
  | in expression starting at /cache/build/yggy-amdci7-9/julialang/yggdrasil/.ci/register_package.jl:139
```

Reactant fix registration issue

---

C/CUDA/CUDA_JIT/build_tarballs.jl
C/CUDA/CUDA_Runtime/build_10.2.jl
C/CUDA/CUDA_Runtime/build_11.4.jl
C/CUDA/CUDA_Runtime/build_11.5.jl
C/CUDA/CUDA_Runtime/build_11.6.jl
C/CUDA/CUDA_Runtime/build_11.7.jl
C/CUDA/CUDA_Runtime/build_11.8.jl
C/CUDA/CUDA_Runtime/build_12.0.jl
C/CUDA/CUDA_Runtime/build_12.1.jl
C/CUDA/CUDA_Runtime/build_12.2.jl
C/CUDA/CUDA_Runtime/build_12.3.jl
C/CUDA/CUDA_Runtime/build_12.4.jl
C/CUDA/CUDA_Runtime/build_tarballs.jl
C/CUDA/libNVVM/build_tarballs.jl

This makes it possible to always redistribute the latest compiler, while keeping the flexibility of using different runtime libraries (e.g. for driver compatibility). It is also needed for use with NVVM, because using the latest version of that library assumes the latest version of the rest of the compiler stack (i.e., ptxas) is also used.

CUDA: Separate compiler bits from the runtime JLL.

---

E/Extrae/build_tarballs.jl

`libbfd` in binutils embeds version number in its soname, so we have to have a stricter compat bound.  Same as https://github.com/JuliaRegistries/General/pull/106245.  CC: @mofeing.

[Extrae] Fix compat bound with Binutils

---

C/CUDA/CUDA_Runtime/build_10.2.jl
C/CUDA/CUDA_Runtime/build_tarballs.jl
C/CUDA/CUDA_Runtime/platform_augmentation.jl
C/CUDA/CUDA_SDK@10.2/build_tarballs.jl
C/CUDA/CUDA_SDK@11.4/build_tarballs.jl
C/CUDA/CUDA_SDK@11.5/build_tarballs.jl
C/CUDA/CUDA_SDK@11.6/build_tarballs.jl
C/CUDA/CUDA_SDK@11.7/build_tarballs.jl
C/CUDA/CUDA_SDK@11.8/build_tarballs.jl
C/CUDA/CUDA_SDK@12.0/build_tarballs.jl
C/CUDA/CUDA_SDK@12.1/build_tarballs.jl
C/CUDA/CUDA_SDK@12.2/build_tarballs.jl
C/CUDA/CUDA_SDK@12.3/build_tarballs.jl
C/CUDA/CUDA_SDK@12.4/build_tarballs.jl
C/CUDA/CUDA_SDK_static@10.2/build_tarballs.jl
C/CUDA/CUDA_SDK_static@11.4/build_tarballs.jl
C/CUDA/CUDA_SDK_static@11.5/build_tarballs.jl
C/CUDA/CUDA_SDK_static@11.6/build_tarballs.jl
C/CUDA/CUDA_SDK_static@11.7/build_tarballs.jl
C/CUDA/CUDA_SDK_static@11.8/build_tarballs.jl
C/CUDA/CUDA_SDK_static@12.0/build_tarballs.jl
C/CUDA/CUDA_SDK_static@12.1/build_tarballs.jl
C/CUDA/CUDA_SDK_static@12.2/build_tarballs.jl
C/CUDA/CUDA_SDK_static@12.3/build_tarballs.jl
C/CUDA/CUDA_SDK_static@12.4/build_tarballs.jl
C/CUDA/common.jl
C/CUDA/common_10.2.jl
platforms/cuda.jl

This PR introduces yet another CUDA-specific platform tag, `"cuda_platform"`, to differentiate between SBSA and Jetson on aarch64. Jetson binaries are only available on the redist server starting with CUDA 11.8, so I've removed support for older versions.
@stemann Sorry for removing CUDA 10.2 support again, but I haven't seen any changes in CUDA.jl so I figured you weren't interested in that anymore. If you are, it would be relatively easy to get your 10.2 build support compatible with this change: It only requires adding a regular runfile path for SBSA in the 10.2 SDK JLL, keeping your apt-based ones for the Jetson platform.
Changes like this are always fragile and very hard to test, so I expect breakage...

CUDA: Introduce arm64 subarchitecture.

---

.buildkite/pipeline.yml
.buildkite/pipeline.yml.signature
.buildkite/utils.jl
C/Cairo/build_tarballs.jl

Once again, changing the build system of a package (Pixman, #8654) had the side effect of changing randomly the compatibility version number ast in the macOS libraries, which is relevant on macOS < 12.  Same as #8665 and #8497.

[Cairo] Rebuild fixing compat with Pixman

---

platforms/cuda.jl

This is blocking cuda builds
```
ERROR: LoadError: UndefVarError: thisminor not defined
Stacktrace:
[1] supported_platforms(; min_version::VersionNumber, max_version::Nothing)
@ Main.CUDA /cache/build/yggy-amdci7-4/julialang/yggdrasil/platforms/cuda.jl:171
```

fix(cuda.jl): use Base.thisminor

---

L/LLVM/LLVM_full@17/build_tarballs.jl
L/LLVM/LLVM_full_assert@17/build_tarballs.jl
L/LLVM/common.jl

Specifically, https://github.com/llvm/llvm-project/pull/92383, which is needed for GPU back-ends on LLVM 17.
cc @gbaraldi @vchuravy

LLVM: Bump JLLs for LLVM 17 to include additional patch.

---

M/MAGEMin/build_tarballs.jl

- added the option to use aH2O, aO2, aTiO2, aMgO, aFeO and aAl2O3 as buffers
- corrected normalization when hitting liquidus

MAGEMin v1.4.5

---

O/OpenImageIO/build_tarballs.jl

Note that `OpenImageIO_jll` did not make it into the registry yet https://github.com/JuliaRegistries/General/pull/107018.

OpenImageIO: Tighten OpenEXR compat bounds

---

L/LLVM/Clang@17/build_tarballs.jl
L/LLVM/LLD@17/build_tarballs.jl
L/LLVM/LLVM@17/build_tarballs.jl
L/LLVM/MLIR@17/build_tarballs.jl

As suggested by @giordano and @gbaraldi, rebuild the remaining LLVM deps after a recent patch bump to ensure consistent version numbering.

LLVM: Rebuild remaining deps for consistent version numbering.

---

L/LLVM/LLVM_full@17/build_tarballs.jl
L/LLVM/LLVM_full_assert@17/build_tarballs.jl
L/LLVM/common.jl

CppInterOp needs this patch for LLVM 17.
https://github.com/compiler-research/CppInterOp/blob/main/patches/llvm/clang17-1-NewOperator.patch

LLVM: Bump JLLs for LLVM 17 to include the CppInterOp patch.

---

L/LLVM/libLLVM@17/build_tarballs.jl

LLVM: Bump libLLVM 17 JLL to include additional patch.

---

O/OpenMPI/build_tarballs.jl
O/OpenMPI/bundled/patches/build_with_no_undefined.patch

Use internal `libevent`, `PMix`, and `prrte` packages to prevent hangs on startup.

OpenMPI: New version 5.0.3

---

B/blis/blis/build_tarballs.jl
B/blis/blis32/build_tarballs.jl
B/blis/bundled/patches/a64fx_config_screen_sector_cache.patch
B/blis/bundled/patches/armsve_kernels_unscreen_arm_sve_h.patch
B/blis/bundled/patches/armsve_kernels_unscreen_armsve256_int_8x10.patch
B/blis/bundled/patches/armsve_kernels_unscreen_armsve512_int_12xk.patch
B/blis/bundled/patches/bli_macro_defs.h.f77suffix64.patch
B/blis/common.jl

Update BLIS library using `master` branch, but simultaneous with release point of version 1.0.0: https://github.com/flame/blis/releases/tag/1.0
As part of the update process, updated/omitted some of the more outdated patches.
Tested locally on `x86_64-apple-darwin` against Julia LinearAlgebra `blas` tests.

[BLIS] Update to v1.0

---

C/CUDA/CUDA_Runtime/build_11.4.jl
C/CUDA/CUDA_Runtime/build_11.5.jl
C/CUDA/CUDA_Runtime/build_11.6.jl
C/CUDA/CUDA_Runtime/build_11.7.jl
C/CUDA/CUDA_Runtime/build_11.8.jl
C/CUDA/CUDA_Runtime/build_12.0.jl
C/CUDA/CUDA_Runtime/build_12.1.jl
C/CUDA/CUDA_Runtime/build_12.2.jl
C/CUDA/CUDA_Runtime/build_12.3.jl
C/CUDA/CUDA_Runtime/build_12.4.jl
C/CUDA/CUDA_Runtime/build_12.5.jl
C/CUDA/CUDA_Runtime/build_tarballs.jl

Apparently some CUDA toolkit libraries use it, so we need to make sure we've loaded the library to prevent system pollution.

CUDA: Put NVRTC back in the runtime.

---

A/aws_checksums/build_tarballs.jl

This PR updates aws_checksums to version 0.1.18. cc: @quinnj @Octogonapus

Automated update of aws_checksums to version 0.1.18

---

C/cminpack/build_tarballs.jl
C/cminpack/bundled/patches/01_CMakePath.patch
C/cminpack/bundled/patches/02_blas_mkl1.patch
C/cminpack/bundled/patches/03_blas_mkl2.patch
C/cminpack/bundled/patches/04_blas.patch
C/cminpack/bundled/patches/05_libdir.patch
C/cminpack/bundled/patches/06_freebsd.patch

Recipe for cminpack. This builds both the double and single precision libraries, and works on all Yggdrasil-supported platforms. I have backported the relevant patches on the upstream master branch to be on top of the 1.3.8 release, but I ended up disabling BLAS for now (once I get proper CMake support for libblastrampoline it will be easier), but this should match the config the library is currently using.
CC @sglyon
Fixes: https://github.com/JuliaPackaging/Yggdrasil/issues/8779

cminpack: Add recipe for version 1.3.8

---

C/CMake/build_tarballs.jl
C/CMake/bundled/patches/01_libblastrampoline.patch

This backports an upstream patch from https://gitlab.kitware.com/cmake/cmake/-/merge_requests/9557 that adds libblastrampoline to the Find{BLAS,LAPACK} modules to allow packages to now say BLA_VENDOR="libblastrampoline" to properly build against libblastrampoline.
This patch will be included in 3.30, but it applies cleanly to 3.29 as well, so lets use it.

CMake: Add support for libblastrampoline

---

Y/Yosys/build_tarballs.jl

This is a simple version bump, but the dependencies list is quite old at this point. Is there a good way to update the dependency `compat`s automatically?

[yosys] update to 34

---

M/MAGEMin/build_tarballs.jl

- corrected volume fraction nomalization mistake when buffer are used
- set buffer fraction = 0 and renormalize outputed phase fractions accordingly
- added site fraction names for out_matlab option and for the julia wrapper

MAGEMin 1.4.6

---

M/MAGEMin/build_tarballs.jl

- correction of segfault for MAGEMin_jll due to wrong number of site fractions names for igneous biotite
- the segfault was not captured during the suite of tests using the locally compiled libMAGEMin.jll  for version 1.4.6 and only appeared when trying to use the released MAGEMin_jll 1.4.6

MAGEMin 1.4.7

---

M/MAGEMin/build_tarballs.jl

- fully corrects the problem affecting MAGEMin_jll due to discrepancies between number of site fractions and array of site mixing names
Because I cannot reproduce the issue locally (only appears with released MAGEMin_jll) it was tricky to locate all possible places where the segfault could appear.  The segfault happens in another place in version 1.4.7 (with respect to v1.4.6). This allowed me to find the pattern and fully fix the problem in this version.

MAGEMin v1.4.8

---

L/LLVMDowngrader/build_tarballs.jl

Now includes support for writing typed IR for LLVM 5 and 7 while in opaque pointer mode. This is supported on LLVM 15-17, i.e., not LLVM 14 which was the first release with some opaque pointer functionality but not what we need (`TypedPointerType`).
Demo:
```llvm
❯ cat wip.ll
define i32 @ptr_load(ptr %ptr) {
%val = load i32, ptr %ptr
ret i32 %val
}
❯ lvm-as --bitcode-version=5.0 -o | llvm-dis-12 - -o -
define i32 @ptr_load({}* %ptr) {
%1 = bitcast {}* %ptr to i32*
%val = load i32, i32* %1, align 4
ret i32 %val
}
```
For implementation details, see https://github.com/JuliaGPU/llvm-downgrade/pull/5

LLVM: Bump downgrader to include opaque pointer support on LLVM 15-17

---

L/LLVMDowngrader/build_tarballs.jl

There were bugs, of course: https://github.com/JuliaGPU/llvm-downgrade/commit/cbfa9715397a7707b6c1ff94ab325af1fab99220

LLVM: Bump downgrader JLL

---

L/LAPACK/LAPACK/build_tarballs.jl

LAPACK was not compiled with the last commit of #8865.
The cached artifacts were used.

[LAPACK] Regenerate the libaries with updated symbols

---

S/SHTns/build_tarballs.jl

The current version (3.5.3) of SHTns_jll does not have batched transforms, introduced in v3.6.

SHTns: Upgrade to v3.6.6

---

L/libblastrampoline/build_tarballs.jl

The previous release had a bug with the `LBT_USE_RTLD_DEEPBIND` environment variable

[LBT] Bump to v5.10.1

---

P/pandoc_crossref/build_tarballs.jl

@giordano should I just bump the version to 0.3.18? That doesn't seem quite right because it's still pandoc-crossref 0.3.17, but the build number is important to distinguish which version of pandoc it was compiled against (and that's why 0.3.17 already exists as a JLL -- it was compiled against an older version of pandoc)

pandoc-crossref 0.3.17.1a

---

P/pandoc_crossref/build_tarballs.jl
P/pandoc_crossref/utils.jl

Follow up to: https://github.com/JuliaPackaging/Yggdrasil/pull/8892#issuecomment-2168402590

[pandoc_crossref] Compat change requires version bump

---

L/LibSSH2/build_tarballs.jl

In https://github.com/JuliaPackaging/Yggdrasil/pull/8393 we changed the layout of OpenSSL to put libraries in `${prefix}/lib` rather than `${prefix}/lib64`.  While this doesn't effect Julia much, if one uses a tool such a `JLLPrefixes` to plop a bunch of JLL's artifacts in a single prefix and then try to use the binaries directly, the RPATHs no longer work.  This rebuild will create a new version of LibSSH2 that will work with the new OpenSSL binaries.

[LibSSH2] Re-build to lock compatibility with OpenSSL v3.0.14+

---

S/SPIRV_Tools/build_tarballs.jl

This broke precompilation (and thus registration) of the generated JLL:
```
┌ Warning: Replacing docs for `SPIRV_Tools_jll.spirv_link :: Tuple{Function}` in module `SPIRV_Tools_jll`
└ @ Base.Docs docs/Docs.jl:243
ERROR: LoadError: cannot set type for global SPIRV_Tools_jll.spirv_link_path. It already has a value or is already set to a different type.
```
Maybe something that should be caught by the auditor?

SPIRV Tools: fix typo in build recipe.

---

L/Libtool/build_tarballs.jl

In the build environment, `/bin/sh` is bourne-compatible, but this is often not the case.  Let's be conservative and require a `/bin/bash` to run our libtool on whatever platform we deploy it on.

[Libtool] Use `/bin/bash`, not `/bin/sh`

---

D/Dbus/build_tarballs.jl

And delete the `armv6l` filter for platforms. @giordano

update dbus to 1.14.10

---

L/LAStools/build_tarballs.jl

This PR adds the LASzip executable to the exported products, so users have access to this as well as the C API. 
Package version 3.4.4
I'm new to cmake builds so feedback is very much appreciated! If @evetion could review this as well that would be great :slightly_smiling_face:

Add LAStools recipe

---

P/polyfill_glibc/build_tarballs.jl

It was added upstream a `LICENSE` file, making the stated below no longer true.
---
~~There is still no LICENSE file, but I already filled an [issue](https://github.com/corsix/polyfill-glibc/issues/5), though the license is stated in the [`README.md`](https://github.com/corsix/polyfill-glibc?tab=readme-ov-file#license) as `MIT` wit~~
> "the above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software" clause of the MIT license is explicitly waived for any such pieces.

New Recipe: polyfill_glibc v0.1.0

---

H/HOHQMesh/build_tarballs.jl

New release with updated keywords for symmetric boundaries.

Update version to HOHQMesh v1.5.1

---

U/UserNSSandbox/build_tarballs.jl

This includes the most recent change to Sandbox: https://github.com/staticfloat/Sandbox.jl/commit/269e91fd5f9e3eba0ce6df133fc17636c680516f

[UserNSSandbox] Forward all user signals

---

F/finufft/build_tarballs.jl

This fixes a performance problem created after the switch to Cmake building: The build type was not set to Release, thereby missing -O3 optimizations.

[finufft] Set Cmake build type to Release

---

C/cufinufft/build_tarballs.jl

Creating a separate build process for `cufinufft`, the CUDA version of FINUFFT, in order to separate it from the microarchitecture expansion business of the CPU lib.

[finufft] CUDA components of FINUFFT library

---

O/openfhe_julia/build_tarballs.jl

I updated openfhe-julia and set compat settings for OpenFHE_jll to v1.2.0, because in https://github.com/hpsc-lab/openfhe-julia/commit/bf374dd537fdd9cd39e71c50ae959d4340345e07, I had to change some names for compatibility with newest OpenFHE v1.2.0

[openfhe_julia] update to version v0.3.3

---

O/open62541/open62541@1.3/build_tarballs.jl
O/open62541/open62541@1.4/build_tarballs.jl

Increases gcc version. When compiling with v4, v5, or v6, the library produced is not usable, due to segfaults occurring on Windows (with basic functionality). Building with v7 and above makes tests within Open62541.jl pass.
Issue described here: https://discourse.julialang.org/t/a-plea-for-help-with-open62541-opc-ua-binaries/114702
Diagnosed further here: https://github.com/martinkosch/Open62541.jl/pull/22
I know that using the lowest possible gcc version is advised for compatibility reasons, but this fix seems to do the job and resolving the issues while keeping gcc v4 might be a task that is beyond my (current) capabilities.
I hope this workaround is acceptable.

[open62541] specify desired gcc version; fixes segfaults on Windows + Linux.

---

F/FLEXPART/build_tarballs.jl
F/FLEXPART/bundled/patches/flexpart-makefile.patch
F/FLEXPART/bundled/patches/flexpart-parmod.patch

Should fix https://github.com/tcarion/Flexpart.jl/issues/9
CC @PaulPerezRMA

[FLEXPART] Version 10.4.2

---

L/libtakum/build_tarballs.jl

[libtakum](https://github.com/takum-arithmetic/libtakum) is an ISO C99 implementation of [takum arithmetic](https://arxiv.org/abs/2404.18603), a proposed improvement over posit arithmetic of which Yggdrasil contains the SoftPosit implementation. This recipe provides libtakum-0.1.0, the first stable release. There are no warnings generated on any of the tested platforms.
Thanks in advance for reviewing this pull request!

New Recipe: libtakum v0.1.0

---

I/isa_l/build_tarballs.jl

Let me try also enabling builds for AArch MacOS and Windows - the changelog for v2.31 says they've fixed some compilation issues. If these still fail, we can disable them again.

Update isa-l from 2.30 to 2.31

---

L/Libtool/build_tarballs.jl
L/Libtool/bundled/patches/shell_for_libtoolize.patch

We were fixing the shell shebang in `libtool` previously with [0], but failing to set the shell shebang for `libtoolize` as well.
[0] https://github.com/JuliaPackaging/Yggdrasil/pull/8923

[Libtool] Use `@SHELL@` in `libtoolize`

---

C/CUDA/CUDSS/build_tarballs.jl

@maleadt 
It seems that NVIDIA added a new build for `aarch64`.
It's not `sbsa` or `jetson`: https://developer.download.nvidia.com/compute/cudss/redist/redistrib_0.3.0.json
How do we handle it with Yggdrasil?

[CUDSS] Upgrade to v0.3.0

---

C/CUDA/CUDA_Driver/build_tarballs.jl

The artifact is tiny, and is going to be used whenever CUDA_Driver_jll is imported, so now that we have package extensions (and CUDA_Driver_jll thus won't be unconditionally depended on) I think it's fine to make it eager.
Hopefully helps with https://github.com/JuliaGPU/CUDA.jl/issues/2415

CUDA: Make driver JLL's not use lazy artifacts.

---

L/libdecor/build_tarballs.jl

Create a build recipe for [libdecor](https://gitlab.freedesktop.org/libdecor/libdecor) which is used by some Wayland clients.
My motivation is to try to get GLFW working on Wayland (see [GLFW release notes](https://www.glfw.org/docs/3.4/news.html#wayland_libdecor_decorations)), though in local testing adding `libdecor_jll` as a runtime dependency to `GLFW_jll` isn't sufficient to magically solve all problems).

New Recipe: libdecor v0.2.2

---

L/libtakum/build_tarballs.jl

This release contains more bugfixes for the handling of NaR and inter-takum conversions.

[libtakum] Update to v0.1.2

---

L/libtakum/build_tarballs.jl

This release fixes the computation of takums whose magnitude is larger than the dynamic range of float32 and improves the performance of addition and subtraction by around 50%.
A new interface is added: The functions takum*_precision() return the number of mantissa bits for a given takum.

[libtakum] Update to v0.2.0

---

Q/quarto/build_tarballs.jl

This has the Julia QuartoNotebookRunner integration, meaning people building Quarto can simply add it as a dependency in their doc builds, and not need to build it on CI.

[quarto_jll] Bump version to v1.5.54

---

G/GDAL/build_tarballs.jl

Fixes #8781. I rebuilt with different combinations of the 7 dependencies added in #8749 to find that giflib breaks GDAL on Windows. So I suggest removing this dependency for now. @eschnett are you ok with this? I should add that installing the older Giflib_jll v5.2.1 (not [the newly built v5.2.2](#8986)) with the current GDAL_jll also didn't help.

[GDAL] Remove giflib to fix Windows

---

C/Coin-OR/Clp/build_tarballs.jl
C/Coin-OR/coin-or-common.jl

Replaces https://github.com/JuliaPackaging/Yggdrasil/pull/8066

[Clp] update to v1.17.9 and use LBT

---

R/Reactant/build_tarballs.jl

CC @wsmoses
I'm not sure if we need to set the `MODE` env var in the `augment_platform_block`.

[Reactant] Augment platforms with Reactant compilation mode

---

I/ITK/build_tarballs.jl

--The import statement for the package generating was failing due to a repeating library product.

[ITK-v5.3.0] Removed repeating library product

---

L/LLVM/Clang_unified/build_tarballs.jl

Probably needs to be a new JLL because the previous one uses packages versions for compatibility (although `unified` might not be the best suffix).
This fixes the issue where Clang_jll.jl currently sometimes loads the wrong LLVM library, as reported by @jpsamaroo.

Add a unified Clang JLL using platform augmentation.

---

L/LLVM/Clang_unified/build_tarballs.jl

We don't want to have a strict dependency on any libLLVM. Maybe this ought to be an argument to `configure_extraction`, but let's do that if we have more than one package requiring this.

Clang (unified JLL): Relax compat bounds of LLVM dependencies.

---

L/LLVM/Clang_unified/build_tarballs.jl
L/LLVM/common.jl

Our LLVM JLLs are a bit of a mess, IMO. Clang_jll and friends are seemingly only to be used as build tools, since they have `dont_dlopen` set on all LibraryProducts (essentially breaking downstream JLLs that would depend on, e.g.,`libclang`). Yet they have `compat` bounds and artifact selection hooks that only allow use on matching Julia versions...
Meanwhile, the newly introduced Clang_unified_jll _is_ strictly intended to be used as a runtime dependency, so here I'm adding the ability to toggle the `dont_dlopen` setting on LibraryProducts that are produced by the LLVM helper scripts.
All this isn't particularly great, and I may have to revisit it because of OpenCL's annoying property that driver libraries are discovered through env vars instead of normal library semantics, but I'm …

LLVM: dlopen libraries in unified JLLs.

---

L/LLVM/LLVM_full@12.0.0/build_tarballs.jl
L/LLVM/LLVM_full@12.0.1/build_tarballs.jl
L/LLVM/LLVM_full@13.0.1/build_tarballs.jl
L/LLVM/LLVM_full@14.0.5/build_tarballs.jl
L/LLVM/LLVM_full@14/build_tarballs.jl
L/LLVM/LLVM_full@15/build_tarballs.jl
L/LLVM/LLVM_full@16/build_tarballs.jl
L/LLVM/LLVM_full@17/build_tarballs.jl
L/LLVM/LLVM_full@18/build_tarballs.jl
L/LLVM/LLVM_full_assert@11.0.1/build_tarballs.jl
L/LLVM/LLVM_full_assert@12.0.0/build_tarballs.jl
L/LLVM/LLVM_full_assert@12.0.1/build_tarballs.jl
L/LLVM/LLVM_full_assert@13.0.1/build_tarballs.jl
L/LLVM/LLVM_full_assert@14.0.5/build_tarballs.jl
L/LLVM/LLVM_full_assert@14/build_tarballs.jl
L/LLVM/LLVM_full_assert@15/build_tarballs.jl
L/LLVM/LLVM_full_assert@16/build_tarballs.jl
L/LLVM/LLVM_full_assert@17/build_tarballs.jl
L/LLVM/LLVM_full_assert@18/build_tarballs.jl
L/LLVM/common.jl

LLVM_full is a build tool, and should be installable on all LLVM versions. I don't think there's a reason the compat restriction is there; it seems to have been added as `julia_version=1.6` for `experimental_platforms=true` (older versions of LLVM-related JLLs don't have any compat restriction), and got unnecessarily updated with newer releases of LLVM.
Re-land of https://github.com/JuliaPackaging/Yggdrasil/pull/3943. This version of the PR has `[ci skip]`; if landed I'll create a PR on General to update existing JLLs.
I also considered relaxing the compat bounds on packages like LLD_jll or LLVM_jll, since the LibraryProducts have `dont_dlopen=true` anyway, but IIUC these all end up depending on libLLVM_jll which would retain its compat bounds, so the situation wouldn't change in …

LLVM: Allow installation of LLVM_full on all Julia versions.

---

.ci/Manifest.toml
0_RootFS/LLVMBootstrap@14/build_tarballs.jl
0_RootFS/LLVMBootstrap@14/bundled/patches/0002-llvm8_libcxx_musl.patch
0_RootFS/LLVMBootstrap@14/bundled/patches/0010-add-musl-triples.patch
0_RootFS/LLVMBootstrap@14/bundled/patches/0100-llvm-13-musl-bb.patch
0_RootFS/LLVMBootstrap@15/build_tarballs.jl
0_RootFS/LLVMBootstrap@15/bundled/0009-compiler-rt-build-crt-in-runtimes-build.patch
0_RootFS/LLVMBootstrap@15/bundled/patches/0002-llvm8_libcxx_musl.patch
0_RootFS/LLVMBootstrap@15/bundled/patches/0010-add-musl-triples.patch
0_RootFS/LLVMBootstrap@15/bundled/patches/0100-llvm-13-musl-bb.patch
0_RootFS/LLVMBootstrap@15/bundled/patches/install-prefix.patch
0_RootFS/LLVMBootstrap@17/build_tarballs.jl
0_RootFS/LLVMBootstrap@17/bundled/libcxx_patches/0002-llvm8_libcxx_musl.patch
0_RootFS/LLVMBootstrap@17/bundled/patches/0004-enable-emutls-for-mingw.patch
0_RootFS/LLVMBootstrap@17/bundled/patches/0010-add-musl-triples.patch
0_RootFS/LLVMBootstrap@17/bundled/patches/0100-llvm-13-musl-bb.patch
0_RootFS/LLVMBootstrap@17/bundled/patches/install-prefix.patch
0_RootFS/LLVMBootstrap@17/bundled/patches/normalize-cmake-triple.patch
0_RootFS/llvm_common.jl

For building POCL, I need a `clang` version that's compatible with the `libLLVM` that will be loaded at run time. I can't use the one from a `HostDependency`, because it doesn't support generating code for the target I'm working with. So instead I think I have to use `preferred_llvm_version`, matching that up with the LLVM version of the build.
However, it looks like we currently only provide:
```
julia> BinaryBuilder.BinaryBuilderBase.available_llvm_builds
8-element Vector{BinaryBuilderBase.LLVMBuild}:
BinaryBuilderBase.LLVMBuild(v"6.0.1", NamedTuple())
BinaryBuilderBase.LLVMBuild(v"7.1.0", NamedTuple())
BinaryBuilderBase.LLVMBuild(v"8.0.1", NamedTuple())
BinaryBuilderBase.LLVMBuild(v"9.0.1", NamedTuple())
BinaryBuilderBase.LLVMBuild(v"11.0.1", NamedTuple()) …
```

Add compiler shards for LLVM 14, 15 and 17.

---

O/OpenCL/build_tarballs.jl

OpenCL discovers drivers through env vars, so provide a 'hook' allowing drivers (like pocl_jll) to register their libraries in a central place, so that e.g. OpenCL.jl can properly set the env var when doing the initial API call.

OpenCL: Add init hook.

---

G/GLFW/build_tarballs.jl

GLFW 3.4 uses libdecor to draw client-side decorations when interacting with a Wayland display.

[GLFW] Require libdecor_jll for Wayland compatibility

---

T/TermInfoDB/build_tarballs.jl
T/TermInfoDB/bundled/COPYING

This uses the directory-based database rather than the single Berkeley database (terminfo.db). The license is from ncurses, which is close enough; see https://invisible-island.net/ncurses/terminfo.src.html.
Ideally this would be shipped as one of Julia's dependencies to ensure that the custom terminfo parser actually works on all platforms, as not all have the terminfo database.

[terminfo-db] Add a builder for the terminfo database

---

S/SuiteSparse/SuiteSparse@7/build_tarballs.jl
S/SuiteSparse/common.jl

New SuiteSparse release 7.8.0: https://github.com/DrTimothyAldenDavis/SuiteSparse/releases/tag/v7.8.0.
I don't think there are major changes to anything in the core parts we build here, but there might need to be some tweaks to the wrappers (it looks like cholmod at least gained a new function).

[SuiteSparse] Update to 7.8.0 and use common build script

---

C/CUDA/CUDA_Driver/build_tarballs.jl
C/CUDA/CUDA_Driver/init.jl

Instead of dlopen+dlclose, check in a separate process, as suggested by @staticfloat.
Also remove the version checks and queries to improve load latency.

CUDA: Simplify driver initialization script.

---

L/LLVMExtra/build_tarballs.jl

Also drops older versions since LLVM.jl only supports Julia 1.10+ now.

LLVM: Bump LLVMExtra for LLVM 18.

---

P/pocl/build_tarballs.jl

Works around https://github.com/JuliaPackaging/Yggdrasil/issues/9221

POCL: Set the SDKROOT during __init__ to make Clang_jll work.

---

L/Libtool/build_tarballs.jl
L/Libtool/bundled/patches/libtool_relocatable.patch

Without this, moving `libtoolize` around breaks :/

Add relocatability patch to `libtool`

---

T/Tk/build_tarballs.jl

Need to wait for Tcl 8.6.12 to propagate all the way into the pkg servers and then restart this build.

Sync Tk version with Tcl version

---

D/DuckDB/build_tarballs.jl

This was removed, but it could be quite useful to have it accessible whenever the DuckDB library is, e.g. for quick database admin. This is also the same as SQLite.

Add in DuckDB shell to match SQLite

---

O/OpenBLAS/OpenBLAS32@0.3.28/build_tarballs.jl
O/OpenBLAS/OpenBLAS32@0.3.28/bundled/patches/80-memory-buffer-multi-threading.patch
O/OpenBLAS/OpenBLAS@0.3.28/build_tarballs.jl
O/OpenBLAS/OpenBLAS@0.3.28/bundled/patches/80-memory-buffer-multi-threading.patch

Backports https://github.com/OpenMathLib/OpenBLAS/pull/4871.  Ref: https://github.com/JuliaLang/julia/issues/55471, https://github.com/OpenMathLib/OpenBLAS/issues/4868.

[OpenBLAS] Backport patch to fix init of threading memory buffers

---

O/OpenBLAS/OpenBLAS32@0.3.28/bundled/patches/81-memory-buffer-multi-threading.patch
O/OpenBLAS/OpenBLAS@0.3.28/bundled/patches/81-memory-buffer-multi-threading.patch

Follow up to #9262, backport https://github.com/OpenMathLib/OpenBLAS/pull/4879.

[OpenBLAS] Backport new threading buffer patch

---

G/GTK4/build_tarballs.jl

Adds libdrm host dependency for Linux/FreeBSD -- comment in meson.build says only a header is needed.

[GTK4] update to 4.14.5

---

P/Pango/build_tarballs.jl

This will probably be a fix for https://github.com/JuliaGraphics/Cairo.jl/issues/363 , based on discussions in https://gitlab.gnome.org/GNOME/pango/-/merge_requests/720
When building with the latest FriBidi_jll, the following error happens on MacOS:
```
../pango/pango-bidi-type.c:83:10: error: use of undeclared identifier '_FRIBIDI_TYPE_SENTINEL'
[10:08:01]     case _FRIBIDI_TYPE_SENTINEL:
[10:08:01]          ^
[10:08:01] 1 error generated.
```
I think the fix is easy, but using the previous version of FriBidi_jll was easier for me than generating a patch. I'll do that if preferred, and either way I'll create an issue upstream.

[Pango] update to 1.54.0

---

P/pocl/build_tarballs.jl
P/pocl/bundled/patches/env-override.patch

Our build of pocl still has some issues:
- it contains hard-coded paths to executables in the build container
- it wants to execute JLL binaries like `llvm-spirv` which aren't executable in isolation (missing environment set-up)
To fix this, I add a patch that allows overriding paths to executables through env vars (x-ref https://github.com/JuliaPackaging/BinaryBuilder.jl/issues/687), at init time generate JLL wrapper scripts that contain all of the necessary environment set-up (~stolen from~ normally done by JLLWrappers.jl), and register those wrappers with `libpocl` by setting the newly-added env var overrides. I considered adding an API instead and doing this lazily, i.e. on the first API call, but it would be ugly to add these pocl-specific hacks to the otherwise generic OpenCL.jl. …

pocl: Use wrapper scripts for JLL binaries.

---

L/libssh/build_tarballs.jl

Compilation on GCC <5 has been fixed upstream.

[libssh] Update to 0.11.1

---

L/LibUV/build_tarballs.jl

This includes
* https://github.com/JuliaLang/libuv/pull/38, backport of https://github.com/libuv/libuv/pull/4521
* https://github.com/JuliaLang/libuv/pull/39, backport of https://github.com/libuv/libuv/pull/4278

[LibUV] Includes a couple of backports from our fork

---

I/ITKIOWrapper/src/CMakeLists.txt
I/ITKIOWrapper/src/itklib.cpp

The package was basically unusable due to c++ pointer errors,
resolved with the addition of functions for loading spatial metadata from images.

[ITKIOWrapper-v1.0.0] fixed  @wrapmodule error

---

C/CImGuiPack/build_tarballs.jl

Not fully tested yet, but I'm opening the PR for transparency. The URL changed (again :upside_down_face:) because `cimgui-pack` has submodules and you can't register a package with submodules.
Requires https://github.com/JuliaImGui/cimgui-pack/pull/4.

[CImGuiPack] Update for ImGui 1.91.0

---

P/proxTV/build_tarballs.jl

@nathanemac
I also added some
```c
#ifdef __cplusplus
extern "C" {
#endif
...
#ifdef __cplusplus
}
#endif
```
such that we can easlily generate wrappers with Clang.jl.

[proxTV] Recompile with -O3 and include headers in the JLL

---

G/gmsh/build_tarballs.jl

Update gmsh to latest 4.13.1.
Add compat for OCCT_jll `~7.7.2`.  Registration is still open https://github.com/JuliaRegistries/General/pull/113891.
Weirdly, for the previous version `https://gmsh.info/src/gmsh-4.13.0-source.tgz` I get `sha256sum` `c85f056ee549a433e814a61c385c97952bbfe514b442b999f6149fffb1e54f64` that does not match `2a286195e27fe11ee48ce3c98a07c6a4b9961f1e03878e0e3681cf2cfc08db11`.

[gmsh] update to 4.13.1, compat for OCCT_jll

---

Q/quarto/build_tarballs.jl

That same macos ArchiveSource does, in fact, seem to be able to support both amd64 and arm64. It looks like the shell wrapper chooses the appropriate deno JS runtime executable dynamically (I.e. the artifacts in that upstream tarball do seem to also run on my M1 MacBook Pro).
I'm not positive if it makes any difference to have the "unpack_target" be " . . . darwin" or ". . . darwin14". I assumed the former, reasoning that amd Macs are becloming "legacy", and maybe it required pinning to an older Darwin version to work.
We'll see . . .

add arm64 to quarto

---

0_RootFS/PlatformSupport/build_tarballs.jl
0_RootFS/Rust/build_tarballs.jl
0_RootFS/gcc_common.jl
0_RootFS/gcc_sources.jl
RootFS.md

This uses FreeBSD 13.2 to match the setup for x86_64. When adding support for FreeBSD AArch64 to Julia, I was using FreeBSD 14.1, so this may turn out to be a different beast altogether. I guess we'll find out.
Trying to remember what all it is I need to do in order to add a new platform... I think there was something I needed to do that made a tag with release assets for all of the platforms. 🤔

Add support for FreeBSD AArch64

---

F/finufft/build_tarballs.jl

This PR fixes wrong test results in FINUFFT.jl on MacOS (see https://github.com/ludvigak/FINUFFT.jl/issues/64).

[finufft] match LLVM version of LLVMOpenMP

---

X/XZ/build_tarballs.jl

The `preferred_gcc_version` was set to v7 in #8166 due to issues with the assembler emitting instructions not supported by the version of binutils bundled with the default GCC. This was in service of updating XZ to v5.6.0, but as of #8396, we build XZ v5.2.5. When v2.5.2 was initially added in #2057, we used the default GCC, so it should no longer be necessary to require v7.

[XZ] Use default GCC version instead of v7

---

C/CUDA/CUDA_Driver/build_tarballs.jl
C/CUDA/CUDA_Driver/init.jl

Apparently `Libdl.find_libraries` does `dlopen`+`dlclose`, which is what https://github.com/JuliaPackaging/Yggdrasil/pull/9214 intended to avoid: https://github.com/JuliaLang/julia/blob/00739173311983479fee3f5f826e4b763872860a/base/libdl.jl#L199-L216
Fixes https://github.com/JuliaGPU/CUDA.jl/issues/2496

CUDA: Prevent unintended dlopen by not using Libdl.find_libraries.

---

R/rr/build_tarballs.jl

Updates rr to current master, which in particular has https://github.com/rr-debugger/rr/commit/07415f58c423053ad024c69918a014275ef6f73f which fixes rr asserts seen on CI. Also picks up https://github.com/rr-debugger/rr/commit/c1ca64585a923f75b12df2eba259ab64bc5646a1, which was a patch we'd been carrying locally.

Bump rr to 5.8

---

M/MbedTLS/MbedTLS@2.28.6/build_tarballs.jl

Given that Julia is moving toward replacing MbedTLS with OpenSSL and relevant builders for Julia's dependencies have been updated to use OpenSSL instead of MbedTLS, this rebuild may not end up getting used, at least for Julia itself. Might as well rebuild just in case though.

[MbedTLS@2.28.6] Rebuild for FreeBSD AArch64 support

---

P/pandoc_crossref/build_tarballs.jl

I think it doesn't pass the checks since Pandoc is not updated to 3.4 yet. Once pandoc_jll's PR is accepted we should try to pass the checks again

Update pandoc_crossref to 0.3.18.0

---

R/rr/build_tarballs.jl

The way our CI system uses --pack-dir (which was a patch we had been carrying until it got merged upstream) does not quite match what ended up upstream. I'm submitting a PR upstream to fix that, but in the meantime, this carries the changes to make our existing CI system work as before.

Pick up another rr commit

---

O/OpenSSH/build_tarballs.jl

Updated to 9.5.0 on Windows, which seems to be the latest available.

Update OpenSSH and add `sftp` as a product

---

L/libevent/build_tarballs.jl

I updated the OpenSSL compat bounds. Not sure whether that's necessary – it builds without that update, claiming to load `OpenSSL_jll 3.0.12`, which doesn't exist for `aarch64-unknown-freebsd`.

libevent: Build for aarch64-unknown-freebsd

---

S/SuiteSparse/SuiteSparse@7/build_tarballs.jl

Julia 1.11 uses SuiteSparse 7.7 and Julia 1.12 uses SuiteSparse 7.8, so separating the builders permits easier per-Julia-version maintenance.
cc @rayegun @giordano

[SuiteSparse@7] Temporarily set version back to 7.7.0

---

W/WhereAmI/build_tarballs.jl

Cross-platform library for identifying where on the filesystem the current executable lives.

Add builder for whereami

---

G/GAP/bundled/patches/kill-then-wait.patch

... to avoid hang when calling StopSingular(). See also <https://github.com/oscar-system/Oscar.jl/issues/4136> and https://github.com/gap-system/gap/pull/5804

[GAP] Patch CLOSE_PTY_IOSTREAM

---

D/demumble/build_tarballs.jl

I messed up the version number when copying the `build_tarballs.jl` from another recipe... 🤦

demumble: Fix version number.

---

M/MAGEMin/build_tarballs.jl

- Added anhydrous alkaline-silicate melt model (Weller et al., 2024)
- Added upper mantle to uppermost mantle database (Holland et al., 2013)
- corrected computation of apfu for pure phases
- changed simplex threshold from 1e10 to 0 -> fixes issues when dealing with highly reduced systems
- corrected mistake in handling pseudocompounds for the metabasite database
- added several pseudocompounds to improve quality of phase equilibrium for igneous and alkaline database

MAGEMin v1.5.4

---

M/MPFR/build_tarballs.jl

There were no functional changes between #5904 and now; all that should be needed is the version change. Once merged, I'll revert this with `[skip build]`.

[MPFR] Temporarily set version back to 4.1.1 for rebuild

---

C/CUDA/CUDA_Driver/build_tarballs.jl
C/CUDA/CUDA_Driver/init.jl

This is to fix the issue reported [here](https://github.com/JuliaPackaging/Yggdrasil/issues/9462) where we would hit an infinite loop when using CUDA_Driver_jll on a custom system image. 
I've added a step which removes the system image argument on the subprocesses that check for driver compatibility so we don't encounter this. This has fixed the issue when I built it locally

Fix infinite init loop for CUDA_Driver_jll

---

P/PROJ/build_tarballs.jl

Fixes #8780. This is hopefully the last minor release that is breaking for us as they the devs changed their DLL naming after our issue. Now by default only the major version is included in the name, though other naming options are also configurable.
https://github.com/OSGeo/PROJ/pull/4167
https://proj.org/en/9.5/news.html

[PROJ] update to 9.5

---

L/libtakum/build_tarballs.jl

This release adds unit tests and documentation for all 280+ functions and fixes the bugs uncovered by the extensive full-coverage tests. It also remove the useless negation functions and adds type limit definitions.
For the build recipe itself, amend it to remove mdoc manuals that have been added with this release.

[libtakum] Update to v0.4.0

---

C/CUDA/CUDA_Runtime/build_12.6.jl
C/CUDA/CUDA_Runtime/build_tarballs.jl
C/CUDA/CUDA_SDK@12.6/build_tarballs.jl
C/CUDA/CUDA_SDK_static@12.6/build_tarballs.jl
platforms/cuda.jl

NVIDIA didn't released new drivers with this new minor release.
However they added new routines in CUSOLVER, which is unexpected for a minor version.
This is the release note for each updated library:
- [CUBLAS](https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/index.html#cublas-release-12-6-update-2)
- [CUFFT](https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/index.html#cufft-release-12-6-update-2)
- [CUSOLVER](https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/index.html#cusolver-release-12-6-update-2)
- [CUSPARSE](https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/index.html#cusparse-release-12-6-update-2)

[CUDA] Upgrade to 12.6 Update 2

---

L/libCppInterOp/build_tarballs.jl
L/libCppInterOp/bundled/patches/cmake.patch

~~switch back to my repo temporally for a test~~
Upgrade to LLVM 18.

libCppInterOp: bump version to v0.1.4

---

S/SuiteSparse/CXSparse/build_tarballs.jl
S/SuiteSparse/ParU/build_tarballs.jl
S/SuiteSparse/SPEX/build_tarballs.jl
S/SuiteSparse/SSGraphBLAS/build_tarballs.jl

Previous builds didn't get registered. These should be fine to register as the SuiteSparse in 1.11 will be the right one.

[SuiteSparse] Rebuild SuiteSparse extras that weren't registered

---

R/Reactant/build_tarballs.jl

There is a very weird bug in Reactant which only appears on Yggdrasil-built aarch64 macOS artifact. If we build it with LLVM 19 on local, it works fine.
We are trying to check if it's due to the LLVM version used for compilation.
Do not merge yet please.

[Reactant] Try building Reactant with a more up-to-date clang

---

S/SIRIUS/build_tarballs.jl

New build recipe for the SIRIUS library, a C/C++ library for electronic structure calculations (density functional theory).
Note that the `cmake` command is run twice in a row. If not, a cryptic error message appears:
> CMake Error: try_run() invoked in cross-compiling mode, please set the following cache variables appropriately:
MPI_RUN_RESULT_C_libver_mpi_normal (advanced)
MPI_RUN_RESULT_C_libver_mpi_normal__TRYRUN_OUTPUT (advanced)
I am happy to hear suggestions on how to tackle this. 
The jll package is only built for linux-x86_64, linux-aarch64 and macos-aarch64. This is a conscious decision.

[SIRIUS] New package SIRIUS v7.6.0

---

C/Cairo/build_tarballs.jl

This PR corrects the just-pushed update to Cairo_jll. It references a later commit than the official 1.18.2 release.
I had browsed the 1.18.2 release notes but did not look at the commits afterward, one of which fixes a regression in 1.18.2: https://gitlab.freedesktop.org/cairo/cairo/-/issues/870. With Cairo_jll 1.18.2, CairoMakie PDF output is corrupted (which I found out shortly after updating Cairo_jll).
I've verified locally that the version produced by this PR works. There will supposedly be a new libcairo release soon, but replacing this will fix the issue without yanking Cairo_jll 1.18.2 from the registry.

[Cairo] add important bugfix for PDF output

---

G/GDAL/build_tarballs.jl

A more minimal predecessor to #9587 to hopefully be able to fix https://github.com/JuliaGeo/GDAL.jl/issues/179 more quickly.

[GDAL] Add LERC v3 only

---

G/GDAL/build_tarballs.jl

Needs:
The recent LERC_jll v4 release broke GDAL_jll since it was an implicit dependency. See https://github.com/JuliaGeo/GDAL.jl/issues/179.
This tries to make a new release compatible with LERC_jll v4, and the latest breaking PROJ release. Since PROJ is also a dependency of libgeotiff this needs #9586 first.
It also adds compats for dependencies that did not yet have them.

[GDAL] Add LERC v4 and use latest PROJ

---

D/Deno/build_tarballs.jl

Also use the official Linux aarch64 build, since the previous URL now lists it as archived and points to the official builds instead.

[Deno] Update Deno_jll to 2.0.0

---

P/protoc/build_tarballs.jl

We got their version numbering wrong. There's a hidden major version number! See the comment in the build script. Hence the big jump in the major version number.

protoc: New version 105.28.2

---

P/Powsybl/build_tarballs.jl

Hello,
This pull request is adding the build script build_tarballs.jl to build the binary part of powsybl julia bindings.
[PowSyBl ](https://www.powsybl.org/)(Power System Blocks) is an open source framework written in Java, dedicated to electrical grid modelling and simulation.
One thing that is a bit specific to the building process here is that we have a dependency to pre built binaries generated by GraalVM native image. it is used by [pypowsybl ](https://github.com/powsybl/pypowsybl) (powsybl python bindings) to provide a C++ interface to the java framework. Those binaries are also used by the julia bindings and need to be pre built elsewhere because native image does not support cross compilation yet.
This is a work in progress, feel free to comment if something seems off.

Add Powsybl julia binaries building script

---

L/LLVM/LLD@14/build_tarballs.jl
L/LLVM/LLD@15/build_tarballs.jl
L/LLVM/LLD@16/build_tarballs.jl
L/LLVM/LLD@17/build_tarballs.jl
L/LLVM/LLD@18/build_tarballs.jl
L/LLVM/LLD@19/build_tarballs.jl
L/LLVM/LLD_unified/build_tarballs.jl
L/LLVM/common.jl

Currently the JLL only exposes `lld`, which isn't always usable, e.g., when using with Clang and `--ld-path`:
```
lld is a generic driver.
Invoke ld.lld (Unix), ld64.lld (macOS), lld-link (Windows), wasm-ld (WebAssembly) instead
error: linker command failed with exit code 1 (use -v to see invocation)
```
This PR also exposes the platform-specific drivers (which are always built, it seems), and also adds a unified LLD JLL since the library is linked against `libLLVM`.
All this is needed to make Clang_jll portable, as it otherwise relies on a system-wide `ld`.

LLVM: Add unified LLD JLL, and add driver entrypoints.

---

U/Uno/build_tarballs.jl

There's no need for a new version because this JLL is still somewhat in development.

[Uno] bump gitsha without updating version

---

M/MGARD/build_tarballs.jl

`MGARD_jll` wasn't packaged because its dependency `protoc_jll` had an error. Trigger a rebuild to fix this.

MGARD: trigger rebuild

---

platforms/mpi.jl

MPItrampoline is now available on FreeBSD.
Update compat versions for MPICH and MPItrampoline.

platforms: Update MPI platforms

---

B/bsdiff_endsley/build_tarballs.jl

This will help testing https://github.com/JuliaIO/BSDiff.jl/pull/49

[bsdiff_endsley] Update Bzip2 compat

---

O/open62541/open62541@1.4/build_tarballs.jl

Updates open62541 recipe to version 1.4.6
https://github.com/open62541/open62541/releases/tag/v1.4.6

[open62541] update to v 1.4.6

---

M/MAGEMin/build_tarballs.jl

- corrected mass conservation issue when buffer is active
- corrected outputing of bulk_wt that was introduced in version 1.5.5

MAGEMin v1.5.6

---

L/libtakum/build_tarballs.jl

This release adds linear takums, useful constant definitions and an RPN calculator as an example.
Overall the numerical precision was improved using automatic tests.

[libtakum] Update to v0.5.0

---

M/MongoC/build_tarballs.jl

fixes #9666, updates to openssl 3 and should build for aarch64-freebsd now.
Note that this seems to break the tests for Mongoc.jl, see https://github.com/felipenoris/Mongoc.jl/pull/123, the code does work fine though.

[MongoC] update to 1.28.1, update openssl version

---

H/HSL/build_tarballs.jl

The dummy library `libhsl.$dlext` now includes the symbols of HSL solvers needed by Uno. 
-> https://github.com/ralna/libHSL/pull/11
cc @odow

[HSL] Upgrade to v4.0.1

---

U/Uno/build_tarballs.jl

I need to bump the version number because we add a new dependency (`HSL_jll.jl`).
cc @odow @cvanaret
Related PR #9674

Compile Uno with HSL_jll.jl

---

B/bsdiff_classic/build_tarballs.jl

This will help testing https://github.com/JuliaIO/BSDiff.jl/pull/49

[bsdiff_classic] Update Bzip2 compat

---

O/OpenPolicyAgent/build_tarballs.jl

Upgrade OpenPolicyAgent to v0.69.0.
Had to switch `CGO_ENABLED` off because of compilation errors.

Upgrade OPA (OpenPolicyAgent) to v0.69.0

---

S/sshpass/build_tarballs.jl
S/sshpass/bundled/patches/configure-ac.patch

Some oddities:
- This required a configure.ac patch to compile on a lot of platforms.
- I think it needs to be built under cygwin to work on windows, so windows is disabled.

[sshpass] Add recipe

---

F/FFLAS_FFPACK/bundled/patches/fflas-ffpack-typo-in-config-blas.patch

This fixes a silly typo in a header file of the FFLAS_FFPACK library (BLAS call ssryk_ instead of ssyrk_). I should and will upstream it, but meanwhile this fixes compilation problems for libraries using FFLAS_FFPACK_jll

[FFLAS_FFPACK] Patched package's config-blas.h to fix silly typo

---

F/FFLAS_FFPACK/bundled/patches/fflas-ffpack-typo-in-config-blas.patch

Another small error in the original library, which breaks some compilers.

[FFLAS_FFPACK] Fixed return types for cblas_dsyrk and cblas_ssyrk

---

O/OpenFHE/build_tarballs.jl

@sloede, I have updated OpenFHE_jll to the recent version of openfhe-development

[OpenFHE_jll] update to version 1.2.3

---

O/openfhe_julia/build_tarballs.jl

@sloede,
I have updated openfhe-julia to new version also setting new compats for openfhe-development v1.2.3.
This PR should be merged after #9725 
Close https://github.com/hpsc-lab/openfhe-julia/issues/71

[openfhe_julia] update to version v0.3.6

---

P/Perple_X/build_tarballs.jl

CC @boriskaus @jadconnolly does this look correct?

[Perple_X ] update to version 7.1.9

---

.ci/Manifest.toml
H/Hwloc/build_tarballs.jl

Includes hwloc rebuild to validate the changes.
x-ref https://github.com/JuliaPackaging/BinaryBuilder.jl/pull/1346

Bump BinaryBuilder to include pkgconfig relocation change.

---

L/LLVMDowngrader/build_tarballs.jl

v0.4 supports `atomicrmw` and `cmpxchg` for https://github.com/JuliaConcurrent/Atomix.jl/pull/39

LLVM: Bump downgrader to v0.4.

---

O/oneAPI_Support/build_tarballs.jl

Binary counterpart of https://github.com/JuliaGPU/oneAPI.jl/pull/480. Removes the libOpenCL workaround we had in place, and also switches back to GCC now that the SYCL headers seem patched, and to avoid what looks like a Clang bug.
Specifically, with Clang we run into the same issue we had the previous time around:
```
ERROR: could not load library "/home/tim/Julia/src/Yggdrasil/O/oneAPI_Support/build/x86_64-linux-gnu/1wcmn0N3/x86_64-linux-gnu-libgfortran5-cxx11/destdir/lib/liboneapi_support.so"
/home/tim/Julia/src/Yggdrasil/O/oneAPI_Support/build/x86_64-linux-gnu/1wcmn0N3/x86_64-linux-gnu-libgfortran5-cxx11/destdir/lib/liboneapi_support.so: undefined symbol: _ZN6oneapi3mkl6lapack21gebrd_scratchpad_sizeIfTnPNS1_8internal9enable_ifIXsr5is_fpIT_EE5valueEvE4typeELPv0EEElRN4sycl3_V15queueElll …
```

oneAPI: Bump to v2025.0.0

---

L/libtakum/build_tarballs.jl

This release makes the *_pi_times() functions more precise, fixes a bug for 0^a with a<0, overhauls the unit tests to use random sampling and fixes a problem with the tie-rounding.
There is also some code refactoring and removal of internal data structures in takum.h. Some inlined header functions are properly implemented such that they can be used by non-C/C++ FFI library consumers.

[libtakum] Update to v0.5.1

---

S/SPIRV_LLVM_Translator/SPIRV_LLVM_Translator@16/build_tarballs.jl
S/SPIRV_LLVM_Translator/SPIRV_LLVM_Translator@17/build_tarballs.jl
S/SPIRV_LLVM_Translator/SPIRV_LLVM_Translator@18/build_tarballs.jl
S/SPIRV_LLVM_Translator/SPIRV_LLVM_Translator@19/build_tarballs.jl
S/SPIRV_LLVM_Translator_unified/build_tarballs.jl

This is also a build to prime the worker caches, as we'll be using the new version of `julia-buildkite-plugin` now which performs some cleanup that's expected to take a significant time the first time it executes. (If it keeps being problematic we'll move away from ZFS again.)

Bump SPIRV-LLVM Translator.

---

C/CUDA/CUDA_Runtime/build_10.2.jl
C/CUDA/CUDA_Runtime/build_tarballs.jl

Notably, `libnvrtc`.
This brings CUDA_Runtime for CUDA 10.2 in sync with CUDA 11.4 wrt. products included in the JLL.
As before:
* `libcublasLt` is available for the Linux platforms.
* `libcusolverMg` is only available for `x86_64-linux-gnu`.

[CUDA_Runtime] Added omitted libraries for CUDA 10.2

---

L/libcxxwrap_julia/build_tarballs.jl

This fixes some issues with the STL wrappings and allows simplification of the OpenCV patch.
Breaks binary compatibility, hence the bump to 0.14.

[libcxxwrap-julia] Version 0.14.0

---

P/Pythia8_cxxwrap/build_tarballs.jl

Fix for a couple of minor issues in wrapper code
- Removed Pythia8::Hist::operator+(double) while waiting for [CxxWrap issue 458](https://github.com/JuliaInterop/CxxWrap.jl/issues/458)
- Do not export `cd` name to avoid warnings

[Pythia8-cxxwrap] Patched wrapper code

---

M/MicrosoftMPI/build_tarballs.jl

Because MPICH is now compiled with GCC5, we also need to regenerate the `*.mod` files for Fortran with `MicrosoftMPI`.
Otherwise we have this error:
```shell
[16:57:41]    use mpi
[16:57:41]       1
[16:57:41] Fatal Error: Cannot read module file ‘mpi.mod’ opened at (1), because it was created by a different version of GNU Fortran
```
when we compile a Fortran that relies on MPICH / MicrosoftMPI + `libgfortran3`.
Related PR: https://github.com/JuliaPackaging/Yggdrasil/pull/8609

[MicrosoftMPI] Use GCC5 for ligbfortran3 architectures

---

L/libzip/build_tarballs.jl

- New version 1.11.2
- Switch from GnuTLS to OpenSSL (preferred by libzip)

libzip: New version 1.11.2

---

S/SuiteSparse/CXSparse/build_tarballs.jl

We need to build CXSparse for every release SuiteSparse that is in Julia. Julia 1.10 is not straightforward because it uses SuiteSparse 7.2 which had the old build system.

[CXSparse 4.4.0] Build for SuiteSparse 7.7.0 for Julia 1.11

---

S/Singular/build_tarballs.jl

This reverts PRs #9811, #9840, #9846, #9851. (i.e. everything since last Friday).
Therefore I expect it to resolve https://github.com/oscar-system/Oscar.jl/issues/4341 that started happening after #9811 (but no idea how to test that locally). This would be the fastest way to get green OSCAR CI again that I can think of. The "real fixes" can be worked on afterwards, maybe in a minor version bump to not have it automatically downstream.
ping @hannes14 @fingolfin

[Singular] Revert recent changes due to downstream breakage

---

S/Singular/build_tarballs.jl

For reference, `Singular.jl` currently has this compat entry `Singular_jll = "~404.000.606"` which this PR should produce version `404.001.700`.
This way the current Singular.jl release will not pick it up giving us time to adjust and release libsingular_julia_jll and then Singular.jl and then finally Oscar.jl (via  PR that changes the compat entry in Project.toml also adjusts the doctests).
ping @hannes14 @thofma @benlorenz @lgoettgens 
Let's wait with merging this until *at least* https://github.com/JuliaRegistries/General/pull/120134 is merged. And it'd be great if someone double checks my logic above so we don't run into a brick wall right again.

[Singular] restore 4.4.0p7 but with minor version +1

---

X/XSLT/build_tarballs.jl

This takes inspiration from #9680 to raise the compatibility bound of the Libgpg_error_jll dependency to include a version that has the necessary FreeBSD support

[XSLT] Update dependency for freebsd-aarch64 support

---

S/SuiteSparse/CXSparse/build_tarballs.jl

CXSparse used to follow the SuiteSparse version numbering, and as a result had 5.x version numbers originally.
Now, since it is a separate package, we use the upstream version of CXSparse (rather than of SuiteSparse collection itself). As a result those are in the 4.x series.
We are also trying to make the CXSparse build independent of SuiteSparse, and as a result all the version numbers are being multiplied by 100 to bypass all the old versions. Hopefully this will be stable in the long run.

[SuiteSparse CXSparse] Bump versioning

---

M/MAGEMin/build_tarballs.jl

- Added extended metapelite database to account for CO2 and S
- Added option to select combination of solution phase for metapelite and metabasite database
- Added “light” option to save minimum output from MAGEMin_C calculations
- Added several pseudocompounds for metapelite to improve phase diagrams quality 
- Corrected mistake when saving endmember wt fraction and end member wt composition

MAGEMin v1.6.0

---

L/Libglvnd/build_tarballs.jl

~~More importantly, setup the `__EGL_VENDOR_LIBRARY_DIRS` environment variable on load to point to locations of system-installed descriptors of the available EGL providers. Without this environment variable, compile-time paths (e.g. `/workspace/destdir/share/glvnd/egl_vendor.d`) appropriate for the Yggdrasil build environment will be used instead, which generally won't work when used by a user.~~
See also https://github.com/NVIDIA/libglvnd/blob/v1.7.0/src/EGL/icd_enumeration.md
More importantly, patch the loader to not look for the `egl_vendors.d` directory inside the BinaryBuilders path environment, which otherwise prevents the EGL library from finding the user's system EGL configuration.

Update to libglvnd v1.7

---

F/FuzzifiED/build_tarballs.jl

`FuzzifiED_jll` provides the necessary Fortran library for the package `FuzzifiED`, hosted at [https://github.com/mankai-chow/FuzzifiED.jl](https://github.com/mankai-chow/FuzzifiED.jl). 
`FuzzifiED_jll` was originally hosted at [https://github.com/mankai-chow/FuzzifiED_jll.jl.git](https://github.com/mankai-chow/FuzzifiED_jll.jl.git) but it would be preferrable if it could be installed without having to specify the url.
The package `FuzzifiED` is designed to do exact diagonalisation (ED) calculations on the fuzzy sphere, and also facilitates the DMRG calculations by ITensors. It can also be used for generic fermion models.

New Recipe: FuzzifiED v0.10.1

---

X/Xorg_libxcb/build_tarballs.jl

In checking that the dependencies were properly built, it seems that the dependecy on XSLT_jll is unnecessary. The in-source `ChangeLog` file (which has more detail than the git-repo NEWS [1]) says that XSLT has been made optional since v1.10 in 2013, and the Arch Linux package [2] agrees in making it a build-only dependecy. See also [3] where it is mentioned that it's only used for generating HTML checks results.
[1] https://gitlab.freedesktop.org/xorg/lib/libxcb/-/blob/master/NEWS
[2] https://archlinux.org/packages/extra/x86_64/libxcb/
[3] https://bugs.freedesktop.org/show_bug.cgi?id=23863

[Xorg_libxcb] Rebuild for freebsd-aarch64

---

G/GSL/GSL@2/build_tarballs.jl
G/GSL/GSL@2/bundled/patches/0001-remove-unknown-ld-option.patch

Not sure if we want to remove this:
https://github.com/JuliaPackaging/Yggdrasil/blob/e504e3ece997c2977e71d1004749cbd2bb4f42ab/G/GSL/GSL%402/build_tarballs.jl#L20-L25
_GSL-2.8/configure_
```sh
case $host_os in
rhapsody* | darwin1.[012])
_lt_dar_allow_undefined='$wl-undefined ${wl}suppress' ;;
darwin1.*)
_lt_dar_allow_undefined='$wl-flat_namespace $wl-undefined ${wl}suppress' ;;
darwin*)
case $MACOSX_DEPLOYMENT_TARGET,$host in
10.[012],*|,*powerpc*-darwin[5-8]*)
_lt_dar_allow_undefined='$wl-flat_namespace $wl-undefined ${wl}suppress' ;;
*)
_lt_dar_allow_undefined='$wl-undefined ${wl}dynamic_lookup $wl-no_fixup_chains' ;;
esac
;;
```

[GSL] Update to 2.8

---

M/MAGEMin/build_tarballs.jl

- Added frac_M_vol, frac_F_vol and frac_S_vol output for MAGEMin_C
- Corrected wrong set of W's for spinel in the metapelite and metapelite extended database
- Added molar mass of CO2 for MAGEMin_C (which was leading to failed mpe bulk loading in the App)

MAGEMin v1.6.1

---

F/FuzzifiED/build_tarballs.jl

I notice that there are some issue with Arpack_jll v3.9 --- it cannot find link to the BLAS library, so I am forcing compatibility with only the lower versions.

New Version: FuzzifiED v0.10.5

---

L/LLVMDowngrader/build_tarballs.jl

Includes a change in phi emission to support global variable operands: https://github.com/JuliaGPU/llvm-downgrade/commit/6e7b850552b656046dfab0cabbf7b83b8f85681d

LLVM: Bump IR downgrader.

---

L/libzenohc/build_tarballs.jl

[libzenohc] Update to 1.0.0

---

L/libzenohc/build_tarballs.jl

Simple update to version 1.0.3, no build script changes required.

[libzenohc] Update to 1.0.3

---

G/GAP_lib/build_tarballs.jl

Switched to using the full release tarball: while this wastes some
bandwidth for transferring GAP packages we don't need, it simplifies
things overall.

[GAP_lib] Version 4.14.0

---

T/Torch/build_tarballs.jl
fancy_toys.jl

Updated Torch recipe
* Changed to provide lazy artifacts.
* Replaced CUDA_full sources with CUDA module dependencies (and similar for CUDA 11.3).
* Updated cuda-part of script accordingly.
* Added xcrun executable for macOS which can handle `--show-sdk-path`.
* Using LLVM v13 (on macOS, v17 has issues).
* Adding cuda="none" tag to non-CUDA platforms with matching CUDA platforms.
Added comment to fancy_toys.jl `should_build_platform`
`should_build_platform` returns true, e.g. for `"x86_64-linux-gnu-cxx11"` when `ARGS = ["x86_64-linux-gnu-cxx11-cuda+10.2"]`.
Added NVTX RuntimeDependency

[Torch] Updated recipe

---

C/catch22/build_tarballs.jl

Adds optimization flags, and generally cleans up the makefile, to resolve [this bug](https://discourse.julialang.org/t/julia-vs-python-performance-on-package-catch22-why-is-julia-slower-in-this-case-and-how-can-i-improve-it/117936/11)

Update to catch22-v0.5.0

---

L/libcxxwrap_julia/build_tarballs.jl

Contains the fixes from https://github.com/JuliaInterop/libcxxwrap-julia/pull/177
CC @fingolfin @benlorenz

[libcxxwrap-julia] Version 0.13.3

---

X/Xorg_xorgproto/build_tarballs.jl

At least 2021.4 is required to build libXfixes 6:
- https://gitlab.freedesktop.org/xorg/lib/libxfixes/-/issues/2
- https://lists.x.org/archives/xorg-announce/2021-April/003085.html
Required to update https://github.com/JuliaPackaging/Yggdrasil/pull/10011.

[Xorg_xorgproto] Bump version

---

O/OpenLDAPClient/build_tarballs.jl

Hi! Here’s a small update for OpenLDAPClient:
1. The package version has been updated to the current LTS 2.5.19, based on the information from the [OpenLDAP download page](https://www.openldap.org/software/download/)
2. The OpenSSL dependency version has been updated to 3.0.15, which is more compatible with other packages and allowed starting from 2.5.14. Relevant references - [bug tracker](https://bugs.openldap.org/show_bug.cgi?id=10030#c1) and 
[implementation](https://git.openldap.org/openldap/openldap/-/merge_requests/489#ee3f73f86d0c13e4ac673288bb586615f8ef66c2)

upgrade to latest LTS v2.5.19 and set OpenSSL to v3.0.15

---

L/Libffi/build_tarballs.jl
L/Libffi/bundled/patches/0001-libdir-no-touchy.patch
L/Libffi/bundled/patches/0002-aarch64-llvm18.patch

As discussed here: https://github.com/JuliaPackaging/Yggdrasil/pull/10006#discussion_r1885031567
This reverts the following commits:
- "[Libffi] Rebuild for freebsd-aarch64 (#9909)":           670483cc247dba8d14365ff8c001253ca550988d
- "Libffi: Build for aarch64-freebsd (#9782)":              f66e34e1a1469b79237ede7ec283b4460b9e08b3
- "Libffi: New version 3.4.6 (#8275)":                      ff6c5543a8362e0f64c1e215df971d068ca56512
- "[Libffi] Upgrade to v3.4.4 (#5834)":                     cca8463eb26fd4acc357c6cd9f06a7cb1105224d
- ~~"libffi: Stop messing with the install diretory (#3906)": 7629d04b17d885309dd15bcb96e7bc990695a7dd~~
Libffi has a more interesting commit history than Expat so I opted to revert all the commits newer than the change to 3.2.2 to be on the safe side. …

[Libffi] Temporary revert to 3.2.2 to build for aarch64-freebsd

---

Z/zbc2014/build_tarballs.jl

Added build_tarball.jl for Zilany, Bruce, and Carney (2014) auditory-nerve model C source code. The script builds `libzbc2014`, a shared library for Julia packages to provide access to the model code.

[ZBC2014] New build recipe for ZBC2014

---

S/snappy/build_tarballs.jl

libsnappy does not need any dependencies. The dependencies are only used for the `snappy_test_tool` binary to compare performance with other compression libraries, but this binary is not being built.

[snappy] Remove unused dependencies

---

G/GLFW/build_tarballs.jl

If I understand the build failure correctly, this is required by https://github.com/JuliaPackaging/Yggdrasil/pull/9810.

[GLFW] Bump to build on aarch64-freebsd

---

A/Arrow/build_tarballs.jl
A/Arrow/bundled/patches/windows-zstd.patch

Arrow: Build with Zstd support

---

L/llama_cpp/build_tarballs.jl

This PR concludes this work: https://github.com/JuliaPackaging/Yggdrasil/pull/10059
It did not increment the fake version (it got tagged as 16+1).
This PR increments the version to v17, inline with the version tracker in the comments.

llama_cpp: Update to tag b4371 - tag as v17

---

G/GDAL/build_tarballs.jl

Removed by mistake, see https://github.com/JuliaPackaging/Yggdrasil/pull/10018#issuecomment-2559312502. Last version is not yet registered so I'm not bumping the version.

[GDAL] Add libcurl compat back

---

0_RootFS/Rootfs/bundled/testsuite/fortran/hello_world/Makefile

Ref: https://github.com/JuliaPackaging/BinaryBuilder.jl/pull/1357#issuecomment-2561141450.

[RootFS] Do not link to libquadmath in RISC-V Fortran tests

---

.ci/Manifest.toml
.ci/Project.toml
E/Enzyme/build_tarballs.jl

We're seemingly hitting https://github.com/tcnksm/ghr/issues/163, let's downgrade `ghr` to v0.14 which has served us well so far.  CC: @wsmoses.

[CI] Downgrade `ghr` to v0.14 and rebuild Enzyme

---

.ci/Manifest.toml

Update Manifest to get new versions of BinaryBuilder and BinaryBuilderBase to get the new Rust/Go versioning features.

[CI] Update Manifest

---

U/utf8proc/build_tarballs.jl

Updates utf8proc to 2.10, which adds support for Unicode 16.
See also https://github.com/JuliaLang/julia/pull/56925
cc @eschnett

update utf8proc to 2.10

---

X/x265/build_tarballs.jl
X/x265/bundled/patches/neon.patch

x265 builds for multiple architectures, using `-march` and `-mcpu` options, and then dispatches at run time. To support that, we need to
- Disable the checks for `-march` and `-mcpu` in the compiler wrappers
- Don't set `-march` or `-mcpu` in the compiler wrappers
We still disable `-march=native` and `-mpcu=native`.

x265: New version 4.1

---

L/LibGit2/build_tarballs.jl

New version: https://github.com/libgit2/libgit2/releases/tag/v1.9.0

LibGit2: New version 1.9.0

---

M/mmtk_julia/build_tarballs.jl

Adding a recipe to build the [mmtk-julia](https://github.com/mmtk/mmtk-julia/tree/master) binding, which should enable building Julia using [MMTk](https://www.mmtk.io).

New Recipe: mmtk_julia v0.30.2

---

O/OpenLibm/build_tarballs.jl

Regressions were accidentally introduced in 0.8.4 such that Julia could no longer build on FreeBSD AArch64. This release is quite small, containing only CI changes and fixes for the aforementioned regressions.

[OpenLibm] Update to 0.8.5

---

F/FlowCutterPACE17/build_tarballs.jl

Set `julia_compat = 1.6` so that binaries will be built for Apple silicon.

FlowCutterPACE17: Apple silicon support

---

L/libCppInterOp/build_tarballs.jl
L/libCppInterOp/bundled/patches/cmake.patch
L/libCppInterOp/bundled/patches/windows.patch

- bump source version to v1.5.0
- switch the source back to https://github.com/compiler-research/CppInterOp

libCppInterOp: Upgrade to v1.5.0

---

L/Libiconv/build_tarballs.jl

Let's see if this also works on RISCV.

[libiconv] Upgrade to 1.18

---

D/Dierckx/build_tarballs.jl

People have reported issues with the new
version (https://github.com/JuliaMath/Dierckx.jl/issues/98, https://github.com/JuliaMath/Dierckx.jl/issues/99) but no one tried to debug it. At least this should give users a more usable version for some time.
Fix #10266, fix https://github.com/JuliaMath/Dierckx.jl/issues/98.

[Dierckx] New version but building old upstream version

---

R/Reactant/build_tarballs.jl

Ref: https://github.com/EnzymeAD/Reactant.jl/issues/526.

[Reactant] Check CUDA version number in platform augmentation

---

M/mmtk_julia/build_tarballs.jl

Adding header files to final artefact, so that they can be imported when building Julia.

Adding mmtk-core header files

---

R/rsync/build_tarballs.jl

This is a security update https://kb.cert.org/vuls/id/952657.

rsync: New version 3.4.0

---

M/mmtk_julia/build_tarballs.jl

By default, the binding does a moving build, but we currently do not support moving objects in Julia. This change makes sure we build and use non-moving Immix instead.

[mmtk_julia] Set the recipe to do a non-moving build of mmtk-julia

---

M/MAGEMin/build_tarballs.jl

- Deactivated pure endmembers swap for epidote as this was leading to mistakenly stabilizing epidote outside the feasible domain. This results in significant improvement of the phase diagram for hydrous systems at low pressure and low temperature conditions for metapelite, metabasite and igneous database.
- Corrected phase_info() function that was displaying wrong phase names for pure phases

MAGEMin v1.6.5

---

I/ITK/build_tarballs.jl

While working on the upstream packages, specifically for the windows platforms, 
I carefully anaylsed the successful PR from last year, and realised the following lines were ommitted for a crucial library : 
```
cp $prefix/lib/libitkminc2-5.3.dll $prefix/bin
cp $prefix/lib/libitkminc2-5.3.dll.a $prefix/bin
```
Which are hereby added in this PR .

[ITK-v5.3.1] ommision of itk minc lib copying resulted in upstream errors

---

L/libharu/build_tarballs.jl

add a pdf-generating library libharu to the julia JLL.
Linux x86_64 glibc only.

New Recipe: libharu v2.4.4

---

G/GAP_pkg/common.jl

Logically the code in these packages only depends on the GAP kernel ABI, and hence GAP_jll, but not on the library code in GAP_lib_jll. Decoupling these make it easier to perform various upgrades. See also #10309 for some background.
This changes has no effect yet, but the next time we update any of the GAP_pkg_* JLLs we will see the benefit.
CC @lgoettgens @ThomasBreuer

[GAP_pkg_*] change GAP_lib_jll to a BuildDependency

---

L/LLVMLibcxx/build_tarballs.jl

For the time being this is only meant to be used as a build-time dependency for some packages which require libc++ header files (e.g. when compiling certain C++ code with clang).

[LLVMLibCxx] New package

---

P/pprof/build_tarballs.jl

Updates to the most recent `pprof` commit which includes both flamegraph and flamegraph2.
I bumped the version to `2.0.0`, since we are introducing a completely new feature. Reviews on this particular point are welcome.
CC: @NHDaly.

bump pprof to a commit which includes both flamegraph and flamegraph2

---

L/libzenohc/build_tarballs.jl

Simple update to version 1.1.1, no build script changes required.

[libzenohc] Update to 1.1.1

---

.ci/Manifest.toml
R/Reactant/build_tarballs.jl

This goes together with https://github.com/EnzymeAD/Reactant.jl/pull/616, but not quite ready yet because a bunch of things are failing still.

[Reactant] Cleanup the recipe

---

M/mmtk_julia/build_tarballs.jl

While Julia only supports building with MMTk using non-moving Immix, this PR enables selecting different binaries depending on each of the possible settings currently supported by the binding itself (i.e. moving x non-moving, Immix x StickyImmix, debug x release builds).
The idea is that depending on the setting specified when building Julia, it should obtain the particular version of the binary built here.

[mmtk_julia] Adding all supported builds of the binding

---

R/Reactant/build_tarballs.jl
R/Reactant/platform_augmentation.jl

This is only to save my progress along the way, nothing works at the moment.

[Reactant] Build for aarch64-linux with CUDA

---

F/Faiss/Faiss/build_tarballs.jl
F/Faiss/Faiss_CUDA/build_tarballs.jl
F/Faiss/bundled/patches/faiss-cmake-mkl-optional.patch
F/Faiss/common.jl

Due to issue with linking with MKL: https://github.com/JuliaPackaging/Yggdrasil/pull/8572#issuecomment-2614600730
Also, removes the need to build with a newer GCC (than v7) wrt. OpenBLAS on PowerPC64LE.

[Faiss] Replaced MKL and OpenBLAS with libblastrampoline

---

P/Powsybl/build_tarballs.jl

* Support aarch64 macos build for powsybl.jl
* Map more features from powsybl-cpp, such as network saving
* Bugfixes

[Powsybl] Release 0.2.0

---

G/GAP_pkg/GAP_pkg_browse/build_tarballs.jl
G/GAP_pkg/GAP_pkg_cddinterface/build_tarballs.jl
G/GAP_pkg/GAP_pkg_crypting/build_tarballs.jl
G/GAP_pkg/GAP_pkg_curlinterface/build_tarballs.jl
G/GAP_pkg/GAP_pkg_cvec/build_tarballs.jl
G/GAP_pkg/GAP_pkg_datastructures/build_tarballs.jl
G/GAP_pkg/GAP_pkg_deepthought/build_tarballs.jl
G/GAP_pkg/GAP_pkg_digraphs/build_tarballs.jl
G/GAP_pkg/GAP_pkg_edim/build_tarballs.jl
G/GAP_pkg/GAP_pkg_ferret/build_tarballs.jl
G/GAP_pkg/GAP_pkg_float/build_tarballs.jl
G/GAP_pkg/GAP_pkg_gauss/build_tarballs.jl
G/GAP_pkg/GAP_pkg_io/build_tarballs.jl
G/GAP_pkg/GAP_pkg_json/build_tarballs.jl
G/GAP_pkg/GAP_pkg_juliainterface/build_tarballs.jl
G/GAP_pkg/GAP_pkg_normalizinterface/build_tarballs.jl
G/GAP_pkg/GAP_pkg_orb/build_tarballs.jl
G/GAP_pkg/GAP_pkg_profiling/build_tarballs.jl
G/GAP_pkg/GAP_pkg_semigroups/build_tarballs.jl
G/GAP_pkg/GAP_pkg_zeromqinterface/build_tarballs.jl
G/GAP_pkg/common.jl

... it is not actually needed for building the C/C++ code
of these packages.
No need to rebuild anything just now but good to have this
in place for the next update.

[GAP_pkg_*] omit gap_lib_version

---

L/libzenohc/build_tarballs.jl

Simple update to version 1.2.0, no build script changes required.

[libzenohc] Update to 1.2.0

---

R/Reactant/build_tarballs.jl
R/Reactant/platform_augmentation.jl

It turns out XLA doesn't like CUDA 12.3:
<https://github.com/openxla/xla/blob/0919d17b5e3de7d15f51fd89e190505cb22a88c4/xla/stream_executor/cuda/subprocess_compilation.cc#L218>.

[Reactant] Build with CUDA 12.4 instead of 12.3

---

L/libcxxwrap_julia/build_tarballs.jl

cc @barche @fingolfin @benlorenz

[libcxxwrap] Rebuild using latest libjulia (for 1.13-DEV)

---

C/CUDA/CUDNN@8/build_tarballs.jl

The diff from the most recent commit to package CUDNN v8, 8af09247b430da171d9a2096a150d980d7196db8, is minimal.
Required for #10418 - v8.9.5 seems to be the most recent redist CUDNN v8 with Jetson binaries, cf. https://developer.download.nvidia.com/compute/cudnn/redist/redistrib_8.9.5.json.

CUDA: Added CUDNN@8 with CUDNN v8.9.5

---

C/CUDA/CUDNN@8/build_tarballs.jl

The diff from the most recent commit to package CUDNN v8, 8af09247b430da171d9a2096a150d980d7196db8, is minimal.
Required for #10418.

[CUDNN] Changed CUDNN to package v8.9.6

---

C/CUDA/CUDNN@8/build_tarballs.jl

The diff from the most recent commit to package CUDNN v8, 8af09247b430da171d9a2096a150d980d7196db8, is minimal.
Required for #10418.

[CUDNN] Changed CUDNN to package v8.9.7

---

C/CImGuiPack/build_tarballs.jl

After #10437 was merged CI failed on Julia 1.13 and that caused registration to be blocked: https://buildkite.com/julialang/yggdrasil/builds/17275#_
But libcxxwrap is now built for 1.13 so the build should succeed: #10441.

[CImGuiPack] Bump to build for Julia 1.13

---

L/LLVM/LLVM_full@19/build_tarballs.jl
L/LLVM/LLVM_full_assert@19/build_tarballs.jl
L/LLVM/common.jl

Also switch clang back to v16 for compilation as that seems to be faster.

[LLVM] Bump to v19.1.7+0

---

T/TensorRT/build_cuda+11.jl
T/TensorRT/build_cuda+12.jl
T/TensorRT/build_tarballs.jl

v10.8.0 bumps the minium glibc version for Linux x86_64 from 2.17 to 2.28: https://docs.nvidia.com/deeplearning/tensorrt/archives/tensorrt-1070/release-notes/index.html#rel-10-7-0

[TensorRT] Changed to package v10.7.0

---

I/ITK/build_tarballs.jl

Hello, So after weeks of head butting, I finally realised the minc error is only and only resolved if we standalone copy the libitkminc2 dll files in the bin directory for windows platforms.
Hoping to get this merged, this is the last time , since i tested it and it works like a charm with the upstream package.
Also, changed the package version to ensure compat bounds.
I tried everything but the only solution for libitkminc2 error in Cmake configuration on windows was copying both the dll files within the 
$prefix/bin directory.

[ITK-v5.3.2] Finally fixed windows minc error

---

I/ITKIOWrapper/build_tarballs.jl
I/ITKIOWrapper/src/CMakeLists.txt
I/ITKIOWrapper/src/itklib.cpp

Backend Wrapper library that supports : 
-- Loading of NIfTI file formats
-- Loading of DICOM file formats
-- Provides spatial metadata
-- Provides voxel data 
-- Writes Nifti file formats
-- Writes Dicom file formats
-- Reorients to a default LPS orientation 
Supported on - Windows, Linux and Mac

[ITKIOWrapper-win-mac-v3.0.0] The holy grail for MedEye3d

---

S/SPIRV_LLVM_Backend/build_tarballs.jl
S/SPIRV_LLVM_Backend/bundled/patches/avoid_builtin_available.patch

To check if it's possible to move from https://github.com/KhronosGroup/SPIRV-LLVM-Translator to LLVM proper.
Doesn't need platform augmentations, because I'd like to simply use the latest version of the back-end possible. This works as long as we statically link `libLLVM`, but may still pose problems when there's IR incompatibilities that can't get auto-upgraded.
cc @vchuravy

Add recipe for the LLVM SPIR-V back-end.

---

S/SPIRV_Tools/build_tarballs.jl

Bumping to a release candidate is kinda sketchy, but 2024.3 has bugs that need solving. So it's either moving forwards to a relatively stable release candidate, or backporting a whole bunch of code.

SPIRV-Tools: Bump to 2024.4-rc2

---

M/MAGEMin/build_tarballs.jl

- Changed bound values for compositional variables from 1e-10 to 1e-6, which largely improves accuracy and performances (15% faster)
- Improved calculation results for extended metapelite database
- Increased maximum size of possible considered phases (max value was hit in some cases)
- Fixed NLopt version to 2.8.0 as more recent version leads to large variation in calculation results between platforms

MAGEMin v1.6.9

---

L/libzenohc/build_tarballs.jl

Simple update to version 1.2.1, no build script changes required.

 [libzenohc] Update to 1.2.1

---

C/CUDA/cuQuantum/build_tarballs.jl

Update to the latest stable release of cuQuantum. Include new library cuDensityMat.

cuQuantum: Bump to 24.11.0

---

A/ADIOS2/build_tarballs.jl
A/AMReX/build_tarballs.jl
C/CGNS/build_tarballs.jl
C/Compose/build_tarballs.jl
E/Exodus/build_tarballs.jl
G/GDAL/build_tarballs.jl
G/gmsh/build_tarballs.jl
H/HighFive/build_tarballs.jl
M/Matio/build_tarballs.jl
N/NetCDF/build_tarballs.jl
O/openPMD_api/build_tarballs.jl
S/SIRIUS/build_tarballs.jl
S/SZ/build_tarballs.jl
S/SZ3/build_tarballs.jl
T/TempestModel/build_tarballs.jl
T/TempestRemap/build_tarballs.jl

Reflect changes in <https://github.com/JuliaRegistries/General/pull/125412>. Ref:
<https://github.com/JuliaPackaging/Yggdrasil/pull/10347#issuecomment-2662923973>.

Restrict compat with `HDF5_jll` for packages using v1.14

---

V/very_nauty/build_tarballs.jl

update to the header file of the library so that bindings for it are easy to make on mac and windows, not only linux

very_nauty: new version 1.1.2

---

L/LLVM/LLVM_full@19/build_tarballs.jl
L/LLVM/LLVM_full_assert@19/build_tarballs.jl
L/LLVM/common.jl

Let's hope this is the last one. Backporting https://github.com/llvm/llvm-project/commit/ac217ee389d63124432e5e6890851a678f7a676b to llvm 20 looks like it will work fine, https://github.com/llvm/llvm-project/pull/128371, so not too worried that this is going to break PkgEval in horrible ways.

[LLVM_full] Bump to v19.1.7+1

---

G/GAP_lib/build_tarballs.jl
G/GAP_lib/bundled/patches/Allow-loading-of-extraperfect-files-from-all-root-dirs-5938.patch

This backports https://github.com/gap-system/gap/pull/5938 to enable further work on https://github.com/oscar-system/Oscar.jl/pull/4592.
cc @fingolfin

[GAP_lib] Backport extraperfect fix

---

G/GAP_lib/build_tarballs.jl

https://github.com/JuliaPackaging/Yggdrasil/pull/10611 again, with the hope that registration works now with https://github.com/JuliaPackaging/BinaryBuilder.jl/pull/1370 available.
cc @fingolfin @giordano

[GAP_lib] Backport extraperfect fix (again)

---

C/CompilerSupportLibraries/CompilerSupportLibraries@v1.3/build_tarballs.jl

This rebuilds CSL 1.3 to use the updated FreeBSD versions (13.4 on x86-64 and 14.1 on AArch64). Let me know if previous CSL versions should also be rebuilt, or if this requires a new version altogether rather than a rebuild.

[CSL@1.3] Increment patch version

---

G/GMP/GMP@6.3.0/build_tarballs.jl

I've observed odd behavior with GMP and MPFR (the latter more recently) on FreeBSD 14.1 AArch64 with binaries built for 13.2. Now that the FreeBSD version for AArch64 has been updated to 14.1, let's rebuild both GMP and MPFR to see whether oddities are resolved.

[GMP@6.3.0] Trigger a rebuild with updated PlatformSupport

---

M/MAGEMin/build_tarballs.jl

- Corrected trace-elements output
- Corrected legacy solver that was leading to unsatisfied bulk-rock composition in some cases
- Largely improved use of initial guess to compute phase diagrams

MAGEMin v1.7.1

---

I/ITK/build_tarballs.jl

Reflect changes in https://github.com/JuliaRegistries/General/pull/126111 Ref:
https://github.com/JuliaPackaging/Yggdrasil/pull/10347#issuecomment-2662923973.

Restrict compat with HDF5_jll for ITK_jll using v1.14 

---

platforms/mpi.jl

Update the default MPI compat entries and the architectures supported by each MPI implementation. Also disable riscv64 builds with MPI since they don't work yet with BinaryBuilder.

platforms/mpi.jl: Update compat and supported architectures

---

W/WrapIt/build_tarballs.jl

- Use of clang/LLVM introduced several issues with c++ code parsing (e.g. https://github.com/grasph/wrapit/issues/67). Change to release 13 solve the issues. 
- release 1.5.0 fixes issue https://github.com/JuliaInterop/CxxWrap.jl/issues/458, adds a unit test, and include test and examples in files installed by `cmake --install`.

Upgrade to wrapit 1.5.0

---

R/ROOT/build_tarballs.jl

bug fix in the recipe: OpenBLAS32_jll was mistyped  OpenBLAS32

[ROOT] Fix in dependencies: OpenBLAS32 -> OpenBLAS32_jll

---

H/HDF5/build_tarballs.jl

This only cleans up the build script. If this build succeeds, then we should merge these changes, but we don't need to release a new version. (Or should we?)

HDF5: Clean up build script

---

R/Reactant/build_tarballs.jl

x/ref https://github.com/EnzymeAD/Reactant.jl/pull/856
essentially we want future precompiled libs to find XLAExecuteSharded and friends, but not use our LLVM symbols [which conflict].
We are explicitly okay here for macos because of the filter. Linux does the right thing already
@avik-pal

Reactant 0.0.84

---

A/aws_c_http_jq/build_tarballs.jl

I have functionality implemented in a fork of aws-c-http that is [stalled upstream](https://github.com/awslabs/aws-c-http/pull/500). The maintainers haven't given a [strong signal](https://github.com/awslabs/aws-c-http/discussions/493#discussioncomment-11378308) that they'll even be open to accepting the functionality or continue to maintain the overall server-side support, so I'm proactively forking the library with the idea that one of two scenarios plays out:
1. My contribution remains stalled or even rejected as the maintainers want to remove support for server-side. In this case, HTTP.jl would want to depend on a fork that _keeps_ server-side support, so this fork would be used long-term (we'd continue to merge contributions from the main project in as it applied to client-side).
2. …

[aws_c_http_jq] Add aws_c_http_jq fork of aws_c_http recipe

---

T/tg/build_tarballs.jl

I reported the 32 bit build issue upstream and they released a patch version that should fix it.

[tg] Bump version to 0.7.3, build on 32 bit platforms

---

N/NetCDF/build_tarballs.jl

NetCFD 4.9.3 is API and ABI incompatible with 4.9.2. Bump the major version number.
See https://github.com/JuliaPackaging/Yggdrasil/pull/10636, https://github.com/JuliaRegistries/General/pull/126541, https://github.com/JuliaBinaryWrappers/NetCDF_jll.jl/commit/09ffe880302aea634969e39a965c5aab5f845ab9, https://github.com/Unidata/netcdf-c/pull/2743/files .

NetCDF: Bump major version due to ABI change

---

G/GEOS/build_tarballs.jl

Release notes https://github.com/libgeos/geos/releases/tag/3.13.1

[GEOS] Update to v3.13.1

---

N/neper/build_tarballs.jl

Running ``run(`$(neper()) -T -n 10`)`` fails with 
`dyld[7307]: Library not loaded: @rpath/libnlopt.0.dylib` using default installation, but solved by `add NLopt_jll@2.9` before loading `neper_jll`.
I'm not sure if this is the correct way to fix it, but from what I could find, 
the update from NLopt_jll from v2.9 to v2.10 renames, e.g., `libnlopt.so.0` to `libnlopt.so.1`: https://github.com/JuliaBinaryWrappers/NLopt_jll.jl/commit/28cc85df871ea6eaa5a8de90dfb7ee9858b322a5
Since I'm not sure how I should verify that this change is the correct, this PR needs to be verified by someone who knows - tagging those who have worked on this file: @fredrikekre @amontoison @kimauth
Also not sure why the compat bounds says no versions left, shouldn't this correspond to `[2, 2.10)`?

neper: Set NLopt compat bounds

---

N/nghttp2/common.jl
N/nghttp2/nghttp2@1.65/build_tarballs.jl

New version: https://github.com/nghttp2/nghttp2/releases/tag/v1.65.0

[nghttp2] Bump to 1.65.0

---

O/OpenBLAS/OpenBLASConsistentFPCSR@0.3.21/build_tarballs.jl
O/OpenBLAS/OpenBLASConsistentFPCSR@0.3.29/build_tarballs.jl
O/OpenBLAS/OpenBLASConsistentFPCSR@0.3.29/bundled/patches/10-disable-running-tests.patch
O/OpenBLAS/OpenBLASConsistentFPCSR@0.3.29/bundled/patches/30-openblas-ofast-power.patch
O/OpenBLAS/OpenBLASConsistentFPCSR@0.3.29/bundled/patches/50-openblas-winexit.patch
O/OpenBLAS/OpenBLASConsistentFPCSR@0.3.29/bundled/patches/70-Build-with-proper-aarch64-flags-on-Neoverse-Darwin.patch

Following @orkolorko's advice, see [#131](https://github.com/JuliaIntervals/IntervalLinearAlgebra.jl/issues/131)

[OpenBLASConsistentFPCSR] Set version to 0.3.22 and add support for aarch64

---

H/HDF4/build_tarballs.jl

The current HDF4 setup provides an include file `netcdf.h` which conflicts with the package `NetCDF_jll`. This PR
- configures HDF4 without NetCDF support to avoid this conflict
- we can in the future configure NetCDF to support HDF4 as container format (I think that's the right approach, HDF4 is more low-level in this case)
- add support for `sz` compression
- build for riscv64 architecture

HDF4: Build without NetCDF support

---

M/msolve/build_tarballs.jl

Bug fix release, esp. for segfaults when running msolve with info level 0 and using elimination orderings.

msolve - v0.7.5

---

A/aws_c_http_jq/build_tarballs.jl

This PR updates aws_c_http_jq to version 0.9.5. cc: @quinnj @Octogonapus

[aws_c_http_jq] Update to version 0.9.5

---

M/MAGEMin/build_tarballs.jl

- Dropping out support for MPI, which is never used with the Julia wrapper and was creating conflict with LaMEM.
- This new version will allow to easily call LaMEM and MAGEMin_C at the same time to compute stable phase equilibrium from passives tracers

MAGEMin 1.7.3

---

F/FLINT/build_tarballs.jl
F/FLINT/bundled/patches/Use-__ARM_ACLE-to-guard-inclusion-of-arm_acle.h.patch

This is completely orthogonal to our rebuilding efforts for FLINT's inverse deps for v3.2.0, but shouldn't complicate anything.
cc @fingolfin @thofma @Joel-Dahne

[FLINT] Bump to v3.2.1

---

L/libgpiod/build_tarballs.jl

This PR adds a build script libgpiod. Libgpiod is a library to manipulate the GPIO pin (primarily for a Raspberry Pi).
CC: @brgl @JakeZw

add libgpiod build script

---

G/Git/build_tarballs.jl

Except for 32-bit Windows. For that OS we ship 2.48.1.

Git: New version 2.49.0

---

O/OpenMPI/OpenMPI@5/build_tarballs.jl

This should address https://github.com/JuliaIO/HDF5.jl/issues/1191.

OpenMPI 5: Declare Fortran libraries

---

D/Deno/build_tarballs.jl

Updates to latest https://github.com/denoland/deno/releases/tag/v2.2.6.

[Deno] Update Deno_jll to 2.2.6

---

I/iso_codes/build_tarballs.jl

- Update the package to 4.17.
- Convert to a platform-independent package. The only content is JSON files.

iso_codes: New version 4.17

---

L/Lingeling/build_tarballs.jl

Removed the filter for apple. Not sure why I included it in the first place.
Does this need a version update? Upstream is still at 1.0.0 so changing it here would be kind of unfortunate ...

Lingeling: add apple

---

Q/qpOASES/build_tarballs.jl
Q/qpOASES/bundled/patches/mypatch.patch

I've adapted the build script to the version 3.2.2 of qpOASES and also build a second solver lib in which MUMPS is used as the underlying sparse solver to have the full functionality of QPOASES.

qpOASES: version 3.2.2 and MUMPS as sparse solver

---

A/armadillo/build_tarballs.jl

Following @imciner2's advice in #10927, here is a version bump for Armadillo that should hopefully make it available on RISC-V after merge.

Update Armadillo to 14.4.1

---

S/SPIRV_LLVM_Translator/SPIRV_LLVM_Translator@15/build_tarballs.jl
S/SPIRV_LLVM_Translator/SPIRV_LLVM_Translator@16/build_tarballs.jl
S/SPIRV_LLVM_Translator/SPIRV_LLVM_Translator@17/build_tarballs.jl
S/SPIRV_LLVM_Translator/SPIRV_LLVM_Translator@18/build_tarballs.jl
S/SPIRV_LLVM_Translator/SPIRV_LLVM_Translator@19/build_tarballs.jl
S/SPIRV_LLVM_Translator/common.jl

Simply [relaxing the compat](https://github.com/JuliaRegistries/General/pull/129041) wasn't enough, we also need to make sure we don't `dlopen` the library (which depends on LLVM).
@giordano This should be an ideal case of `[skip build]`; in combination I should do `[ci skip]` when merging, right?

SPIRV LLVM translator: set dont_dlopen=true.

---

L/libdmg_hfsplus/build_tarballs.jl

Libdmg-hfsplus offers open-source utilities for creating compressed dmg files, a de facto standard for MacOS application distribution. It can be used as a cross-platform alternative to `hdiutil`, which, to my understanding, [according to the thread](https://bugzilla.mozilla.org/show_bug.cgi?id=935237), is used by Mozilla to package Firefox in a Linux build environment something like:
```
mkisofs -D -V "Firefox test" -no-pad -r -apple -o firefox-uncompressed.dmg /tmp/bundle/
dmg dmg /build/obj-firefox-darwin/dist/firefox-uncompressed.dmg /build/obj-firefox-darwin/dist/firefox.dmg
```
Alternatively, one can preallocate a disk image and add files to it:
```
dd if=/dev/zero of=uncompressed.dmg bs=1M count=256
mkfs.hfsplus -v "Firefox 40.x" uncompressed.dmg
hfsplus attract.dmg addall stagedir …
```

[libdmg-hfsplus] new package

---

O/osslsigncode/build_tarballs.jl

Osslsigncode allows one to sign Windows binaries like `.exe` and `.dll`. It also contains functionality for signing MSI installers, and according to https://github.com/mtrojnar/osslsigncode/pull/277#issue-1771451905, it can also sign MSIX installers, which is relevant for the AppBundler project.

[osslsigncode] add builder

---

S/SPIRV_LLVM_Translator/build_tarballs.jl

PoCL's support for LLVM 20 is not perfect yet, so let's go back to LLVM 19 for the time being.

SPIRV Translator: Build for LLVM 19.

---

S/SPIRV_LLVM_Translator/build_tarballs.jl

I had switched to GCC 13 to silence a linker warning, but turns out that regresses compatibility.

SPIRV LLVM translator: Rebuild against GCC 10.

---

C/code_server/build_tarballs.jl

This will be useful for BB2, where I want to be able to launch a VSCode instance within the build environment for debugging tricky builds.

Add `code_server` prebuilt binaries

---

S/SPIRV_Headers/build_tarballs.jl

There's a problem with many SPIR-V JLLs though: Upstream versioning has recently been revamped, now tracking the SDK version for each component (like SPIRV-Headers). That means that for some JLLs, the version will go backwards, as is the case here...
@giordano Any suggestion on how to tackle this? Yank every version > 1.4.309 so that this one is the only one which should get installed?

SPIRV-Headers: Bump to SDK 1.4.309.

---

A/AppBundlerUtils/build_tarballs.jl

This is a trivial utility that is only useful in the context of the AppBundler package. The MacOS application bundle format requires that the main launcher is located at
```
Contents/MacOS/appname
```
as it needs to encode the whole application signature and hold corresponding entitlements. 
On MacOS, it is easy to compile it with `Clang_jll`; I wouldn’t need this binary product as I could make it in place. However, on Linux, where all the bundling toolchains are already available, I do have an issue with the MacOS SDK headers not being available. Retrieving them is possible, but that introduces another potential point of failure, which I would like to avoid. 
Hence, my solution is to package the launcher with BinaryBuilder and then retrieve it independently from the host platform as:
``` …
```

[AppBundlerUtils] new recipe

---

L/libCppInterOp/build_tarballs.jl
L/libCppInterOp/bundled/patches/cmake.patch

- update source to test https://github.com/compiler-research/CppInterOp/pull/553
- remove wasm link flags in the cmake patch

libCppInterOp: build v0.1.7

---

M/MAGEMin/build_tarballs.jl

- Corrected wrong memory access for ume database (leading to crash during memory deallocation)
- Added test for ume database to avoid such problem in the future

MAGEMin v1.7.5

---

O/OCaml/OCaml@5.3.0/build_tarballs.jl
O/OCaml/OCaml@5.3.0/bundled/patches/00001-ocaml-relative-libdir.patch

Locally I'm hitting:
```julia
┌ Warning: Minimum instruction set detected for lib/ocaml/stublibs/dllunixnat.dll is avx2, not x86_64 as desired.
└ @ BinaryBuilder.Auditor ~/.julia/packages/BinaryBuilder/gFhyp/src/Auditor.jl:358
```
If you know the appropriate `-mtune` or `CFLAGS`, I'll be happy to re-build to get a baseline-compatible binary

[OCaml] Add Windows / macOS pre-built binaries

---

O/OCaml/OCaml@5.3.0/build_tarballs.jl

The pattern matching that I had here assumed that the absolute paths were from BinaryBuilder, but that's no longer true.

[OCaml] Fix interpreter shebang for pre-built binaries

---

G/GASNet/GASNet_conduit_smp/build_tarballs.jl
G/GASNet/common.jl

there are still some things to properly configure, like:
- ~the `CROSS_HAVE_MMAP`, `CROSS_PAGESIZE`, `CROSS_STACK_GROWS_UP`, `CROSS_HAVE_X86_CMPXCHG16B`, `CROSS_HAVE_SHM_OPEN` env vars~ (needs better tuning but can be done later)
- ~~flags for debug mode~~ (not a priority)
- ~~fix for macOS~~ (fixed)
if this works correctly, i will add more conduits like the mpi and the ucx ones

[GASNet] Add GASNet smp conduit recipe

---

E/Exodus/build_tarballs.jl
E/Exodus/bundled/patches/windows-cmake-error.patch

This PR does the following
1. Updates the git source to point to a new version of libexodus
2. Updates the version number to 9.4.0
3. Adds cmake as a dependency since this version of libexodus requires cmake >= 3.22
4. Bumps preferred_gcc_version to 9 due to build failures in linux aarch64
5. A small patch to fix issues encountered in windows build.

[Exodus_jll] update build_tarballs.jl for new libexodus version 9.04

---

M/MAGEMin/build_tarballs.jl

- Fixes shear modulus calculation for slb database
- Fixes issue introduced in version 1.7.6 that was wrongfully outputting phases in mol% on a 1atom basis instead of mol%.
While double checking the output of MAGEMin with a reference software (Theriak-Domino), I realized that the unit displayed in the reference software were not the one used in the calculation. This discrepancy led to breaking MAGEMin in v1.7.6 and version v1.7.7 rolls back the changes...

MAGEMin v1.7.7

---

L/LLVM/LLVM_full@18/build_tarballs.jl
L/LLVM/LLVM_full@19/build_tarballs.jl
L/LLVM/LLVM_full@20/build_tarballs.jl
L/LLVM/LLVM_full_assert@18/build_tarballs.jl
L/LLVM/LLVM_full_assert@19/build_tarballs.jl
L/LLVM/LLVM_full_assert@20/build_tarballs.jl
L/LLVM/common.jl

This backports https://github.com/llvm/llvm-project/pull/139259 to the LLVM versions that are currently being used by Julia: 18 for Julia 1.12, 19 for nightly, and 20 for https://github.com/JuliaLang/julia/pull/58142. I didn't bother bumping LLVM 17, even though it's also affected, because it's not being used by any Julia release right now.

Trigger a build of LLVM 18/19/20 with an ORC fix.

---

S/SCIP/build_tarballs.jl

cc @matbesancon 
SCIP has long been segfaulting on Windows.
I rigged up an "interesting" CI job to help debug this in SCIP.jl: https://github.com/scipopt/SCIP.jl/pull/330
This PR is the result. Hopefully it fixes things.
I tried v11 and still got errors.

[SCIP] rebuild and hopefully fix for Windows

---

N/NodeJS/NodeJS_22/build_tarballs.jl

Adds a new recipe (with updated checksums) based on NodeJS_20_jll for Node 22.

New recipe: NodeJS_22_jll

---

A/aws_c_http_jq/build_tarballs.jl

This PR updates aws_c_http_jq to version 0.10.2. cc: @quinnj @Octogonapus

[aws_c_http_jq] Update to version 0.10.2

---

P/pocl/pocl@6/build_tarballs.jl
P/pocl/pocl@7/build_tarballs.jl
P/pocl/pocl@7/common.jl

PoCL: Regenerate wrapper with more `__init__` improvements

---

P/pocl/pocl@6/build_tarballs.jl

I did this in https://github.com/JuliaPackaging/Yggdrasil/pull/11193, but apparently one can't do a single wrapper regeneration for multiple packages or BB will get confused about the artifacts to download: https://buildkite.com/julialang/yggdrasil/builds/20261#0196ce95-011f-4246-89f8-64d405c9dff9
```
ERROR: LoadError: Incomplete JLL release!  Could not find tarball for i686-linux-gnu-cxx03-llvm_version+14
```
I think this is because PoCL 7 doesn't have an augmented platform anymore, but v6 has? Let's try bumping both separately.

PoCL: Rebuild wrapper for v6.

---

P/pocl/pocl@6/build_tarballs.jl
P/pocl/pocl@7/build_tarballs.jl
P/pocl/pocl@7/common.jl

I somehow failed doing a simple wrapper regeneration (#11193, #11194), so I guess we'll need yet another full rebuild. To make this a little less painful, I've reduced the number of platforms to build for so that we only build for those LLVM versions as found in Julia.

PoCL: Rebuild + reduce number of LLVM versions.

---

S/SCIP_PaPILO/build_tarballs.jl

In my effort to get https://github.com/JuliaPackaging/Yggdrasil/pull/11175 working, I bumped the dependency compat, but I didn't bump the version.
x-ref https://github.com/JuliaRegistries/General/pull/130943

[SCIP_PaPILO] bump version

---

S/SCIP/build_tarballs.jl

To stay in line with
https://github.com/JuliaPackaging/Yggdrasil/blob/3ee6b35bc25b7439c99928a9edb9b3463abc75b2/S/SCIP_PaPILO/build_tarballs.jl#L105

[SCIP] bump compat of boost_jll

---

P/pocl/pocl@7/build_tarballs.jl

Use of zstd was recently added to our LLVM build, so the PoCL library (which links statically against LLVM) needs to have Zstd_jll as a dependency.

PoCL 7: Add Zstd_jll dependency.

---

M/Makemsix/build_tarballs.jl

The `makemsix -pack` command fails on Windows with the following error:
```
Microsoft (R) makemsix version 1.7.241
Copyright (C) 2017 Microsoft.  All rights reserved.
Error: 0x80070057
LOG:
Invalid file name
Call failed in /workspace/srcdir/msix-packaging/src/msix/pack/AppxPackageWriter.cpp on line 159
```
This regression was introduced during a refactoring that removed a forced include. The missing `windows.h` header causes runtime issues when using the tool.
To resolve the error, I added the missing header by setting:
```bash
export CXXFLAGS="$CXXFLAGS -include windows.h"
```
This ensures the necessary Windows API definitions are available during compilation and resolves the runtime error.

[Makemsix] fix makemsix runtime error on windows

---

C/CFITSIO/build_tarballs.jl

The x86_64-linux-gnu GCC v4.8 toolchain was built with too old glibc.

[CFITSIO] Use GCC 5

---

S/SPIRV_LLVM_Translator/build_tarballs.jl
S/SPIRV_LLVM_Translator/bundled/patches/addllvm_hidden_l.patch
S/SPIRV_LLVM_Translator/bundled/patches/visibility.patch

Otherwise those symbols can end up being resolved to a different LLVM library, e.g., Julia's.
@giordano @gbaraldi: This is the same problem as happens with PoCL, and needs to be fixed in multiple recipes.
On Linux it suffices to use `-Wl,--exclude-libs,ALL`, macOS requires switching from `-l` to `-hidden-l` (altering semantics, which is annoying), and on Windows I think we don't need this at all since symbols need to be marked explicitly `dllexport`.

SPIRV LLVM Translator: Prevent leaking LLVM symbols by controlling visibility

---

S/SPIRV_LLVM_Translator/build_tarballs.jl

Transitive from LLVM, which is linked statically.

SPIRV LLVM Translator: Add Zstd dependency.

---

N/NCCL/build_tarballs.jl

Removes `ln -s ${CUDA_HOME}/lib ${CUDA_HOME}/lib64` which was causing issues in local builds that depend on NCCL

[NCCL] Remove Symlink to lib64

---

G/GALAHAD/build_tarballs.jl

With the new release of `CUTEst_jll.jl` (https://github.com/JuliaPackaging/Yggdrasil/pull/11328), it should fix the issue with the dependencies that are not dlopen'ed are runtime.
-> https://github.com/JuliaRegistries/General/pull/132057#issuecomment-2923558114

[GALAHAD] Upgrade to v5.2.2

---

G/GAP/build_tarballs.jl

Our nightly testsuite currently fails with segfaults like the following one:
```julia
[10949] signal 11 (2): Segmentation fault: 11
in expression starting at /Users/goettgen/julia/GAP.jl/test/runtests.jl:3
_platform_strlen at /usr/lib/system/libsystem_platform.dylib (unknown line)
Allocations: 3302178 (Pool: 3292810; Big: 9368); GC: 7
ERROR: Package GAP errored during testing (received signal: 11)
```
I hope that this gets fixed by rebuilding GAP_jll and GAP_pkg_juliainterfact_jll with the new libjulia. This PR does the first part for that.
cc @fingolfin

[GAP] Rebuild with latest libjulia

---

L/libsingular_julia/build_tarballs.jl

This is needed to get the libcxxwrap that was build against the new libjula in our dependency tree.
The PR to Singular.jl that bumps the libsingular_julia compat to `~0.48` should also bump the CxxWrap compat to `~0.17`.
cc @fingolfin

[libsingular_julia] Rebuild with libcxxwrap 0.14

---

P/pocl/pocl@7/build_tarballs.jl

Some part of the build hard-codes the path to SLEEF:
```
no such file or directory: '/opt/aarch64-linux-gnu/aarch64-linux-gnu/sys-root/usr/local/lib/libsleef.so'
```
Since we don't have vectorization on any other platform, let's just disable it for now.

PoCL: Disable SLEEF vectorization on ARM

---

I/ImageMagick/ImageMagick@7/build_tarballs.jl

Latest `Libtiff_jll` can still not be used with ImageMagick.jl, CI error message(s):
"The value of field_readcount and field_writecount must be greater than or equal to -3 and not zero.. `TIFFMergeFieldInfo' @ error/tiff.c/TIFFErrors/574"
This stems from [this libtiff issue](https://gitlab.com/libtiff/libtiff/-/issues/532#note_2134433038), which has been resolved [here](https://gitlab.com/libtiff/libtiff/-/merge_requests/668) and should be fixed in the next libtiff release.
Making separate PRs for `ImageMagick@6` & `ImageMagick@7` to avoid registration conflicts.

[ImageMagick@7] Revert Libtiff_jll to ~4.5.1

---

G/GoogleCodeSearch/build_tarballs.jl

The go version and stdlib this was compiled with 5 years ago has several reported vulnerabilties. Since JuliaHub uses this jll, we get pinged on this in our docker image scans all the time.
I'm not sure of the best way to force a rebuild, but it doesn't build as it was.  I have to set julia_compat to 1.6 to have it build for the experimental platforms.
Is this the best way to do force a rebuild? Will this cause a released jll as `1.2.0+1` when it's merged?

[GoogleCodeSearch] update to force Go toolchain update

---

A/aws_c_sdkutils/build_tarballs.jl

This PR updates aws_c_sdkutils to version 0.2.4. cc: @quinnj @Octogonapus

[aws_c_sdkutils] Update to version 0.2.4

---

S/SPIRV_LLVM_Backend/build_tarballs.jl
S/SPIRV_LLVM_Backend/bundled/patches/fix_insertvalue.patch

Backports https://github.com/llvm/llvm-project/pull/143131

SPIRV LLVM back-end: back-port a patch.

---

G/GAP/build_tarballs.jl

Their support for libjulia was added in https://github.com/JuliaPackaging/Yggdrasil/pull/9667 and https://github.com/JuliaPackaging/Yggdrasil/pull/11384, respectively.
The two new builds work for me locally.
cc @fingolfin

[GAP] Enable aarch64-FreeBSD and riscv

---

L/LibCURL/LibCURL@8/build_tarballs.jl
L/LibCURL/common.jl

Re-build LibCURL 8.14.1 without using a MacOSX SDK. It appears that using the SDK was necessary only for version 8.13. As a long shot, this might solve the MacOSX build failure seen in https://github.com/JuliaLang/julia/pull/58708.

LibCURL: Build without MacOSX SDK

---

J/juliaup/build_tarballs.jl

Of course, it's a bit backwards to have this, because if you can install julia packages, you probably already have julia, but in https://github.com/Keno/ClaudeBox.jl I'm using JLLs for the non-standard purpose of putting together a container image in which I'd like to have juliaup available.

Add recipe for juliaup

---

L/LLVMExtra/build_tarballs.jl

I made a silly typo that only manifests in the LLVM 20 (Julia nightly) build...
Sorry for wasting compute here. I wish there was an easier way to mass-build these artifacts (they really don't take that long to build; only 30s, with 4m30 spent on sandbox set-up, audit, etc).

LLVM: Bump LLVMExtra again.

---

G/GAP/common.jl
G/GAP_pkg/GAP_pkg_browse/build_tarballs.jl
G/GAP_pkg/GAP_pkg_cddinterface/build_tarballs.jl
G/GAP_pkg/GAP_pkg_crypting/build_tarballs.jl
G/GAP_pkg/GAP_pkg_curlinterface/build_tarballs.jl
G/GAP_pkg/GAP_pkg_cvec/build_tarballs.jl
G/GAP_pkg/Project.toml
G/GAP_pkg/update.jl

Changes:
- Resolves the other TODO from https://github.com/JuliaPackaging/Yggdrasil/pull/11412.
- Applies some comments from https://github.com/JuliaPackaging/Yggdrasil/pull/11412.
- Extends the platform list for gap package jlls to include aarch64-freebsd and riscv (each that fails will have them filtered again in the respective recipe)
- Small changes to `update.jl`:
- Adapt the Project.toml to include all deps that are loaded, fixed executing it for me
- Fix the setting of `offset` when the upstream version changes. This is not relevant for anything in this PR, but I noticed that the current code is just wrong. Consider `upstream_version = v"1.2.3"; offset = v"1.0.0"` (so `version = v"101.200.300") and there is now a patch release of upstream. Resetting offset to `v"0.0.0"` would …

[GAP_pkg_*] Rebuild with extended platforms (part 1)

---

G/GAP_pkg/GAP_pkg_normalizinterface/build_tarballs.jl
G/GAP_pkg/GAP_pkg_orb/build_tarballs.jl
G/GAP_pkg/GAP_pkg_profiling/build_tarballs.jl
G/GAP_pkg/GAP_pkg_semigroups/build_tarballs.jl
G/GAP_pkg/GAP_pkg_zeromqinterface/build_tarballs.jl

Touches some recipes to rebuild with the changes from https://github.com/JuliaPackaging/Yggdrasil/pull/11455.
> Extends the platform list for gap package jlls to include aarch64-freebsd and riscv (each that fails will have them filtered again in the respective recipe)
cc @fingolfin

[GAP_pkg_*] Rebuild with extended platforms (part 4)

---

.gitignore
L/legate/build_tarballs.jl

This wraps the [legate ](https://github.com/nv-legate/legate) library from NVIDIA. For now it should work with CUDA 12.2 - 12.8. I still need to get things working for other architectures and expand the MPI ABI.

[New Package] Legate

---

O/OpenCL_Headers/build_tarballs.jl

They tagged a new version. Not a new release but would be better than using an arbitrary version in my opinion.

Update OpenCL headers

---

R/ROOT_julia/build_tarballs.jl

ROOT_julia_jll provides the CxxWrap shared library for the ROOT.jl package that provides a Julia interface to the C++ ROOT framework. It depends on the ROOT_jll package that bundles the ROOT framework c++ libraries.

Add recipe for ROOT_julia_jll

---

Q/Qt6Wayland/build_tarballs.jl

It seems the Qt CMakeLists.txt (mistakenly?) disables the freeBSD build entirely, resulting in a missing FileProduct error at registration time. Forcing the build by adapting the CMakeLists.txt reveals a new error related to missing Wayland support in Qt6Base on freeBSD, so fixing this will have to wait until we bump the Qt version.
I had missed this error on the first build, and in fact no artifacts except for the host musl build have been released for this JLL.

[Qt6Wayland] Disable freeBSD

---

F/Foldseek/build_tarballs.jl

This updates Foldseek for version 8 to version 10. Foldseek v10 also introduced GPU support; however, I think it is better to keep Foldseek_jll CPU only and add a different recipe for a Foldseek_GPU_jll package in the future.

Update Foldseek to v10

---

G/GettextRuntime/build_tarballs.jl

Fixes #11030
These are the parts of gettext that are useful at runtime. Unlike the current `Gettext_jll`, this package doesn't depend on `XML2_jll`.

[GettextRuntime] Make gettext-runtime its own package

---

M/msolve/build_tarballs.jl

- Improved matrix-vector product
- Improved lifting of rational parametrization
- Several memory improvements
- Changes interface of `initialize_basis()` which now enables connection to already existing hash tables

msolve v0.9.0

---

D/DuckDB/build_tarballs.jl

Should fix issues where extensions can no longer be found in DuckDB.jl

[DuckDB] Explicitly set compatible platform targets

---

G/Glib/build_tarballs.jl

Closes https://github.com/JuliaPackaging/Yggdrasil/issues/11498#issuecomment-2992104107.
I don't think Gettext is necessary at run time. I am building without, and there are no errors nor warnings, and the Gettext library is not referenced in the shared libraries.

Glib: Build with PCRE2 10.42

---

L/legate/build_tarballs.jl
L/legate/bundled/legion_redop.patch

Adds patch to legate_jll instead of the wrapper code.
The patch is applied to a dependency of legate that we do not wrap and do not have control over. It is applied after configuration which is responsible for cloning the source of the external library we patch. This also ensures the patch is shipped to all dependencies of legate_jll.

Add Patch to Legate

---

C/CUDA/CUDA_Compiler/build_11.jl
C/CUDA/CUDA_Compiler/build_12.jl
C/CUDA/CUDA_Compiler/build_tarballs.jl
C/CUDA/CUDA_Compiler/platform_augmentation.jl
C/CUDA/CUDA_Runtime/build_10.2.jl
C/CUDA/CUDA_Runtime/build_11.4.jl
C/CUDA/CUDA_Runtime/build_11.5.jl
C/CUDA/CUDA_Runtime/build_11.6.jl
C/CUDA/CUDA_Runtime/build_11.7.jl
C/CUDA/CUDA_Runtime/build_11.8.jl
C/CUDA/CUDA_Runtime/build_12.0.jl
C/CUDA/CUDA_Runtime/build_12.1.jl
C/CUDA/CUDA_Runtime/build_12.2.jl
C/CUDA/CUDA_Runtime/build_12.3.jl
C/CUDA/CUDA_Runtime/build_12.4.jl
C/CUDA/CUDA_Runtime/build_12.5.jl
C/CUDA/CUDA_Runtime/build_12.6.jl
C/CUDA/CUDA_Runtime/build_12.8.jl
C/CUDA/CUDA_Runtime/build_12.9.jl
C/CUDA/CUDA_Runtime/build_tarballs.jl

Another attempt at separating out the executable compiler bits from the CUDA runtime JLL, only keeping the libraries in there. This makes it possible to keep using the most recent compiler even if the user wants/needs to use an older or local runtime.
Previously attempted in https://github.com/JuliaPackaging/Yggdrasil/pull/8616, reverted in https://github.com/JuliaPackaging/Yggdrasil/pull/8670 because it turned out that `ptxas` from CUDA 12 generates code incompatible with an NVIDIA driver for CUDA 11. Fixed here by using a platform augmentation that inspects the driver version and selects an appropriate artifact.
Note that I only moved out the executable, and kept compiler libraries like `nvrtc` and `nvjitlink` in the runtime JLL. Ideally I wanted to move those out too, in order to use …

CUDA: Split compiler bits out in separate JLL.

---

L/Libxc/Libxc/build_tarballs.jl
L/Libxc/Libxc_GPU/build_tarballs.jl

Forgot to do that in https://github.com/JuliaPackaging/Yggdrasil/pull/11418, so the QE JLL is still not happy.

Libxc: Add fortran .so product

---

D/DuckDB/build_tarballs.jl

Follow-up fix from https://github.com/JuliaPackaging/Yggdrasil/pull/11522 - the targets are not `aarch64-apple-darwin` but `aarch64-apple-darwin20` causing the previous matcher to fail.

[DuckDB] Fix MacOS targets

---

G/GAP_pkg/GAP_pkg_juliainterface/build_tarballs.jl

I put this as upstream_version 0.14.1, since that will be the patch release of GAP.jl making this here available, see https://github.com/oscar-system/GAP.jl/pull/1200.
cc @fingolfin

[GAP_pkg_juliainterface] Rebuild for GAP.jl 0.14.x release

---

G/Gnuplot/build_tarballs.jl

For https://github.com/mbaz/Gaston.jl/pull/192.
~We need to figure out what to do when the qt terminal is unavailable on some platforms.~
I've added a fake executable in `libexec`, in order to determine `GNUPLOT_DRIVER_DIR` at runtime.

fix `gnuplot_qt` and `gnuplot_x11`

---

L/libheif/build_tarballs.jl

Needs https://github.com/JuliaPackaging/Yggdrasil/pull/11605.
Needed for https://github.com/JuliaPackaging/Yggdrasil/pull/11604.
Requires a `c++20` aware compiler, narrowed down to gcc 9 to also fix build errors.
TODO:
<details>
Hum, `macos`:
```
[12:33:06] /workspace/srcdir/libheif-1.20.1/tests/catch_amalgamated.cpp:7772:21: error: 'uncaught_exceptions' is unavailable: introduced in macOS 10.12
[12:33:06]  7772 |         return std::uncaught_exceptions() > 0;
[12:33:06]       |                     ^
[12:33:06] /opt/x86_64-apple-darwin14/x86_64-apple-darwin14/sys-root/usr/include/c++/v1/exception:131:63: note: 'uncaught_exceptions' has been explicitly marked unavailable here
[12:33:06]   131 | _LIBCPP_FUNC_VIS _LIBCPP_AVAILABILITY_UNCAUGHT_EXCEPTIONS int uncaught_exceptions() _NOEXCEPT; …
```

add `libheif`

---

C/CImGuiPack/build_tarballs.jl

This lets us get rid of all the CxxWrap/C++ stuff now that we use C bindings to `imgui_test_engine`. Building for https://github.com/JuliaImGui/cimgui-pack/pull/12.

[CImGuiPack] Update for cimgui_test_engine and v1.92

---

U/Uno/build_tarballs.jl

Uno v2.0.0 released on July 6, 2025 (documented [here](https://github.com/cvanaret/Uno/releases/tag/v2.0.0)).
cc @amontoison

[Uno] update to v2.0.0

---

G/Gnuplot/build_tarballs.jl

See https://github.com/mbaz/Gaston.jl/pull/194 -- test failures might indicate gnuplot was not built properly, because a couple of its dependencies were updated almost simultaneously.

Rebuild gnuplot

---

G/Git_LFS/build_tarballs.jl

Would like to hook this up with Git.jl so the git executable provided there calls the git-lfs we build here when we issue commands like ```run(`$(Git.git()) lfs ...`)``` -- not sure how to accomplish that yet ...

New recipe: git-lfs v3.7.0

---

L/LLVM/LLVM_full@20/build_tarballs.jl
L/LLVM/common.jl

This static library can be used by the Rust `clang-sys` crate, which is used by `bindgen`. I'm hoping to use this to resolve an issue where picking up the default (static) musl results in a nonfunctional `dlopen`, breaking `bindgen`; this can be resolved by linking `libclang` statically such that `dlopen` is not required. See https://github.com/KyleMayes/clang-sys?tab=readme-ov-file#static

LLVM: Also build `libclang.a`

---

G/GAP_pkg/GAP_pkg_juliainterface/build_tarballs.jl
G/GAP_pkg/common.jl

The above is the version that Oscar v1.4.1 on julia 1.12.0-rc1 resolves to. With this rebuild, Oscar v1.4.1 should load again on julia 1.12 rc.
This PR resets the recipe back to https://github.com/lgoettgens/Yggdrasil/blob/86f0a6ac4aec5c17a88b1e05d13075e7e16d093b/G/GAP_pkg/GAP_pkg_juliainterface/build_tarballs.jl, with the single change of an updated `libjulia_jll` version number.
Immediately after this is merged, this PR should be reverted with `[skip ci]` and `[skip build]` so that we have the latest recipe on the yggy master again.
cc @fingolfin

[GAP_pkg_juliainterface] Rebuild v0.1300.103 against new libjulia

---

L/libigc/build_tarballs.jl

Added 2 cherry-picks that are not included in v2.14.1 but needed to build NEO.

[oneAPI] libigc: add cherry-picks to v2.14.1

---

L/libigc/build_tarballs.jl

@maleadt I need this to link against the same libstd++ when building NEO.

oneAPI: Use GCC 11 for libigc

---

U/Uno/build_tarballs.jl

Uno v2.0.1 released on August 2nd, 2025 (documented [here](https://github.com/cvanaret/Uno/releases/tag/v2.0.1)).
cc @amontoison

[Uno] update to v2.0.1

---

L/LibCURL/LibCURL@8/build_tarballs.jl
L/LibCURL/common.jl

Since Zstd_jll is now a julia standard lib, there is no reason not to enable it in CURL (and in fact a source build currently enables it automatically). Ref https://github.com/JuliaLang/julia/issues/59171.

[LibCURL] Build with zstd support

---

G/GettextTiny/build_tarballs.jl

From https://github.com/sabotage-linux/gettext-tiny
This provides an alternative complete implementation of `msgfmt` that is easier to compile compared to `Gettext_jll`.

[GettextTiny] New recipe

---

S/SPIRV_LLVM_Translator/build_tarballs.jl
S/SPIRV_LLVM_Translator/bundled/addrspacecast_null.patch

Required after the codegen changes in JuliaLang/julia#58837
Upstream PR opened at KhronosGroup/SPIRV-LLVM-Translator#3305

[SPIRV_LLVM_TRANSLATOR] add patch for addrspacecast of null

---

.ci/Manifest.toml
.ci/Project.toml

This is a short-term fix for building recipes with libjulia as a dependency for `julia_version+1.13.0`, that currently error with 
```julia
ERROR: LoadError: KeyError: key UUID("3161d3a3-bdf6-5164-811a-617609db77b4") not found
```
e.g. in https://github.com/JuliaPackaging/Yggdrasil/pull/11832
cc @giordano

[CI] Downgrade HistoricalStdlibVersions to v2.0.2

---

N/nghttp2/common.jl
N/nghttp2/nghttp2@1.66/build_tarballs.jl

Released on 17 June 2025: https://github.com/nghttp2/nghttp2/releases/tag/v1.66.0

[nghttp2] Bump to 1.66.0

---

.github/workflows/component_owners.yml

We are going to be treating this system as just an advisory/notification system for letting relevant people know about changes to packages, they are not expected (or required to) do reviews on them if they don't want to (or have nothing to say).

Don't request reviews when doing component notifications

---

U/Uno/build_tarballs.jl

Uno v2.0.3 released on August 27, 2025 (documented [here](https://github.com/cvanaret/Uno/releases/tag/v2.0.3)).
cc @amontoison

[Uno] update to v2.0.3

---

C/CUDA/CUDA_Driver/init.jl

As it turns out, the forwards compatible driver can now be loaded across major versions. This is great! However, it also exposes us to inadvertently breaking older devices, as noticed in https://github.com/JuliaGPU/CUDA.jl/issues/2844. To prevent this, make CUDA_Driver_jll.jl's `__init__` even more complicated, by inspecting available devices (in a separate process, of course) and using that information to decide whether or not to load the forwards-compatible driver.
Regresses load time of CUDA_Driver_jll by about 30%. On some respectable systems I tested on, it's about 700ms now.
Closes https://github.com/JuliaGPU/CUDA.jl/issues/2844

CUDA: Consider device capabilities when loading a newer driver.

---

C/CUDA/CUDA_Driver/init.jl

Hopefully fixes the `EPIPE` seen in the wild.

CUDA: Make driver JLL's init asynchronously read subprocess output.

---

G/Git/build_tarballs.jl

This installer was made available "after warranty" to address a number of vulnerability advisories.
https://github.com/git-for-windows/git/releases/tag/v2.50.1.windows.1
Should this bump the patch version of the JLL itself?

Git: Update last Windows 32-bit version

---

A/AcousticsToolbox/build_tarballs.jl
A/AcousticsToolbox/bundled/licenses/LICENSE-orca.txt

The last PR (https://github.com/JuliaPackaging/Yggdrasil/pull/12013) was missing installation of LICENSE file into the tarball. This PR fixes that.

`AcousticsToolbox`: add license information

---

A/Aravis/build_tarballs.jl

On riscv64-linux-gnu, the following error occurs using the old recipe:
```
[00:45:36] ninja: subcommand failed
[00:45:36] /opt/riscv64-linux-gnu/bin/../lib/gcc/riscv64-linux-gnu/14.2.0/../../../../riscv64-linux-gnu/bin/ld.bfd: /usr/lib/libglib-2.0.so: error adding symbols: file in wrong format
[00:45:36] collect2: error: ld returned 1 exit status
```
Setting a more recent Glib_jll compat version fixes it.

[Aravis] update to 0.8.35

---

M/MAGEMin/build_tarballs.jl

- Corrected oversight introduced in v1.8.4 when using initial guess. This was leading to MAGEMin failing when using initial guess outside of PT diagram (PX, TX etc.) -> Added a new test to avoid this kind of problems in the future
- Added option to access and modify standard state properties of the end-members through the Julia wrapper.

MAGEMin v1.8.5

---

I/ImageMagick/ImageMagick@7/build_tarballs.jl

This PR adds `magick` as an ExecutableProduct since that is the main CLI in version 7, all other executables are symbolic links to `magick`, and `convert` is explicitly deprecated in favor of `magick`.
```
julia> run(`$(ImageMagick_jll.imagemagick_convert()) --version`);
WARNING: The convert command is deprecated in IMv7, use "magick" instead of "convert" or "magick convert"
```

Add magick executable.

---

X/XGBoost/XGBoost/build_tarballs.jl
X/XGBoost/XGBoost_GPU/build_tarballs.jl
X/XGBoost/common.jl

This is a patch fix for #12048. For some reason, building from source on Mac OS systems doesn't seem to work with AppleClang, so instead I've set these systems to exclusively use the pre-built binaries from XGBoost itself. Any thoughts/suggestions welcome :slightly_smiling_face:

[XGBoost] Builds for Apple Systems and more CUDA platforms

---

C/Conduit/build_tarballs.jl

Re-build Conduit 0.9.5. The previous build failed to register because it wasn't properly augmented for MPI.

Conduit: Correct build

---

G/GAP_pkg/GAP_pkg_juliainterface/build_tarballs.jl

Having this makes our treehash job green again, and allows us to release a 0.15.3 patch release of GAP.jl before we flip the switch to gap 4.15.0.

[GAP_pkg_juliainterface] Rebuild with latest master

---

U/Uno/build_tarballs.jl

[Uno v2.2.0](https://github.com/cvanaret/Uno/releases/tag/v2.2.0) released on Sept 29, 2025.
cc @amontoison

[Uno] Upgrade to v2.2.0

---

L/liboqs/build_tarballs.jl

This PR adds [open-quantum-safe/liboqs](https://github.com/open-quantum-safe/liboqs), a C library for prototyping and experimenting with quantum-resistant cryptography. I'm making LibOQS.jl a wrapper for the liboqs.
Many of the configuration settings included in the script were made possible by leveraging ChatGPT's capabilities, enabling build compatibility across numerous platforms.

liboqs: New package

---

G/GAP_pkg/GAP_pkg_juliainterface/build_tarballs.jl
G/GAP_pkg/update.jl

[GAP_pkg_juliainterface] Rebuild with GAP 4.15.0

---

G/GAP_pkg/GAP_pkg_curlinterface/build_tarballs.jl

[GAP_pkg_curlinterface] Update to 2.4.2

---

G/GAP_pkg/GAP_pkg_profiling/build_tarballs.jl

[GAP_pkg_profiling] Update to 2.6.2

---

I/iceberg_rust_ffi/build_tarballs.jl

We're also including OpenSSL dependency, because iceberg_rust_ffi now depends on object_store_ffi, which also has this dependency.

Upgrade iceberg_rust_ffi

---

C/CUDA/CUDA_SDK@13.0/build_tarballs.jl
C/CUDA/CUDA_SDK_static@13.0/build_tarballs.jl
C/CUDA/common.jl

With CUDA 13, we need new headers from the package `cuda_crt` to generate the Julia wrappers for `CUDA.jl` or `CUDSS.jl`.

[CUDA] Add missing headers for CUDA 13

---

U/Uno/build_tarballs.jl

[Uno v2.2.1](https://github.com/cvanaret/Uno/releases/tag/v2.2.1) was released on Oct 8, 2025.
cc @amontoison @giordano

[Uno] Update to Uno v2.2.1
