L/libjulia/build_tarballs.jl
L/libjulia/common.jl

Based on [this comment](https://github.com/JuliaPackaging/Yggdrasil/pull/7006#issuecomment-1621283410) by @benlorenz 

[libjulia] further tweak list of Julia versions

---

G/GAP_pkg/GAP_pkg_juliainterface/build_tarballs.jl

[GAP_pkg_juliainterface] rebuild for updated libjulia

---

L/libpolymake_julia/build_tarballs.jl

also use `julia_versions` from `L/libjulia/common.jl`

[libpolymake_julia] rebuild for libjulia 1.11

---

L/LLVMExtra/build_tarballs.jl

For https://github.com/maleadt/LLVM.jl/pull/346

Bump LLVMExtra

---

C/ClustalO/build_tarballs.jl

[Clustal-Omega](http://www.clustal.org/omega/) v1.2.4 (built via the [GitHub](https://github.com/GSLBiotech/clustal-omega.git) source)

[ClustalO] add recipe

---

L/libmcfp/build_tarballs.jl

[libmcfp] Add new build script for libmcfp v1.2.4

---

L/libsais/build_tarballs.jl

[libsais](https://github.com/IlyaGrebnov/libsais) v2.7.3

[libsais] add recipe

---

L/libmcfp/build_tarballs.jl

To help with https://github.com/JuliaPackaging/Yggdrasil/pull/6998#issuecomment-1630744561

[libmcfp] Don't use AnyPlatform, installed cmake files discern between 32/64 bits

---

S/Sundials/Sundials@5/build_tarballs.jl
S/Sundials/bundled@5/patches/Sundials_NoKLUTest.patch
S/Sundials/bundled@5/patches/Sundials_NoLAPACKTest.patch

Attempt to build Sundials 5 with SuiteSparse 7.

[Sundials 5] Build Sundials v5.2 with SuiteSparse 7.2

---

M/MDLovoFit/build_tarballs.jl

* Package name: MDLovoFit
* Version: v20.0.4

Wizard recipe: MDLovoFit-v20.0.4

---

M/MDLovoFit/build_tarballs.jl

Create binaries to MDLovoFit to new version v20.1.0

MDLovoFit to v20.1.0

---

S/SIMDe/build_tarballs.jl

[SIMD Everywhere](https://github.com/simd-everywhere/simde.git) v0.7.6

[SIMDe] add recipe

---

S/STRIDE/build_tarballs.jl
S/Stride/build_tarballs.jl

- academic-only use license: https://github.com/MDAnalysis/stride/blob/master/LICENSE
cc: @lmiq

[STRIDE] Add build script for STRIDE v1.0.0

---

M/MDLovoFit/build_tarballs.jl

Update to minor bug fix release.

Update to MDLovoFit 20.1.1

---

F/FLINT/build_tarballs.jl
F/FLINT/bundled/patches/make_flint_great_again.patch

[FLINT] Backport critical bug

---

B/Bowtie/bowtie@2.5.1/build_tarballs.jl
B/Bowtie/common.jl

[Bowtie2](https://github.com/BenLangmead/bowtie2.git) v2.5.1

[Bowtie] add recipe

---

S/SPRAL/build_tarballs.jl

[SPRAL] Release 2023.07.04

---

I/IGLWrap/build_tarballs.jl

[IGLWrap] bump libIGL to 2.4.0

---

M/minify/build_tarballs.jl

[Minify (by tdewolff)](https://github.com/tdewolff/minify.git) v2.12.7

[minify] add recipe

---

L/LLVM/libLLVM@15/build_tarballs.jl

Hopefully the storage servers have caught up with the uploads already.

Rebuild LLVM packages.

---

O/OpenSSH/build_tarballs.jl

Also update Windows to 9.2.2.
Also build agains OpenSSL 3.

OpenSSH: Update to 9.3p2

---

S/Singular/build_tarballs.jl

update to 4.3.2-4 (Hilbert Series) @fingolfin

[Singular] update to 4.3.2-4 (Hilbert Series)

---

K/KMA/build_tarballs.jl

[k-mer alignment](https://bitbucket.org/genomicepidemiology/kma/src/master/) v1.3.21

[KMA] add recipe

---

L/libcrossterm/build_tarballs.jl

Automatic PR generated for https://github.com/kdheepak/libcrossterm

[libcrossterm] Bump to refs/tags/v0.4.0

---

P/Packmol/build_tarballs.jl

- Update packmol version to 20.14.2
- Change source of build to specific github commit

[packmol] Update version to 20.14.2

---

L/LibTracyClient/LibTracyClient@0.9.1/build_tarballs.jl

Resolves https://github.com/topolarity/Tracy.jl/issues/28 (for real)
cc @staticfloat

LibTracyClient: Use GCC >= 7

---

L/LibUV/build_tarballs.jl
M/MbedTLS/MbedTLS@2.28.2/build_tarballs.jl
O/OpenLibm/build_tarballs.jl

Sequel to https://github.com/JuliaPackaging/Yggdrasil/pull/7036. Working my way through Julia's binary dependencies starting at the bottom of the tree, doing 3 at a time.

Trigger new builds for openlibm, libuv, and mbedtls

---

D/dSFMT/build_tarballs.jl
P/p7zip/build_tarballs.jl

Rebuild dSFMT and p7zip

---

X/XGBoost/build_tarballs.jl

[Release notes](https://github.com/dmlc/xgboost/releases/tag/v1.7.6)

[xgboost] bump to v1.7.6

---

L/LLVM/LLVM_full@15/build_tarballs.jl
L/LLVM/LLVM_full_assert@15/build_tarballs.jl

Rebuild LLVM_full@15 and LLVM_full_assert@15

---

L/llama_cpp/build_tarballs.jl

- update to v0.0.13 (master-11f3ca0, 2023-07-29)
- use Metal on Apple Silicon for faster inference, fixes #7132
cc: @svilupp

[llama_cpp] Use Metal on Apple Silicon, update to v0.0.13 (master-11f3ca0, 2023-07-29)

---

H/HDF5/build_tarballs.jl

Update HDF5 C library to 1.14.1-2
CC: @eschnett , @simonbyrne , @musm

[HDF5] Update to HDF5 1.14.1

---

D/Dex/bundled/patches/03-group-support-oidc.patch

With this it will be possible to support groups in OIDC connector and added few important messages in the logs that will help debug on a production system.

[Dex]: Support groups in oidc ✨

---

U/unzip/build_tarballs.jl
U/unzip/bundled/patches/cr_to_xcr.patch

This represents `v6.0` with the two extra patch releases that Mark Adler has added on his branch for security purposes.

[unzip] Package `v6.0.2`

---

G/GMP/GMP@6.2.1/build_tarballs.jl
L/LibCURL/LibCURL@8/build_tarballs.jl

I feel like Julia didn't always have quite so many binary dependencies to update 🤔

Rebuild GMP, libgit2, and libcurl

---

K/Kokkos/build_tarballs.jl

Fix missing libraryproduct in kokkos

---

W/WaveFD/build_tarballs.jl

changes correspond to this PR: https://github.com/ChevronETC/WaveFD.jl/pull/40

new version of WaveFD

---

S/Singular/build_tarballs.jl

[Singular] update to 4.3.2-5

---

L/libsingular_julia/build_tarballs.jl

for Singular_jll 403.204.400
@fingolfin ,@ederc

[libsingular_julia] update to latest version

---

F/FFMPEG/FFMPEG/build_tarballs.jl

Ref: https://discourse.julialang.org/t/error-in-precompiling-ffmpeg-and-cairo-and-cairomakie/102461

[FFMPEG] Build against older version of FreeType2

---

W/WaveFD/build_tarballs.jl

contains the following fix: https://github.com/ChevronETC/WaveFD.jl/pull/42.

[WaveFD] new version 0.6.1

---

G/GR/build_tarballs.jl

For reference, see
* https://github.com/jheinen/GR.jl/issues/525
* https://github.com/JuliaPackaging/Yggdrasil/pull/7164
* https://discourse.julialang.org/t/plots-jl-and-cairo-makie-not-compatible/102509
CC: @jheinen

[GR] Add explicit dependency on `FreeType2_jll`

---

M/MKL/build_tarballs.jl

[MKL] Version 2023.2.0

---

L/LLVM/Clang@15/build_tarballs.jl
L/LLVM/LLVM@15/build_tarballs.jl

These depend on the rebuilt LLVM_full and libLLVM.

Rebuild LLVM and Clang 15

---

S/Singular/build_tarballs.jl

[Singular] update to 4.3.2-6Singular] update to 4.3.2-6 (syMres_with_map,syMinimzye_with_map)

[Singular] update to 4.3.2-6

---

O/OpenCV/build_tarballs.jl

Cf. https://github.com/JuliaImages/OpenCV.jl/issues/23

[OpenCV] Rebuild JLL for 1.10 compatibility

---

L/LibTracyClient/LibTracyClient@0.9.1/build_tarballs.jl
L/LibTracyClient/LibTracyClient@0.9.1/bundled/patches/libTracyClient-rr-nopl-seq.patch

Like #7225, but for the *other* copy of tracy in yggdrasil (sigh).

LibTracyClient: Also carry rr nopl patch

---

S/SCOTCH/build_tarballs.jl

[SCOTCH] Fix #6569

---

M/mrfDepth/build_tarballs.jl

Add the Fortran code from R package mrfDepth, cc: @jbytecode
Fix #7224

Add mrfDepth, fix #7224

---

H/hsa_rocr/common.jl
H/hsa_rocr/hsa_rocr@5.4.4/build_tarballs.jl
H/hsa_rocr/hsa_rocr@5.4.4/bundled/patches/musl-affinity.patch
H/hsa_rocr/hsa_rocr@5.4.4/bundled/patches/musl-clock-gettime.patch
H/hsa_rocr/hsa_rocr@5.4.4/bundled/patches/musl-pthread-rwlock.patch

Still need to figure out glibc issue with `CLOCK_BOOTTIME`...

[hsa_rocr] Add 5.4.4

---

S/Singular/build_tarballs.jl

update to 4.3.2-7: absoute primary decomposition, hilbert series for modules: @fingolfin

[Singular] update to 4.3.2-7

---

C/CUDA/CUDA_SDK@12.1/build_tarballs.jl
C/CUDA/CUDA_SDK_static@12.1/build_tarballs.jl

CUDA: Add SDK JLLs for v12.1.

---

C/CUDA/CUDA_SDK@11.4/build_tarballs.jl
C/CUDA/CUDA_SDK_static@11.4/build_tarballs.jl
C/CUDA/common.jl

CUDA: Add SDK JLLs for v11.4.

---

C/CUDA/CUDA_SDK@11.5/build_tarballs.jl
C/CUDA/CUDA_SDK_static@11.5/build_tarballs.jl

CUDA: Add SDK JLLs for v11.5.

---

C/CUDA/CUDA_SDK@11.6/build_tarballs.jl
C/CUDA/CUDA_SDK_static@11.6/build_tarballs.jl

CUDA: Add SDK JLLs for v11.6.

---

C/CUDA/CUDA_SDK@11.7/build_tarballs.jl
C/CUDA/CUDA_SDK_static@11.7/build_tarballs.jl

CUDA: Add SDK JLLs for v11.7.

---

C/CUDA/CUDA_SDK@11.8/build_tarballs.jl
C/CUDA/CUDA_SDK_static@11.8/build_tarballs.jl

CUDA: Add SDK JLLs for v11.8.

---

C/CUDA/CUDA_SDK@12.0/build_tarballs.jl
C/CUDA/CUDA_SDK_static@12.0/build_tarballs.jl

CUDA: Add SDK JLLs for v12.0.

---

H/HMMER/build_tarballs.jl

https://github.com/EddyRivasLab/hmmer/releases/tag/hmmer-3.4
This new version supports ARM platforms (Linux and MacOS).

[HMMER] Update to v3.4

---

U/umesimd/build_tarballs.jl

- **Name**: umesimd
- **Version**: 0.8.1 (6f72452743151b76ecb9ddf4dd696d263b45cb74)
- **Source**: https://github.com/edanor/umesimd.git
- **Language(s)**: C++
- **Build System**: CMake
- **Depends**: N/A
- **Depends (optional)**: N/A
- **Purpose**: Dependency for another package
- **Description**: "UME::SIMD A library for explicit simd vectorization."
Header-only library. Set to last merged commit

[umesimd] add recipe

---

C/CImGuiPack/build_tarballs.jl

The new src introduced breaking changes.

[CImGuiPack] Fix version

---

O/OpenPolicyAgent/build_tarballs.jl

New recipe for Open Policy Agent: https://github.com/open-policy-agent/opa

New Recipe: Open Policy Agent (OPA) v0.55.0

---

L/libpolars/build_tarballs.jl

The source is from https://github.com/pangoraw/polars.jl/tree/main/c-polars and will be used to power the Julia package at the same location.

[libpolars] Add libpolars

---

C/Coin-OR/Bonmin/build_tarballs.jl
C/Coin-OR/coin-or-common.jl

Changes made to build tarballs for Bonmin 1.8.9

[Bonmin] Update to 1.8.9

---

L/libsingular_julia/build_tarballs.jl

[libsingular_julia] new version 0.40.2

---

L/Luna/build_tarballs.jl
L/Luna/bundled/patches/fix_it.patch

Let's see whether this works...

[Luna] Update to v0.28.0

---

G/GAP/build_tarballs.jl

[GAP] rebuild with latest libjulia_jll

---

G/GAP_pkg/GAP_pkg_juliainterface/build_tarballs.jl

[GAP_pkg_juliainterface] rebuild with latest libjulia_jll

---

P/Pango/build_tarballs.jl
P/Pango/bundled/patches/dwrite.patch

I'm hoping this fixes some font issues on Windows in Gtk4.jl.

[Pango] update to 1.50.14

---

T/teensy_loader_cli/build_tarballs.jl

This depends on https://github.com/JuliaPackaging/Yggdrasil/pull/7320.
To any future people that want to bring this to non-linux systems - [read the Makefile](https://github.com/PaulStoffregen/teensy_loader_cli/blob/master/Makefile), and godspeed.

[teensy_loader_cli] Add teensy_loader_cli

---

F/Foldseek/build_tarballs.jl

https://github.com/steineggerlab/foldseek/releases/tag/8-ef4e960

[Foldseek] Update to v8

---

P/PRIMA/build_tarballs.jl

[PRIMA] add recipe

---

P/Perple_X/build_tarballs.jl

[Perple_X] version 7.1.3

---

B/Binaryen/build_tarballs.jl

Version bump for an upstream release.

Upgrade Binaryen to version_116

---

R/rure/build_tarballs.jl

This is the recipe for building the [c api of RUst's REgex engine](https://github.com/rust-lang/regex/tree/master/regex-capi)

[rure] add recipe

---

H/HIP/HIP@5.4.4/build_tarballs.jl
H/HIP/HIP@5.4.4/bundled/patches/improve-compilation-disable-tests.patch
H/HIP/HIP@5.4.4/bundled/patches/no-init-abort.patch
H/HIP/HIP@5.4.4/bundled/patches/register-tracer-callback-no-const.patch
H/HIP/common.jl

@amontoison I would appreciate a review!

[HIP] Add 5.4.4 (properly this time!)

---

X/Xorg_xcb_util_cursor/build_tarballs.jl

[Xorg_xcb_util_cursor] New package

---

E/EpollShim/build_tarballs.jl

Dependency for Wayland on FreeBSD

[epoll-shim] New package

---

P/PRIMA/build_tarballs.jl

[PRIMA] Upgrade to v0.7.1

---

G/gh_cli/build_tarballs.jl

Update gh cli to curent latest version 2.35.0

update gh cli

---

M/Matio/build_tarballs.jl

Try rebuilding matio

---

T/Trilinos/build_tarballs.jl
T/Trilinos/bundled/patches/freebsd.patch
T/Trilinos/bundled/patches/intrepid2sfinae.patch
T/Trilinos/bundled/patches/iossexplicit.patch
T/Trilinos/bundled/patches/mpi.patch
T/Trilinos/bundled/patches/msmpicompat.patch
T/Trilinos/bundled/patches/muslmallinfo.patch
T/Trilinos/bundled/patches/muslunistd.patch
T/Trilinos/bundled/patches/nohdf5.patch
T/Trilinos/bundled/patches/panzerhardcode.patch
T/Trilinos/bundled/patches/rusagecompat.patch
T/Trilinos/bundled/patches/seacasassertnuke.patch
T/Trilinos/bundled/patches/stkalignedalloc.patch
T/Trilinos/bundled/patches/stknolonglong.patch
T/Trilinos/bundled/patches/stktypename.patch
T/Trilinos/bundled/patches/stratikimosnotpetra.patch
T/Trilinos/bundled/patches/teuchoswinexport2.patch
T/Trilinos/bundled/patches/ulltemplate.patch
T/Trilinos/bundled/patches/winheadercase.patch
T/Trilinos/bundled/patches/winsigcompat.patch
T/Trilinos/bundled/patches/zoltan2time.patch
T/Trilinos/bundled/patches/ztmsmpicompat.patch
platforms/mpi.jl

Turns out just Teko isn't enough for charon (https://github.com/JuliaPackaging/Yggdrasil/pull/7383). Hopefully this should do it though.

Enable more trilinos packages

---

L/LibUnwind/LibUnwind@1.7.2/build_tarballs.jl
L/LibUnwind/LibUnwind@1.7.2/bundled/patches/libunwind-revert_prelink_unwind.patch

libunwind: revert problematic change for FreeBSD.

---

H/HiGHS/HiGHS/build_tarballs.jl
H/HiGHS/HiGHSstatic/build_tarballs.jl
H/HiGHS/highs_common.jl

[HiGHS] up version

---

M/MAGEMin/build_tarballs.jl

- Corrects bugs for MAGEMin_C Julia wrapper

MAGEMin v1.3.4

---

L/LibUnwind/LibUnwind@1.7.2/build_tarballs.jl

https://github.com/JuliaLang/julia/issues/51465

libunwind: revert problematic patch on all platforms

---

B/Binutils/build_tarballs.jl

Binutils: Build libiberty with -fPIC

---

L/libcxxwrap_julia/build_tarballs.jl

[libcxxwrap_julia] rebuild for Julia 1.10.0-beta3

---

S/SCIP/build_tarballs.jl

Trying to understand the error when merging the last SCIP PR

[SCIP] format to trigger build

---

G/GenICamRuntime/build_tarballs.jl

Not sure whether the binaries will work on musl.

Added GenICamRuntime recipe

---

C/CUDA/CUDA_Runtime/platform_augmentation.jl

Fixes https://github.com/JuliaGPU/CUDA.jl/issues/1877

CUDA_Runtime: Add an include dependency on the driver.

---

M/MAGEMin/build_tarballs.jl

- Added Metabasite database (Green et al., 2016)

MAGEMin v1.3.5

---

S/spglib/build_tarballs.jl

See https://github.com/spglib/spglib/releases/tag/v2.1.0

Update `spglib` to v2.1.0

---

0_RootFS/Rust/build_tarballs.jl

Companion PR to https://github.com/JuliaPackaging/BinaryBuilderBase.jl/pull/334

[0_RootFS] Update Rust to v1.73.0

---

V/ViennaRNA/build_tarballs.jl
V/ViennaRNA/bundled/patches/RNAlocmin-fix-clang.patch

https://github.com/ViennaRNA/ViennaRNA/releases/tag/v2.6.4

[ViennaRNA] Update to v2.6.4

---

B/Blosc2/build_tarballs.jl
B/Blosc2/bundled/patches/armv7l.patch

Blosc2: Support armv7l

---

C/CUDA/CUDA_Driver/init.jl

CUDA: Add a preference to disallow loading the compat driver.

---

C/CUDA/CUDA_Runtime/platform_augmentation.jl
L/libigc/build_tarballs.jl
N/NEO/build_tarballs.jl

TOML supports this, so we should.

Support actual bools for boolean preferences.

---

N/NEO/build_tarballs.jl

oneAPI: Bump NEO to 23.30.26918.

---

S/SuiteSparse/SuiteSparse@7/build_tarballs.jl
S/SuiteSparse/common.jl

[SuiteSparse] Update to suitesparse 7.3.0

---

S/Singular/build_tarballs.jl

[Singular] update to 4.3.2-10

---

L/libsingular_julia/build_tarballs.jl

[libsingular_julia] update Singular_julia_jll to 403.210.1000

---

L/LLVM/common.jl

Probably not worth a rebuild for

[LLVM] install cmake files

---

B/Blosc/build_tarballs.jl

[Blosc] Update to v1.21.5

---

Y/yaml_cpp/build_tarballs.jl

Follow-up for #7591 and #7599.

yaml_cpp: Updated to v0.8.0

---

G/Git/build_tarballs.jl

git 2.42.0

---

S/SuiteSparse/SuiteSparse_GPU@7/build_tarballs.jl

@maleadt Could you review this PR to make sure the updated GPU build is ok, in case anything needs to be changed to keep pace with the cuda ecosystem.
Also cc @rayegun

[SuiteSparse_GPU] Build GPU libraries for SuiteSparse 7.3

---

C/CALCEPH/build_tarballs.jl

Updating the library to the latest available version on the IMCCE website

[CALCEPH] Update to 3.5.3

---

S/SSW/build_tarballs.jl

- Name: SSW
- Version: v1.2.5 (c32f4c2b07df137a0fce72ec7c7e60474937a52e)
- Source: https://github.com/mengyao/Complete-Striped-Smith-Waterman-Library.git
- Language(s): C/C++
- Build System: Makefile
- Depends: Zlib (jll available: yes)
- Depends (optional): Java/Python (unused)
- Description: "An SIMD Smith-Waterman C/C++/Python/Java/R Library for Use in Genomic Applications"

[SSW] add recipe

---

C/CDE/build_tarballs.jl

Adding an executable binding for the [Chemistry Discovery Engine](https://github.com/HabershonLab/cde) (CDE)

CDE [new package]

---

O/oneAPI_Support_Headers/build_tarballs.jl

[oneAPI_Support_Headers] add recipe

---

S/SCS/build_tarballs.jl

x-ref https://github.com/JuliaPackaging/Yggdrasil/pull/7665

[SCS] update to v3.2.4

---

S/SCS_GPU/build_tarballs.jl

x-ref https://github.com/JuliaPackaging/Yggdrasil/pull/7665

[SCS_GPU] update to v3.2.4

---

S/SCS_MKL/build_tarballs.jl

x-ref https://github.com/JuliaPackaging/Yggdrasil/pull/7665
@kalmarek I've updated the MKL version. Is that okay?
We could also try building this on other platforms.

[SCS_MKL] update to v3.2.4

---

H/HandIsomorphism/build_tarballs.jl

* Package name: HandIsomorphism
* Version: v0.0.1

Wizard recipe: HandIsomorphism-v0.0.1

---

L/LLVMExtra/build_tarballs.jl

- This hopes to use https://github.com/JuliaPackaging/BinaryBuilder.jl/pull/1299

[LLVMExtra] Retrigger build to update stdlib compats

---

P/Perple_X/build_tarballs.jl

[Perple_X] version 7.1.4

---

S/SPRAL/build_tarballs.jl

[SPRAL] Upgrade to v2023.11.15

---

L/libminc/build_tarballs.jl

Added a recipe to build libminc

Added libminc

---

L/LLVM/Clang@16/build_tarballs.jl
L/LLVM/LLD@16/build_tarballs.jl
L/LLVM/LLVM@16/build_tarballs.jl
L/LLVM/MLIR@16/build_tarballs.jl
L/LLVM/common.jl

Build dependent libs and make the clang and lld install

---

L/libcxxwrap_julia/build_tarballs.jl

Mainly releasing now for compatibility fixes with Julia master.
CC @fingolfin @benlorenz

[libcxxwrap-julia] Version 0.11.2

---

A/armadillo/build_tarballs.jl
E/ensmallen/build_tarballs.jl
M/mlpack/build_tarballs.jl

mlpack -> 4.3.0
ensmallen -> 2.21.0
Armadillo -> 12.6.6
Hopefully everything will build correctly... let's find out!

Update Armadillo, ensmallen, and mlpack to latest stable versions.

---

C/CoolProp/build_tarballs.jl

ignore the commit msg, it is updating from 6.5.0 to 6.6.0

[CoolProp] update to 6.6.0

---

0_RootFS/Rootfs/build_tarballs.jl

https://github.com/JuliaPackaging/Yggdrasil/pull/7728#issuecomment-1830964109
Companion PR in BBB: https://github.com/JuliaPackaging/BinaryBuilderBase.jl/pull/354

[Rootfs] Restore the old version of patchelf

---

S/Singular/build_tarballs.jl

[Singular] update to 4.3.2-11

---

C/Cares/build_tarballs.jl

https://c-ares.org/changelog.html#1_23_0

[Cares] Update to v1.23.0

---

X/X13as/build_tarballs.jl
X/X13as/bundled/x13as_license.md

Add recipe for [X13-ARIMA-SEATS](https://www.census.gov/data/software/x13as.X-13ARIMA-SEATS.html#list-tab-635278563)  seasonal adjustment program.

New recipe: X13as

---

T/TropicalGemmC/build_tarballs.jl

Added support of CUDA v12.3.1, and have some update in the related C library.
I mistakenly closed the previous PR #7750, sorry about that.

[TropicalGemmC] new version 0.1.2

---

G/GTPSA/build_tarballs.jl

This recipe generates binaries for the gtpsa shared library wrapped by the GTPSA.jl package (https://github.com/bmad-sim/GTPSA.jl) presently in development.

New Recipe: GTPSA v1.0.0

---

P/Poppler/build_tarballs.jl

Closes https://github.com/JuliaPackaging/Yggdrasil/issues/7799.

Poppler: New version 23.12.0

---

Q/QuEST/build_tarballs.jl

* Package name: QuEST
* Version: v3.7.0

Wizard recipe: QuEST-v3.7.0

---

M/msolve/build_tarballs.jl

Bug fixes for
- prime handling in multi-modular setting
- normal form computations over finite fields

msolve-v0.6.2

---

N/NCCL/build_tarballs.jl

[NCCL] fix augment_platform_block

---

S/Singular/build_tarballs.jl

[Singular] update to 4.3.2-12

---

L/libsingular_julia/build_tarballs.jl

libsingular_julia for Singular_jll 403.212.1200

---

C/CUDA/CUDA_Runtime/build_10.2.jl
C/CUDA/CUDA_Runtime/build_tarballs.jl

CUDA_Runtime: Restore v10.2

---

S/Singular/build_tarballs.jl

[Singular] update prune_and_map

---

S/Singular/build_tarballs.jl

[Singular] prune_with_map, map ideals with 0 generators

---

M/MPItrampoline/build_tarballs.jl

Closes https://github.com/JuliaPackaging/Yggdrasil/issues/7420.

MPItrampoline: Correct compilers in compiler wrappers

---

C/CUDA/cuQuantum/build_tarballs.jl

https://docs.nvidia.com/cuda/cuquantum/latest/overview.html latest version is 23.10.0.6, which also seems to need CUTENSOR 2.0
cc @maleadt

Add support for latest cuQuantum release

---

C/CUDA/cuQuantum/build_tarballs.jl

CC: @kshyatt.
Companion to https://github.com/JuliaRegistries/General/pull/97815.

[cuQuantum_jll] Fix compat bound with CUTENSOR_jll

---

L/LaMEM/build_tarballs.jl

This updates LaMEM to version 2.1.2, utilising PETSc 3.18.6

[LaMEM] version 2.1.2

---

S/SuiteSparse/SuiteSparse@7/build_tarballs.jl

Ref https://github.com/JuliaLang/julia/pull/52577#issuecomment-1872963230 and https://github.com/JuliaLang/julia/pull/52577#issuecomment-1872967550.  Most of the other options were fixed by #7878, but some were missed.

[SuiteSparse@7] Update some CMake configuration options

---

W/Wayland_protocols/build_tarballs.jl

[Wayland_protocols] update to 1.31

---

C/Cares/build_tarballs.jl

https://c-ares.org/changelog.html#1_24_0

[Cares] Update to v1.24.0

---

C/Cares/build_tarballs.jl

https://c-ares.org/changelog.html#1_25_0

[Cares] Update to v1.25.0

---

A/AMGCL_C/build_tarballs.jl

- fix issues with 64bit int on windows

[AMGCL_C]: wrap new amgcl_c version v0.2.0

---

A/AMGCL_C/build_tarballs.jl

Return error state of objects insted

[AMGCL_C]: Prevent C++ exceptions from terminating

---

C/CUTEst/build_tarballs.jl

Upgrade CUTEST to v2.0.27

---

L/LLVM/Clang@17/build_tarballs.jl
L/LLVM/LLD@17/build_tarballs.jl
L/LLVM/LLVM@17/build_tarballs.jl
L/LLVM/MLIR@17/build_tarballs.jl
L/LLVM/libLLVM@17/build_tarballs.jl

Last PR of the LLVM update to v17

[LLVM, Clang, LLD, MLIR] Bump to v17

---

T/Tasmanian/build_tarballs.jl

- O3
- link with strampoline
- link with OMP

[Tasmanian] - using recommended flags

---

N/normaliz/build_tarballs.jl
N/normaliz/bundled/patches/fmpz_inc.patch
N/normaliz/bundled/patches/time_inc.patch

cc: @thofma @fingolfin 
upstream PR for the extra patches: https://github.com/Normaliz/Normaliz/pull/414

[normaliz] update to 3.10.1 and build with flint 3

---

G/Geant4_julia/build_tarballs.jl

Added in addition the following classes:
- G4GeneralParticleSource
- G4SingleParticleSource
- G4SPSPosDistribution
- G4SPSAngDistribution
- G4SPSEneDistribution

[Geant4Julia] New wrappers with latest WrapIt and Geant4 versions

---

P/PortMidi/build_tarballs.jl

Add support for PortMidi.
(This is my first binary builder RP. I hope it works out. Sorry if I break something...)

[PortMidi] Add recipe for v2.0.4

---

O/OpenBLAS/OpenBLAS32@0.3.26/build_tarballs.jl
O/OpenBLAS/OpenBLAS32@0.3.26/bundled/patches/70-no-mtune-native.patch
O/OpenBLAS/OpenBLAS@0.3.26/build_tarballs.jl
O/OpenBLAS/OpenBLAS@0.3.26/bundled/patches/70-no-mtune-native.patch

Ref: https://github.com/OpenMathLib/OpenBLAS/issues/4431#issuecomment-1892681769.

[OpenBLAS@0.3.26] Build with GCC 11 to get SVE kernels

---

S/Singular/build_tarballs.jl

[Singular] update to 4.3.2-14

---

G/GTKmm3/build_tarballs.jl

Should fix https://github.com/JuliaPackaging/Yggdrasil/issues/7935 which also applies to `GTKmm3`
Ref: https://github.com/JuliaPackaging/Yggdrasil/pull/7948
CC @topolarity

[GTKmm3] remove extra symlinks

---

N/NCCL/build_tarballs.jl
N/NCCL/bundled/patches/busid.patch

Include patch from https://github.com/NVIDIA/nccl/issues/1125#issuecomment-1878385150

[NCCL] apply busid patch

---

G/Geant4_julia/build_tarballs.jl

"get" was clashing with Base.get

[Geant4-julia] removing a export to avoid clashes

---

P/Perple_X/build_tarballs.jl

[Perple_X] version 7.1.6

---

L/libsingular_julia/build_tarballs.jl

libsingular_julia for Singular_jll 403.214.1400

---

H/HDF5/build_tarballs.jl

Closes https://github.com/JuliaPackaging/Yggdrasil/issues/7998.

HDF5: Allow both OpenMPI @4 and OpenMPI @5

---

S/smesh/build_tarballs.jl

[Smesh](https://github.com/trixi-framework/smesh) is a simple Fortran package for generating and handling unstructured triangular and polygonal meshes. It is part of the Trixi Framework.
cc @simonechiocchetti @bennibolm

Add build recipe for smesh

---

C/Cares/build_tarballs.jl

https://github.com/c-ares/c-ares/releases/tag/cares-1_26_0

[Cares] Update to v1.26.0

---

S/spglib/build_tarballs.jl

See https://github.com/spglib/spglib/releases/tag/v2.3.0

Update `spglib` build_tarballs.jl to v2.3.0

---

M/MParT/build_tarballs.jl

Sorry for the quick followup, I got snagged by a known issue in CxxWrap that I wasn't aware of.

MParT 2.2.2

---

D/Diamond/build_tarballs.jl

https://github.com/bbuchfink/diamond/releases/tag/v2.1.9

[Diamond] Update to v2.1.9

---

M/MAGEMin/build_tarballs.jl

- Corrected segfault error when running code in parallel
- Corrected Julia wrapper mistake when dealing with lower fraction oxides 
- Updated Julia wrapper to work with @view
- Added computation of specific heat capacity
- Prepared MAGEMin_C 1.3.7 to work with the upcoming Julia App

MAGEMin v1.3.7

---

C/Coin-OR/Ipopt/build_tarballs.jl
C/Coin-OR/coin-or-common.jl

Related issue: https://github.com/jump-dev/Ipopt.jl/issues/403

[Ipopt] Update to v3.14.14

---

L/libjwt/build_tarballs.jl

* Package name: libjwt
* Version: v1.15.3

Wizard recipe: libjwt-v1.15.3

---

A/AlphaMolWrapper/build_tarballs.jl

Update includes ability to adjust calculation precision parameters for AlphaMolWrapper and some cleanup in wrapped function calls.

[AlphaMolWrapper] Updating to 0.2

---

A/AlphaMolWrapper/build_tarballs.jl

Fixing compat of libcxxwrap_jll

[AlphaMolWrapper_jll] Update

---

C/cddlib/build_tarballs.jl

x-ref https://github.com/JuliaPolyhedra/CDDLib.jl/issues/65#issuecomment-1958147827

[cddlib] update to latest commit

---

A/azurite/build_tarballs.jl

Update azurite to current release (3.29.0).

[Azurite] Bump to v3.29

---

Q/Qt6Positioning/build_tarballs.jl

First dependency layer for Qt6 WebView (issue https://github.com/JuliaGraphics/jlqml/issues/21)

[Qt6] Add Qt6Positioning

---

P/PARMETIS/build_tarballs.jl

[PARMETIS] Remove the symbolic link on Windows

---

Q/Qt6WebSockets/build_tarballs.jl

Dependency for webview (issue https://github.com/JuliaGraphics/jlqml/issues/21)

[Qt6] Add Qt6WebSockets

---

F/FFMPEG/FFplay/build_tarballs.jl
F/FFMPEG/common.jl

Follow up to #8090 
Hopefully this should compile for mac + aarch

Update FFplay to 6.1.1

---

L/libsingular_julia/build_tarballs.jl

update libsingular_julia to 0.43.0

---

Z/zimg/build_tarballs.jl

zimg: New version 3.0.5

---

M/msolve/build_tarballs.jl

msolve v0.6.5

---

S/spla/build_tarballs.jl

This is a build recipe for the spla (Specialized Parallel Linear Algebra) library: https://github.com/eth-cscs/spla.
Note: we made the conscious decision not to support Windows or FreeBSD.

New build recipe for spla

---

G/GnuTLS/build_tarballs.jl
G/GnuTLS/bundled/patches/03-undo-libtasn1-cisdigit.patch

GnuTLS: New version 3.8.3

---

L/Libuuid/build_tarballs.jl

Libuuid: New version 2.39.3

---

M/MAGEMin/build_tarballs.jl

- corrected reduced chemical system for igneous database when TiO2 = 0.0
- update MAGEMin_C documentation

MAGEMin v1.3.8

---

G/gh_cli/build_tarballs.jl

Ref https://github.com/JuliaPackaging/ArtifactUtils.jl/issues/24.

[gh_cli] Do not remove Windows

---

O/OpenSpiel/build_tarballs.jl

@fingolfin Analogous to https://github.com/JuliaPackaging/Yggdrasil/pull/6763
Fix #8220.

[OpenSpiel] rebuild with no changes for latest libcxxwrap

---

L/libcxxwrap_julia/build_tarballs.jl

This should become the basis for CxxWrap 0.15
CC @fingolfin

[libcxxwrap-julia] Version 0.12.1

---

C/CompilerSupportLibraries/CompilerSupportLibraries@v1.1/build_tarballs.jl

Ref #8205 and https://github.com/JuliaPackaging/BinaryBuilderBase.jl/pull/369

Rebuild CSL with libgomp fixes

---

H/HiGHS/HiGHS/build_tarballs.jl
H/HiGHS/HiGHSstatic/build_tarballs.jl
H/HiGHS/highs_common.jl

x-ref https://github.com/ERGO-Code/HiGHS/releases/tag/v1.7.0

[HiGHS] update to v1.7.0

---

L/libcxxwrap_julia/build_tarballs.jl

Adds `std::queue` support (by @PraneethJain)

[libcxxwrap-julia] Version 0.12.2

---

C/CUDA/CUDA_Runtime/build_tarballs.jl

Was missing from https://github.com/JuliaPackaging/Yggdrasil/pull/8240; cc @amontoison

CUDA: Update missing compat bound

---

S/Singular/build_tarballs.jl

[Singular] update to 4.3.2-16

---

O/OpenFHE/build_tarballs.jl

[OpenFHE] update to v1.1.4

---

L/Libuuid/build_tarballs.jl

[Libuuid] Disable for macOS

---

L/libpng/build_tarballs.jl

Ref #8259, #8263, https://github.com/JuliaPackaging/Yggdrasil/pull/8110#issuecomment-1986447387

[libpng] Disable building the framework on macOS

---

G/GtkSourceView/build_tarballs.jl

Update to v5, which depends on GTK4.

[GtkSourceView] update to 5.10.0

---

L/libzenoh/build_tarballs.jl
L/libzenohc/build_tarballs.jl

* Package name: libzenoh
* Version: v0.10.1

Wizard recipe: libzenohc-v0.10.1

---

B/biber/build_tarballs.jl

UPDATE: Wrapper around binaries obtained from CTAN.ORG
Initially, even though it doesn't work, I think it's worth sharing this draft. Can we make it work somehow? It would close #5633

Wrap binaries for biber

---

L/libsingular_julia/build_tarballs.jl

* add std_with_HC
* @fingolfin

libsingular_julia for Singular_jll 403.216.160

---

S/Singular/build_tarballs.jl

[Singular] update to 4.3.2-16.1

---

L/libdatachannel/build_tarballs.jl

~~Windows build seems to not be working because it apparently can't find OpenSSL~~
For some reason that only happens when building locally.

Add libdatachannel

---

L/libsingular_julia/build_tarballs.jl

libsingular_julia for Singular_jll 403.216.1601

---

G/GAP_pkg/.gitignore
G/GAP_pkg/GAP_pkg_juliainterface/build_tarballs.jl
G/GAP_pkg/Project.toml
G/GAP_pkg/update.jl

WIP, I'll have to update this with GAP.jl in lockstep

[GAP_pkg_juliainterface] update for GAP 4.13.0

---

L/libsingular_julia/build_tarballs.jl

libsingular_julia for Singular_jll 403.216.1602

---

N/nlohmann_json/build_tarballs.jl

New build recipe for https://github.com/nlohmann/json, a JSON library for modern C++.

[nlohmann_json] New build recipe

---

L/LibUV/build_tarballs.jl

Picks up the fix for https://github.com/JuliaDebug/Cthulhu.jl/issues/541

Bump Libuv

---

S/SuiteSparse/SuiteSparse@7/build_tarballs.jl
S/SuiteSparse/common.jl

A first attempt in https://github.com/JuliaPackaging/Yggdrasil/pull/8354 to update both the CPU and GPU versions in a single PR failed. Trying here to split the update.

[SuiteSparse] Update to 7.6.1

---

W/WrapIt/build_tarballs.jl

Update W/Wrapit to version 1.3.1

[Wrapit] update to version 1.3.1

---

S/SuiteSparse/SuiteSparse_GPU@7/build_tarballs.jl

Following up on https://github.com/JuliaPackaging/Yggdrasil/pull/8355

[SuiteSparse_GPU] Update to 7.6.1

---

N/neper/build_tarballs.jl

Release notes: https://github.com/neperfepx/neper/releases/tag/v4.8.2

[neper] Update to v4.8.2

---

M/MAGEMin/build_tarballs.jl

- Corrected issue with minimum number of pseudocompounds for fluid which was leading to segmentation fault when computing system specific heat capactity

MAGEMin v1.4.1

---

Z/zig/build_tarballs.jl

[zig] Update Zig to 0.11.0

---

X/XZ/build_tarballs.jl

[XZ] Revert recipe to v5.4.6 and add a note not to update it

---

N/nlcglib/build_tarballs.jl

This is a new build recipe for the [nlcglib](https://github.com/simonpintarelli/nlcglib) library, providing a set of nonlinear CG (conjugated gradient) methods for wave-function minimization in DFT (density functional theory). We made the conscious decision not to support Windows or FreeBSD.

[nlcglib] New package recipe

---

0_RootFS/Rust/build_tarballs.jl

Companion PR to https://github.com/JuliaPackaging/BinaryBuilderBase.jl/pull/372

[0_RootFS] Update Rust to v1.77.1

---

0_RootFS/Rootfs/build_tarballs.jl

See also https://github.com/JuliaPackaging/BinaryBuilderBase.jl/pull/370 .

Rootfs: Update Meson to 1.4.0

---

C/CFITSIO/build_tarballs.jl

[CFITSIO] Rebuild with libcurl with unversioned symbols

---

M/micromamba/build_tarballs.jl

upgrades the micromamba build to v1.5.8 (the latest release)

micromamba 1.5.8

---

P/Poppler/build_tarballs.jl

[Poppler] Rebuild with libcurl with unversioned symbols

---

G/Git/build_tarballs.jl

[Git] Rebuild with libcurl with unversioned symbols

---

L/LibUCL/build_tarballs.jl

[LibUCL] Rebuild with libcurl with unversioned symbols

---

P/PROJ/build_tarballs.jl

[PROJ] Rebuild with libcurl with unversioned symbols

---

H/HDF5/build_tarballs.jl

[HDF5] Rebuild with libcurl with unversioned symbols

---

N/NetCDF/build_tarballs.jl

This needed https://github.com/JuliaPackaging/Yggdrasil/pull/8423 to go in first, now we can rebuilb

[NetCDF] Rebuild with libcurl with unversioned symbols

---

L/libgeotiff/build_tarballs.jl

We can rebuild this now that PROJ was done in https://github.com/JuliaPackaging/Yggdrasil/pull/8424

[libgeotiff] Rebuild with libcurl with unversioned symbols

---

F/fzf/build_tarballs.jl

https://github.com/junegunn/fzf/releases/tag/0.49.0

[fzf] update to 0.49.0

---

C/CUTEst/build_tarballs.jl

[CUTEst] Add Windows support

---

S/SoftHSM2/build_tarballs.jl

* Package name: SoftHSM2
* Version: v2.6.1

Wizard recipe: SoftHSM2-v2.6.1

---

O/oneAPI_Support/build_tarballs.jl

However, due to an MKL bug, we still need to vendor a copy of libopencl. The difference with before, is that we now vendor a compliant ICD loader, while the one provided by Intel in the Conda intel-opencl-rt package isn't even compatible with all of their own hardware.
I'll be filing a bug upstream to hopefully fix the MKL issue so that we can avoid the vendored copy.
cc @giordano

oneAPI: Have the support library depend on OpenCL_jll.

---

S/spglib/build_tarballs.jl

See https://github.com/spglib/spglib/releases/tag/v2.4.0

Update spglib_jll.jl to v2.4.0

---

A/AlgoimDiff/build_tarballs.jl

Point toward an updated version of the c++ source of algoim

[AlgoimDiff] Update to v1.1.0

---

G/Geant4/build_tarballs.jl
G/Geant4/bundled/patches/windows.patch

- Needed to add patch file for windows

[Geant4] Upgrade version to 11.2.1 and add windows platform

---

O/OpenBLAS/OpenBLAS32@0.3.27/bundled/patches/60-retain-the-bf16-capability-in-fallback-versions-of-t.patch
O/OpenBLAS/OpenBLAS32@0.3.27/bundled/patches/70-Build-with-proper-aarch64-flags-on-Neoverse-Darwin.patch
O/OpenBLAS/OpenBLAS@0.3.27/bundled/patches/60-retain-the-bf16-capability-in-fallback-versions-of-t.patch
O/OpenBLAS/OpenBLAS@0.3.27/bundled/patches/70-Build-with-proper-aarch64-flags-on-Neoverse-Darwin.patch

Ref https://github.com/JuliaPackaging/Yggdrasil/pull/8446#issuecomment-2041183503.

[OpenBLAS@0.3.27] Restore patch to fix compilation on aarch64-darwin

---

M/MAGEMin/build_tarballs.jl

- corrected normalization issues when computing output structure for the Julia wrapper
- Added K2O-reduced compositional system for igneous database

MAGEMin v1.4.4

---

N/NodeJS/NodeJS_20/build_tarballs.jl

Simply updates NodeJS_20_jll's version.

[NodeJS_20_jll] Update version

---

M/msolve/build_tarballs.jl

Totally forgot about msolve. Hope this works.
I had to add the usual version number shenanigans, so this is now 0.600.501.
CC: @ederc @fingolfin @benlorenz 
P.S.: I ran the AlgebraicSolving tests locally on x86 and they passed.

[msolve] rebuild for flint 3

---

L/LLVMDowngrader/build_tarballs.jl

This adds the ability to emit LLVM 7 bitcode.

LLVM: Bump downgrader JLL.

---

H/HOHQMesh/build_tarballs.jl

Bug fixes and Intel compiler support.

update to HOHQMesh version 1.4.2

---

C/CvxCompress/build_tarballs.jl

Made changes to CvxCompress C-code to move to chrono for timing to allow apple build. Also added artifacts for the header files.

Cvx compress 1.1.0

---

D/DACE/build_tarballs.jl

This version primarily addresses the interaction between DACE and Julia Vectors.

[DACE] bump version to 0.2.0

---

G/gmsh/build_tarballs.jl

Same stupid thing as #8497.  Ref https://github.com/JuliaFEM/Gmsh.jl/issues/33.  CC: @j-fu.

[gmsh] Rebuild with Cairo 1.18

---

L/LLVM/libLLVM@17/build_tarballs.jl

Follow-up for https://github.com/JuliaPackaging/Yggdrasil/pull/8697#issuecomment-2117555142

LLVM: Bump libLLVM 17 JLL to include additional patch.

---

Z/ZipFlow/build_tarballs.jl

[ZipFlow] Update to 1.4

---

S/Singular/build_tarballs.jl

[Singular] update to 4.4.0-1

---

L/libsingular_julia/build_tarballs.jl

libsingular_julia for Singular_jll 404.000.100
@fingolfin

[libsingular_julia] for Singular_jll 404.000.100

---

C/CUDA/CUDA_SDK@12.5/build_tarballs.jl

Tim, I propose to add `yanked = true` for the previous release [here](https://github.com/JuliaRegistries/General/blob/7d59d07cee1ba8ec829523c7d8711267d1aac927/jll/C/CUDA_SDK_jll/Versions.toml#L100-L101).

[CUDA] Regenerate CUDA_SDK

---

L/LLVM/Clang@17/build_tarballs.jl
L/LLVM/LLD@17/build_tarballs.jl
L/LLVM/LLVM@17/build_tarballs.jl
L/LLVM/MLIR@17/build_tarballs.jl

LLVM: Rebuild remaining deps for consistent version numbering.

---

A/aws_c_s3/build_tarballs.jl

This PR updates aws_c_s3 to version v0.5.9. cc: @quinnj @Octogonapus

Automated update of aws_c_s3 to version v0.5.9

---

K/kubectl/build_tarballs.jl

Only one more minor release to go after this.

[kubectl_jll] Build version v1.29.5

---

K/kubectl/build_tarballs.jl

This is currently the latest version

[kubectl_jll] Build version v1.30.1

---

L/LLVMDowngrader/build_tarballs.jl

Fixes https://github.com/JuliaGPU/llvm-downgrade/issues/4

LLVM: Bump downgrader.

---

A/armadillo/build_tarballs.jl
M/mlpack/build_tarballs.jl

mlpack released version 4.4.0, so this PR bumps that, but at the same time I also updated Armadillo to its latest stable version.  Let's see what CI thinks... :smile:

Bump mlpack and Armadillo versions.

---

L/libCppInterOp/build_tarballs.jl
L/libCppInterOp/bundled/patches/cmake.patch

test https://github.com/compiler-research/CppInterOp/pull/301

[CppInterOp] Build version v0.1.2

---

L/libCppInterOp/build_tarballs.jl
L/libCppInterOp/bundled/patches/cmake.patch

- Force to enable`-fPIC`
- Install empty rpath

[CppInterOp] Build version v0.1.3

---

J/jlqml/build_tarballs.jl

[jlqml] Version 0.6.2

---

O/openfhe_julia/build_tarballs.jl

Update version of openfhe_julia and compat settings.
cc @sloede

[openfhe_julia] update to version v0.3.1

---

L/libcxxwrap_julia/build_tarballs.jl

[libcxxwrap-julia] Version 0.13.1

---

G/GAP/build_tarballs.jl
G/GAP/bundled/patches/macos.patch
G/GAP_lib/build_tarballs.jl

Also fix GAC_LDFLAGS on macOS, drop a redundant filter!

[GAP] version 4.13.1

---

H/HOHQMesh/build_tarballs.jl

Add feature of symmetric mesh generation.

update to HOHQMesh version 1.5.0

---

S/SPIRV_LLVM_Translator/SPIRV_LLVM_Translator@13/build_tarballs.jl
S/SPIRV_LLVM_Translator/SPIRV_LLVM_Translator@14/build_tarballs.jl
S/SPIRV_LLVM_Translator/SPIRV_LLVM_Translator@15/build_tarballs.jl
S/SPIRV_LLVM_Translator/SPIRV_LLVM_Translator@16/build_tarballs.jl
S/SPIRV_LLVM_Translator/SPIRV_LLVM_Translator@17/build_tarballs.jl
S/SPIRV_LLVM_Translator/common.jl
S/SPIRV_LLVM_Translator_unified/build_tarballs.jl

Also reinstate the non-unified version for use with dependencies that rely on specific versions of this tool.

Bump SPIRV Translator

---

L/libcxxwrap_julia/build_tarballs.jl

Should fix https://github.com/JuliaIPU/IPUToolkit.jl/pull/66 with thanks to @PraneethJain

[libcxxwrap_julia] Version 0.13.2

---

J/jlqml/build_tarballs.jl

[jlqml] Version 0.6.3

---

Q/Qt6Declarative/build_tarballs.jl

Needed for proper loading on Windows

[Qt6Declarative] Update products list

---

R/Reactant/build_tarballs.jl

[Reactant] Update to v0.0.8

---

L/libtree/build_tarballs.jl

https://github.com/haampie/libtree/compare/v3.1.0...v3.1.1

[libtree] Update to v3.1.1

---

L/libgsd/build_tarballs.jl

* Package name: libgsd
* Version: v3.2.1

Wizard recipe: libgsd-v3.2.1

---

M/MAGEMin/build_tarballs.jl

- general improvement of the accuracy of the phase equilibrium prediction
- corrects issue with spinel in for the metabasite database when O was set to 0.0
- corrects julia function to export to csv when using buffer
- corrects function to compute zircon saturation
- reorganization of the C code to simplify database modification and addition

MAGEMin v1.4.9

---

J/jd/build_tarballs.jl

* Package name: jd
* Version: v1.8.1

Wizard recipe: jd-v1.8.1

---

L/libCppInterOpExtra/build_tarballs.jl

The build script is based on LLVMExtra.

[CppInterOpExtra] Build version v0.0.1

---

L/libgsd/build_tarballs.jl

Added FileProduct of gsd.h to use in CBinding.jl

[libgsd-3.2.1]  Added header files

---

W/Wasmtime/build_tarballs.jl

Let's see whether this works...

Add builder for Wasmtime CLI and C API

---

X/Xorg_xcb_proto/build_tarballs.jl

[Xorg_xcb_proto] Version 1.17.0

---

S/Singular/build_tarballs.jl

[Singular] update to 4.4.0-3

---

C/CImGuiPack/build_tarballs.jl

Note that the URL changed in https://github.com/Gnimuc/CImGui.jl/pull/119.
CC @Gnimuc

[CImGuiPack] Update to ImGui 1.90.8

---

O/OpenFHE/build_tarballs.jl

Update OpenFHE to new version, update of openfhe-julia follows

[OpenFHE] update to version v1.2.0

---

E/Enzyme/build_tarballs.jl

@vchuravy let me know if you know a better way of retriggering, per CI hitting reg rate limit apparently: https://buildkite.com/julialang/yggdrasil/builds/11549#01905cfd-bded-4180-9bb4-f4210d91cb98

Enzyme: force rerun for registration

---

E/Enzyme/build_tarballs.jl

@vchuravy @giordano @staticfloat 
I'm doing nothing differently here, but I can update the commit and maybe it'll be happy after some time off

Enzyme: is third time the charm?

---

L/libsingular_julia/build_tarballs.jl

[libsingular_julia] for option handling

---

E/Extrae/build_tarballs.jl

Try fix the error in https://buildkite.com/julialang/yggdrasil/builds/11585#01905fc2-8ac7-4ee3-a7f6-f475db0874c5/6-14497

[Extrae] Try fix `augment_platform_block` error

---

L/libsass/build_tarballs.jl

[libsass] Update `libsass` to v3.6.6

---

L/libusb/build_tarballs.jl

[libusb] Update to v1.0.27

---

L/libtakum/build_tarballs.jl

There have been some bugfixes, namely for subtraction and special rounding cases.

[libtakum] Update to v0.1.1

---

O/open62541/open62541@1.4/build_tarballs.jl

[open62541] upgrade to v1.4.2

---

A/aws_c_io/build_tarballs.jl

Fix aws-c-io version

---

I/ITK/build_tarballs.jl

New PR opened from a new branch.
Hoping to get merged :)

[ITK-v5.3.0] Added a lot of library products and fixed linking on Mingw32 systems

---

O/OTF2/build_tarballs.jl

New recipe: OTF2

---

O/OTF2/build_tarballs.jl

[OTF2] Build for more platforms

---

C/Coin-OR/CoinUtils/build_tarballs.jl
C/Coin-OR/coin-or-common.jl

Replacement for https://github.com/JuliaPackaging/Yggdrasil/pull/8067

[CoinUtils] update to 2.11.11

---

C/Coin-OR/Osi/build_tarballs.jl
C/Coin-OR/coin-or-common.jl

[Osi] Upgrade to v0.108.10

---

C/Chuffed/build_tarballs.jl

Updating Chuffed artifact (necessary for using the SolutionLimit attribute -- x-ref: https://discourse.julialang.org/t/question-about-when-minizinc-will-return-feasible-solutions/116595/8)

[Chuffed] Update from v0.10.4 to v0.13.2

---

M/msolve/build_tarballs.jl

- Bug fixes
- New lifting, disabled by default

msolve v0.6.7

---

F/Fmt/build_tarballs.jl

Also enable all supported platforms

[libfmt] Update to 11.0.1

---

R/Reactant/build_tarballs.jl

[Reactant_jll] Some minor fixes on tag selection

---

C/Cares/build_tarballs.jl

https://c-ares.org/changelog.html

[Cares] update to v1.32.2

---

R/Reactant/build_tarballs.jl

Automerge is giving an error due to bad string formatting.

[Reactant_jll] Fix formatting `augment_platform_block`

---

T/Tcl/build_tarballs.jl

[Tk] Kick off new build to get mac aarch64 binaries

---

T/Tcl/build_tarballs.jl

[Tcl] Update build_tarballs.jl to get mac aarch64 binaries

---

G/GNURX/build_tarballs.jl

Needed for `file` and `libmagic` on Windows.

Add builder for MinGW libgnurx

---

L/LibUnwind/LibUnwind@1.8.1/build_tarballs.jl
L/LibUnwind/LibUnwind@1.8.1/bundled/patches/libunwind-disable-initial-exec-tls.patch

https://github.com/JuliaLang/julia/pull/55049

libunwind: Enable per thread register state cache

---

M/MAGEMin/build_tarballs.jl

- Re-adds the individual solution phase minimization time
- Corrects issue when computing specific heat capacity through the Julia wrapper
- Corrects calculation of nno buffer

MAGEMin v1.5.0

---

M/msolve/build_tarballs.jl

msolve - v0.6.8

---

C/Cares/build_tarballs.jl

https://github.com/c-ares/c-ares/releases/tag/v1.32.3

[Cares] update to v1.32.3

---

L/LLVM/Clang_unified/build_tarballs.jl

I removed the existing release when I shouldn't have, so now I need a full rebuild...

LLVM: Bump unified Clang JLL

---

P/pocl/build_tarballs.jl

POCL: Add Clang_unified_jll dependency.

---

W/WrapIt/build_tarballs.jl

Upgrade W/WrapIt to v1.4.0

---

M/msolve/build_tarballs.jl

- New interface for degrevlex GBs over QQ
- Several bug fixes for f4sat

[msolve] v0.7.0

---

M/msolve/build_tarballs.jl

Bug fix release for julia interface added in v0.7.0.

[msolve] v0.7.1

---

H/HiGHS/HiGHS/build_tarballs.jl
H/HiGHS/HiGHSstatic/build_tarballs.jl
H/HiGHS/highs_common.jl

Tagging @odow @imciner2 as they were the last ones who updated HiGHS.

[HiGHS] update to v1.7.2

---

C/Clingo/build_tarballs.jl

Some targets in CI were failing in #8758. I am trying again and troubleshooting here.

[Clingo] Update to v5.7.1

---

N/nlcglib/build_tarballs.jl

Updating `nlcglib_jll` to v1.1.0

[nlcglib] Updating to version 1.1.0

---

S/SpFFT/build_tarballs.jl

Updating `SpFFT_jll` to v1.1.0

[SpFFT] Updating to version 1.1.0

---

S/spla/build_tarballs.jl

[spla] Update to version 1.6.1

---

O/open62541/open62541@1.4/build_tarballs.jl

Newest bugfix release of open62541

[open62541] update to v1.4.3

---

R/Rmath/build_tarballs.jl

Ref: https://github.com/JuliaStats/Rmath-julia/issues/47, fix https://github.com/JuliaStats/Rmath-julia/issues/44.  CC: @ViralBShah.

[Rmath] Manually set `USEGCC`/`USECLANG`

---

L/libssh/build_tarballs.jl

Note that setting the doxygen tag has been merged upstream.

[libssh] Update to 0.11.0

---

T/Tcl/build_tarballs.jl
T/Tk/build_tarballs.jl

Force Tk and Tcl to be on the same versions through compat.

[Tcl] 8.6.12

---

O/OpenSSH/build_tarballs.jl
O/open62541/open62541@1.4/build_tarballs.jl

Updates open62541 to version 1.4.4.

[open62541] v1.4.4

---

P/pandoc/build_tarballs.jl

Previous Pandoc update PR (bump to Pandoc 3.2) is at https://github.com/JuliaPackaging/Yggdrasil/pull/8891.

[pandoc] Update to 3.3

---

X/XML2/build_tarballs.jl

Bump XML2 to 2.13.3

---

X/XDiag/build_tarballs.jl

Just a new patch release, see https://github.com/awietek/xdiag/releases

[XDiag] bump 0.2.2

---

L/libass/build_tarballs.jl

and bump HarfBuzz compat to latest version.

[libass] update to 0.15.2

---

C/CUTEst/build_tarballs.jl

- The library in quadruple precision is correctly compiled with this new release.

[CUTEst] Upgrade to v2.2.3

---

L/LaMEM/build_tarballs.jl

[LaMEM] version 2.1.4

---

M/MAGEMin/build_tarballs.jl

- Improving the accuracy of metabasite and igneous phase diagrams
- Corrected mol fraction output for Julia wrapper
- Updated MAGEMin framework for the upcoming Stixrude & Lithgow-Bertelloni database

MAGEMin v1.5.1

---

O/openfhe_julia/build_tarballs.jl

[openfhe_julia] update to version v0.3.4

---

I/IntelOpenMP/build_tarballs.jl

This is consistent with the `lazy_artifacts=true` we have in MKL_jll

[IntelOpenMP] Make artifacts lazy

---

M/MAGEMin/build_tarballs.jl

- Corrected issue when adding anti-ordered pseudocompound that was leading to site fraction constraint being not respected

MAGEMin v1.5.2

---

I/ITKIOWrapper/src/itklib.cpp

The function for loading the direction of the Itk image got leftover, integrated .
Sorry, for the inconvenience caused.

ITKIOWrapper-v1.0.0 Added getDirection function

---

L/LibUV/build_tarballs.jl

Ref: https://github.com/libuv/libuv/pull/4525.

[LibUV] Backport another bugfix

---

R/Reactant/build_tarballs.jl

Reactant: cuda round 4?

---

S/Singular/build_tarballs.jl

[Singular] update to 4.4.0-5

---

L/libtakum/build_tarballs.jl

Properly handle saturation arithmetic for the enclosed math functions.

[libtakum] Update to v0.2.2

---

G/GAP/build_tarballs.jl
G/GAP/bundled/patches/julia_gc-rescan.patch
G/GAP/bundled/patches/macos.patch

Also restore GAC_LDFLAGS to what now hopefully really is a sane default.

[GAP] workaround GC issue, update libjulia

---

Q/quarto/build_tarballs.jl

try to get the latst archive sources for quarto

bump quarto to v1.5.57

---

S/Singular/build_tarballs.jl

[Singular] fix exit calls of childs

---

L/libsingular_julia/build_tarballs.jl

[libsingular_julia] for Singular_jll 404.000.503

---

C/Catalyst/build_tarballs.jl

- source for v2.0.0
- adapted build procedure according to documentation https://catalyst-in-situ.readthedocs.io/en/latest/build_and_install.html
- added Cmake_jj as dependency as a newer cmake version was required
I hope things go well!

[Catalyst] Update to v2.0.0

---

Y/yyjson/build_tarballs.jl
Y/yyjson/bundled/patches/yyjson_api_inline_off.patch

* Package name: yyjson
* Version: v0.10.0

Wizard recipe: yyjson-v0.10.0

---

D/DBCtoDBF/build_tarballs.jl

Wizard recipe: DBCtoDBF-v1.0.0

---

P/PhreeqcRM/build_tarballs.jl

[PhreeqcRM](https://github.com/usgs-coupled/phreeqcrm) is widely used software packages to simulate geochemical reactions in ground and geothermal waters.

[PhreeqcRM] version 3.8.2

---

C/CImGuiPack/build_tarballs.jl

Building for https://github.com/JuliaImGui/cimgui-pack/pull/6.

[CImGuiPack] Bump for ImGui 1.91.1

---

L/libsingular_julia/build_tarballs.jl

[libsingular_julia] for Singular_jll 404.000.504

---

G/GAP/build_tarballs.jl

This is using a different version so I can switch
back and forth between them for debugging

[GAP] don't require precise marking

---

L/libbensolve/build_tarballs.jl

* Package name: libbensolve
* Version: v2.1.0

Wizard recipe: libbensolve-v2.1.0

---

L/libtakum/build_tarballs.jl

Add functions for integer powers and roots.

[libtakum] Update to v0.3.0

---

M/MAGEMin/build_tarballs.jl

- Added an extended version of the ultramafic database (ume), accounting for hb, pl and aug from metabasite database
- Added atom per formula unit (apfu) output for the Julia wrapper
- Corrected inaccurate reaction lines in case of liquid solvus 
- Added support for reduced compositional system for ultramafic database (O and S can be set to 0.0)

MAGEMin v1.5.3

---

C/CompilerSupportLibraries/CompilerSupportLibraries@v1.2/build_tarballs.jl

The first of many PRs to build stuff for FreeBSD AArch64

[CSL] New version for FreeBSD AArch64 support

---

R/Rmath/build_tarballs.jl

This will provide Rmath library as of version 4.4.1 of R.

Rmath version 0.5.1

---

Z/Zlib/build_tarballs.jl

To get FreeBSD AArch64 support

[Zlib] Trigger a new build

---

F/FLEXPART/bundled/patches/flexpart-parmod.patch

Fix the error we get when trying to model multiple species in a single run.

[FLEXPART] change maxspec to 10

---

G/GMP/GMP@6.2.1/build_tarballs.jl

I rebuilt 6.3.0 previously since that's what Julia is using but MPFR needs 6.2.1.

[GMP@6.2.1] Rebuild for FreeBSD AArch64 support

---

S/Singular/build_tarballs.jl

[Singular] update to 4.4.0-6

---

R/rr/build_tarballs.jl

Picks up upstream commit https://github.com/rr-debugger/rr/commit/2f319cad9dc4fa7d719f16472bdd3830b9fb6f3a

Pick up an extra rr bug fix

---

O/OpenSSL/OpenSSL@1.1/build_tarballs.jl
O/OpenSSL/OpenSSL@3.0/build_tarballs.jl
O/OpenSSL/common.jl

Not sure whether it actually works to rebuild multiple versions in a single PR...

[OpenSSL] Support FreeBSD AArch64 in versions 1.1 and 3.0

---

O/OpenSSH/build_tarballs.jl

Let's see if this makes the package actually work on Windows, e.g. https://github.com/JuliaDocs/DocumenterTools.jl/pull/74

[OpenSSH] Also install `libcrypto` on Windows

---

A/alsa/build_tarballs.jl

[alsa] Update to 1.2.12

---

S/Singular/build_tarballs.jl

@fingolfin also introducing environment variable SINGULAR_CPUS

[Singular] library fixes, limit processes

---

P/Pythia8_cxxwrap/build_tarballs.jl

Added CxxWrap wrappers for the PYTHIA_jll package

[Pythia8_cxxwrap] New package with the CxxWrap wrappers of PYTHIA8

---

S/SuiteSparse/SuiteSparse@7/build_tarballs.jl

It was set to 7.7.0 temporarily for a rebuild.
[skip build]

[SuiteSparse@7] Set version back to 7.8.2

---

D/demumble/build_tarballs.jl
D/demumble/bundled/patches/0001-build-system-now-supports-more-build-environments.patch

https://github.com/nico/demumble: a stand-aline demangler like `c++filt`.

demumble: add initial recipe.

---

L/libsingular_julia/build_tarballs.jl

[libsingular_julia] for Singular_jll 404.000.606

---

O/OpenFHE/build_tarballs.jl

@sloede 
I update also version of OpenFHE_jll needed by #9537

[OpenFHE_jll] update to version 1.2.1

---

J/JSON_C/build_tarballs.jl

To include newer platforms (current release is 4 years old) for https://github.com/JuliaPackaging/Yggdrasil/pull/9453

JSON_C: Update to v0.17

---

O/openfhe_julia/build_tarballs.jl

@sloede 
I also set a new compat settings for OpenFHE_jll, because older version does not work with latest Msys and Clang.

[openfhe_julia] update to version v0.3.5

---

M/MPFR/build_tarballs.jl

This reverts #9543.
[skip build]

[MPFR] Set version back to 4.2.1

---

B/Binutils/build_tarballs.jl

Also enable more Unix platforms (where things work out of the box).

Binutils: New version 2.43

---

R/Reactant/build_tarballs.jl

Reactant: fix bazel build

---

C/CImGuiPack/build_tarballs.jl

Building for https://github.com/JuliaImGui/cimgui-pack/pull/7.

[CImGuiPack] Update for ImGui v1.91.2

---

L/libsingular_julia/build_tarballs.jl

[libsingular_julia] quotient /saturation for smodule

---

L/LLVM/libLLVM@19/build_tarballs.jl

Not sure if `julia_compat="1.12"` needs to be changed.

[libLLVM] Bump to v19.1.1+0

---

L/libsingular_julia/build_tarballs.jl

[libsingular_julia] update to latest cxxwrap

---

U/Uno/build_tarballs.jl

x-ref: https://github.com/cvanaret/Uno
cc @cvanaret
I haven't tried this locally, so let's see what happens. ... okay, not immediately straight forward. I'll try this locally.

[Uno] add initial build_tarballs.jl

---

P/Perple_X/build_tarballs.jl

updates for Perple_X release 7.1.8, adds MC_fit target.

[Perple_X] version 7.1.8

---

U/Uno/build_tarballs.jl

Suggested by @giordano in https://github.com/JuliaPackaging/Yggdrasil/pull/8937

[Uno] a few tweaks to build_tarballs.jl

---

H/HiGHS/HiGHS/build_tarballs.jl
H/HiGHS/HiGHSstatic/build_tarballs.jl
H/HiGHS/highs_common.jl

[HiGHS] update to v1.8.0

---

P/PETSc/build_tarballs.jl
P/PETSc/bundled/patches/mpi-constants.patch

[PETSc] version 3.22.0

---

S/sgtsnepi/build_tarballs.jl

[SGtSNEpi] version 3.0.0

---

L/libblastrampoline/common.jl
L/libblastrampoline/libblastrampoline@5.11/build_tarballs.jl
L/libblastrampoline/libblastrampoline@5.4/build_tarballs.jl

Fix https://github.com/JuliaPackaging/Yggdrasil/pull/9641#discussion_r1813751799

[libblastrampoline] Fix version number

---

U/Uno/build_tarballs.jl

[Uno] update gitsha without updating version

---

L/libwebsockets/build_tarballs.jl

Hi! I’ve added a build script for [libwebsockets](https://github.com/warmcat/libwebsockets) version 4.3.3, I think it will be useful :)

[libwebsockets] version 4.3.3

---

L/Libgpg_error/build_tarballs.jl
L/Libgpg_error/bundled/patches/01-fix-macos-environ.patch

Also takes care of the freebsd build required in https://github.com/JuliaPackaging/Yggdrasil/pull/9680

libgpg_error: bump to v1.50.

---

L/libjulia/build_tarballs.jl
L/libjulia/common.jl

This is mainly an experiment to see what is missing. I am also not sure which version of Julia is supposed to be the first with support for FreeBSD aarch64

[libjulia] enable FreeBSD aarch64

---

L/Libiconv/build_tarballs.jl

Also, rebuild for aarch64-freebsd

[Libiconv] Make pkgconfig file relocatable

---

U/Uno/build_tarballs.jl

[Uno] bump gitsha without changing version

---

A/ADOLC/build_tarballs.jl

New version
- is based on ADOL-C's C Interface
- remove CxxWrap dependency

[ADOLC] Update to 2.0.0

---

O/Openresty/build_tarballs.jl

Update Openresty to v1.27.1
Also update some deps, openssl to 3.0.15 and zlib to 1.3.1.

Update Openresty to v1.27.1

---

S/SDPA/build_tarballs.jl

x-ref https://github.com/jump-dev/SDPA.jl/issues/62

[SDPA] update to 7.3.18

---

C/CvxCompress/build_tarballs.jl
C/CvxCompress/bundled/patches/cross-compile-cvxcompress-gencode.patch

[CvxCompress] update to 1.2.0

---

L/libplist/build_tarballs.jl

This also has the side-effect of supporting aarch64 freebsd!

[libplist] Bump to v2.6.0

---

L/libjulia/build_tarballs.jl
L/libjulia/common.jl

such that https://github.com/JuliaLang/julia/pull/56373 is included
cc @fingolfin

[libjulia] update julia 1.12.0-DEV version

---

U/Uno/build_tarballs.jl

[Uno] update to v1.2.0

---

S/Spasm/build_tarballs.jl
S/Spasm/bundled/patches/spasm-add-cinttypes.patch
S/Spasm/bundled/patches/spasm-config-argp.patch
S/Spasm/bundled/patches/spasm-disable-Werr.patch

This is a fresh start at a recipe for the SpaSM direct linear algebra solver modulo p, by Charles Bouillaguet (see https://github.com/cbouilla/spasm).

[Spasm] New recipe

---

L/libxlsxwriter/build_tarballs.jl

* Package name: libxlsxwriter
* Version: v1.1.9

Wizard recipe: libxlsxwriter-v1.1.9

---

R/Reactant/build_tarballs.jl

[Reactant] Update version to 0.0.24

---

M/MAGEMin/build_tarballs.jl

- Corrected unforeseen segfault problem affecting MAGEMin_C (julia wrapper)
- New tests have been added to MAGEMin_C to avoid that in the future

MAGEMin v1.5.8

---

U/unixODBC/build_tarballs.jl
U/unixODBC/bundled/patches/clock_gettime.patch

Windows build recipe: https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-unixodbc/PKGBUILD

[unixODBC] 2.3.12

---

E/Enzyme/build_tarballs.jl

New attempt at #9771, I haven't changed anything, just opened a PR from a different branch, I don't know what went wrong with the pipeline in that PR.
Close #9771.

Upgrade enzyme to refs/tags/v0.0.164

---

H/HiGHS/HiGHS/build_tarballs.jl
H/HiGHS/HiGHSstatic/build_tarballs.jl
H/HiGHS/highs_common.jl

[HiGHS] update to v1.8.1

---

X/xsum/build_tarballs.jl

For https://github.com/JuliaMath/Xsum.jl/issues/15

update Xsum to v3.0

---

L/libtakum/build_tarballs.jl

Adding a README and fixing some minor issues in manual pages and the build system.

[libtakum] Update to v1.0.0

---

U/Uno/build_tarballs.jl

cc @amontoison 
cc @cvanaret 
Charlie: I didn't really follow the flurry of PRs about the compilation stuff, so not sure if I need something else here.

[Uno] update to v1.3.0

---

P/proxTV/build_tarballs.jl

[proxTV] Upgrade to v3.4.0

---

S/Singular/build_tarballs.jl

[Singular] update to 4.4.0-7

---

S/Singular/build_tarballs.jl

[Singular] ABI fixes

---

S/Singular/build_tarballs.jl

@fingolfin that should now cover all changes

[Singular] ABI fixes for kMin_std

---

G/Glib/build_tarballs.jl

Also add libgirepository as a product.

[Glib] update to 2.82.2

---

S/Singular/build_tarballs.jl

[Singular] ABI extended

---

A/Aravis/build_tarballs.jl

Also Glib_jll compat increased for aarch64-unknown-freebsd

[Aravis] bump version to 0.8.33

---

O/Octave/build_tarballs.jl

[Octave] New builder - v9.2.0

---

M/MAGEMin/build_tarballs.jl

- Corrected default ilmenite model for metapelite and metabasite database to be ilm instead of ilmm
- Added adaptive refinement for MAGEMin_C Julia wrapper

MAGEMin v1.5.9

---

W/wget/build_tarballs.jl

- new version 1.25.0
- switch from GnuTLS to OpenSSL

wget: New version 1.25.0

---

P/P4est/build_tarballs.jl

Also enable OpenMPI and support JSON via Jansson.

P4est: New version 2.8.6

---

O/open62541/open62541@1.3/build_tarballs.jl
O/open62541/open62541@1.4/build_tarballs.jl

Updates the 1.4 and 1.3 release versions of open62541.

[open62541] update to v1.4.8 and 1.3.15

---

L/libposit/build_tarballs.jl

Refine the conversion routines between posits and floats to alleviate some rare rounding errors.

[libposit] Update to v1.0.1

---

L/libtakum/build_tarballs.jl

Some code refactoring and improving the precision for some rare operations.

[libtakum] Update to v1.0.1

---

P/proxTV/build_tarballs.jl

@amontoison
Thanks in advance :)

update proxTV to v3.5.0

---

Q/Qt6Charts/build_tarballs.jl

For issue https://github.com/JuliaGraphics/QML.jl/issues/210

[Qt6Charts] Add Qt6Charts

---

L/libsingular_julia/build_tarballs.jl

[libsingular_julia] update treehash

---

F/flecs/build_tarballs.jl

creating new build recipe for flecs ecs system.

flecs v4.0.3

---

E/Expat/build_tarballs.jl

As discussed here: https://github.com/JuliaPackaging/Yggdrasil/pull/10006#discussion_r1885031567

[Expat] Temporary revert to 2.2.10 to build for aarch64-freebsd

---

C/CImGuiPack/build_tarballs.jl

Building for ~~https://github.com/JuliaImGui/cimgui-pack/pull/8~~ https://github.com/JuliaImGui/cimgui-pack/pull/9.

[CImGuiPack] Update for ImGui v1.91.6

---

L/llama_cpp/build_tarballs.jl

Closes https://github.com/JuliaPackaging/Yggdrasil/issues/10058.

llama_cpp: Update to tag b4371

---

M/MAGEMin/build_tarballs.jl

- Added Igneous Alkaline Dry database (igad) from Weller et al., 2024
- Added Igneous Green et al., 2025 corrected and updated from Holland et al., 2018

MAGEMin v1.6.2

---

W/Wayland_protocols/build_tarballs.jl

[Wayland_protocols] update to 1.36

---

P/PDAL/build_tarballs.jl

This should resolve this problem https://github.com/JuliaRegistries/General/pull/121954.

PDAL: Depend on LibCURL

---

C/Clay/build_tarballs.jl

* Package name: Clay
* Version: v0.1.2

Wizard recipe: Clay-v0.1.2

---

Q/Qhull/build_tarballs.jl

As discussed in https://github.com/JuliaPackaging/Yggdrasil/issues/9889

[QHull] Update version number for semver

---

M/MAGEMin/build_tarballs.jl

- Added solution phase full name
- Updated mineral naming to fit THERMOCALC convention
- Corrected issue when deactivating solution phase model

MAGEMin v1.6.3

---

I/ITKIOWrapper/build_tarballs.jl
I/ITKIOWrapper/src/itklib.cpp

Added support for 
1. : dicom loading
2 : Changing orientation for the voxel data arrays

ITKIOWrapper-v1.0.0 added DIcom support

---

G/GAP_pkg/GAP_pkg_juliainterface/build_tarballs.jl
G/GAP_pkg/common.jl

I.e. to include https://github.com/oscar-system/GAP.jl/pull/1112.
cc @fingolfin

[GAP_pkg_juliainterface] Rebuild with GAP string conversion changes

---

L/libpng/build_tarballs.jl

Note that the package version is NOT updated.

libpng: Update to 1.6.45

---

S/SuiteSparse/SuiteSparse_GPU@7/build_tarballs.jl

[SuiteSparse_GPU] Update to 7.8.3

---

L/libCppInterOp/bundled/patches/cmake.patch
L/libCppInterOp/bundled/patches/windows.patch

- update patches
- retrigger build

libCppInterOp: fix symbol visibility issues on Windows

---

L/libCppInterOpExtra/build_tarballs.jl

based on https://github.com/JuliaPackaging/Yggdrasil/pull/10250

libCppInterOpExtra: bump version to v0.0.2

---

M/MAGEMin/build_tarballs.jl

- Corrected issue that was making the ultramafic extended database crash
- Corrected issue when computing graphite mol fraction for metapelite extended database

MAGEMin v1.6.4

---

D/Dierckx/build_tarballs.jl

Some arguments were changed, change minor version number.

[Dierckx] Upgrade to newer upstream

---

R/Reactant/build_tarballs.jl

[Reactant] Fix CUDA version check

---

R/Reactant/build_tarballs.jl

Ref: https://github.com/EnzymeAD/Reactant.jl/issues/526#issuecomment-2596057388. CC: @wsmoses @avik-pal

[Reactant] Reduce minimum CUDA version to 12.3

---

I/ITK/build_tarballs.jl

Saw the script reverted back for some lines, apologies.

[ITK-v5.3.1] Fixing Mingw errors for lib targets

---

R/Reactant/build_tarballs.jl
R/Reactant/platform_augmentation.jl

Very preliminary at the moment, opening to see how building with the new option goes and then we'll tweak it.  CC: @wsmoses.

[Reactant] Build with different versions of CUDA

---

G/GAP_lib/build_tarballs.jl
G/GAP_lib/bundled/patches/Add-packagedirs-and-ExtendPackageDirectories-5873.patch

cf. https://github.com/oscar-system/GAP.jl/pull/1095#issuecomment-2598465768
cc @fingolfin

[GAP_lib] Backport new package directories features

---

E/EDFlib/build_tarballs.jl
E/EDFlib/bundled/patches/freebsd.patch

Also include the header as a file product, just in case.

[EDFlib] Update to v1.26.0

---

M/mmtk_julia/build_tarballs.jl

Updating `mmtk-julia` version.

[mmtk_julia] Update binding version

---

.ci/Manifest.toml

Reverts JuliaPackaging/Yggdrasil#10332
Try to see if this solves the issue in https://github.com/JuliaPackaging/Yggdrasil/pull/10330#issuecomment-2612783632

Revert "[CI] Update manifest (#10332)"

---

U/UCX/build_tarballs.jl

[UCX] Update UCX

---

S/SuiteSparse/ParU/build_tarballs.jl
S/SuiteSparse/SPEX/build_tarballs.jl
S/SuiteSparse/SSGraphBLAS/build_tarballs.jl

Re-run these so that they can appear on General and then I'll get them merged. Will only function on v1.12

[SuiteSparse Extras] Re-run builders for SPEX, ParU, GraphBLAS

---

M/MAGEMin/build_tarballs.jl

- Added option to deactivate pure phase
- Added information about end-member and solution phases abbreviations and compositions
- Corrected unit output for entropy and enthalpy for pure and solution phases

MAGEMin v1.6.6

---

U/UserNSSandbox/build_tarballs.jl

X-ref: https://github.com/JuliaContainerization/Sandbox.jl/commit/a3320d4ddcb4b2fa39d8831b06cfaaf97b16f85d

[UserNSSandbox] Add OverlayedReadOnly mounts

---

L/libsingular_julia/build_tarballs.jl

[libsingular_julia] for Singular_jll 404.100.000

---

R/Reactant/build_tarballs.jl

Includes changes from https://github.com/EnzymeAD/Reactant.jl/pull/653.

[Reactant] Update to v0.0.58

---

S/Singular/build_tarballs.jl

[Singular] update to 4.4.1p1

---

C/CImGuiPack/build_tarballs.jl

Building for https://github.com/JuliaImGui/cimgui-pack/pull/10.

[CImGuiPack] Bump version of wrappers

---

M/MAGEMin/build_tarballs.jl

- Improved accuracy  of calculations for metapelite, metabasite, igneous, mantle and alkali dry datasets
- Corrected mistake that was leading to a 6bar pressure shift

MAGEMin v1.6.7

---

L/libjulia/build_tarballs.jl
L/libjulia/common.jl

There were some ABI breaking changes e.g. to struct layouts.
CC @benlorenz @barche

[libjulia] update 1.12-DEV to most recent master

---

G/GAP/build_tarballs.jl

[GAP] rebuild with latest libjulia

---

N/NLopt/build_tarballs.jl

nlopt 2.10.0

---

L/libjulia/build_tarballs.jl
L/libjulia/bundled/patches/1.13.0-DEV/bf16-workaround.patch
L/libjulia/common.jl

cc @benlorenz @fingolfin @barche

[libjulia] Rebuild for julia 1.13.0-DEV

---

G/GAP/build_tarballs.jl

[GAP] rebuild with latest libjulia (for 1.13-DEV)

---

A/Arpack/Arpack/build_tarballs.jl
A/Arpack/Arpack32/build_tarballs.jl

Is this the right way to pull in new architectures? Just rebuild without changing anything else?

[Arpack] Rebuild to include riscv

---

C/CImGuiPack/build_tarballs.jl

Building for https://github.com/JuliaImGui/cimgui-pack/pull/11.

[CImGuiPack] Build for v1.91.8

---

G/GAP/build_tarballs.jl

[GAP] rebuild with latest libjulia (for 1.13-DEV), now with version bump

---

Q/Qt6Base/build_tarballs.jl
Q/Qt6Base/common.jl

And some extra hoop-jumping for macOS...

[Qt6Base] Version 6.8.2 (targets build)

---

G/GAP_pkg/GAP_pkg_juliainterface/build_tarballs.jl
G/GAP_pkg/update.jl

[GAP_pkg_juliainterface] Rebuild with latest libjulia (for 1.13-DEV), with bump

---

L/libsingular_julia/build_tarballs.jl

[libsingular_julia] rebuild for julia 1.13-DEV

---

H/Heptagon/build_tarballs.jl
H/Heptagon/bundled/patches/00001-better-stdlib-default.patch

This adds a recipe for heptagon (https://gitlab.inria.fr/synchrone/heptagon) a synchronous dataflow language and compiler.
Almost entirely thanks to @mlechu and @xal-0

[Heptagon] Add v1.05

---

Q/Qt6Base/common.jl

[Qt6] Add support for separate windows products

---

M/MAGEMin/build_tarballs.jl

- further improved accuracy of metapelite, metabasite, igneous and alkaline databases calculations
- added iw buffer to metapelite, metabasite, igneous and alkaline databases
- added prehnite, pumpellyite and pyrophyllite for the metapelite extended databases

MAGEMin v1.6.8

---

S/Singular/build_tarballs.jl

[Singular] fix Oscar short tests

---

M/mmtk_julia/build_tarballs.jl

Pushing this fix https://github.com/mmtk/mmtk-julia/pull/228 to the binding code to fix the MMTk+Julia CI.

[mmtk-julia] Updating binding hash

---

A/AquaCrop/build_tarballs.jl

[AquaCrop] Add version 7.1.1

---

A/AquaCrop/build_tarballs.jl

This is the current release of AquaCrop.
cc @veddox @gabo-di @visr

[AquaCrop] Add version 7.2

---

M/MozillaCACerts/build_tarballs.jl

[MozillaCACerts] Add julia compat

---

O/open62541/open62541@1.4/build_tarballs.jl

Should be a straightforward patch version bump.

[open62541] update to version 1.4.10

---

P/pixi/build_tarballs.jl

New recipe to build the [pixi package manager](pixi.sh).

[pixi] new recipe at v0.41.3

---

N/nauty_graph/build_tarballs.jl
V/very_nauty/build_tarballs.jl

* Package name: nauty_graph
* Version: v1.1.1

Wizard recipe: very_nauty-v1.1.1

---

M/MAGEMin/build_tarballs.jl

- Added option to use initial guess when computing phase diagrams
- Corrected recently introduced mistake that was leading to wrong values for Vp_S and Vs_S
- Improved computational time for latent heat of reaction calculation
- Slightly shifting compositional variables bounds to smaller values (1e-8)

MAGEMin v1.7.0

---

I/ittapi/build_tarballs.jl
I/ittapi/bundled/patches/.gitattributes
I/ittapi/bundled/patches/0001-Add-non-exec-stack-annotation-only-for-ELF.patch

This version fixes issues with executable stack: https://github.com/intel/ittapi/pull/170.

[ittapi] Update to v3.25.5

---

G/GAP_pkg/GAP_pkg_juliainterface/build_tarballs.jl

[GAP_pkg_juliainterface] Update to avoid on-the-fly recompilation

---

M/MozillaCACerts/build_tarballs.jl

Latest from https://curl.se/docs/caextract.html

[MozillaCACerts] Update 2025-02-25

---

I/ITKIOWrapper/build_tarballs.jl

Updated upstream Wrapper package to use ITK_jll with new HDF5 version.

[ITKIOWrapper] updated dependency version

---

R/ROOT/build_tarballs.jl

Follow-up of #10684
---------
Co-authored-by: Mosè Giordano <mose@gnu.org>

[ROOT] Fix OpenBLAS32_jll UUID

---

M/mmtk_julia/build_tarballs.jl

[mmtk-julia] Updating binding version

---

B/BPNET/build_tarballs.jl
B/BPNET/bundled/patches/cmakegnu.patch

I revised this . 
https://github.com/JuliaPackaging/Yggdrasil/pull/10470

[BPNET 0.0.2] Dependency is added

---

S/Singular/build_tarballs.jl

[Singular] default to sequential algorithms

---

S/Singular/build_tarballs.jl

fixes https://github.com/oscar-system/Oscar.jl/issues/4714
@fingolfin

[Singular] fix oscar macosx test

---

D/Darknet/Darknet/build_tarballs.jl
D/Darknet/common.jl

Update to the last release https://github.com/AlexeyAB/darknet/releases/tag/yolov4

[darknet] update to last release (yolov4)

---

H/H3/build_tarballs.jl

The official patch version is out.
related from [H3] Update to version 4.2.0 #10689

[H3] Update to version 4.2.1

---

S/SuiteSparse/SuiteSparse32@7/build_tarballs.jl
S/SuiteSparse/SuiteSparse@7/build_tarballs.jl
S/SuiteSparse/common.jl

Splitting https://github.com/JuliaPackaging/Yggdrasil/pull/10726 1/2

[SuiteSparse] Update to 7.10.1

---

S/SuiteSparse/CXSparse/build_tarballs.jl

Follow-up to https://github.com/JuliaPackaging/Yggdrasil/pull/10726

[CXSparse] Update SuiteSparse version

---

S/SuiteSparse/SuiteSparse_GPU@7/build_tarballs.jl

Split from https://github.com/JuliaPackaging/Yggdrasil/pull/10726

[SuiteSparse_GPU] Update to 7.10.1

---

N/nauty/build_tarballs.jl

See https://github.com/JuliaPackaging/Yggdrasil/pull/10746#pullrequestreview-2687753820.
cc @benlorenz

[nauty] Build for aarch64-freebsd

---

M/MAGEMin/build_tarballs.jl

- Re-added the use of pure-endmember swapping during levelling stage to improve accuracy of minimizations
- Further improves initial guess to compute phase diagrams

MAGEMin v1.7.2

---

N/normaliz/build_tarballs.jl

[normaliz] Rebuild with FLINT 3.2.0

---

C/CUDA/CUDA_Driver/init.jl

Also make it so that errors aren't swallowed.
cc @abussy

CUDA driver: Use a fresh env to ensure we can load Libdl.

---

P/pandoc/build_tarballs.jl

[pandoc] bump to v3.6.4

---

H/HiGHS/HiGHS/build_tarballs.jl
H/HiGHS/HiGHSstatic/build_tarballs.jl
H/HiGHS/highs_common.jl

[HiGHS] update to v1.10.0

---

G/gecko/build_tarballs.jl

This PR adds the build script to get a gecko artifact. Gecko is a graph ordering library developed at LLNL.

New Recipe: gecko v1.0.0

---

R/Reactant/build_tarballs.jl

Reactant 0.0.97

---

M/MPFR/build_tarballs.jl

See also https://github.com/JuliaPackaging/Yggdrasil/pull/10637.

MPFR: New version 4.2.2

---

S/snappy/build_tarballs.jl

Fixes https://github.com/google/snappy/issues/201

[snappy] Update to v1.2.2

---

S/SoapyRemote/build_tarballs.jl

Yet another SoapySDR back-end plugin.

Add recipe for SoapyRemote.

---

C/ColPack/build_tarballs.jl

I did many tests with a local version of `ColPack_jll.jl` before opening #10855 but I found just after a few big issues with OpenMP.
ColPack is not well tested with OpenMP and only the serial version works as expected. 
cc @gdalle

[ColPack] Recompile ColPack without OpenMP

---

L/libCppInterOpExtra/build_tarballs.jl

libCppInterOpExtra: bump version to v0.0.3

---

O/OpenMPI/OpenMPI@4/build_tarballs.jl

Companion to https://github.com/JuliaPackaging/Yggdrasil/pull/10884

OpenMPI 4: Declare Fortran libraries

---

W/Wayland/build_tarballs.jl

Also always build host tools and remove host build dependency on self.
Should solve issue #10809

[Wayland] Version 1.23.1

---

V/Vim/build_tarballs.jl
V/Vim/bundled/patches/windows_build.patch

[Vim] Add 9.1

---

M/MLX_C/build_tarballs.jl

Includes https://github.com/ml-explore/mlx-c/pull/56

[MLX_C] Updated to v0.1.2

---

C/CUDA/CUTENSOR/build_tarballs.jl

Update to the latest stable release of CUTENSOR.

CUTENSOR: Bump to 2.1.0

---

L/LLVM/Clang_unified/build_tarballs.jl
L/LLVM/LLD_unified/build_tarballs.jl
L/LLVM/MLIR@20/build_tarballs.jl

I think these are the only packages remaining that should be bumped by me, i.e. I don't think I should bump enzyme or mlir-tblgen.

[MLIR, Clang_unfied, LLD_unified] Bump to v20

---

S/SPIRV_Tools/build_tarballs.jl

SPIRV-Translator apparently relies on that.

SPIRV-Tools: Build a library for each tool.

---

C/cminpack/build_tarballs.jl

This corrects the dependency bug discussed in https://github.com/JuliaPackaging/Yggdrasil/pull/10924.

cminpack: Correct BLAS usage

---

L/libclangex/build_tarballs.jl

Update to the latest ClangCompiler.jl source.

libclangex: bump version to v0.2.0

---

L/LAMMPS/build_tarballs.jl

@vchuravy I've also changed the versioning to use Dates instead, as this is more inline with how LAMMPS does it.
What's your opinion on this?

LAMMPS: update to patch_2Apr2025

---

Z/Zenoh/build_tarballs.jl
Z/ZenohC/build_tarballs.jl

Builds a binary for the Zenoh messaging middleware.

Add recipe for Zenoh C library

---

X/Xorg_inputproto/build_tarballs.jl

This makes this package available on riscv64.

Xorg_inputproto: Switch to AnyPlatform

---

N/N2QN1/build_tarballs.jl

Hi,
I want to integrate the software N2QN1 to Ydgrassil. I test on my latpop, and it ran without errors.

N2QN1 : add a recipe V3.0

---

L/libCppInterOpExtra/build_tarballs.jl

Rebuild for libCppInterOpExtra 0.1.7

libCppInterOpExtra: bump version to 0.0.4

---

K/kdb_c_api/build_tarballs.jl

added extra compilation arguments for apple builds and updated git hash to latest

[kdb_c_api] darwin build extras

---

M/MAGEMin/build_tarballs.jl

- Added chlorite to igneous database
- Updated heat capacity unit for phases to J/kg/K
- Updated light output for geodynamic coupling
- Removed old Matlab apps

MAGEMin v1.7.4

---

B/Bun/build_tarballs.jl

This is a PR to add the [Bun](https://bun.sh/) library

[Bun] new package

---

T/TDLib/build_tarballs.jl

Rewrites the build script to follow TDLib’s documented cross-compilation flow

TDLib cross-building

---

I/IRBEM/build_tarballs.jl

add International Radiation Belt Environment Modeling (IRBEM) library

new: IRBEM

---

C/cufinufft/build_tarballs.jl
F/finufft/build_tarballs.jl

Update build scripts for both CPU and CUDA binaries

[FINUFFT] Build FINUFFT v2.4.0-rc1

---

M/MAGEMin/build_tarballs.jl

- Corrected mistake when outputting phase in mol fraction.
- Added benchmark for mol, wt, vol and densities against Theriak.
- Corrected call to wrong function leading to segfault error in some special circumstances

MAGEMin v1.7.6

---

P/pocl/build_tarballs.jl

I figured the init script wasn't horrible enough already, so here's some additional hacks.
Fixes https://github.com/JuliaGPU/OpenCL.jl/issues/303

PoCL: Expose libc to clang/lld on systems without libc-dev.

---

P/pocl/build_tarballs.jl

Rebuild POCL wrapper

---

S/SCIP_PaPILO/build_tarballs.jl

x-ref https://github.com/JuliaPackaging/Yggdrasil/pull/11164

[SCIP_PaPILO] update to GCC@12

---

O/open62541/open62541@1.4/build_tarballs.jl

Should be a straightforward patch bump.

[open62541] update to v 1.4.12

---

Z/Zenohd/build_tarballs.jl

This compiles the Zenoh router, used to connect Zenoh clients.

Buildscript for Zenoh router

---

G/gecko/build_tarballs.jl
G/gecko/bundled/geckowrapper/CMakeLists.txt
G/gecko/bundled/geckowrapper/geckowrapper.cxx

Followup for #10794 @imciner2 . Trying to expose the C++ API via CxxWrap here, analogue to https://github.com/JuliaPackaging/Yggdrasil/blob/master/S/SDPA/build_tarballs.jl .

gecko wrapper lib

---

B/bitwarden_cli/build_tarballs.jl

[bitwarden_cli] bump to version 2025.1.3

---

A/aws_lc/build_tarballs.jl

This PR updates aws_lc to version 1.52.0. cc: @quinnj @Octogonapus

[aws_lc] Update to version 1.52.0

---

S/satsuma/build_tarballs.jl
S/satsuma/bundled/patches/remove-march.patch
S/satsuma/bundled/tsl/robin_growth_policy.h
S/satsuma/bundled/tsl/robin_hash.h
S/satsuma/bundled/tsl/robin_map.h
S/satsuma/bundled/tsl/robin_set.h

Satsuma is a preprocessor for SAT problems, and implements symmetry breaking through computation of the automorphism group.
It is an executable-only package.

[satsuma] new package

---

R/ROCmDeviceLibs/ROCmDeviceLibs@6.4.1/build_tarballs.jl

This is based on https://github.com/JuliaPackaging/Yggdrasil/pull/11084/files
I'm not sure how to test if this works.
I basically found an RPM and changed the URL and SHA-256, updated version number, and change the paths to to `mv` command.
Any guidance would be aprecciated.

Add ROCmDeviceLibs 6.4.1

---

R/Reactant/build_tarballs.jl
R/Reactant/platform_augmentation.jl

@giordano @avik-pal temporarily dropping the cuda update so the other updates can unblock people

Reactant 0.0.191 : actually runs

---

O/OpenCL_Headers/build_tarballs.jl

I used the date of the commit for `version`.

Bump OpenCL_Headers

---

G/GAP_pkg/GAP_pkg_juliainterface/build_tarballs.jl

[GAP_pkg_juliainterface] Rebuild with latest libjulia

---

L/libsingular_julia/build_tarballs.jl

[libsingular] Add facstd

---

H/HiGHS/HiGHS/build_tarballs.jl
H/HiGHS/HiGHSstatic/build_tarballs.jl

[HiGHS] Trigger rebuild for 1.11 to use proper commit

---

M/MAGEMin/build_tarballs.jl

- Added function to compute the properties of metastable assemblages
- Added feasibility check when using initial guess
- Added vol% to dataframe -> csv export function

MAGEMin v1.8.0

---

A/aws_c_mqtt/build_tarballs.jl

This PR updates aws_c_mqtt to version 0.13.1. cc: @quinnj @Octogonapus

[aws_c_mqtt] Update to version 0.13.1

---

Q/Qt6QuickTimeline/build_tarballs.jl

[Qt6QuickTimeline] Add new Qt package

---

L/libjulia/common.jl

[libjulia] Split julia/libjulia supported platforms

---

P/Pythia8_cxxwrap/build_tarballs.jl

Avoid to export: copy, exp, fill, front, reset, run, size, stat

[Pythia8_cxxwrap] Removed conflictive exports

---

L/LLVMExtra/build_tarballs.jl

For https://github.com/JuliaLLVM/LLVM.jl/pull/516

LLVM: Bump LLVMExtra.

---

N/normaliz/build_tarballs.jl

[normaliz] Rebuild with FLINT 3.3.0

---

S/Singular/build_tarballs.jl

[Singular] Rebuild with FLINT 3.3.0

---

G/GAP_pkg/GAP_pkg_normalizinterface/build_tarballs.jl

[GAP_pkg_normalizinterface] Rebuild with normaliz 3.10.5

---

G/GAP_pkg/GAP_pkg_cddinterface/build_tarballs.jl

[GAP_pkg_cddinterface] Rebuild for more platforms

---

A/AcousticsToolbox/build_tarballs.jl

Version update to 2025.06.18 to include OALIB and ORCA

Update AcousticsToolbox to include Orca model

---

L/libblastrampoline/common.jl
L/libblastrampoline/libblastrampoline@5.13/build_tarballs.jl

cc @ViralBShah 
-> https://github.com/JuliaLang/julia/pull/58775

[LBT] Upgrade to v5.13.1

---

P/procps/build_tarballs.jl
P/procps/bundled/patches/clock_boottime.patch

`procps` is the project that provides many of the well known process introspection utilities like `top` and `ps` on Linux.

New recipe: procps

---

L/libclc/build_tarballs.jl
L/libclc/bundled/patches/124743.patch

Add new recipe for libclc.

---

R/rdma_core/build_tarballs.jl
R/rdma_core/bundled/patches/libibverbs_dynamic_driver.patch

[rdma_core_jll] Update to v58.0

---

C/CUDA/CUDA_Compiler/build_tarballs.jl

Fixes https://github.com/JuliaPackaging/Yggdrasil/pull/11540.

CUDA: Put the compiler version in the init block instead.

---

S/slope/build_tarballs.jl

https://github.com/jolars/libslope/compare/v2.6.0...v5.1.1

[slope] Update to 5.1.1

---

L/libcxxwrap_julia/build_tarballs.jl

Cc @barche @benlorenz @lgoettgens

[libcxxwrap-julia] rebuild against latest libjulia_jll

---

G/Gnuplot/build_tarballs.jl

Fix gnuplot 5 build (which currently fails to build).

[Gnuplot_jll] fix `Gnuplot` 5 build

---

L/libde265/build_tarballs.jl

Needed for https://github.com/JuliaPackaging/Yggdrasil/pull/11606.
Tested on all platforms locally.

add `libde265`

---

S/Skia/build_tarballs.jl
S/Skia/bundled/patches/skiapatches.patch

Added Skia library. The 2D library in use by Chrome and other web browsers

Added skia library

---

M/MPFR/MPFR@4.2.0/build_tarballs.jl

See https://github.com/JuliaPackaging/Yggdrasil/pull/11576#issuecomment-3022771553. In particular, this should add a riscv build.
cc @giordano

[MPFR@4.2.0] Rebuild after recipe splitup

---

G/GAP_pkg/GAP_pkg_normalizinterface/build_tarballs.jl

[GAP_pkg_normalizinterface] Rebuild for riscv

---

G/gismo/build_tarballs.jl

This is a version update for the Geometry + Simulation Modules (gismo), a C++ library for Isogeometric Analysis.
See https://github.com/gismo/gismo

[gismo] New Version: Geometry + Simulation Modules v25.07.0

---

L/libcxxwrap_julia/build_tarballs.jl

cc @fingolfin @barche @benlorenz

[libcxxwrap-julia] Rebuild against latest libjulia

---

I/IntelOpenMP/build_tarballs.jl

In preparation for updating MKL to 2025.2.

IntelOpenMP: Update to version 2025.2.0

---

N/NOMAD/build_tarballs.jl

- Update the version of FreeBSD
- Upgrade and pin the version of GCC compiler on Mac Silicon

[NOMAD] Upgrade to v4.5.1

---

G/GAP_pkg/GAP_pkg_juliainterface/build_tarballs.jl
G/GAP_pkg/common.jl

Reverts JuliaPackaging/Yggdrasil#11669.
cc @fingolfin 

[GAP_pkg_juliainterface] Revert recipe back to latest version

---

J/jlqml/build_tarballs.jl

[jlqml] Version 0.7.1

---

L/libblastrampoline/libblastrampoline@5.13/build_tarballs.jl

See https://github.com/JuliaPackaging/Yggdrasil/pull/11740#issuecomment-3133335266

Fix libblastrampoline julia compat for 5.13

---

O/oneAPI_Support_Headers/build_tarballs.jl

[oneAPI_Support_Headers] Upgrade to v2025.2.0

---

L/LibUnwind/LibUnwind@1.8.2/build_tarballs.jl

Motivation: https://github.com/JuliaLang/julia/issues/59171#issuecomment-3142108242

LibUnwind: enable debug_frame on all platforms

---

L/LLVM/LLVM_full@20/build_tarballs.jl
L/LLVM/LLVM_full_assert@20/build_tarballs.jl
L/LLVM/common.jl

This rebases the branch + IRCE fix

[LLVM] Build LLVM 20.1.8-0

---

C/CUDA/CUDA_Compiler/platform_augmentation.jl

Runs into https://github.com/JuliaLang/julia/issues/59257, but should still help most users.
Fixes https://github.com/JuliaGPU/CUDA.jl/issues/2839

CUDA: Respect the Runtime preferences in the Compiler JLL.

---

B/Bazel/build_tarballs.jl

[Bazel] Enable ccache

---

R/Reactant/build_tarballs.jl

Unnecessary after fixing #4067 with #11828.

[Reactant] Remove Windows hack

---

G/GAP_pkg/GAP_pkg_float/build_tarballs.jl
G/GAP_pkg/GAP_pkg_gauss/build_tarballs.jl
G/GAP_pkg/GAP_pkg_io/build_tarballs.jl
G/GAP_pkg/GAP_pkg_json/build_tarballs.jl
G/GAP_pkg/GAP_pkg_normalizinterface/build_tarballs.jl

[GAP_pkg_*] Rebuild with GAP_jll 400.1401.x, julia compat 1.10 (part 3)

---

G/GAP_pkg/GAP_pkg_orb/build_tarballs.jl
G/GAP_pkg/GAP_pkg_profiling/build_tarballs.jl
G/GAP_pkg/GAP_pkg_semigroups/build_tarballs.jl
G/GAP_pkg/GAP_pkg_zeromqinterface/build_tarballs.jl

[GAP_pkg_*] Rebuild with GAP_jll 400.1401.x, julia compat 1.10 (part 4)

---

G/GAP_pkg/GAP_pkg_guava/build_tarballs.jl
G/GAP_pkg/GAP_pkg_kbmag/build_tarballs.jl
G/GAP_pkg/GAP_pkg_nq/build_tarballs.jl
G/GAP_pkg/GAP_pkg_simpcomp/build_tarballs.jl

[GAP_pkg_*] Rebuild with julia compat 1.10 (part 6)

---

R/Reactant/build_tarballs.jl

Reactant: 0.0.231

---

P/p7zip/build_tarballs.jl

Fixes https://github.com/advisories/GHSA-gmc7-pqv9-966m

[p7zip] Update to 17.06

---

S/Singular/build_tarballs.jl

[Singular] fix highcorner

---

RootFS.md

Update compiler shard versions in docs

---

M/MAGEMin/build_tarballs.jl

- Added the Gibbs energy of the species/endmembers of solution phases to the output structure

MAGEMin v1.8.3

---

O/oneAPI_Support/build_tarballs.jl

[oneAPI_Support] Recompile the C interface

---

.github/component_owners.yml

x-ref https://github.com/JuliaPackaging/Yggdrasil/pull/11930

Clarify that component_owners must be collaborators

---

L/LAPACK/LAPACK/build_tarballs.jl
L/LAPACK/LAPACK32/build_tarballs.jl

Closes https://github.com/JuliaPackaging/Yggdrasil/issues/11923.

LAPACK: Build version 3.12.1

---

.github/component_owners.yml

Add kalmarek to component_owners.yml

---

.github/component_owners.yml

@michel2323 
Did I forget some packages?

Add the oneAPI packages in component_owners.yml

---

A/autoconf/build_tarballs.jl
A/autoconf/patches/relocatable-autoconf.patch

This updates the `autoconf` from v2.71 to v2.72.

Update autoconf version to 2.72 and fix source sha256sum

---

0_RootFS/Go/build_tarballs.jl

Like https://github.com/JuliaPackaging/Yggdrasil/pull/9267, but update to the newest.

[RootFs/Go] Update to 1.25.0

---

C/CUDA/CUDA_Compiler/build_tarballs.jl
C/CUDA/CUDA_Driver/build_tarballs.jl
C/CUDA/CUDA_Runtime/build_13.0.jl
C/CUDA/CUDA_Runtime/build_tarballs.jl

CUDA: Bump Runtime/Compiler/Driver JLLs for 13.0.1.

---

C/CUDA/cuQuantum/build_tarballs.jl

[cuQuantum] Bump version

---

L/libtakum/build_tarballs.jl

A small update that reflects a change in the automatic tests.

[libtakum] Update to v1.0.2

---

M/MAGEMin/build_tarballs.jl

- Corrected p2x amphibole function for ig, mb and mpe database
- Added list of partitioning coefficients for OL12
- Improved initial guess routine which increases performance and accuracy

MAGEMin v1.8.4

---

L/libsparseir/build_tarballs.jl

I would like to add a C++ project [libsparseir](https://github.com/SpM-lab/libsparseir).  
This libsparseir is a C++ reimplementation of Julia's [SparseIR.jl](https://github.com/SpM-lab/SparseIR.jl) implementation.
Some APIs have been optimized, making the libsparseir package worth including in your projects.

libsparseir: New package

---

S/spglib/build_tarballs.jl

See https://github.com/spglib/spglib/issues/609

Update spglib version to 2.6.0

---

T/tblis/build_tarballs.jl

This updates the tblis bindings to the latest release: https://github.com/MatthewsResearchGroup/tblis/releases/tag/v1.3.0

[tblis] Update v1.3.0

---

.github/component_owners.yml
C/CoolProp/build_tarballs.jl

This also adds @longemen3000 and myself as maintainers for the JLL.

Coolprop 7.1

---

U/Uno/build_tarballs.jl

[Uno] Upgrade to v2.1.0

---

G/GAP_pkg/common.jl
G/GAP_pkg/update.jl

This contains all the common changes from https://github.com/JuliaPackaging/Yggdrasil/pull/12032. Afterwards, each pkg needs to be updated separately with more or less the respective changes from https://github.com/JuliaPackaging/Yggdrasil/pull/12032, so this PR should not do any builds (as the follow-up PRs will do that)

[GAP_pkg_*] Update jll version scheme

---

L/libsparseir/build_tarballs.jl

libsparseir: Update to version v0.6.0

---

G/GAP_pkg/GAP_pkg_io/build_tarballs.jl

[GAP_pkg_io] Update to 4.9.3

---

G/GAP_pkg/GAP_pkg_anupq/build_tarballs.jl

[GAP_pkg_anupq] Update to 3.3.2

---

G/GAP_pkg/GAP_pkg_cddinterface/build_tarballs.jl

[GAP_pkg_cddinterface] Update to 2025.06.24

---

G/GAP_pkg/GAP_pkg_cohomolo/build_tarballs.jl

[GAP_pkg_cohomolo] Touch for updated versioning scheme

---

G/GAP_pkg/GAP_pkg_deepthought/build_tarballs.jl

[GAP_pkg_deepthought] Update to 1.0.9

---

G/GAP_pkg/GAP_pkg_digraphs/build_tarballs.jl

[GAP_pkg_digraphs] Update to 1.13.1

---

G/GAP_pkg/GAP_pkg_guava/build_tarballs.jl

[GAP_pkg_guava] Update to 3.20

---

G/GAP_pkg/GAP_pkg_normalizinterface/build_tarballs.jl

[GAP_pkg_normalizinterface] Update to 1.4.1

---

G/GAP_pkg/GAP_pkg_orb/build_tarballs.jl

[GAP_pkg_orb] Update to 5.0.1

---

G/GAP_pkg/GAP_pkg_semigroups/build_tarballs.jl

[GAP_pkg_semigroups] Update to 5.5.4

---

G/GAP_pkg/GAP_pkg_gauss/build_tarballs.jl

[GAP_pkg_gauss] Rebuild with gap 4.15.0

---

G/GAP_pkg/GAP_pkg_kbmag/build_tarballs.jl

[GAP_pkg_kbmag] Touch for new versioning scheme

---

G/GAP_pkg/GAP_pkg_simpcomp/build_tarballs.jl

[GAP_pkg_simpcomp] Touch for new versioning scheme

---

E/Electron/build_tarballs.jl

Linux and Windows are missing necessary files. 
Previous build tested at https://github.com/IanButterworth/ElectronCall.jl/pull/3
Added files:
- v8_context_snapshot.bin - V8 JavaScript engine snapshot (critical for startup performance and functionality)
- snapshot_blob.bin - V8 heap snapshot (critical)
- *.pak files - Chromium resource files:
- resources.pak - Core resources (critical)
- chrome_100_percent.pak and chrome_200_percent.pak - UI resources (critical for display)

[Electron] Include required files on linux and windows

---

E/Electron/build_tarballs.jl

Current theory for why electron is failing to start properly on linux and windows, but is working on macOS (where we just bundle the App dir) https://github.com/IanButterworth/ElectronCall.jl/actions/runs/18210569241/job/51850088518?pr=3

[Electron] Preserve directory structure

---

L/LLVM/libLLVM@21/build_tarballs.jl

[libLLVM] Build v21.1.2

---

L/libblastrampoline/common.jl
L/libblastrampoline/libblastrampoline@5.15/build_tarballs.jl

This includes a fix for Windows CI for base julia

[libblastrampoline] Bump to v5.15.0
